---
sidebar: sidebar 
permalink: ontap-security-hardening/certificate-status-protocol.html 
keywords: tr-4569, ontap hardening guide, security, certificate status, certificate, OCSP, advanced privilege level, security config ocsp enable -app name 
summary: 'O OCSP (Online Certificate Status Protocol) permite que aplicativos ONTAP que usam comunicações TLS, como LDAP ou TLS, recebam status de certificado digital quando o OCSP está ativado.' 
---
= Protocolo de estado do certificado online
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O OCSP (Online Certificate Status Protocol) permite que aplicativos ONTAP que usam comunicações TLS, como LDAP ou TLS, recebam status de certificado digital quando o OCSP está ativado. O aplicativo recebe uma resposta assinada significando que o certificado solicitado é bom, revogado ou desconhecido.

O OCSP permite determinar o status atual de um certificado digital sem exigir listas de revogação de certificados (CRLs).

Por padrão, a verificação do status do certificado OCSP está desativada. Ele pode ser ativado com o comando `security config ocsp enable -app name`, onde o nome do aplicativo pode ser `autosupport`, `audit_log`, `fabricpool` `ems` , , , `kmip`, `ldap_ad`, `ldap_nis_namemap`, `all` ou . O comando requer nível de privilégio avançado.
