---
sidebar: sidebar 
permalink: ontap-security-hardening/create-ca-signed-certificates.html 
keywords: tr-4569, ontap hardening guide, security, self-signed, digital certificates, CA-signed digital certificates, generate-csr, security certificate install 
summary: Crie um certificado digital assinado pela CA para uso na autenticação do cluster ou SVM como um servidor SSL. 
---
= Crie um certificado digital assinado pela CA
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para muitas organizações, o certificado digital auto-assinado para o acesso à Web ONTAP não é compatível com suas políticas INFOSEC. Em sistemas de produção, é uma prática recomendada do NetApp instalar um certificado digital assinado pela CA para uso na autenticação do cluster ou SVM como um servidor SSL.

Você pode usar o `security certificate generate-csr` comando para gerar uma solicitação de assinatura de certificado (CSR) e o `security certificate install` comando para instalar o certificado recebido de volta da CA.

.Passos
. Para criar um certificado digital assinado pela CA da organização, faça o seguinte:
+
.. Gerar um CSR.
.. Siga o procedimento da sua organização para solicitar um certificado digital usando a CSR da CA da sua organização. Por exemplo, usando a interface da Web do Microsoft ative Directory Certificate Services, vá para `<CA_server_name>/certsrv` e solicite um certificado.
.. Instale o certificado digital no ONTAP.



