---
sidebar: sidebar 
permalink: ontap-security-hardening/enable-ldap-signing-sealing.html 
keywords: tr-4569, ontap hardening guide, security, queries, LDAP server, none, sign, seal 
summary: A assinatura e a selagem do protocolo Lightweight Directory Access permitem a segurança da sessão em consultas a um servidor LDAP. 
---
= Ative a assinatura e a vedação do protocolo Lightweight Directory Access
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media


[role="lead"]
Assinatura e selagem são suportados para habilitar a segurança da sessão em consultas a um servidor LDAP. Essa abordagem fornece uma alternativa à segurança de sessão LDAP-over-TLS.

A assinatura confirma a integridade dos dados de carga útil LDAP usando tecnologia de chave secreta. A vedação criptografa os dados de carga útil LDAP para evitar a transmissão de informações confidenciais em texto não criptografado. As configurações de segurança de sessão em um SVM correspondem às disponíveis no servidor LDAP. Por padrão, a assinatura e a vedação LDAP são desativadas.

.Passos
. Para ativar esta função, execute o `vserver cifs security modify` comando com o `session-security-for-ad-ldap` parâmetro.
+
Opções para funções de segurança LDAP:

+
** *Nenhum*: Padrão, sem assinatura ou vedação
** *Sign*: Assine o tráfego LDAP
** *Seal*: Assine e criptografe o tráfego LDAP
+

NOTE: Os parâmetros de sinal e selo são cumulativos, o que significa que, se a opção de sinal for usada, o resultado será LDAP com assinatura. No entanto, se a opção de vedação for usada, o resultado será sinal e selo. Além disso, se um parâmetro não for especificado para esse comando, o padrão será nenhum.

+
O seguinte é um exemplo de configuração:

+
[listing]
----
cluster1::> vserver cifs security modify -vserver vs1 -kerberos-clock-skew 3 -kerberos-ticket-age 8 -session-security-for-ad-ldap seal
----



