---
sidebar: sidebar 
permalink: ontap-security-hardening/lif-security.html 
keywords: tr-4569, ontap hardening guide, Data LIF, Cluster LIF, Node management LIF, Cluster management LIF, Intercluster LIF, requires private IP subnet, requires secure network, default firewall policy, is the firewall customizable, under no circumstance should any LIF roles be exposed to the internet 
summary: Entenda as caraterísticas de segurança de cada função de LIF. 
---
= Caraterísticas de segurança das funções de LIF no ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Um LIF é um endereço IP ou nome de porta mundial (WWPN) com caraterísticas associadas, como uma função, uma porta inicial, um nó inicial, uma lista de portas para failover e uma política de firewall. Você pode configurar LIFs em portas pelas quais o cluster envia e recebe comunicações pela rede. É fundamental entender as caraterísticas de segurança de cada função de LIF.



== Funções do LIF

As funções de LIF podem ser as seguintes:

* *Data LIF*: Um LIF associado a um SVM e usado para comunicação com clientes.
* *Cluster LIF*: Um LIF usado para transportar tráfego entre nós em um cluster.
* *LIF de gerenciamento de nós*: Um LIF que fornece um endereço IP dedicado para gerenciar um nó específico em um cluster.
* *Cluster Management LIF*: Um LIF que fornece uma única interface de gerenciamento para todo o cluster.
* *Intercluster LIF*: Um LIF usado para comunicação entre clusters, backup e replicação.




== Caraterísticas de segurança de cada função de LIF

[cols="21%,13%,14%,18%,18%,16%"]
|===
|  | LIF de dados | LIF de cluster | LIF de gerenciamento de nós | LIF de gerenciamento de clusters | LIF entre clusters 


| Requer sub-rede IP privada? | Não | Sim | Não | Não | Não 


| Requer rede segura? | Não | Sim | Não | Não | Sim 


| Política de firewall predefinida | Muito restritivo | Completamente aberto | Média | Média | Muito restritivo 


| O firewall é personalizável? | Sim | Não | Sim | Sim | Sim 
|===
[IMPORTANT]
====
* Como o LIF do cluster está completamente aberto sem política de firewall configurável, ele deve estar em uma sub-rede IP privada em uma rede segura isolada.
* As funções de LIF nunca devem ser expostas à Internet.


====
Saiba mais sobre como proteger LIFs, consulte link:../networking/configure_firewall_policies_for_lifs.html["Configurar políticas de firewall para LIFs"].
