---
sidebar: sidebar 
permalink: ontap-security-hardening/oauth20-token-based-auth-for-rest-api.html 
keywords: tr-4569, ontap hardening guide, security, access, oauth, oauth 2.0, token based authentication, rest api, tokens 
summary: Os tokens OAuth 2,0 substituem senhas para autenticação de conta de usuário. 
---
= Autenticação baseada em token ONTAP OAuth 2,0 para API REST
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Como alternativa à autenticação baseada em certificado, você pode usar a autenticação baseada em token OAuth 2,0 para API REST.

A partir do ONTAP 9.14,1, você tem a opção de controlar o acesso aos clusters do ONTAP usando a estrutura autorização aberta (OAuth 2,0). Você pode configurar esse recurso usando qualquer uma das interfaces administrativas do ONTAP, incluindo a CLI do ONTAP, o Gerenciador do sistema e a API REST. No entanto, as decisões de autorização e controle de acesso do OAuth 2,0 só podem ser aplicadas quando um cliente acessa o ONTAP usando a API REST.

Os tokens OAuth 2,0 substituem senhas para autenticação de conta de usuário.

Para obter mais informações sobre como usar o OAuth 2,0, consulte link:../authentication/overview-oauth2.html["Documentação do ONTAP sobre autenticação e autorização usando OAuth 2,0"].
