---
sidebar: sidebar 
permalink: ontap-security-hardening/security-hardening-overview.html 
keywords: tr-4569, ontap hardening guide, security, threats, threat landscape, hardening guide, introduction 
summary: Use este guia para o ONTAP para ajudar sua organização a atender aos objetivos de segurança prescritos para confidencialidade, integridade e disponibilidade do sistema de informações. 
---
= Visão geral do fortalecimento da segurança do ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media


[role="lead"]
O ONTAP fornece um conjunto de controles que permitem proteger o sistema operacional de storage ONTAP, o software de gerenciamento de dados líder do setor. Use as orientações e as configurações do ONTAP para ajudar sua organização a cumprir os objetivos de segurança prescritos para confidencialidade, integridade e disponibilidade do sistema de informações.

A evolução do cenário atual de ameaças apresenta uma organização com desafios únicos para proteger seus ativos mais valiosos: Dados e informações. As ameaças e vulnerabilidades avançadas e dinâmicas que enfrentamos estão cada vez mais aumentando em sofisticação. Juntamente com um aumento na eficácia das técnicas de ofuscação e reconhecimento por parte de potenciais intrusos, os gestores de sistemas devem abordar a segurança de dados e informações de forma proativa.


NOTE: A partir de julho de 2024, o conteúdo de relatórios técnicos publicados anteriormente como PDFs foi integrado à documentação do produto ONTAP. A documentação de segurança do ONTAP agora inclui conteúdo de _TR-4569: Guia de proteção de segurança para ONTAP_.
