---
sidebar: sidebar 
permalink: ontap-security-hardening/snapshot-copy-locking.html 
keywords: tr-4569, ontap hardening guide,security, snapshot copy locking, tamper-proof snapshot, tamperproof, tamper proof 
summary: O bloqueio de cópias snapshot impede a exclusão de cópias snapshot usando a tecnologia SnapLock. 
---
= Bloqueio de cópias snapshot
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O bloqueio de cópias snapshot é uma funcionalidade do SnapLock em que as cópias Snapshot são tornadas indeléveis manual ou automaticamente, com um período de retenção na política de Snapshot de volume. O objetivo do bloqueio de cópias Snapshot é impedir que administradores desonestos ou não confiáveis excluam snapshots em sistemas ONTAP primário ou secundário.

O bloqueio de cópia Snapshot foi introduzido no ONTAP 9.12,1. O bloqueio de cópias snapshot também é conhecido como bloqueio instantâneo à prova de violação. Embora isso exija a licença SnapLock e a inicialização do relógio de conformidade, o bloqueio de cópias snapshot não está relacionado ao SnapLock Compliance ou ao SnapLock Enterprise. Não há administrador de storage confiável, assim como o SnapLock Enterprise e ele não protege a infraestrutura de storage físico subjacente, como o SnapLock Compliance. Isso é uma melhoria em relação às cópias Snapshot do SnapVaulting para um sistema secundário. A recuperação rápida de snapshots bloqueados em sistemas primários pode ser obtida para restaurar volumes corrompidos por ransomware.

Para obter mais detalhes sobre o bloqueio de cópias instantâneas, consulte link:../snaplock/snapshot-lock-concept.html["Documentação do ONTAP"].
