---
sidebar: sidebar 
permalink: ontap-security-hardening/snapshot-copy-locking.html 
keywords: tr-4569, ontap hardening guide,security, snapshot copy locking, tamper-proof snapshot, tamperproof, tamper proof 
summary: O bloqueio de snapshot impede a exclusão de snapshot usando a tecnologia SnapLock. 
---
= Bloqueio instantâneo
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O bloqueio de snapshot é um recurso do SnapLock no qual os snapshots são tornados indeléveis manual ou automaticamente com um período de retenção na política de snapshot de volume. O objetivo do bloqueio de snapshot é impedir que administradores desonestos ou não confiáveis excluam snapshots no sistema ONTAP primário ou secundário.

O bloqueio instantâneo foi introduzido no ONTAP 9.12.1. O bloqueio de snapshot também é conhecido como bloqueio de snapshot à prova de violação. Embora exija a licença SnapLock e a inicialização do relógio de conformidade, o bloqueio de instantâneos não está relacionado ao SnapLock Compliance ou ao SnapLock Enterprise. Não há administrador de storage confiável, assim como o SnapLock Enterprise e ele não protege a infraestrutura de storage físico subjacente, como o SnapLock Compliance. Essa é uma melhoria em relação aos snapshots SnapVaulting para um sistema secundário. A recuperação rápida de snapshots bloqueados em sistemas primários pode ser obtida para restaurar volumes corrompidos por ransomware.

Para obter mais detalhes, consulte link:../snaplock/snapshot-lock-concept.html["documentação de bloqueio de instantâneos"].
