---
sidebar: sidebar 
permalink: ontap-security-hardening/sshv2.html 
keywords: tr-4569, ontap hardening guide, security, security ssh modify, SSH key exchange algorithms, SSH ciphers, SSH MAC algorithms, passwords for user sessions, public key for machine access 
summary: Substitua as configurações existentes de algoritmos de troca de chaves SSH, cifras ou algoritmos MAC para o cluster ou um SVM com as configurações especificadas. 
---
= Gerenciamento do SSHv2
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O `security ssh modify` comando substitui as configurações existentes dos algoritmos de troca de chaves SSH, cifras ou algoritmos MAC para o cluster ou um SVM com as configurações especificadas.

[TIP]
====
A NetApp recomenda o seguinte:

* Use senhas para sessões de usuário.
* Use uma chave pública para acesso à máquina.


====


== Cifras suportadas e trocas de chaves

[cols="42%,58%"]
|===
| Cifras | Troca de chaves 


| aes256-ctr | diffie-hellman-group-Exchange-sha256 (SHA-2) 


| aes192-ctr | diffie-hellman-group-Exchange-SHA1 (SHA-1) 


| aes128-ctr | diffie-hellman-group14-SHA1 (SHA-1) 


| aes256-cbc | diffie-hellman-group1-SHA1 (SHA-1) 


| aes192-cbc | - 


| aes128-cbc | - 


| aes128-gcm | - 


| aes256-gcm | - 


| 3des-cbc | - 
|===


== Criptografia simétrica AES e 3DES suportada

O ONTAP também suporta os seguintes tipos de criptografia simétrica AES e 3DES (também conhecidos como cifras):

* hmac-sha1
* hmac-sha1-96
* hmac-md5
* hmac-md5-96
* hmac-ripemd160
* umac-64
* umac-64
* umac-128
* hmac-sha2-256
* hmac-sha2-512
* hmac-sha1-etm
* hmac-sha1-96-etm
* hmac-sha2-256-etm
* hmac-sha2-512-etm
* hmac-md5-etm
* hmac-md5-96-etm
* hmac-ripemd160-etm
* umac-64-etm
* umac-128-etm



NOTE: A configuração de gerenciamento SSH se aplica ao ONTAP e à plataforma BMC.
