---
sidebar: sidebar 
permalink: authentication-access-control/webauthn-mfa-overview.html 
keywords: mfa, multi-factor, authentication, authorization, webauthn, FIDO2, hardware key 
summary: A partir do ONTAP 9.16,1, você pode ativar o WebAuthn MFA para usuários do ONTAP. 
---
= Visão geral da autenticação multifator WebAuthn
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A partir do ONTAP 9.16,1, os administradores podem ativar a autenticação multifator WebAuthn (MFA) para usuários que fazem login no Gerenciador de sistema. Isso permite logins do System Manager usando uma chave FIDO2 (como uma YubiKey) como uma segunda forma de autenticação. Por padrão, o WebAuthn MFA está desativado para usuários novos e existentes do ONTAP.

O WebAuthn MFA é compatível com usuários e grupos que usam os seguintes tipos de autenticação para o primeiro método de autenticação:

* Usuários: Senha, domínio ou nsswitch
* Grupos: Domínio ou nsswitch


Depois de ativar o WebAuthn MFA como o segundo método de autenticação para um usuário, o usuário é solicitado a Registrar um autenticador de hardware ao fazer login no System Manager. Após o Registro, a chave privada é armazenada no autenticador e a chave pública é armazenada no ONTAP.

O ONTAP suporta uma credencial WebAuthn por usuário. Se um usuário perder um autenticador e precisar substituí-lo, o administrador do ONTAP precisará excluir a credencial WebAuthn do usuário para que o usuário possa Registrar um novo autenticador no próximo login.


NOTE: Os usuários que têm o WebAuthn MFA habilitado como um segundo método de autenticação precisam usar o FQDN (por exemplo, "https://myontap.example.com"[]) em vez do endereço IP (por exemplo, "https://192.168.100.200"[]) para acessar o System Manager. Para usuários com WebAuthn MFA habilitado, as tentativas de fazer login no System Manager usando o endereço IP são rejeitadas.
