---
sidebar: sidebar 
permalink: ransomware-solutions/ransomware-snaplock-tamperproof-snapshots.html 
keywords: tr-4572, technical report, ransomware, protect, protection, netapp ransomware protection, netapp tr, ontap tr 
summary: A proteção contra ransomware do NetApp inclui o SnapLock, que provou ser altamente eficaz na proteção contra ameaças de ransomware. 
---
= Cópias snapshot à prova de SnapLock e invioláveis para proteção de ransomware
:allow-uri-read: 


[role="lead"]
Uma arma vital no arsenal de NetApp Snap é o SnapLock, que provou ser altamente eficaz na proteção contra ameaças de ransomware. Ao impedir a exclusão não autorizada de dados, o SnapLock fornece uma camada adicional de segurança, garantindo que os dados críticos permaneçam intactos e acessíveis, mesmo em caso de ataques mal-intencionados.



== SnapLock Compliance

O SnapLock Compliance (SLC) fornece proteção indelével para seus dados. O SLC proíbe que os dados sejam excluídos mesmo quando um administrador tenta reinicializar a matriz. Ao contrário de outros produtos competitivos, o SnapLock Compliance não é vulnerável a ataques de engenharia social por meio das equipes de suporte desses produtos. Os dados protegidos por volumes do SnapLock Compliance são recuperáveis até que esses dados atinjam a data de expiração.

Para ativar o SnapLock, é necessária uma link:../system-admin/manage-licenses-concept.html["ONTAP One"] licença.

.Saiba mais
* link:../snaplock/index.html["Documentação do SnapLock"]




== Cópias Snapshot à prova de violações

As cópias Snapshot (TPS) à prova de violações fornecem uma maneira conveniente e rápida de proteger os dados de atos maliciosos. Ao contrário do SnapLock Compliance, o TPS é normalmente usado em sistemas primários onde o usuário pode proteger os dados por um determinado tempo e deixado localmente para recuperações rápidas ou onde os dados não precisam ser replicados fora do sistema primário. O TPS usa tecnologias SnapLock para impedir que a cópia snapshot principal seja excluída, mesmo por um administrador do ONTAP que use o mesmo período de expiração de retenção do SnapLock. A exclusão de cópias snapshot é impedida mesmo que o volume não esteja habilitado para SnapLock, embora os snapshots não tenham a mesma natureza indelével dos volumes SnapLock Compliance.

Para fazer cópias snapshot à prova de violações, é necessária uma link:../system-admin/manage-licenses-concept.html["ONTAP One"] licença.

.Saiba mais
* link:../snaplock/snapshot-lock-concept.html["Bloqueie uma cópia snapshot para proteção contra ataques de ransomware"].

