---
permalink: s3-config/create-s3-service-data-policy-task.html 
sidebar: sidebar 
keywords: create, s3, service, data, policy 
summary: Você pode criar políticas de serviço para dados e serviços de gerenciamento do S3. É necessária uma política de dados de serviço S3 para permitir o tráfego de dados S3 nos LIFs. 
---
= Crie a política de dados de serviço do ONTAP S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode criar políticas de serviço para dados e serviços de gerenciamento do S3. É necessária uma política de dados de serviço S3 para permitir o tráfego de dados S3 nos LIFs.

.Sobre esta tarefa
Uma política de dados de serviço S3 é necessária se você estiver usando LIFs de dados e LIFs entre clusters. Não é necessário se você estiver usando LIFs de cluster para o caso de uso de disposição em camadas local.

Quando uma política de serviço é especificada para um LIF, a política é usada para criar uma função padrão, política de failover e lista de protocolos de dados para o LIF.

Embora vários protocolos possam ser configurados para SVMs e LIFs, é uma prática recomendada para S3 ser o único protocolo ao fornecer dados de objetos.

.Passos
. Altere a configuração de privilégios para avançado:
+
`set -privilege advanced`

. Criar uma política de dados de serviço:
+
`network interface service-policy create -vserver _svm_name_ -policy _policy_name_ -services data-core,data-s3-server`

+
Os `data-core` serviços e `data-s3-server` são os únicos necessários para habilitar o ONTAP S3, embora outros serviços possam ser incluídos conforme necessário.


