---
permalink: s3-config/enable-ontap-s3-access-remote-fabricpool-task.html 
sidebar: sidebar 
keywords: enable, ontap s3, access, remote, fabricpool tiering 
summary: 'Para que o ONTAP S3 seja usado como um nível de capacidade remota de FabricPool (nuvem), o administrador do ONTAP S3 deve fornecer informações sobre a configuração do servidor S3 para o administrador remoto do cluster do ONTAP.' 
---
= Habilite o acesso ao ONTAP S3 para disposição remota de FabricPool em camadas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para que o ONTAP S3 seja usado como um nível de capacidade remota de FabricPool (nuvem), o administrador do ONTAP S3 deve fornecer informações sobre a configuração do servidor S3 para o administrador remoto do cluster do ONTAP.

.Sobre esta tarefa
As seguintes informações do servidor S3 são necessárias para configurar as camadas de nuvem do FabricPool:

* Nome do servidor (FQDN)
* nome do intervalo
* Certificado CA
* chave de acesso
* palavra-passe (chave de acesso secreta)


Além disso, é necessária a seguinte configuração de rede:

* Deve haver uma entrada para o nome do host do servidor ONTAP S3 remoto no servidor DNS configurado para o SVM admin, incluindo o nome FQDN do servidor S3 e os endereços IP em seus LIFs.
* As LIFs de clusters devem ser configuradas no cluster local, embora o peering de cluster não seja necessário.


Consulte a documentação do FabricPool sobre como configurar o ONTAP S3 como uma camada de nuvem.

link:../fabricpool/index.html["Gerenciamento de camadas de storage usando o FabricPool"]
