---
permalink: s3-config/ontap-s3-supported-actions-reference.html 
sidebar: sidebar 
keywords: ontap s3, supported, actions 
summary: Ações compatíveis com o ONTAP S3. 
---
= Ações compatíveis com o ONTAP S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As ações do ONTAP S3 são compatíveis com APIs REST S3 padrão, exceto conforme indicado abaixo. Para obter detalhes, consulte link:https://docs.aws.amazon.com/AmazonS3/latest/API/Type_API_Reference.html["Referência de API do Amazon S3"^].


NOTE: Essas S3 ações são suportadas especificamente ao usar buckets S3 nativos no ONTAP. Algumas dessas ações, como as associadas ao controle de versão, bloqueios de objetos e outros recursos, não são suportadas ao usar link:../s3-multiprotocol/index.html["S3 buckets nas (S3 em volumes nas multiprotocolo)"]o .

A menos que seja indicado para uma operação específica, os seguintes cabeçalhos de solicitação comuns são suportados a partir do ONTAP 9.8:

* `Authorization`
* `Connection`
* `Content-Length`
* `Content-MD5`
* `Content-Type`
* `Date`
* `Expect`
* `Host`
* `x-amz-date`




== Operações do balde

As operações a seguir são suportadas no ONTAP usando APIs AWS S3:

|===
| Funcionamento do balde | Suporte ONTAP começando com 


 a| 
CreateBucket

O ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação, além deste cabeçalho adicional:

* `x-amz-bucket-object-lock-enabled`

| ONTAP 9.11,1 


 a| 
DeleteBucket

O ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação.
| ONTAP 9.11,1 


| DeleteBucketCors ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação. | ONTAP 9,8 


| DeleteBucketLifecycle ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação. | ONTAP 9,8 


 a| 
DeleteBucketPolicy

O ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação.
| ONTAP 9.12,1 


| O GetBucketAcl ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação. | ONTAP 9,8 


| GetBucketCors ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação. | ONTAP 9,8 


 a| 
GetBucketLifecycleConfiguration

O ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação.
 a| 
ONTAP 9.13,1

*Somente ações de expiração são suportadas



| GetBucketLocation ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação. | ONTAP 9.10,1 


| GetBucketPolicy ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação. | ONTAP 9.12,1 


| O GetBucketVersioning ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação. | ONTAP 9.11,1 


| O HeadBucket ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação. | ONTAP 9,8 


| O ListAllMyBuckets ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação. | ONTAP 9,8 


| O ListBuckets ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação. | ONTAP 9,8 


| ListBucketVersions ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação. | ONTAP 9.11,1 


| PutBucket  a| 
* ONTAP 9.11,1
* ONTAP 9.8 - compatível apenas com APIs REST do ONTAP




| PutBucketCors ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação.  a| 
ONTAP 9,8



| PutBucketLifecycleConfiguration ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação. | ONTAP 9.13.1 * somente ações de expiração são suportadas 


| PutBucketPolicy ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação. | ONTAP 9.12,1 


| PutBucketVersioning ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação. | ONTAP 9.11,1 
|===


== Operações de objetos

A partir do ONTAP 9.9,1, o ONTAP S3 oferece suporte a metadados e marcação de objetos.

* PutObject e CreateMultipartUpload incluem pares de chave-valor usando `x-amz-meta-<key>.`
+
Por exemplo `x-amz-meta-project: ontap_s3`: .

* GetObject e HeadObject retornam metadados definidos pelo usuário.
* Ao contrário dos metadados, as tags podem ser lidas independentemente dos objetos usando:
+
** Marcação de objetos
** GetObjectTagging
** DeleteObjectTagging




A partir do ONTAP 9.11,1, o ONTAP S3 oferece suporte ao controle de versão de objetos e às ações associadas a essas APIs do ONTAP:

* GetBucketControle de versão
* ListBucketVersions
* PutBucketControle de versão


A menos que seja indicado para uma operação específica, os seguintes parâmetros de consulta de URI são suportados:

* `versionId`(conforme exigido para operações de objetos começando com ONTAP 9.12.1)


|===
| Operação do objeto | Suporte ONTAP começando com 


 a| 
AbortMultipartUpload

O ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação, além deste parâmetro de consulta URI adicional:
`uploadId`
 a| 
ONTAP 9,8



 a| 
CompleteMultipartUpload

O ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação, além deste parâmetro de consulta URI adicional:
`uploadId`
 a| 
ONTAP 9,8



 a| 
CopyObject

O ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação, além destes cabeçalhos adicionais:

* `x-amz-copy-source`
* `x-amz-copy-source-if-match`
* `x-amz-copy-source-if-modified-since`
* `x-amz-copy-source-if-none-match`
* `x-amz-copy-source-if-unmodified-since`
* `x-amz-metadata-directive`
* `x-amz-object-lock-mode`
* `x-amz-object-lock-retain-until-date`
* `x-amz-tagging`
* `x-amz-tagging-directive`
* `x-amz-meta-<metadata-name>`

| ONTAP 9.12,1 


 a| 
CreateMultipartUpload

O ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação, além destes cabeçalhos adicionais:

* `Cache-Control`
* `Content-Disposition`
* `Content-Encoding`
* `Content-Language`
* `Expires`
* `x-amz-tagging`
* `x-amz-object-lock-mode`
* `x-amz-object-lock-retain-until-date`
* `x-amz-meta-<metadata-name>`

| ONTAP 9,8 


 a| 
DeleteObject

O ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação, além deste cabeçalho adicional:

* `x-amz-bypass-governance-retention`

| ONTAP 9,8 


| DeleteObjects ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação, além deste cabeçalho adicional: * `x-amz-bypass-governance-retention` | ONTAP 9.11,1 


 a| 
DeleteObjectTagging

O ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação.
| ONTAP 9.9,1 


 a| 
GetObject

O ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação, além destes parâmetros de consulta URI adicionais:

* `partNumber`
* `response-cache-control`
* `response-content-disposition`
* `response-content-encoding`
* `response-content-language`
* `response-content-type`
* `response-expires`


E este cabeçalho de solicitação adicional:

* Alcance

| ONTAP 9,8 


| GetObjectAcl ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação. | ONTAP 9,8 


 a| 
ObterAtributosDeObjeto

O ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação, além deste cabeçalho adicional:

* `x-amz-object-attributes`

| ONTAP 9.17.1 


| GetObjectRetention ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação. | ONTAP 9.14,1 


| O GetObjectTagging ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação. | ONTAP 9.9,1 


| O HeadObject ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação. | ONTAP 9,8 


 a| 
ListMultipartUpload

O ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação, além destes parâmetros URI adicionais:

* `delimiter`
* `key-marker`
* `max-uploads`
* `prefix`
* `upload-id-marker`

| ONTAP 9,8 


 a| 
ListObjects

O ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação, além destes parâmetros URI adicionais:

* `delimiter`
* `encoding-type`
* `marker`
* `max-keys`
* `prefix`

| ONTAP 9,8 


 a| 
ListObjectsV2

O ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação, além destes parâmetros URI adicionais:

* `continuation-token`
* `delimiter`
* `encoding-type`
* `fetch-owner`
* `max-keys`
* `prefix`
* `start-after`

| ONTAP 9,8 


 a| 
ListObjectVersions

O ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação, além destes parâmetros URI adicionais:

* `delimiter`
* `encoding-type`
* `key-marker`
* `max-keys`
* `prefix`
* `version-id-marker`

| ONTAP 9.11,1 


 a| 
ListParts

O ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação, além destes parâmetros URI adicionais:

* `max-parts`
* `part-number-marker`
* `uploadId`

| ONTAP 9,8 


 a| 
PutObject

O ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação, além destes cabeçalhos adicionais:

* `Cache-Control`
* `Content-Disposition`
* `Content-Encoding`
* `Content-Language`
* `Expires`
* `x-amz-tagging`
* `x-amz-object-lock-mode`
* `x-amz-object-lock-retain-until-date`
* `x-amz-meta-<metadata-name>`

| ONTAP 9,8 


| PutObjectLockConfiguration ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação. | ONTAP 9.14,1 


 a| 
Retenção PutObjectRetention

O ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação, além deste cabeçalho adicional:

* `x-amz-bypass-governance-retention`

| ONTAP 9.14,1 


| PutObjectTagging ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação. | ONTAP 9.9,1 


| UploadPart | ONTAP 9,8 


 a| 
UploadPartCopy

O ONTAP S3 suporta todos os parâmetros e cabeçalhos comuns para esta solicitação, além destes parâmetros URI adicionais:

* `partNumber`
* `uploadId`


E estes cabeçalhos de solicitação adicionais:

* `x-amz-copy-source`
* `x-amz-copy-source-if-match`
* `x-amz-copy-source-if-modified-since`
* `x-amz-copy-source-if-none-match`
* `x-amz-copy-source-if-unmodified-since`
* `x-amz-copy-source-range`

| ONTAP 9.12,1 
|===


== Políticas de grupo

Essas operações não são específicas do S3 e geralmente estão associadas a processos de identidade e gerenciamento (IAM). O ONTAP é compatível com esses comandos, mas não usa as APIs REST do IAM.

* Criar política
* Política do AttachGroup




== Gerenciamento de usuários

Essas operações não são específicas do S3 e geralmente estão associadas aos processos do IAM.

* CreateUser
* DeleteUser
* CreateGroup
* DeleteGroup




== S3 ações por liberação

.ONTAP 9.14,1
ONTAP 9.14,1 adiciona suporte para bloqueio de objetos S3.


NOTE: Operações de retenção legal (bloqueios sem tempos de retenção definidos) não são suportadas.

* GetObjectLockConfiguration
* GetObjectRetention
* PutObjectLockConfiguration
* Retenção PutObjectRetention


.ONTAP 9.13,1
O ONTAP 9.13,1 adiciona suporte ao gerenciamento do ciclo de vida do bucket.

* DeleteBucketLifecycleConfiguration
* GetBucketLifecycleConfiguration
* PutBucketLifecycleConfiguration


.ONTAP 9.12,1
O ONTAP 9.12,1 adiciona suporte a políticas de bucket e a capacidade de copiar objetos.

* DeleteBucketPolicy
* Política de GetBucketPolicy
* Política de PutBucketPolicy
* CopyObject
* UploadPartCopy


.ONTAP 9.11,1
O ONTAP 9.11,1 adiciona suporte para versionamento, URLs pré-assinados, uploads em grupo e suporte para ações S3 comuns, como criar e excluir buckets usando APIs do S3.

* ONTAP S3 agora oferece suporte a solicitações de assinatura de uploads em blocos usando `x-amz-content-sha256:
STREAMING-AWS4-HMAC-SHA256-PAYLOAD`
* O ONTAP S3 agora oferece suporte a aplicativos clientes usando URLs pré-assinados para compartilhar objetos ou permitir que outros usuários façam upload de objetos sem exigir credenciais de usuário.
* CreateBucket
* DeleteBucket
* GetBucketControle de versão
* ListBucketVersions
* PutBucket
* PutBucketControle de versão
* DeleteObjects
* ListObjectVersions



NOTE: Como o FlexGroup subjacente não é criado até que o primeiro bucket seja, um bucket deve ser criado no ONTAP antes que um cliente externo possa criar um bucket usando o CreateBucket.

.ONTAP 9.10,1
ONTAP 9.10,1 adiciona suporte para SnapMirror S3 e GetBucketLocation.

* GetBucketlocalização


.ONTAP 9.9,1
O ONTAP 9.9,1 adiciona suporte para metadados de objetos e suporte a marcação ao ONTAP S3.

* PutObject e CreateMultipartUpload agora incluem pares de chave-valor usando `x-amz-meta-<key>`. Por exemplo `x-amz-meta-project: ontap_s3`: .
* GetObject e HeadObject agora retornam metadados definidos pelo usuário.


Tags também podem ser usadas com baldes. Ao contrário dos metadados, as tags podem ser lidas independentemente dos objetos usando:

* Marcação de objetos
* GetObjectTagging
* DeleteObjectTagging

