---
permalink: s3-config/ontap-version-support-s3-concept.html 
sidebar: sidebar 
keywords: tr-4814, ontap, version, support, s3, object, storage, AWS S3, Azure S3, cloud volumes ontap, aws, azure 
summary: O ONTAP dá suporte ao storage de objetos S3 para ambientes locais a partir do ONTAP 9.8. O Cloud Volumes ONTAP dá suporte ao storage de objetos S3 para ambientes de nuvem a partir do ONTAP 9.9,1. 
---
= Suporte à versão do ONTAP para storage de objetos S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O storage de objetos do S3 é compatível com todas as plataformas AFF, FAS e ONTAP Select usando o ONTAP 9.8 e posterior.

Assim como em outros protocolos, como FC, iSCSI, NFS, NVMe_of e SMB, o S3 requer a instalação de uma licença antes que ela possa ser usada no ONTAP. A licença S3 é uma licença de custo zero, mas deve ser instalada em sistemas que estejam atualizando para o ONTAP 9.8. A licença S3 pode ser transferida a partir do link:https://mysupport.netapp.com/site/systems/master-license-keys/ontaps3["Página chaves de licença principal"^]no site de suporte da NetApp.

Os novos sistemas ONTAP 9.8 e posteriores têm a licença S3 pré-instalada.



== Cloud Volumes ONTAP

O ONTAP S3 é configurado e funciona da mesma forma no Cloud Volumes ONTAP que em ambientes locais, com uma exceção:

* Ao criar buckets no Cloud Volumes ONTAP, você deve usar o procedimento de CLI para garantir que o volume FlexGroup subjacente use apenas agregados de um único nó. O uso de agregados de vários nós afetará o desempenho porque os nós estarão em zonas de disponibilidade geograficamente separadas e suscetíveis a problemas de latência.


|===
| Fornecedor de nuvem | Versão de ONTAP 


| Azure | ONTAP 9.9,1 e posterior 


| AWS | ONTAP 9.11,0 e posterior 


| Google Cloud | ONTAP 9.12,1 e posterior 
|===


== Amazon FSX para NetApp ONTAP

O armazenamento de objetos S3 é compatível com os serviços do Amazon FSX for NetApp usando o ONTAP 9.11 e posterior.



== Suporte S3 com MetroCluster

A partir do ONTAP 9.14,1, é possível habilitar um servidor de storage de objetos S3 em uma SVM em um agregado espelhado em configurações IP e FC do MetroCluster.

A partir do ONTAP 9.12,1, é possível habilitar um servidor de storage de objetos S3 em uma SVM em um agregado sem espelhamento em uma configuração IP do MetroCluster. Para obter mais informações sobre as limitações de agregados sem espelhamento em configurações MetroCluster IP, link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/considerations_unmirrored_aggrs.html["Considerações para agregados sem espelhamento"^]consulte .



== S3 visualização pública no ONTAP 9.7

No ONTAP 9.7, o armazenamento de objetos S3 foi introduzido como uma prévia pública. Essa versão não foi destinada a ambientes de produção e não será mais atualizada a partir do ONTAP 9.8. Somente as versões do ONTAP 9.8 e posteriores são compatíveis com storage de objetos do S3 em ambientes de produção.

Os buckets do S3 criados com a visualização pública do 9,7 podem ser usados no ONTAP 9.8 e posterior, mas não podem aproveitar os aprimoramentos de recursos. Se você tiver buckets criados com a visualização pública do 9,7, migre o conteúdo desses buckets para buckets do 9,8 para oferecer suporte a recursos, segurança e melhorias de desempenho.
