---
permalink: nfs-trunking/prepare-network-task.html 
sidebar: sidebar 
keywords: NFS, servers, network, prepare, NFS trunking, LIF, trunking group, NIC 
summary: Para aproveitar o entroncamento NFSv4,1, os LIFs em um grupo de entroncamento devem residir no mesmo nó e ter portas iniciais no mesmo nó. . 
---
= Prepare sua rede para o entroncamento de NFS do ONTAP
:allow-uri-read: 


[role="lead"]
Para aproveitar o entroncamento NFSv4,1, os LIFs em um grupo de entroncamento devem residir no mesmo nó e ter portas iniciais no mesmo nó. As LIFs devem ser configuradas em um grupo de failover no mesmo nó.

.Sobre esta tarefa
Um mapeamento individual de LIFs e NICs produz o maior ganho de desempenho, mas não é necessário para habilitar o entroncamento. Ter pelo menos duas NICs instaladas pode oferecer um benefício de desempenho, mas não é necessário.

Você pode ter vários grupos de failover, mas o grupo de failover para o entroncamento deve incluir apenas os LIFS no grupo de entroncamento.

Você deve ajustar o grupo de failover do entroncamento sempre que adicionar ou remover conexões (e NICs subjacentes) de um grupo de failover.

.Antes de começar
* Você deve saber os nomes das portas associadas às placas de rede se quiser criar um grupo de failover.
* Todas as portas devem estar no mesmo nó.


.Passos
. Verifique os nomes e o status das portas de rede que você planeja usar:
+
`network port status`

. Crie o grupo failover:
+
`network interface failover-groups create -vserver _svm_name_ -failover-group _failover_group_name_ -targets _ports_list_`

+

NOTE: Não é um requisito ter um grupo de failover, mas é altamente recomendável.

+
** `_svm_name_` É o nome do SVM que contém o servidor NFS.
** `_ports_list_` é a lista de portas que serão adicionadas ao grupo failover.
+
As portas são adicionadas no formato _node_name:port_number_, por exemplo, node1:e0c.

+
O comando a seguir cria o grupo de failover FG3 para SVM VS1 e adiciona três portas:

+
`network interface failover-groups create -vserver vs1 -failover-group fg3 -targets cluster1-01:e0c,cluster1-01:e0d,cluster1-01:e0e`

+
Saiba mais sobre link:../networking/configure_failover_groups_and_policies_for_lifs_overview.html["grupos de failover."]



. Se necessário, crie LIFs para membros do grupo de entroncamento:
+
`network interface create -vserver _svm_name_ -lif _lif_name_ -home-node _node_name_ -home-port _port_name_ -address _IP_address_ -netmask _IP_address_ [-service-policy _policy_] [-auto-revert {true|false}]`

+
** `-home-node` - O nó para o qual o LIF retorna quando o comando de reversão de interface de rede é executado no LIF.
+
Você também pode especificar se o LIF deve reverter automaticamente para o nó inicial e porta inicial com a `-auto-revert` opção.

** `-home-port` É a porta física ou lógica à qual o LIF retorna quando o comando de reversão da interface de rede é executado no LIF.
** Pode especificar um endereço IP com `-address` as opções e `-netmask`, não com a `-subnet` opção.
** Quando você atribui endereços IP, talvez seja necessário configurar uma rota padrão para um gateway se houver clientes ou controladores de domínio em uma sub-rede IP diferente. A `network route create` página man contém informações sobre a criação de uma rota estática dentro de um SVM.
** `-service-policy` - A política de serviços para o LIF. Se nenhuma política for especificada, uma política padrão será atribuída automaticamente. Use o `network interface service-policy show` comando para revisar as políticas de serviço disponíveis.
** `-auto-revert` - Especificar se um LIF de dados é automaticamente revertido para o seu nó inicial em circunstâncias como inicialização, alterações no status do banco de dados de gerenciamento ou quando a conexão de rede é feita. A configuração padrão é falsa, mas você pode configurá-la como verdadeira dependendo das políticas de gerenciamento de rede em seu ambiente.
+
Repita esta etapa para cada LIF no grupo de entroncamento.

+
O comando a seguir cria `lif-A` para o SVM `vs1`, na porta `e0c` do nó `cluster1_01`:

+
`network interface create -vserver vs1 -lif lif-A -service-policy *???* -home-node cluster1_01 -home-port e0c -address 192.0.2.0`

+
Saiba mais sobre link:../networking/create_lifs.html["Criação de LIF."]



. Verifique se os LIFs foram criados:
+
`network interface show`

. Verifique se o endereço IP configurado está acessível:
+
[cols="25,75"]
|===
| Para verificar um... | Utilizar... 


| Endereço IPv4 | `network ping` 


| Endereço IPv6 | `network ping6` 
|===

