---
permalink: flexcache/enable-flexcache-duality.html 
sidebar: sidebar 
keywords: flexcache, s3, nas, dual protocol, certificates, ontap 9.18.1 
summary: A partir do ONTAP 9.18.1, você pode habilitar o acesso S3 a volumes NAS FlexCache. Isso permite que os clientes acessem dados armazenados em um volume FlexCache usando o protocolo S3, além dos protocolos NAS tradicionais como NFS e SMB. Este é um guia rápido sobre como configurar isso. 
---
= Habilitar o acesso S3 aos volumes NAS FlexCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.18.1, você pode habilitar o acesso S3 a volumes NAS FlexCache, também conhecido como "dualidade". Isso permite que clientes acessem dados armazenados em um volume FlexCache usando o protocolo S3, além dos protocolos NAS tradicionais como NFS e SMB. Você pode usar as informações a seguir para configurar a dualidade FlexCache.



== Pré-requisitos

Antes de começar, você deve garantir que concluiu os seguintes pré-requisitos:

* Certifique-se de que o protocolo S3 e os protocolos NAS desejados (NFS, SMB ou ambos) estejam licenciados e configurados na SVM.
* Verifique se DNS e quaisquer outros serviços necessários estão configurados.
* Cluster e SVM emparelhados
* FlexCache Volume criar
* Data-lif criada



NOTE: Para obter documentação mais completa sobre FlexCache dualidade, consulte link:https://docs.netapp.com/us-en/ontap/s3-multiprotocol/index.html#how-s3-multiprotocol-support-works["Suporte multiprotocolo ONTAP S3"].



== Etapa 1: criar e assinar certificados

Para habilitar o acesso S3 a um FlexCache volume, você precisa instalar certificados para a SVM que hospeda o FlexCache volume. Este exemplo usa certificados autoassinados, mas em um ambiente de produção, você deve usar certificados assinados por uma autoridade certificadora (CA) confiável.

. [[anchor1-step]]Crie uma CA raiz SVM:
+
[source, cli]
----
security certificate create -vserver <svm> -type root-ca -common-name <arbitrary_name>
----
. [[anchor2-step]]Gerar uma solicitação de assinatura de certificado:
+
[source, cli]
----
security certificate generate-csr -common-name <dns_name_of_data_lif> -dns-name <dns_name_of_data_lif> -ipaddr <data_lif_ip>
----
+
Exemplo de saída:

+
[listing]
----
-----BEGIN CERTIFICATE REQUEST-----
MIICzjCCAbYCAQAwHzEdMBsGA1UEAxMUY2FjaGUxZy1kYXRhLm5hcy5sYWIwggEi
MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCusJk075O8Uh329cHI6x+BaRS2
w5wrqvzoYlidXtYmdCH3m1DDprBiAyfIwBC0/iU3Xd5NpB7nc1wK1CI2VEkrXGUg
...
vMIGN351+FgzLQ4X5lKfoMXCV70NqIakxzEmkTIUDKv7n9EVZ4b5DTTlrL03X/nK
+Bim2y2y180PaFB3NauZHTnIIzIc8zCp2IEqmFWyMDcdBjP9KS0+jNm4QhuXiM8F
D7gm3g/O70qa5OxbAEal5o4NbOl95U0T0rwqTaSzFG0XQnK2PmA1OIwS5ET35p3Z
dLU=
-----END CERTIFICATE REQUEST-----
----
+
Exemplo de chave privada:

+
[listing]
----
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCusJk075O8Uh32
9cHI6x+BaRS2w5wrqvzoYlidXtYmdCH3m1DDprBiAyfIwBC0/iU3Xd5NpB7nc1wK
1CI2VEkrXGUgwBtx1K4IlrCTB829Q1aLGAQXVyWnzhQc4tS5PW/DsQ8t7olZ9zEI
...
rXGEdDaqp7jQGNXUGlbxO3zcBil1/A9Hc6oalNECgYBKwe3PeZamiwhIHLy9ph7w
dJfFCshsPalMuAp2OuKIAnNa9l6fT9y5kf9tIbskT+t5Dth8bmV9pwe8UZaK5eC4
Svxm19jHT5QqloDaZVUmMXFKyKoqPDdfvcDk2Eb5gMfIIb0a3TPC/jqqpDn9BzuH
TO02fuRvRR/G/HUz2yRd+A==
-----END PRIVATE KEY-----
----
+

NOTE: Guarde uma cópia do seu pedido de certificado e da sua chave privada para referência futura.

. Assine o certificado:
+
O  `root-ca` é o que você criou em <<anchor1-step,Crie uma CA raiz SVM>>.

+
[source, cli]
----
certificate sign -ca <svm_root_ca> -ca-serial <svm_root_ca_sn> -expire-days 364 -format PEM -vserver <svm>
----
. Cole a Solicitação de Assinatura de Certificado (CSR) gerada em <<anchor2-step,Gerar uma solicitação de assinatura de certificado>>.
+
Exemplo:

+
[listing]
----
-----BEGIN CERTIFICATE REQUEST-----
MIICzjCCAbYCAQAwHzEdMBsGA1UEAxMUY2FjaGUxZy1kYXRhLm5hcy5sYWIwggEi
MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCusJk075O8Uh329cHI6x+BaRS2
w5wrqvzoYlidXtYmdCH3m1DDprBiAyfIwBC0/iU3Xd5NpB7nc1wK1CI2VEkrXGUg
...
vMIGN351+FgzLQ4X5lKfoMXCV70NqIakxzEmkTIUDKv7n9EVZ4b5DTTlrL03X/nK
+Bim2y2y180PaFB3NauZHTnIIzIc8zCp2IEqmFWyMDcdBjP9KS0+jNm4QhuXiM8F
D7gm3g/O70qa5OxbAEal5o4NbOl95U0T0rwqTaSzFG0XQnK2PmA1OIwS5ET35p3Z
dLU=
-----END CERTIFICATE REQUEST-----
----
+
Isso imprime um certificado assinado no console, semelhante ao exemplo a seguir.

+
Exemplo de certificado assinado:

+
[listing]
----
-----BEGIN CERTIFICATE-----
MIIDdzCCAl+gAwIBAgIIGHolbgv5DPowDQYJKoZIhvcNAQELBQAwLjEfMB0GA1UE
AxMWY2FjaGUtMTY0Zy1zdm0tcm9vdC1jYTELMAkGA1UEBhMCVVMwHhcNMjUxMTIx
MjIxNTU4WhcNMjYxMTIwMjIxNTU4WjAfMR0wGwYDVQQDExRjYWNoZTFnLWRhdGEu
...
qS7zhj3ikWE3Gp9s+QijKWXx/0HDd1UuGqy0QZNqNm/M0mqVnokJNk5F4fBFxMiR
1o63BxL8xGIRdtTCjjb2Gq2Wj7EClUw6CykEkxAcVk+XrRtArGkNtcYdtHfUsKVE
wswvv0rNydrNnWhJLhSl8TW5Tex+OMyTXgk9/3K8kB0mAMrtxxYjt8tm+gztkivf
J0eo1uDJhaNxqwEZRzFyGaa4k1+56oFzRfTc
-----END CERTIFICATE-----
----
. Copie o certificado para a próxima etapa.
. Instale o certificado do servidor na SVM:
+
[source, cli]
----
certificate install -type server -vserver <svm> -cert-name flexcache-duality
----
. Cole o certificado assinado de <<anchor3-step,Assinar o certificado>>.
+
Exemplo:

+
[listing]
----
Please enter Certificate: Press <Enter> [twice] when done
-----BEGIN CERTIFICATE-----
MIIDdzCCAl+gAwIBAgIIGHolbgv5DPowDQYJKoZIhvcNAQELBQAwLjEfMB0GA1UE
AxMWY2FjaGUtMTY0Zy1zdm0tcm9vdC1jYTELMAkGA1UEBhMCVVMwHhcNMjUxMTIx
MjIxNTU4WhcNMjYxMTIwMjIxNTU4WjAfMR0wGwYDVQQDExRjYWNoZTFnLWRhdGEu
bmFzLmxhYjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAK6wmTTvk7xS
...
qS7zhj3ikWE3Gp9s+QijKWXx/0HDd1UuGqy0QZNqNm/M0mqVnokJNk5F4fBFxMiR
1o63BxL8xGIRdtTCjjb2Gq2Wj7EClUw6CykEkxAcVk+XrRtArGkNtcYdtHfUsKVE
wswvv0rNydrNnWhJLhSl8TW5Tex+OMyTXgk9/3K8kB0mAMrtxxYjt8tm+gztkivf
J0eo1uDJhaNxqwEZRzFyGaa4k1+56oFzRfTc
-----END CERTIFICATE-----
----
. Cole a chave privada gerada em <<anchor2-step,Gerar uma solicitação de assinatura de certificado>>.
+
Exemplo:

+
[listing]
----
Please enter Private Key: Press <Enter> [twice] when done
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCusJk075O8Uh32
9cHI6x+BaRS2w5wrqvzoYlidXtYmdCH3m1DDprBiAyfIwBC0/iU3Xd5NpB7nc1wK
1CI2VEkrXGUgwBtx1K4IlrCTB829Q1aLGAQXVyWnzhQc4tS5PW/DsQ8t7olZ9zEI
W/gaEIajgpXIwGNWZ+weKQK+yoolxC+gy4IUE7WvnEUiezaIdoqzyPhYq5GC4XWf
0johpQugOPe0/w2nVFRWJoFQp3ZP3NZAXc8H0qkRB6SjaM243XV2jnuEzX2joXvT
wHHH+IBAQ2JDs7s1TY0I20e49J2Fx2+HvUxDx4BHao7CCHA1+MnmEl+9E38wTaEk
NLsU724ZAgMBAAECggEABHUy06wxcIk5hO3S9Ik1FDZV3JWzsu5gGdLSQOHRd5W+
...
rXGEdDaqp7jQGNXUGlbxO3zcBil1/A9Hc6oalNECgYBKwe3PeZamiwhIHLy9ph7w
dJfFCshsPalMuAp2OuKIAnNa9l6fT9y5kf9tIbskT+t5Dth8bmV9pwe8UZaK5eC4
Svxm19jHT5QqloDaZVUmMXFKyKoqPDdfvcDk2Eb5gMfIIb0a3TPC/jqqpDn9BzuH
TO02fuRvRR/G/HUz2yRd+A==
-----END PRIVATE KEY-----
----
. Insira os certificados das autoridades de certificação (CA) que formam a cadeia do certificado do servidor.
+
Isso começa com o certificado da CA emissora do certificado do servidor e pode chegar até o certificado da CA raiz.

+
[listing]
----
Do you want to continue entering root and/or intermediate certificates {y|n}: n

You should keep a copy of the private key and the CA-signed digital certificate for future reference.

The installed certificate's CA and serial number for reference:
CA: cache-164g-svm-root-ca
serial: 187A256E0BF90CFA
----
. Obtenha a chave pública para a CA raiz do SVM:
+
[source, cli]
----
security certificate show -vserver <svm> -common-name <root_ca_cn> -ca <root_ca_cn> -type root-ca -instance

-----BEGIN CERTIFICATE-----
MIIDgTCCAmmgAwIBAgIIGHokTnbsHKEwDQYJKoZIhvcNAQELBQAwLjEfMB0GA1UE
AxMWY2FjaGUtMTY0Zy1zdm0tcm9vdC1jYTELMAkGA1UEBhMCVVMwHhcNMjUxMTIx
MjE1NTIzWhcNMjYxMTIxMjE1NTIzWjAuMR8wHQYDVQQDExZjYWNoZS0xNjRnLXN2
bS1yb290LWNhMQswCQYDVQQGEwJVUzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
...
DoOL7vZFFt44xd+rp0DwafhSnLH5HNhdIAfa2JvZW+eJ7rgevH9wmOzyc1vaihl3
Ewtb6cz1a/mtESSYRNBmGkIGM/SFCy5v1ROZXCzF96XPbYQN4cW0AYI3AHYBZP0A
HlNzDR8iml4k9IuKf6BHLFA+VwLTJJZKrdf5Jvjgh0trGAbQGI/Hp2Bjuiopkui+
n4aa5Rz0JFQopqQddAYnMuvcq10CyNn7S0vF/XLd3fJaprH8kQ==
-----END CERTIFICATE-----
----
+

NOTE: Isso é necessário para configurar o cliente para confiar nos certificados assinados pela SVM root-ca. A chave pública é exibida no console. Copie e salve a chave pública. Os valores neste comando são os mesmos que você inseriu em <<anchor1-step,Crie uma CA raiz SVM>>.





== Etapa 2: configurar o servidor S3

. Habilitar acesso ao protocolo S3:
+
[source, cli]
----
vserver show -vserver <svm> -fields allowed-protocols
----
+

NOTE: O S3 é permitido no nível SVM por padrão.

. Clone uma política existente:
+
[source, cli]
----
network interface service-policy clone -vserver <svm> -policy default-data-files -target-vserver <svm> -target-policy <any_name>
----
. Adicione S3 à política clonada:
+
[source, cli]
----
network interface service-policy add-service -vserver <svm> -policy <any_name> -service data-s3-server
----
. Adicione a nova política ao data lif:
+
[source, cli]
----
network interface modify -vserver <svm> -lif <data_lif> -service-policy duality
----
+

NOTE: Modificar a política de serviço de uma LIF existente pode ser disruptivo. Isso exige que a LIF seja desativada e reativada com um ouvinte para o novo serviço. TCP *deveria* se recuperar rapidamente disso, mas esteja ciente do impacto potencial.

. Crie o servidor de armazenamento de objetos S3 na SVM:
+
[source, cli]
----
vserver object-store-server create -vserver <svm> -object-store-server <dns_name_of_data_lif> -certificate-name flexcache-duality
----
. Ativar a funcionalidade S3 no FlexCache volume:
+
A  `flexcache config`opção `-is-s3-enabled` deve ser definida como `true` antes de você poder criar um bucket. Você também deve definir a opção `-is-writeback-enabled` para `false`.

+
O comando a seguir modifica um FlexCache existente:

+
[source, cli]
----
flexcache config modify -vserver <svm> -volume <fcache_vol> -is-writeback-enabled false -is-s3-enabled true
----
. Crie um bucket S3:
+
[source, cli]
----
vserver object-store-server bucket create -vserver <svm> -bucket <bucket_name> -type nas -nas-path <flexcache_junction_path>
----
. Crie uma política de bucket:
+
[source, cli]
----
vserver object-store-server bucket policy add-statement -vserver <svm> -bucket <bucket_name> -effect allow
----
. Crie um usuário S3:
+
[source, cli]
----
vserver object-store-server user create -user <user> -comment ""
----
+
Exemplo de saída:

+
[listing]
----
    Vserver: <svm>>
       User: <user>>
 Access Key: WCOT7...Y7D6U
 Secret Key: 6143s...pd__P
    Warning: The secret key won't be displayed again. Save this key for future use.
----
. Regenerar chaves para o usuário raiz:
+
[source, cli]
----
vserver object-store-server user regenerate-keys -vserver <svm> -user root
----
+
Exemplo de saída:

+
[listing]
----
    Vserver: <svm>>
       User: root
 Access Key: US791...2F1RB
 Secret Key: tgYmn...8_3o2
    Warning: The secret key won't be displayed again. Save this key for future use.
----




== Etapa 3: configurar o cliente

Existem muitos clientes S3 disponíveis. Um bom ponto de partida é com o AWS CLI. Para mais informações, consulte link:https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html["Instalando o AWS CLI"^].
