---
permalink: flexcache/index.html 
sidebar: sidebar 
keywords: flexcache, volumes, faster, data, access, configure, manage, overview, origin volumes 
summary: Você pode configurar e gerenciar o FlexCache volumes para acelerar o acesso aos dados. 
---
= Visão geral do FlexCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A tecnologia NetApp FlexCache acelera o acesso aos dados, reduz a latência da WAN e reduz os custos de largura de banda da WAN para workloads com uso intenso de leitura, especialmente quando os clientes precisam acessar os mesmos dados repetidamente. Ao criar um volume FlexCache, você cria um cache remoto de um volume (origem) já existente que contém apenas os dados acessados ativamente (dados ativos) do volume de origem.

Quando um volume FlexCache recebe uma solicitação de leitura dos dados ativos que ele contém, ele pode responder mais rápido do que o volume de origem porque os dados não precisam viajar até o cliente. Se um volume FlexCache receber uma solicitação de leitura para dados de leitura com pouca frequência (dados inativos), ele recupera os dados necessários do volume de origem e armazena os dados antes de servir a solicitação do cliente. As solicitações de leitura subsequentes para esses dados são então fornecidas diretamente do volume FlexCache. Após a primeira solicitação, os dados não precisam mais viajar pela rede ou ser atendidos de um sistema carregado. Por exemplo, suponha que você esteja enfrentando gargalos no cluster em um ponto de acesso singular para dados solicitados com frequência. Você pode usar o FlexCache volumes no cluster para fornecer vários pontos de montagem nos dados ativos, reduzindo os gargalos e aumentando a performance. Como outro exemplo, suponha que você precise diminuir o tráfego de rede para um volume que é acessado de vários clusters. Você pode usar o FlexCache volumes para distribuir dados ativos do volume de origem entre os clusters da rede. Isso reduz o tráfego de WAN, dando aos usuários pontos de acesso mais próximos.

Você também pode usar a tecnologia FlexCache para melhorar a performance em ambientes de nuvem ou nuvem híbrida. Um volume FlexCache pode ajudar você a migrar workloads para a nuvem híbrida armazenando dados em cache de um data center local para a nuvem. Também é possível usar o FlexCache volumes para remover silos de nuvem, armazenando dados em cache de um fornecedor de nuvem para outro ou entre duas regiões do mesmo fornecedor de nuvem.

A partir do ONTAP 9.10,1, você pode link:global-file-locking-task.html["ative o bloqueio global de ficheiros"] em todos os volumes do FlexCache. O bloqueio global de arquivos impede que um usuário acesse um arquivo que já esteja aberto por outro usuário. As atualizações do volume de origem são então distribuídas para todos os volumes FlexCache simultaneamente.

A partir do ONTAP 9.9,1, o FlexCache volumes mantém uma lista de arquivos não encontrados. Isso ajuda a reduzir o tráfego de rede removendo a necessidade de enviar várias chamadas para a origem quando os clientes pesquisam arquivos inexistentes.

link:supported-unsupported-features-concept.html["Recursos compatíveis com volumes FlexCache e seus volumes de origem"]Também está disponível uma lista de protocolos adicionais, incluindo uma lista de protocolos suportados pela versão ONTAP.

Você pode aprender mais sobre a arquitetura da tecnologia ONTAP FlexCache no link:https://www.netapp.com/pdf.html?item=/media/7336-tr4743.pdf["TR-4743: FlexCache em ONTAP"^].



== Vídeos



=== Como o FlexCache pode reduzir a latência da WAN e os tempos de leitura para dados globais

video::rbbH0l74RWc[youtube,width=848,height=480]


=== Saiba mais sobre os benefícios de desempenho do ONTAP FlexCache!

video::bWi1-8Ydkpg[youtube,width=848,height=480]