---
permalink: flexcache/sizing-concept.html 
sidebar: sidebar 
keywords: guidelines, sizing, flexcache, volume 
summary: Antes de começar a provisionar os volumes, você precisa estar ciente dos limites do FlexCache volumes. 
---
= Diretrizes para dimensionamento de volumes ONTAP FlexCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de começar a provisionar os volumes, você precisa estar ciente dos limites do FlexCache volumes.

O limite de tamanho de um FlexVol volume é aplicável a um volume de origem. O tamanho de um volume FlexCache pode ser menor ou igual ao volume de origem. A melhor prática para o tamanho de um volume de FlexCache é ser pelo menos 10% do tamanho do volume de origem.

Você também precisa estar ciente dos seguintes limites adicionais para o FlexCache volumes:

[cols="55,15,15,15"]
|===


| Limite | ONTAP 9,5-9,6 | ONTAP 9,7 | ONTAP 9 F.8 e mais tarde 


| Número máximo de volumes FlexCache que você pode criar a partir de um volume de origem | 10 | 10 | 100 


| Número máximo recomendado de volumes de origem por nó | 10 | 100 | 100 


| Número máximo recomendado de volumes FlexCache por nó | 10 | 100 | 100 


| Número máximo recomendado de componentes FlexGroup em um volume FlexCache por nó | 40 | 800 | 800 


| Número máximo de constituintes por volume FlexCache por nó | 32 | 32 | 32 
|===
.Informações relacionadas
https://mysupport.netapp.com/NOW/products/interoperability["Interoperabilidade do NetApp"^]
