---
permalink: volumes/assign-quota-policies-concept.html 
sidebar: sidebar 
keywords: considerations for, assigning, quota, policies 
summary: Uma política de cota é um agrupamento das regras de cota para todos os volumes FlexVol de um SVM. Você deve estar ciente de certas considerações ao atribuir as políticas de cota. 
---
= Considerações para atribuir políticas de quota
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Uma política de cota é um agrupamento das regras de cota para todos os volumes FlexVol de um SVM. Você deve estar ciente de certas considerações ao atribuir as políticas de cota.

* Um SVM tem uma política de cota atribuída a qualquer momento. Quando um SVM é criado, uma política de cota em branco é criada e atribuída ao SVM. Essa política de cota padrão tem o nome "padrão", a menos que um nome diferente seja especificado quando o SVM for criado.
* O SVM pode ter até cinco políticas de cota. Se um SVM tiver cinco políticas de cota, você não poderá criar uma nova política de cota para o SVM até excluir uma política de cota existente.
* Quando você precisa criar uma regra de cota ou alterar regras de cota para uma política de cota, você pode escolher uma das seguintes abordagens:
+
** Se você estiver trabalhando em uma política de cota atribuída a um SVM, não será necessário atribuir a política de cota ao SVM.
** Se estiver trabalhando em uma política de cota não atribuída e atribuindo a diretiva de cota ao SVM, você deverá ter um backup da política de cota para a qual poderá reverter, se necessário.
+
Por exemplo, você pode fazer uma cópia da política de cota atribuída, alterar a cópia, atribuir a cópia ao SVM e renomear a política de cota original.



* Você pode renomear uma política de cota mesmo quando ela é atribuída ao SVM.

