---
permalink: volumes/autoshrink-snapshot-copy-deletion-concept.html 
sidebar: sidebar 
keywords: how, autoshrink functionality, interacts with, snapshot copy, deletion, automatic 
summary: Como a funcionalidade de redução automática diminui o tamanho de um FlexVol volume, ele também pode afetar quando as cópias snapshot de volume são excluídas automaticamente. 
---
= Funcionalidade de redução automática e eliminação de cópia instantânea
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Como a funcionalidade de redução automática diminui o tamanho de um FlexVol volume, ele também pode afetar quando as cópias snapshot de volume são excluídas automaticamente.

A funcionalidade de redução automática interage com a exclusão automática de cópia Snapshot do volume das seguintes maneiras:

* Se o `grow_shrink` modo automático e a exclusão automática de cópia Snapshot estiverem ativados, quando um tamanho de volume diminuir, ele poderá acionar uma exclusão automática de cópia Snapshot.
+
Isso ocorre porque a reserva Snapshot é baseada em uma porcentagem do tamanho do volume (5% por padrão), e essa porcentagem agora é baseada em um tamanho de volume menor. Isso pode fazer com que cópias Snapshot saiam da reserva e sejam excluídas automaticamente.

* Se o `grow_shrink` modo de dimensionamento automático estiver ativado e você excluir manualmente uma cópia Snapshot, ela poderá acionar um encolhimento automático de volume.

