---
permalink: volumes/autoshrink-snapshot-copy-deletion-concept.html 
sidebar: sidebar 
keywords: how, autoshrink functionality, interacts with, snapshot copy, deletion, automatic 
summary: Como a funcionalidade de auto-redução diminui o tamanho de um FlexVol volume, ele também pode afetar quando os instantâneos de volume são excluídos automaticamente. 
---
= Funcionalidade de redução automática e eliminação de instantâneos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Como a funcionalidade de auto-redução diminui o tamanho de um FlexVol volume, ele também pode afetar quando os instantâneos de volume são excluídos automaticamente.

A funcionalidade de auto-redução interage com a eliminação automática de instantâneos de volume das seguintes formas:

* Se o `grow_shrink` modo automático e a eliminação automática de instantâneos estiverem ativados, quando o tamanho de um volume diminuir, pode acionar uma eliminação automática de instantâneos.
+
Isso ocorre porque a reserva de snapshot é baseada em uma porcentagem do tamanho do volume (5% por padrão), e essa porcentagem agora é baseada em um tamanho de volume menor. Isso pode fazer com que os snapshots saiam da reserva e sejam excluídos automaticamente.

* Se o `grow_shrink` modo de dimensionamento automático estiver ativado e você excluir manualmente um instantâneo, ele poderá acionar um encolhimento automático de volume.

