---
permalink: volumes/change-inactive-data-threshold-task.html 
sidebar: sidebar 
keywords: storage, efficiency, temperature, change, efficient, default, threshold, inactive, compression, cold data, frequency, threshold, scan, coldness, temperature-sensitive 
summary: Você pode alterar a frequência com que o ONTAP realiza uma verificação de dados inativos modificando o limite de frieza em volumes usando a eficiência de storage sensível à temperatura. 
---
= Alterar o limite de compressão de dados inativos de volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar a frequência com que o ONTAP realiza uma verificação de dados inativos modificando o limite de frieza em volumes usando a eficiência de storage sensível à temperatura.

.Antes de começar
Você precisa ser um administrador de cluster ou SVM e usar o nível de privilégio avançado da CLI do ONTAP.

.Sobre esta tarefa
O limiar de frieza pode ser de 1 a 60 dias. O limite padrão é de 14 dias.

.Passos
. Defina o nível de privilégio:
+
`set -privilege advanced`

. Modificar a compressão de dados inativos em um volume:
+
`volume efficiency inactive-data-compression modify -vserver <vserver_name> -volume <volume_name> -threshold-days <integer>`



Consulte a página de manual para obter informações adicionais sobre link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-inactive-data-compression-modify.html#description["modificação da compressão de dados inativos"].
