---
permalink: volumes/commands-configure-deletion-flexclone-reference.html 
sidebar: sidebar 
keywords: commands for, configuring, deletion of, flexclone files, configure, command, delete, deletion, files, file 
summary: Quando os clientes excluem arquivos FlexClone sem usar o SDK de gerenciamento do NetApp, você pode usar os comandos de exclusão de clone de arquivo de volume para permitir a exclusão mais rápida de arquivos FlexClone de um FlexVol volume. 
---
= Comandos para configurar a exclusão de arquivos FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando os clientes excluem arquivos FlexClone sem usar o SDK de gerenciamento do NetApp, você pode usar os `volume file clone deletion` comandos para permitir a exclusão mais rápida de arquivos FlexClone de um FlexVol volume. Extensões e tamanho mínimo de arquivos FlexClone são usados para permitir a exclusão mais rápida.

Você pode usar os `volume file clone deletion` comandos para especificar uma lista de extensões suportadas e um requisito de tamanho mínimo para arquivos FlexClone em um volume. O método de exclusão mais rápido é usado apenas para arquivos FlexClone que atendam aos requisitos. Para arquivos FlexClone que não atendem aos requisitos, o método de exclusão mais lento é usado.

Quando os clientes excluem arquivos FlexClone e LUNs FlexClone de um volume usando o SDK de gerenciamento do NetApp, os requisitos de extensão e tamanho não se aplicam porque o método de exclusão mais rápido é sempre usado.

[cols="2*"]
|===
| Para... | Use este comando... 


 a| 
Adicione uma extensão à lista de extensões suportadas para o volume
 a| 
`volume file clone deletion add-extension`



 a| 
Altere o tamanho mínimo dos arquivos FlexClone que podem ser excluídos do volume usando o método de exclusão mais rápido
 a| 
`volume file clone deletion modify`



 a| 
Remova uma extensão da lista de extensões suportadas para o volume
 a| 
`volume file clone deletion remove-extension`



 a| 
Visualize a lista de extensões suportadas e o tamanho mínimo de ficheiros FlexClone que os clientes podem eliminar do volume utilizando o método de eliminação mais rápida
 a| 
`volume file clone deletion show`

|===
Para obter informações detalhadas sobre esses comandos, consulte a página man apropriada.
