---
permalink: volumes/commands-display-quotas-reference.html 
sidebar: sidebar 
keywords: commands for, display, displaying, information about, quotas 
summary: Você pode usar comandos para exibir um relatório de cota contendo cotas aplicadas e uso de recursos, exibir informações sobre o estado e erros da cota ou sobre políticas de cota e regras de cota. 
---
= Comandos para exibir informações sobre cotas no ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar comandos para exibir um relatório de cota contendo cotas aplicadas e uso de recursos, exibir informações sobre o estado e erros da cota ou sobre políticas de cota e regras de cota.

[NOTE]
====
Você pode executar os seguintes comandos apenas no FlexVol volumes.

====
[cols="2*"]
|===
| Se você quiser... | Use este comando... 


 a| 
Exibir informações sobre cotas aplicadas
 a| 
`volume quota report`



 a| 
Exibir o uso de recursos (espaço em disco e número de arquivos) de alvos de cota
 a| 
`volume quota report`



 a| 
Determine quais limites de cota são afetados quando uma gravação em um arquivo é permitida
 a| 
`volume quota report` com o `-path` parâmetro



 a| 
Exiba o estado da cota, como `on` , `off` e `initializing`
 a| 
`volume quota show`



 a| 
Exibir informações sobre o Registro de mensagens de cota
 a| 
`volume quota show` com o `-logmsg` parâmetro



 a| 
Veja erros que ocorrem durante a inicialização e redimensionamento da cota
 a| 
`volume quota show` com o `-instance` parâmetro



 a| 
Exibir informações sobre políticas de cota
 a| 
`volume quota policy show`



 a| 
Exibir informações sobre regras de cota
 a| 
`volume quota policy rule show`



 a| 
Exibir o nome da política de cota atribuída a uma máquina virtual de storage (SVM, anteriormente conhecido como SVM)
 a| 
`vserver show` com o `-instance` parâmetro

|===
Saiba mais sobre `volume quota` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume+quota["Referência do comando ONTAP"^]na .
