---
permalink: volumes/commands-display-space-usage-reference.html 
sidebar: sidebar 
keywords: commands for, displaying, space, usage, information, display 
summary: Você usa os comandos de volume e agregado de storage para ver como o espaço está sendo usado em agregados, volumes e snapshots. 
---
= Comandos para exibir informações de uso de espaço
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Use os `storage aggregate` comandos e `volume` para ver como o espaço está sendo usado em agregados e volumes e em seus snapshots.

A partir do ONTAP 9.18.1, o  `storage aggregate show-space` comando altera como a Capacidade Lógica Referenciada e a Capacidade Lógica Não Referenciada são relatadas. A Capacidade Lógica Referenciada relata blocos referenciados em todos os objetos e blocos não referenciados em objetos fragmentados. A Capacidade Lógica Não Referenciada relata apenas blocos não referenciados em objetos que ultrapassaram o limite de preenchimento e estão aptos para exclusão e desfragmentação.

Por exemplo, ao usar o limite de preenchimento agregado padrão de 40% para ONTAP S3 e StorageGRID, 60% dos blocos em um objeto devem estar sem referência antes que os blocos sejam relatados como capacidade sem referência.

Em versões anteriores ao ONTAP 9.18.1, a Capacidade Lógica Referenciada reporta blocos referenciados em todos os objetos (tanto completos quanto fragmentados). A Capacidade Lógica Não Referenciada reporta blocos não referenciados em todos os objetos.

[cols="2*"]
|===
| Para exibir informações sobre... | Use este comando... 


 a| 
Agregados, incluindo detalhes sobre porcentagens de espaço usadas e disponíveis, tamanho da reserva de snapshot e outras informações de utilização de espaço
 a| 
`storage aggregate show`

`storage aggregate show-space -fields snap-size-total,used-including-snapshot-reserve`



 a| 
Como discos e grupos RAID são usados em um agregado e status RAID
 a| 
`storage aggregate show-status`



 a| 
A quantidade de espaço em disco que seria recuperada se você excluísse um snapshot específico
 a| 
`volume snapshot compute-reclaimable` (avançado)



 a| 
A quantidade de espaço utilizada por um volume
 a| 
`volume show -fields size,used,available,percent-used`

`volume show-space`



 a| 
A quantidade de espaço usada por um volume no agregado que contém
 a| 
`volume show-footprint`

|===
.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=storage+aggregate+show["show de agregados de storage"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-space.html["espaço de exposição de agregados de armazenamento"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-status.html["status de exibição de agregado de armazenamento"^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-compute-reclaimable.html["recuperação de computação do snapshot de volume"^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-show.html["apresentação do volume"^]

