---
permalink: volumes/commands-activate-modify-quotas-reference.html 
sidebar: sidebar 
keywords: commands to, activate, modify, quotas, command, commands 
summary: Os comandos de cota de volume permitem alterar o estado de cotas e configurar o Registro de mensagens de cotas. 
---
= Comandos para ativar e modificar cotas no ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`volume quota` os comandos permitem alterar o estado das cotas e configurar o registro de mensagens das cotas. Dependendo do que você precisa fazer, você pode usar os seguintes comandos para ativar e modificar cotas:

[cols="2*"]
|===
| Se você quiser... | Use este comando... 


 a| 
Ativar cotas (também chamado de _inicializando_ elas)
 a| 
`volume quota on`



 a| 
Redimensionar cotas existentes
 a| 
`volume quota resize`



 a| 
Desativar cotas
 a| 
`volume quota off`



 a| 
Altere o Registro de mensagens de cotas, ative cotas, desative cotas ou redimensione cotas existentes
 a| 
`volume quota modify`

|===
Saiba mais sobre os comandos descritos neste procedimento no link:https://docs.netapp.com/us-en/ontap-cli/["Referência do comando ONTAP"^].

.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-on.html["quota de volume ativada"^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-resize.html["redimensionar cota de volume"^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-off.html["cota de volume desativada"^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-modify.html["alteração da cota de volume"^]

