---
permalink: volumes/commands-move-volumes-reference.html 
sidebar: sidebar 
keywords: commands, moving, volumes, to move, move 
summary: A CLI do ONTAP fornece comandos específicos para gerenciar a movimentação de volume. 
---
= Comandos para mover volumes no ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A CLI do ONTAP fornece comandos específicos para gerenciar a movimentação de volume. Dependendo do que você precisa fazer, use os seguintes comandos para gerenciar regras de cota e políticas de cota:

[cols="2*"]
|===
| Se você quiser... | Use este comando... 


 a| 
Abortar uma operação de movimentação de volume ativa.
 a| 
`volume move abort`



 a| 
Mostrar o status de um volume que se move de um agregado para outro agregado.
 a| 
`volume move show`



 a| 
Comece a mover um volume de um agregado para outro agregado.
 a| 
`volume move start`



 a| 
Gerenciar agregados de destino para movimentação de volume.
 a| 
`volume move target-aggr`



 a| 
Acionar a transição de um trabalho de movimento.
 a| 
`volume move trigger-cutover`



 a| 
Alterar a quantidade de tempo que o acesso do cliente é bloqueado se o padrão não for adequado.
 a| 
`volume move start` ou `volume move modify` com o `-cutover-window` parâmetro. O `volume move modify` comando é um comando avançado e o `-cutover-window` é um parâmetro avançado.



 a| 
Determine o que o sistema faz se a operação de movimentação de volume não puder ser concluída durante o tempo em que o acesso do cliente é bloqueado.
 a| 
`volume move start` ou `volume move modify` com o `-cutover-action` parâmetro. O `volume move modify` comando é um comando avançado e o `-cutover-action` é um parâmetro avançado.

|===
.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume+move["movimentação de volume"^]

