---
permalink: volumes/commands-manage-quota-rules-policies-reference.html 
sidebar: sidebar 
keywords: commands to, manage, quota rules, quota policies, command, commands, quota, quotas, policy, policies 
summary: 'Os `volume quota policy rule` comandos permitem configurar regras de quota e os `volume quota policy` comandos e alguns `vserver` comandos permitem configurar políticas de quota.' 
---
= Comandos para gerenciar regras de cota e políticas de cota
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os `volume quota policy rule` comandos permitem configurar regras de quota e os `volume quota policy` comandos e alguns `vserver` comandos permitem configurar políticas de quota. Dependendo do que você precisa fazer, use os seguintes comandos para gerenciar regras de cota e políticas de cota:


NOTE: Você pode executar os seguintes comandos apenas no FlexVol volumes.



== Comandos para gerenciar regras de cota

[cols="2*"]
|===
| Se você quiser... | Use este comando... 


 a| 
Crie uma nova regra de cota
 a| 
`volume quota policy rule create`



 a| 
Excluir uma regra de cota existente
 a| 
`volume quota policy rule delete`



 a| 
Modificar uma regra de cota existente
 a| 
`volume quota policy rule modify`



 a| 
Exibir informações sobre regras de cota configuradas
 a| 
`volume quota policy rule show`

|===


== Comandos para gerenciar políticas de cota

[cols="2*"]
|===
| Se você quiser... | Use este comando... 


 a| 
Duplique uma política de quota e as regras de quota que contém
 a| 
`volume quota policy copy`



 a| 
Crie uma nova política de quota em branco
 a| 
`volume quota policy create`



 a| 
Excluir uma política de cota existente que não esteja atribuída atualmente a uma máquina virtual de storage (SVM)
 a| 
`volume quota policy delete`



 a| 
Renomeie uma política de cota
 a| 
`volume quota policy rename`



 a| 
Exibir informações sobre políticas de cota
 a| 
`volume quota policy show`



 a| 
Atribua uma política de cota a um SVM
 a| 
`vserver modify -quota-policy _policy_name_`



 a| 
Exiba o nome da política de cota atribuída a um SVM
 a| 
`vserver show`

|===
Saiba mais sobre os comandos descritos neste procedimento no link:https://docs.netapp.com/us-en/ontap-cli/["Referência do comando ONTAP"^].

.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume+quota+policy["política de cota de volume"^]
* link:https://docs.netapp.com/us-en/ontap-cli/vserver-modify.html["svm modificar -quota-política policy_name"^]
* link:https://docs.netapp.com/us-en/ontap-cli/vserver-show.html["mostra o svm"^]

