---
permalink: volumes/configure-flexvol-delete-flexclone-files-luns-task.html 
sidebar: sidebar 
keywords: configure, flexvol volume, automatically, delete, flexclone files, flexclone luns, flexvol, volume, automatic, file, autodelete 
summary: Você pode habilitar um FlexVol volume para excluir automaticamente arquivos FlexClone e LUNs FlexClone quando o espaço livre no volume diminuir abaixo de um determinado limite. 
---
= Configure um FlexVol volume para excluir automaticamente arquivos FlexClone e LUNs FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar um volume para começar a excluir automaticamente arquivos FlexClone e LUNs FlexClone quando o espaço livre no volume diminuir abaixo de um determinado valor limite e parar automaticamente de excluir clones quando uma quantidade de espaço livre no volume for recuperada. Embora não seja possível especificar o valor de limite que inicia a exclusão automática de clones, você pode especificar se um clone é elegível para exclusão e especificar a quantidade de espaço livre de destino para um volume.

Um volume exclui automaticamente arquivos FlexClone e LUNs FlexClone quando o espaço livre no volume diminui abaixo de um determinado limite e quando _ambos_ dos seguintes requisitos são atendidos:

* A funcionalidade de autodelete está ativada para o volume que contém os arquivos FlexClone e LUNs FlexClone.
+
Você pode ativar a capacidade de transferência de um FlexVol volume usando o `volume snapshot autodelete modify` comando. Você deve definir o `-trigger` parâmetro para `volume` ou `snap_reserve` para que um volume exclua automaticamente arquivos FlexClone e LUNs FlexClone.

* A funcionalidade de configuração do sistema de áudio e vídeo é habilitada para os LUNs FlexClone e FlexClone.
+
Você pode ativar o arquivo FlexClone ou FlexClone LUN usando o `file clone create` comando com o `-autodelete` parâmetro. Como resultado, você pode preservar certos arquivos FlexClone e LUNs FlexClone, desativando o serviço de seleção de clones e garantindo que outras configurações de volume não substituam a configuração de clone.



.Antes de começar
* O FlexVol volume deve conter arquivos FlexClone e LUNs FlexClone, além de estar online.
* O FlexVol volume não deve ser um volume somente leitura.


.Passos
. Ative a exclusão automática de arquivos FlexClone e LUNs FlexClone no FlexVol volume usando o `volume snapshot autodelete modify` comando. Saiba mais sobre `volume snapshot autodelete modify` o link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-autodelete-modify.html["Referência do comando ONTAP"^]na .
+
** Para o `-trigger` parâmetro, pode especificar `volume` ou `snap_reserve`.
** Para o `-destroy-list` parâmetro, você deve sempre especificar `lun_clone,file_clone`, independentemente de você querer excluir apenas um tipo de clone. O exemplo a seguir mostra como você pode ativar o volume vol1 para acionar a exclusão automática de arquivos FlexClone e LUNs FlexClone para recuperação de espaço até que 25% do volume consista em espaço livre:
+
[listing]
----
cluster1::> volume snapshot autodelete modify -vserver vs1 -volume vol1 -enabled true -commitment disrupt -trigger volume -target-free-space 25 -destroy-list lun_clone,file_clone

Volume modify successful on volume:vol1
----
+
[NOTE]
====
Ao ativar volumes FlexVol para exclusão automática, se você definir o valor `-commitment` do parâmetro como `destroy`, todos os arquivos FlexClone e LUNs FlexClone com o `-autodelete` parâmetro definido como `true` poderão ser excluídos quando o espaço livre no volume diminuir abaixo do valor de limite especificado. No entanto, os arquivos FlexClone e LUNs FlexClone com o `-autodelete` parâmetro definido como `false` não serão excluídos.

====


. Verifique se a exclusão automática de arquivos FlexClone e LUNs FlexClone está ativada no FlexVol volume usando o `volume snapshot autodelete show` comando. Saiba mais sobre `volume snapshot autodelete show` o link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-autodelete-show.html["Referência do comando ONTAP"^]na .
+
O exemplo a seguir mostra que o volume vol1 está habilitado para exclusão automática de arquivos FlexClone e LUNs FlexClone:

+
[listing]
----
cluster1::> volume snapshot autodelete show -vserver vs1 -volume vol1

         Vserver Name: vs1
          Volume Name: vol1
          Enabled: true
           Commitment: disrupt
         Defer Delete: user_created
         Delete Order: oldest_first
  Defer Delete Prefix: (not specified)
    Target Free Space: 25%
              Trigger: volume
     *Destroy List: lun_clone,file_clone*
Is Constituent Volume: false
----
. Certifique-se de que o serviço de correio eletrónico está ativado para os ficheiros FlexClone e LUNs FlexClone no volume que pretende eliminar, executando as seguintes etapas:
+
.. Ative a exclusão automática de um arquivo FlexClone específico ou LUN FlexClone usando o `volume file clone autodelete` comando. Saiba mais sobre `volume file clone autodelete` o link:https://docs.netapp.com/us-en/ontap-cli/volume-file-clone-autodelete.html["Referência do comando ONTAP"^]na .
+
Você pode forçar um arquivo FlexClone específico ou LUN FlexClone a ser automaticamente excluído usando o `volume file clone autodelete` comando com o `-force` parâmetro.

+
O exemplo a seguir mostra que a exclusão automática do FlexClone LUN lun1_clone contido no volume vol1 está ativada:

+
[listing]
----
cluster1::> volume file clone autodelete -vserver vs1 -clone-path /vol/vol1/lun1_clone -enabled true
----
+
Você pode ativar o arquivo FlexClone e LUNs do FlexClone.

.. Verifique se o arquivo FlexClone ou FlexClone LUN está habilitado para exclusão automática usando o `volume file clone show-autodelete` comando. Saiba mais sobre `volume file clone show-autodelete` o link:https://docs.netapp.com/us-en/ontap-cli/volume-file-clone-show-autodelete.html["Referência do comando ONTAP"^]na .
+
O exemplo a seguir mostra que o FlexClone LUN lun1_clone está habilitado para exclusão automática:

+
[listing]
----
cluster1::> volume file clone show-autodelete -vserver vs1 -clone-path vol/vol1/lun1_clone
Vserver Name: vs1
Clone Path: vol/vol1/lun1_clone
**Autodelete Enabled: true**
----


+
Saiba mais sobre os comandos descritos neste procedimento no link:https://docs.netapp.com/us-en/ontap-cli/["Referência do comando ONTAP"^].


