---
permalink: volumes/control-io-performance-qos-task.html 
sidebar: sidebar 
keywords: control, monitor, i/o performance, flexvol volumes, using storage qos, qos, performance, throttle, flexvol, policy, policy group 
summary: Você pode controlar a performance de e/S para volumes do FlexVol usando grupos de políticas de QoS de storage para gerenciar workloads. 
---
= Controle e monitore o desempenho de e/S do FlexVol volume com a QoS de storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode controlar a performance de entrada/saída (e/S) a volumes FlexVol atribuindo volumes a grupos de políticas QoS de storage. Você pode controlar a performance de e/S para garantir que os workloads atinjam objetivos de performance específicos ou para controlar um workload que afeta negativamente outros workloads.

.Sobre esta tarefa
Os grupos de políticas aplicam um limite máximo de taxa de transferência (por exemplo, 100 MB/s). Você pode criar um grupo de políticas sem especificar uma taxa de transferência máxima, que permite monitorar o desempenho antes de controlar a carga de trabalho.

Também é possível atribuir SVMs, LUNs e arquivos a grupos de políticas.

Observe os seguintes requisitos sobre a atribuição de um volume a um grupo de políticas:

* O volume deve estar contido pelo SVM ao qual o grupo de políticas pertence.
+
Você especifica o SVM ao criar o grupo de políticas.

* A partir do ONTAP 9.18.1, você pode atribuir políticas de QoS a objetos contidos dentro de outros objetos que possuem políticas de QoS, como um volume contido em uma SVM.  Ao usar políticas de QoS aninhadas, a política mais restritiva é aplicada.
+
Em versões anteriores ao ONTAP 9.18.1, é possível atribuir políticas de QoS a objetos contidos dentro de outros objetos com políticas de QoS, mas esses objetos são rastreados separadamente pelo QoS e não interagem entre si.  Por exemplo, se você tiver uma SVM com um limite máximo de 50 IOPS e um FlexVol volume com um limite máximo de 100 IOPS, o FlexVol volume será limitado pelo limite máximo de 100 IOPS, mas não será contabilizado pelo QoS na carga de trabalho da SVM.



Para obter mais informações sobre como usar QoS de armazenamento, consulte link:../system-admin/index.html["Referência de administração do sistema"].

.Passos
. Use o `qos policy-group create` comando para criar um grupo de políticas.
. Use o `volume create` comando ou o `volume modify` comando com o `-qos-policy-group` parâmetro para atribuir um volume a um grupo de políticas.
. Use os `qos statistics` comandos para exibir dados de desempenho.
. Se necessário, use o `qos policy-group modify` comando para ajustar o limite máximo de taxa de transferência do grupo de políticas.


.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=qos+policy-group["grupo de políticas de qos"^]
* link: https://docs.netapp.com/us-en/ontap-cli/qos-policy-group-create.html [qos policy-group create]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["criar volume"^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-modify.html["modificação do volume"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=qos+statistics["estatísticas de qos"^]

