---
permalink: volumes/convert-directory-qtree-task.html 
sidebar: sidebar 
keywords: convert, directory, qtree 
summary: Se você tiver um diretório na raiz de um FlexVol volume que deseja converter para uma qtree, você deve migrar os dados contidos no diretório para uma nova qtree com o mesmo nome. 
---
= Converta um diretório em uma qtree
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você tiver um diretório na raiz de um FlexVol volume que deseja converter em uma qtree, precisará migrar os dados contidos no diretório para uma nova qtree com o mesmo nome, usando seu aplicativo cliente.

.Sobre esta tarefa
As etapas que você seguir para converter um diretório em uma qtree dependem do cliente que você usa. O processo a seguir descreve as tarefas gerais que você precisa concluir.

.Antes de começar
Não é possível excluir um diretório se ele estiver associado a um compartilhamento CIFS existente.

.Passos
. Renomeie o diretório a ser transformado em uma qtree.
. Crie uma nova qtree com o nome do diretório original.
. Use o aplicativo cliente para mover o conteúdo do diretório para a nova qtree.
. Exclua o diretório agora vazio.

