---
permalink: volumes/convert-directory-qtree-windows-client-task.html 
sidebar: sidebar 
keywords: convert, directory to a qtree, using, windows client, directory, qtree, windows 
summary: Para converter um diretório em uma qtree usando um cliente Windows, renomeie o diretório, crie uma qtree no sistema de armazenamento e mova o conteúdo do diretório para a qtree. 
---
= Converta um diretório em uma qtree usando um cliente Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para converter um diretório em uma qtree usando um cliente Windows, renomeie o diretório, crie uma qtree no sistema de armazenamento e mova o conteúdo do diretório para a qtree.

.Sobre esta tarefa
Você deve usar o Windows Explorer para este procedimento. Você não pode usar a interface de linha de comando do Windows ou o ambiente de prompt do dos.

.Passos
. Abra o Explorador do Windows.
. Clique na representação da pasta do diretório que deseja alterar.
+
[NOTE]
====
O diretório deve residir na raiz de seu volume contendo.

====
. No menu *File*, selecione *Renomear* para atribuir um nome diferente a este diretório.
. No sistema de armazenamento, use o `volume qtree create` comando para criar uma nova qtree com o nome original do diretório.
. No Windows Explorer, abra a pasta de diretório renomeada e selecione os arquivos dentro dela.
. Arraste esses arquivos para a representação da pasta da nova qtree.
+
[NOTE]
====
Quanto mais subpastas contidas na pasta que você está movendo, mais longa a operação de movimentação demora.

====
. No menu *Arquivo*, selecione *Excluir* para excluir a pasta de diretório renomeada, agora vazia.

