---
permalink: volumes/create-flexclone-snapmirror-concept.html 
sidebar: sidebar 
keywords: considerations, creating, flexclone volume, from snapmirror, source, destination, volume, flexclone, snapmirror, future 
summary: Você pode criar um volume FlexClone a partir do volume de origem ou destino em uma relação existente do SnapMirror, mas isso pode afetar futuras operações de replicação do SnapMirror. 
---
= Considerações para criar um volume FlexClone a partir de uma fonte ou volume de destino SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode criar um volume FlexClone a partir do volume de origem ou destino em uma relação de volume SnapMirror existente. No entanto, isso pode impedir que futuras operações de replicação do SnapMirror sejam concluídas com êxito.

A replicação pode não funcionar porque ao criar o volume FlexClone, você pode bloquear uma cópia Snapshot usada pelo SnapMirror. Se isso acontecer, o SnapMirror pára de replicar para o volume de destino até que o volume FlexClone seja destruído ou seja dividido de seu pai. Você tem duas opções para resolver este problema:

* Se você precisar do volume FlexClone temporariamente e puder acomodar uma parada temporária da replicação do SnapMirror, poderá criar o volume FlexClone e excluí-lo ou dividi-lo de seu pai quando possível.
+
A replicação SnapMirror continua normalmente quando o volume FlexClone é excluído ou é dividido de seu pai.

* Se uma interrupção temporária da replicação do SnapMirror não for aceitável, você poderá criar uma cópia Snapshot no volume de origem do SnapMirror e usá-la para criar o volume FlexClone. (Se você estiver criando o volume FlexClone a partir do volume de destino, aguarde até que a cópia Snapshot seja replicada para o volume de destino do SnapMirror.)
+
Esse método de criação de uma cópia Snapshot no volume de origem do SnapMirror permite criar o clone sem bloquear uma cópia Snapshot que esteja em uso pelo SnapMirror.


