---
permalink: volumes/create-flexclone-snapmirror-concept.html 
sidebar: sidebar 
keywords: considerations, creating, flexclone volume, from snapmirror, source, destination, volume, flexclone, snapmirror, future 
summary: Você pode criar um volume FlexClone a partir do volume de origem ou destino em uma relação existente do SnapMirror, mas isso pode afetar futuras operações de replicação do SnapMirror. 
---
= Saiba mais sobre como criar um volume FlexClone do ONTAP a partir de uma fonte do SnapMirror ou de um volume de destino
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode criar um volume FlexClone a partir do volume de origem ou do volume de destino em uma relação do SnapMirror de volume existente. Se você estiver usando uma versão do ONTAP anterior à ONTAP 9.12.1, no entanto, com relações do tipo DP que usam a política  `DPDefault`, isso pode impedir que futuras operações de replicação do SnapMirror sejam concluídas com sucesso.

A replicação pode não funcionar porque, ao criar o volume FlexClone, você pode bloquear um instantâneo usado pelo SnapMirror. Se isso acontecer, o SnapMirror pára de replicar para o volume de destino até que o volume FlexClone seja destruído ou seja dividido de seu pai. Você tem duas opções para resolver este problema:

* Se você precisar do volume FlexClone temporariamente e puder acomodar uma parada temporária da replicação do SnapMirror, poderá criar o volume FlexClone e excluí-lo ou dividi-lo de seu pai quando possível.
+
A replicação SnapMirror continua normalmente quando o volume FlexClone é excluído ou é dividido de seu pai.

* Se uma interrupção temporária da replicação do SnapMirror não for aceitável, você poderá criar um snapshot no volume de origem do SnapMirror e usá-lo para criar o volume FlexClone. (Se estiver criando o volume FlexClone a partir do volume de destino, aguarde até que esse instantâneo seja replicado para o volume de destino SnapMirror.)
+
Esse método de criação de um snapshot no volume de origem do SnapMirror permite criar o clone sem bloquear um snapshot que está em uso pelo SnapMirror.



Se você estiver usando relacionamentos XDP com ONTAP 9.12.1 ou posterior com a  `MirrorAllSnapshots`política, não deverá enfrentar esse problema.

Informações relacionadas: link:../data-protection/convert-snapmirror-version-flexible-task.html["Converta uma relação existente do tipo ONTAP SnapMirror DP para XDP"]
