---
permalink: volumes/deduplication-flexclone-files-luns-concept.html 
sidebar: sidebar 
keywords: deduplication, flexclone files, flexclone luns, files, luns, flexclone, efficiency, efficient, blocks, block 
summary: Para aumentar a eficiência do espaço de storage físico, crie um arquivo FlexClone ou LUN FlexClone do arquivo pai e do LUN pai em um volume habilitado para deduplicação. 
---
= Deduplicação com arquivos FlexClone e FlexClone LUNs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar com eficiência o espaço de storage físico dos blocos de dados criando um arquivo FlexClone ou LUN FlexClone do arquivo pai e LUN pai em um volume habilitado para deduplicação.

O mecanismo de compartilhamento de blocos usado pelos arquivos FlexClone e LUNs também é usado pela deduplicação. Você pode maximizar a economia de espaço em um FlexVol volume habilitando a deduplicação no volume e clonando o volume habilitado para deduplicação.

[NOTE]
====
Ao executar o `sis undo` comando em um volume habilitado para deduplicação, você não pode criar arquivos FlexClone e LUNs FlexClone dos arquivos pai e LUNs pai residentes nesse volume.

====
Saiba mais sobre os comandos descritos neste procedimento no link:https://docs.netapp.com/us-en/ontap-cli/["Referência do comando ONTAP"^].
