---
permalink: volumes/default-user-quotas-volume-affect-qtrees-concept.html 
sidebar: sidebar 
keywords: how, default, user, quotas, flexvol volume, affect, quotas, qtrees, volume 
summary: Se uma cota de usuário padrão for definida para um FlexVol volume, uma cota de usuário padrão será criada automaticamente para cada qtree contido nesse volume para o qual existe uma cota de árvore explícita ou derivada. 
---
= Como as cotas de usuário padrão em um FlexVol volume afetam as cotas para qtrees nesse volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se uma cota de usuário padrão for definida para um FlexVol volume, uma cota de usuário padrão será criada automaticamente para cada qtree contido nesse volume para o qual existe uma cota de árvore explícita ou derivada.

Se uma cota de usuário padrão na qtree já existir, ela permanecerá inalterada quando a cota de usuário padrão no volume for criada.

As cotas de usuário padrão criadas automaticamente no qtrees têm os mesmos limites que a cota de usuário padrão criada para o volume.

Uma cota de usuário explícita para uma qtree substitui (substitui os limites aplicados) a cota de usuário padrão criada automaticamente, da mesma forma que substitui uma cota de usuário padrão nessa qtree criada por um administrador.
