---
permalink: volumes/default-tree-quotas-volume-create-concept.html 
sidebar: sidebar 
keywords: default, tree quotas, flexvol volume, create, derived tree quotas, derived, quota, tree 
summary: Quando você cria uma cota de árvore padrão em um FlexVol volume, as cotas de árvore derivadas correspondentes são criadas automaticamente para cada qtree nesse volume. 
---
= Como as cotas de árvore padrão em um FlexVol volume criam cotas de árvore derivadas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando você cria uma cota de árvore padrão em um FlexVol volume, as cotas de árvore derivadas correspondentes são criadas automaticamente para cada qtree nesse volume.

Essas cotas de árvore derivadas têm os mesmos limites que a cota de árvore padrão. Se não existirem quotas adicionais, os limites têm os seguintes efeitos:

* Os usuários podem usar tanto espaço em uma qtree como eles são alocados para todo o volume (desde que eles não excedessem o limite para o volume usando espaço na raiz ou em outra qtree).
* Cada um dos qtrees pode crescer para consumir todo o volume.


A existência de uma cota de árvore padrão em um volume continua a afetar todos os novos qtrees que são adicionados ao volume. Cada vez que uma nova qtree é criada, uma cota de árvore derivada também é criada.

Como todas as cotas derivadas, as cotas de árvore derivadas exibem os seguintes comportamentos:

* São criados somente se o alvo ainda não tiver uma cota explícita.
* Aparecem nos relatórios de cota, mas não aparecem quando você mostra regras de cota com o `volume quota policy rule show` comando. Saiba mais sobre `volume quota policy rule show` o link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-policy-rule-show.html["Referência do comando ONTAP"^]na .


.Exemplo de cotas de árvores derivadas
Você tem um volume com três qtrees (proj1, proj2 e proj3) e a única cota de árvore é uma cota explícita na qtree proj1 que limita seu tamanho de disco a 10 GB. Se você criar uma cota de árvore padrão no volume e reinicializar cotas no volume, o relatório de cota agora contém quatro cotas de árvore:

[listing]
----
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1     proj1     tree    1           0B   10GB       1       -   proj1
vol1               tree    *           0B   20GB       0       -   *
vol1     proj2     tree    2           0B   20GB       1       -   proj2
vol1     proj3     tree    3           0B   20GB       1       -   proj3
...
----
A primeira linha mostra a cota explícita original na qtree proj1. Esta quota permanece inalterada.

A segunda linha mostra a nova cota de árvore padrão no volume. O especificador de cota asterisco (*) indica que é uma cota padrão. Essa cota é resultado da regra de cota que você criou.

As duas últimas linhas mostram novas cotas de árvores derivadas para os qtrees proj2 e proj3. O ONTAP criou automaticamente essas cotas como resultado da cota de árvore padrão no volume. Essas cotas de árvore derivadas têm o mesmo limite de disco de 20 GB que a cota de árvore padrão no volume. O ONTAP não criou uma cota de árvore derivada para a qtree proj1 porque a qtree proj1 já tinha uma cota explícita.
