---
permalink: volumes/delete-flexvol-task.html 
sidebar: sidebar 
keywords: delete, flexvol volume, flexvol, volume 
summary: Você pode usar a CLI do ONTAP para excluir um FlexVol volume que não seja mais necessário. 
---
= Eliminar um FlexVol volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode excluir um FlexVol volume que não seja mais necessário.

.Antes de começar
Nenhum aplicativo deve estar acessando os dados no volume que deseja excluir.

[NOTE]
====
Se eliminar acidentalmente um volume, consulte o artigo da base de dados de Conhecimento link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_use_the_Volume_Recovery_Queue["Como utilizar a fila de recuperação de volume"^].

====
.Passos
. Se o volume tiver sido montado, desmonte-o:
+
`volume unmount -vserver vserver_name -volume volume_name`

. Se o volume for parte de uma relação SnapMirror, exclua a relação usando o `snapmirror delete` comando.
. Se o volume estiver online, coloque o volume offline:
+
`volume offline -vserver vserver_name volume_name`

. Eliminar o volume:
+
`volume delete -vserver vserver_name volume_name`





== Resultado

O volume é excluído, juntamente com quaisquer políticas de cota associadas e qtrees.

.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/volume-unmount.html["desmontar o volume"]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["eliminar SnapMirror"]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-offline.html["volume off-line"]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-delete.html["eliminação do volume"]

