---
permalink: volumes/determine-space-used-flexclone-task.html 
sidebar: sidebar 
keywords: space, flexclone, volume, space, utilization, flexvol 
summary: É possível determinar o espaço usado por um volume FlexClone com base no tamanho nominal e na quantidade de espaço que ele compartilha com o FlexVol volume pai. 
---
= Determine o espaço usado por um volume FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível determinar o espaço usado por um volume FlexClone com base no tamanho nominal e na quantidade de espaço que ele compartilha com o FlexVol volume pai. Quando um volume FlexClone é criado, ele compartilha todos os dados com o volume pai. Embora o tamanho nominal do FlexVol volume seja o mesmo que o tamanho de seu pai, ele usa muito pouco espaço livre do agregado.

.Sobre esta tarefa
O espaço livre usado por um volume FlexClone recém-criado é de aproximadamente 0,5% de seu tamanho nominal. Esse espaço é usado para armazenar os metadados do volume FlexClone.

Os novos dados gravados no volume pai ou no FlexClone não são compartilhados entre os volumes. O aumento na quantidade de novos dados gravados no volume FlexClone leva a um aumento no espaço que o volume FlexClone requer do agregado que contém.

.Passo
. Determine o espaço físico real usado pelo volume FlexClone usando o `volume show` comando.
+
O exemplo a seguir mostra o espaço físico total usado pelo volume FlexClone:

+
[listing]
----

cluster1::> volume show -vserver vs01 -volume clone_vol1 -fields size,used,available,
percent-used,physical-used,physical-used-percent
vserver    volume     size  available  used   percent-used   physical-used     physical-used-percent
-------   ----------  ----  ---------  -----  ------------    -------------   ---------------------
vs01     clone_vol1   20MB   18.45MB   564KB       7%             196KB               1%
----
+
Saiba mais sobre `volume show` o link:https://docs.netapp.com/us-en/ontap-cli/volume-show.html["Referência do comando ONTAP"^]na .


