---
permalink: volumes/differences-hard-soft-threshold-quotas-concept.html 
sidebar: sidebar 
keywords: differences, hard, soft, threshold, quotas, quota, notification, prevent 
summary: As cotas rígidas impedem as operações, enquanto as cotas de limite e soft acionam notificações. 
---
= Diferenças entre cotas duras, macias e de limiares
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As cotas rígidas impedem operações enquanto as cotas flexíveis acionam notificações.

As cotas rígidas impõem um limite rígido aos recursos do sistema; qualquer operação que resultaria em exceder o limite falha. As seguintes configurações criam cotas rígidas:

* Parâmetro de limite do disco
* Parâmetro limit ficheiros


As cotas flexíveis enviam uma mensagem de aviso quando o uso de recursos atinge um determinado nível, mas não afetam as operações de acesso a dados, para que você possa tomar as medidas apropriadas antes que a cota seja excedida. As configurações a seguir criam cotas flexíveis:

* Limite para o parâmetro limite do disco
* Parâmetro de limite do disco flexível
* Parâmetro de limite de arquivos macios


As cotas de limite e disco flexível permitem que os administradores recebam mais de uma notificação sobre uma cota. Normalmente, os administradores definem o limite de disco para um valor que é apenas ligeiramente menor do que o limite de disco, de modo que o limite forneça um "aviso final" antes de as gravações começarem a falhar.
