---
permalink: volumes/disable-data-compression-volume-task.html 
sidebar: sidebar 
keywords: disable data compression 
summary: Você pode desativar a compressão de dados em um volume usando o comando volume Efficiency Modify. 
---
= Desative a compressão de dados em um volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode desativar a compressão de dados em um volume usando o `volume efficiency modify` comando.

.Sobre esta tarefa
Se você quiser desativar a compressão pós-processo, primeiro você deve desativar a compressão inline no volume.

.Passos
. Parar qualquer operação de eficiência de volume que esteja atualmente ativa no volume:
+
`volume efficiency stop`

. Desativar compressão de dados:
+
`volume efficiency modify`

+
Os dados compatados existentes permanecerão compatados no volume. Apenas as novas gravações que entram no volume não são comprimidas.



.Exemplos
O seguinte comando desativa a compressão em linha no volume VolA:

`volume efficiency modify -vserver vs1 -volume VolA -inline-compression false`

O seguinte comando desativa a compressão pós-processo e a compressão em linha no volume VolA:

`volume efficiency modify -vserver vs1 -volume VolA -compression false -inline-compression false`
