---
permalink: volumes/display-file-inode-usage-task.html 
sidebar: sidebar 
keywords: flexvol, file limit, inode, maximum 
summary: 'Determine se você precisa aumentar o número de inodes (públicos) para seus volumes FlexVol para evitar que eles atinjam seu limite de arquivos.' 
---
= Determine o uso de arquivos e inode para um volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os volumes FlexVol têm um número máximo de arquivos que podem conter. Você pode usar um comando CLI para determinar se você precisa aumentar o número de inodes (públicos) para seus volumes FlexVol para evitar que eles atinjam seu limite de arquivos.

.Sobre esta tarefa
Inodes públicos podem ser livres (não estão associados a um arquivo) ou usados (apontam para um arquivo). O número de inodes livres para um volume é o número total de inodes para o volume menos o número de inodes usados (o número de arquivos).

Se houver compartilhamentos no nível de qtree e no nível de volume no mesmo pool FlexVol ou SCVMM, os qtrees aparecerão como diretórios no compartilhamento FlexVol. Portanto, você precisa ter cuidado para não excluí-los acidentalmente.

.Passos
. Para exibir o uso de inode para um volume, digite o seguinte comando:
+
[source, cli]
----
volume show -vserver <SVM_name> -volume <volume_name> -fields files-used
----


.Exemplo
[listing]
----
cluster1::*> volume show -vserver vs1 -volume vol1 -fields files-used
Vserver Name: vs1
Files Used (for user-visible data): 98
----