---
permalink: volumes/enable-large-vol-file-support-task.html 
sidebar: sidebar 
keywords: create, modify, volume, large file, large volume 
summary: Você pode ativar o suporte para grandes volumes e arquivos quando criar um novo volume ou modificar um volume existente. 
---
= Ative o suporte de grande volume e arquivos grandes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.12,1 P2, você pode criar um novo volume ou modificar um volume existente para permitir suporte para um tamanho máximo de volume de 300TB e um tamanho máximo de arquivo (LUN) de 128TB.

.Antes de começar
* O ONTAP 9.12,1 P2 ou posterior está instalado no cluster.
* Se você estiver habilitando o suporte de grande volume no cluster de origem em uma relação do SnapMirror, você deve ter o ONTAP 9.12,1 P2 ou posterior instalado no cluster que hospeda o volume de origem, bem como o cluster que hospeda o volume de destino.
* Você é um administrador de cluster ou SVM.




== Crie um novo volume

.Passo
. Crie um volume com suporte de arquivos e volume grande habilitado:
+
[source, cli]
----
volume create -vserver <svm_name> -volume <volume_name> -aggregate <aggregate_name> -is-large-size-enabled true
----


.Exemplo
O exemplo a seguir cria um novo volume com suporte de grande volume e tamanho de arquivo ativado.

[listing]
----
volume create -vserver vs1 -volume big_vol1 -aggregate aggr1 -is-large-size-enabled true
----


== Modificar um volume existente

.Passo
. Modifique um volume para permitir o suporte a grandes volumes e arquivos:
+
[source, cli]
----
volume modify -vserver <svm_name> -volume <volume_name> -is-large-size-enabled true
----


.Exemplo
O exemplo a seguir modifica um volume existente para suportar grande volume e tamanho de arquivo.

[listing]
----
volume modify -vserver vs2 -volume data_vol -is-large-size-enabled true
----
.Informações relacionadas
* link:../volumes/create-volume-task.html["Crie um volume"]
* link:https://docs.netapp.com/us-en/ontap-cli/["Referência do comando"]

