---
permalink: volumes/enable-inline-data-compaction-fas-systems-task.html 
sidebar: sidebar 
keywords: enable, inline, data compaction, fas systems, hdd aggregate, volume efficiency 
summary: 'Permitir a compactação de dados in-line em sistemas FAS com agregados Flash Pool (híbridos) ou agregados HDD no nível de volume ou agregado.' 
---
= Permitir a compactação de dados in-line em sistemas FAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
YYYou pode permitir a compactação de dados in-line em sistemas FAS com agregados Flash Pool (híbridos) ou agregados HDD no nível do volume usando o `volume efficiency` comando cluster shell. A compactação de dados é desativada por padrão para volumes criados em sistemas FAS. Saiba mais sobre `volume efficiency` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume+efficiency["Referência do comando ONTAP"^]na .

.Sobre esta tarefa
Para permitir a compactação de dados in-line em um volume, sua `-space-guarantee` opção deve ser definida como `none`. Habilitar a compactação de dados em um volume em um agregado de HDD usa recursos adicionais de CPU.

.Passos
. Mude para o nível de privilégio avançado:
+
[source, cli]
----
set -privilege advanced
----
+
Saiba mais sobre `set` o link:https://docs.netapp.com/us-en/ontap-cli/set.html["Referência do comando ONTAP"^]na .

. Verifique o estado de compactação de dados dos volumes e agregados para o nó desejado:
+
[source, cli]
----
volume efficiency show -volume <volume_name>
----
+
Saiba mais sobre `volume efficiency show` o link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-show.html["Referência do comando ONTAP"^]na .

. Permitir a compactação de dados no volume:
+
[source, cli]
----
volume efficiency modify -volume <volume_name> -data-compaction true
----
+
Saiba mais sobre `volume efficiency modify` o link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-modify.html["Referência do comando ONTAP"^]na .

+
[NOTE]
====
Se a compactação de dados estiver definida como `false` para um agregado ou um volume, a compactação falhará. Ativar a compactação não compacta os dados existentes; apenas novas gravações no sistema são compactadas. O `volume efficiency start` comando contém mais informações sobre como compactar dados existentes. Saiba mais sobre `volume efficiency start` o link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-start.html["Referência do comando ONTAP"^]na .

====
. Veja as estatísticas de compactação:
+
[source, cli]
----
volume efficiency show -volume <volume_name>
----

