---
permalink: volumes/enable-storage-efficiency-visualization-concept.html 
sidebar: sidebar 
keywords: storage, efficiency, visualization, storage aggregate 
summary: Mostrar diferentes visualizações da eficiência de storage de todos os agregados em seu sistema. 
---
= Visualização de eficiência de storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Use o `storage aggregate show-efficiency` comando para exibir informações sobre a eficiência de storage de todos os agregados em seu sistema. Saiba mais sobre `storage aggregate show-efficiency` o link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-efficiency.html["Referência do comando ONTAP"^]na .

O `storage aggregate show-efficiency` comando tem três visualizações diferentes que podem ser invocadas passando opções de comando.



== Vista predefinida

A exibição padrão exibe a proporção geral para cada um dos agregados.

`cluster1::> storage aggregate show-efficiency`



== Vista detalhada

Chame a exibição detalhada com a `-details` opção de comando. Esta vista apresenta o seguinte:

* Relação de eficiência geral para cada um dos agregados.
* Taxa geral sem snapshots.
* Divisão de proporção para as seguintes tecnologias de eficiência: Deduplicação de volume, compressão de volume, snapshots, clones, compactação de dados e deduplicação in-line agregada.


`cluster1::> storage aggregate show-efficiency -details`



== Vista avançada

A vista avançada é semelhante à vista detalhada e apresenta detalhes lógicos e físicos utilizados.

Tem de executar este comando no nível avançado de privilégios. Alterne para privilégios avançados usando o `set -privilege advanced` comando.

O prompt de comando muda para `cluster::*>`.

`cluster1::> set -privilege advanced`

Invoque a visualização avançada com a `-advanced` opção de comando.

`cluster1::*> storage aggregate show-efficiency -advanced`

Para exibir taxas para um único agregado, invoque o comando individualmente `-aggregate _aggregate_name_`. Este comando pode ser executado no nível de administrador, bem como no nível de privilégio avançado.

`cluster1::> storage aggregate show-efficiency -aggregate aggr1`

Saiba mais sobre `set -privilege advanced` o link:https://docs.netapp.com/us-en/ontap-cli/set.html["Referência do comando ONTAP"^]na .
