---
permalink: volumes/enable-disable-background-deduplication-aff-task.html 
sidebar: sidebar 
keywords: manage, aggregate-level, background, deduplication, aff systems 
summary: Ative ou desative a deduplicação em nível agregado para volumes ou determine se o recurso está ativado. 
---
= Gerenciar a deduplicação em segundo plano em nível de agregado em sistemas AFF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A deduplicação em nível de agregado elimina blocos duplicados em volumes pertencentes ao mesmo agregado. A partir do ONTAP 9.3, você pode executar deduplicação em nível agregado em segundo plano em sistemas AFF. O recurso é habilitado por padrão para todos os volumes recém-criados e todos os volumes atualizados com deduplicação de fundo de volume ativada.

.Sobre esta tarefa
A operação é acionada automaticamente quando uma porcentagem grande suficiente do log de mudança foi preenchida. Nenhuma programação ou política está associada à operação.

A partir do ONTAP 9.4, os usuários do AFF também podem executar o verificador de deduplicação em nível agregado para eliminar duplicatas de dados existentes entre volumes no agregado. Pode utilizar o `storage aggregate efficiency cross-volume-dedupe start` comando com a `-scan-old-data=true` opção para iniciar o scanner:

[listing]
----
cluster-1::> storage aggregate efficiency cross-volume-dedupe start -aggregate aggr1 -scan-old-data true
----
A verificação de deduplicação pode ser demorada. Você pode querer executar a operação em horas fora do pico.

[NOTE]
====
A deduplicação em segundo plano em nível agregado às vezes é chamada de deduplicação em segundo plano entre volumes.

====
.Passos
. Gerenciar a deduplicação em segundo plano em nível agregado em sistemas AFF:
+
[cols="2*"]
|===
| Se você quiser... | Use este comando 


 a| 
Habilitar a deduplicação em segundo plano em nível de agregado
 a| 
`volume efficiency modify -vserver <vserver_name\> -volume <vol_name\> -cross-volume-background-dedupe true`



 a| 
Desativar a deduplicação em segundo plano em nível agregado
 a| 
`volume efficiency modify -vserver <vserver_name\> -volume <vol_name\> -cross-volume-background-dedupe false`



 a| 
Exibir o status de deduplicação em segundo plano no nível agregado
 a| 
`aggregate efficiency cross-volume-dedupe show`

|===

