---
permalink: volumes/features-supported-volume-rehost-concept.html 
sidebar: sidebar 
keywords: features, do not support, volume rehost 
summary: Existem vários recursos do ONTAP que não suportam o volume Rehost. Você deve estar ciente desses recursos antes de tentar uma operação de rehost. 
---
= Recursos não compatíveis com um rehost de volume no ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Existem vários recursos do ONTAP que não suportam o volume Rehost. Você deve estar ciente desses recursos antes de tentar uma operação de rehost.

Os recursos a seguir não são compatíveis com um rehost de volume:

* SVM DR
* Configurações do MetroCluster
+

NOTE: Clonar um volume como um volume FlexClone em um SVM diferente também não é compatível com configurações do MetroCluster.

* Volumes SnapLock
* Volumes de criptografia de volume NetApp (NVE) (em versões do ONTAP anteriores a 9,8)
+
Nas versões do ONTAP anteriores a 9,8, você deve descriptografar o volume antes de rehospedá-lo. As chaves de criptografia de volumes dependem das chaves do SVM. Se um volume for movido para outro SVM e a configuração de chave multitenant estiver habilitada no SVM de origem ou destino, o volume e as chaves SVM não corresponderão.

+
A partir do ONTAP 9,8, é possível hospedar novamente um volume com NVE.

* Volumes FlexGroup
* Clonar volumes

