---
permalink: volumes/flexclone-efficient-copies-concept.html 
sidebar: sidebar 
keywords: use, flexclone, volumes, create, efficient, copies, flexvol volumes 
summary: Os volumes FlexClone são cópias graváveis, com uso eficiente de espaço e ponto no tempo de um FlexVol volume pai que pode ser gerenciado para proteção de dados ou com outros fins. 
---
= Visão geral do uso do volume do FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os volumes FlexClone são cópias graváveis e pontuais de um FlexVol volume pai. Os volumes FlexClone usam espaço para uso eficiente, pois compartilham os mesmos blocos de dados com os volumes FlexVol pai para dados comuns. O instantâneo usado para criar um volume FlexClone também é compartilhado com o volume pai.

Você pode clonar um volume FlexClone existente para criar outro volume FlexClone. Você também pode criar um clone de um FlexVol volume que contenha LUNs e clones de LUN.

Você também pode dividir um volume FlexClone de seu volume pai. A partir do ONTAP 9.4, para volumes não garantidos em sistemas AFF, a operação dividida para volumes FlexClone compartilha os blocos físicos e não copia os dados. Portanto, a divisão de volumes FlexClone em sistemas AFF é mais rápida do que a operação de divisão FlexClone em outros sistemas FAS no ONTAP 9.4 e versões posteriores.

Você pode criar dois tipos de volumes FlexClone: Volumes FlexClone de leitura-gravação e volumes FlexClone de proteção de dados. Embora você possa criar um volume FlexClone de leitura e gravação de um FlexVol volume normal, use apenas um volume secundário do SnapVault para criar um volume FlexClone de proteção de dados.
