---
permalink: volumes/flexvol-reclaim-free-space-autodelete-concept.html 
sidebar: sidebar 
keywords: how, flexvol, volume, reclaim, free, space, autodelete, setting 
summary: Você pode habilitar a configuração de FlexVol volume para excluir automaticamente arquivos FlexClone e LUNs FlexClone e recuperar espaço livre no volume. 
---
= Volumes do FlexVol e recuperação de espaço livre com visão geral do projeto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pode ativar a definição de FlexVol volume para eliminar automaticamente ficheiros FlexClone e LUNs FlexClone. Ao ativar o serviço de correio eletrónico, pode recuperar uma quantidade alvo de espaço livre no volume quando um volume estiver quase cheio.

Você pode configurar um volume para começar a excluir automaticamente arquivos FlexClone e LUNs FlexClone quando o espaço livre no volume diminuir abaixo de um determinado valor limite e parar automaticamente de excluir clones quando uma quantidade de espaço livre no volume for recuperada. Embora não seja possível especificar o valor de limite que inicia a exclusão automática de clones, você pode especificar se um clone é elegível para exclusão e especificar a quantidade de espaço livre de destino para um volume.

Um volume exclui automaticamente arquivos FlexClone e LUNs FlexClone quando o espaço livre no volume diminui abaixo de um determinado limite e quando _ambos_ dos seguintes requisitos são atendidos:

* A funcionalidade de autodelete está ativada para o volume que contém os arquivos FlexClone e LUNs FlexClone.
+
Você pode ativar a capacidade de transferência de um FlexVol volume usando o `volume snapshot autodelete modify` comando. Você deve definir o `-trigger` parâmetro para `volume` ou `snap_reserve` para que um volume exclua automaticamente arquivos FlexClone e LUNs FlexClone. Saiba mais sobre `volume snapshot autodelete modify` o link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-autodelete-modify.html["Referência do comando ONTAP"^]na .

* A funcionalidade de configuração do sistema de áudio e vídeo é habilitada para os LUNs FlexClone e FlexClone.
+
Você pode ativar o arquivo FlexClone ou FlexClone LUN usando o `file clone create` comando com o `-autodelete` parâmetro. Como resultado, você pode preservar certos arquivos FlexClone e LUNs FlexClone, desativando o serviço de seleção de clones e garantindo que outras configurações de volume não substituam a configuração de clone. Saiba mais sobre `file clone create` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=file+clone+create["Referência do comando ONTAP"^]na .


