---
permalink: volumes/full-quota-reinitialization-required-concept.html 
sidebar: sidebar 
keywords: when, full, quota, reinitialization, required 
summary: Embora o redimensionamento de cotas seja mais rápido, você deve fazer uma reinicialização total da cota se fizer certas alterações pequenas ou extensas em suas cotas. 
---
= Quando é necessária uma reinicialização total da quota
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Embora o redimensionamento de cotas seja mais rápido, você deve fazer uma reinicialização total da cota se fizer certas alterações pequenas ou extensas em suas cotas.

É necessária uma reinicialização total da quota nas seguintes circunstâncias:

* Você cria uma cota para um destino que não tinha uma cota anteriormente (nem uma cota explícita nem uma derivada de uma cota padrão).
* Você altera o estilo de segurança de uma qtree de UNIX para misto ou NTFS.
* Você altera o estilo de segurança de uma qtree de misto ou NTFS para UNIX.
* Você remove usuários de um destino de cota com vários usuários ou adiciona usuários a um destino que já tenha vários usuários.
* Você faz mudanças extensas em suas cotas.


.Exemplo de alterações de cotas que exigem inicialização
Suponha que você tenha um volume que contenha três qtrees e as únicas cotas no volume são três cotas de árvore explícitas. Você decide fazer as seguintes alterações:

* Adicione uma nova qtree e crie uma nova cota de árvore para ela.
* Adicione uma cota de usuário padrão para o volume.


Ambas as alterações requerem uma inicialização completa da quota. O redimensionamento não torna as cotas efetivas.
