---
permalink: volumes/inline-storage-efficiency-enablement-aff-concept.html 
sidebar: sidebar 
keywords: inline, storage, efficiency, enabled, default, aff systems 
summary: Todos os recursos de eficiência de armazenamento em linha são habilitados por padrão em todos os volumes existentes e recém-criados em todos os sistemas AFF . 
---
= Eficiência de storage in-line habilitada por padrão em sistemas AFF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Por padrão, os recursos de eficiência de storage são ativados em todos os volumes recém-criados em sistemas AFF. Todos os recursos de eficiência de armazenamento em linha são habilitados por padrão em todos os volumes existentes e recém-criados em todos os sistemas AFF .

Os recursos de eficiência de storage incluem deduplicação in-line, deduplicação in-line entre volumes e compressão in-line, e são habilitados por padrão em sistemas AFF, conforme mostrado na tabela.

[NOTE]
====
O comportamento de compactação de dados em volumes AFF é habilitado por padrão.

====
[cols="4*"]
|===
| Condições de volume 3+| Recursos de eficiência de armazenamento habilitados por padrão 


 a| 
 a| 
Deduplicação in-line
 a| 
Deduplicação in-line entre volumes
 a| 
Compressão in-line



 a| 
Atualização do cluster
 a| 
Sim
 a| 
Sim
 a| 
Sim



 a| 
Transição do modo 7 do ONTAP para o Clustered ONTAP
 a| 
Sim
 a| 
Sim
 a| 
Sim



 a| 
Movimentação de volume
 a| 
Sim
 a| 
Sim
 a| 
Sim



 a| 
Volumes com provisionamento espesso
 a| 
Sim
 a| 
Não
 a| 
Sim



 a| 
Volumes criptografados
 a| 
Sim
 a| 
Não
 a| 
Sim

|===
As exceções a seguir se aplicam a um ou mais recursos de eficiência de storage in-line:

* Somente os volumes de leitura-gravação podem ser compatíveis com a capacitação padrão de eficiência de storage in-line.
* Os volumes com economia de compactação são omitidos da ativação da compactação in-line.
* Os volumes que têm a deduplicação pós-processo ativada são omitidos da ativação da compressão inline.
* Nos volumes em que a eficiência do volume é desativada, o sistema substitui as configurações de política de eficiência de volume existentes e a define para ativar a política somente inline.

