---
permalink: volumes/ls-command-space-usage-concept.html 
sidebar: sidebar 
keywords: how, ls command, accounts, space, usage 
summary: Um relatório de cota pode diferir da saída do comando ls que exibe apenas o tamanho de um arquivo e não inclui blocos indiretos usados pelo arquivo. 
---
= Disparidade entre o comando ls e o relatório de cota para uso de espaço
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando você usa o `ls` comando para exibir o conteúdo de um FlexVol volume montado em um cliente UNIX, os tamanhos de arquivo exibidos na saída podem diferir do uso de espaço exibido no relatório de cota para o volume, dependendo do tipo de blocos de dados para o arquivo.

A saída do `ls` comando exibe apenas o tamanho de um arquivo e não inclui blocos indiretos usados pelo arquivo. Quaisquer blocos vazios do arquivo também são incluídos na saída do comando.

Portanto, se um arquivo não tiver blocos vazios, o tamanho exibido pelo `ls` comando pode ser menor que o uso de disco especificado por um relatório de cota devido à inclusão de blocos indiretos no relatório de cota. Por outro lado, se o arquivo tiver blocos vazios, o tamanho exibido pelo `ls` comando pode ser mais do que o uso do disco especificado pelo relatório de cota.

A saída do `ls` comando exibe apenas o tamanho de um arquivo e não inclui blocos indiretos usados pelo arquivo. Quaisquer blocos vazios do arquivo também são incluídos na saída do comando.

.Exemplo da diferença entre o uso de espaço contabilizado pelo comando ls e um relatório de cota
O relatório de cota a seguir mostra um limite de 10 MB para uma qtree Q1:

[listing]
----

                                      ----Disk----  ----Files-----   Quota
  Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
  -------  --------  ------  -------  -----  -----  ------  ------   ---------
  vol1     q1          tree    user1   10MB  10MB        1       -   q1

...
----
Um arquivo presente na mesma qtree pode ter um tamanho que exceda o limite de cota quando visto de um cliente UNIX usando o `ls` comando, como mostrado no exemplo a seguir:

[listing]
----
[user1@lin-sys1 q1]$ ls -lh
-rwxr-xr-x  1 user1 nfsuser  **27M** Apr 09  2013 file1
----
Saiba mais sobre `ls` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=ls["Referência do comando ONTAP"^]na .
