---
permalink: volumes/manage-inline-data-compaction-aff-task.html 
sidebar: sidebar 
keywords: manage, inline, data, compaction, aff, systems 
summary: 'Controle a compactação de dados in-line em sistemas AFF ao nível do volume usando o comando "volume Efficiency Modify".' 
---
= Gerenciar a compactação de dados in-line em sistemas AFF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode controlar a compactação de dados in-line em sistemas AFF no nível do volume usando o `volume efficiency modify` comando. A compactação de dados é habilitada por padrão para todos os volumes em sistemas AFF.

.Antes de começar
A compactação de dados exige que a garantia de espaço de volume seja definida como `none`. Este é o padrão para sistemas AFF.

[NOTE]
====
A garantia de espaço padrão em volumes de proteção de dados que não são da AFF é definida como nenhum.

====
.Passos
. Para verificar a definição de garantia de espaço para o volume:
+
`volume show -vserver vserver_name -volume volume_name –fields space-guarantee`

. Para ativar a compactação de dados:
+
`volume efficiency modify -vserver vserver_name -volume volume_name -data-compaction true`

. Para desativar a compactação de dados:
+
`volume efficiency modify -vserver vserver_name -volume volume_name -data-compaction false`

. Para apresentar o estado da compactação de dados:
+
`volume efficiency show -instance`



.Exemplos
`cluster1::> volume efficiency modify -vserver vs1 -volume vol1 -data-compaction true` `cluster1::> volume efficiency modify -vserver vs1 -volume vol1 -data-compaction false`
