---
permalink: volumes/manage-aggregate-level-deduplication-aff-task.html 
sidebar: sidebar 
keywords: manage, aggregate-level, inline, deduplication, aff systems 
summary: Gerencie o recurso de deduplicação em nível agregado que elimina blocos duplicados em volumes pertencentes ao mesmo agregado. 
---
= Gerenciar a deduplicação in-line em nível de agregado em sistemas AFF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A deduplicação em nível de agregado elimina blocos duplicados em volumes pertencentes ao mesmo agregado. Você pode executar a desduplicação em nível de agregação em linha em sistemas AFF . O recurso é habilitado por padrão para todos os volumes recém-criados e todos os volumes atualizados com a deduplicação in-line de volume ativada.

.Sobre esta tarefa
A operação de deduplicação elimina blocos duplicados antes que os dados sejam gravados no disco. Somente os volumes com `space guarantee` o conjunto para `none` podem participar da deduplicação in-line em nível de agregado. Esta é a configuração padrão em sistemas AFF.

[NOTE]
====
A deduplicação in-line de nível agregado às vezes é chamada de deduplicação in-line entre volumes.

====
.Passo
. Gerenciar a deduplicação in-line em nível de agregado em sistemas AFF:
+
[cols="2*"]
|===
| Se você quiser... | Use este comando 


 a| 
Habilitar a deduplicação in-line em nível de agregado
 a| 
`volume efficiency modify -vserver vserver_name -volume vol_name -cross-volume-inline-dedupe true`



 a| 
Desativar a deduplicação in-line em nível de agregado
 a| 
`volume efficiency modify -vserver vserver_name -volume vol_name -cross-volume-inline-dedupe false`



 a| 
Exibir o status de deduplicação in-line em nível de agregado
 a| 
`volume efficiency config -volume vol_name`

|===


.Exemplos
O comando a seguir exibe o status de deduplicação in-line em nível agregado:

[listing]
----

wfit-8020-03-04::> volume efficiency config -volume choke0_wfit_8020_03_0
Vserver:                                      vs0
Volume:                                       choke0_wfit_8020_03_0
Schedule:                                     -
Policy:                                       choke_VE_policy
Compression:                                  true
Inline Compression:                           true
Inline Dedupe:                                true
Data Compaction:                              true
Cross Volume Inline Deduplication:            false
----