---
permalink: volumes/methods-delete-flexclone-files-luns-concept.html 
sidebar: sidebar 
keywords: methods, delete, flexclone, files, flexclone luns 
summary: Entenda quais métodos estão disponíveis para excluir arquivos FlexClone e LUNs FlexClone. 
---
= Métodos para excluir arquivos FlexClone e LUNs FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar vários métodos para excluir arquivos FlexClone e LUNs FlexClone. Entender quais métodos estão disponíveis ajuda você a Planejar como gerenciar clones.

Você pode usar os seguintes métodos para excluir arquivos FlexClone e LUNs FlexClone:

* Você pode configurar um FlexVol volume para excluir automaticamente clones com o recurso de transferência de dados ativado quando o espaço livre em um FlexVol volume diminuir abaixo de um determinado limite.
* Você pode configurar clientes para excluir clones usando o SDK de gerenciabilidade do NetApp.
* Você pode usar clientes para excluir clones usando os protocolos nas e SAN.
+
O método de exclusão mais lento é habilitado por padrão porque esse método não usa o SDK de gerenciamento do NetApp. No entanto, você pode configurar o sistema para usar o método de exclusão mais rápido quando você excluir arquivos FlexClone usando os `volume file clone deletion` comandos.


