---
permalink: volumes/modify-volume-efficiency-policy-task.html 
sidebar: sidebar 
keywords: modify, volume efficiency policy, volume, efficiency, policy 
summary: Você pode modificar uma política de eficiência de volume para executar a deduplicação e a compactação de dados por uma duração diferente ou alterar o cronograma de trabalho. 
---
= Modificar uma política de eficiência de volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode modificar uma política de eficiência de volume para executar a deduplicação e a compactação de dados por uma duração diferente ou alterar a programação da tarefa usando o `volume efficiency policy modify` comando. Saiba mais sobre `volume efficiency policy modify` o link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-policy-modify.html["Referência do comando ONTAP"^]na .

.Passos
. Use o `volume efficiency policy modify` comando para modificar uma política de eficiência de volume.


.Exemplos
O comando a seguir modifica a política de eficiência de volume chamada policy1 para ser executada a cada hora:

`volume efficiency policy modify -vserver vs1 -policy policy1 -schedule hourly`

O comando a seguir modifica uma política de eficiência de volume chamada pol2 para o limite de 30%:

`volume efficiency policy modify -vserver vs1 -policy pol1 -type threshold -start-threshold-percent 30%`
