---
permalink: volumes/non-space-reserved-luns-thin-provisioned-concept.html 
sidebar: sidebar 
keywords: configuration, settings, non-space-reserved, files, luns, thin-provisioned, volumes 
summary: A combinação de configuração de FlexVol volume e arquivo ou LUN requer que o storage seja alocado no gerenciamento de espaço livre ativo e inicial para evitar a falta de espaço. 
---
= Configurações para arquivos não reservados ao espaço ou LUNs com volumes provisionados com thin
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Essa combinação de configuração de FlexVol volume e arquivo ou LUN exige que a menor quantidade de storage seja alocada antes, mas requer gerenciamento ativo de espaço livre para evitar erros devido à falta de espaço.

As seguintes configurações são necessárias para configurar um LUN ou arquivos não reservados ao espaço em um volume provisionado com thin:

[cols="2*"]
|===
| Definição do volume | Valor 


 a| 
Garantia
 a| 
Nenhum



 a| 
Reserva fracionária
 a| 
0



 a| 
Reserva do Snapshot
 a| 
Qualquer



 a| 
snapshot Autodelete
 a| 
Opcional



 a| 
Crescimento automático
 a| 
Opcional

|===
[cols="2*"]
|===
| Configuração de arquivo ou LUN | Valor 


 a| 
Reserva de espaço
 a| 
Desativado

|===


== Considerações adicionais

Quando o volume ou agregado ficar sem espaço, as operações de gravação no arquivo ou LUN podem falhar.

Se você não quiser monitorar ativamente o espaço livre tanto para o volume quanto para o agregado, ative o crescimento automático para o volume e defina o tamanho máximo para o volume como o tamanho do agregado. Nessa configuração, você deve monitorar ativamente o espaço livre agregado, mas não precisa monitorar o espaço livre no volume.
