---
permalink: volumes/obtain-qtree-junction-path-task.html 
sidebar: sidebar 
keywords: obtain, qtree, junction, path 
summary: Você pode montar uma qtree individual obtendo o caminho de junção ou caminho de namespace da qtree. 
---
= Obtenha um caminho de junção de qtree
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode montar uma qtree individual obtendo o caminho de junção ou caminho de namespace da qtree. O caminho de qtree exibido pelo comando CLI `qtree show -instance` é do formato `/vol/<volume_name>/<qtree_name>`. No entanto, esse caminho não se refere ao caminho de junção ou caminho de namespace da qtree.

Saiba mais sobre `qtree show` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=qtree+show["Referência do comando ONTAP"^]na .

.Sobre esta tarefa
Você precisa saber o caminho de junção do volume para obter o caminho de junção ou caminho de namespace da qtree.

.Passos
. Use o `vserver volume junction-path` comando para obter o caminho de junção de um volume.
+
O exemplo a seguir exibe o caminho de junção do volume chamado vol1 localizado na máquina virtual de armazenamento (SVM) chamada vs0:

+
[listing]
----
cluster1::> volume show -volume vol1 -vserver vs0 -fields junction-path

------- ------ -------------

vs0 vol1 /vol1
----
+
A partir da saída acima, o caminho de junção do volume é `/vol1`. Como qtrees são sempre enraizados no volume, o caminho de junção ou o caminho do namespace da qtree será `/vol1/qtree1`.



Saiba mais sobre `vserver volume junction-path` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+volume+junction-path["Referência do comando ONTAP"^]na .
