---
permalink: volumes/prevent-flexclone-file-lun-automatic-deleted-task.html 
sidebar: sidebar 
keywords: prevent, specific, flexclone, file, or flexclone, lun, from automatically, deleted 
summary: Se você tiver arquivos FlexClone ou LUNs FlexClone específicos que deseja preservar, poderá excluí-los do processo de exclusão automática do FlexClone. 
---
= Impedir a eliminação automática de um ficheiro FlexClone ou LUN FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você configurar um FlexVol volume para excluir automaticamente arquivos FlexClone e LUNs FlexClone, qualquer clone que atenda aos critérios especificados poderá ser excluído. Se você tiver arquivos FlexClone ou LUNs FlexClone específicos que deseja preservar, poderá excluí-los do processo de exclusão automática do FlexClone.

.Antes de começar
Uma licença FlexClone deve ser instalada. Esta licença está incluída no link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"].

.Sobre esta tarefa
Quando você cria um arquivo FlexClone ou LUN FlexClone, por padrão, a configuração de ciclo de vida para o clone é desativada. Os arquivos do FlexClone e os LUNs do FlexClone com o recurso de configuração de ciclo de vida desativado são preservados quando você configura um FlexVol volume para excluir automaticamente clones para recuperar espaço no volume.

[NOTE]
====
Se você definir o `commitment` nível no volume como `try` ou `disrupt`, poderá preservar individualmente arquivos FlexClone ou LUNs FlexClone específicos desativando o modo de exibição de dados para esses clones. No entanto, se você definir o `commitment` nível no volume como `destroy` e as listas destruir incluir `lun_clone,file_clone`, a configuração de volume substituirá a configuração clone e todos os arquivos FlexClone e FlexClone LUNs poderão ser excluídos independentemente da configuração de ciclo de vida dos clones.

====
.Passos
. Evite que um arquivo FlexClone específico ou LUN FlexClone seja excluído automaticamente usando o `volume file clone autodelete` comando.
+
O exemplo a seguir mostra como você pode desativar o FlexClone LUN lun1_clone contido no vol1:

+
[listing]
----
cluster1::> volume file clone autodelete -vserver vs1 -volume vol1 -clone-path lun1_clone -enable false
----
+
Um arquivo ou LUN FlexClone com o sistema de diagnóstico guiado por sintomas (FlexClone) desativado não pode ser excluído automaticamente para recuperar espaço no volume.

. Verifique se o arquivo FlexClone ou FlexClone LUN está desabilitado usando o `volume file clone show-autodelete` comando.
+
O exemplo a seguir mostra que o FlexClone lun lun1_clone é falso:

+
[listing]
----
cluster1::> volume file clone show-autodelete -vserver vs1 -clone-path vol/vol1/lun1_clone
															Vserver Name: vs1
															Clone Path: vol/vol1/lun1_clone
															Autodelete Enabled: false
----

