---
permalink: volumes/qtrees-partition-your-volumes-concept.html 
sidebar: sidebar 
keywords: use, qtrees, partition, flexvol volumes 
summary: Qtrees permitem que você particione seus volumes FlexVol em segmentos menores que você pode gerenciar individualmente. Você pode usar qtrees para gerenciar cotas, estilo de segurança e plocks CIFS. 
---
= Qtrees e particionamento FlexVol volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Qtrees permitem que você particione seus volumes FlexVol em segmentos menores que você pode gerenciar individualmente. Você pode usar qtrees para gerenciar cotas, estilo de segurança e plocks CIFS.

O ONTAP cria uma qtree padrão, chamada _qtree0_, para cada volume. Se você não colocar dados em uma qtree, ele reside no qtree0.

Os nomes de Qtree não devem ter mais de 64 carateres.

Diretórios não podem ser movidos entre qtrees. Somente arquivos podem ser movidos entre qtrees.

Se você criar compartilhamentos em nível de qtree e em nível de volume no mesmo pool FlexVol ou SCVMM, o qtrees aparecerá como diretórios no compartilhamento FlexVol. Portanto, você precisa ter cuidado para não excluí-los acidentalmente.
