---
permalink: volumes/quotas-special-windows-groups-concept.html 
sidebar: sidebar 
keywords: how quotas work, special windows groups 
summary: Existem vários grupos especiais do Windows que processam cotas de forma diferente dos outros grupos do Windows. Você deve entender como as cotas são aplicadas para esses grupos especiais. 
---
= Como as cotas funcionam com grupos especiais do Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Existem vários grupos especiais do Windows que processam cotas de forma diferente dos outros grupos do Windows. Você deve entender como as cotas são aplicadas para esses grupos especiais.

[NOTE]
====
O ONTAP não suporta cotas de grupo com base em IDs de grupo do Windows. Se você especificar um ID de grupo do Windows como destino de cota, a cota será considerada uma cota de usuário.

====
.Todos
Quando o destino da cota é o grupo todos, um arquivo com uma ACL mostrando que o proprietário é todos é contado sob o SID para todos.

.CRIAR/Administradores
Quando o alvo de cota é o grupo BUILTIN/Administradores, a entrada é considerada uma cota de usuário e é usada apenas para rastreamento. Não é possível impor restrições a BUILTIN/Administradores. Se um membro do BUILTIN/Administradores criar um arquivo, o arquivo é de propriedade de BUILTIN/Administradores e é contado sob o SID para BUILTIN/Administradores (não o SID pessoal do usuário).
