---
permalink: volumes/quotas-flexclone-files-luns-concept.html 
sidebar: sidebar 
keywords: how quotas work, flexclone files, flexclone luns 
summary: Você deve estar familiarizado com como as cotas funcionam com arquivos FlexClone e LUNs FlexClone antes de usá-los. 
---
= Como as cotas funcionam com arquivos FlexClone e LUNs FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve estar familiarizado com como as cotas funcionam com arquivos FlexClone e LUNs FlexClone antes de usá-los.

Os limites de cota são aplicados no tamanho lógico total dos arquivos FlexClone ou LUNs FlexClone. As operações de clonagem não falham no compartilhamento de blocos, mesmo que isso faça com que as cotas sejam excedidas.

Quando você cria um arquivo FlexClone ou FlexClone LUN, as cotas não reconhecem nenhuma economia de espaço. Por exemplo, se você criar um arquivo FlexClone de um arquivo pai de 10 GB, você estará usando apenas 10 GB de espaço físico, mas a utilização da cota será registrada como 20 GB (10 GB para o pai e 10 GB para o arquivo FlexClone).

Se a criação de um arquivo FlexClone ou LUN resultar na ultrapassagem da cota de grupo ou usuário, a operação de clone será bem-sucedida desde que o FlexVol volume tenha espaço suficiente para manter os metadados para o clone. No entanto, a cota para esse usuário ou grupo está sobrsubscrita.
