---
permalink: volumes/quotas-applied-root-user-concept.html 
sidebar: sidebar 
keywords: quotas applied, root user 
summary: 'O usuário root (UID-0) em clientes UNIX está sujeito a cotas de árvore, mas não a cotas de usuário ou grupo. Isso permite que o usuário root tome ações em nome de outros usuários que, de outra forma, seriam impedidas por uma cota.' 
---
= Como as cotas são aplicadas ao usuário raiz
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O usuário root (UID-0) em clientes UNIX está sujeito a cotas de árvore, mas não a cotas de usuário ou grupo. Isso permite que o usuário root tome ações em nome de outros usuários que, de outra forma, seriam impedidas por uma cota.

Quando o usuário root realiza uma alteração de propriedade de arquivo ou diretório ou outra operação (como o comando UNIX `chown`) em nome de um usuário com menos Privileges, o ONTAP verifica as cotas com base no novo proprietário, mas não relata erros ou interrompe a operação, mesmo que as restrições de cota rígida do novo proprietário sejam excedidas. Isso pode ser útil quando uma ação administrativa, como a recuperação de dados perdidos, resulta em exceder temporariamente as cotas.

[NOTE]
====
Depois que a transferência de propriedade é realizada, no entanto, um sistema cliente irá relatar um erro de espaço em disco se o usuário tentar alocar mais espaço em disco enquanto a cota ainda é excedida.

====
.Informações relacionadas
* link:../volumes/quotas-applied-concept.html["Como as cotas são aplicadas"]
* link:../volumes/quotas-applied-users-multiple-ids-concept.html["Como as cotas são aplicadas a usuários com vários IDs"]

