---
permalink: volumes/quota-targets-types-concept.html 
sidebar: sidebar 
keywords: quotas, quota targets, quota types 
summary: Cada cota tem um tipo específico. O destino de cota é derivado do tipo e especifica o usuário, grupo ou qtree ao qual os limites de cota são aplicados. 
---
= Cotas e tipos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada cota tem um tipo específico. O destino de cota é derivado do tipo e especifica o usuário, grupo ou qtree ao qual os limites de cota são aplicados.

A tabela a seguir lista as metas de cota, os tipos de cotas a que cada meta de cota está associada e como cada meta de cota é representada.

[cols="15,15,35,35"]
|===


| Destino de cota | Tipo de cota | Como o alvo é representado | Notas 


 a| 
utilizador
 a| 
quota de utilizador
 a| 
Nome de utilizador UNIX UID UNIX

Um arquivo ou diretório cujo UID corresponde ao usuário

Nome de utilizador do Windows no formato pré-Windows 2000

Windows SID

Um arquivo ou diretório com uma ACL de propriedade do SID do usuário
 a| 
As cotas de usuário podem ser aplicadas para um volume ou qtree específico.



 a| 
grupo
 a| 
cota de grupo
 a| 
Nome do grupo UNIX GID

Um arquivo ou diretório cujo GID corresponde ao grupo
 a| 
As cotas de grupo podem ser aplicadas para um volume ou qtree específico.


NOTE: O ONTAP não aplica cotas de grupo com base em IDs do Windows.



 a| 
qtree
 a| 
cota de árvore
 a| 
nome de qtree
 a| 
As cotas de árvore são aplicadas a um volume específico e não afetam qtrees em outros volumes.



 a| 
`""`
 a| 
cota de usuário quotagroup

cota de árvore
 a| 
Aspas duplas (""")
 a| 
Um alvo de cota de "" denota uma quota _default_. Para cotas padrão, o tipo de cota é determinado pelo valor do campo tipo.

|===