---
permalink: volumes/quotas-applied-users-multiple-ids-concept.html 
sidebar: sidebar 
keywords: how, quotas are applied, users, multiple ids 
summary: Um usuário pode ser representado por vários IDs. Você pode definir uma única cota de usuário para tal usuário especificando uma lista de IDs como o destino da cota. Um arquivo de propriedade de qualquer um desses IDs está sujeito à restrição da cota de usuário. 
---
= Como as cotas são aplicadas a usuários com vários IDs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um usuário pode ser representado por vários IDs. Você pode definir uma única cota de usuário para tal usuário especificando uma lista de IDs como o destino da cota. Um arquivo de propriedade de qualquer um desses IDs está sujeito à restrição da cota de usuário.

Suponha que um usuário tenha o UID UNIX `20` e os IDs do Windows `corp\john_smith` e `engineering\jsmith`. Para esse usuário, você pode especificar uma cota em que o destino da cota é uma lista de UID e IDs do Windows. Quando esse usuário grava no sistema de armazenamento, a cota especificada se aplica, independentemente de a gravação ter origem em UID `20`, `corp\john_smith` ou `engineering\jsmith`.

Observe que regras de cota separadas são consideradas alvos separados, mesmo que os IDs pertençam ao mesmo usuário. Por exemplo, para o mesmo usuário, você pode especificar uma cota que limita UID `20` a 1GBMB de espaço em disco e outra cota que limita corp john_smith a 2GBMB de espaço em disco, mesmo que ambos os IDs representem o mesmo usuário. O ONTAP aplica cotas a UID `20` e `corp\john_smith` separadamente. Nesse caso, não são aplicados limites ao `engineering\jsmith`, mesmo que os limites sejam aplicados aos outros IDs usados pelo mesmo usuário.

.Informações relacionadas
* link:../volumes/quotas-applied-concept.html["Como as cotas são aplicadas"]
* link:../volumes/quotas-applied-root-user-concept.html["Como as cotas são aplicadas ao usuário raiz"]

