---
permalink: volumes/rehost-volume-another-svm-task.html 
sidebar: sidebar 
keywords: rehost, volume, from one SVM to another SVM 
summary: Uma operação de rehost de volume permite reatribuir um volume nas ou SAN de um SVM para outro SVM, sem exigir uma cópia SnapMirror. 
---
= Prepare-se para rehospedar um volume de um SVM para outro SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Uma operação de rehost de volume permite reatribuir um volume nas ou SAN de um SVM para outro SVM, sem exigir uma cópia SnapMirror. O procedimento exato de rehost depende do protocolo de acesso do cliente usado e do tipo de volume. O rehost de volume é uma operação que causa interrupções no acesso aos dados e no gerenciamento de volumes.

Antes de rehospedar um volume de um SVM para outro, você precisa estar em conformidade com as seguintes condições:

* O volume deve estar online
* O protocolo de volume deve ser SAN ou nas
+
** Para os volumes do protocolo nas, o volume não deve fazer parte do caminho de junção e deve ser desmontado


* Se o volume estiver em um relacionamento SnapMirror, o relacionamento deve ser excluído, seguido de liberar as informações de relacionamento somente ou quebrado antes do rehost de volume
+
** Você pode ressincronizar a relação SnapMirror após a operação de rehost de volume


* O subtipo vserver deve ser o mesmo para SVMs de origem e destino
+
** Os volumes só podem ser rehospedados entre SVMs do mesmo subtipo


* O volume não pode ser pai FlexClone ou FlexClone
+
** FlexClones devem ser divididos antes de rehospedar o volume pai ou clone



