---
permalink: volumes/rehost-volume-another-svm-task.html 
sidebar: sidebar 
keywords: rehost, volume, from one SVM to another SVM 
summary: Uma operação de rehost de volume permite reatribuir um volume nas ou SAN de um SVM para outro SVM, sem exigir uma cópia SnapMirror. 
---
= Prepare-se para rehospedar um volume de um SVM para outro SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Uma operação de rehost de volume permite reatribuir um volume nas ou SAN de um SVM para outro SVM, sem exigir uma cópia SnapMirror. O procedimento exato de rehost depende do protocolo de acesso do cliente usado e do tipo de volume. O rehost de volume é uma operação que causa interrupções no acesso aos dados e no gerenciamento de volumes.

Antes de rehospedar um volume de um SVM para outro, você precisa estar em conformidade com as seguintes condições:

* O volume deve estar online.
* Protocolo SAN ou nas
+
Para o protocolo nas, o volume deve ser desmontado.

* Se o volume estiver em um relacionamento SnapMirror, o relacionamento deve ser excluído ou quebrado antes do rehost do volume.
+
Você pode ressincronizar a relação SnapMirror após a operação de rehost de volume.


