---
permalink: volumes/relocate-root-volumes-new-aggregates-task.html 
sidebar: sidebar 
keywords: relocate, root volumes, new aggregates 
summary: O procedimento de substituição de raiz migra o agregado de raiz atual para outro conjunto de discos sem interrupção. 
---
= Realocar um volume raiz para novos agregados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O procedimento de substituição de raiz migra o agregado de raiz atual para outro conjunto de discos sem interrupção. Pode ser necessário executar isso como parte de um processo de substituição de disco ou manutenção preventiva.

.Sobre esta tarefa
Você pode alterar o local do volume raiz para um novo agregado nos seguintes cenários:

* Quando os agregados de raiz não estão no disco que preferir
* Quando pretender reorganizar os discos ligados ao nó
* Quando estiver a efetuar uma substituição de prateleira das prateleiras de disco EOS


.Passos
. Realocar o agregado raiz:
+
`system node migrate-root -node node_name -disklist disk_list -raid-type raid_type`

+
** *-node*
+
Especifica o nó que possui o agregado raiz que você deseja migrar.

** *-disklist*
+
Especifica a lista de discos nos quais o novo agregado raiz será criado. Todos os discos precisam ser sobressalentes e de propriedade do mesmo nó. O número mínimo de discos necessário depende do tipo RAID.

** *-raid-type*
+
Especifica o tipo RAID do agregado raiz. O valor padrão é `raid-dp`. Este é o único tipo suportado no modo avançado.



. Monitorize o progresso do trabalho:
+
`job show -id jobid -instance`



.Resultados
Se todas as pré-verificações forem bem-sucedidas, o comando iniciará uma tarefa de substituição de volume raiz e será encerrado.
