---
permalink: volumes/resume-efficiency-operation-checkpoint-task.html 
sidebar: sidebar 
keywords: resume, halted, efficiency, operation 
summary: Se uma operação de eficiência for interrompida pelo sistema, você pode retomar a operação de eficiência no mesmo ponto. 
---
= Retomar uma operação de eficiência parada
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se uma operação de eficiência for interrompida devido a uma parada do sistema, interrupção do sistema ou reinicialização, você poderá retomar a operação de eficiência a partir do mesmo ponto em que foi interrompida. Isso ajuda a economizar tempo e recursos, não sendo necessário reiniciar a operação desde o início.

.Sobre esta tarefa
Se você ativou apenas a deduplicação no volume, a deduplicação é executada nos dados. Se você habilitou a deduplicação e a compactação de dados em um volume, a compactação de dados será executada primeiro, seguida pela deduplicação.

Você pode ver os detalhes do ponto de verificação de um volume usando o `volume efficiency show` comando. Saiba mais sobre `volume efficiency show` o link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-show.html["Referência do comando ONTAP"^]na .

Por padrão, as operações de eficiência são retomadas a partir de pontos de verificação. No entanto, se um ponto de verificação correspondente a uma operação de eficiência anterior (a fase em que o `volume efficiency start`` comando -scan-old-data é executado) for superior a 24 horas, então a operação de eficiência não será retomada do ponto de verificação anterior automaticamente. Neste caso, a operação de eficiência começa desde o início. No entanto, se você souber que mudanças significativas não ocorreram no volume desde a última varredura, você pode forçar a continuação do ponto de verificação anterior usando a `-use-checkpoint` opção.

.Passos
. Use o `volume efficiency start` comando com a `-use-checkpoint` opção para retomar uma operação de eficiência.
+
O seguinte comando permite retomar uma operação de eficiência em novos dados no volume VolA:

+
`volume efficiency start -vserver vs1 -volume VolA -use-checkpoint true`

+
O seguinte comando permite retomar uma operação de eficiência em dados existentes no volume VolA:

+
`volume efficiency start -vserver vs1 -volume VolA -scan-old-data true -use-checkpoint true`

+
Saiba mais sobre `volume efficiency start` o link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-start.html["Referência do comando ONTAP"^]na .


