---
permalink: volumes/rules-node-root-volumes-aggregates-concept.html 
sidebar: sidebar 
keywords: restrictions, rules, governing, node root volumes, root aggregates 
summary: Você deve estar ciente das restrições que regem o volume raiz e o agregado raiz de um nó. 
---
= Restrições em volumes de raiz de nós e agregados de raiz
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve estar ciente das restrições que regem o volume raiz e o agregado raiz de um nó.


NOTE: O volume raiz de um nó contém diretórios e arquivos especiais para o nó. O volume raiz está contido no agregado raiz.

O volume raiz de um nó é um FlexVol volume instalado na fábrica ou pelo software de configuração. Ele é reservado para arquivos de sistema, arquivos de log e arquivos principais. O nome do diretório é `/mroot`, que é acessível somente através do systemshell pelo suporte técnico. O tamanho mínimo para o volume raiz de um nó depende do modelo da plataforma.

* As seguintes regras regem o volume raiz do nó:
+
** A menos que o suporte técnico o instrua a fazê-lo, não modifique a configuração ou o conteúdo do volume raiz.
** Não armazene dados do usuário no volume raiz.
+
Armazenar dados de usuário no volume raiz aumenta o tempo de giveback de storage entre nós em um par de HA.

** Você pode mover o volume raiz para outro agregado.
+
link:relocate-root-volumes-new-aggregates-task.html["Realocação de volumes raiz para novos agregados"]



* O agregado raiz é dedicado apenas ao volume raiz do nó.
+
O ONTAP impede que você crie outros volumes no agregado raiz.



https://hwu.netapp.com["NetApp Hardware Universe"^]
