---
permalink: volumes/run-efficiency-operations-scheduling-task.html 
sidebar: sidebar 
keywords: run, modify, scheduling, efficiency, operations, deduplication, data, compression 
summary: Modifique o agendamento de operações de deduplicação ou compressão de dados em um volume. 
---
= Execute uma operação de eficiência usando o agendamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível modificar o agendamento de operações de deduplicação ou compressão de dados em um volume. As opções de configuração de uma política de programação e eficiência de volume são mutuamente exclusivas.

.Sobre esta tarefa
Esta operação é efetuada através do `volume efficiency modify` comando.

.Passos
. Use o `volume efficiency modify` comando para modificar o agendamento de operações de deduplicação ou compressão de dados em um volume.


.Exemplos
O comando a seguir modifica o agendamento de operações de eficiência para que o VolA seja executado às 11 horas, de segunda a sexta-feira:

`volume efficiency modify -vserver vs1 -volume VolA -schedule mon-fri@23`

.Informações relacionadas
* link:run-efficiency-operations-depending-new-data-task.html["Execute operações de eficiência dependendo da quantidade de novos dados gravados"]

