---
permalink: volumes/run-efficiency-operations-depending-new-data-task.html 
sidebar: sidebar 
keywords: run deduplication based on new data, run data compression based on new data, efficiency operation, written 
summary: Você pode modificar o cronograma de operação de eficiência para executar a deduplicação ou a compactação de dados quando o número de novos blocos gravados no volume após a operação de eficiência anterior exceder uma porcentagem de limite especificada. Isto aplica-se se a operação de eficiência anterior foi realizada manualmente ou programada. 
---
= Execute uma operação de eficiência com base na quantidade de novos dados gravados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode modificar o cronograma de operação de eficiência para executar a deduplicação ou a compactação de dados quando o número de novos blocos gravados no volume após a operação de eficiência anterior exceder uma porcentagem de limite especificada. Isto aplica-se se a operação de eficiência anterior foi realizada manualmente ou programada.

.Sobre esta tarefa
Se a `schedule` opção estiver definida como `auto`, a operação de eficiência programada será executada quando a quantidade de novos dados exceder a porcentagem especificada. O valor de limite padrão é 20%. Esse valor limite é a porcentagem do número total de blocos já processados pela operação de eficiência.

.Passos
. Use o `volume efficiency modify` comando com a `auto@num` opção para modificar o valor percentual de limiar.
+
`num` é um número de dois dígitos para especificar a porcentagem.



.Exemplo
O comando a seguir modifica o valor percentual de limiar para 30% para o volume VolA:

`volume efficiency modify -vserver vs1 -volume -VolA -schedule auto@30`

.Informações relacionadas
* link:run-efficiency-operations-scheduling-task.html["Execute operações de eficiência usando o agendamento"]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-modify.html["modificação da eficiência de volume"^]

