---
permalink: volumes/set-efficiency-mode-task.html 
sidebar: sidebar 
keywords: enable, temperature, sensitive, storage, efficiency, mode, performance mode, efficient mode, set, System Manager, higher efficiency 
summary: A partir do ONTAP 9.10,1, você pode definir o modo de eficiência de storage ao criar um novo volume AFF. 
---
= Definir o modo de eficiência de armazenamento durante a criação de volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.10,1, você pode definir o modo de eficiência de storage ao criar um novo volume AFF.

.Sobre esta tarefa
Você pode controlar o modo de eficiência de armazenamento em um novo volume AFF usando o parâmetro `-storage-efficiency-mode`. Você pode escolher entre duas opções para definir o modo de eficiência de armazenamento: `default` ou `efficient`. O modo de eficiência de armazenamento que você escolher depende de se deseja maior desempenho ou maior eficiência de armazenamento no volume. O parâmetro `-storage-efficiency-mode` Não é compatível com volumes que não sejam AFF ou com volumes de proteção de dados.

O modo de desempenho é definido por padrão ao criar novos volumes AFF com eficiência de armazenamento.

link:enable-temperature-sensitive-efficiency-concept.html["Saiba mais sobre a eficiência de armazenamento sensível à temperatura e os modos de eficiência de armazenamento"].

.Passos
. Crie um novo volume e defina o modo de eficiência:
+
[source, cli]
----
volume create -vserver <vserver name> -volume <volume name> -aggregate <aggregate name> -size <volume size> -storage-efficiency-mode <efficient|default>
----
+
Definir `-storage-efficiency-mode` para `efficient` para o modo de eficiência ou para `default` para o modo de desempenho.

+
No exemplo a seguir, aff_vol1 é criado com o modo de eficiência.



[listing]
----
volume create -vserver vs1 -volume aff_vol1 -aggregate aff_aggr1 -storage-efficiency-mode efficient -size 10g
----