---
permalink: volumes/snapshot-copies-flexclone-files-luns-concept.html 
sidebar: sidebar 
keywords: how, snapshot copies, work, flexclone files, flexclone luns 
summary: Entender a sinergia entre cópias Snapshot e arquivos FlexClone e LUNs FlexClone, bem como certas restrições. 
---
= Como as cópias Snapshot funcionam com arquivos FlexClone e FlexClone LUNs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Há uma sinergia entre as cópias Snapshot e os arquivos FlexClone e os LUNs FlexClone. Se você trabalha com essas tecnologias, você deve estar ciente do que é possível, bem como das restrições relevantes.

.Criação de arquivos FlexClone e LUNs
Você pode criar um arquivo FlexClone ou FlexClone LUN a partir de uma cópia Snapshot existente. A cópia é baseada nos arquivos pai e LUNs pai contidos em um FlexVol volume.

.Excluindo uma cópia Snapshot
Não é possível excluir manualmente uma cópia Snapshot da qual arquivos FlexClone ou LUNs FlexClone estejam sendo criados no momento. A cópia Snapshot permanece bloqueada até que o processo de compartilhamento de bloco em segundo plano seja concluído. Se você tentar excluir uma cópia Snapshot bloqueada, o sistema exibirá uma mensagem solicitando que você tente novamente a operação após algum tempo. Neste caso, você precisa continuar tentando novamente a operação de exclusão. Você poderá excluir a cópia Snapshot depois que o compartilhamento de bloco for concluído.
