---
permalink: volumes/user-ids-mixed-environment-concept.html 
sidebar: sidebar 
keywords: ontap determines, determine user ids, mixed environment 
summary: Vários fatores determinam se o ONTAP usa um ID UNIX ou Windows ao aplicar cotas de usuário. 
---
= Como o ONTAP determina as IDs de usuário em um ambiente misto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você tiver usuários acessando o armazenamento do ONTAP a partir de clientes Windows e UNIX, a segurança do Windows e UNIX será usada para determinar a propriedade do arquivo. Vários fatores determinam se o ONTAP usa um ID UNIX ou Windows ao aplicar cotas de usuário.

Se o estilo de segurança da qtree ou FlexVol volume que contém o arquivo for apenas NTFS ou apenas UNIX, o estilo de segurança determina o tipo de ID usado ao aplicar cotas de usuário. Para qtrees com o estilo de segurança misto, o tipo de ID usado é determinado se o arquivo tem uma ACL.

A tabela a seguir resume qual tipo de ID é usado.

[cols="3*"]
|===
| Estilo de segurança | ACL | Sem ACL 


 a| 
UNIX
 a| 
ID UNIX
 a| 
ID UNIX



 a| 
Misto
 a| 
ID do Windows
 a| 
ID UNIX



 a| 
NTFS
 a| 
ID do Windows
 a| 
ID do Windows

|===