---
permalink: volumes/view-footprint-savings-task.html 
sidebar: sidebar 
keywords: view, temperature sensitive, storage, efficiency, footprint, savings, volume 
summary: Dependendo da versão do ONTAP, você pode visualizar a economia de espaço físico em cada volume. Você pode fazer isso para avaliar a eficácia de seus processos administrativos ou como parte do Planejamento de capacidade. 
---
= Visualize a economia do espaço físico do volume com ou sem a eficiência de storage sensível à temperatura
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dependendo da versão do ONTAP, você pode visualizar a economia de espaço físico em cada volume. Você pode fazer isso para avaliar a eficácia de seus processos administrativos ou como parte do Planejamento de capacidade.

.Sobre esta tarefa
A partir do ONTAP 9.11,1, você pode usar o comando `volume show-footprint` para visualizar a economia de espaço físico em volumes com a eficiência de storage sensível à temperatura (TSSE) ativada. A partir do ONTAP 9.13,1, você pode usar o mesmo comando para visualizar a economia de espaço físico em volumes não habilitados com TSSE.

.Passos
. Veja a economia de espaço físico do volume:
+
[source, cli]
----
volume show-footprint
----
+
.Exemplo de saída com TSSE ativado
[listing]
----
      Vserver : vs0
      Volume  : vol_tsse_75_per_compress

      Feature                                         Used       Used%
      --------------------------------             ----------    -----
      Volume Data Footprint                           10.15GB      13%
      Volume Guarantee                                     0B       0%
      Flexible Volume Metadata                        64.25MB       0%
      Delayed Frees                                   235.0MB       0%
      File Operation Metadata                             4KB       0%

      Total Footprint                                 10.45GB      13%

      Footprint Data Reduction                         6.85GB       9%
           Auto Adaptive Compression                   6.85GB       9%
      Effective Total Footprint                        3.59GB       5%
----
+
.Exemplo de saída sem TSSE ativado
[listing]
----
      Vserver : vs0
      Volume  : vol_file_cg_75_per_compress

      Feature                                         Used       Used%
      --------------------------------             ----------    -----
      Volume Data Footprint                            5.19GB       7%
      Volume Guarantee                                     0B       0%
      Flexible Volume Metadata                        32.12MB       0%
      Delayed Frees                                   90.17MB       0%
      File Operation Metadata                             4KB       0%

      Total Footprint                                  5.31GB       7%

      Footprint Data Reduction                         1.05GB       1%
           Data Compaction                             1.05GB       1%
      Effective Total Footprint                        4.26GB       5%
----


.Informações relacionadas
* link:set-efficiency-mode-task.html["Definir o modo de eficiência de armazenamento durante a criação de volume"]

