---
permalink: volumes/view-space-savings-flexclone-files-luns-task.html 
sidebar: sidebar 
keywords: view space, view space savings, flexclone files, flexclone luns 
summary: É possível exibir a porcentagem de espaço em disco salvo pelo compartilhamento de blocos em um volume que contém arquivos FlexClone e LUNs FlexClone. Você pode fazer isso como parte do Planejamento de capacidade. 
---
= Visualize economia de espaço com arquivos FlexClone e LUNs FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível exibir a porcentagem de espaço em disco salvo pelo compartilhamento de blocos em um volume que contém arquivos FlexClone e LUNs FlexClone. Você pode fazer isso como parte do Planejamento de capacidade.

.Passos
. Para visualizar a economia de espaço alcançada devido a arquivos FlexClone e LUNs FlexClone, digite o seguinte comando:
+
`df -s volname`

+
`volname` É o nome do FlexVol volume.

+
[NOTE]
====
Se você executar o `df -s` comando em um FlexVol volume habilitado para deduplicação, poderá visualizar o espaço economizado tanto por arquivos de deduplicação quanto por FlexClone e LUNs.

====


.Exemplo
O exemplo a seguir mostra a economia de espaço em um volume FlexClone test1:

[listing]
----
systemA> df -s test1

Filesystem         used   saved   %saved Vserver
/vol/test1/        4828    5744     54%  vs1
----
Saiba mais sobre os comandos descritos neste procedimento no link:https://docs.netapp.com/us-en/ontap-cli/["Referência do comando ONTAP"^].
