---
permalink: volumes/view-status-efficiency-operations-task.html 
sidebar: sidebar 
keywords: efficiency, operation, status, view, sequential packing 
summary: Você pode ver se a deduplicação ou a compactação de dados estão ativadas em um volume. Você também pode exibir o status, o estado, o tipo de compactação e o progresso das operações de eficiência em um volume. 
---
= Visualizar operações e status de eficiência
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode ver se a deduplicação ou a compactação de dados estão ativadas em um volume. Você também pode exibir o status, o estado, o tipo de compactação e o progresso das operações de eficiência em um volume.

Existem duas tarefas disponíveis. Ambos usam o comando `volume efficiency show`.



== Ver o estado de eficiência

.Passos
. Ver o estado de uma operação de eficiência num volume: `volume efficiency show`
+
O comando a seguir exibe o status de uma operação de eficiência no volume VolA que é atribuído ao tipo de compressão adaptável:

+
`volume efficiency show -instance -vserver vs1 -volume VolA`

+
Se a operação de eficiência estiver ativada no volume VolA e a operação estiver inativa, você poderá ver o seguinte na saída do sistema:

+
[listing]
----
cluster1::> volume efficiency show -vserver vs1 -volume VolA

  Vserver Name: vs1
   Volume Name: VolA
   Volume Path: /vol/VolA
         State: Enabled
        Status: Idle
      Progress: Idle for 00:03:20
----




== Determine se os volumes contêm dados embalados sequencialmente

Você pode exibir uma lista de volumes que têm o empacotamento sequencial ativado, por exemplo, quando precisar reverter para uma versão do ONTAP anterior a 9.13.1. Você deve estar no modo de privilégio avançado para usar este comando.

.Passos
. Defina o nível de privilégio: `set -privilege advanced`
. Listar volumes que têm o empacotamento sequencial ativado:
+
`volume efficiency show -extended-auto-adaptive-compression true`


