---
permalink: volumes/view-efficiency-space-savings-task.html 
sidebar: sidebar 
keywords: view space savings deduplication, view space savings data compression, view space savings 
summary: Visualize a economia de espaço obtida por meio da deduplicação e da compactação de dados em um volume como parte do Planejamento de capacidade ou para outros fins. 
---
= Visualize a economia de espaço de eficiência
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode ver a quantidade de economia de espaço obtida por meio da deduplicação e da compactação de dados em um volume. Você pode fazer isso para avaliar a eficácia de seus processos administrativos ou como parte do Planejamento de capacidade.

.Sobre esta tarefa
Você precisa usar o comando `volume show` para exibir a economia de espaço em um volume. Observe que a economia de espaço em snapshots não está incluída ao calcular a economia de espaço obtida em um volume. O uso de deduplicação não afeta as cotas de volume. As cotas são relatadas no nível lógico e permanecem inalteradas.

.Passos
. Use o `volume show` comando para ver a economia de espaço obtida em um volume usando deduplicação e compactação de dados.


.Exemplo
O comando a seguir permite visualizar a economia de espaço obtida usando deduplicação e compactação de dados no volume VolA: `volume show -vserver vs1 -volume VolA`

[listing]
----
cluster1::> volume show -vserver vs1 -volume VolA

                                 Vserver Name: vs1
                                  Volume Name: VolA
																											...
            Space Saved by Storage Efficiency: 115812B
       Percentage Saved by Storage Efficiency: 97%
                 Space Saved by Deduplication: 13728B
            Percentage Saved by Deduplication: 81%
                Space Shared by Deduplication: 1028B
                   Space Saved by Compression: 102084B
        Percentage Space Saved by Compression: 97%
																											...
----