---
permalink: volumes/view-volume-efficiency-policy-task.html 
sidebar: sidebar 
keywords: view, volume, efficiency, policy 
summary: Você pode exibir a política de eficiência de volume, incluindo o nome, a programação, a duração e a descrição. 
---
= Ver uma política de eficiência de volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode exibir a política de eficiência de volume, incluindo o nome, a programação, a duração e a descrição.

.Sobre esta tarefa
O comando `volume efficiency policy show` é usado para exibir uma política de eficiência de volume. Quando você executa o comando no escopo do cluster, as políticas com escopo de cluster não são exibidas. No entanto, você pode exibir as políticas com escopo de cluster no contexto SVM.

.Passos
. Use o `volume efficiency policy show` comando para exibir informações sobre uma política de eficiência de volume.
+
A saída depende dos parâmetros especificados. Para obter mais informações sobre a exibição de exibição detalhada e outros parâmetros, consulte a página de manual para este comando.



.Exemplos
O comando a seguir exibe informações sobre as políticas criadas para o SVM VS1:
`volume efficiency policy show -vserver vs1`

O comando a seguir exibe as políticas para as quais a duração é definida como 10 horas:
`volume efficiency policy show -duration 10`
