---
permalink: volumes/view-capacity-flexclone-files-luns-task.html 
sidebar: sidebar 
keywords: view, node, capacity, creating, deleting, flexclone, files, flexclone luns 
summary: Determine se um nó tem capacidade para receber solicitações para criar e excluir arquivos FlexClone e LUNs FlexClone visualizando a carga dividida do nó. 
---
= Visualize a capacidade do nó antes de criar e excluir arquivos FlexClone e LUNs FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve determinar se um nó tem capacidade para receber solicitações para criar e excluir arquivos FlexClone e LUNs FlexClone. Isso pode ser feito visualizando a carga dividida para o nó. Se a carga máxima de divisão for atingida, não serão aceites novos pedidos até que a carga dividida fique abaixo do máximo.

.Sobre esta tarefa
Quando o nó atinge sua carga máxima de divisão, uma `EBUSY` mensagem de erro é emitida em resposta à criação e exclusão de solicitações. Quando a carga dividida para o nó cai abaixo do máximo, o nó aceita solicitações para criar e excluir arquivos FlexClone e LUNs FlexClone novamente.

Um nó pode aceitar novas solicitações quando o `Allowable Split Load` campo exibe capacidade e a solicitação de criação se encaixa na capacidade disponível.

.Passos
. Veja a quantidade de capacidade que um nó tem para criar e excluir arquivos FlexClone e LUNs FlexClone usando o `volume file clone split load show` comando.
+
No exemplo a seguir, a carga dividida é exibida para todos os nós em cluster1. Todos os nós no cluster têm capacidade para criar e excluir arquivos FlexClone e LUNs FlexClone, conforme indicado pelo campo carga dividida permitida:

+
[listing]
----
cluster1::> volume file clone split load show
Node       Max        Current    Token         Allowable
           Split Load Split Load Reserved Load Split Load
---------- ---------- ---------- ------------- ----------
node1         15.97TB         0B         100MB    15.97TB
node2         15.97TB         0B         100MB    15.97TB
2 entries were displayed.
----

