---
permalink: encryption-at-rest/assign-authentication-keys-seds-external-task.html 
sidebar: sidebar 
keywords: assign, data, authentication, key, fips, drive, sed, external, key, management 
summary: Você pode usar o comando Storage Encryption Disk Modify para atribuir uma chave de autenticação de dados a uma unidade FIPS ou SED. Os nós de cluster usam essa chave para bloquear ou desbloquear dados criptografados na unidade. 
---
= Atribuir uma chave de autenticação de dados a uma unidade FIPS ou SED com gerenciamento de chaves externas ONTAP
:allow-uri-read: 


[role="lead"]
Você pode usar o `storage encryption disk modify` comando para atribuir uma chave de autenticação de dados a uma unidade FIPS ou SED. Os nós de cluster usam essa chave para bloquear ou desbloquear dados criptografados na unidade.

.Sobre esta tarefa
Uma unidade com autocriptografia é protegida contra acesso não autorizado somente se o ID da chave de autenticação estiver definido como um valor não padrão. O ID seguro do fabricante (MSID), que tem ID de chave 0x0, é o valor padrão para unidades SAS. Para unidades NVMe, o valor padrão é uma chave nula, representada como um ID de chave em branco. Quando você atribui o ID da chave a uma unidade de autocriptografia, o sistema altera o ID da chave de autenticação para um valor não padrão.

Este procedimento não causa interrupções.

.Antes de começar
Você deve ser um administrador de cluster para executar esta tarefa.

.Passos
. Atribuir uma chave de autenticação de dados a uma unidade FIPS ou SED:
+
`storage encryption disk modify -disk _disk_ID_ -data-key-id _key_ID_`

+
Saiba mais sobre `storage encryption disk modify` o link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-modify.html["Referência do comando ONTAP"^]na .

+
[NOTE]
====
Você pode usar o `security key-manager query -key-type NSE-AK` comando para exibir IDs de chave.

====
+
[listing]
----
cluster1::> storage encryption disk modify -disk 0.10.* -data-key-id <id_value>

Info: Starting modify on 14 disks.
      View the status of the operation by using the
      storage encryption disk show-status command.
----
. Verifique se as chaves de autenticação foram atribuídas:
+
`storage encryption disk show`

+
Saiba mais sobre `storage encryption disk show` o link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show.html["Referência do comando ONTAP"^]na .

+
[listing]
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data <id_value>
0.0.1   data <id_value>
[...]
----


.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show.html["exibição de disco de criptografia de armazenamento"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show-status.html["disco de criptografia de armazenamento mostrar-status"^]

