---
permalink: encryption-at-rest/before-configuring-concept.html 
sidebar: sidebar 
keywords: collect, network, information, ontap 9.2, earlier 
summary: Se você estiver usando o ONTAP 9.2 ou anterior, você deve preencher a Planilha de configuração de rede antes de ativar o gerenciamento de chaves externas. 
---
= Colete informações de rede no ONTAP 9.2 e anteriores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você estiver usando o ONTAP 9.2 ou anterior, você deve preencher a Planilha de configuração de rede antes de ativar o gerenciamento de chaves externas.

[NOTE]
====
A partir do ONTAP 9.3, o sistema deteta automaticamente todas as informações de rede necessárias.

====
[cols="35,35,30"]
|===


| Item | Notas | Valor 


 a| 
Nome da interface de rede de gerenciamento de chaves
 a| 
 a| 



 a| 
Endereço IP da interface de rede de gerenciamento de chaves
 a| 
Endereço IP do LIF de gerenciamento de nós, no formato IPv4 ou IPv6
 a| 



 a| 
Comprimento do prefixo da rede IPv6 da interface de rede de gerenciamento de chaves
 a| 
Se você estiver usando IPv6, o comprimento do prefixo de rede IPv6
 a| 



 a| 
Máscara de sub-rede da interface de rede de gerenciamento de chaves
 a| 
 a| 



 a| 
Endereço IP do gateway de interface de rede de gerenciamento de chaves
 a| 
 a| 



 a| 
Endereço IPv6 para a interface de rede do cluster
 a| 
Necessário somente se você estiver usando IPv6 para a interface de rede de gerenciamento de chaves
 a| 



 a| 
Número da porta para cada servidor KMIP
 a| 
Opcional. O número da porta deve ser o mesmo para todos os servidores KMIP. Se você não fornecer um número de porta, o padrão será a porta 5696, que é a porta atribuída pela IANA (Internet Assigned Numbers Authority) para KMIP.
 a| 



 a| 
Nome da etiqueta da chave
 a| 
Opcional. O nome da tag chave é usado para identificar todas as chaves pertencentes a um nó. O nome da etiqueta de chave padrão é o nome do nó.
 a| 

|===
.Informações relacionadas
https://www.netapp.com/pdf.html?item=/media/19676-tr-3954.pdf["Relatório técnico da NetApp 3954: Requisitos e procedimentos de pré-instalação de criptografia de armazenamento da NetApp para o Gerenciador de chaves vitalício"^]

https://www.netapp.com/pdf.html?item=/media/19682-tr-4074.pdf["Relatório técnico da NetApp 4074: Requisitos e procedimentos de pré-instalação da criptografia de armazenamento NetApp para o KeySecure"^]
