---
permalink: encryption-at-rest/change-key-management-passphrase-task.html 
sidebar: sidebar 
keywords: changing, onboard, key, management, passphrase 
summary: É uma prática recomendada de segurança alterar periodicamente a senha de gerenciamento de chaves integradas. Copie a nova senha de gerenciamento de chaves integrada para um local seguro fora do sistema de storage para uso futuro. 
---
= Altere a senha de gerenciamento de chaves integradas com o ONTAP
:allow-uri-read: 


[role="lead"]
É uma prática recomendada de segurança alterar periodicamente a senha de gerenciamento de chaves integradas. Copie a nova senha de gerenciamento de chaves integrada para um local seguro fora do sistema de storage para uso futuro.

.Antes de começar
* Você deve ser um administrador de cluster ou SVM para executar essa tarefa.
* São necessários Privileges avançados para esta tarefa.


.Passos
. Alterar para nível de privilégio avançado:
+
`set -privilege advanced`

. Altere a senha de gerenciamento de chaves integradas:
+
[cols="25,75"]
|===


| Para esta versão ONTAP... | Use este comando... 


 a| 
ONTAP 9 F.6 e mais tarde
 a| 
`security key-manager onboard update-passphrase`



 a| 
ONTAP 9 F.5 e anteriores
 a| 
`security key-manager update-passphrase`

|===
+
O seguinte comando ONTAP 9.6 permite alterar a senha de gerenciamento de chaves integradas para `cluster1`:

+
[listing]
----
clusterl::> security key-manager onboard update-passphrase
Warning: This command will reconfigure the cluster passphrase for onboard key management for Vserver "cluster1".
Do you want to continue? {y|n}: y
Enter current passphrase:
Enter new passphrase:
----
. Digite `y` no prompt para alterar a senha de gerenciamento de chave integrada.
. Introduza a frase-passe atual no prompt da frase-passe atual.
. No novo prompt de senha, insira uma senha entre 32 e 256 carateres ou, para "cc-mode", uma senha entre 64 e 256 carateres.
+
Se a senha "'cc-mode'" especificada for inferior a 64 carateres, haverá um atraso de cinco segundos antes que a operação de configuração do gerenciador de chaves exiba o prompt de senha novamente.

. No prompt de confirmação da senha, redigite a senha.


.Depois de terminar
Em um ambiente MetroCluster, você deve atualizar a senha no cluster de parceiros:

* No ONTAP 9.5 e versões anteriores, é necessário executar `security key-manager update-passphrase` com a mesma senha no cluster de parceiros.
* No ONTAP 9.6 e posterior, você será solicitado a executar `security key-manager onboard sync` com a mesma senha no cluster de parceiros.


Copie a senha de gerenciamento de chaves integrada para um local seguro fora do sistema de storage para uso futuro.

Você deve fazer backup manual das informações de gerenciamento de chaves sempre que alterar a senha de gerenciamento de chaves integradas.

.Informações relacionadas
* link:backup-key-management-information-manual-task.html["Fazer backup manual de informações de gerenciamento de chaves integradas"]
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-onboard-update-passphrase.html["gerenciador de chaves de segurança integrado atualização de frase-senha"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-update-passphrase.html["senha de atualização do gerenciador de chaves de segurança"^]

