---
permalink: encryption-at-rest/cluster-version-support-nve-task.html 
sidebar: sidebar 
keywords: determining, whether, cluster, version, supports, nve 
summary: Você deve determinar se a versão do cluster é compatível com NVE antes de instalar a licença. Você pode usar o comando version para determinar a versão do cluster. 
---
= Determine se a versão do cluster é compatível com NVE
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve determinar se a versão do cluster é compatível com NVE antes de instalar a licença. Você pode usar o `version` comando para determinar a versão do cluster.

.Sobre esta tarefa
A versão do cluster é a versão mais baixa do ONTAP em execução em qualquer nó no cluster.

.Passo
. Determine se a versão do cluster é compatível com NVE:
+
`version -v`

+
NVE não é suportado se o comando output exibir o texto "'1Ono-DARE" (para "'criptografia sem dados em repouso'") ou se você estiver usando uma plataforma que não está listada no link:configure-netapp-volume-encryption-concept.html#support-details["Detalhes do suporte"].

+
O comando a seguir determina se o NVE é suportado `cluster1` no .

+
[listing]
----
cluster1::> version -v
NetApp Release 9.1.0: Tue May 10 19:30:23 UTC 2016 <1Ono-DARE>
----
+
A saída de `1Ono-DARE` indica que o NVE não é suportado na versão do cluster.


