---
permalink: encryption-at-rest/configure-external-key-management-overview-concept.html 
sidebar: sidebar 
keywords: external key management, kmip, configure 
summary: 'Você pode usar um ou mais servidores de gerenciamento de chaves externos para proteger as chaves que o cluster usa para acessar dados criptografados. Um servidor de gerenciamento de chaves externo é um sistema de terceiros em seu ambiente de storage que serve chaves para nós que usam o Key Management Interoperability Protocol (KMIP).' 
---
= Saiba mais sobre como configurar o gerenciamento de chaves externas com o ONTAP NetApp Volume Encryption
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar um ou mais servidores externos de gerenciamento de chaves para proteger as chaves que o cluster usa para acessar dados criptografados. Um servidor externo de gerenciamento de chaves é um sistema de terceiros em seu ambiente de armazenamento que fornece chaves para nós usando o Protocolo de Interoperabilidade de Gerenciamento de Chaves (KMIP). Além do Gerenciador de Chaves Onboard, o ONTAP oferece suporte a vários servidores externos de gerenciamento de chaves.

 Beginning with ONTAP 9.10.1, you can use xref:manage-keys-azure-google-task.html[Azure Key Vault or Google Cloud Key Manager Service] to protect your NVE keys for data SVMs. Beginning with ONTAP 9.11.1, you can configure multiple external key managers in a cluster. See xref:configure-cluster-key-server-task.html[Configure clustered key servers]. Beginning with ONTAP 9.12.0, you can use link:https://docs.aws.amazon.com/kms/latest/developerguide/overview.html[AWS' KMS^] to protect your NVE keys for data SVMs. Beginning with ONTAP 9.17.1, you can use OpenStack's xref:manage-keys-barbican-task.html[Barbican KMS] to protect your NVE keys for data SVMs.