---
permalink: encryption-at-rest/delete-key-management-database-task.html 
sidebar: sidebar 
keywords: transitioning, onboard key management, external key management 
summary: Se você quiser alternar para o gerenciamento de chaves integradas do gerenciamento de chaves externas, exclua a configuração de gerenciamento de chaves externas para ativar o gerenciamento de chaves integradas. 
---
= Mude do gerenciamento de chaves externas para o gerenciamento de chaves integrado ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para alternar para o gerenciamento de chaves integrado, exclua a configuração de gerenciamento de chaves externas antes de habilitar o gerenciamento de chaves integrado.

.Antes de começar
* Para criptografia baseada em hardware, é necessário redefinir as chaves de dados de todas as unidades FIPS ou SEDs para o valor padrão.
+
link:return-seds-unprotected-mode-task.html["Retornar uma unidade FIPS ou SED para o modo desprotegido"]

* Você deve ter excluído todas as conexões externas do gerenciador de chaves.
+
link:remove-external-key-server-93-later-task.html["Excluindo uma conexão externa do gerenciador de chaves"]

* Você deve ser um administrador de cluster para executar esta tarefa.


.Passos
As etapas para fazer a transição do gerenciamento de chaves dependem da versão do ONTAP que você está usando.

[role="tabbed-block"]
====
.ONTAP 9 F.6 e mais tarde
--
. Mude para o nível de privilégio avançado:
+
`set -privilege advanced`

. Use o comando:
+
`security key-manager external disable -vserver _admin_SVM_`

+

NOTE: Em um ambiente MetroCluster, você deve repetir o comando nos dois clusters para o SVM de administrador.



Saiba mais sobre `security key-manager external disable` nolink:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-external-disable.html["Referência do comando ONTAP"^] .

--
.ONTAP 9 F.5 e anteriores
--
Use o comando:
`security key-manager delete-kmip-config`

Saiba mais sobre `security key-manager delete-kmip-config` nolink:https://docs.netapp.com/us-en/ontap-cli-9161/security-key-manager-delete-kmip-config.html["Referência do comando ONTAP"^] .

--
====
.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-external-disable.html["desabilitação externa do gerenciador de chaves de segurança"^]

