---
permalink: encryption-at-rest/delete-encrypted-volume-task.html 
sidebar: sidebar 
keywords: deleting, encrypted, volume 
summary: Você pode usar o comando de exclusão de volume para excluir um volume criptografado. 
---
= Excluir um volume criptografado no ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `volume delete` comando para excluir um volume criptografado.

.Antes de começar
* Você deve ser um administrador de cluster para executar esta tarefa. Como alternativa, você pode ser um administrador SVM a quem o administrador do cluster delegou autoridade. Para obter mais informações, link:delegate-volume-encryption-svm-administrator-task.html["delegar autoridade para executar o comando de movimentação de volume"]consulte .
* O volume deve estar offline.


.Passo
. Eliminar um volume encriptado:
+
`volume delete -vserver _SVM_name_ -volume _volume_name_`

+
Saiba mais sobre `volume delete` o link:https://docs.netapp.com/us-en/ontap-cli/volume-delete.html["Referência do comando ONTAP"^]na .

+
O comando a seguir exclui um volume criptografado chamado `vol1`:

+
[listing]
----
cluster1::> volume delete -vserver vs1 -volume vol1
----
+
Digite `yes` quando for solicitado que você confirme a exclusão.

+
O sistema exclui a chave de criptografia do volume após 24 horas.

+
Use `volume delete` com a `-force true` opção para excluir um volume e destruir a chave de criptografia correspondente imediatamente. Este comando requer Privileges avançado. Saiba mais sobre `volume delete` o link:https://docs.netapp.com/us-en/ontap-cli/volume-delete.html["Referência do comando ONTAP"^]na .



.Depois de terminar
Você pode usar o `volume recovery-queue` comando para recuperar um volume excluído durante o período de retenção após a emissão do `volume delete` comando:

`volume recovery-queue _SVM_name_ -volume _volume_name_`

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_use_the_Volume_Recovery_Queue["Como usar o recurso recuperação de volume"]
