---
permalink: encryption-at-rest/enable-onboard-key-management-new-nodes-concept.html 
sidebar: sidebar 
keywords: onboard key management, onboard new nodes, okm, encrypt 
summary: Você pode usar o Gerenciador de chaves integrado para proteger as chaves que o cluster usa para acessar dados criptografados. É necessário habilitar o Gerenciador de chaves integrado em cada cluster que acessa um volume criptografado ou um disco com autocriptografia. 
---
= Habilitar o gerenciamento de chaves integrado em nós ONTAP recém-adicionados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o Gerenciador de chaves integrado para proteger as chaves que o cluster usa para acessar dados criptografados. É necessário habilitar o Gerenciador de chaves integrado em cada cluster que acessa um volume criptografado ou um disco com autocriptografia.

[NOTE]
====
Para o ONTAP 9.6 e versões posteriores, você deve executar o `security key-manager onboard sync` comando a cada vez que você adiciona um nó ao cluster.

Para o ONTAP 9.5 e versões anteriores, você deve executar o `security key-manager setup` comando sempre que adicionar um nó ao cluster.

Se você adicionar um nó a um cluster com gerenciamento de chaves integrado, execute este comando para atualizar as chaves ausentes.

====
Se você tiver uma configuração do MetroCluster, revise estas diretrizes:

* A partir do ONTAP 9.6, é necessário executar `security key-manager onboard enable` primeiro no cluster local e, em seguida, executar `security key-manager onboard sync` no cluster remoto, usando a mesma frase-passe em cada um.
+
Saiba mais sobre `security key-manager onboard enable` e `security key-manager onboard sync` no link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+key-manager+onboard["Referência do comando ONTAP"^].

* No ONTAP 9.5, você deve executar `security key-manager setup` no cluster local e `security key-manager setup -sync-metrocluster-config yes` no cluster remoto, usando a mesma senha em cada um.
* Antes do ONTAP 9.5, você deve executar `security key-manager setup` no cluster local, esperar aproximadamente 20 segundos e, em seguida, executar `security key-manager setup` no cluster remoto, usando a mesma senha em cada um.


Por padrão, você não é obrigado a inserir a senha do gerenciador de chaves quando um nó é reinicializado. A partir do ONTAP 9.4, pode utilizar a `-enable-cc-mode yes` opção para exigir que os utilizadores introduzam a frase-passe após uma reinicialização.

Para NVE, se você definir `-enable-cc-mode yes`o , os volumes criados com os `volume create` comandos e `volume move start` serão criptografados automaticamente. Para `volume create`, não é necessário especificar `-encrypt true`. Para `volume move start`, não é necessário especificar `-encrypt-destination true`.

[NOTE]
====
Se a tentativa de senha falhar, reinicie o nó. Após a reinicialização, você pode tentar inserir a senha novamente.

====
.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=cluster+image["comandos de imagem de cluster"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-external-enable.html["gerenciador de chaves de segurança externo habilitado"^]
* link:https://docs.netapp.com/us-en/ontap-cli//security-key-manager-onboard-enable.html["habilitar gerenciador de chaves de segurança integrado"^]

