---
permalink: encryption-at-rest/install-license-task.html 
sidebar: sidebar 
keywords: install, license, VE license, NVE, encryption, encrypt data 
summary: Uma licença VE permite que você use o recurso em todos os nós do cluster. Você deve verificar se a licença está instalada antes de poder criptografar dados com NVE. 
---
= Instale a licença
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Uma licença VE permite que você use o recurso em todos os nós do cluster. Essa licença é necessária para que você possa criptografar dados com NVE. Está incluído com link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"].

Antes do ONTAP One, a licença VE foi incluída com o pacote de encriptação. O pacote de criptografia não é mais oferecido, mas ainda é válido. Embora não seja necessário atualmente, os clientes existentes podem optar por link:../system-admin/download-nlf-task.html["Atualize para o ONTAP One"].

.Antes de começar
* Você deve ser um administrador de cluster para executar esta tarefa.
* Tem de ter recebido a chave de licença VE do seu representante de vendas ou ter o ONTAP One instalado.


.Passos
. link:../system-admin/manage-license-task.html["Verifique se a licença VE está instalada"].
+
O nome do pacote de licença VE é `VE`.

. Se a licença não estiver instalada, link:../system-admin/install-license-task.html["Use o Gerenciador do sistema ou a CLI do ONTAP para instalá-lo"].

