---
permalink: encryption-at-rest/purge-data-encrypted-asynchronous-snapmirror-task.html 
sidebar: sidebar 
keywords: securely, purging, scrub, data, encrypted, volume, nve, netapp, volume encryption, snapmirror, asynchronous 
summary: 'A partir do ONTAP 9.8, você pode usar a limpeza segura para "esfregar" dados em volumes habilitados para NVE com uma relação assíncrona do SnapMirror, sem interrupções.' 
---
= Limpe com segurança os dados em um volume criptografado com uma relação assíncrona do SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.8, você pode usar uma limpeza segura para dados "cruzadores" sem interrupções em volumes habilitados para NVE com uma relação assíncrona do SnapMirror.

.Antes de começar
* Você deve ser um administrador de cluster para executar esta tarefa.
* São necessários Privileges avançados para esta tarefa.


.Sobre esta tarefa
A limpeza segura pode levar de vários minutos a muitas horas para ser concluída, dependendo da quantidade de dados nos arquivos excluídos. Pode utilizar o `volume encryption secure-purge show` comando para visualizar o estado da operação. Você pode usar o `volume encryption secure-purge abort` comando para encerrar a operação.


NOTE: Para fazer uma limpeza segura em um host SAN, você deve excluir todo o LUN que contém os arquivos que deseja limpar, ou você deve ser capaz de perfurar buracos no LUN para os blocos que pertencem aos arquivos que deseja limpar. Se você não puder excluir o LUN ou o sistema operacional do host não suportar furos no LUN, não será possível executar uma limpeza segura.

.Passos
. No sistema de armazenamento, mude para o nível de privilégio avançado:
+
`set -privilege advanced`

. Exclua os arquivos ou o LUN que você deseja limpar com segurança.
+
** Em um cliente nas, exclua os arquivos que você deseja limpar com segurança.
** Em um host SAN, exclua o LUN que você deseja limpar com segurança ou perfurar buracos no LUN para os blocos que pertencem aos arquivos que deseja limpar.


. Prepare o volume de destino na relação assíncrona para ser purgado com segurança:
+
`volume encryption secure-purge start -vserver _SVM_name_ -volume _volume_name_ -prepare true`

+
Repita esta etapa em cada volume em sua relação assíncrona do SnapMirror.

. Se os arquivos que você deseja limpar com segurança estiverem em snapshots, exclua os snapshots:
+
`snapshot delete -vserver _SVM_name_ -volume _volume_name_ -snapshot`

. Se os arquivos que você deseja limpar com segurança estiverem nos snapshots base, faça o seguinte:
+
.. Crie um instantâneo no volume de destino na relação assíncrona do SnapMirror:
+
`volume snapshot create -snapshot snapshot_name -vserver _SVM_name_ -volume _volume_name_`

.. Atualize o SnapMirror para mover o instantâneo base para a frente:
+
`snapmirror update -source-snapshot _snapshot_name_ -destination-path _destination_path_`

+
Repita esta etapa para cada volume na relação assíncrona do SnapMirror.

.. Repita as etapas (a) e (b) iguais ao número de instantâneos base mais um.
+
Por exemplo, se você tiver dois snapshots base, repita as etapas (a) e (b) três vezes.

.. Verifique se o instantâneo base está presente
`snapshot show -vserver _SVM_name_ -volume _volume_name_`
.. Eliminar o instantâneo base
`snapshot delete -vserver _svm_name_ -volume _volume_name_ -snapshot snapshot`


. Limpe com segurança os arquivos excluídos:
+
`volume encryption secure-purge start -vserver _svm_name_ -volume _volume_name_`

+
Repita esta etapa em cada volume na relação assíncrona do SnapMirror.

+
O seguinte comando limpa com segurança os arquivos excluídos no "'vol1" na SVM "'VS1":

+
[listing]
----
cluster1::> volume encryption secure-purge start -vserver vs1 -volume vol1
----
. Verifique o estado da operação de purga segura:
+
`volume encryption secure-purge show`


