---
permalink: encryption-at-rest/replace-self-encrypting-disk-task.html 
sidebar: sidebar 
keywords: replacing, fips drive, sed 
summary: Você pode substituir uma unidade FIPS ou SED da mesma forma que substitui um disco comum. Certifique-se de atribuir novas chaves de autenticação de dados à unidade de substituição. Para uma unidade FIPS, você também pode querer atribuir uma nova chave de autenticação FIPS 140-2-2. 
---
= Substitua uma unidade FIPS ou SED no ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode substituir uma unidade FIPS ou SED da mesma forma que substitui um disco comum. Certifique-se de atribuir novas chaves de autenticação de dados à unidade de substituição. Para uma unidade FIPS, você também pode querer atribuir uma nova chave de autenticação FIPS 140-2-2.


NOTE: Se um par de HA estiver usando link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/support-storage-encryption-concept.html["Criptografia de unidades SAS ou NVMe (SED, NSE, FIPS)"], siga as instruções no link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/return-seds-unprotected-mode-task.html["Retornar uma unidade FIPS ou SED para o modo desprotegido"]tópico para todas as unidades do par de HA antes de inicializar o sistema (opções de inicialização 4 ou 9). Se não fizer isso, poderá resultar em perda de dados futura se as unidades forem reaproveitadas.

.Antes de começar
* Você deve saber o ID da chave para a chave de autenticação usada pela unidade.
* Você deve ser um administrador de cluster para executar esta tarefa.


.Passos
. Certifique-se de que o disco foi marcado como com falha:
+
`storage disk show -broken`

+
Saiba mais sobre `storage disk show` o link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-show.html["Referência do comando ONTAP"^]na .

+
[listing]
----
cluster1::> storage disk show -broken
Original Owner: node1
  Checksum Compatibility: block
                                                Drawer                              Usable Physical
    Disk            Outage Reason  HA Shelf Bay  /Slot Chan   Pool    Type    RPM     Size     Size Model
    --------------- ------------- --- ----- --- ------ ---- ------ ------- ------ -------- -------- ----------------
    1.0.12          admin failed   0a     0  12   -/-     A FAILED SSD-NVM      -   1.75TB   1.75TB X4024S173A1T9NTE

Original Owner: node2
  Checksum Compatibility: block
                                                Drawer                              Usable Physical
    Disk            Outage Reason  HA Shelf Bay  /Slot Chan   Pool    Type    RPM     Size     Size Model
    --------------- ------------- --- ----- --- ------ ---- ------ ------- ------ -------- -------- ----------------
    1.0.13          admin failed   0b     0  13   -/-     B FAILED SSD-NVM      -   1.75TB   1.75TB X4024S173A1T9NTF

2 entries were displayed.
[...]
----
. Remova o disco com falha e substitua-o por uma nova unidade FIPS ou SED, seguindo as instruções no guia de hardware do modelo de compartimento de disco.
. Atribua a propriedade do disco recém-substituído:
+
`storage disk assign -disk disk_name -owner node`

+
Saiba mais sobre `storage disk assign` o link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-assign.html["Referência do comando ONTAP"^]na .

+
[listing]
----
cluster1::> storage disk assign -disk 2.1.1 -owner cluster1-01
----
. Confirme se o novo disco foi atribuído:
+
`storage encryption disk show`

+
Saiba mais sobre `storage encryption disk show` o link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show.html["Referência do comando ONTAP"^]na .

+
[listing]
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data <id_value>
0.0.1   data <id_value>
1.10.0  data <id_value>
1.10.1  data <id_value>
2.1.1   open 0x0
[...]
----
. Atribua as chaves de autenticação de dados à unidade FIPS ou SED.
+
link:assign-authentication-keys-seds-external-task.html["Atribuição de uma chave de autenticação de dados a uma unidade FIPS ou SED (gerenciamento de chaves externas)"]

. Se necessário, atribua uma chave de autenticação FIPS 140-2-2 à unidade FIPS.
+
link:assign-fips-140-2-authentication-key-task.html["Atribuição de uma chave de autenticação FIPS 140-2-2 a uma unidade FIPS"]



.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-assign.html["atribuição de disco de armazenamento"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-show.html["exibição do disco de armazenamento"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show.html["exibição de disco de criptografia de armazenamento"^]

