---
permalink: encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html 
sidebar: sidebar 
keywords: restoring, onboard, key management encryption 
summary: Ocasionalmente, você pode precisar restaurar uma chave de criptografia integrada de gerenciamento de chaves. Depois de verificar que uma chave precisa ser restaurada, você pode configurar o Gerenciador de chaves integrado para restaurar a chave. 
---
= Restaurar chaves de criptografia integradas de gerenciamento de chaves no ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ocasionalmente, pode ser necessário restaurar uma chave de criptografia de gerenciamento de chaves integrada.  Depois de verificar se uma chave precisa ser restaurada, você pode configurar o Onboard Key Manager para restaurá-la. O procedimento a ser seguido para restaurar suas chaves de criptografia de gerenciamento de chaves onboard varia de acordo com sua versão do ONTAP.

.Antes de começar
* Exclua o banco de dados do gerenciador de chaves externo se você usar o NSE com um servidor KMIP externo. Para mais detalhes, vejalink:delete-key-management-database-task.html["Transição do gerenciamento de chaves externas para o gerenciamento de chaves onboard do ONTAP"] .
* Você deve ser um administrador de cluster para executar esta tarefa.



NOTE: Se você estiver usando o NSE em um sistema com um módulo Flash Cache, também deverá ativar o NVE ou NAE. O NSE não criptografa dados que residem no módulo Flash Cache.



== ONTAP 9 F.6 e mais tarde


IMPORTANT: Se você estiver executando o ONTAP 9.8 ou posterior e o volume raiz estiver criptografado, siga o procedimento para <<ontap-9-8>>.

. Verifique se a chave precisa ser restaurada
`security key-manager key query -node _node_`
+
Saiba mais sobre `security key-manager key query` o link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-key-query.html["Referência do comando ONTAP"^]na .

. Restaurar a chave
`security key-manager onboard sync`
+
Saiba mais sobre `security key-manager onboard sync` o link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-onboard-sync.html["Referência do comando ONTAP"^]na .

. No prompt de frase-passe, insira a senha de gerenciamento de chave integrada para o cluster.




== ONTAP 9.8 ou posterior com volume de raiz criptografado

Se você estiver executando o ONTAP 9.8 e posterior e seu volume raiz estiver criptografado, defina uma senha de recuperação de gerenciamento de chaves integrado com o menu de inicialização. Este processo também é necessário se você fizer uma substituição de Mídia de inicialização.

. Inicialize o nó no menu de inicialização e selecione a opção `(10) Set onboard key management recovery secrets`.
. Enter `y` para utilizar esta opção.
. No prompt, insira a senha de gerenciamento de chaves integradas para o cluster.
. No prompt, insira os dados da chave de backup.
+
Após inserir os dados da chave de backup, o nó retorna ao menu de inicialização.

. No menu de inicialização, selecione a opção `(1) Normal Boot`.




== ONTAP 9 F.5 e anteriores

. Verifique se a chave precisa ser restaurada
`security key-manager key show`
. Restaurar a chave
`security key-manager setup -node _node_`
+
Saiba mais sobre `security key-manager setup` nolink:https://docs.netapp.com/us-en/ontap-cli-9161/security-key-manager-setup.html["Referência do comando ONTAP"^] .

. No prompt de frase-passe, insira a senha de gerenciamento de chave integrada para o cluster.

