---
permalink: encryption-at-rest/transition-external-key-from-onboard-key-task.html 
sidebar: sidebar 
keywords: transitioning, external key management, onboard key management 
summary: Se você quiser alternar para o gerenciamento de chaves externas do gerenciamento de chaves integradas, exclua a configuração de gerenciamento de chaves integradas antes de habilitar o gerenciamento de chaves externas. 
---
= Transição para o gerenciamento de chaves externas do gerenciamento de chaves integrado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você quiser alternar para o gerenciamento de chaves externas do gerenciamento de chaves integradas, exclua a configuração de gerenciamento de chaves integradas antes de habilitar o gerenciamento de chaves externas.

.Antes de começar
* Para criptografia baseada em hardware, é necessário redefinir as chaves de dados de todas as unidades FIPS ou SEDs para o valor padrão.
+
link:return-seds-unprotected-mode-task.html["Retornar uma unidade FIPS ou SED para o modo desprotegido"]

* Para criptografia baseada em software, você deve descriptografar todos os volumes.
+
link:unencrypt-volume-data-task.html["Uncriptografando dados de volume"]

* Você deve ser um administrador de cluster para executar esta tarefa.


.Passo
. Exclua a configuração de gerenciamento de chaves integradas para um cluster:
+
[cols="35,65"]
|===


| Para esta versão ONTAP... | Use este comando... 


 a| 
ONTAP 9 F.6 e mais tarde
 a| 
`security key-manager onboard disable -vserver SVM`



 a| 
ONTAP 9 F.5 e anteriores
 a| 
`security key-manager delete-key-database`

|===


Para obter a sintaxe de comando completa, consulte https://docs.netapp.com/us-en/ontap-cli["Referência do comando ONTAP"^] .
