---
permalink: encryption-at-rest/unencrypt-volume-data-task.html 
sidebar: sidebar 
keywords: unencrypting, volume, data 
summary: Você pode usar o comando de início de movimentação de volume para mover e descriptografar dados de volume. 
---
= Descriptografe dados de volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `volume move start` comando para mover e descriptografar dados de volume.

.Antes de começar
Você deve ser um administrador de cluster para executar esta tarefa. Como alternativa, você pode ser um administrador SVM a quem o administrador do cluster delegou autoridade. Para obter mais informações, link:delegate-volume-encryption-svm-administrator-task.html["Delegar autoridade para executar o comando de movimentação de volume"]consulte .

.Passos
. Mova um volume criptografado existente e descriptografe os dados no volume:
+
`volume move start -vserver _SVM_name_ -volume volume_name -destination-aggregate _aggregate_name_ -encrypt-destination false`

+
Para obter a sintaxe de comando completa, consulte a página man para o comando.

+
O comando a seguir move um volume existente nomeado `vol1` para o agregado de destino `aggr3` e descriptografa os dados no volume:

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol1 -destination-aggregate aggr3 -encrypt-destination false
----
+
O sistema exclui a chave de criptografia do volume. Os dados no volume não são criptografados.

. Verifique se o volume está desativado para criptografia:
+
`volume show -encryption`

+
Para obter a sintaxe de comando completa, consulte a página man para o comando.

+
O comando a seguir exibe se os volumes em `cluster1` são criptografados:

+
[listing]
----
cluster1::> volume show -encryption

Vserver  Volume   Aggregate   State    Encryption State
-------  ------   ---------   -----    ----------------
vs1      vol1     aggr1       online   none
----

