---
permalink: ndmp/configure-backup-application-task.html 
sidebar: sidebar 
keywords: configure, backup, application 
summary: Depois que o cluster é configurado para o acesso NDMP, você deve coletar informações da configuração do cluster e, em seguida, configurar o resto do processo de backup no aplicativo de backup. 
---
= Configure a aplicação de cópia de segurança
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois que o cluster é configurado para o acesso NDMP, você deve coletar informações da configuração do cluster e, em seguida, configurar o resto do processo de backup no aplicativo de backup.

.Passos
. Reúna as seguintes informações que você configurou anteriormente no ONTAP:
+
** O nome de usuário e a senha que o aplicativo de backup requer para criar a conexão NDMP
** Os endereços IP das LIFs entre clusters que o aplicativo de backup requer para se conetar ao cluster


. No ONTAP, exiba os aliases atribuídos pelo ONTAP a cada dispositivo usando o `storage tape alias show` comando.
+
Os aliases são muitas vezes úteis na configuração do aplicativo de backup.

+
[listing]
----
cluster1::> storage tape show -alias

  Device ID: 2a.0
Device Type: tape drive
Description: Hewlett-Packard LTO-5

Node                        Alias     Mapping
--------------------------- --------- ------------------------------
stsw-3220-4a-4b-02          st2       SN[HU19497WVR]
...
----
. No aplicativo de backup, configure o restante do processo de backup usando a documentação do aplicativo de backup.


.Depois de terminar
Se ocorrer um evento de mobilidade de dados, como uma movimentação de volume ou migração de LIF, você deve estar preparado para reinicializar quaisquer operações de backup interrompidas.
