---
permalink: ndmp/index.html 
sidebar: sidebar 
keywords: decide, ndmp, configuration, network, data, management, protocol, backup, back up 
summary: 'Você pode configurar rapidamente um cluster ONTAP 9 para usar o Protocolo de gerenciamento de dados de rede (NDMP) para fazer backup de dados diretamente em fita usando um aplicativo de backup de terceiros.' 
---
= Saiba mais sobre a configuração da NDMP ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar rapidamente um cluster ONTAP 9 para usar o Protocolo de gerenciamento de dados de rede (NDMP) para fazer backup de dados diretamente em fita usando um aplicativo de backup de terceiros.

Se o aplicativo de backup oferecer suporte ao Cluster Aware Backup (CAB), você poderá configurar o NDMP como _SVM-scoped_ ou _node-scoped_:

* O escopo do SVM no nível do cluster (admin SVM) permite fazer backup de todos os volumes hospedados em diferentes nós do cluster. NDMP com escopo SVM é recomendado, sempre que possível.
* O NDMP com escopo de nó permite fazer backup de todos os volumes hospedados nesse nó.


Se o aplicativo de backup não suportar CAB, você deve usar NDMP com escopo de nó.

NDMP com escopo SVM e escopo de nó são mutuamente exclusivos; eles não podem ser configurados no mesmo cluster.


NOTE: O NDMP com escopo de nó está obsoleto no ONTAP 9.

Saiba mais link:../tape-backup/cluster-aware-backup-extension-concept.html["Backup ciente de cluster (CAB)"]sobre o .

Antes de configurar o NDMP, verifique o seguinte:

* Você tem um aplicativo de backup de terceiros (também chamado de aplicativo de gerenciamento de dados ou DMA).
* Você é um administrador de cluster.
* Dispositivos de fita e um servidor de Mídia opcional estão instalados.
* Os dispositivos de fita são conetados ao cluster por meio de um switch Fibre Channel (FC) ou conetados localmente.
* Pelo menos um dispositivo de fita tem um número de unidade lógica (LUN) de 0.

