---
permalink: consistency-groups/limits.html 
sidebar: sidebar 
keywords: consistency groups, object limits 
summary: Ao Planejar seus grupos de consistência, há limites de objetos que você deve estar ciente. 
---
= Limites do grupo de consistência
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao Planejar e gerenciar seus grupos de consistência, considere os limites de objetos no escopo do cluster e do grupo de consistência pai ou filho.



== Limites impostos

A tabela a seguir captura limites para grupos de consistência. Limites separados se aplicam a grupos de consistência usando a sincronização ativa do SnapMirror. Para obter mais informações, link:../snapmirror-active-sync/limits-reference.html["Limites de sincronização ativa do SnapMirror"]consulte .

|===


| Limite | Âmbito de aplicação | Mínimo | Máximo 


| Número de grupos de consistência | Cluster | 0 | Igual à contagem máxima de volume no cluster* 


| Número de grupos de consistência pai | Cluster | 0 | Igual à contagem máxima de volume no cluster 


| Número de grupos de consistência individual e pai | Cluster | 0 | Igual à contagem máxima de volume no cluster 


| Número de volumes em um grupo de consistência | Grupo de consistência único | volume 1 | 80 volumes 


| Número de volumes em um grupo de consistência com o SnapMirror assíncrono | Grupo de consistência único | volume 1  a| 
* Em ONTAP 9.15,1 e posterior: 80 volumes
* Em ONTAP 9.13,1 e 9.14.1: 16 volumes




| Número de volumes no filho de um grupo de consistência pai | Grupo de consistência pai | volume 1 | 80 volumes 


| Número de volumes em um grupo de consistência filho | Grupo de consistência infantil | volume 1 | 80 volumes 


| Número de grupos filhos de consistência em um grupo pai de consistência | Grupo de consistência pai | 1 grupo de consistência | 5 grupos de consistência 


| Número de relacionamentos de recuperação de desastres do SVM em que existe um grupo de consistência (disponível a partir do ONTAP 9.14,1) | Cluster | 0 | 32 
|===
Um máximo de 50 grupos de consistência habilitados com o SnapMirror assíncrono podem ser hospedados em um cluster.



== Limites não aplicados

A programação mínima de instantâneos suportados para grupos de consistência é de 30 minutos. Isso é baseado link:https://www.netapp.com/media/12385-tr4571.pdf["Testes para FlexGroup volumes"^]no , que compartilha a mesma infraestrutura Snapshot que os grupos de consistência.
