---
sidebar: sidebar 
permalink: concept-svm-admin-dashboard-sm.html 
keywords: netapp, system manager, ontap, administration, overview, svm, storage vm, volume, vserver, dashboard, administrator, tenant, multi-tenancy, protocol, network interface, performance, learn 
summary: Os administradores de SVM podem monitorar e gerenciar suas próprias SVMs usando um painel de controle dedicado do System Manager. Isso é particularmente útil em um ambiente ONTAP com locatários, onde o administrador do cluster pode fornecer um painel de SVM para cada locatário. 
---
= Saiba mais sobre o painel de administração do SVM do ONTAP System Manager
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A partir do ONTAP 9.19.1, os administradores de SVM podem monitorar e gerenciar suas SVMs usando um painel dedicado do System Manager e a página Storage > Volumes. Isso é particularmente útil em um ambiente ONTAP com locatários, onde o administrador do cluster pode fornecer um painel de SVM para cada locatário.

O administrador do cluster fornece as credenciais de login aos administradores do SVM. Os administradores do SVM podem visualizar detalhes e desempenho no painel do SVM e na página *Armazenamento > Volumes*. O painel exibe os protocolos do SVM, as interfaces de rede, detalhes e métricas de desempenho. A página Volumes fornece informações sobre os volumes do SVM e, se permitido pelo administrador do cluster, a capacidade de o administrador do SVM adicionar novos volumes.

.O que vem a seguir
link:task-assign-svm-admin-access-sm.html["Atribua acesso de administrador SVM com ONTAP System Manager"]
