---
sidebar: sidebar 
permalink: concept_administration_overview.html 
keywords: netapp, system manager, ontap, administration, overview, cluster, node, local tier, aggregate, svm, storage vm, service level, volume, qtree, LUN, automatic aggregate selection, vserver, protocol, quota, disk, HA pair, dashboard, subnet, domain, interface, mirroring, vaulting, storage, html5 
summary: O System Manager permite gerenciar sistemas de storage e objetos de storage e executar tarefas comuns de gerenciamento relacionadas a sistemas de storage a partir de um navegador da Web. 
---
= Visão geral da administração com o System Manager
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O System Manager é uma interface gráfica de gerenciamento baseada em HTML5 que permite usar um navegador da Web para gerenciar sistemas de storage e objetos de storage (como discos, volumes e camadas de storage) e executar tarefas comuns de gerenciamento relacionadas a sistemas de storage.

Os procedimentos nesta seção ajudam a gerenciar seu cluster com o System Manager no ONTAP 9.7 e versões posteriores.

[NOTE]
====
* O Gerenciador do sistema está incluído no software ONTAP como um serviço da Web, habilitado por padrão e acessível por meio de um navegador.
* O nome do Gestor de sistema mudou a partir de ONTAP 9.6. Em ONTAP 9.5 e mais cedo foi chamado de OnCommand System Manager. Começando com o ONTAP 9.6 e posterior, ele é chamado de Gerenciador de sistema.
* Se você estiver usando o Gerenciador de sistema clássico (disponível somente no ONTAP 9.7 e anterior), consulte  https://docs.netapp.com/us-en/ontap-system-manager-classic/index.html["System Manager Classic (ONTAP 9 9,7.0 a 0)"^]


====
Com o System Manager Dashboard, é possível visualizar informações gerais sobre alertas e notificações importantes, a eficiência e a capacidade das camadas e volumes de storage, os nós disponíveis em um cluster, o status dos nós em um par de HA, as aplicações e objetos mais ativos e as métricas de performance de um cluster ou nó.

Com o System Manager, você pode executar muitas tarefas comuns, como as seguintes:

* Crie um cluster, configure uma rede e configure os detalhes de suporte para o cluster.
* Configure e gerencie objetos de storage, como discos, camadas locais, volumes, qtrees e cotas.
* Configurar protocolos, como SMB e NFS, e provisionar o compartilhamento de arquivos.
* Configurar protocolos como FC, FCoE, NVMe e iSCSI para acesso a bloco.
* Crie e configure componentes de rede, como sub-redes, domínios de broadcast, interfaces de dados e gerenciamento e grupos de interfaces.
* Configure e gerencie relacionamentos de espelhamento e cofre.
* Execute operações de gerenciamento de clusters, de nós de storage e de máquina virtual de armazenamento (VM de armazenamento).
* Crie e configure VMs de storage, gerencie objetos de storage associados a VMs de storage e gerencie serviços de VM de storage.
* Monitore e gerencie configurações de alta disponibilidade (HA) em um cluster.
* Configure os processadores de serviço para fazer login, gerenciar, monitorar e administrar remotamente o nó, independentemente do estado do nó.




== Terminologia do System Manager

O Gerenciador do sistema usa terminologia diferente da CLI para algumas funcionalidades de chave do ONTAP.

* *Nível local* – um conjunto de unidades físicas de estado sólido ou unidades de disco rígido em que você armazena seus dados. Talvez você os conheça como agregados. Na verdade, se você usar a CLI do ONTAP, você ainda verá o termo _agregado_ usado para representar um nível local.
* * Camada de nuvem* – armazenamento na nuvem usado pelo ONTAP quando você deseja ter alguns de seus dados fora do local por um dos vários motivos. Se você está pensando na parte da nuvem de um FabricPool, você já descobriu isso. E, se você estiver usando um sistema StorageGRID, sua nuvem pode não estar fora do local. (Uma experiência semelhante à nuvem no local é chamada de _nuvem privada_.)
* *Storage VM* – uma máquina virtual em execução no ONTAP que fornece serviços de armazenamento e dados aos seus clientes. Você pode saber isso como um _SVM_ ou um _vserver_.
* *Interface de rede* - um endereço e propriedades atribuídos a uma porta de rede física. Você pode saber isso como uma _interface lógica (LIF)_.
* *Pausa* - uma ação que pára as operações. Antes do ONTAP 9.8, você pode ter se referido a _quiesce_ em outras versões do Gerenciador de sistema.

