---
sidebar: sidebar 
permalink: concept_nas_provision_overview.html 
keywords: netapp, ontap, provisioning, nas, overview, provision NAS storage, manage NAS services, NAS file service, Linux client, Windows client, NAS multiprotocol, name service, name service switch, NFS, SMB, DNS, LDAP, NIS, Kerberos security, export, share, qtree, name mapping, NAS data service 
summary: O ONTAP permite que você forneça dados para clientes Linux e Windows de forma simples, segura e eficiente. 
---
= Aprenda sobre gerenciamento de NAS com o ONTAP System Manager
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Os tópicos nesta seção mostram como configurar e gerenciar ambientes nas com o System Manager no ONTAP 9.7 e versões posteriores.

Se você estiver usando o gerenciador de sistema clássico (disponível somente no ONTAP 9.7 e versões anteriores), consulte estes tópicos:

* https://docs.netapp.com/us-en/ontap-system-manager-classic/nfs-config/index.html["Visão geral da configuração NFS"^]
* https://docs.netapp.com/us-en/ontap-system-manager-classic/smb-config/index.html["Visão geral da configuração SMB"^]


O System Manager é compatível com fluxos de trabalho para:

* Configuração inicial de clusters que você pretende usar para serviços de arquivos nas.
* Provisionamento de volume adicional para necessidades dinâmicas de storage.
* Configuração e manutenção para instalações de autenticação e segurança padrão do setor.


Com o System Manager, você pode gerenciar serviços nas no nível de componente:

* Protocolos - NFS, SMB ou ambos (multiprotocolo nas)
* Serviços de nomes - DNS, LDAP e NIS
* Switch do serviço de nomes
* Segurança Kerberos e TLS
* Exportações e ações
* Qtrees
* Mapeamento de nomes de usuários e grupos

