---
settings:
  name: ONTAP 9
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  search: ontap, ontap-metrocluster, ontap-fli, ontap-automation, ontap-cli
  langs: pt-br,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: ONTAP docs
    url: "/index.html"
  - section: release-notes
  - section: introduction-concepts
  - section: setup-upgrade
  - section: cluster-admin
  - section: volume-admin
  - section: network-management
  - section: nas-management
  - section: san-management
  - section: object-storage-management
  - section: authentication-access-control
  - section: security-encryption
  - section: data-protection-disaster-recovery
  - section: event-performance-monitoring
  - title: Páginas de manual do ONTAP
    url: "/concepts/manual-pages.html"
  - title: Avisos legais
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
