---
sidebar: sidebar 
permalink: task-svm-admin-dashboard-sm.html 
keywords: netapp, system manager, ontap, administration, svm, storage vm, volume, vserver, dashboard, administrator, tenant, multi-tenancy, protocol, network interface, performance 
summary: Os administradores de cluster podem conceder aos administradores de SVM acesso para monitorar e gerenciar as SVMs. Os administradores de SVM podem monitorar e gerenciar as SVMs com o painel de administração de SVM no ONTAP System Manager. 
---
= Gerencie e monitore SVMs do ONTAP com System Manager
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A partir do ONTAP 9.19.1, os administradores de SVM podem monitorar e gerenciar suas próprias SVMs usando um painel de controle dedicado do System Manager.

.Antes de começar
O administrador do seu cluster deve fornecer-lhe:

* Endereço IP de gerenciamento para a SVM
* Credenciais (nome de usuário e senha) para o painel de controle do System Manager da SVM (o usuário vsadmin deve estar desbloqueado)
* Opcionalmente, permissões para adicionar volumes na SVM


.Passos
. Digite o endereço IP de gerenciamento da SVM em um navegador.
. Digite seu nome de usuário e senha para o administrador do SVM (vsadmin).
. Selecione *Sign in*.
+
O painel do ONTAP System Manager é aberto.

. Você pode visualizar as seguintes informações sobre a SVM:
+
[cols="1,2"]
|===
| Informações SVM | Descrição 


| Protocolos | Os protocolos habilitados na SVM. 


| Detalhes | Informações do NIS e LDAP, idioma e o período de retenção após a exclusão de um volume. 


| Desempenho | Estatísticas de desempenho de latência, IOPS e throughput por hora, dia, semana, mês ou ano para o protocolo selecionado. 
|===
. Opcionalmente, você pode baixar os dados em um arquivo de valores separados por vírgula (csv) para análise posterior.
. Selecione *armazenamento > volumes*.
+
A página do painel de controle de Volumes é aberta.

+
O administrador do cluster pode conceder permissão para adicionar volumes à SVM. Se essa permissão não for concedida, selecionar o botão *Adicionar* falhará e uma mensagem de erro será exibida.



.Informações relacionadas
* link:concepts/cluster-svm-administrators-concept.html["Administração de clusters e SVM"]
* link:task_cp_dashboard_tour.html#performance["Saiba mais sobre gerenciamento de clusters nos painéis do ONTAP System Manager (seção Desempenho)"]
* link:volumes/manage-volumes-task.html["Gerenciar volumes ONTAP com o System Manager"]

