---
sidebar: sidebar 
permalink: task_admin_recover_deleted_volumes.html 
keywords: netapp, ontap, administration, recover, recovering, recovery, deleted, undelete, volume, volumes, recover deleted volume, SVM, storage VM, vserver, FlexVol volume, purging volume, volume retention time, deleting a volume 
summary: Se você tiver excluído acidentalmente um ou mais volumes do FlexVol, poderá recuperar esses volumes. Você também pode excluir os volumes permanentemente limpando os volumes. 
---
= Recuperar volumes excluídos
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se você excluiu acidentalmente um ou mais volumes do FlexVol, use o Gerenciador do sistema para recuperar esses volumes. A partir do ONTAP 9.8, você também pode usar o Gerenciador de sistema para recuperar volumes do FlexGroup. Você também pode excluir os volumes permanentemente limpando os volumes.

O tempo de retenção de volume pode ser definido em um nível de VM de storage. Por padrão, o tempo de retenção do volume é definido para 12 horas.



== Selecionar volumes eliminados

.Passos
. Clique em *armazenamento > volumes*.
. Clique em *mais > Mostrar volumes excluídos*.
. Selecione os volumes e clique na ação desejada para recuperar ou excluir permanentemente os volumes.




== Repor as configurações de volume

A exclusão de um volume exclui as configurações associadas do volume. A recuperação de um volume não repõe todas as configurações. Execute as seguintes tarefas manualmente após recuperar um volume para trazer o volume de volta ao seu estado original:

.Passos
. Mude o nome do volume.
. Configure um caminho de junção (nas).
. Crie mapeamentos para LUNs no volume (SAN).
. Associe uma política de snapshot e uma política de exportação ao volume.
. Adicione novas regras de política de cota para o volume.
. Adicione uma política DE QOS para o volume.

