---
sidebar: sidebar 
permalink: task_cp_monitor_cluster_performance_ci.html 
keywords: netapp, ontap, cluster, performance, monitor, monitoring, headroom, cpu, cpus, data infrastructure insights, troubleshoot, optimize, private data center, Kafka, MongoDB, Nginx, Active IQ Unified Manager, cluster performance, monitor performance 
summary: Com o Data Infrastructure Insights, você pode monitorar, solucionar problemas e otimizar todos os seus recursos, incluindo suas nuvens públicas e seus data centers privados. 
---
= Monitore o desempenho do cluster com o ONTAP Data Infrastructure Insights
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O NetApp Data Infrastructure Insights é uma ferramenta de monitoramento que oferece visibilidade de toda a sua infraestrutura. Com o Data Infrastructure Insights, você pode monitorar, solucionar problemas e otimizar todos os seus recursos, incluindo suas nuvens públicas e seus data centers privados.



== Monitore, solucione problemas e otimize todos os seus recursos

O Data Infrastructure Insights ajuda a reduzir significativamente o tempo de resolução de problemas e evita que eles afetem os usuários finais. Ele também ajuda a reduzir os custos de infraestrutura de nuvem. Sua exposição a ameaças internas é reduzida ao proteger seus dados com inteligência acionável.

O Data Infrastructure Insights oferece visibilidade de toda a sua infraestrutura híbrida em um só lugar, da nuvem pública ao seu data center. Você pode criar instantaneamente painéis relevantes que podem ser personalizados de acordo com suas necessidades específicas. Você também pode criar alertas direcionados e condicionais que sejam específicos e relevantes para as necessidades da sua organização.

A detecção avançada de anomalias ajuda a corrigir problemas de forma proativa, antes que eles ocorram. Você pode visualizar a contenção e a degradação de recursos automaticamente para restaurar os workloads afetados com rapidez. A solução de problemas vai mais rapidamente com a hierarquia de relações criada automaticamente entre os diferentes componentes da pilha.

Você pode identificar recursos não utilizados ou abandonados em todo o seu ambiente, o que ajuda a descobrir oportunidades de dimensionar corretamente a infraestrutura e otimizar todo o seu gasto.

O Data Infrastructure Insights visualiza a topologia do seu sistema para entender a arquitetura do Kubernetes. Você pode monitorar a integridade dos clusters do Kubernetes, incluindo os nós com problemas, e aumentar o zoom quando encontrar um problema.

O Data Infrastructure Insights ajuda você a proteger os dados organizacionais contra uso indevido por usuários mal-intencionados ou comprometidos por meio de aprendizado de máquina avançado e detecção de anomalias que fornecem inteligência acionável sobre ameaças internas.

O Data Infrastructure Insights ajuda você a visualizar as métricas do Kubernetes para que você possa entender completamente as relações entre seus pods, nós e clusters. Você pode avaliar a integridade de um cluster ou um pod de trabalho, bem como a carga que ele está processando atualmente, permitindo que você assuma o comando do cluster K8S e controle a integridade e o custo da implantação.

.Links relacionados
* link:https://docs.netapp.com/us-en/cloudinsights/task_cloud_insights_onboarding_1.html["Comece a usar o Data Infrastructure Insights"^]

