---
sidebar: sidebar 
permalink: task_admin_monitor_capacity_in_sm.html 
keywords: used storage, digital advisor, local tier capacity, aggregate capacity, add capacity, used capacity, available, total capacity, inactive data, overprovision, overflows, snapshot copy reserves, reserves, clone, maximum capacity limit, storage VM, allocate 
summary: Com o System Manager, você pode monitorar quanto de capacidade de storage foi usada e quanto ainda está disponível para um cluster, uma camada local ou uma VM de storage. 
---
= Monitore a capacidade do cluster, da categoria e do SVM no ONTAP System Manager
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Com o System Manager, você pode monitorar quanto de capacidade de storage foi usada e quanto ainda está disponível para um cluster, uma camada local ou uma VM de storage.

Com cada versão do ONTAP, o Gerenciador de sistemas fornece informações de monitoramento de capacidade mais robustas:

* A partir do ONTAP 9.13,1, é possível habilitar um limite máximo de capacidade para uma VM de storage e definir um limite para acionar alertas quando o storage usado atinge uma determinada porcentagem da capacidade máxima.
* A partir do ONTAP 9.12,1, o Gerenciador de sistema exibe a quantidade de capacidade comprometida de um nível local.
* A partir do ONTAP 9.10.1, o Gerenciador de sistemas permite visualizar dados históricos sobre a capacidade e projeções do cluster sobre a quantidade de capacidade que será usada ou disponível no futuro. Também é possível monitorar a capacidade de camadas e volumes locais.



NOTE: As medições da capacidade utilizada são apresentadas de forma diferente, dependendo da versão do ONTAP. Saiba mais em link:./concepts/capacity-measurements-in-sm-concept.html["Medições de capacidade no System Manager"].



== Exibir a capacidade de um cluster

Pode visualizar as medições de capacidade de um cluster no painel de instrumentos no System Manager.

.Antes de começar
Para exibir dados relacionados à capacidade na nuvem, você precisa ter uma conta no Digital Advisor e estar conetado.

.Passos
. No System Manager, clique em *Dashboard*.
. Na seção *capacidade*, você pode ver o seguinte:
+
--
** Capacidade total utilizada do cluster
** Capacidade total disponível do cluster
** Percentagens de capacidade utilizada e disponível.
** Relação de redução de dados.
** Quantidade de capacidade usada na nuvem.
** Histórico de uso da capacidade.
** Projeção do uso da capacidade


--
+

NOTE: No System Manager, as representações de capacidade não são responsáveis pelas capacidades da camada de storage raiz (agregado).

. Clique no gráfico para ver mais detalhes sobre a capacidade do cluster.
+
As medições de capacidade são apresentadas em duas cartas de barras:

+
--
** O gráfico superior exibe a capacidade física: O tamanho do espaço físico usado, reservado e disponível.
** O gráfico inferior exibe a capacidade lógica: O tamanho dos dados do cliente, instantâneos e clones e o espaço lógico total usado.


--
+
Abaixo dos gráficos de barras estão as medições para redução de dados:

+
--
** Taxa de redução de dados apenas para os dados do cliente (snapshots e clones não estão incluídos).
** Relação geral de redução de dados.


--


Para obter mais informações, link:./concepts/capacity-measurements-in-sm-concept.html["Medições de capacidade no System Manager"]consulte .



== Visualizar a capacidade de um nível local

Você pode visualizar detalhes sobre a capacidade das camadas locais. A partir do ONTAP 9.12.1, a visualização de *Capacidade* também inclui a quantidade de capacidade comprometida para uma camada local, permitindo que você determine se precisa adicionar capacidade à camada local para acomodar a capacidade comprometida e evitar a falta de espaço livre.

.Passos
. Clique em *armazenamento > camadas*.
. Selecione o nome do nível local.
. Na página *Visão geral*, na seção *capacidade*, a capacidade é mostrada em um gráfico de barras com três medidas:
+
** Capacidade utilizada e reservada
** Capacidade disponível
** Capacidade comprometida (começando com ONTAP 9.12,1)


. Clique no gráfico para ver detalhes sobre a capacidade do nível local.
+
As medições de capacidade são apresentadas em duas cartas de barras:

+
--
** O gráfico de barras superior exibe a capacidade física: O tamanho do espaço físico usado, reservado e disponível.
** O gráfico de barras inferior exibe a capacidade lógica: O tamanho dos dados do cliente, instantâneos e clones e o total do espaço lógico usado.


--
+
Abaixo dos gráficos de barras estão as relações de medição para redução de dados:

+
--
** Taxa de redução de dados apenas para os dados do cliente (snapshots e clones não estão incluídos).
** Relação geral de redução de dados.


--


Para obter mais informações, link:./concepts/capacity-measurements-in-sm-concept.html["Medições de capacidade no System Manager"]consulte .

.Ações opcionais
* Se a capacidade comprometida for maior que a capacidade do nível local, você pode considerar adicionar capacidade ao nível local antes que ele fique sem espaço livre. link:./disks-aggregates/add-disks-local-tier-aggr-task.html["Adicionar capacidade a um nível local (adicionar discos a um agregado)"]Consulte .
* Você também pode exibir o armazenamento que volumes específicos usam no nível local selecionando a guia *volumes*.




== Visualizar a capacidade dos volumes em uma VM de storage

Você pode ver quanto storage é usado pelos volumes em uma VM de storage e quanto de capacidade ainda está disponível. A medição total do armazenamento usado e disponível é chamada de "capacidade entre volumes".

.Passos
. Selecione *Storage* > *Storage VMs*.
. Clique no nome da VM de armazenamento.
. Role até a seção *Capacity*, que mostra um gráfico de barras com as seguintes medidas:
+
--
** *Físico usado*: Soma do armazenamento físico usado em todos os volumes nesta VM de armazenamento.
** *Disponível*: Soma da capacidade disponível em todos os volumes nesta VM de armazenamento.
** *Uso lógico*: Soma do armazenamento lógico usado em todos os volumes nesta VM de armazenamento.


--


Para obter mais detalhes sobre as medições, link:./concepts/capacity-measurements-in-sm-concept.html["Medições de capacidade no System Manager"]consulte .



== Exibir o limite máximo de capacidade de uma VM de storage

A partir do ONTAP 9.13,1, é possível visualizar o limite máximo de capacidade de uma VM de armazenamento.

.Antes de começar
Você deve link:manage-max-cap-limit-svm-in-sm-task.html["Ative o limite máximo de capacidade de uma VM de storage"] antes de poder visualizá-lo.

.Passos
. Selecione *Storage* > *Storage VMs*.
+
Pode visualizar as medições da capacidade máxima de duas formas:

+
--
** Na linha da VM de armazenamento, veja a coluna *capacidade máxima* que contém um gráfico de barras que mostra a capacidade usada, a capacidade disponível e a capacidade máxima.
** Clique no nome da VM de armazenamento. Na guia *Visão geral*, role para ver os valores limite de capacidade máxima, capacidade alocada e capacidade de alerta na coluna esquerda.


--


.Informações relacionadas
* link:manage-max-cap-limit-svm-in-sm-task.html#edit-max-cap-limit-svm["Edite o limite máximo de capacidade de uma VM de armazenamento"]
* link:./concepts/capacity-measurements-in-sm-concept.html["Medições de capacidade no System Manager"]

