---
permalink: tape-backup/access-event-log-files-backup-restore-operations-task.html 
sidebar: sidebar 
keywords: access, event, log, files, rdfile, nodeshell, tap, backup, monitor, restore, operations 
summary: Você pode acessar os arquivos de log de eventos para operações de backup e restauração de fita no diretório /etc/log/ usando o comando rdfile no nodeshell. Você pode exibir esses arquivos de log de eventos para monitorar operações de backup e restauração de fita. 
---
= Acesse os arquivos de log de eventos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode acessar os arquivos de log de eventos para operações de backup e restauração de fita `/etc/log/` no diretório usando o `rdfile` comando no nodeshell. Você pode exibir esses arquivos de log de eventos para monitorar operações de backup e restauração de fita.

.Sobre esta tarefa
Com configurações adicionais, como uma função de controle de acesso com acesso ao `spi` serviço da Web ou uma conta de usuário configurada com o `http` método de acesso, você também pode usar um navegador da Web para acessar esses arquivos de log.

.Passos
. Para acessar o nodeshell, digite o seguinte comando:
+
`*node run -node _node_name_*`

+
`node_name` é o nome do nó.

. Para acessar os arquivos de log de eventos para operações de backup e restauração de fita, digite o seguinte comando:
+
`*rdfile /etc/log/backup*`



.Informações relacionadas
link:../system-admin/index.html["Administração do sistema"]
