---
permalink: tape-backup/add-drives-libraries-concept.html 
sidebar: sidebar 
keywords: add, tape, drives, libraries, storage, system 
summary: 'Você pode adicionar unidades de fita e bibliotecas ao sistema de armazenamento dinamicamente (sem colocar o sistema de armazenamento offline).' 
---
= Como você adiciona unidades de fita e bibliotecas aos sistemas de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode adicionar unidades de fita e bibliotecas ao sistema de armazenamento dinamicamente (sem colocar o sistema de armazenamento offline).

Quando você adiciona um novo trocador médio, o sistema de armazenamento deteta sua presença e adiciona-a à configuração. Se o trocador de meio já estiver referenciado nas informações de alias, não serão criados novos nomes lógicos. Se a biblioteca não for referenciada, o sistema de armazenamento cria um novo alias para o trocador de médio.

Em uma configuração de biblioteca de fitas, você deve configurar uma unidade de fita ou um carregador médio no LUN 0 de uma porta de destino para o ONTAP descobrir todos os trocadores médios e unidades de fita nessa porta de destino.
