---
permalink: tape-backup/assign-tape-aliases-task.html 
sidebar: sidebar 
keywords: assign, tape, aliases, device, identification, drive, medium, changer, logical, names, backup 
summary: Para facilitar a identificação do dispositivo, você pode atribuir aliases de fita a uma unidade de fita ou trocador de médio porte. Os aliases fornecem uma correspondência entre os nomes lógicos dos dispositivos de backup e um nome atribuído permanentemente à unidade de fita ou ao trocador de Mídia. 
---
= Atribua aliases de fita
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para facilitar a identificação do dispositivo, você pode atribuir aliases de fita a uma unidade de fita ou trocador de médio porte. Os aliases fornecem uma correspondência entre os nomes lógicos dos dispositivos de backup e um nome atribuído permanentemente à unidade de fita ou ao trocador de Mídia.

.Passos
. Atribua um alias a uma unidade de fita ou trocador de médio usando o `storage tape alias set` comando.
+
Para obter mais informações sobre esse comando, consulte as páginas man.

+
Você pode visualizar as informações do número de série (SN) sobre as unidades de fita usando o `system node hardware tape drive show` comando e sobre bibliotecas de fitas usando os `system node hardware tape library show` comandos.

+
O comando a seguir define um nome de alias para uma unidade de fita com o número de série SN[123456]L4 anexado ao nó, cluster1-01:

+
[listing]
----
cluster-01::> storage tape alias set  -node cluster-01 -name st3 -mapping SN[123456]L4
----
+
O comando a seguir define um nome de alias para um trocador de Mídia com número de série SN[65432] anexado ao nó, cluster1-01:

+
[listing]
----
cluster-01::> storage tape alias set  -node cluster-01 -name mc1 -mapping SN[65432]
----


.Informações relacionadas
xref:assign-tape-aliases-concept.adoc[O que é a distorção da fita]

xref:remove-tape-aliases-task.adoc[Removendo aliases de fita]
