---
permalink: tape-backup/availability-volumes-tapes-backup-restore-lif-reference.html 
sidebar: sidebar 
keywords: lif, availability, volumes, tape, devices, backup, restore, types, cab, extension, application 
summary: 'Você pode configurar um aplicativo de backup para estabelecer uma conexão de controle NDMP em qualquer um dos tipos de LIF em um cluster. No modo NDMP com escopo de máquina virtual de armazenamento (SVM), você pode determinar a disponibilidade de volumes e dispositivos de fita para operações de backup e restauração, dependendo desses tipos de LIF e do status da extensão DA CABINE.' 
---
= Disponibilidade de volumes e dispositivos de fita para backup e restauração em diferentes tipos de LIF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar um aplicativo de backup para estabelecer uma conexão de controle NDMP em qualquer um dos tipos de LIF em um cluster. No modo NDMP com escopo de máquina virtual de armazenamento (SVM), você pode determinar a disponibilidade de volumes e dispositivos de fita para operações de backup e restauração, dependendo desses tipos de LIF e do status da extensão DA CABINE.

As tabelas a seguir mostram a disponibilidade de volumes e dispositivos de fita para tipos de LIF de conexão de controle NDMP e o status da EXTENSÃO DA CABINE:



== Disponibilidade de volumes e dispositivos de fita quando a EXTENSÃO CAB não é suportada pelo aplicativo de backup

|===
| Tipo de LIF de conexão de controle NDMP | Volumes disponíveis para backup ou restauração | Dispositivos de fita disponíveis para backup ou restauração 


 a| 
LIF de gerenciamento de nós
 a| 
Todos os volumes hospedados por um nó
 a| 
Dispositivos de fita conetados ao nó que hospeda o LIF de gerenciamento de nós



 a| 
LIF de dados
 a| 
Somente volumes pertencentes ao SVM hospedados por um nó que hospeda o data LIF
 a| 
Nenhum



 a| 
LIF de gerenciamento de clusters
 a| 
Todos os volumes hospedados por um nó que hospeda o LIF de gerenciamento de cluster
 a| 
Nenhum



 a| 
LIF entre clusters
 a| 
Todos os volumes hospedados por um nó que hospeda o LIF entre clusters
 a| 
Dispositivos de fita conetados ao nó que hospeda o LIF entre clusters

|===


== Disponibilidade de volumes e dispositivos de fita quando a EXTENSÃO CAB é suportada pelo aplicativo de backup

|===
| Tipo de LIF de conexão de controle NDMP | Volumes disponíveis para backup ou restauração | Dispositivos de fita disponíveis para backup ou restauração 


 a| 
LIF de gerenciamento de nós
 a| 
Todos os volumes hospedados por um nó
 a| 
Dispositivos de fita conetados ao nó que hospeda o LIF de gerenciamento de nós



 a| 
LIF de dados
 a| 
Todos os volumes pertencentes ao SVM que hospeda o data LIF
 a| 
Nenhum



 a| 
LIF de gerenciamento de clusters
 a| 
Todos os volumes no cluster
 a| 
Todos os dispositivos de fita no cluster



 a| 
LIF entre clusters
 a| 
Todos os volumes no cluster
 a| 
Todos os dispositivos de fita no cluster

|===