---
permalink: tape-backup/commands-manage-node-scoped-ndmp-reference.html 
sidebar: sidebar 
keywords: command, manage, node, scoped, ndmp, mode 
summary: Você pode usar os comandos ndmp dos serviços do sistema para gerenciar NDMP em um nível de nó. Alguns desses comandos são obsoletos e serão removidos em uma futura versão principal. 
---
= Comandos para gerenciar o modo NDMP com escopo de nó no ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar os `system services ndmp` comandos para gerenciar NDMP em um nível de nó. Alguns desses comandos são obsoletos e serão removidos em uma futura versão principal.

Você pode usar os seguintes comandos NDMP somente no nível avançado de privilégio:

* `system services ndmp service terminate`
* `system services ndmp service start`
* `system services ndmp service stop`
* `system services ndmp log start`
* `system services ndmp log stop`


|===
| Se você quiser... | Use este comando... 


 a| 
Ativar o serviço NDMP
 a| 
`system services ndmp on`*



 a| 
Desativar o serviço NDMP
 a| 
`system services ndmp off`*



 a| 
Apresentar a configuração NDMP
 a| 
`system services ndmp show`*



 a| 
Modificar a configuração NDMP
 a| 
`system services ndmp modify`*



 a| 
Exibir a versão padrão do NDMP
 a| 
`system services ndmp version`*



 a| 
Exibir a configuração do serviço NDMP
 a| 
`system services ndmp service show`



 a| 
Modificar a configuração do serviço NDMP
 a| 
`system services ndmp service modify`



 a| 
Exibir todas as sessões NDMP
 a| 
`system services ndmp status`



 a| 
Exibir informações detalhadas sobre todas as sessões NDMP
 a| 
`system services ndmp probe`



 a| 
Termine a sessão NDMP especificada
 a| 
`system services ndmp kill`



 a| 
Encerrar todas as sessões NDMP
 a| 
`system services ndmp kill-all`



 a| 
Altere a senha NDMP
 a| 
`system services ndmp password`*



 a| 
Ative o modo NDMP com escopo de nó
 a| 
`system services ndmp node-scope-mode on`*



 a| 
Desative o modo NDMP com escopo de nó
 a| 
`system services ndmp node-scope-mode off`*



 a| 
Exibir o status do modo NDMP com escopo do nó
 a| 
`system services ndmp node-scope-mode status`*



 a| 
Encerrar com força todas as sessões NDMP
 a| 
`system services ndmp service terminate`



 a| 
Inicie o daemon de serviço NDMP
 a| 
`system services ndmp service start`



 a| 
Pare o daemon de serviço NDMP
 a| 
`system services ndmp service stop`



 a| 
Inicie o registo para a sessão NDMP especificada
 a| 
`system services ndmp log start`*



 a| 
Parar o registo para a sessão NDMP especificada
 a| 
`system services ndmp log stop`*

|===
* Esses comandos são obsoletos e serão removidos em uma futura versão principal.


Saiba mais sobre `system services ndmp` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+services+ndmp["Referência do comando ONTAP"^]na .
