---
permalink: tape-backup/commands-manage-drives-media-changers-reference.html 
sidebar: sidebar 
keywords: manage, tape, drive, media, changer, operation, cluster, cartridge, position, online, offline, reset, clear 
summary: Existem comandos para visualizar informações sobre unidades de fita e trocadores de Mídia em um cluster, colocar uma unidade de fita on-line e colocá-la off-line, modificar a posição do cartucho da unidade de fita, definir e limpar o nome do alias da unidade de fita e redefinir uma unidade de fita. Você também pode exibir e redefinir estatísticas de unidade de fita. 
---
= Comandos ONTAP para gerenciar unidades de fita, trocadores de mídia e operações de unidades de fita
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Existem comandos para visualizar informações sobre unidades de fita e trocadores de Mídia em um cluster, colocar uma unidade de fita on-line e colocá-la off-line, modificar a posição do cartucho da unidade de fita, definir e limpar o nome do alias da unidade de fita e redefinir uma unidade de fita. Você também pode exibir e redefinir estatísticas de unidade de fita.

|===
| Se você quiser... | Use este comando... 


 a| 
Coloque uma unidade de fita on-line
 a| 
`storage tape online`



 a| 
Limpe um nome de alias para unidade de fita ou trocador de Mídia
 a| 
`storage tape alias clear`



 a| 
Ative ou desative uma operação de rastreamento de fita para uma unidade de fita
 a| 
`storage tape trace`



 a| 
Modifique a posição do cartucho da unidade de fita
 a| 
`storage tape position`



 a| 
Redefina uma unidade de fita
 a| 
`storage tape reset`

[NOTE]
====
Este comando está disponível apenas no nível avançado de privilégios.

====


 a| 
Defina um nome de alias para unidade de fita ou trocador de Mídia
 a| 
`storage tape alias set`



 a| 
Tire uma unidade de fita off-line
 a| 
`storage tape offline`



 a| 
Veja informações sobre todas as unidades de fita e trocadores de Mídia
 a| 
`storage tape show`



 a| 
Exibir informações sobre unidades de fita conetadas ao cluster
 a| 
* `storage tape show-tape-drive`
* `system node hardware tape drive show`




 a| 
Veja informações sobre os modificadores de Mídia conetados ao cluster
 a| 
`storage tape show-media-changer`



 a| 
Exibir informações de erro sobre unidades de fita conetadas ao cluster
 a| 
`storage tape show-errors`



 a| 
Veja todas as unidades de fita qualificadas e compatíveis do ONTAP conetadas a cada nó no cluster
 a| 
`storage tape show-supported-status`



 a| 
Exibir aliases de todas as unidades de fita e alteradores de Mídia conetados a cada nó no cluster
 a| 
`storage tape alias show`



 a| 
Redefina a leitura de estatísticas de uma unidade de fita para zero
 a| 
`storage stats tape zero` `tape_name`

Você deve usar este comando no nodeshell.



 a| 
Ver unidades de fita suportadas pelo ONTAP
 a| 
`storage show tape supported [-v]`

Você deve usar este comando no nodeshell. Você pode usar a `-v` opção para exibir mais detalhes sobre cada unidade de fita.



 a| 
Veja as estatísticas do dispositivo de fita para entender o desempenho da fita e verificar o padrão de uso
 a| 
`storage stats tape` `tape_name`

Você deve usar este comando no nodeshell.

|===
.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=storage+tape["fita de armazenamento"^]

