---
permalink: tape-backup/common-ndmp-topologies-reference.html 
sidebar: sidebar 
keywords: ndmp, tape, backup, topologies, storage, system, local, data, server 
summary: 'O NDMP dá suporte a várias topologias e configurações entre aplicativos de backup e sistemas de storage ou outros servidores NDMP que fornecem dados (sistemas de arquivos) e serviços de fita.' 
---
= Aprenda sobre topologias comuns de backup de fita ONTAP NDMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O NDMP dá suporte a várias topologias e configurações entre aplicativos de backup e sistemas de storage ou outros servidores NDMP que fornecem dados (sistemas de arquivos) e serviços de fita.



== Sistema de storage para fita local

Na configuração mais simples, um aplicativo de backup faz backup dos dados de um sistema de storage para um subsistema de fita conetado ao sistema de storage. A conexão de controle NDMP existe através do limite da rede. A conexão de dados NDMP que existe no sistema de storage entre os serviços de dados e fita é chamada de configuração local NDMP.



== Sistema de storage para fita anexado a outro sistema de storage

Um aplicativo de backup também pode fazer backup de dados de um sistema de armazenamento para uma biblioteca de fitas (um trocador de médio com uma ou mais unidades de fita) conetada a outro sistema de armazenamento. Neste caso, a conexão de dados NDMP entre os serviços de dados e fita é fornecida por uma conexão de rede TCP ou TCP/IPv6. Isso é chamado de uma configuração de sistema de storage três vias NDMP para o sistema de storage.



== Biblioteca de fitas conetada ao sistema de storage à rede

As bibliotecas de fitas habilitadas para NDMP fornecem uma variação da configuração de três vias. Nesse caso, a biblioteca de fitas se coneta diretamente à rede TCP/IP e se comunica com o aplicativo de backup e o sistema de armazenamento por meio de um servidor NDMP interno.



== Sistema de storage para servidor de dados para fita ou servidor para sistema de storage para fita

O NDMP também dá suporte a configurações de três vias de sistema de storage para servidor de dados e servidor para storage, embora essas variantes sejam menos amplamente implantadas. O sistema de armazenamento para servidor permite o backup de dados do sistema de armazenamento em uma biblioteca de fitas conetada ao host do aplicativo de backup ou a outro sistema de servidor de dados. A configuração do sistema de servidor para armazenamento permite que os dados do servidor sejam copiados para uma biblioteca de fitas conetada ao sistema de armazenamento.
