---
permalink: tape-backup/could-not-initialize-media-reference.html 
sidebar: sidebar 
keywords: initiate, media, error, corrective, action, fix, problem, tape, drive, corrupt, damaged, backup, active, io, thread 
summary: Não foi possível inicializar o suporte. 
---
= Não foi possível inicializar o suporte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
* *Mensagem*
+
`Could not initialize media`

* *Causa*
+
Você pode receber esse erro por um dos seguintes motivos:

+
** A unidade de fita usada para o backup está corrompida ou danificada.
** A fita não contém o backup completo ou está corrompida.
** O número máximo de threads de e/S de fita locais ativos está atualmente em uso.
+
Você pode ter um máximo de 16 unidades de fita locais ativas.



* *Ações corretivas*
+
** Se a unidade de fita estiver corrompida ou danificada, tente novamente a operação com uma unidade de fita válida.
** Se a fita não contiver o backup completo ou estiver corrompida, não será possível executar a operação de restauração.
** Se os recursos de fita não estiverem disponíveis, aguarde que alguns dos trabalhos de backup ou restauração sejam concluídos e tente novamente a operação.



