---
permalink: tape-backup/data-backup-dump-concept.html 
sidebar: sidebar 
keywords: dump, engine, flexvol, volumes, backup, recovery, snapshot, copy, tape, device 
summary: Dump é uma solução de backup e recuperação baseada em snapshot da ONTAP que ajuda você a fazer backup de arquivos e diretórios de um snapshot para um dispositivo de fita e restaurar os dados de backup para um sistema de armazenamento. 
---
= Sobre o motor de descarga para volumes FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dump é uma solução de backup e recuperação baseada em snapshot da ONTAP que ajuda você a fazer backup de arquivos e diretórios de um snapshot para um dispositivo de fita e restaurar os dados de backup para um sistema de armazenamento.

Você pode fazer backup dos dados do sistema de arquivos, como diretórios, arquivos e suas configurações de segurança associadas, em um dispositivo de fita usando o backup de despejo. Você pode fazer backup de um volume inteiro, de uma qtree inteiro ou de uma subárvore que não seja um volume inteiro nem uma qtree inteiro.

Você pode executar um backup ou restauração de despejo usando aplicativos de backup compatíveis com NDMP.

Quando você executa um backup de despejo, você pode especificar o snapshot a ser usado para um backup. Se você não especificar um snapshot para o backup, o mecanismo de despejo cria um snapshot para o backup. Após a conclusão da operação de backup, o motor de descarga exclui esse instantâneo.

Você pode executar backups de nível 0, incrementais ou diferenciais na fita usando o mecanismo de despejo.

[NOTE]
====
Depois de reverter para uma versão anterior ao Data ONTAP 8.3, você deve executar uma operação de backup de linha de base antes de executar uma operação de backup incremental.

====
.Informações relacionadas
link:../setup-upgrade/index.html["Atualize, reverta ou downgrade"]
