---
permalink: tape-backup/dump-volume-move-concept.html 
sidebar: sidebar 
keywords: dump, works, volume, move, tape, backup, restore, storage, system 
summary: As operações de backup e restauração em fita e a movimentação de volume podem ser executadas em paralelo até que a fase final de transição seja tentada pelo sistema de storage. Após essa fase, novas operações de backup e restauração de fita não são permitidas no volume que está sendo movido. No entanto, as operações atuais continuam a ser executadas até a conclusão. 
---
= Como o dump funciona com a movimentação de volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As operações de backup e restauração em fita e a movimentação de volume podem ser executadas em paralelo até que a fase final de transição seja tentada pelo sistema de storage. Após essa fase, novas operações de backup e restauração de fita não são permitidas no volume que está sendo movido. No entanto, as operações atuais continuam a ser executadas até a conclusão.

A tabela a seguir descreve o comportamento das operações de backup e restauração de fita após a operação de movimentação de volume:

|===
| Se você estiver executando operações de backup e restauração de fita na... | Então... 


 a| 
Modo NDMP com escopo de máquina virtual de storage (SVM) quando a EXTENSÃO CAB é suportada pelo aplicativo de backup
 a| 
Você pode continuar executando operações incrementais de backup em fita e restauração em volumes somente leitura/gravação e leitura sem reconfigurar políticas de backup.



 a| 
Modo NDMP com escopo SVM quando a EXTENSÃO CAB não é suportada pelo aplicativo de backup
 a| 
Você pode continuar executando operações incrementais de backup em fita e restauração em volumes somente leitura/gravação e leitura se migrar o LIF configurado na política de backup para o nó que hospeda o agregado de destino. Caso contrário, após a movimentação do volume, você deve executar um backup de linha de base antes de executar a operação de backup incremental.

|===
[NOTE]
====
Quando ocorre uma movimentação de volume, se o volume pertencente a uma SVM diferente no nó de destino tiver o mesmo nome do volume movido, então você não poderá executar operações de backup incrementais do volume movido.

====