---
permalink: tape-backup/dump-snapmirror-single-file-lun-restore-concept.html 
sidebar: sidebar 
keywords: dump, works, snapmirror, single, file, lun, restore, operation 
summary: Antes de executar operações de backup de despejo ou restauração em um volume para o qual um único arquivo ou LUN é restaurado usando a tecnologia SnapMirror, você deve entender como as operações de despejo funcionam com um único arquivo ou operação de restauração LUN. 
---
= Como o dump funciona com uma restauração de arquivo único ou LUN do ONTAP SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de executar operações de backup de despejo ou restauração em um volume para o qual um único arquivo ou LUN é restaurado usando a tecnologia SnapMirror, você deve entender como as operações de despejo funcionam com um único arquivo ou operação de restauração LUN.

Durante uma operação de restauração de um único arquivo ou LUN do SnapMirror, a e/S do cliente é restrita no arquivo ou LUN que está sendo restaurado. Quando a operação de restauração de um único arquivo ou LUN terminar, a restrição de e/S no arquivo ou LUN é removida. Se um backup de despejo for executado em um volume para o qual um único arquivo ou LUN é restaurado, o arquivo ou LUN que tem restrição de e/S cliente não será incluído no backup de despejo. Em uma operação de backup subsequente, esse arquivo ou LUN é feito backup em fita após a restrição de e/S ser removida.

Não é possível executar uma restauração de despejo e uma operação de restauração de arquivo único SnapMirror ou LUN simultaneamente no mesmo volume.
