---
permalink: tape-backup/dump-events-concept.html 
sidebar: sidebar 
keywords: dump, event, field, information, parenthesis, type 
summary: O campo evento para um evento de despejo contém um tipo de evento seguido de informações específicas do evento entre parênteses. 
---
= Quais são os eventos de despejo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O campo evento para um evento de despejo contém um tipo de evento seguido de informações específicas do evento entre parênteses.

A tabela a seguir descreve os eventos, suas descrições e as informações de eventos relacionados que podem ser gravadas para uma operação de despejo:

|===
| Evento | Descrição | Informações sobre eventos 


 a| 
Iniciar
 a| 
O despejo NDMP é iniciado
 a| 
Nível de despejo e o tipo de despejo



 a| 
Fim
 a| 
Despejos concluídos com sucesso
 a| 
Quantidade de dados processados



 a| 
Abortar
 a| 
A operação é cancelada
 a| 
Quantidade de dados processados



 a| 
Opções
 a| 
As opções especificadas são listadas
 a| 
Todas as opções e seus valores associados, incluindo opções NDMP



 a| 
Tape_open (fita aberta)
 a| 
A fita está aberta para leitura/gravação
 a| 
O novo nome do dispositivo de fita



 a| 
Tape_Close (Fechar fita)
 a| 
A fita está fechada para leitura/gravação
 a| 
O nome do dispositivo de fita



 a| 
Mudança de fase
 a| 
Um despejo está entrando em uma nova fase de processamento
 a| 
O nome da nova fase



 a| 
Erro
 a| 
Um despejo encontrou um evento inesperado
 a| 
Mensagem de erro



 a| 
Snapshot
 a| 
Um instantâneo é criado ou localizado
 a| 
O nome e a hora do instantâneo



 a| 
Base_dump
 a| 
Foi localizada uma entrada de despejo base no metafile interno
 a| 
O nível e o tempo do despejo base (apenas para despejos incrementais)

|===