---
permalink: tape-backup/dump-backup-concept.html 
sidebar: sidebar 
keywords: dump, backup, qtree, file, system, data 
summary: Um backup de despejo grava dados do sistema de arquivos do disco para a fita usando um processo predefinido. Você pode fazer backup de um volume, uma qtree ou uma subárvore que não seja um volume inteiro nem uma qtree inteiro. 
---
= Como funciona um backup de despejo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um backup de despejo grava dados do sistema de arquivos do disco para a fita usando um processo predefinido. Você pode fazer backup de um volume, uma qtree ou uma subárvore que não seja um volume inteiro nem uma qtree inteiro.

A tabela a seguir descreve o processo que o ONTAP usa para fazer backup do objeto indicado pelo caminho de despejo:

[cols="1,4"]
|===
| Fase | Ação 


 a| 
1
 a| 
Para backups de volumes inferiores a completos ou de qtree, o ONTAP percorre diretórios para identificar os arquivos a serem copiados. Se você estiver fazendo backup de um volume ou qtree inteiro, o ONTAP combina esse estágio com o Estágio 2.



 a| 
2
 a| 
Para um backup de volume completo ou de qtree completo, o ONTAP identifica os diretórios nos volumes ou qtrees a serem copiados.



 a| 
3
 a| 
O ONTAP grava os diretórios em fita.



 a| 
4
 a| 
O ONTAP grava os arquivos em fita.



 a| 
5
 a| 
O ONTAP grava as informações da ACL (se aplicável) na fita.

|===
O backup de despejo usa uma cópia Snapshot de seus dados para o backup. Portanto, você não precisa colocar o volume off-line antes de iniciar o backup.

O backup de despejo nomeia cada cópia Snapshot que ele cria como `snapshot_for_backup.n`, onde `n` é um número inteiro começando em 0. Cada vez que o backup de despejo cria uma cópia Snapshot, ele aumenta o número inteiro em 1. O número inteiro é redefinido para 0 após o sistema de armazenamento ser reiniciado. Depois que a operação de backup for concluída, o mecanismo de despejo excluirá essa cópia Snapshot.

Quando o ONTAP executa vários backups de despejo simultaneamente, o mecanismo de despejo cria várias cópias Snapshot. Por exemplo, se o ONTAP estiver executando dois backups de despejo simultaneamente, você encontrará as seguintes cópias Snapshot nos volumes a partir dos quais os dados estão sendo copiados: `snapshot_for_backup.0` E `snapshot_for_backup.1`.

[NOTE]
====
Quando você está fazendo backup de uma cópia Snapshot, o mecanismo de despejo não cria uma cópia Snapshot adicional.

====