---
permalink: tape-backup/environment-variables-concept.html 
sidebar: sidebar 
keywords: environment, variable, information, backup, restore, operation, ndmp, application, storage, system 
summary: As variáveis de ambiente são usadas para comunicar informações sobre uma operação de backup ou restauração entre um aplicativo de backup habilitado para NDMP e um sistema de armazenamento. 
---
= Visão geral das variáveis de ambiente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As variáveis de ambiente são usadas para comunicar informações sobre uma operação de backup ou restauração entre um aplicativo de backup habilitado para NDMP e um sistema de armazenamento.

Por exemplo, se um usuário especificar que um aplicativo de backup deve fazer `/vserver1/vol1/dir1` backup , o aplicativo de backup define a variável de ambiente DO SISTEMA DE ARQUIVOS como `/vserver1/vol1/dir1`. Da mesma forma, se um usuário especificar que um backup deve ser um backup de nível 1, o aplicativo de backup define a variável de ambiente de NÍVEL como 1 (um).

[NOTE]
====
A configuração e a análise de variáveis de ambiente são geralmente transparentes para os administradores de backup, ou seja, o aplicativo de backup as define automaticamente.

====
Um administrador de backup raramente especifica variáveis de ambiente; no entanto, você pode querer alterar o valor de uma variável de ambiente daquele definido pelo aplicativo de backup para caraterizar ou contornar um problema funcional ou de desempenho. Por exemplo, um administrador pode querer desativar temporariamente a geração do histórico de arquivos para determinar se o processamento de informações do histórico de arquivos do aplicativo de backup está contribuindo para problemas de desempenho ou problemas funcionais.

Muitos aplicativos de backup fornecem um meio de substituir ou modificar variáveis de ambiente ou especificar variáveis de ambiente adicionais. Para obter informações, consulte a documentação do aplicativo de backup.
