---
permalink: tape-backup/event-logging-concept.html 
sidebar: sidebar 
keywords: monitor, tape, backup, restore, operations, flexvol, volumes 
summary: Você pode exibir os arquivos de log de eventos para monitorar as operações de backup e restauração de fita. O ONTAP Registra automaticamente eventos significativos de backup e restauração e o momento em que eles ocorrem em um arquivo de log chamado backup no diretório /etc/log/ do controlador. Por predefinição, o registo de eventos está definido como ligado. 
---
= Monitore as operações de backup e restauração de fita ONTAP para volumes FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode exibir os arquivos de log de eventos para monitorar as operações de backup e restauração de fita. O ONTAP Registra automaticamente eventos significativos de backup e restauração e o momento em que eles ocorrem em um arquivo de log chamado `backup` no diretório do controlador `/etc/log/`. Por predefinição, o registo de eventos está definido para `on`.

Talvez você queira exibir arquivos de log de eventos pelos seguintes motivos:

* Verificar se um backup noturno foi bem-sucedido
* Coleta de estatísticas sobre operações de backup
* Para usar as informações em arquivos de log de eventos anteriores para ajudar a diagnosticar problemas com operações de backup e restauração


Uma vez por semana, os arquivos de log de eventos são girados. O `/etc/log/backup` ficheiro é renomeado para `/etc/log/backup.0`, o `/etc/log/backup.0` ficheiro é renomeado para `/etc/log/backup.1`, e assim por diante. O sistema salva os arquivos de log por até seis semanas; portanto, você pode ter até sete arquivos de mensagem (`/etc/log/backup.[0-5]`e o arquivo atual `/etc/log/backup`).
