---
permalink: tape-backup/increment-chains-concept.html 
sidebar: sidebar 
keywords: increment, chain, backups, path, restore 
summary: Uma cadeia de incremento é uma série de backups incrementais do mesmo caminho. Como você pode especificar qualquer nível de backup a qualquer momento, você deve entender cadeias de incremento para poder executar backups e restaurações de forma eficaz. Você pode executar 31 níveis de operações de backup incrementais. 
---
= Aprenda sobre cadeias de incremento e ONTAP NDMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Uma cadeia de incremento é uma série de backups incrementais do mesmo caminho. Como você pode especificar qualquer nível de backup a qualquer momento, você deve entender cadeias de incremento para poder executar backups e restaurações de forma eficaz. Você pode executar 31 níveis de operações de backup incrementais.

Existem dois tipos de cadeias de incremento:

* Uma cadeia de incremento consecutiva, que é uma sequência de backups incrementais que começa com o nível 0 e é aumentada em 1 em cada backup subsequente.
* Uma cadeia de incremento não consecutiva, onde backups incrementais saltam níveis ou têm níveis que estão fora de sequência, como 0, 2, 3, 1, 4 ou mais comumente 0, 1, 2, 1 ou 0, 1, 2, 1, 1.


Os backups incrementais são baseados no backup de nível mais recente. Por exemplo, a sequência dos níveis de backup 0, 2, 3, 1, 4 fornece duas cadeias de incremento: 0, 2, 3 e 0, 1, 4. A tabela a seguir explica as bases dos backups incrementais:

|===
| Ordem de cópia de segurança | Nível de incremento | Cadeia de incremento | Base | Cópia de segurança dos ficheiros 


 a| 
1
 a| 
0
 a| 
Ambos
 a| 
Arquivos no sistema de armazenamento
 a| 
Todos os arquivos no caminho de backup



 a| 
2
 a| 
2
 a| 
0, 2, 3
 a| 
Backup de nível 0
 a| 
Arquivos no caminho de backup criados desde o backup de nível 0



 a| 
3
 a| 
3
 a| 
0, 2, 3
 a| 
Backup de nível 2
 a| 
Arquivos no caminho de backup criados desde o backup de nível 2



 a| 
4
 a| 
1
 a| 
0, 1, 4
 a| 
Backup de nível 0, porque este é o nível mais recente que é menor do que o backup de nível 1
 a| 
Arquivos no caminho de backup criados desde o backup de nível 0, incluindo arquivos que estão nos backups de nível 2 e nível 3



 a| 
5
 a| 
4
 a| 
0, 1, 4
 a| 
O backup de nível 1, por ser um nível mais baixo e mais recente que os backups de nível 0, nível 2 ou nível 3
 a| 
Arquivos criados desde o backup de nível 1

|===