---
permalink: tape-backup/manage-svm-scoped-ndmp-mode-concept.html 
sidebar: sidebar 
keywords: manage, svm, scope, ndmp, flexvol, volumes, vserver, modify 
summary: Você pode gerenciar NDMP por SVM usando as opções e comandos NDMP. Você pode modificar as opções NDMP usando o comando vserver services ndmp Modify. No modo NDMP com escopo SVM, a autenticação do usuário é integrada ao mecanismo de controle de acesso baseado em funções. 
---
= Gerenciar o modo NDMP com escopo SVM para visão geral do FlexVol volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode gerenciar NDMP por SVM usando as opções e comandos NDMP. Você pode modificar as opções NDMP usando o `vserver services ndmp modify` comando. No modo NDMP com escopo SVM, a autenticação do usuário é integrada ao mecanismo de controle de acesso baseado em funções.

Você pode adicionar NDMP na lista de protocolos permitidos ou não permitidos usando o `vserver modify` comando. Por padrão, NDMP está na lista de protocolos permitidos. Se NDMP for adicionado à lista de protocolos não permitidos, as sessões NDMP não poderão ser estabelecidas.

Você pode controlar o tipo de LIF no qual uma conexão de dados NDMP é estabelecida usando a `-preferred-interface-role` opção. Durante um estabelecimento de conexão de dados NDMP, o NDMP escolhe um endereço IP que pertence ao tipo LIF, conforme especificado por essa opção. Se os endereços IP não pertencem a nenhum desses tipos de LIF, então a conexão de dados NDMP não pode ser estabelecida. Para obter mais informações sobre a `-preferred-interface-role` opção, consulte as páginas de manual.

Para obter mais informações sobre o `vserver services ndmp modify` comando, consulte as páginas de manual.

.Informações relacionadas
xref:commands-manage-svm-scoped-ndmp-reference.adoc[Comandos para gerenciar o modo NDMP com escopo SVM]

xref:cluster-aware-backup-extension-concept.adoc[O que a extensão Cluster Aware Backup faz]

xref:svm-scoped-ndmp-mode-concept.adoc[Qual é o modo NDMP com escopo SVM]

link:../system-admin/index.html["Administração do sistema"]
