---
permalink: tape-backup/manage-svm-scoped-ndmp-mode-concept.html 
sidebar: sidebar 
keywords: manage, svm, scope, ndmp, flexvol, volumes, vserver, modify 
summary: Você pode gerenciar NDMP por SVM usando as opções e comandos NDMP. Você pode modificar as opções NDMP usando o comando vserver services ndmp Modify. No modo NDMP com escopo SVM, a autenticação do usuário é integrada ao mecanismo de controle de acesso baseado em funções. 
---
= Saiba mais sobre como gerenciar o modo NDMP com escopo SVM do ONTAP para volumes FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode gerenciar NDMP por SVM usando as opções e comandos NDMP. Você pode modificar as opções NDMP usando o `vserver services ndmp modify` comando. No modo NDMP com escopo SVM, a autenticação do usuário é integrada ao mecanismo de controle de acesso baseado em funções.

Você pode adicionar NDMP na lista de protocolos permitidos ou não permitidos usando o `vserver modify` comando. Por padrão, NDMP está na lista de protocolos permitidos. Se NDMP for adicionado à lista de protocolos não permitidos, as sessões NDMP não poderão ser estabelecidas.

Você pode controlar o tipo de LIF no qual uma conexão de dados NDMP é estabelecida usando a `-preferred-interface-role` opção. Durante um estabelecimento de conexão de dados NDMP, o NDMP escolhe um endereço IP que pertence ao tipo LIF, conforme especificado por essa opção. Se os endereços IP não pertencem a nenhum desses tipos de LIF, então a conexão de dados NDMP não pode ser estabelecida. Saiba mais sobre `vserver services ndmp modify` o link:https://docs.netapp.com/us-en/ontap-cli/vserver-services-ndmp-modify.html["Referência do comando ONTAP"^]na .



== Comandos para gerenciar o modo NDMP com escopo SVM do ONTAP

Você pode usar os `vserver services ndmp` comandos para gerenciar NDMP em cada máquina virtual de storage (SVM, anteriormente conhecido como SVM).

|===
| Se você quiser... | Use este comando... 


 a| 
Ativar o serviço NDMP
 a| 
`vserver services ndmp on`

[NOTE]
====
O serviço NDMP deve estar sempre habilitado em todos os nós em um cluster. Você pode ativar o serviço NDMP em um nó usando o `system services ndmp on` comando. Por padrão, o serviço NDMP é sempre ativado em um nó.

====


 a| 
Desativar o serviço NDMP
 a| 
`vserver services ndmp off`



 a| 
Apresentar a configuração NDMP
 a| 
`vserver services ndmp show`



 a| 
Modificar a configuração NDMP
 a| 
`vserver services ndmp modify`



 a| 
Exibir a versão padrão do NDMP
 a| 
`vserver services ndmp version`



 a| 
Exibir todas as sessões NDMP
 a| 
`vserver services ndmp status`



 a| 
Exibir informações detalhadas sobre todas as sessões NDMP
 a| 
`vserver services ndmp probe`



 a| 
Encerrar uma sessão NDMP especificada
 a| 
`vserver services ndmp kill`



 a| 
Encerrar todas as sessões NDMP
 a| 
`vserver services ndmp kill-all`



 a| 
Gerar a senha NDMP
 a| 
`vserver services ndmp generate-password`



 a| 
Exibir status do ramal NDMP
 a| 
`vserver services ndmp extensions show`

Este comando está disponível no nível de privilégio avançado.



 a| 
Modificar (ativar ou desativar) o estado da extensão NDMP
 a| 
`vserver services ndmp extensions modify`

Este comando está disponível no nível de privilégio avançado.



 a| 
Inicie o registo para a sessão NDMP especificada
 a| 
`vserver services ndmp log start`

Este comando está disponível no nível de privilégio avançado.



 a| 
Parar o registo para a sessão NDMP especificada
 a| 
`vserver services ndmp log stop`

Este comando está disponível no nível de privilégio avançado.

|===
Saiba mais sobre `vserver services ndmp` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+services+ndmp["Referência do comando ONTAP"^]na .

.Informações relacionadas
xref:commands-manage-svm-scoped-ndmp-reference.adoc[Comandos para gerenciar o modo NDMP com escopo SVM]

xref:cluster-aware-backup-extension-concept.adoc[O que a extensão Cluster Aware Backup faz]

xref:svm-scoped-ndmp-mode-concept.adoc[Qual é o modo NDMP com escopo SVM]

link:../system-admin/index.html["Administração do sistema"]
