---
permalink: tape-backup/ndmp-management-flexgroup-concept.html 
sidebar: sidebar 
keywords: understand, ndmp, flexgroup, volume, flexvol 
summary: A partir do ONTAP 9.7, o NDMP é compatível com volumes FlexGroup. 
---
= Saiba mais sobre o suporte NDMP com volumes ONTAP FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.7, o NDMP é compatível com volumes FlexGroup.

A partir do ONTAP 9.7, o comando ndmpcopy é suportado para transferência de dados entre volumes FlexVol e FlexGroup.

Se você reverter do ONTAP 9.7 para uma versão anterior, as informações de transferência incremental das transferências anteriores não serão mantidas e, portanto, você deverá executar uma cópia de linha de base após reverter.

A partir do ONTAP 9.8, os seguintes recursos NDMP são compatíveis com volumes FlexGroup:

* A mensagem NDMP_snap_RECOVER na classe de extensão 0x2050 pode ser usada para recuperar arquivos individuais em um volume FlexGroup.
* A extensão de backup reiniciável (RBE) NDMP é compatível com volumes FlexGroup.
* As variáveis de ambiente EXCLUEM e MULTI_SUBTREE_NAMES são suportadas para volumes FlexGroup.

