---
permalink: tape-backup/ndmp-server-secure-control-svm-scoped-mode-concept.html 
sidebar: sidebar 
keywords: ndmp, server, supports, secure, control, connections, svm, scoped, mode, ssl, connection, dma, data, management, application 
summary: 'Uma conexão de controle segura pode ser estabelecida entre o aplicativo de gerenciamento de dados (DMA) e o servidor NDMP usando soquetes seguros (SSL/TLS) como mecanismo de comunicação. Esta comunicação SSL é baseada nos certificados do servidor.' 
---
= O servidor NDMP oferece suporte a conexões de controle ONTAP seguras no modo com escopo SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Uma conexão de controle seguro pode ser estabelecida entre o aplicativo de gerenciamento de dados (DMA) e o servidor NDMP usando soquetes seguros (SSL/TLS) como mecanismo de comunicação. Esta comunicação SSL é baseada nos certificados do servidor. O servidor NDMP escuta na porta 30000 (atribuída pela IANA para o serviço "'ndmps").

Depois de estabelecer a conexão do cliente nesta porta, o handshake SSL padrão segue onde o servidor apresenta o certificado ao cliente. Quando o cliente aceita o certificado, o handshake SSL está concluído. Depois que esse processo estiver concluído, toda a comunicação entre o cliente e o servidor é criptografada. O fluxo de trabalho do protocolo NDMP permanece exatamente como antes. A conexão NDMP segura requer apenas autenticação de certificado do lado do servidor. Um DMA pode optar por estabelecer uma conexão conetando-se ao serviço NDMP seguro ou ao serviço NDMP padrão.

Por padrão, o serviço NDMP seguro é desativado para uma máquina virtual de storage (SVM). Você pode ativar ou desativar o serviço NDMP seguro em um determinado SVM usando o `vserver services ndmp modify -vserver vserver -is-secure-control-connection-enabled [true|false]` comando.
