---
permalink: tape-backup/overview-concept.html 
sidebar: sidebar 
keywords: tape, backup, flexvol, volumes, ndmp, data, management, protocol, network, bandwidth, smtape, dump 
summary: 'O ONTAP oferece suporte a backup e restauração em fita por meio do protocolo NDMP (Network Data Management Protocol). O NDMP permite que você faça backup de dados em sistemas de armazenamento diretamente para fita, resultando em uso eficiente da largura de banda da rede. O ONTAP suporta ambos os motores dump e SMTape para backup em fita.' 
---
= Backup em fita de volumes FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O ONTAP oferece suporte a backup e restauração em fita por meio do protocolo NDMP (Network Data Management Protocol). O NDMP permite que você faça backup de dados em sistemas de armazenamento diretamente para fita, resultando em uso eficiente da largura de banda da rede. O ONTAP suporta ambos os motores dump e SMTape para backup em fita.

Você pode executar um backup ou restauração de despejo ou SMTape usando aplicativos de backup compatíveis com NDMP. Apenas a versão NDMP 4 é suportada.



== Backup em fita usando despejo

Dump é um backup baseado em snapshot no qual os dados do sistema de arquivos são copiados para a fita. O mecanismo de despejo do ONTAP faz backup de arquivos, diretórios e as informações da lista de controle de acesso (ACL) aplicáveis à fita. É possível fazer backup de um volume inteiro, de uma qtree inteira ou de uma subárvore que não seja um volume inteiro ou uma qtree inteiro. O dump suporta backups de linha de base, diferenciais e incrementais.



== Backup em fita usando SMTape

O SMTape é uma solução de recuperação de desastres baseada em snapshot da ONTAP que faz backup de blocos de dados em fita. Você pode usar o SMTape para realizar backups de volume em fitas. No entanto, você não pode executar um backup no nível de qtree ou subárvore. O SMTape suporta backups de linha de base, diferenciais e incrementais.
