---
permalink: tape-backup/physical-path-names-concept.html 
sidebar: sidebar 
keywords: physical, path, names, ppn, numerical, address, tape, drive, electrical 
summary: 'Nomes de caminho físico (PPNs) são as sequências de endereços numéricos que o ONTAP atribui a unidades de fita e bibliotecas de fitas com base no adaptador ou switch SCSI-2/3 (local específico) que estão conetados ao sistema de armazenamento. PPNs também são conhecidos como nomes elétricos.' 
---
= Quais são os nomes de caminhos físicos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nomes de caminho físico (PPNs) são as sequências de endereços numéricos que o ONTAP atribui a unidades de fita e bibliotecas de fitas com base no adaptador ou switch SCSI-2/3 (local específico) que estão conetados ao sistema de armazenamento. PPNs também são conhecidos como nomes elétricos.

Os PPNs de dispositivos com conexão direta usam o seguinte formato `host_adapter`: . `device_id_lun`

[NOTE]
====
O valor LUN é exibido apenas para dispositivos de troca de fita e médio cujos valores de LUN não são zero; ou seja, se o valor LUN for zero, a `lun` parte do PPN não é exibida.

====
Por exemplo, o PPN 8,6 indica que o número do adaptador host é 8, o ID do dispositivo é 6 e o número da unidade lógica (LUN) é 0.

Os dispositivos de fita SAS também são dispositivos de conexão direta. Por exemplo, o PPN 5c.4 indica que em um sistema de armazenamento, o HBA SAS está conetado no slot 5, a fita SAS está conetada à porta C do HBA SAS e o ID do dispositivo é 4.

Os PPNs de dispositivos conetados a switch Fibre Channel usam o seguinte formato `switch:port_id`: . `device_id_lun`

Por exemplo, o PPN my_SWITCH:5.3L2 indica que a unidade de fita conetada à porta 5 de um switch chamado MY_SWITCH está definida com ID de dispositivo 3 e tem o LUN 2.

O LUN (número de unidade lógica) é determinado pela unidade. Fibre Channel, unidades de fita SCSI e bibliotecas e discos têm PPNs.

Os PPNs de unidades de fita e bibliotecas não mudam a menos que o nome do switch mude, a unidade de fita ou a biblioteca se mova ou a unidade de fita ou a biblioteca seja reconfigurada. Os PPNs permanecem inalterados após a reinicialização. Por exemplo, se uma unidade de fita chamada MY_SWITCH:5.3L2 for removida e uma nova unidade de fita com o mesmo ID de dispositivo e LUN estiver conetada à porta 5 do switch my_SWITCH, a nova unidade de fita será acessível usando MY_SWITCH:5.3L2.
