---
permalink: tape-backup/qualify-new-drive-dynamically-concept.html 
sidebar: sidebar 
keywords: storage, system, qualifies, new, tape, drive, dynamically 
summary: O sistema de armazenamento qualifica uma unidade de fita dinamicamente, combinando a ID do fornecedor e a ID do produto com as informações contidas na tabela de qualificação da fita. 
---
= Como o sistema de armazenamento qualifica uma nova unidade de fita dinamicamente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O sistema de armazenamento qualifica uma unidade de fita dinamicamente, combinando a ID do fornecedor e a ID do produto com as informações contidas na tabela de qualificação da fita.

Quando você coneta uma unidade de fita ao sistema de armazenamento, ela procura uma correspondência de ID de fornecedor e ID de produto entre as informações obtidas durante a descoberta de fita e as informações na tabela de qualificação de fita interna. Se o sistema de armazenamento detetar uma correspondência, ele marca a unidade de fita como qualificada e pode acessar a unidade de fita. Se o sistema de armazenamento não conseguir encontrar uma correspondência, a unidade de fita permanece no estado não qualificado e não é acessada.
