---
permalink: tape-backup/remove-tape-aliases-task.html 
sidebar: sidebar 
keywords: remove, tape, aliases, clear, command, drive, medium, changer 
summary: Você pode remover aliases usando o comando clear de alias de fita de armazenamento quando aliases persistentes não são mais necessários para uma unidade de fita ou um trocador de médio. 
---
= Remover aliases de fita
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode remover aliases usando o `storage tape alias clear` comando quando aliases persistentes não são mais necessários para uma unidade de fita ou um trocador de médio.

.Passos
. Remova um alias de uma unidade de fita ou trocador de médio usando o `storage tape alias clear` comando.
+
Para obter mais informações sobre esse comando, consulte as páginas man.

+
O comando a seguir remove os aliases de todas as unidades de fita especificando o escopo da operação de eliminação de alias para `tape`:

+
[listing]
----
cluster-01::>storage tape alias clear -node cluster-01 -clear-scope tape
----


.Depois de terminar
Se você estiver executando uma operação de backup ou restauração de fita usando NDMP, depois de remover um alias de uma unidade de fita ou trocador de médio porte, você deve atribuir um novo nome de alias à unidade de fita ou trocador de médio para continuar o acesso ao dispositivo de fita.

.Informações relacionadas
xref:assign-tape-aliases-concept.adoc[O que é a distorção da fita]

xref:assign-tape-aliases-task.adoc[Atribuindo aliases de fita]
