---
permalink: tape-backup/restore-7-mode-clustered-ontap-concept.html 
sidebar: sidebar 
keywords: tape, backup, restore, support, data, 7 mode, storage, system 
summary: Você pode restaurar dados de backup de um sistema de storage operando no modo 7 ou executando o ONTAP para um sistema de storage operando no modo 7 ou executando o ONTAP. 
---
= Suporte de backup e restauração em fita entre o Data ONTAP operando no modo 7 e o ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode restaurar dados de backup de um sistema de storage operando no modo 7 ou executando o ONTAP para um sistema de storage operando no modo 7 ou executando o ONTAP.

As seguintes operações de backup e restauração em fita são suportadas entre o Data ONTAP operando no modo 7 e o ONTAP:

* Fazer backup de um volume de 7 modos para uma unidade de fita conetada a um sistema de armazenamento executando o ONTAP
* Fazer backup de um volume ONTAP em uma unidade de fita conetada a um sistema de 7 modos
* Restaurar dados de backup de um volume de 7 modos a partir de uma unidade de fita conetada a um sistema de armazenamento executando o ONTAP
* Restaurar dados de backup de um volume ONTAP de uma unidade de fita conetada a um sistema de modo 7D.
* Restaurar um volume do modo 7D para um volume ONTAP
+
[NOTE]
====
....
-   A 7-Mode LUN is restored as a LUN on an ONTAP volume.
-   You should retain the ONTAP LUN identifiers when restoring a 7-Mode LUN to an existing ONTAP LUN.
....
====
* Restaurar um volume ONTAP para um volume do modo 7D.
+
[NOTE]
====
Um LUN ONTAP é restaurado como um arquivo regular em um volume de 7 modos.

====

