---
permalink: tape-backup/restore-events-concept.html 
sidebar: sidebar 
keywords: restore, events, parenthesis, type 
summary: O campo evento para um evento de restauração contém um tipo de evento seguido de informações específicas de eventos entre parênteses. 
---
= Quais são os eventos de restauração
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O campo evento para um evento de restauração contém um tipo de evento seguido de informações específicas de eventos entre parênteses.

A tabela a seguir fornece informações sobre os eventos, suas descrições e as informações de eventos relacionados que podem ser gravadas para uma operação de restauração:

|===
| Evento | Descrição | Informações sobre eventos 


 a| 
Iniciar
 a| 
A restauração NDMP é iniciada
 a| 
Nível de restauração e tipo de restauração



 a| 
Fim
 a| 
Restaurações concluídas com êxito
 a| 
Número de arquivos e quantidade de dados processados



 a| 
Abortar
 a| 
A operação é cancelada
 a| 
Número de arquivos e quantidade de dados processados



 a| 
Opções
 a| 
As opções especificadas são listadas
 a| 
Todas as opções e seus valores associados, incluindo opções NDMP



 a| 
Tape_open (fita aberta)
 a| 
A fita está aberta para leitura/gravação
 a| 
O novo nome do dispositivo de fita



 a| 
Tape_Close (Fechar fita)
 a| 
A fita está fechada para leitura/gravação
 a| 
O nome do dispositivo de fita



 a| 
Mudança de fase
 a| 
Restaurar está entrando em uma nova fase de processamento
 a| 
O nome da nova fase



 a| 
Erro
 a| 
Restaurar encontros com um evento inesperado
 a| 
Mensagem de erro

|===