---
permalink: tape-backup/scalability-limits-smtape-sessions-reference.html 
sidebar: sidebar 
keywords: scalability, limits, smtap, backup, restore, session, ndmp, cli, tape, seeding, system, memory 
summary: 'Ao executar operações de backup e restauração SMTape através de NDMP ou CLI (tape seeding), você deve estar ciente do número máximo de sessões de backup e restauração SMTape que podem ser executadas simultaneamente em sistemas de armazenamento com diferentes capacidades de memória do sistema. Este número máximo depende da memória do sistema de um sistema de armazenamento.' 
---
= Limites de escalabilidade do ONTAP para sessões de backup e restauração do SMTape
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao executar operações de backup e restauração SMTape através de NDMP ou CLI (tape seeding), você deve estar ciente do número máximo de sessões de backup e restauração SMTape que podem ser executadas simultaneamente em sistemas de armazenamento com diferentes capacidades de memória do sistema. Este número máximo depende da memória do sistema de um sistema de armazenamento.

[NOTE]
====
Os limites de escalabilidade das sessões de backup e restauração SMTape são diferentes dos limites de sessão NDMP e dos limites de sessão de despejo.

====
|===
| Memória do sistema do sistema de armazenamento | Número total de sessões de backup e restauração SMTape 


 a| 
Menos de 16 GB
 a| 
6



 a| 
Maior ou igual a 16 GB, mas inferior a 24 GB
 a| 
16



 a| 
Maior ou igual a 24 GB
 a| 
32

|===
Você pode obter a memória do sistema do seu sistema de armazenamento usando o `sysconfig -a` comando (disponível através do nodeshell). Saiba mais sobre `sysconfig -a` o link:https://docs.netapp.com/us-en/ontap-cli/system-node-run.html["Referência do comando ONTAP"^]na .

.Informações relacionadas
* xref:scalability-limits-ndmp-sessions-reference.adoc[Limites de escalabilidade para sessões NDMP]
* xref:scalability-limits-dump-backup-restore-sessions-concept.adoc[Limites de escalabilidade para sessões de backup e restauração de despejo]

