---
permalink: tape-backup/serial-numbers-concept.html 
sidebar: sidebar 
keywords: serial, numbers, sn, tape, drive, medium, changer, wwn 
summary: 'Um número de série (SN) é um identificador exclusivo para uma unidade de fita ou um carregador médio. O ONTAP gera aliases baseados no SN em vez do WWN.' 
---
= Quais são os números de série
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um número de série (SN) é um identificador exclusivo para uma unidade de fita ou um carregador médio. O ONTAP gera aliases baseados no SN em vez do WWN.

Como o SN é um identificador exclusivo para uma unidade de fita ou um trocador de médio, o alias permanece o mesmo independentemente dos caminhos de conexão múltiplos para a unidade de fita ou trocador de médio. Isso ajuda os sistemas de armazenamento a rastrear a mesma unidade de fita ou carregador médio em uma configuração de biblioteca de fitas.

O SN de uma unidade de fita ou de um trocador de médio não muda mesmo se você renomear o switch Fibre Channel ao qual a unidade de fita ou o trocador de médio está conetado. No entanto, em uma biblioteca de fitas, se você substituir uma unidade de fita existente por uma nova, o ONTAP gera novos aliases porque o SN da unidade de fita muda. Além disso, se você mover uma unidade de fita existente para um novo slot em uma biblioteca de fitas ou remapear o LUN da unidade de fita, o ONTAP gera um novo alias para essa unidade de fita.

[NOTE]
====
Você deve atualizar os aplicativos de backup com os aliases recém-gerados.

====
O SN de um dispositivo de fita usa o seguinte formato: `SN[xxxxxxxxxx]L[X]`

`x` É um caractere alfanumérico e L``X`` é o LUN do dispositivo de fita. Se o LUN for 0, a parte L``X`` da cadeia de carateres não será exibida.

Cada SN é composto por até 32 carateres; o formato para o SN não é sensível a maiúsculas e minúsculas.
