---
permalink: tape-backup/smtape-capabilities-concept.html 
sidebar: sidebar 
keywords: smtap, capabilities, snapshot, copy, preservation, deduplication, compression, restored, volume, backup, restore 
summary: Os recursos do SMTape, como backup de snapshots, backups incrementais e diferenciais, preservação de recursos de deduplicação e compactação em volumes restaurados e semeadura em fita, ajudam a otimizar suas operações de backup e restauração em fita. 
---
= Recursos SMTape para otimizar operações de backup e restauração de fita ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os recursos do SMTape, como backup de snapshots, backups incrementais e diferenciais, preservação de recursos de deduplicação e compactação em volumes restaurados e semeadura em fita, ajudam a otimizar suas operações de backup e restauração em fita.

O SMTape oferece os seguintes recursos:

* Fornece uma solução de recuperação de desastres
* Permite backups incrementais e diferenciais
* Faz backup de snapshots
* Ativa o backup e a restauração de volumes deduplicados e preserva a deduplicação nos volumes restaurados
* Faz backup de volumes compatados e preserva a compactação nos volumes restaurados
* Ativa a semeadura da fita


O SMTape suporta o fator de bloqueio em múltiplos de 4 KB, na faixa de 4 KB a 256 KB.

[NOTE]
====
Você pode restaurar os dados para volumes criados apenas em duas versões consecutivas do ONTAP.

====