---
permalink: tape-backup/smtape-engine-concept.html 
sidebar: sidebar 
keywords: smtape, disaster, recovery, solution, blocks, data, tape, qtree, subtree, volume, license, baseline, differential, incremental, backup 
summary: O SMTape é uma solução de recuperação de desastres da ONTAP que faz backup de blocos de dados em fita. Você pode usar o SMTape para realizar backups de volume em fitas. No entanto, você não pode executar um backup no nível de qtree ou subárvore. O SMTape suporta backups de linha de base, diferenciais e incrementais. SMTape não requer uma licença. 
---
= Saiba mais sobre o mecanismo ONTAP SMTape para volumes FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SMTape é uma solução de recuperação de desastres da ONTAP que faz backup de blocos de dados em fita. Você pode usar o SMTape para realizar backups de volume em fitas. No entanto, você não pode executar um backup no nível de qtree ou subárvore. O SMTape suporta backups de linha de base, diferenciais e incrementais. SMTape não requer uma licença.

Você pode executar uma operação de backup e restauração SMTape usando um aplicativo de backup compatível com NDMP. Você pode escolher SMTape para executar operações de backup e restauração somente no modo NDMP com escopo de máquina virtual de armazenamento (SVM).

[NOTE]
====
O processo de reversão não é suportado quando uma sessão de backup ou restauração do SMTape está em andamento. Você deve esperar até que a sessão termine ou você deve abortar a sessão NDMP.

====
Usando SMTape, você pode fazer backup de 255 snapshots. Para backups subsequentes de linha de base, incrementais ou diferenciais, você deve excluir snapshots de backup mais antigos.

Antes de executar uma restauração de linha de base, o volume para o qual os dados estão sendo restaurados deve ser do tipo `DP` e esse volume deve estar no estado restrito. Após uma restauração bem-sucedida, esse volume é automaticamente online. É possível realizar restaurações incrementais ou diferenciais subsequentes nesse volume na ordem em que os backups foram executados.
