---
permalink: tape-backup/smtape-volume-move-concept.html 
sidebar: sidebar 
keywords: smtape, backup, operation, volume, move, cutover, phase 
summary: Operações de backup e operações de movimentação de volume do SMTape podem ser executadas em paralelo até que o sistema de armazenamento tente a fase final de transição. Após essa fase, as novas operações de backup SMTape não podem ser executadas no volume que está sendo movido. No entanto, as operações atuais continuam a ser executadas até a conclusão. 
---
= Como o SMTape funciona com a movimentação de volume do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Operações de backup e operações de movimentação de volume do SMTape podem ser executadas em paralelo até que o sistema de armazenamento tente a fase final de transição. Após essa fase, as novas operações de backup SMTape não podem ser executadas no volume que está sendo movido. No entanto, as operações atuais continuam a ser executadas até a conclusão.

Antes de iniciar a fase de transição para um volume, a operação de movimentação de volume verifica as operações ativas de backup SMTape no mesmo volume. Se houver operações de backup ativas do SMTape, a operação de movimentação de volume passa para um estado de transição diferido e permite que as operações de backup do SMTape sejam concluídas. Depois que essas operações de backup forem concluídas, você deverá reiniciar manualmente a operação de movimentação de volume.

Se o aplicativo de backup suportar a EXTENSÃO CAB, você poderá continuar executando operações incrementais de backup em fita e restauração em volumes somente leitura/gravação e leitura sem reconfigurar políticas de backup.

As operações de restauração de linha de base e movimentação de volume não podem ser executadas simultaneamente; no entanto, a restauração incremental pode ser executada em paralelo com as operações de movimentação de volume, com o comportamento semelhante ao das operações de backup SMTape durante operações de movimentação de volume.
