---
permalink: tape-backup/snapshot-copies-during-smtape-backup-concept.html 
sidebar: sidebar 
keywords: snapshot, copy, smtape, backup, baseline, incremental, snapmirror 
summary: Você deve entender como os snapshots são usados durante um backup de linha de base do SMTape e um backup incremental. Há também considerações a ter em mente ao executar um backup usando SMTape. 
---
= Aprenda sobre o uso de snapshots ONTAP durante o backup SMTape
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve entender como os snapshots são usados durante um backup de linha de base do SMTape e um backup incremental. Há também considerações a ter em mente ao executar um backup usando SMTape.



== Backup de linha de base

Durante a execução de um backup de linha de base, você pode especificar o nome do snapshot a ser feito backup em fita. Se nenhum snapshot for especificado, dependendo do tipo de acesso do volume (leitura/gravação ou somente leitura), um snapshot será criado automaticamente ou os snapshots existentes serão usados. Quando você especifica um snapshot para o backup, todos os snapshots mais antigos do que o snapshot especificado também são copiados para fita.

Se você não especificar um snapshot para o backup, ocorrerá o seguinte:

* Para um volume de leitura/gravação, um instantâneo é criado automaticamente.
+
O instantâneo recém-criado e todos os instantâneos mais antigos são copiados para a fita.

* Para um volume somente leitura, todos os instantâneos, incluindo o snapshot mais recente, são copiados para fita.
+
Não são feitos backup de quaisquer novos instantâneos criados após o início do backup.





== Backup incremental

Para operações de backup incrementais ou diferenciais do SMTape, os aplicativos de backup compatíveis com NDMP criam e gerenciam os snapshots.

Você deve sempre especificar um snapshot durante a execução de uma operação de backup incremental. Para uma operação de backup incremental bem-sucedida, o backup instantâneo durante a operação de backup anterior (linha de base ou incremental) deve estar no volume a partir do qual o backup é executado. Para garantir que você use esse snapshot de backup, você deve considerar a política de snapshot atribuída nesse volume ao configurar a política de backup.



== Considerações sobre backups do SMTape em destinos do SnapMirror

* Uma relação de espelho de proteção de dados cria snapshots temporários no volume de destino para replicação.
+
Você não deve usar esses snapshots para backup SMTape.

* Se uma atualização do SnapMirror ocorrer em um volume de destino em um relacionamento de espelho de proteção de dados durante uma operação de backup do SMTape no mesmo volume, o snapshot que é feito backup pelo SMTape não deve ser excluído no volume de origem.
+
Durante a operação de backup, o SMTape bloqueia o instantâneo no volume de destino e, se o instantâneo correspondente for excluído no volume de origem, a operação de atualização do SnapMirror subsequente falha.

* Você não deve usar esses snapshots durante o backup incremental.

