---
permalink: tape-backup/svm-scoped-ndmp-mode-concept.html 
sidebar: sidebar 
keywords: svm, scoped, ndmp, node, tape, backup, storage, cirtual, machine, svm, restore, cab, extension 
summary: 'Você pode executar com êxito as operações de backup em fita e restauração no nível da máquina virtual de storage (SVM) se o serviço NDMP estiver habilitado no SVM. Você pode fazer backup e restaurar todos os volumes hospedados em diferentes nós na SVM de um cluster, se a aplicação de backup suportar a EXTENSÃO CAB.' 
---
= Qual é o modo NDMP com escopo SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode executar com êxito as operações de backup em fita e restauração no nível da máquina virtual de storage (SVM) se o serviço NDMP estiver habilitado no SVM. Você pode fazer backup e restaurar todos os volumes hospedados em diferentes nós na SVM de um cluster, se a aplicação de backup suportar a EXTENSÃO CAB.

Uma conexão de controle NDMP pode ser estabelecida em diferentes tipos de LIF. No modo NDMP com escopo da SVM, esses LIFs pertencem ao data SVM ou admin SVM. A conexão pode ser estabelecida em um LIF somente se o serviço NDMP estiver habilitado no SVM que possui esse LIF.

Um LIF de dados pertence ao data SVM e o LIF entre clusters, LIF de gerenciamento de nós e LIF de clusters pertencem ao administrador SVM.

No modo NDMP com escopo SVM, a disponibilidade de volumes e dispositivos de fita para operações de backup e restauração depende do tipo de LIF no qual a conexão de controle NDMP é estabelecida e do status da extensão DA CABINE. Se o aplicativo de backup suportar a EXTENSÃO CAB e um volume e o dispositivo de fita compartilharem a mesma afinidade, o aplicativo de backup poderá executar uma operação de backup ou restauração local, em vez de uma operação de backup ou restauração de três vias.

.Informações relacionadas
xref:manage-svm-scoped-ndmp-mode-concept.adoc[Gerenciamento do modo NDMP com escopo da SVM para volumes FlexVol]
