---
permalink: tape-backup/tape-reservations-concept.html 
sidebar: sidebar 
keywords: tape, reservation, drive, medium, changer, bridge, libraries, scsi, persistent, reserve, release 
summary: Vários sistemas de armazenamento podem compartilhar o acesso a unidades de fita, trocadores médios, pontes ou bibliotecas de fitas. As reservas de fita garantem que apenas um sistema de armazenamento acesse um dispositivo em qualquer momento específico, ativando o mecanismo de reserva/Liberação SCSI ou as reservas persistentes SCSI para todas as unidades de fita, trocadores médios, bridges e bibliotecas de fitas. 
---
= Saiba mais sobre reservas de fitas ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vários sistemas de armazenamento podem compartilhar o acesso a unidades de fita, trocadores médios, pontes ou bibliotecas de fitas. As reservas de fita garantem que apenas um sistema de armazenamento acesse um dispositivo em qualquer momento específico, ativando o mecanismo de reserva/Liberação SCSI ou as reservas persistentes SCSI para todas as unidades de fita, trocadores médios, bridges e bibliotecas de fitas.

[NOTE]
====
Todos os sistemas que compartilham dispositivos em uma biblioteca, independentemente de os switches estarem envolvidos ou não, devem usar o mesmo método de reserva.

====
O mecanismo de reserva/Liberação SCSI para reservar dispositivos funciona bem em condições normais. No entanto, durante os procedimentos de recuperação de erros de interface, as reservas podem ser perdidas. Se isso ocorrer, iniciadores que não o proprietário reservado podem acessar o dispositivo.

As reservas feitas com SCSI Persistent Reservations não são afetadas por mecanismos de recuperação de erros, como restauração de loop ou restauração de destino; no entanto, nem todos os dispositivos implementam as reservas persistentes SCSI corretamente.
