---
permalink: tape-backup/tape-seeding-concept.html 
sidebar: sidebar 
keywords: tape, seeding, smtape, functionality, destination, flexvol, data, protection, mirror 
summary: A semeadura de fita é uma funcionalidade SMTape que ajuda você a inicializar um FlexVol volume de destino em uma relação de espelho de proteção de dados. 
---
= O que é a semeadura da fita
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A semeadura de fita é uma funcionalidade SMTape que ajuda você a inicializar um FlexVol volume de destino em uma relação de espelho de proteção de dados.

A semeadura de fita permite estabelecer uma relação de espelho de proteção de dados entre um sistema de origem e um sistema de destino através de uma conexão de baixa largura de banda.

O espelhamento incremental das cópias Snapshot da origem para o destino é viável em uma conexão com baixa largura de banda. No entanto, um espelhamento inicial da cópia Snapshot de base leva muito tempo em uma conexão de baixa largura de banda. Nesses casos, você pode executar um backup SMTape do volume de origem para uma fita e usar a fita para transferir a cópia Snapshot de base inicial para o destino. Em seguida, você pode configurar atualizações incrementais de SnapMirror para o sistema de destino usando a conexão de baixa largura de banda.
