---
permalink: tape-backup/tape-devices-concept.html 
sidebar: sidebar 
keywords: tape, device, representation, combination, rewind, type, compression, capability, drive 
summary: Um dispositivo de fita é uma representação de uma unidade de fita. É uma combinação específica do tipo de rebobinagem e capacidade de compressão de uma unidade de fita. 
---
= Saiba mais sobre dispositivos de fita ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um dispositivo de fita é uma representação de uma unidade de fita. É uma combinação específica do tipo de rebobinagem e capacidade de compressão de uma unidade de fita.

Um dispositivo de fita é criado para cada combinação de tipo de rebobinagem e capacidade de compressão. Portanto, uma unidade de fita ou biblioteca de fitas pode ter vários dispositivos de fita associados a ela. Você deve especificar um dispositivo de fita para mover, gravar ou ler fitas.

Quando você instala uma unidade de fita ou uma biblioteca de fitas em um sistema de armazenamento, o ONTAP cria dispositivos de fita associados à unidade de fita ou à biblioteca de fitas.

O ONTAP deteta unidades de fita e bibliotecas de fitas e atribui números lógicos e dispositivos de fita a elas. O ONTAP deteta as bibliotecas e unidades de fita Fibre Channel, SAS e SCSI paralelo quando elas são conetadas às portas de interface. O ONTAP deteta essas unidades quando suas interfaces estão ativadas.
