---
permalink: tape-backup/types-data-dump-engine-restores-concept.html 
sidebar: sidebar 
keywords: types, data, dump, engine, restores, disaster, controller, disruption, file, attribute 
summary: Quando ocorre um desastre ou uma interrupção do controlador, o mecanismo de despejo fornece vários métodos para recuperar todos os dados que você fez backup, de arquivos únicos, para atributos de arquivo, para diretórios inteiros. Conhecer os tipos de dados que o mecanismo de despejo pode restaurar e quando usar qual método de recuperação pode ajudar a minimizar o tempo de inatividade. 
---
= Tipos de dados que o motor de descarga restaura
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando ocorre um desastre ou uma interrupção do controlador, o mecanismo de despejo fornece vários métodos para recuperar todos os dados que você fez backup, de arquivos únicos, para atributos de arquivo, para diretórios inteiros. Conhecer os tipos de dados que o mecanismo de despejo pode restaurar e quando usar qual método de recuperação pode ajudar a minimizar o tempo de inatividade.

Você pode restaurar dados para um LUN on-line mapeado. No entanto, os aplicativos host não podem acessar esse LUN até que a operação de restauração esteja concluída. Após a conclusão da operação de restauração, o cache do host dos dados LUN deve ser lavado para fornecer coerência com os dados restaurados.

O motor de descarga pode recuperar os seguintes dados:

* Conteúdo de arquivos e diretórios
* Permissões de arquivo UNIX
* ACLs
+
Se você restaurar um arquivo que tenha apenas permissões de arquivo UNIX para uma qtree ou volume NTFS, o arquivo não tem ACLs do Windows NT. O sistema de armazenamento usa apenas as permissões de arquivo UNIX neste arquivo até que você crie uma ACL do Windows NT nele.

+
[NOTE]
====
Se você restaurar ACLs de backup de sistemas de armazenamento que executam o Data ONTAP 8.2 para sistemas de armazenamento que executam o Data ONTAP 8.1.x e anteriores que tenham um limite ACE inferior a 1.024, uma ACL padrão será restaurada.

====
* Informações de Qtree
+
As informações de Qtree são usadas somente se uma qtree for restaurada para a raiz de um volume. As informações de Qtree não são usadas se uma qtree for restaurada para um diretório inferior, como `/vs1/vol1/subdir/lowerdir` , e deixar de ser uma qtree.

* Todos os outros atributos de arquivo e diretório
* Fluxos do Windows NT
* LUNs
+
** Um LUN deve ser restaurado para um nível de volume ou um nível de qtree para que ele permaneça como um LUN.
+
Se for restaurado para um diretório, ele será restaurado como um arquivo porque não contém metadados válidos.

** Um LUN de 7 modos é restaurado como LUN em um volume ONTAP.


* Um volume do modo 7D pode ser restaurado para um volume ONTAP.
* Os arquivos alinhados à VM restaurados para um volume de destino herdam as propriedades de alinhamento da VM do volume de destino.
* O volume de destino para uma operação de restauração pode ter arquivos com bloqueios obrigatórios ou de aconselhamento.
+
Ao executar a operação de restauração para um volume de destino, o motor de descarga ignora esses bloqueios.


