---
permalink: tape-backup/use-cases-choosing-tape-backup-method-concept.html 
sidebar: sidebar 
keywords: cases, choose, tape, backup, engine, smtape, dump, restore 
summary: 'O ONTAP suporta dois mecanismos de backup: SMTape e dump. Você deve estar ciente dos casos de uso dos mecanismos de backup SMTape e dump para ajudá-lo a escolher o mecanismo de backup para executar operações de backup e restauração de fita.' 
---
= Casos de uso para mecanismos de backup ONTAP SMTape e dump
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O ONTAP suporta dois mecanismos de backup: SMTape e dump. Você deve estar ciente dos casos de uso dos mecanismos de backup SMTape e dump para ajudá-lo a escolher o mecanismo de backup para executar operações de backup e restauração de fita.

O despejo pode ser usado nos seguintes casos:

* Direct Access Recovery (DAR) de arquivos e diretórios
* Backup de um subconjunto de subdiretórios ou arquivos em um caminho específico
* Excluindo arquivos e diretórios específicos durante backups
* Preservando o backup por longos períodos


SMTape pode ser usado nos seguintes casos:

* Solução de recuperação de desastres
* Preservar a economia de deduplicação e as configurações de deduplicação nos dados de backup durante uma operação de restauração
* Backup de grandes volumes

