---
permalink: software_setup/concept_additional_system_configuration_tasks_to_complete.html 
sidebar: sidebar 
keywords: ontap, software, setup, additional, system, configuration, tasks 
summary: Depois de configurar um cluster, você pode usar o Gerenciador do sistema ou a interface de linha de comando ONTAP para continuar a configurar o cluster. 
---
= Tarefas adicionais de configuração do sistema a serem concluídas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de configurar um cluster, você pode usar o Gerenciador do sistema ou a interface de linha de comando (CLI) do ONTAP para continuar a configuração do cluster.

[cols="2*"]
|===
| Tarefa de configuração do sistema | Recurso 


 a| 
Configurar rede:

* Criar domínios de broadcast
* Crie sub-redes
* Crie espaços IP

 a| 
link:../networking/set_up_nas_path_failover_98_and_later_cli.html["Configurar a rede"]



 a| 
Configure o processador de serviço
 a| 
link:../system-admin/index.html["Administração do sistema"]



 a| 
Coloque seus agregados
 a| 
link:../disks-aggregates/index.html["Gerenciamento de disco e agregado"]



 a| 
Criar e configurar máquinas virtuais de armazenamento de dados (SVMs)
 a| 
link:../nfs-config/index.html["Configuração NFS"]

link:../smb-config/index.html["Configuração SMB"]

link:../san-admin/index.html["Administração da SAN"]



 a| 
Configurar notificações de eventos
 a| 
link:../error-messages/config-workflow-task.html["Configuração EMS"]

|===