---
permalink: software_setup/gather_cluster_setup_information.html 
sidebar: sidebar 
keywords: ontap, software, setup, deciding, decide, if, whether, use, cli, cluster, System Manager, IPv6, HA, root volumes 
summary: Configuração do software 
---
= Reunir informações para configurar um cluster ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de iniciar a configuração do cluster, você deve coletar as informações necessárias para concluir a configuração do cluster, como a porta da interface de gerenciamento de cluster e o endereço IP. Comece reunindo todas as informações relevantes nas planilhas de configuração do cluster. A folha de cálculo de configuração do cluster permite-lhe registar os valores de que necessita durante o processo de configuração do cluster. Se um valor padrão for fornecido, você pode usar esse valor ou então digitar o seu próprio.

.Sobre esta tarefa
Este procedimento se aplica aos sistemas FAS, AFF e ASA. Se você tiver um sistema ASA r2 (ASA A1K, ASA A90, ASA A70, ASA A50, ASA A30, ASA A20 ou ASA C30), siga link:https://docs.netapp.com/us-en/asa-r2/install-setup/initialize-ontap-cluster.html["estes passos"^] para configurar um cluster ONTAP. Os sistemas ASA R2 fornecem uma experiência de ONTAP simplificada específica para clientes somente SAN.



== Predefinições do sistema

Os padrões do sistema são os valores padrão para a rede de cluster privada. É melhor usar esses valores padrão. No entanto, se eles não atenderem aos seus requisitos, você pode usar a tabela para Registrar seus próprios valores.


NOTE: Para clusters configurados para usar switches de rede, cada switch de cluster deve usar o tamanho de MTU 9000.

[cols="2*"]
|===
| Tipos de informação | Seus valores 


| Portas de rede de cluster privado |  


| Máscara de rede de cluster |  


| Endereços IP da interface de cluster (para cada porta de rede de cluster em cada nó) os endereços IP de cada nó devem estar na mesma sub-rede. |  
|===


== Informações do cluster

[cols="2*"]
|===
| Tipos de informação | Seus valores 


| Nome do cluster o nome deve começar com uma letra e deve ter menos de 44 carateres. O nome pode incluir os seguintes carateres especiais: 
`.` `-` `_` |  
|===


== Chaves de licença de recurso

Você pode encontrar chaves de licença para seus pedidos de software iniciais ou complementares no site de suporte da NetApp em *meu suporte* > *licenças de software*.

[cols="2*"]
|===
| Tipos de informação | Seus valores 


| Chaves de licença de recurso |  
|===


== Máquina virtual de storage de administração (SVM)

[cols="2*"]
|===
| Tipos de informação | Seus valores 


 a| 
Senha do administrador do cluster

A senha da conta de administrador que o cluster exige antes de conceder acesso ao console pelo administrador do cluster ou por meio de um protocolo seguro.


NOTE: Para fins de segurança, a gravação de senhas nesta Planilha não é recomendada.

As regras padrão para senhas são as seguintes:

* Uma senha deve ter pelo menos oito carateres.
* Uma senha deve conter pelo menos uma letra e um número.

 a| 



 a| 
Porta de interface de gerenciamento de clusters

A porta física que está conetada à rede de dados e permite que o administrador do cluster gerencie o cluster.
 a| 



 a| 
Endereço IP da interface de gerenciamento de cluster

Um endereço IPv4 ou IPv6 exclusivo para a interface de gerenciamento de cluster. O administrador do cluster usa esse endereço para acessar o administrador SVM e gerenciar o cluster. Normalmente, esse endereço deve estar na rede de dados.

Você pode obter esse endereço IP do administrador responsável pela atribuição de endereços IP na sua organização.

Exemplo: 192.0.2.66
 a| 



 a| 
Máscara de rede de interface de gerenciamento de cluster (IPv4)

A máscara de sub-rede que define o intervalo de endereços IPv4 válidos na rede de gerenciamento de cluster.

Exemplo: 255.255.255.0
 a| 



 a| 
Comprimento da máscara de rede da interface de gerenciamento de cluster (IPv6)

Se a interface de gerenciamento de cluster usar um endereço IPv6, esse valor representa o comprimento do prefixo que define o intervalo de endereços IPv6 válidos na rede de gerenciamento de cluster.

Exemplo: 64
 a| 



 a| 
Gateway padrão da interface de gerenciamento de cluster

O endereço IP do roteador na rede de gerenciamento de cluster.
 a| 



 a| 
Nome de domínio DNS

O nome do domínio DNS da rede.

O nome de domínio deve consistir em carateres alfanuméricos. Para inserir vários nomes de domínio DNS, separe cada nome com uma vírgula ou um espaço.
 a| 



 a| 
Endereços IP do servidor de nomes

Os endereços IP dos servidores de nomes DNS. Separe cada endereço com uma vírgula ou um espaço.
 a| 

|===


== Informações do nó (para cada nó no cluster)

[cols="2*"]
|===
| Tipos de informação | Seus valores 


 a| 
Localização física do controlador (opcional)

Uma descrição da localização física do controlador. Use uma descrição que identifique onde encontrar esse nó no cluster (por exemplo, "'Lab 5, Row 7, Rack B'").
 a| 



 a| 
Porta de interface de gerenciamento de nó

A porta física que está conetada à rede de gerenciamento de nós e permite que o administrador do cluster gerencie o nó.
 a| 



 a| 
Endereço IP da interface de gerenciamento do nó

Um endereço IPv4 ou IPv6 exclusivo para a interface de gerenciamento de nós na rede de gerenciamento. Se você definiu a porta da interface de gerenciamento de nó como uma porta de dados, esse endereço IP deve ser um endereço IP exclusivo na rede de dados.

Você pode obter esse endereço IP do administrador responsável pela atribuição de endereços IP na sua organização.

Exemplo: 192.0.2.66
 a| 



 a| 
Máscara de rede de interface de gerenciamento de nó (IPv4)

A máscara de sub-rede que define o intervalo de endereços IP válidos na rede de gerenciamento de nós.

Se você definiu a porta de interface de gerenciamento de nó como uma porta de dados, a máscara de rede deve ser a máscara de sub-rede da rede de dados.

Exemplo: 255.255.255.0
 a| 



 a| 
Comprimento da máscara de rede da interface de gestão do nó (IPv6)

Se a interface de gerenciamento de nó usa um endereço IPv6, esse valor representa o comprimento do prefixo que define o intervalo de endereços IPv6 válidos na rede de gerenciamento de nó.

Exemplo: 64
 a| 



 a| 
Gateway padrão da interface de gerenciamento de nó

O endereço IP do roteador na rede de gerenciamento de nós.
 a| 

|===


== Informações do servidor NTP

[cols="2*"]
|===
| Tipos de informação | Seus valores 


 a| 
Endereços do servidor NTP

Os endereços IP dos servidores NTP (Network Time Protocol) no seu site. Esses servidores são usados para sincronizar o tempo no cluster.
 a| 

|===