---
permalink: software_setup/task_configure_important_ems_events_to_send_email_notifications.html 
sidebar: sidebar 
keywords: ontap, software, setup, configure, important, ems, events, email, notifications 
summary: Para receber notificações por e-mail dos eventos mais importantes, você deve configurar o EMS para enviar mensagens de e-mail para eventos que sinalizem atividade importante. 
---
= Configurar eventos importantes do EMS para enviar notificações por e-mail
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para receber notificações por e-mail para os eventos mais importantes, você deve configurar o EMS para enviar mensagens de e-mail para eventos que sinalizem atividade importante.

O DNS deve ser configurado no cluster para resolver os endereços de e-mail.

Você pode executar essa tarefa sempre que o cluster estiver sendo executado inserindo os comandos na linha de comando ONTAP.

. Configure as definições do servidor de correio SMTP de eventos:
+
`event config modify -mail-server mailhost.your_domain -mail-from cluster_admin@your_domain`

. Criar um destino de e-mail para notificações de eventos:
+
`event notification destination create -name storage-admins -email your_email@your_domain`

. Configure os eventos importantes para enviar notificações por e-mail:
+
`event notification create -filter-name important-events -destinations storage_admins`


