---
permalink: software_setup/task_create_the_cluster_on_the_first_node.html 
sidebar: sidebar 
keywords: ontap, software, setup, create, cluster, first, node, autosupport, CLI 
summary: 'Você usa o assistente Configuração de cluster para criar o cluster no primeiro nó. O assistente ajuda você a configurar a rede de cluster que coneta os nós, criar a máquina virtual de armazenamento de administrador de cluster (SVM), adicionar chaves de licença de recurso e criar a interface de gerenciamento de nó para o primeiro nó.' 
---
= Crie o cluster no primeiro nó no ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você usa o assistente Configuração de cluster para criar o cluster no primeiro nó. O assistente ajuda você a configurar a rede de cluster que coneta os nós, criar a máquina virtual de armazenamento de administrador de cluster (SVM), adicionar chaves de licença de recurso e criar a interface de gerenciamento de nó para o primeiro nó.


NOTE: Este procedimento aplica-se aos sistemas FAS, AFF e ASA atuais. Se tiver um sistema ASA R2 (ASA A1K, ASA A70 ou ASA A90), siga link:https://docs.netapp.com/us-en/asa-r2/install-setup/initialize-ontap-cluster.html["estes passos"^] para utilizar o Gestor de sistema para configurar um cluster ONTAP. Os sistemas ASA R2 fornecem uma experiência de ONTAP simplificada específica para clientes somente SAN.

.Antes de começar
* Você deve ter instalado, cabeado e ligado o novo sistema de storage de acordo com as instruções de instalação e configuração do modelo da sua plataforma. Consulte https://docs.netapp.com/us-en/ontap-systems/index.html["Documentação do AFF e do FAS"^] .
* As interfaces de rede do cluster devem ser configuradas em cada nó do cluster para comunicação intra-cluster.
* Se você estiver configurando o IPv6 em seu cluster, o IPv6 deve ser configurado no controlador de gerenciamento básico (BMC) para que você possa acessar o sistema usando SSH.


.Passos
. Ligue todos os nós que você está adicionando ao cluster. Isso é necessário para ativar o reconhecimento para a configuração do cluster.
. Conete-se ao console do primeiro nó.
+
O nó é inicializado e, em seguida, o assistente Configuração de cluster é iniciado no console.

+
[listing]
----
Welcome to the cluster setup wizard....
----
. Confirme a declaração AutoSupport.
+
[listing]
----
Type yes to confirm and continue {yes}: yes
----
+

NOTE: O AutoSupport está ativado por predefinição.

. Siga as instruções na tela para atribuir um endereço IP ao nó.
+
A partir do ONTAP 9.13.1, você pode atribuir endereços IPv6 para LIFs de gerenciamento em plataformas A800 e FAS8700. Para versões do ONTAP anteriores a 9.13.1, ou para 9.13.1 e posteriores em outras plataformas, você deve atribuir endereços IPv4 para LIFs de gerenciamento e depois converter para IPv6 depois de concluir a configuração do cluster.

. Pressione *Enter* para continuar.
+
[listing]
----
Do you want to create a new cluster or join an existing cluster? {create, join}:
----
. Criar um novo cluster: `create`
. Aceite as predefinições do sistema ou introduza os seus próprios valores.
. Após a conclusão da configuração, faça login no cluster e verifique se o cluster está ativo e se o primeiro nó está em funcionamento, digitando o comando CLI do ONTAP: `cluster show`
+
O exemplo a seguir mostra um cluster no qual o primeiro nó (cluster1-01) está íntegro e qualificado para participar:

+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
cluster1-01           true    true
----
+
Você pode acessar o assistente Configuração de cluster para alterar qualquer um dos valores inseridos para o SVM admin ou nó SVM usando o `cluster setup` comando.



.Depois de terminar
Se necessário, link:convert-ipv4-to-ipv6-task.html["Converter de IPv4 para IPv6"].
