---
sidebar: sidebar 
permalink: high-availability/halt-reboot-node-wo-takeover-task.html 
keywords: high availability pair, hair, inhibit-takeover, reboot, epsilon, HA 
summary: Você interrompe ou reinicializa um nó em um cluster de dois nós sem iniciar o takeover quando executa determinada manutenção de hardware em um nó ou compartimento. Além disso, você deseja limitar o tempo mantendo o nó do parceiro ativo ou quando há problemas para impedir um takeover manual e manter os agregados e fornecendo dados. Além disso, se o suporte técnico estiver ajudando você na solução de problemas, eles podem fazer com que você execute este procedimento como parte desses esforços. 
---
= Interrompa ou reinicie nós ONTAP sem iniciar a aquisição em clusters de dois nós
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você interrompe ou reinicializa um nó em um cluster de dois nós sem iniciar o takeover quando executa determinada manutenção de hardware em um nó ou compartimento. Além disso, você deseja limitar o tempo mantendo o nó do parceiro ativo ou quando há problemas para impedir um takeover manual e manter os agregados e fornecendo dados. Além disso, se o suporte técnico estiver ajudando você na solução de problemas, eles podem fazer com que você execute este procedimento como parte desses esforços.

.Sobre esta tarefa
* Antes de inibir a aquisição (utilizando o `-inhibit-takeover true` parâmetro), desative a HA do cluster.


[CAUTION]
====
* Em um cluster de dois nós, o cluster HA garante que a falha de um nó não desabilite o cluster. No entanto, se você não desativar a HA do cluster antes de usar o  `-inhibit-takeover true` parâmetro, ambos os nós param de fornecer dados.
* Se você tentar interromper ou reinicializar um nó antes de desativar o HA do cluster, o ONTAP emitirá um aviso e instrui você a desabilitar o HA do cluster.


====
* Você migra LIFs (interfaces lógicas) para o nó de parceiro que deseja permanecer online.
* Se no nó que você está interrompendo ou reinicializando há agregados que você deseja manter, você os move para o nó que deseja permanecer online.


.Passos
. Verifique se ambos os nós estão íntegros:
+
[source, cli]
----
cluster show
----
+
Para ambos os nós, `true` aparece `Health` na coluna.

+
[listing]
----
cluster::> cluster show
Node         Health  Eligibility
------------ ------- ------------
node1        true     true
node2        true     true
----
+
Saiba mais sobre `cluster show` o link:https://docs.netapp.com/us-en/ontap-cli/cluster-show.html["Referência do comando ONTAP"^]na .

. Migre todos os LIFs do nó que você irá desligar ou reinicializar para o nó parceiro:
+
[source, cli]
----
network interface migrate-all -node <node_name>
----
+
Saiba mais sobre `network interface migrate-all` o link:https://docs.netapp.com/us-en/ontap-cli/network-interface-migrate-all.html["Referência do comando ONTAP"^]na .

. Se houver agregados no nó que você irá interromper ou reinicializar e que deseja manter online quando o nó estiver inativo, realoque-os para o nó parceiro.
+
.. Mostre os agregados no nó que você irá interromper ou reinicializar:
+
[source, cli]
----
storage aggregates show -node <node_name>
----
+
Por exemplo, node1 é o nó que será interrompido ou reinicializado:

+
[listing]
----
cluster::> storage aggregates show -node node1
Aggregate  Size  Available  Used%  State  #Vols   Nodes   RAID  Status
---------  ----  ---------  -----  -----  -----   -----   ----  ------
aggr0_node_1_0
           744.9GB   32.68GB   96% online       2 node1    raid_dp,
                                                                normal
aggr1       2.91TB    2.62TB   10% online       8 node1    raid_dp,
                                                                normal
aggr2
            4.36TB    3.74TB   14% online      12 node1    raid_dp,
                                                                normal
test2_aggr  2.18TB    2.18TB    0% online       7 node1    raid_dp,
                                                                normal
4 entries were displayed.
----
.. Mova os agregados para o nó parceiro:
+
[source, cli]
----
storage aggregate relocation start -node <node_name> -destination <node_name> -aggregate-list <aggregate_name>
----
+
Por exemplo, agregados aggr1, aggr2 e test2_aggr estão sendo movidos de node1 para node2:

+
`storage aggregate relocation start -node _node1_ -destination _node2_ -aggregate-list _aggr1_,_aggr2_,_test2_aggr_`



. Desative o HA do cluster:
+
[source, cli]
----
cluster ha modify -configured false
----
+
Quando o HA do cluster está desativado, epsilon é movido automaticamente para o nó 1. A saída de retorno confirma que o HA está desativado: `Notice: HA is disabled`

+

NOTE: Esta operação não desativa o failover de armazenamento.

. Se o nó a ser interrompido ou reinicializado for o nó 1, mova epsilon para o nó 2:
+
.. Defina o nível de privilégio como avançado:
+
[source, cli]
----
set -privilege advanced
----
.. Verifique se o nó 2 está íntegro e apto para epsilon:
+
[source, cli]
----
cluster show
----
.. Remova o epsilon do nó 1:
+
[source, cli]
----
cluster modify -node <node1_name> -epsilon false
----
.. Atribua epsilon ao nó 2:
+
[source, cli]
----
cluster modify -node <node2_name> -epsilon true
----
.. Verifique se epsilon está no nó 2:
+
[source, cli]
----
cluster show
----


. Interrompa ou reinicialize e impeça a tomada de controle do nó alvo:
+
[cols="1h,1h"]
|===


 a| 
Interrompa o nó sem iniciar a tomada de controle:
 a| 
[source, cli]
----
system node halt -node _node_name_ -inhibit-takeover true
----


 a| 
Reinicialize o nó sem iniciar a tomada de controle:
 a| 
[source, cli]
----
system node reboot -node _node_name_ -inhibit-takeover true
----
|===
+

NOTE: Na saída do comando, você verá um aviso perguntando se deseja continuar, digite `y`.

. Verifique se o nó que ainda está online está em bom estado (enquanto o parceiro está inativo):
+
[source, cli]
----
cluster show
----
+
Para o nó on-line, `true` aparece `Health` na coluna.

+

NOTE: Na saída do comando, você verá um aviso de que o cluster HA não está configurado. Você pode ignorar o aviso.

. Execute as ações necessárias para interromper ou reinicializar o nó.
. Inicialize o nó offline a partir do prompt do LOADER:
+
[source, cli]
----
boot_ontap
----
. Verifique se ambos os nós estão íntegros:
+
[source, cli]
----
cluster show
----
+
Para ambos os nós, `true` aparece `Health` na coluna.

+

NOTE: Na saída do comando, você verá um aviso de que o cluster HA não está configurado. Neste momento, pode ignorar o aviso.

. Reativar HA do cluster:
+
[source, cli]
----
cluster ha modify -configured true
----
. Se, anteriormente neste procedimento, você realocou agregados para o nó parceiro, mova-os de volta para o nó de origem.
+
[source, cli]
----
storage aggregate relocation start -node <node_name> -destination <node_name> -aggregate-list <aggregate_name>
----
+
Por exemplo, agregados aggr1, aggr2 e test2_aggr estão sendo movidos do nó node2 para o nó node1:
`storage aggregate relocation start -node _node2_ -destination _node1_ -aggregate-list _aggr1_,_aggr2_,_test2_aggr_`

. Reverter LIFs para suas portas domésticas:
+
.. Veja os LIFs que não estão em casa:
+
[source, cli]
----
network interface show -is-home false
----
+
Saiba mais sobre `network interface show` o link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["Referência do comando ONTAP"^]na .

.. Se houver LIFs não residenciais que não foram migrados do nó para baixo, verifique se é seguro movê-los antes de reverter.
.. Se for seguro fazê-lo, reverta todos os LIFs para home.
+
[source, cli]
----
 network interface revert *
----
+
Saiba mais sobre `network interface revert` o link:https://docs.netapp.com/us-en/ontap-cli/network-interface-revert.html["Referência do comando ONTAP"^]na .





.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/cluster-ha-modify.html["cluster ha modificar"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-relocation-start.html["início da realocação do agregado de armazenamento"^]

