---
permalink: nas-audit/additional-information-reference.html 
sidebar: sidebar 
keywords: additional information 
summary: Depois de testar o acesso de cliente SMB com sucesso, você pode executar a configuração SMB avançada ou adicionar acesso SAN. Depois de testar com êxito o acesso ao cliente NFS, você pode executar uma configuração NFS avançada ou adicionar acesso SAN. Quando o acesso ao protocolo for concluído, você deverá proteger o volume raiz da SVM. 
---
= Onde encontrar informações adicionais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de testar o acesso de cliente SMB com sucesso, você pode executar a configuração SMB avançada ou adicionar acesso SAN. Depois de testar com êxito o acesso ao cliente NFS, você pode executar uma configuração NFS avançada ou adicionar acesso SAN. Quando o acesso ao protocolo for concluído, você deverá proteger o volume raiz da SVM.



== Configuração SMB

Você pode configurar ainda mais o acesso SMB usando o seguinte:

* link:../smb-admin/index.html["Gerenciamento de SMB"]
+
Descreve como configurar e gerenciar o acesso a arquivos usando o protocolo SMB.

* https://www.netapp.com/pdf.html?item=/media/16326-tr-4191pdf.pdf["Relatório técnico da NetApp 4191: Guia de práticas recomendadas para Serviços de arquivos do Windows Clustered Data ONTAP 8.2"^]
+
Fornece uma breve visão geral da implementação de SMB e outros recursos de Serviços de arquivos do Windows com recomendações e informações básicas de solução de problemas para o ONTAP.

* https://www.netapp.com/pdf.html?item=/media/19673-tr-3740.pdf["Relatório técnico da NetApp 3740: Protocolo CIFS de última geração SMB 2 no Data ONTAP"^]
+
Descreve os recursos do SMB 2, detalhes de configuração e sua implementação no ONTAP.





== Configuração NFS

Você pode configurar ainda mais o acesso NFS usando o seguinte:

* link:../nfs-admin/index.html["Gerenciamento de NFS"]
+
Descreve como configurar e gerenciar o acesso a arquivos usando o protocolo NFS.

* https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["Relatório técnico da NetApp 4067: Guia de práticas recomendadas e implementação de NFS"^]
+
Serve como um guia operacional NFSv3 e NFSv4 e fornece uma visão geral do sistema operacional ONTAP com foco em NFSv4.

* https://www.netapp.com/pdf.html?item=/media/16328-tr-4668pdf.pdf["Relatório técnico da NetApp 4668: Guia de práticas recomendadas para serviços de nomes"^]
+
Fornece uma lista abrangente de práticas recomendadas, limites, recomendações e considerações ao configurar LDAP, NIS, DNS e arquivos de usuário e grupo locais para fins de autenticação.

* https://www.netapp.com/pdf.html?item=/media/19384-tr-4616.pdf["Relatório técnico do NetApp 4616: Kerberos NFS no ONTAP com o Microsoft ative Directory"]
* https://www.netapp.com/pdf.html?item=/media/19423-tr-4835.pdf["Relatório técnico do NetApp 4835: Como configurar o LDAP no ONTAP"]
* https://www.netapp.com/pdf.html?item=/media/16398-tr-3580pdf.pdf["Relatório técnico da NetApp 3580: NFSv4 melhorias e melhores práticas Guia de implementação do Data ONTAP"^]
+
Descreve as práticas recomendadas que devem ser seguidas durante a implementação de componentes NFSv4 em clientes AIX, Linux ou Solaris conetados a sistemas que executam o ONTAP.





== Proteção do volume raiz

Depois de configurar protocolos no SVM, você deve garantir que seu volume raiz esteja protegido:

* link:../data-protection/index.html["Proteção de dados"]
+
Descreve como criar um espelhamento de compartilhamento de carga para proteger o volume raiz da SVM, que é uma prática recomendada do NetApp para SVMs habilitadas para nas. Também descreve como recuperar rapidamente de falhas ou perdas de volume promovendo o volume raiz do SVM a partir de um espelhamento de compartilhamento de carga.


