---
permalink: nas-audit/basic-auditing-concept.html 
sidebar: sidebar 
keywords: basic audit concepts 
summary: Para entender a auditoria no ONTAP, você deve estar ciente de alguns conceitos básicos de auditoria. 
---
= Conceitos básicos de auditoria
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para entender a auditoria no ONTAP, você deve estar ciente de alguns conceitos básicos de auditoria.

* *Staging arquivos*
+
Os arquivos binários intermediários em nós individuais onde os Registros de auditoria são armazenados antes da consolidação e conversão. Os arquivos de estadiamento estão contidos nos volumes de estadiamento.

* * Volume de estadiamento*
+
Um volume dedicado criado pelo ONTAP para armazenar arquivos de teste. Há um volume de estadiamento por agregado. Os volumes de preparo são compartilhados por todas as máquinas virtuais de armazenamento (SVMs) habilitadas para auditoria para armazenar Registros de auditoria do acesso a dados para volumes de dados nesse agregado específico. Os Registros de auditoria de cada SVM são armazenados em um diretório separado dentro do volume de teste.

+
Os administradores de cluster podem exibir informações sobre volumes de teste, mas a maioria das outras operações de volume não são permitidas. Somente o ONTAP pode criar volumes de estadiamento. O ONTAP atribui automaticamente um nome aos volumes de teste. Todos os nomes de volume de estadiamento começam com `MDV_aud_` seguido pelo UUID do agregado que contém esse volume de estadiamento (por exemplo: `MDV_aud_1d0131843d4811e296fc123478563412` .)

* *Volumes do sistema*
+
Um FlexVol volume que contém metadados especiais, como metadados para logs de auditoria de serviços de arquivo. O SVM admin é proprietário de volumes de sistema, que podem ser vistos no cluster. Os volumes de estadiamento são um tipo de volume do sistema.

* *Tarefa de consolidação*
+
Uma tarefa que é criada quando a auditoria é ativada. Essa tarefa de longa execução em cada SVM leva os Registros de auditoria de arquivos de teste nos nós membros do SVM. Essa tarefa mescla os Registros de auditoria em ordem cronológica ordenada e os converte em um formato de log de eventos legível pelo usuário especificado na configuração de auditoria -- o formato de arquivo EVTX ou XML. Os logs de eventos convertidos são armazenados no diretório de log de eventos de auditoria especificado na configuração de auditoria SVM.


