---
permalink: nas-audit/certificates-disaster-recovery-non-id-preserve-concept.html 
sidebar: sidebar 
keywords: certificates, replicate, svm, disaster recovery, relationships, non-ID-preserve, configuration 
summary: Os certificados de segurança usados para autenticação SSL ao fazer conexões com servidores FPolicy não são replicados para destinos de recuperação de desastres SVM com configurações que não preservem ID. Embora a configuração do mecanismo externo FPolicy na SVM seja replicada, os certificados de segurança não são replicados. Tem de instalar manualmente os certificados de segurança no destino. 
---
= Os certificados ONTAP FPolicy não são replicados em relacionamentos de recuperação de desastres SVM com uma configuração sem preservação de ID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os certificados de segurança usados para autenticação SSL ao fazer conexões com servidores FPolicy não são replicados para destinos de recuperação de desastres SVM com configurações que não preservem ID. Embora a configuração do mecanismo externo FPolicy na SVM seja replicada, os certificados de segurança não são replicados. Tem de instalar manualmente os certificados de segurança no destino.

Quando você configura a relação de recuperação de desastres SVM, o valor selecionado para a `-identity-preserve` opção `snapmirror create` do comando determina os detalhes de configuração replicados no SVM de destino.

Se você definir `-identity-preserve` a opção como `true` (ID-Preserve), todos os detalhes de configuração do FPolicy serão replicados, incluindo as informações do certificado de segurança. Só tem de instalar os certificados de segurança no destino se definir a opção como `false` (non-ID-Preserve).

.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["SnapMirror create"^]

