---
permalink: nas-audit/cli-change-events-concept.html 
sidebar: sidebar 
keywords: cli change events, audited 
summary: O ONTAP pode auditar certos eventos de mudança de CLI, incluindo certos eventos de compartilhamento de SMB, certos eventos de política de auditoria, determinados eventos de grupo de segurança local, eventos de grupo de usuários locais e eventos de política de autorização. Entender quais eventos de mudança podem ser auditados é útil ao interpretar os resultados dos logs de eventos. 
---
= Saiba mais sobre os eventos de mudança de CLI do ONTAP que podem ser auditados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O ONTAP pode auditar certos eventos de mudança de CLI, incluindo certos eventos de compartilhamento de SMB, certos eventos de política de auditoria, determinados eventos de grupo de segurança local, eventos de grupo de usuários locais e eventos de política de autorização. Entender quais eventos de mudança podem ser auditados é útil ao interpretar os resultados dos logs de eventos.

Você pode gerenciar eventos de alteração da CLI de auditoria de máquina virtual de storage (SVM) girando manualmente os logs de auditoria, habilitando ou desativando a auditoria, exibindo informações sobre auditoria de eventos de alterações, modificando eventos de auditoria de alterações e excluindo eventos de alteração de auditoria.

Como administrador, se você executar qualquer comando para alterar a configuração relacionada aos eventos SMB-share, grupo de usuários local, grupo de segurança local, política de autorização e política de auditoria, um Registro será gerado e o evento correspondente será auditado:

|===


| Categoria Auditoria | Eventos | IDs de eventos | Execute este comando... 


 a| 
Auditoria Mhost
 a| 
mudança de política
 a| 
[4719] Configuração de auditoria alterada
 a| 
`vserver audit disable|enable|modify`



 a| 
compartilhamento de arquivos
 a| 
[5142] a partilha de rede foi adicionada
 a| 
`vserver cifs share create`



 a| 
[5143] a partilha de rede foi modificada
 a| 
`vserver cifs share modify` `vserver cifs share create|modify|delete` `vserver cifs share add|remove`



 a| 
[5144] partilha de rede eliminada
 a| 
`vserver cifs share delete`



 a| 
Auditoria
 a| 
conta de utilizador
 a| 
[4720] usuário local criado
 a| 
`vserver cifs users-and-groups local-user create` `vserver services name-service unix-user create`



 a| 
[4722] utilizador local ativado
 a| 
`vserver cifs users-and-groups local-user create|modify`



 a| 
[4724] Reposição da palavra-passe do utilizador local
 a| 
`vserver cifs users-and-groups local-user set-password`



 a| 
[4725] Utilizador local desativado
 a| 
`vserver cifs users-and-groups local-user create|modify`



 a| 
[4726] utilizador local eliminado
 a| 
`vserver cifs users-and-groups local-user delete` `vserver services name-service unix-user delete`



 a| 
[4738] alteração do utilizador local
 a| 
`vserver cifs users-and-groups local-user modify` `vserver services name-service unix-user modify`



 a| 
[4781] Renomear utilizador local
 a| 
`vserver cifs users-and-groups local-user rename`



 a| 
grupo de segurança
 a| 
[4731] Grupo de Segurança local criado
 a| 
`vserver cifs users-and-groups local-group create` `vserver services name-service unix-group create`



 a| 
[4734] Grupo de Segurança local eliminado
 a| 
`vserver cifs users-and-groups local-group delete` `vserver services name-service unix-group delete`



 a| 
[4735] Grupo de Segurança local modificado
 a| 
`vserver cifs users-and-groups local-group rename|modify` `vserver services name-service unix-group modify`



 a| 
[4732] Usuário adicionado ao Grupo local
 a| 
`vserver cifs users-and-groups local-group add-members` `vserver services name-service unix-group adduser`



 a| 
[4733] Usuário removido do Grupo local
 a| 
`vserver cifs users-and-groups local-group remove-members` `vserver services name-service unix-group deluser`



 a| 
autorização-política-alteração
 a| 
[4704] Direitos de Usuário atribuídos
 a| 
`vserver cifs users-and-groups privilege add-privilege`



 a| 
[4705] Direitos de usuário removidos
 a| 
`vserver cifs users-and-groups privilege remove-privilege|reset-privilege`

|===
.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver["svm"^]

