---
permalink: nas-audit/configure-auditing-unix-security-files-directories-task.html 
sidebar: sidebar 
keywords: configure, audit, unix security style files, directories 
summary: Você configura a auditoria de arquivos e diretórios de estilo de segurança UNIX adicionando ACEs de auditoria a ACLs NFSv4.x. Isso permite que você monitore determinados eventos de acesso a arquivos NFS e diretórios para fins de segurança. 
---
= Configurar a auditoria do ONTAP para arquivos e diretórios de estilo de segurança UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você configura a auditoria de arquivos e diretórios de estilo de segurança UNIX adicionando ACEs de auditoria a ACLs NFSv4.x. Isso permite que você monitore determinados eventos de acesso a arquivos NFS e diretórios para fins de segurança.

.Sobre esta tarefa
Para NFSv4.x, os ACEs discricionários e do sistema são armazenados na mesma ACL. Eles não são armazenados em DACLs e SACLs separados. Portanto, você deve ter cuidado ao adicionar ACEs de auditoria a uma ACL existente para evitar sobrescrever e perder uma ACL existente. A ordem em que você adiciona os ACEs de auditoria a uma ACL existente não importa.

.Passos
. Recupere a ACL existente para o arquivo ou diretório usando o `nfs4_getfacl` comando ou equivalente.
+
Saiba mais sobre como manipular ACLs no link:https://docs.netapp.com/us-en/ontap-cli/["Referência do comando ONTAP"^].

. Anexe os ACEs de auditoria desejados.
. Aplique a ACL atualizada ao arquivo ou diretório usando o `nfs4_setfacl` comando ou equivalente.

