---
permalink: nas-audit/connect-external-fpolicy-servers-task.html 
sidebar: sidebar 
keywords: connect, external fpolicy servers 
summary: Para habilitar o processamento de arquivos, talvez seja necessário conetar-se manualmente a um servidor FPolicy externo se a conexão tiver sido encerrada anteriormente. Uma conexão é terminada após o tempo limite do servidor ser atingido ou devido a algum erro. Como alternativa, o administrador pode encerrar manualmente uma conexão. 
---
= Conete-se a servidores FPolicy externos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para habilitar o processamento de arquivos, talvez seja necessário conetar-se manualmente a um servidor FPolicy externo se a conexão tiver sido encerrada anteriormente. Uma conexão é terminada após o tempo limite do servidor ser atingido ou devido a algum erro. Como alternativa, o administrador pode encerrar manualmente uma conexão.

.Sobre esta tarefa
Se ocorrer um erro fatal, a conexão com o servidor FPolicy pode ser encerrada. Depois de resolver o problema que causou o erro fatal, você deve se reconetar manualmente ao servidor FPolicy.

.Passos
. Conete-se ao servidor FPolicy externo usando o `vserver fpolicy engine-connect` comando.
+
Para obter mais informações sobre o comando, consulte as páginas de manual.

. Verifique se o servidor FPolicy externo está conetado usando o `vserver fpolicy show-engine` comando.
+
Para obter mais informações sobre o comando, consulte as páginas de manual.


