---
permalink: nas-audit/connect-external-fpolicy-servers-task.html 
sidebar: sidebar 
keywords: connect, external fpolicy servers 
summary: Para habilitar o processamento de arquivos, talvez seja necessário conetar-se manualmente a um servidor FPolicy externo se a conexão tiver sido encerrada anteriormente. Uma conexão é terminada após o tempo limite do servidor ser atingido ou devido a algum erro. Como alternativa, o administrador pode encerrar manualmente uma conexão. 
---
= Conete-se a servidores FPolicy externos no ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para habilitar o processamento de arquivos, talvez seja necessário conetar-se manualmente a um servidor FPolicy externo se a conexão tiver sido encerrada anteriormente. Uma conexão é terminada após o tempo limite do servidor ser atingido ou devido a algum erro. Como alternativa, o administrador pode encerrar manualmente uma conexão.

.Sobre esta tarefa
Se ocorrer um erro fatal, a conexão com o servidor FPolicy pode ser encerrada. Depois de resolver o problema que causou o erro fatal, você deve se reconetar manualmente ao servidor FPolicy.

.Passos
. Conete-se ao servidor FPolicy externo usando o `vserver fpolicy engine-connect` comando.
+
Saiba mais sobre `vserver fpolicy engine-connect` o link:https://docs.netapp.com/us-en/ontap-cli/vserver-fpolicy-engine-connect.html["Referência do comando ONTAP"^]na .

. Verifique se o servidor FPolicy externo está conetado usando o `vserver fpolicy show-engine` comando.
+
Saiba mais sobre `vserver fpolicy show-engine` o link:https://docs.netapp.com/us-en/ontap-cli/vserver-fpolicy-show-engine.html["Referência do comando ONTAP"^]na .


