---
permalink: nas-audit/create-fpolicy-scope-task.html 
sidebar: sidebar 
keywords: create, fpolicy scope 
summary: Depois de criar a política FPolicy, você precisa criar um escopo FPolicy. Ao criar o escopo, você associa o escopo a uma política FPolicy. Um escopo define os limites nos quais a política FPolicy se aplica. Os escopos podem incluir ou excluir arquivos com base em compartilhamentos, políticas de exportação, volumes e extensões de arquivo. 
---
= Crie o escopo FPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de criar a política FPolicy, você precisa criar um escopo FPolicy. Ao criar o escopo, você associa o escopo a uma política FPolicy. Um escopo define os limites nos quais a política FPolicy se aplica. Os escopos podem incluir ou excluir arquivos com base em compartilhamentos, políticas de exportação, volumes e extensões de arquivo.

.O que você vai precisar
A folha de trabalho do âmbito da FPolicy tem de ser concluída. A política FPolicy deve existir com um mecanismo externo associado (se a política estiver configurada para usar servidores FPolicy externos) e deve ter pelo menos um evento FPolicy associado.

.Passos
. Crie o escopo FPolicy usando o `vserver fpolicy policy scope create` comando.
+
`vserver fpolicy policy scope create -vserver-name vs1.example.com -policy-name policy1 -volumes-to-include datavol1,datavol2`

. Verifique a configuração do escopo do FPolicy usando o `vserver fpolicy policy scope show` comando.
+
`vserver fpolicy policy scope show -vserver vs1.example.com -instance`

+
[listing]
----

                   Vserver: vs1.example.com
                    Policy: policy1
         Shares to Include: -
         Shares to Exclude: -
        Volumes to Include: datavol1, datavol2
        Volumes to Exclude: -
Export Policies to Include: -
Export Policies to Exclude: -
File Extensions to Include: -
File Extensions to Exclude: -
----

