---
permalink: nas-audit/delete-security-trace-records-task.html 
sidebar: sidebar 
keywords: delete, security trace records 
summary: Depois de terminar de usar um Registro de rastreamento de filtro para verificar a segurança do acesso ao arquivo ou para solucionar problemas de acesso ao cliente SMB ou NFS, você pode excluir o Registro de rastreamento de segurança do log de rastreamento de segurança. 
---
= Excluir registros de rastreamento de segurança em SVMs ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de terminar de usar um Registro de rastreamento de filtro para verificar a segurança do acesso ao arquivo ou para solucionar problemas de acesso ao cliente SMB ou NFS, você pode excluir o Registro de rastreamento de segurança do log de rastreamento de segurança.

.Sobre esta tarefa
Antes de poder eliminar um registo de rastreio de segurança, tem de saber o número de sequência do registo.

[NOTE]
====
Cada máquina virtual de storage (SVM) pode armazenar no máximo 128 Registros de rastreamento. Se o máximo for atingido na SVM, os Registros de rastreamento mais antigos serão excluídos automaticamente à medida que novos forem adicionados. Se você não quiser excluir manualmente os Registros de rastreamento neste SVM, você pode permitir que o ONTAP exclua automaticamente os resultados de rastreamento mais antigos depois que o máximo for atingido para abrir espaço para novos resultados.

====
.Passos
. Identifique o número de sequência do registo que pretende eliminar:
+
`vserver security trace trace-result show -vserver vserver_name -instance`

. Eliminar o registo de rastreio de segurança:
+
`vserver security trace trace-result delete -node node_name -vserver vserver_name -seqnum integer`

+
`vserver security trace trace-result delete -vserver vs1 -node node1 -seqnum 999`

+
** `-node` `node_name` é o nome do nó do cluster no qual ocorreu o evento de rastreamento de permissões que você deseja excluir.
+
Este é um parâmetro obrigatório.

** `-vserver` `vserver_name` É o nome do SVM no qual ocorreu o evento de rastreamento de permissões que você deseja excluir.
+
Este é um parâmetro obrigatório.

** `-seqnum` `integer` é o número de sequência do evento de registo que pretende eliminar.
+
Este é um parâmetro obrigatório.




