---
permalink: nas-audit/display-enabled-fpolicy-policies-task.html 
sidebar: sidebar 
keywords: display, information, enabled fpolicy policies 
summary: 'Você pode exibir informações sobre políticas FPolicy ativadas para determinar qual mecanismo externo FPolicy ele está configurado para usar, qual é a prioridade para a política e a qual máquina virtual de armazenamento (SVM) a política FPolicy está associada.' 
---
= Exibir informações sobre políticas FPolicy ativadas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode exibir informações sobre políticas FPolicy ativadas para determinar qual mecanismo externo FPolicy ele está configurado para usar, qual é a prioridade para a política e a qual máquina virtual de armazenamento (SVM) a política FPolicy está associada.

.Sobre esta tarefa
Se você não especificar nenhum parâmetro, o comando exibirá as seguintes informações:

* Nome do SVM
* Nome da política
* Prioridade da política


Você pode usar parâmetros de comando para filtrar a saída do comando por critérios especificados.

.Passo
. Exiba informações sobre políticas FPolicy ativadas usando o comando apropriado:
+
[cols="35,65"]
|===


| Se você quiser exibir informações sobre políticas ativadas... | Digite o comando... 


 a| 
No cluster
 a| 
`vserver fpolicy show-enabled`



 a| 
Em uma SVM especificada
 a| 
`vserver fpolicy show-enabled -vserver vserver_name`



 a| 
Com o nome da política especificado
 a| 
`vserver fpolicy show-enabled -policy-name policy_name`



 a| 
Com o número de sequência especificado
 a| 
`vserver fpolicy show-enabled -priority integer`

|===


.Exemplo
O exemplo a seguir exibe as informações sobre as políticas FPolicy ativadas no cluster:

[listing]
----
cluster1::> vserver fpolicy show-enabled
Vserver                 Policy Name               Priority

----------------------- ------------------------- ----------
vs1.example.com         pol_native                native
vs1.example.com         pol_native2               native
vs1.example.com         pol1                      2
vs1.example.com         pol2                      4
----