---
permalink: nas-audit/display-fpolicy-policy-status-task.html 
sidebar: sidebar 
keywords: display, information, fpolicy, policy status 
summary: 'Você pode exibir informações sobre o status das políticas FPolicy para determinar se uma política está ativada, qual mecanismo externo ele está configurado para usar, qual é o número de sequência para a política e a qual máquina virtual de armazenamento (SVM) a política FPolicy está associada.' 
---
= Exibir informações sobre o status da política ONTAP FPolicy
:allow-uri-read: 


[role="lead"]
Você pode exibir informações sobre o status das políticas FPolicy para determinar se uma política está ativada, qual mecanismo externo ele está configurado para usar, qual é o número de sequência para a política e a qual máquina virtual de armazenamento (SVM) a política FPolicy está associada.

.Sobre esta tarefa
Se você não especificar nenhum parâmetro, o comando exibirá as seguintes informações:

* Nome do SVM
* Nome da política
* Número de sequência da política
* Estado da política


Além de exibir informações sobre o status da política para políticas FPolicy configuradas no cluster ou em um SVM específico, você pode usar parâmetros de comando para filtrar a saída do comando por outros critérios.

Você pode especificar o `-instance` parâmetro para exibir informações detalhadas sobre as políticas listadas. Alternativamente, você pode usar o `-fields` parâmetro para exibir apenas os campos indicados na saída do comando ou `-fields ?` para determinar quais campos você pode usar.

.Passo
. Exiba informações filtradas sobre o status da política FPolicy usando o comando apropriado:
+
[cols="35,65"]
|===


| Se você quiser exibir informações de status sobre políticas... | Digite o comando... 


 a| 
No cluster
 a| 
`vserver fpolicy show`



 a| 
Que têm o status especificado
 a| 
`vserver fpolicy show -status {on|off}`



 a| 
Em uma SVM especificada
 a| 
`vserver fpolicy show -vserver vserver_name`



 a| 
Com o nome da política especificado
 a| 
`vserver fpolicy show -policy-name policy_name`



 a| 
Que utilizam o motor externo especificado
 a| 
`vserver fpolicy show -engine engine_name`

|===


.Exemplo
O exemplo a seguir exibe as informações sobre políticas FPolicy no cluster:

[listing]
----

cluster1::> vserver fpolicy show
                                        Sequence
Vserver             Policy Name           Number  Status      Engine
------------------- ------------------- --------  ---------   ---------
FPolicy             cserver_policy      -         off         eng1
vs1.example.com     v1p1                -         off         eng2
vs1.example.com     v1p2                -         off         native
vs1.example.com     v1p3                -         off         native
vs1.example.com     cserver_policy      -         off         eng1
vs2.example.com     v1p1                3         on          native
vs2.example.com     v1p2                1         on          eng3
vs2.example.com     cserver_policy      2         on          eng1
----