---
permalink: nas-audit/enable-disable-fpolicy-policies-task.html 
sidebar: sidebar 
keywords: enable, disable, fpolicy policies 
summary: Você pode ativar as políticas FPolicy após a conclusão da configuração. A ativação da política define sua prioridade e inicia o monitoramento de acesso a arquivos para a política. Você pode desativar as políticas FPolicy se quiser interromper o monitoramento de acesso a arquivos para a política. 
---
= Habilitar ou desabilitar políticas ONTAP FPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode ativar as políticas FPolicy após a conclusão da configuração. A ativação da política define sua prioridade e inicia o monitoramento de acesso a arquivos para a política. Você pode desativar as políticas FPolicy se quiser interromper o monitoramento de acesso a arquivos para a política.

.Antes de começar
Antes de ativar as políticas FPolicy, a configuração FPolicy deve ser concluída.

.Sobre esta tarefa
* A prioridade é usada quando várias políticas são habilitadas na máquina virtual de storage (SVM) e mais de uma política é subscrita ao mesmo evento de acesso a arquivos.
* As políticas que usam a configuração nativa do mecanismo têm uma prioridade maior do que as políticas para qualquer outro mecanismo, independentemente do número de sequência atribuído a elas ao ativar a política.
* Se pretender alterar a prioridade de uma política FPolicy, tem de desativar a política e, em seguida, reactivá-la utilizando o novo número de sequência.


.Passo
. Execute a ação apropriada:
+
[cols="35,65"]
|===


| Se você quiser... | Digite o seguinte comando... 


 a| 
Ativar uma política FPolicy
 a| 
`vserver fpolicy enable -vserver-name vserver_name -policy-name policy_name -sequence-number integer`



 a| 
Desativar uma política FPolicy
 a| 
`vserver fpolicy disable -vserver-name vserver_name -policy-name policy_name`

|===

