---
permalink: nas-audit/enable-disable-auditing-svms-task.html 
sidebar: sidebar 
keywords: enable, disable, audit, svms 
summary: 'Você pode ativar ou desativar a auditoria em máquinas virtuais de armazenamento (SVMs). Talvez você queira interromper temporariamente a auditoria de arquivos e diretórios desativando a auditoria. Você pode ativar a auditoria a qualquer momento (se houver uma configuração de auditoria).' 
---
= Ativar e desativar a auditoria em SVMs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode ativar ou desativar a auditoria em máquinas virtuais de armazenamento (SVMs). Talvez você queira interromper temporariamente a auditoria de arquivos e diretórios desativando a auditoria. Você pode ativar a auditoria a qualquer momento (se houver uma configuração de auditoria).

.O que você vai precisar
Antes de habilitar a auditoria na SVM, a configuração de auditoria da SVM já deve existir.

link:create-auditing-config-task.html["Crie a configuração de auditoria"]

.Sobre esta tarefa
A desativação da auditoria não exclui a configuração de auditoria.

.Passos
. Execute o comando apropriado:
+
[cols="35,65"]
|===


| Se você quer que a auditoria seja... | Digite o comando... 


 a| 
Ativado
 a| 
`vserver audit enable -vserver vserver_name`



 a| 
Desativado
 a| 
`vserver audit disable -vserver vserver_name`

|===
. Verifique se a auditoria está no estado desejado:
+
`vserver audit show -vserver vserver_name`



.Exemplos
O exemplo a seguir permite a auditoria do SVM VS1:

[listing]
----
cluster1::> vserver audit enable -vserver vs1

cluster1::> vserver audit show -vserver vs1

                             Vserver: vs1
                      Auditing state: true
                Log Destination Path: /audit_log
       Categories of Events to Audit: file-ops, cifs-logon-logoff
                          Log Format: evtx
                 Log File Size Limit: 100MB
        Log Rotation Schedule: Month: -
  Log Rotation Schedule: Day of Week: -
          Log Rotation Schedule: Day: -
         Log Rotation Schedule: Hour: -
       Log Rotation Schedule: Minute: -
                  Rotation Schedules: -
            Log Files Rotation Limit: 10
----
O exemplo a seguir desativa a auditoria para SVM VS1:

[listing]
----
cluster1::> vserver audit disable -vserver vs1

                             Vserver: vs1
                      Auditing state: false
                Log Destination Path: /audit_log
       Categories of Events to Audit: file-ops, cifs-logon-logoff
                          Log Format: evtx
                 Log File Size Limit: 100MB
        Log Rotation Schedule: Month: -
  Log Rotation Schedule: Day of Week: -
          Log Rotation Schedule: Day: -
         Log Rotation Schedule: Hour: -
       Log Rotation Schedule: Minute: -
                  Rotation Schedules: -
            Log Files Rotation Limit: 10
----