---
permalink: nas-audit/enable-audit-svm-task.html 
sidebar: sidebar 
keywords: enable, audit, svm 
summary: Depois de concluir a configuração de auditoria, você deve habilitar a auditoria na máquina virtual de armazenamento. 
---
= Habilite a auditoria no SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de concluir a configuração de auditoria, será necessário habilitar a auditoria na máquina virtual de storage (SVM).

.Antes de começar
A configuração de auditoria da SVM já deve existir.

.Sobre esta tarefa
Quando uma configuração de descarte de ID de recuperação de desastres da SVM é iniciada pela primeira vez (após a inicialização do SnapMirror ser concluída) e o SVM tiver uma configuração de auditoria, o ONTAP desativa automaticamente a configuração de auditoria. A auditoria é desativada no SVM somente leitura para evitar que os volumes de preparo sejam preenchidos. Você pode ativar a auditoria somente depois que a relação do SnapMirror for interrompida e o SVM for leitura-gravação.

.Passos
. Habilite a auditoria no SVM:
+
`vserver audit enable -vserver vserver_name`

+
`vserver audit enable -vserver vs1`



.Informações relacionadas
* link:create-auditing-config-task.html["Crie a configuração de auditoria"]
* link:verify-auditing-config-task.html["Verifique a configuração de auditoria"]

