---
permalink: nas-audit/file-directory-access-events-audited-reference.html 
sidebar: sidebar 
keywords: nfs file, directory access events, audited 
summary: O ONTAP pode auditar determinados eventos de acesso a arquivos NFS e diretórios. Saber quais eventos de acesso podem ser auditados é útil ao interpretar os resultados dos logs de eventos de auditoria convertidos. 
---
= Eventos de acesso a arquivos e diretórios NFS que podem ser auditados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O ONTAP pode auditar determinados eventos de acesso a arquivos NFS e diretórios. Saber quais eventos de acesso podem ser auditados é útil ao interpretar os resultados dos logs de eventos de auditoria convertidos.

Você pode auditar os seguintes eventos de acesso a arquivos NFS e diretórios:

* LEIA
* ABRIR
* FECHAR
* READDIR
* ESCREVA
* SETATTR
* CRIAR
* LINK
* OPENATTR
* RETIRE
* GETATTR
* VERIFIQUE
* NVERIFY
* MUDAR O NOME


Para auditar de forma confiável os eventos DE RENOMEAÇÃO do NFS, você deve definir ACEs de auditoria em diretórios em vez de arquivos porque as permissões de arquivo não são verificadas para uma operação DE RENOMEAÇÃO se as permissões de diretório forem suficientes.
