---
permalink: nas-audit/fpolicy-scope-config-native-engine-concept.html 
sidebar: sidebar 
keywords: requirement, fpolicy, scope, configurations, policy, native engine 
summary: Se você configurar a política FPolicy para usar o mecanismo nativo, há um requisito específico para como definir o escopo FPolicy configurado para a política. 
---
= Requisito para configurações de escopo ONTAP FPolicy se a política FPolicy usar o mecanismo nativo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você configurar a política FPolicy para usar o mecanismo nativo, há um requisito específico para como definir o escopo FPolicy configurado para a política.

O escopo FPolicy define os limites nos quais a política FPolicy se aplica, por exemplo, se a FPolicy se aplica a volumes ou compartilhamentos especificados. Existem vários parâmetros que restringem ainda mais o escopo ao qual a política FPolicy se aplica. Um desses parâmetros, `-is-file-extension-check-on-directories-enabled`, especifica se deve verificar as extensões de arquivo nos diretórios. O valor padrão é `false`, o que significa que as extensões de arquivo nos diretórios não estão marcadas.

Quando uma diretiva FPolicy que usa o mecanismo nativo está ativada em um compartilhamento ou volume e o `-is-file-extension-check-on-directories-enabled` parâmetro é definido como `false` para o escopo da política, o acesso ao diretório é negado. Com essa configuração, como as extensões de arquivo não são verificadas para diretórios, qualquer operação de diretório é negada se ela estiver sob o escopo da política.

Para garantir que o acesso ao diretório seja bem-sucedido ao usar o mecanismo nativo, você deve definir o `-is-file-extension-check-on-directories-enabled parameter` para `true` ao criar o escopo.

Com este parâmetro definido como `true`, as verificações de extensão acontecem para operações de diretório e a decisão de permitir ou negar acesso é tomada com base nas extensões incluídas ou excluídas na configuração do escopo FPolicy.
