---
permalink: nas-audit/fpolicy-scope-worksheet-reference.html 
sidebar: sidebar 
keywords: complete, fpolicy, scope, worksheet 
summary: Você pode usar essa Planilha para Registrar os valores necessários durante o processo de configuração do escopo do FPolicy. Se um valor de parâmetro for necessário, você precisará determinar qual valor usar para esses parâmetros antes de configurar o escopo FPolicy. 
---
= Planilhas completas de escopo do ONTAP FPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar essa Planilha para Registrar os valores necessários durante o processo de configuração do escopo do FPolicy. Se um valor de parâmetro for necessário, você precisará determinar qual valor usar para esses parâmetros antes de configurar o escopo FPolicy.

Você deve Registrar se deseja incluir cada configuração de parâmetro na configuração do escopo do FPolicy e, em seguida, Registrar o valor dos parâmetros que deseja incluir.

[cols="40,20,20,20"]
|===


| Tipo de informação | Obrigatório | Incluir | Seus valores 


 a| 
Nome da máquina virtual de storage (SVM)
 a| 
Sim
 a| 
Sim
 a| 



 a| 
Nome da política
 a| 
Sim
 a| 
Sim
 a| 



 a| 
Compartilhamentos a incluir
 a| 
Não
 a| 
 a| 



 a| 
Compartilhamentos a excluir
 a| 
Não
 a| 
 a| 



 a| 
Volumes a incluir
 a| 
Não
 a| 
 a| 



 a| 
Volumes a excluir
 a| 
Não
 a| 
 a| 



 a| 
Políticas de exportação a incluir
 a| 
Não
 a| 
 a| 



 a| 
Exportar políticas para excluir
 a| 
Não
 a| 
 a| 



 a| 
Extensões de arquivo a incluir
 a| 
Não
 a| 
 a| 



 a| 
Extensão do ficheiro a excluir
 a| 
Não
 a| 
 a| 



 a| 
A verificação de extensão de arquivo no diretório está ativada?
 a| 
Não
 a| 
 a| 

|===