---
permalink: nas-audit/fpolicy-services-svm-namespaces-concept.html 
sidebar: sidebar 
keywords: fpolicy, services, work, svm, namespaces 
summary: 'O ONTAP fornece um namespace unificado de máquina virtual de storage (SVM). Os volumes no cluster são Unidos por junções para fornecer um único sistema de arquivos lógico. O servidor FPolicy está ciente da topologia do namespace e fornece serviços FPolicy em todo o namespace.' 
---
= Como os serviços do FPolicy funcionam nos namespaces do SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O ONTAP fornece um namespace unificado de máquina virtual de storage (SVM). Os volumes no cluster são Unidos por junções para fornecer um único sistema de arquivos lógico. O servidor FPolicy está ciente da topologia do namespace e fornece serviços FPolicy em todo o namespace.

O namespace é específico e contido no SVM. Portanto, você pode ver o namespace somente no contexto SVM. Os namespaces têm as seguintes caraterísticas:

* Existe um namespace único em cada SVM, com a raiz do namespace sendo o volume raiz, representado no namespace como barra (/).
* Todos os outros volumes têm pontos de junção abaixo da raiz (/).
* Junções de volume são transparentes para os clientes.
* Uma única exportação de NFS pode fornecer acesso ao namespace completo. Caso contrário, as políticas de exportação podem exportar volumes específicos.
* Compartilhamentos SMB podem ser criados no volume ou em qtrees dentro do volume, ou em qualquer diretório dentro do namespace.
* A arquitetura do namespace é flexível.
+
Exemplos de arquiteturas de namespace típicas são os seguintes:

+
** Um namespace com um único ramo fora da raiz
** Um namespace com vários ramificações fora da raiz
** Um namespace com vários volumes não ramificados fora da raiz



