---
permalink: nas-audit/fpolicy-external-engine-config-worksheet-reference.html 
sidebar: sidebar 
keywords: complete, fpolicy, external engine, configuration, worksheet 
summary: Você pode usar esta Planilha para Registrar os valores que você precisa durante o processo de configuração do mecanismo externo FPolicy. Se um valor de parâmetro for necessário, você precisará determinar qual valor usar para esses parâmetros antes de configurar o mecanismo externo. 
---
= Preencha a folha de cálculo de configuração do motor externo FPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar esta Planilha para Registrar os valores que você precisa durante o processo de configuração do mecanismo externo FPolicy. Se um valor de parâmetro for necessário, você precisará determinar qual valor usar para esses parâmetros antes de configurar o mecanismo externo.



== Informações para uma configuração externa básica do motor

Você deve Registrar se deseja incluir cada configuração de parâmetro na configuração do mecanismo externo e, em seguida, Registrar o valor para os parâmetros que deseja incluir.

[cols="40,20,20,20"]
|===


| Tipo de informação | Obrigatório | Incluir | Seus valores 


 a| 
Nome da máquina virtual de storage (SVM)
 a| 
Sim
 a| 
Sim
 a| 



 a| 
Nome do motor
 a| 
Sim
 a| 
Sim
 a| 



 a| 
Servidores FPolicy primários
 a| 
Sim
 a| 
Sim
 a| 



 a| 
Número da porta
 a| 
Sim
 a| 
Sim
 a| 



 a| 
Servidores FPolicy secundários
 a| 
Não
 a| 
 a| 



 a| 
Tipo de motor externo
 a| 
Não
 a| 
 a| 



 a| 
Opção SSL para comunicação com servidor FPolicy externo
 a| 
Sim
 a| 
Sim
 a| 



 a| 
Certificado FQDN ou nome comum personalizado
 a| 
Não
 a| 
 a| 



 a| 
Número de série do certificado
 a| 
Não
 a| 
 a| 



 a| 
Autoridade de certificação
 a| 
Não
 a| 
 a| 

|===


== Informações para parâmetros externos avançados do motor

Para configurar um motor externo com parâmetros avançados, tem de introduzir o comando de configuração no modo de privilégio avançado.

[cols="40,20,20,20"]
|===


| Tipo de informação | Obrigatório | Incluir | Seus valores 


 a| 
Tempo limite para cancelar uma solicitação
 a| 
Não
 a| 
 a| 



 a| 
Tempo limite para abortar uma solicitação
 a| 
Não
 a| 
 a| 



 a| 
Intervalo para envio de solicitações de status
 a| 
Não
 a| 
 a| 



 a| 
Máximo de solicitações pendentes no servidor FPolicy
 a| 
Não
 a| 
 a| 



 a| 
Tempo limite para desconetar um servidor FPolicy não responsivo
 a| 
Não
 a| 
 a| 



 a| 
Intervalo para enviar mensagens keep-alive para o servidor FPolicy
 a| 
Não
 a| 
 a| 



 a| 
Máximo de tentativas de reconexão
 a| 
Não
 a| 
 a| 



 a| 
Receber tamanho do buffer
 a| 
Não
 a| 
 a| 



 a| 
Enviar tamanho do buffer
 a| 
Não
 a| 
 a| 



 a| 
Tempo limite para purgar um Session ID durante a reconexão
 a| 
Não
 a| 
 a| 

|===