---
permalink: nas-audit/index.html 
sidebar: sidebar 
keywords: file, access, auditing, audit, smb, cifs, nfs, fpolicy, udit, nas, events, svms 
summary: Você pode usar os recursos de auditoria de acesso a arquivos disponíveis para os protocolos SMB e NFS com o ONTAP, como auditoria nativa e gerenciamento de políticas de arquivos usando FPolicy. 
---
= Auditoria de SMB e NFS e rastreamento de segurança
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar os recursos de auditoria de acesso a arquivos disponíveis para os protocolos SMB e NFS com o ONTAP, como auditoria nativa e gerenciamento de políticas de arquivos usando FPolicy.

Você deve projetar e implementar a auditoria de eventos de acesso a arquivos SMB e NFS nas seguintes circunstâncias:

* O acesso básico a arquivos de protocolo SMB e NFS foi configurado.
* Você deseja criar e manter uma configuração de auditoria usando um dos seguintes métodos:
+
** Funcionalidade ONTAP nativa
** Servidores FPolicy externos






== Auditar eventos nas em SVMs

A auditoria de eventos nas é uma medida de segurança que permite controlar e Registrar determinados eventos SMB e NFS em máquinas virtuais de storage (SVMs). Isso ajuda você a rastrear possíveis problemas de segurança e fornece evidências de quaisquer violações de segurança. Você também pode organizar e auditar políticas de acesso central do ative Directory para ver qual seria o resultado da implementação delas.



=== Eventos SMB

Você pode auditar os seguintes eventos:

* Eventos de acesso a arquivos SMB e pastas
+
Você pode auditar eventos de acesso a arquivos SMB e pastas em objetos armazenados em volumes FlexVol pertencentes aos SVMs habilitados para auditoria.

* Eventos de logon e logoff SMB
+
Você pode auditar eventos de logon e logoff SMB para servidores SMB em SVMs.

* Eventos de preparação da política de acesso central
+
Você pode auditar o acesso efetivo de objetos em servidores SMB usando permissões aplicadas por meio de políticas de acesso centrais propostas. A auditoria por meio do preparo de políticas de acesso central permite que você veja quais são os efeitos das políticas de acesso centrais antes que elas sejam implantadas.

+
A auditoria do preparo de políticas de acesso central é configurada usando GPOs do active Directory. No entanto, a configuração de auditoria SVM deve ser configurada para auditar eventos de preparação de políticas de acesso central.

+
Embora você possa ativar o estadiamento da diretiva de acesso central na configuração de auditoria sem ativar o Controle de Acesso Dinâmico no servidor SMB, os eventos de estadiamento da política de acesso central são gerados somente se o Controle de Acesso Dinâmico estiver ativado. O Dynamic Access Control é ativado através de uma opção de servidor SMB. Ele não está habilitado por padrão.





=== Eventos NFS

Você pode auditar eventos de arquivo e diretório utilizando NFSv4 ACL em objetos armazenados em SVMs.
