---
permalink: nas-audit/manual-rotate-audit-event-logs-task.html 
sidebar: sidebar 
keywords: manually, rotate, audit event logs 
summary: 'Antes de poder visualizar os registos de eventos de auditoria, os registos têm de ser convertidos para formatos legíveis pelo utilizador. Se você quiser exibir os logs de eventos de uma máquina virtual de storage específica (SVM) antes que o ONTAP gire automaticamente o log, você pode girar manualmente os logs de eventos de auditoria em uma SVM.' 
---
= Rode manualmente os registos de eventos de auditoria
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de poder visualizar os registos de eventos de auditoria, os registos têm de ser convertidos para formatos legíveis pelo utilizador. Se você quiser exibir os logs de eventos de uma máquina virtual de storage específica (SVM) antes que o ONTAP gire automaticamente o log, você pode girar manualmente os logs de eventos de auditoria em uma SVM.

.Passo
. Gire os logs de eventos de auditoria usando o `vserver audit rotate-log` comando.
+
`vserver audit rotate-log -vserver vs1`

+
O log de eventos de auditoria é salvo no diretório de log de eventos de auditoria SVM com o formato especificado pela configuração de auditoria (`XML`ou `EVTX`) e pode ser visualizado usando o aplicativo apropriado.


