---
permalink: nas-audit/persistent-stores.html 
sidebar: sidebar 
keywords: overview, persistent store, fpolicy 
summary: A partir do ONTAP 9.14,1, o FPolicy permite configurar um armazenamento persistente para capturar eventos de acesso a arquivos para políticas assíncronas não obrigatórias no SVM. Armazenamentos persistentes podem ajudar a desacoplar o processamento de e/S do cliente do processamento de notificação FPolicy para reduzir a latência do cliente. Configurações obrigatórias síncronas e assíncronas não são suportadas. 
---
= Armazenamentos persistentes de FPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Armazenamentos persistentes podem ajudar a desacoplar o processamento de e/S do cliente do processamento de notificações FPolicy para reduzir a latência do cliente. A partir do ONTAP 9.14,1, é possível configurar um armazenamento persistente FPolicy para capturar eventos de acesso a arquivos para políticas assíncronas não obrigatórias no SVM. Configurações síncronas (obrigatórias ou não obrigatórias) e assíncronas obrigatórias não são suportadas.

Esta funcionalidade só está disponível no modo externo FPolicy. A aplicação de parceiro que você usa precisa para dar suporte a esse recurso. Você deve trabalhar com seu parceiro para garantir que essa configuração do FPolicy seja suportada.

A partir do ONTAP 9.15,1, a configuração de armazenamento persistente do FPolicy é simplificada. O `persistent-store create` comando automatiza a criação de volume para o SVM e configura o volume com as práticas recomendadas de armazenamento persistente.

Para obter mais informações sobre as práticas recomendadas de armazenamento persistente, link:requirements-best-practices-fpolicy-concept.html["Requisitos, considerações e práticas recomendadas para configurar o FPolicy"]consulte .

Para obter informações sobre como adicionar armazenamentos persistentes, link:create-persistent-stores.html["Crie armazenamentos persistentes"]consulte .
