---
permalink: nas-audit/process-when-reverting-concept.html 
sidebar: sidebar 
keywords: process, revert, cluster 
summary: 'Se você pretende reverter o cluster, deve estar ciente do processo de reversão que o ONTAP segue quando houver máquinas virtuais de storage (SVMs) habilitadas para auditoria no cluster. Você deve tomar certas ações antes de reverter.' 
---
= Entenda as implicações de reverter o cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você pretende reverter o cluster, deve estar ciente do processo de reversão que o ONTAP segue quando houver máquinas virtuais de storage (SVMs) habilitadas para auditoria no cluster. Você deve tomar certas ações antes de reverter.



== Revertendo para uma versão do ONTAP que não suporte a auditoria de eventos de logon e logoff SMB e eventos de preparação de políticas de acesso central

O suporte para auditoria de eventos de logon e logoff SMB e para eventos de preparação de políticas de acesso central começa com o Clustered Data ONTAP 8.3. Se você estiver revertendo para uma versão do ONTAP que não ofereça suporte a esses tipos de eventos e tiver configurações de auditoria que monitorem esses tipos de eventos, será necessário alterar a configuração de auditoria desses SVMs habilitados para auditoria antes de reverter. Você deve modificar a configuração para que apenas eventos de arquivo operacional sejam auditados.
