---
permalink: nas-audit/supported-file-operation-filter-fpolicy-nfsv4-concept.html 
sidebar: sidebar 
keywords: ontap 9, supported file operation, filter combinations, fpolicy, monitor, nfsv4 
summary: Ao configurar seu evento FPolicy, você precisa estar ciente de que apenas certas combinações de operações de arquivo e filtros são suportadas para monitorar operações de acesso a arquivos NFSv4. 
---
= Combinações de operação de arquivo e filtro suportadas que o ONTAP FPolicy monitora para NFSv4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao configurar seu evento FPolicy, você precisa estar ciente de que apenas certas combinações de operações de arquivo e filtros são suportadas para monitorar operações de acesso a arquivos NFSv4.

A partir do ONTAP 9.15,1, o FPolicy suporta o protocolo NFSv4,1.

A lista de combinações de filtros e operação de arquivos compatíveis para monitoramento FPolicy de eventos de acesso a arquivos NFSv4 ou NFSv4,1 é fornecida na seguinte tabela:

[cols="30,70"]
|===


| Operações de arquivos compatíveis | Filtros suportados 


 a| 
fechar
 a| 
offline-bit, exclude-directory



 a| 
criar
 a| 
bit offline



 a| 
criar_dir
 a| 
Atualmente, nenhum filtro é suportado para esta operação de arquivo.



 a| 
eliminar
 a| 
bit offline



 a| 
delete_dir
 a| 
Atualmente, nenhum filtro é suportado para esta operação de arquivo.



 a| 
getattr
 a| 
offline-bit, exclude-directory



 a| 
link
 a| 
bit offline



 a| 
pesquisa
 a| 
offline-bit, exclude-directory



 a| 
abrir
 a| 
offline-bit, exclude-directory



 a| 
leia
 a| 
offline-bit, primeira leitura



 a| 
escreva
 a| 
offline-bit, primeira gravação, write-with-size-change



 a| 
mudar o nome
 a| 
bit offline



 a| 
rename_dir
 a| 
Atualmente, nenhum filtro é suportado para esta operação de arquivo.



 a| 
ajuste
 a| 
offline-bit, setattr_with_owner_change, setattr_with_group_change, setattr_with_mode_change, setattr_with_sacl_change, setattr_with_dacl_change, setattr_with_modify_time_change, setattr_with_access_time_change, setattr_time_change, setattr_change, setattr_time_change, setattr_change



 a| 
link simbólico
 a| 
bit offline

|===
A partir do ONTAP 9.13,1, os usuários podem receber notificações para operações de arquivos com falha devido à falta de permissões. A lista de combinações de filtro e operação de arquivo negado de acesso com suporte para monitoramento FPolicy de eventos de acesso a arquivos NFSv4 ou NFSv4,1 é fornecida na tabela a seguir:

[cols="30,70"]
|===


| Acesso suportado operação de arquivo negado | Filtros suportados 


 a| 
acesso
 a| 
NA



 a| 
criar
 a| 
NA



 a| 
criar_dir
 a| 
NA



 a| 
eliminar
 a| 
NA



 a| 
delete_dir
 a| 
NA



 a| 
link
 a| 
NA



 a| 
abrir
 a| 
NA



 a| 
leia
 a| 
NA



 a| 
mudar o nome
 a| 
NA



 a| 
rename_dir
 a| 
NA



 a| 
ajuste
 a| 
NA



 a| 
escreva
 a| 
NA

|===