---
permalink: san-config/configure-fc-adapters-initiator-mode-task.html 
sidebar: sidebar 
keywords: configure, fc adapters, initiator mode 
summary: 'Você pode configurar portas FC individuais de adaptadores integrados e determinadas placas de adaptador FC para o modo iniciador. O modo iniciador é usado para conetar as portas a unidades de fita, bibliotecas de fita ou armazenamento de terceiros com virtualização FlexArray ou importação de LUN estrangeiro (FLI).' 
---
= Configurar adaptadores FC para o modo iniciador
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar portas FC individuais de adaptadores integrados e determinadas placas de adaptador FC para o modo iniciador. O modo iniciador é usado para conetar as portas a unidades de fita, bibliotecas de fita ou armazenamento de terceiros com virtualização FlexArray ou importação de LUN estrangeiro (FLI).

.O que você vai precisar
* Os LIFs no adaptador devem ser removidos de quaisquer conjuntos de portas dos quais sejam membros.
* Todos os LIF de todas as máquinas virtuais de armazenamento (SVM) que usam a porta física a ser modificada devem ser migrados ou destruídos antes de alterar a personalidade da porta física de destino para iniciador.


.Sobre esta tarefa
Cada porta FC integrada pode ser configurada individualmente como iniciador ou destino. As portas em certos adaptadores FC também podem ser configuradas individualmente como uma porta de destino ou uma porta de iniciador, assim como as portas FC integradas. Uma lista de adaptadores que podem ser configurados para o modo de destino está disponível no https://hwu.netapp.com["NetApp Hardware Universe"^].

[NOTE]
====
O NVMe/FC oferece suporte ao modo iniciador.

====
.Passos
. Remova todas as LIFs do adaptador:
+
`network interface delete -vserver _SVM_name_ -lif _lif_name_,_lif_name_`

. Coloque o adaptador offline:
+
`network fcp adapter modify -node _node_name_ -adapter _adapter_port_ -status-admin down`

+
Se o adaptador não ficar offline, você também pode remover o cabo da porta apropriada do adaptador no sistema.

. Altere o adaptador de destino para iniciador:
+
`system hardware unified-connect modify -t initiator _adapter_port_`

. Reinicie o nó que hospeda o adaptador que você alterou.
. Verifique se as portas FC estão configuradas no estado correto para sua configuração:
+
`system hardware unified-connect show`

. Coloque o adaptador novamente online:
+
`node run -node _node_name_ storage enable adapter _adapter_port_`


