---
permalink: san-config/configure-fc-adapters-initiator-target.html 
sidebar: sidebar 
keywords: configure, fc adapters, initiator mode, target mode, FC-NVMe, FC adapter speed 
summary: Os adaptadores FC integrados e algumas placas de adaptador de expansão FC podem ser configurados como iniciadores ou portas de destino. Outros adaptadores de expansão FC são configurados como iniciadores ou destinos na fábrica e não podem ser alterados. 
---
= Configurar as portas do adaptador ONTAP FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os adaptadores FC integrados e algumas placas de adaptador de expansão FC podem ser configurados individualmente como iniciadores ou portas de destino. Outros adaptadores de expansão FC são configurados como iniciadores ou destinos na fábrica e não podem ser alterados. Portas FC adicionais também estão disponíveis por meio de placas UTA2 compatíveis configuradas com adaptadores FC SFP.

As portas do iniciador podem ser usadas para se conectar diretamente aos compartimentos de disco back-end e, possivelmente, a arrays de storage estranhos. As portas de destino podem ser usadas para se conectar somente aos switches FC.

O número de portas integradas e portas CNA/UTA2 configuradas para FC varia de acordo com o modelo da controladora. Os adaptadores de expansão de destino suportados também variam dependendo do modelo do controlador. Consulte link:https://hwu.netapp.com["NetApp Hardware Universe"^] para obter uma lista completa de portas FC integradas e adaptadores de expansão de destino compatíveis para o modelo de controladora.



== Configurar adaptadores FC para o modo iniciador

O modo iniciador é usado para conetar as portas a unidades de fita, bibliotecas de fita ou armazenamento de terceiros com virtualização FlexArray ou importação de LUN estrangeiro (FLI).

.Antes de começar
* Os LIFs no adaptador devem ser removidos de quaisquer conjuntos de portas dos quais sejam membros.
* Todos os LIF de todas as máquinas virtuais de armazenamento (SVM) que usam a porta física a ser modificada devem ser migrados ou destruídos antes de alterar a personalidade da porta física de destino para iniciador.


[NOTE]
====
O NVMe/FC oferece suporte ao modo iniciador.

====
.Passos
. Remova todas as LIFs do adaptador:
+
[source, cli]
----
network interface delete -vserver _SVM_name_ -lif _lif_name_,_lif_name_
----
. Coloque o adaptador offline:
+
[source, cli]
----
network fcp adapter modify -node _node_name_ -adapter _adapter_port_ -status-admin down
----
+
Se o adaptador não ficar offline, você também pode remover o cabo da porta apropriada do adaptador no sistema.

. Altere o adaptador de destino para iniciador:
+
[source, cli]
----
system hardware unified-connect modify -t initiator _adapter_port_
----
. Reinicie o nó que hospeda o adaptador que você alterou.
. Verifique se as portas FC estão configuradas no estado correto para sua configuração:
+
[source, cli]
----
system hardware unified-connect show
----
. Coloque o adaptador novamente online:
+
[source, cli]
----
node run -node _node_name_ storage enable adapter _adapter_port_
----




== Configurar adaptadores FC para o modo de destino

O modo de destino é usado para conetar as portas aos iniciadores FC.

As mesmas etapas são usadas para configurar adaptadores FC para o protocolo FC e para o protocolo FC-NVMe. No entanto, apenas certos adaptadores FC são compatíveis com FC-NVMe. Consulte link:https://hwu.netapp.com["NetApp Hardware Universe"^] a para obter uma lista de adaptadores compatíveis com o protocolo FC-NVMe.

.Passos
. Coloque o adaptador offline:
+
[source, cli]
----
node run -node _node_name_ storage disable adapter _adapter_name_
----
+
Se o adaptador não ficar offline, você também pode remover o cabo da porta apropriada do adaptador no sistema.

. Altere o adaptador do iniciador para o destino:
+
[source, cli]
----
system node hardware unified-connect modify -t target -node _node_name_ adapter _adapter_name_
----
. Reinicie o nó que hospeda o adaptador que você alterou.
. Verifique se a porta de destino tem a configuração correta:
+
[source, cli]
----
network fcp adapter show -node _node_name_
----
. Coloque o adaptador online:
+
[source, cli]
----
network fcp adapter modify -node _node_name_ -adapter _adapter_port_ -state up
----




== Configurar a velocidade do adaptador FC

Você deve configurar a velocidade da porta de destino do adaptador para corresponder à velocidade do dispositivo ao qual ele se coneta, em vez de usar a negociação automática. Uma porta definida como negociação automática pode levar mais tempo para se reconetar após uma tomada de controle/giveback ou outra interrupção.

.Sobre esta tarefa
Como essa tarefa abrange todas as máquinas virtuais de armazenamento (SVMs) e todas as LIFs em um cluster, você deve usar os `-home-port` parâmetros e `-home-lif` para limitar o escopo dessa operação. Se você não usar esses parâmetros, a operação se aplica a todos os LIFs no cluster, o que pode não ser desejável.

.Antes de começar
Todos os LIFs que usam esse adaptador como porta inicial devem estar offline.

.Passos
. Tire todos os LIFs neste adaptador offline:
+
[source, cli]
----
network interface modify -vserver * -lif * { -home-node node1 -home-port 0c } -status-admin down
----
. Coloque o adaptador offline:
+
[source, cli]
----
network fcp adapter modify -node node1 -adapter 0c -state down
----
+
Se o adaptador não ficar offline, você também pode remover o cabo da porta apropriada do adaptador no sistema.

. Determine a velocidade máxima do adaptador de porta:
+
[source, cli]
----
fcp adapter show -instance
----
+
Não é possível modificar a velocidade do adaptador para além da velocidade máxima.

. Alterar a velocidade do adaptador:
+
[source, cli]
----
network fcp adapter modify -node node1 -adapter 0c -speed 16
----
. Coloque o adaptador online:
+
[source, cli]
----
network fcp adapter modify -node node1 -adapter 0c -state up
----
. Coloque todos os LIFs no adaptador online:
+
[source, cli]
----
network interface modify -vserver * -lif * { -home-node node1 -home-port 0c } -status-admin up
----

