---
permalink: san-config/fc-switch-config-limits-reference.html 
sidebar: sidebar 
keywords: fc, switch, configuration, limits 
summary: Os switches Fibre Channel têm limites máximos de configuração, incluindo o número de logins suportados por porta, grupo de portas, blade e switch. Os fornecedores de switch documentam seus limites suportados. 
---
= Limites de configuração para switches FC usados com sistemas ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os switches Fibre Channel têm limites máximos de configuração, incluindo o número de logins suportados por porta, grupo de portas, blade e switch. Os fornecedores de switch documentam seus limites suportados.

Cada interface lógica FC (LIF) faz logon em uma porta de switch FC. O número total de logins de um único destino no nó é igual ao número de LIFs mais um login para a porta física subjacente. Não exceda os limites de configuração do fornecedor do switch para logins ou outros valores de configuração. Isso também é válido para os iniciadores que estão sendo usados no lado do host em ambientes virtualizados com NPIV habilitado. Não exceda os limites de configuração do fornecedor do switch para logins para o destino ou os iniciadores que estão sendo usados na solução.



== Limites do interrutor Brocade

Você pode encontrar os limites de configuração para switches Brocade nas _Diretrizes de escalabilidade Brocade_.



== Limites do switch dos sistemas Cisco

Você pode encontrar os limites de configuração para switches Cisco http://www.cisco.com/en/US/products/ps5989/products_installation_and_configuration_guides_list.html["Limites de configuração do Cisco"^] no guia para sua versão do software de switch Cisco.
