---
permalink: san-config/fc-target-port-supported-speeds-reference.html 
sidebar: sidebar 
keywords: fc, target, port, supported, speeds 
summary: As portas de destino FC podem ser configuradas para serem executadas em diferentes velocidades. Você deve definir a velocidade da porta de destino para corresponder à velocidade do dispositivo ao qual ela se coneta. Todas as portas de destino usadas por um determinado host devem ser definidas para a mesma velocidade. 
---
= Velocidades compatíveis com porta de destino FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As portas de destino FC podem ser configuradas para serem executadas em diferentes velocidades. Você deve definir a velocidade da porta de destino para corresponder à velocidade do dispositivo ao qual ela se coneta. Todas as portas de destino usadas por um determinado host devem ser definidas para a mesma velocidade.

As portas de destino FC podem ser usadas para configurações FC-NVMe da mesma maneira que são usadas nas configurações FC.

Você deve definir a velocidade da porta de destino para corresponder à velocidade do dispositivo ao qual ele se coneta em vez de usar a negociação automática. Uma porta definida como negociação automática pode levar mais tempo para se reconetar após uma tomada de controle/giveback ou outra interrupção.

É possível configurar portas integradas e adaptadores de expansão para serem executados nas seguintes velocidades. Cada porta do controlador e adaptador de expansão pode ser configurada individualmente para diferentes velocidades, conforme necessário.

[cols="4*"]
|===
| Portas de 4 GB | Portas de 8 GB | Portas de 16 GB | Portas de 32 GB 


 a| 
* 4 GB
* 2 GB
* 1 GB

 a| 
* 8 GB
* 4 GB
* 2 GB

 a| 
* 16 GB
* 8 GB
* 4 GB

 a| 
* 32 GB
* 16 GB
* 8 GB


|===
[NOTE]
====
As portas UTA2 podem usar um adaptador SFP de 8 GB para suportar velocidades de 8, 4 e 2 GB, se necessário.

====