---
permalink: san-config/fc-target-port-config-recommendations-concept.html 
sidebar: sidebar 
keywords: fc, target, port, configuration, recommendations 
summary: Para obter o melhor desempenho e a mais alta disponibilidade, use a configuração de porta de destino FC recomendada. 
---
= Determine as velocidades de porta FC suportadas para o seu sistema ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As portas de destino FC podem ser configuradas e usadas para o protocolo FC-NVMe exatamente da mesma forma que são configuradas e usadas para o protocolo FC.

Para obter o melhor desempenho e a maior disponibilidade, você deve usar a configuração de porta de destino recomendada em  https://hwu.netapp.com["NetApp Hardware Universe"^] para o seu sistema ONTAP específico.

Cada porta FC integrada e porta de adaptador de expansão pode ser configurada individualmente para diferentes velocidades, conforme suportado. As velocidades suportadas variam de acordo com seu sistema ONTAP e HBAs. Todas as portas de destino usadas por um determinado host devem ser configuradas com a mesma velocidade.

Como prática recomendada, você deve configurar uma velocidade comum em todas as suas portas de iniciador, switch e destino. Se as velocidades da porta e do iniciador forem diferentes e não for possível negociar uma velocidade comum, uma sessão não poderá ser estabelecida. Não é recomendável usar a negociação automática para estabelecer a velocidade da sua porta. A negociação automática pode tornar o estabelecimento da sessão e a reconexão mais lentos após uma interrupção.

As velocidades suportadas estão listadas no NetApp Hardware Universe em *Placas Adaptadoras Suportadas* para cada sistema ONTAP.

.Passos
. Acesse link:https://hwu.netapp.com["NetApp Hardware Universe"^].
. Selecione *Produtos*.
. Em *Plataformas*, selecione o seu tipo de sistema.
. Selecione o seu sistema específico e, em seguida, selecione a sua versão do ONTAP.
. Selecione *Mostrar resultados* e, em seguida, selecione *Placas adaptadoras compatíveis*.
+
As placas adaptadoras FC estão listadas na *Categoria* como "Block Access (Target)" e as velocidades suportadas estão listadas em *Supported Protocol(s)*.


