---
permalink: san-config/fc-target-port-config-recommendations-concept.html 
sidebar: sidebar 
keywords: fc, target, port, configuration, recommendations 
summary: Para obter o melhor desempenho e a mais alta disponibilidade, use a configuração de porta de destino FC recomendada. 
---
= Configurações e velocidades recomendadas de porta de destino FC para sistemas ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As portas de destino FC podem ser configuradas e usadas no protocolo FC-NVMe da mesma maneira que são configuradas e usadas no protocolo FC. O suporte ao protocolo FC-NVMe varia de acordo com a sua plataforma e a versão do ONTAP. Use o NetApp Hardware Universe para verificar o suporte.

Para obter o melhor desempenho e a mais alta disponibilidade, você deve usar a configuração de porta de destino recomendada listada na https://hwu.netapp.com["NetApp Hardware Universe"^] para sua plataforma específica.



== Configuração para portas de destino FC com ASICs compartilhados

As plataformas a seguir têm pares de portas com circuitos integrados (ASICs) específicos de aplicativos compartilhados. Se você usar um adaptador de expansão com essas plataformas, configure suas portas FC para que elas não usem o mesmo ASIC para conetividade.

[cols="3*"]
|===
| Controlador | Pares de portas com ASIC partilhado | Número de portas de destino: Portas recomendadas 


 a| 
* FAS8200
* AFF A300

 a| 
0g-0h
 a| 
1: 0g 2: 0g, 0h



 a| 
* FAS2720
* FAS2750
* AFF A220

 a| 
0c-0d 0e-0f
 a| 
1: 0c 2: 0c, 0e 3: 0c, 0e, 0d 4: 0c, 0e, 0d, 0f

|===


== Velocidades compatíveis com porta de destino FC

As portas de destino FC podem ser configuradas para serem executadas em diferentes velocidades. Todas as portas de destino usadas por um determinado host devem ser definidas para a mesma velocidade. Você deve definir a velocidade da porta de destino para corresponder à velocidade do dispositivo ao qual ela se coneta. Não use a negociação automática para a velocidade da porta. Uma porta definida como negociação automática pode levar mais tempo para se reconetar após uma tomada de controle/giveback ou outra interrupção.

É possível configurar portas integradas e adaptadores de expansão para serem executados nas seguintes velocidades. Cada porta do controlador e adaptador de expansão pode ser configurada individualmente para diferentes velocidades, conforme necessário.

[cols="4*"]
|===
| Portas de 4 GB | Portas de 8 GB | Portas de 16 GB | Portas de 32 GB 


 a| 
* 4 GB
* 2 GB
* 1 GB

 a| 
* 8 GB
* 4 GB
* 2 GB

 a| 
* 16 GB
* 8 GB
* 4 GB

 a| 
* 32 GB
* 16 GB
* 8 GB


|===
[NOTE]
====
As portas UTA2 podem usar um adaptador SFP de 8 GB para suportar velocidades de 8, 4 e 2 GB, se necessário.

====