---
permalink: san-config/fcoe-supported-hop-count-reference.html 
sidebar: sidebar 
keywords: fcoe, supported, hop, count 
summary: 'A contagem máxima de saltos Fibre Channel over Ethernet (FCoE) suportada entre um host e um sistema de armazenamento depende do fornecedor do switch e do suporte do sistema de armazenamento para configurações FCoE.' 
---
= Contagem de saltos com suporte para FCoE
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A contagem máxima de saltos Fibre Channel over Ethernet (FCoE) suportada entre um host e um sistema de armazenamento depende do fornecedor do switch e do suporte do sistema de armazenamento para configurações FCoE.

A contagem de saltos é definida como o número de switches no caminho entre o iniciador (host) e o destino (sistema de armazenamento). A documentação da Cisco Systems também se refere a esse valor como o _diâmetro da malha SAN_.

Para FCoE, você pode ter switches FCoE conetados a switches FC.

Para conexões FCoE de ponta a ponta, os switches FCoE devem estar executando uma versão de firmware que suporte ISLs (links inter-switch Ethernet).

A tabela a seguir lista o máximo de contagens de saltos suportadas:

[cols="2*"]
|===
| Fornecedor do interrutor | Contagem de saltos suportada 


 a| 
Brocade
 a| 
7 para FC

5 para FCoE



 a| 
Cisco
 a| 
7

Até 3 dos switches podem ser switches FCoE.

|===