---
permalink: san-config/fibre-channel-fcoe-zoning-concept.html 
sidebar: sidebar 
keywords: fibre, channel, fcoe zoning 
summary: Uma zona FC, FC-NVMe ou FCoE é um agrupamento lógico de uma ou mais portas em uma malha. Para que os dispositivos possam se ver, conetar, criar sessões entre si e se comunicar, ambas as portas precisam ter uma associação de zona comum. Recomenda-se um zoneamento de iniciador único. 
---
= Visão geral do zoneamento Fibre Channel e FCoE
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Uma zona FC, FC-NVMe ou FCoE é um agrupamento lógico de uma ou mais portas em uma malha. Para que os dispositivos possam se ver, conetar, criar sessões entre si e se comunicar, ambas as portas devem ser membros da mesma zona.

O zoneamento aumenta a segurança limitando o acesso e a conetividade a pontos finais que compartilham uma zona comum. As portas que não estão na mesma zona não podem se comunicar umas com as outras. Isso reduz ou elimina _crosstalk_ entre HBAs iniciador. Caso ocorram problemas de conetividade, o zoneamento ajuda a isolar problemas de um conjunto específico de portas, diminuindo assim o tempo de resolução.

O zoneamento reduz o número de caminhos disponíveis para uma porta específica e reduz o número de caminhos entre um host e o sistema de armazenamento. Por exemplo, algumas soluções de multipathing do sistema operacional host têm um limite no número de caminhos que podem gerenciar. O zoneamento pode reduzir o número de caminhos visíveis para o host para que os caminhos para o host não excedam o máximo permitido pelo sistema operacional do host.



== Zoneamento baseado em nome mundial

O zoneamento baseado no World Wide Name (WWN) especifica o WWN dos membros a serem incluídos na zona. Embora o zoneamento do Nome do nó Mundial (WWNN) seja possível com alguns fornecedores de switch, quando o zoneamento no ONTAP, você deve usar o zoneamento do Nome do Porto Mundial (WWPN).

WWPN zoneamento é necessário para definir adequadamente uma porta específica e usar NPIV de forma eficaz. Os switches FC devem ser zoneados usando as WWPNs das interfaces lógicas (LIFs) do destino, e não as WWPNs das portas físicas no nó. As WWPNs dos portos físicos começam com "50" e as WWPNs dos LIFs começam com ""20"".

WWPN zoneamento fornece flexibilidade porque o acesso não é determinado por onde o dispositivo está fisicamente conetado à malha. Você pode mover um cabo de uma porta para outra sem reconfigurar zonas.
