---
permalink: san-config/host-support-multipathing-concept.html 
sidebar: sidebar 
keywords: host, support, multipathing 
summary: 'O ONTAP sempre usa o Acesso lógico de Unidade assimétrica (ALUA) para caminhos FC e iSCSI. Use configurações de host compatíveis com ALUA para protocolos FC e iSCSI.' 
---
= Suporte de host para visão geral de multipathing
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O ONTAP sempre usa o Acesso lógico de Unidade assimétrica (ALUA) para caminhos FC e iSCSI. Use configurações de host compatíveis com ALUA para protocolos FC e iSCSI.

A partir do par de HA multipath ONTAP 9.5, o failover/giveback é compatível com configurações NVMe usando o acesso de namespace assíncrono (ANA). No ONTAP 9.4, o NVMe só oferece suporte a um caminho do host para o destino. O host de aplicações precisa gerenciar o failover de caminho para seu parceiro de alta disponibilidade (HA).

Para obter informações sobre quais configurações de host específicas suportam ALUA ou ANA, consulte https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^] e https://docs.netapp.com/us-en/ontap-sanhost/index.html["Configuração do host SAN ONTAP"] para o sistema operacional do seu host.
