---
permalink: san-config/individual-zones-reference.html 
sidebar: sidebar 
keywords: individual zones 
summary: Na configuração de zoneamento recomendada, há um iniciador de host por zona. A zona consiste na porta do iniciador do host e em um ou mais LIFs de destino nos nós de storage que estão fornecendo acesso aos LUNs até o número desejado de caminhos por destino. Isso significa que os hosts que acessam os mesmos nós não podem ver as portas uns dos outros, mas cada iniciador pode acessar qualquer nó. 
---
= Zonas individuais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Na configuração de zoneamento recomendada, há um iniciador de host por zona. A zona consiste na porta do iniciador do host e em um ou mais LIFs de destino nos nós de storage que estão fornecendo acesso aos LUNs até o número desejado de caminhos por destino. Isso significa que os hosts que acessam os mesmos nós não podem ver as portas uns dos outros, mas cada iniciador pode acessar qualquer nó.

Você deve adicionar todos os LIF da máquina virtual de armazenamento (SVM) na zona com o iniciador do host. Isso permite que você mova volumes ou LUNs sem editar suas zonas existentes ou criar novas zonas.

Para caminhos de Fibre Channel para nós que executam ONTAP, certifique-se de que os switches FC sejam zoneados usando WWPNs das interfaces lógicas de destino (LIFs), e não as WWPNs das portas físicas no nó. As WWPNs dos portos físicos começam com "50" e as WWPNs dos LIFs começam com ""20"".
