---
permalink: san-config/multipathing-software-required-concept.html 
sidebar: sidebar 
keywords: when, host, multipathing, software, required 
summary: 'Se houver mais de um caminho das interfaces lógicas (LIFs) da máquina virtual de storage (SVM) para a malha, é necessário software de multipathing. O software multipathing é necessário no host sempre que o host puder acessar um LUN por mais de um caminho.' 
---
= Quando o software de multipathing do host é necessário
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se houver mais de um caminho das interfaces lógicas (LIFs) da máquina virtual de storage (SVM) para a malha, é necessário software de multipathing. O software multipathing é necessário no host sempre que o host puder acessar um LUN por mais de um caminho.

O software multipathing apresenta um único disco para o sistema operacional para todos os caminhos para um LUN. Sem software multipathing, o sistema operacional poderia tratar cada caminho como um disco separado, o que pode levar à corrupção de dados.

Sua solução é considerada como tendo vários caminhos se você tiver qualquer um dos seguintes:

* Uma única porta de iniciador no host que é anexada a várias LIFs SAN no SVM
* Várias portas de iniciador anexando a um único LIF de SAN no SVM
* Várias portas de iniciador anexadas a várias LIFs SAN no SVM


O software multipathing é recomendado em configurações de HA. Além do mapa LUN seletivo, é recomendável usar o zoneamento de switch FC ou portsets para limitar os caminhos usados para acessar LUNs.

O software multipathing também é conhecido como software MPIO (multipath I/o).
