---
permalink: san-config/prevent-loss-connectivity-x1133a-r6-adapter-concept.html 
sidebar: sidebar 
keywords: how, prevent, loss, connectivity, using, x1133a-r6, adapter 
summary: Você pode evitar a perda de conetividade durante uma falha de porta configurando o sistema com caminhos redundantes para separar HBAs X1133A-R6. 
---
= Evite a perda de conetividade para um sistema ONTAP usando um adaptador X1133A-R6
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode evitar a perda de conetividade durante uma falha de porta configurando o sistema com caminhos redundantes para separar HBAs X1133A-R6.

O HBA X1133A-R6 é um adaptador FC de 4 portas e 16 GB que consiste em dois pares de 2 portas. O adaptador X1133A-R6 pode ser configurado como modo de destino ou modo de iniciador. Cada par de 2 portas é suportado por um único ASIC (por exemplo, porta 1 e porta 2 no ASIC 1 e porta 3 e porta 4 no ASIC 2). Ambas as portas em um único ASIC devem ser configuradas para operar no mesmo modo, seja no modo de destino ou no modo de iniciador. Se ocorrer um erro com o ASIC que suporta um par, ambas as portas do par ficam offline.

Para evitar essa perda de conetividade, configure o sistema com caminhos redundantes para separar HBAs X1133A-R6 ou com caminhos redundantes para portas compatíveis com ASICs diferentes no HBA.
