---
permalink: san-config/recommended-paths-host-nodes-concept.html 
sidebar: sidebar 
keywords: recommended, number, paths, host, nodes, cluster 
summary: Você não deve exceder mais de oito caminhos do host para cada nó do cluster, prestando atenção ao número total de caminhos que podem ser suportados pelo sistema operacional do host e pelo multipathing usado no host. 
---
= Número recomendado de caminhos do host para nós no cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você não deve exceder mais de oito caminhos do host para cada nó do cluster, prestando atenção ao número total de caminhos que podem ser suportados pelo sistema operacional do host e pelo multipathing usado no host.

Você deve ter no mínimo dois caminhos por LUN conetando-se a cada nó de relatório por meio do mapa de LUN seletivo (SLM) usado pela máquina virtual de storage (SVM) no cluster. Isso elimina pontos únicos de falha e permite que o sistema sobreviva a falhas de componentes.

Se você tiver quatro ou mais nós no cluster ou mais de quatro portas de destino sendo usadas pelas SVMs em qualquer um de seus nós, use os métodos a seguir para limitar o número de caminhos que podem ser usados para acessar LUNs em seus nós, de modo que você não exceda o máximo recomendado de oito caminhos.

* SLM
+
O SLM reduz o número de caminhos do host para o LUN para apenas caminhos no nó proprietário do LUN e do parceiro de HA do nó proprietário. O SLM está ativado por predefinição.

* Portsets para iSCSI
* Mapeamentos do grupo FC de seu host
* Zoneamento do switch FC


.Informações relacionadas
link:../san-admin/index.html["Administração da SAN"]
