---
permalink: san-config/support-shared-san-config-concept.html 
sidebar: sidebar 
keywords: requirements, shared, san, configurations 
summary: Configurações de SAN compartilhadas são definidas como hosts conectados aos sistemas de storage da ONTAP e aos sistemas de storage de outros fornecedores. O acesso aos sistemas de storage da ONTAP e aos sistemas de storage de outros fornecedores a partir de um único host é suportado, desde que vários requisitos sejam atendidos. 
---
= Requisitos para configurações de SAN compartilhadas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Configurações de SAN compartilhadas são definidas como hosts conectados aos sistemas de storage da ONTAP e aos sistemas de storage de outros fornecedores. O acesso aos sistemas de storage da ONTAP e aos sistemas de storage de outros fornecedores a partir de um único host é suportado, desde que sejam atendidos vários requisitos.

Para todos os sistemas operacionais host, é uma prática recomendada usar adaptadores separados para se conetar aos sistemas de storage de cada fornecedor. O uso de adaptadores separados reduz as chances de drivers e configurações conflitantes. Para conexões com um sistema de armazenamento ONTAP, o modelo do adaptador, BIOS, firmware e driver devem ser listados como suportados na ferramenta de Matriz de interoperabilidade do NetApp.

Você deve definir os valores de tempo limite necessários ou recomendados e outros parâmetros de armazenamento para o host. Você deve sempre instalar o software NetApp ou aplicar as configurações do NetApp por último.

* Para o AIX, você deve aplicar os valores da versão do AIX Host Utilities listada na ferramenta de Matriz de interoperabilidade para sua configuração.
* Para o ESX, você deve aplicar as configurações do host usando o Virtual Storage Console para VMware vSphere.
* Para HP-UX, você deve usar as configurações de armazenamento padrão HP-UX.
* Para Linux, você deve aplicar os valores da versão Linux Host Utilities listada na ferramenta de Matriz de interoperabilidade para sua configuração.
* Para o Solaris, você deve aplicar os valores da versão do Solaris Host Utilities listada na ferramenta de Matriz de interoperabilidade para sua configuração.
* Para o Windows, você deve instalar a versão do Windows Host Utilities que está listada na ferramenta de Matriz de interoperabilidade para sua configuração.


.Informações relacionadas
https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^]
