---
permalink: san-config/supported-fc-ports-concept.html 
sidebar: sidebar 
keywords: supported, fc, ports 
summary: O número de portas FC integradas e portas CNA/UTA2 configuradas para FC varia de acordo com o modelo da controladora. As portas FC também estão disponíveis por meio de adaptadores de expansão de destino FC compatíveis ou placas UTA2 adicionais configuradas com adaptadores FC SFP mais. 
---
= Portas FC compatíveis
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O número de portas FC integradas e portas CNA/UTA2 configuradas para FC varia de acordo com o modelo da controladora. As portas FC também estão disponíveis por meio de adaptadores de expansão de destino FC compatíveis ou placas UTA2 adicionais configuradas com adaptadores FC SFP mais.



== FC integrado, UTA e portas de UTA2 GbE

* As portas integradas podem ser configuradas individualmente como portas FC de destino ou iniciador.
* O número de portas FC integradas difere dependendo do modelo do controlador.
+
O https://hwu.netapp.com["NetApp Hardware Universe"^] contém uma lista completa de portas FC integradas em cada modelo de controladora.

* Os sistemas FAS2520 não são compatíveis com FC.




== Portas FC do adaptador de expansão de destino

* Os adaptadores de expansão de destino disponíveis diferem dependendo do modelo do controlador.
+
O https://hwu.netapp.com["NetApp Hardware Universe"^] contém uma lista completa dos adaptadores de expansão de destino para cada modelo de controlador.

* As portas em alguns adaptadores de expansão FC são configuradas como iniciadores ou destinos na fábrica e não podem ser alteradas.
+
Outras podem ser configuradas individualmente como portas FC de destino ou iniciador, assim como as portas FC integradas. Uma lista completa está disponível em https://hwu.netapp.com["NetApp Hardware Universe"^].


