---
permalink: san-config/world-wide-name-based-zoning-concept.html 
sidebar: sidebar 
keywords: world, wide, name-based, zoning 
summary: 'O zoneamento baseado no World Wide Name (WWN) especifica o WWN dos membros a serem incluídos na zona. Ao zonear no ONTAP, você deve usar o zoneamento de nome de porta mundial (WWPN).' 
---
= Zoneamento baseado em nome mundial
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O zoneamento baseado no World Wide Name (WWN) especifica o WWN dos membros a serem incluídos na zona. Ao zonear no ONTAP, você deve usar o zoneamento de nome de porta mundial (WWPN).

WWPN zoneamento fornece flexibilidade porque o acesso não é determinado por onde o dispositivo está fisicamente conetado à malha. Você pode mover um cabo de uma porta para outra sem reconfigurar zonas.

Para caminhos Fibre Channel para controladores de storage que executam ONTAP, verifique se os switches FC estão zoneados usando WWPNs das interfaces lógicas de destino (LIFs), e não as WWPNs das portas físicas no nó. Para obter mais informações sobre LIFs, consulte o _Guia de Gerenciamento de rede do ONTAP_.

link:../networking/networking_reference.html["Gerenciamento de rede"]
