---
permalink: san-config/zoning-restrictions-cisco-fc-fcoe-switches-reference.html 
sidebar: sidebar 
keywords: zoning, restrictions, for cisco, fc, fcoe, switches 
summary: Ao usar os switches FC e FCoE Cisco, uma única zona de malha não deve conter mais de um LIF de destino para a mesma porta física. Se várias LIFs na mesma porta estiverem na mesma zona, as portas LIF podem falhar ao recuperar de uma perda de conexão. 
---
= Restrições de zoneamento para switches Cisco FC e FCoE
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao usar os switches FC e FCoE Cisco, uma única zona de malha não deve conter mais de um LIF de destino para a mesma porta física. Se várias LIFs na mesma porta estiverem na mesma zona, as portas LIF podem falhar ao recuperar de uma perda de conexão.

Os switches FC comuns são usados no protocolo FC-NVMe da mesma maneira que são usados no protocolo FC.

* Várias LIFs para os protocolos FC e FCoE podem compartilhar portas físicas em um nó, contanto que estejam em zonas diferentes.
* O FC-NVMe e o FCoE não podem compartilhar a mesma porta física.
* FC e FC-NVMe podem compartilhar a mesma porta física de 32 GB.
* Os switches FC e FCoE da Cisco exigem que cada LIF em uma determinada porta esteja em uma zona separada das outras LIFs nessa porta.
* Uma única zona pode ter LIFs FC e FCoE. Uma zona pode conter um LIF de cada porta de destino no cluster, mas tenha cuidado para não exceder os limites de caminho do host e verificar a configuração do SLM.
* LIFs em diferentes portas físicas podem estar na mesma zona.
* Os switches Cisco exigem que os LIFs sejam separados.
+
Embora não seja necessário, recomenda-se separar LIFs para todos os switches


