---
permalink: upgrade/arp-warning-clear.html 
sidebar: sidebar 
keywords: ontap, upgrade, ransomware, protection, security, arp 
summary: Antes de atualizar o ONTAP, configure clientes LDAP usando o SSLv3 para comunicações seguras com servidores LDAP para usar o TLS. O SSL não estará disponível após a atualização. 
---
= Resolva os avisos de atividade no ARP (Autonomous ransomware Protection) antes de uma atualização do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de atualizar para o ONTAP 9.16,1 ou posterior, você deve responder a quaisquer avisos de atividade anormais relatados pela proteção Autônoma contra ransomware (ARP). No ONTAP 9.16,1, o ARP mudou para um modelo baseado em aprendizado de máquina/inteligência artificial (IA). Devido a essa alteração, quaisquer avisos ativos não resolvidos do ARP existente no ONTAP 9.15,1 ou anterior serão perdidos após a atualização.

.Passos
. Responda a quaisquer avisos de atividade anormais comunicados pela link:../anti-ransomware/respond-abnormal-task.html["ARP"] e resolva quaisquer problemas potenciais.
. Confirme a resolução desses problemas antes de atualizar selecionando *Atualizar e Limpar tipos de arquivos suspeitos* para Registrar sua decisão e retomar o monitoramento ARP normal.

