---
permalink: upgrade/concept_when_you_need_to_update_the_disk_qualification_package.html 
sidebar: sidebar 
keywords: upgrade, ontap, dqp, disk, qualification, package 
summary: 'Depois de atualizar o ONTAP, adicionar um novo tipo ou tamanho de unidade, ou atualizar o firmware do disco, você também deve atualizar o Pacote de Qualificação de disco do ONTAP (DQP).' 
---
= Atualize o Pacote de Qualificação de disco
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de atualizar seu software ONTAP, você deve baixar e instalar o Pacote de Qualificação de disco do ONTAP (DQP). O DQP não é atualizado como parte de uma atualização do ONTAP.

O DQP contém os parâmetros adequados para a interação ONTAP com todas as unidades recém-qualificadas. Se a sua versão do DQP não contiver informações para uma unidade recém-qualificada, o ONTAP não terá as informações para configurar corretamente a unidade.

É prática recomendada atualizar o DQP a cada trimestre. Você também deve atualizar o DQP pelas seguintes razões:

* Sempre que você adicionar um novo tipo ou tamanho de unidade a um nó no cluster
+
Por exemplo, se você já tiver unidades de 1 TB e adicionar unidades de 2 TB, precisará verificar a atualização DQP mais recente.

* Sempre que atualizar o firmware do disco
* Sempre que estiverem disponíveis ficheiros DQP ou firmware de disco mais recentes


.Informações relacionadas
* https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware/download/DISKQUAL/ALL/qual_devices.zip["NetApp Downloads: Pacote de Qualificação de disco"^]
* https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Downloads do NetApp: Firmware da unidade de disco"^]

