---
permalink: upgrade/confirm-configuration.html 
sidebar: sidebar 
keywords: ontap, upgrade, before, confirm, configuration, hardware, cluster management switches, metrocluster ip switches, san, target, release 
summary: Antes de atualizar o ONTAP, você deve confirmar se sua configuração de hardware é suportada na versão de destino. 
---
= Confirme o suporte do ONTAP para sua configuração de hardware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de atualizar o ONTAP, você deve confirmar se a configuração de hardware pode suportar a versão de destino do ONTAP.



== Todas as configurações

Use https://hwu.netapp.com["NetApp Hardware Universe"^] para confirmar se a plataforma de hardware e os switches de cluster e gerenciamento são suportados na versão de destino do ONTAP. Os switches de cluster e gerenciamento incluem os switches de rede de cluster (NX-os), os switches de rede de gerenciamento (IOS) e o arquivo de configuração de referência (RCF). Se o cluster e os switches de gerenciamento forem suportados, mas não estiverem executando as versões mínimas de software necessárias para a versão de destino do ONTAP, atualize seus switches para versões de software compatíveis.

* https://mysupport.netapp.com/site/info/broadcom-cluster-switch["Downloads do NetApp: Switches de cluster Broadcom"^]
* https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Downloads do NetApp: Switches Ethernet Cisco"^]
* https://mysupport.netapp.com/site/info/netapp-cluster-switch["Downloads do NetApp: Switches de cluster do NetApp"^]



NOTE: Se você precisar atualizar seus switches, a NetApp recomenda que você conclua primeiro a atualização do software ONTAP e, em seguida, execute a atualização de software para seus switches.



== Configurações do MetroCluster

Antes de atualizar o ONTAP, se você tiver uma configuração do MetroCluster, use o https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^] para confirmar que seus switches IP do MetroCluster são suportados na versão do ONTAP de destino.



== Configurações de SAN

Antes de atualizar o ONTAP, se o cluster estiver configurado para SAN, use o https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^] para confirmar se a configuração da SAN é totalmente compatível.

Todos os componentes SAN, incluindo a versão de software ONTAP de destino, o sistema operacional do host e patches, o software de utilitários de host necessários, o software de multipathing e os drivers e firmware do adaptador, devem ser suportados.
