---
permalink: upgrade/considerations-authenticate-ssh-public-key-fips-concept.html 
sidebar: sidebar 
keywords: ontap, upgrade, update, considerations, ssl, fips mode, host key algorithm, authentication 
summary: Se o modo SSL FIPS estiver ativado em um cluster onde as contas de administrador se autenticam com uma chave pública SSH, o algoritmo de chave de host deve ser suportado na versão de destino. 
---
= Verifique o suporte do algoritmo da chave do host SSH antes da atualização do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de atualizar o ONTAP, se o modo SSL FIPS estiver ativado em um cluster onde as contas de administrador se autenticam com uma chave pública SSH, você deve garantir que o algoritmo de chave do host seja suportado na versão de ONTAP de destino.

A tabela a seguir indica algoritmos de tipo de chave de host compatíveis com conexões SSH ONTAP. Esses tipos de chave não se aplicam à configuração da autenticação pública SSH.

[cols="30,30,30"]
|===


| Lançamento do ONTAP | Tipos de chave compatíveis no modo FIPS | Tipos de chave compatíveis no modo não FIPS 


 a| 
9.11.1 e mais tarde
 a| 
ecdsa-sha2-nistp256
 a| 
ecdsa-sha2-nistp256 e rsa-sha2-512 e rsa-sha2-256 e ssh-ed25519 e ssh-dss e ssh-rsa



 a| 
9.10.1 e anteriores
 a| 
ecdsa-sha2-nistp256 e ssh-ed25519
 a| 
ecdsa-sha2-nistp256 ssh-ed25519 ssh-dss e ssh-rsa

|===

NOTE: O suporte para o algoritmo de chave de host ssh-ed25519 é removido a partir de ONTAP 9.11,1.

Para obter mais informações, link:../networking/configure_network_security_using_federal_information_processing_standards_fips.html["Configurar a segurança da rede usando o FIPS"]consulte .

Contas de chave pública SSH existentes sem os algoritmos de chave suportados devem ser reconfiguradas com um tipo de chave suportado antes de atualizar ou a autenticação de administrador falhar.

link:../authentication/enable-ssh-public-key-accounts-task.html["Saiba mais sobre como ativar contas de chave pública SSH."]
