---
permalink: upgrade/create-upgrade-plan.html 
sidebar: sidebar 
keywords: ontap, upgrade, plan, planning, upgrade advisor, advisor, digital advisor, active iq, create an upgrade plan, estimate upgrade, 
summary: O serviço Upgrade Advisor no Digital Advisor fornece inteligência que ajuda você a Planejar sua atualização e minimiza a incerteza e o risco. 
---
= Planeje sua atualização com o Upgrade Advisor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você tiver um contrato ativo link:https://www.netapp.com/us/services/support-edge.aspx["Serviços da SupportEdge"^]para link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["Consultor digital"^]o , é recomendável usar o Upgrade Advisor para gerar um plano de atualização.

O serviço Upgrade Advisor no Digital Advisor fornece inteligência que ajuda você a Planejar sua atualização e minimiza a incerteza e o risco.

O Digital Advisor identifica problemas no seu ambiente que podem ser resolvidos atualizando para uma versão mais recente do ONTAP. O serviço de recomendações de atualização ajuda você a Planejar uma atualização bem-sucedida e fornece um relatório de problemas que você pode precisar estar ciente na versão do ONTAP para a qual você está atualizando.


NOTE: O Supervisor de Atualização requer um pacote AutoSupport completo para criar o relatório.

Se você não tiver um contrato de serviços de borda de suporte ativo para o Digital Advisor, deverá link:prepare.html["Prepare-se para o seu upgrade sem o Upgrade Advisor"].

.Passos
. https://aiq.netapp.com/["Inicie o consultor digital da Active IQ"^]
. No Digital Advisor link:https://docs.netapp.com/us-en/active-iq/task_view_risk_and_take_action.html["visualize todos os riscos associados ao cluster e tome medidas corretivas manualmente"^].
+
Os riscos incluídos nas categorias *alteração de configuração de software*, *alteração de configuração de hardware* e *Substituição de hardware* precisam ser resolvidos antes de realizar uma atualização do ONTAP.

. Reveja o caminho de atualização recomendado e link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["gere o seu plano de atualização"^].


.O que vem a seguir
* Você deve analisar a link:../release-notes/index.html["Notas de versão do ONTAP"]versão de destino do ONTAP recomendada para o cluster pelo Supervisor de Atualização; em seguida, você deve seguir o plano gerado pelo Consultor de Atualização para atualizar o cluster.
* Você deve link:reboot-sp-bmc.html["Reinicie o SP ou o BMC"] antes do início da atualização.


.Informações relacionadas
* https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_manually_upload_AutoSupport_messages_to_NetApp_in_ONTAP_9["Como fazer upload manual de mensagens do AutoSupport para o NetApp"^]

