---
permalink: upgrade/create-upgrade-plan.html 
sidebar: sidebar 
keywords: ontap, upgrade, plan, planning, upgrade advisor, upgrade health checker, advisor, digital advisor, active iq, create an upgrade plan 
summary: Você pode usar o Upgrade Advisor no Active IQ Digital Advisor ou o Upgrade Health Checker para gerar automaticamente um relatório de atualização específico para seu ambiente e configuração de cluster. 
---
= Prepare-se para uma atualização do ONTAP com o Upgrade Advisor ou o Upgrade Health Checker
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o Upgrade Advisor no Active IQ Digital Advisor ou o Upgrade Health Checker para gerar automaticamente um relatório de atualização específico para seu ambiente e configuração de cluster. Ambas as ferramentas fornecem inteligência que ajuda você a planejar sua atualização, identificar bloqueios e avisos e minimizar incertezas e riscos.



== Prepare-se para atualizar com o Upgrade Advisor

Upgrade Advisor identifica problemas em seu ambiente que podem ser resolvidos com a atualização para uma versão mais recente do ONTAP e fornece um relatório de problemas que você pode precisar conhecer na versão do ONTAP para a qual está atualizando. Upgrade Advisor também fornece um caminho de atualização recomendado e gera um plano de atualização específico para a configuração do seu cluster.

Upgrade Advisor é especialmente adequado para usuários com um ambiente menor que preferem uma experiência baseada em nuvem e centrada na interface do usuário.

.Antes de começar
* É necessário ter um contrato ativo de link:https://www.netapp.com/us/services/support-edge.aspx["Serviços da SupportEdge"^] para link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["Consultor digital"^] usar o Upgrade Advisor.
* AutoSupport deve estar habilitado para que o Upgrade Advisor acesse automaticamente os logs do AutoSupport necessários para gerar um plano de atualização. Se você não habilitou o AutoSupport, você pode https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_manually_upload_AutoSupport_messages_to_NetApp_in_ONTAP_9["Carregue manualmente ficheiros AutoSupport"^].


.Passos
. https://aiq.netapp.com/["Inicie o consultor digital da Active IQ"^]
. No Digital Advisor link:https://docs.netapp.com/us-en/active-iq/task_view_risk_and_take_action.html["visualize todos os riscos associados ao cluster e tome medidas corretivas manualmente"^].
+
Os riscos incluídos nas categorias *alteração de configuração de software*, *alteração de configuração de hardware* e *Substituição de hardware* precisam ser resolvidos antes de realizar uma atualização do ONTAP.

. Reveja o caminho de atualização recomendado e link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["gere o seu plano de atualização"^].


.O que vem a seguir
* Você deve analisar a link:../release-notes/index.html["Notas de versão do ONTAP"]versão de destino do ONTAP recomendada para o cluster pelo Supervisor de Atualização; em seguida, você deve seguir o plano gerado pelo Consultor de Atualização para atualizar o cluster.
* Você deve link:reboot-sp-bmc.html["Reinicie o SP ou o BMC"] antes do início da atualização.




== Prepare-se para atualizar com o Upgrade Health Checker

O Upgrade Health Checker é uma ferramenta instalada localmente, adequada para usuários com ambientes grandes ou complexos, acesso limitado à internet ou estruturas de automação e orquestração existentes. Não é necessário contrato SupportEdge para usar o Upgrade Health Checker.

.Antes de começar
Você deve link:https://docs.netapp.com/us-en/upgrade-health-checker/set-up-upgrade-health-checker.html["Baixe e configure o Upgrade Health Checker"] antes de poder usá-lo para gerar um plano de atualização.

.Passos
. link:https://docs.netapp.com/us-en/upgrade-health-checker/generate-report-upgrade-health-checker.html["Gere um plano de atualização com o Upgrade Health Checker"^].


.O que vem a seguir
* Você deve consultar a link:../release-notes/index.html["Notas de versão do ONTAP"] para a versão do ONTAP recomendada para o seu cluster; em seguida, deve seguir o plano gerado pelo Upgrade Health Checker para atualizar o seu cluster.
* Você deve link:reboot-sp-bmc.html["Reinicie o SP ou o BMC"] antes do início da atualização.

