---
permalink: upgrade/download-software-image.html 
sidebar: sidebar 
keywords: ontap, software, image, download, downloading, upgrade 
summary: Dependendo da versão atual do ONTAP, você pode baixar a imagem de software ONTAP de destino para uma atualização para um servidor HTTPS, HTTP ou FTP ou uma pasta local. 
---
= Transfira a imagem do software ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de atualizar o ONTAP, primeiro você deve baixar a imagem de software ONTAP de destino no site de suporte da NetApp. Dependendo da versão do ONTAP, você pode baixar o software ONTAP para um servidor HTTPS, HTTP ou FTP em sua rede ou para uma pasta local.

[cols="2"]
|===
| Se você está correndo... | Você pode baixar a imagem para este local... 


| ONTAP 9 F.6 e mais tarde  a| 
* Um servidor HTTPS com o certificado CA do servidor deve ser instalado no sistema local.
* Uma pasta local
* Um servidor HTTP ou FTP




| ONTAP 9 .4 e mais tarde  a| 
* Uma pasta local
* Um servidor HTTP ou FTP




| ONTAP 9 F.0 e mais tarde | Um servidor HTTP ou FTP 
|===
.Sobre esta tarefa
* Se você estiver executando uma atualização sem interrupções automatizada (ANDU) usando um link:concept_upgrade_paths.html#types-of-upgrade-paths["caminho de atualização direta de multi-hop"], precisará link:download-software-image.html["transferir"]do pacote de software para a versão intermediária do ONTAP e para a versão ONTAP de destino necessária para sua atualização. Por exemplo, se você estiver atualizando do ONTAP 9.8 para o ONTAP 9.13,1, você deve baixar os pacotes de software para ONTAP 9.12,1 e ONTAP 9.13,1. link:concept_upgrade_paths.html#supported-upgrade-paths["caminhos de atualização suportados"]Consulte para determinar se o caminho de atualização requer que você baixe um pacote de software intermediário.
* Se estiver a atualizar um sistema com encriptação de volume NetApp para o ONTAP 9.5 ou posterior, tem de transferir a imagem do software ONTAP para países não restritos, que inclui encriptação de volume NetApp.
+
Se você usar a imagem do software ONTAP para países restritos para atualizar um sistema com criptografia de volume NetApp, o sistema ficará em pânico e perderá o acesso aos volumes.

* Não é necessário transferir um pacote de software separado para o seu firmware. A atualização de firmware do cluster está incluída no pacote de atualização do software ONTAP e é copiada para o dispositivo de inicialização de cada nó. O novo firmware é então instalado como parte do processo de atualização.


.Passos
. Localize o software ONTAP de destino na link:https://mysupport.netapp.com/site/products/all/details/ontap9/downloads-tab["Transferências de software"^] área do site de suporte da NetApp.
+
Para uma atualização do ONTAP Select, selecione *Atualização do nó ONTAP Select*.

. Copie a imagem do software (por exemplo, 97_q_image.tgz) para o local apropriado.
+
Dependendo da versão do ONTAP, o local será um diretório de um servidor HTTP, HTTPS ou FTP a partir do qual a imagem será servida ao sistema local ou a uma pasta local no sistema de armazenamento.


