---
permalink: upgrade/install-software-manual-upgrade.html 
sidebar: sidebar 
keywords: ontap, software, image, download, downloading, install, installing. manual, manually 
summary: Depois de transferir o pacote de software ONTAP para uma atualização manual, tem de o instalar localmente antes de iniciar a atualização 
---
= Instale o pacote de software ONTAP para atualizações manuais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de transferir o pacote de software ONTAP para uma atualização manual, tem de o instalar localmente antes de iniciar a atualização.

.Passos
. Defina o nível de privilégio como avançado, inserindo *y* quando solicitado a continuar: `set -privilege advanced`
+
(`*>`É apresentado o aviso avançado ).

. Instale a imagem.
+
[cols="2"]
|===
| Se tiver a seguinte configuração... | Use este comando... 


 a| 
** Sem MetroCluster
** MetroCluster de 2 nós

 a| 
[source, cli]
----
system node image update -node * -package <location> -replace-package true -setdefault true -background true
----
`<location>` Pode ser um servidor Web ou uma pasta local, dependendo da versão do ONTAP. Consulte a `system node image update` página de manual para obter detalhes.

Este comando instala a imagem do software em todos os nós simultaneamente. Para instalar a imagem em cada nó, uma de cada vez, não especifique o `-background` parâmetro.



 a| 
** MetroCluster de 4 nós
** Configuração de MetroCluster de 8 nós

 a| 
[source, cli]
----
system node image update -node * -package <location> -replace-package true -background true -setdefault false
----
Você deve emitir este comando em ambos os clusters.

Este comando usa uma consulta estendida para alterar a imagem do software de destino, que é instalada como a imagem alternativa em cada nó.

|===
. Digite `y` para continuar quando solicitado.
. Verifique se a imagem do software está instalada em cada nó.
+
[source, cli]
----
system node image show-update-progress -node *
----
+
Este comando exibe o status atual da instalação da imagem de software. Você deve continuar a executar este comando até que todos os nós relatem um *Status de execução* de *sair* e um *Status de saída* de *sucesso*.

+
O comando de atualização da imagem do nó do sistema pode falhar e apresentar mensagens de erro ou aviso. Depois de resolver quaisquer erros ou avisos, você pode executar o comando novamente.

+
Este exemplo mostra um cluster de dois nós no qual a imagem do software é instalada com sucesso em ambos os nós:

+
[listing]
----
cluster1::*> system node image show-update-progress -node *
There is no update/install in progress
Status of most recent operation:
        Run Status:     Exited
        Exit Status:    Success
        Phase:          Run Script
        Exit Message:   After a clean shutdown, image2 will be set as the default boot image on node0.
There is no update/install in progress
Status of most recent operation:
        Run Status:     Exited
        Exit Status:    Success
        Phase:          Run Script
        Exit Message:   After a clean shutdown, image2 will be set as the default boot image on node1.
2 entries were acted on.
----

