---
permalink: upgrade/prepare.html 
sidebar: sidebar 
keywords: upgrade, ontap, prepare, digital advisor, preparation, before you upgrade, plan, upgrade overview, upgrade summary 
summary: A preparação para uma atualização do ONTAP ajuda a identificar e mitigar riscos de atualização ou bloqueadores e conta com considerações especiais aplicáveis à sua configuração. 
---
= Prepare-se para uma atualização do software ONTAP sem o consultor de atualização
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A preparação adequada para uma atualização de software do ONTAP ajuda a identificar e mitigar possíveis riscos de atualização ou bloqueadores antes de iniciar o processo de atualização. Durante a preparação da atualização, você também pode identificar quaisquer considerações especiais que você possa precisar considerar antes de atualizar. Por exemplo, se o modo SSL FIPS estiver ativado no cluster e as contas de administrador usarem chaves públicas SSH para autenticação, você precisará verificar se o algoritmo da chave do host é suportado na versão do ONTAP de destino.

Se tiver um contrato SupportEdge ativo para link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["Consultor digital"^], link:create-upgrade-plan.html["Planeje sua atualização com o Upgrade Advisor"]. Se você não tiver acesso ao consultor digital do Active IQ (também conhecido como consultor digital), faça o seguinte para se preparar para uma atualização do ONTAP.

. link:choose-target-version.html["Escolha o seu lançamento de ONTAP de destino"].
. Revise as seções _Avisos de atualização_ e _problemas conhecidos e limitações_ no link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 Notas de versão"] para sua versão de destino.
+
_Cuidados de atualização_ descreva possíveis problemas que você deve estar ciente antes de atualizar. _Problemas e limitações conhecidos_ descrevem um comportamento potencialmente inesperado do sistema que você pode experimentar após a atualização.

+
Você deve entrar com sua conta do NetApp ou criar uma conta para acessar as Notas de versão.

. link:confirm-configuration.html["Confirme o suporte do ONTAP para sua configuração de hardware"].
+
Sua plataforma de hardware, switches de gerenciamento de cluster e switches IP MetroCluster devem oferecer suporte ao lançamento de destino. Se o cluster estiver configurado para SAN, a configuração da SAN deve ser totalmente suportada.

. link:task_check_for_common_configuration_errors_using_config_advisor.html["Use o Active IQ Config Advisor para verificar se você não tem erros de configuração comuns."]
. Revise o ONTAP suportado link:concept_upgrade_paths.html#supported-upgrade-paths["caminhos de atualização"]para determinar se você pode realizar uma atualização direta ou se precisa concluir a atualização por etapas.
. link:task_verifying_the_lif_failover_configuration.html["Verifique a configuração de failover de LIF"].
+
Antes de realizar uma atualização, é necessário verificar se as políticas de failover e os grupos de failover do cluster estão configurados corretamente.

. link:concept_verify_svm_routing.html["Verifique a configuração de roteamento SVM"].
. link:special-considerations.html["Verifique considerações especiais"] para o cluster.
+
Se houver certas configurações no cluster, há ações específicas que você precisa executar antes de iniciar uma atualização de software do ONTAP.

. link:reboot-sp-bmc.html["Reinicie o SP ou o BMC"].

