---
permalink: upgrade/reboot-sp-bmc.html 
sidebar: sidebar 
keywords: ontap, upgrade, how, firmware, updated, during, digital advisor 
summary: Não é necessário atualizar o firmware antes de uma atualização do ONTAP. O firmware do cluster está incluído no pacote de atualização do ONTAP e é instalado como parte do processo de atualização. 
---
= Reinicie o SP ou o BMC para se preparar para a atualização de firmware durante uma atualização do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Não é necessário atualizar manualmente o firmware antes de efetuar uma atualização do ONTAP. O firmware do cluster está incluído no pacote de atualização do ONTAP e é copiado para o dispositivo de inicialização de cada nó. O novo firmware é então instalado como parte do processo de atualização.

O firmware dos seguintes componentes é atualizado automaticamente se a versão do cluster for mais antiga do que o firmware fornecido com o pacote de atualização do ONTAP:

* BIOS/Loader
* Processador de Serviço (SP) ou controlador de gerenciamento de placa base (BMC)
* Compartimento de armazenamento
* Disco
* Flash Cache


Para se preparar para uma atualização suave, você deve reiniciar o SP ou o BMC antes que a atualização comece.

.Passo
. Reinicie o SP ou o BMC antes da atualização:
+
[source, cli]
----
system service-processor reboot-sp -node <node_name>
----
+
Reinicie apenas um SP ou BMC de cada vez. Aguarde que o SP ou BMC reinicializado recicle completamente antes de reiniciar o próximo.



Você também pode link:../update/firmware-task.html["atualize o firmware manualmente"]fazer o mesmo entre as atualizações do ONTAP. Se tiver o Digital Advisor, pode link:https://activeiq.netapp.com/system-firmware/["Veja a lista de versões de firmware atualmente incluídas na imagem do ONTAP"^].

Versões de firmware atualizadas estão disponíveis da seguinte forma:

* link:https://mysupport.netapp.com/site/downloads/firmware/system-firmware-diagnostics["Firmware do sistema (BIOS, BMC, SP)"^]
* link:https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["Firmware do compartimento"^]
* link:https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Firmware de cache de disco e Flash"^]

