---
permalink: upgrade/snapmirror-cascade-relationship-blocked.html 
sidebar: sidebar 
keywords: ontap, upgrade, 9.9.1. 9.10.1, update, cascade, LTR, long term retention, snapshots, considerations, secondary storage 
summary: 'Se você tiver um relacionamento em cascata do SnapMirror configurado no cluster, talvez seja necessário desativar os snapshots de retenção de longo prazo (LTR) antes de atualizar' 
---
= Desative snapshots de retenção de longo prazo antes da atualização do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Em um relacionamento de volumes em cascata, os snapshots de retenção de longo prazo (LTR) são suportados apenas no volume de destino SnapMirror final da cascata em todas as versões do ONTAP 9.  Habilitar snapshots LTR em qualquer volume intermediário na cascata resulta em backups e snapshots perdidos.

Saiba mais sobrelink:../data-protection/long-term-retention-snapshots-concept.html["instantâneos de retenção de longo prazo"] .

Se você tiver uma configuração sem suporte na qual os instantâneos LTR foram habilitados em qualquer volume intermediário de uma cascata, entre em contato com o suporte técnico e consulte olink:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/Cascading_a_volume_with_Long-Term_Retention_(LTR)_snapshots_enabled_is_not_supported["Base de conhecimento da NetApp : não há suporte para cascateamento de um volume com snapshots de retenção de longo prazo (LTR) habilitados"^] para assistência.

As seguintes versões do ONTAP não permitem que você habilite snapshots LTR em nenhum volume em uma cascata, exceto no volume de destino final do SnapMirror .

* 9.15.1 e posterior
* 9.14.1P2 e P4 até P14
* 9.13.1P9 a P17
* 9.12.1 P12 a P19
* 9.11.1P15 a P20
* 9.10.1P18 a P20
* 9.9.1P20


Antes de atualizar de uma versão do ONTAP que permite habilitar snapshots LTR em volumes intermediários de uma cascata para uma versão do ONTAP que os bloqueia, você precisa desabilitar snapshots LTR para evitar backups e snapshots perdidos.

Você precisa agir nos seguintes cenários:

* Os instantâneos de retenção de longo prazo (LTR) são configurados no volume "B" em uma cascata SnapMirror "A > B > C" ou em outro volume de destino SnapMirror médio em sua cascata maior.
* Os instantâneos LTR são definidos por uma programação aplicada a uma regra de política do SnapMirror. Essa regra não replica snapshots do volume de origem, mas os cria diretamente no volume de destino.
+

NOTE: Para obter mais informações sobre cronogramas e políticas do SnapMirror , consulte olink:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/How_does_the_schedule_parameter_in_an_ONTAP_9_SnapMirror_policy_rule_work["Base de conhecimento da NetApp : Como funciona o parâmetro "schedule" em uma regra de política do ONTAP 9 SnapMirror ?"^] .



.Passos
. Remova a regra LTR da política SnapMirror no volume médio da cascata:
+
[listing]
----
Secondary::> snapmirror policy remove-rule -vserver <> -policy <> -snapmirror-label <>
----
+
Saiba mais sobre  `snapmirror policy remove-rule` no link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-remove-rule.html["Referência do comando ONTAP"^] .

. Adicione a regra novamente para a etiqueta SnapMirror sem a programação LTR:
+
[listing]
----
Secondary::> snapmirror policy add-rule -vserver <> -policy <> -snapmirror-label <> -keep <>
----
+

NOTE: A remoção de instantâneos LTR das regras de política do SnapMirror significa que o SnapMirror irá retirar os instantâneos com o rótulo fornecido do volume de origem. Também pode ser necessário adicionar ou modificar uma programação na política de instantâneos do volume de origem para criar instantâneos devidamente rotulados.

+
Saiba mais sobre `snapmirror policy add-rule` o link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-add-rule.html["Referência do comando ONTAP"^]na .

. Se necessário, modifique (ou crie) um agendamento na política de instantâneos do volume de origem para permitir que os instantâneos sejam criados com um rótulo SnapMirror:
+
[listing]
----
Primary::> volume snapshot policy modify-schedule -vserver <> -policy <> -schedule <> -snapmirror-label <>
----
+
[listing]
----
Primary::> volume snapshot policy add-schedule -vserver <> -policy <> -schedule <> -snapmirror-label <> -count <>
----



NOTE: Os instantâneos LTR ainda podem ser ativados no volume de destino final do SnapMirror dentro de uma configuração em cascata do SnapMirror.
