---
permalink: upgrade/snapmirror-cascade-relationship-blocked.html 
sidebar: sidebar 
keywords: ontap, upgrade, 9.9.1. 9.10.1, update, cascade, LTR, long term retention, snapshots, considerations, secondary storage 
summary: Se você tiver um relacionamento em cascata do SnapMirror configurado em seu cluster, talvez seja necessário desativar os snapshots de retenção de longo prazo antes de atualizar. 
---
= Desative snapshots de retenção de longo prazo antes da atualização do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Em uma relação de volumes em cascata, snapshots de retenção de longo prazo são suportados apenas no volume de destino SnapMirror final da cascata em todas as versões do ONTAP 9. Habilitar snapshots de retenção de longo prazo em qualquer volume intermediário na cascata resulta em backups e snapshots perdidos.

Saiba mais sobrelink:../data-protection/long-term-retention-snapshots-concept.html["instantâneos de retenção de longo prazo"] .

Se você tiver uma configuração não suportada na qual snapshots de retenção de longo prazo estejam habilitados em qualquer volume intermediário de uma cascata, entre em contato com o suporte técnico e consulte o link https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/Cascading_a_volume_with_Long-Term_Retention_ retention)_snapshots_enabled_is_not_supported [Base de conhecimento da NetApp : Cascatar um volume com snapshots de retenção de longo prazo (LTR) habilitados não é suportado^] para obter assistência.

As seguintes versões do ONTAP não permitem ativar snapshots de retenção de longo prazo em nenhum volume em cascata, exceto no volume de destino final do SnapMirror .

* 9.15.1 e posterior
* 9.14.1P2 e P4 até P14
* 9.13.1P9 a P17
* 9.12.1 P12 a P19
* 9.11.1P15 a P20
* 9.10.1P18 a P20
* 9.9.1P20


Antes de atualizar de uma versão do ONTAP que permite habilitar snapshots de retenção de longo prazo em volumes intermediários de uma cascata para uma versão do ONTAP que os bloqueia, você precisa desabilitar os snapshots de retenção de longo prazo para evitar a perda de backups e snapshots.

Você precisa agir nos seguintes cenários:

* Os snapshots de retenção de longo prazo são configurados no volume "B" em uma cascata SnapMirror "A > B > C" ou em outro volume de destino SnapMirror intermediário em sua cascata maior.
* Os snapshots de retenção de longo prazo são definidos por um cronograma aplicado a uma regra de política do SnapMirror . Esta regra não replica snapshots do volume de origem, mas os cria diretamente no volume de destino.
+

NOTE: Para obter mais informações sobre cronogramas e políticas do SnapMirror , consulte olink:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/How_does_the_schedule_parameter_in_an_ONTAP_9_SnapMirror_policy_rule_work["Base de conhecimento da NetApp : Como funciona o parâmetro "schedule" em uma regra de política do ONTAP 9 SnapMirror ?"^] .



.Passos
. Remova a regra de retenção de longo prazo da política SnapMirror no volume intermediário da cascata:
+
[listing]
----
Secondary::> snapmirror policy remove-rule -vserver <> -policy <> -snapmirror-label <>
----
+
Saiba mais sobre  `snapmirror policy remove-rule` no link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-remove-rule.html["Referência do comando ONTAP"^] .

. Adicione a regra novamente para o rótulo SnapMirror sem o cronograma de retenção de longo prazo:
+
[listing]
----
Secondary::> snapmirror policy add-rule -vserver <> -policy <> -snapmirror-label <> -keep <>
----
+

NOTE: Remover os snapshots de retenção de longo prazo das regras de política do SnapMirror significa que o SnapMirror irá extrair os snapshots com o rótulo fornecido do volume de origem. Você também pode precisar adicionar ou modificar um agendamento na política de snapshots do volume de origem para criar snapshots devidamente rotulados.

+
Saiba mais sobre `snapmirror policy add-rule` o link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-add-rule.html["Referência do comando ONTAP"^]na .

. Se necessário, modifique (ou crie) um agendamento na política de instantâneos do volume de origem para permitir que os instantâneos sejam criados com um rótulo SnapMirror:
+
[listing]
----
Primary::> volume snapshot policy modify-schedule -vserver <> -policy <> -schedule <> -snapmirror-label <>
----
+
[listing]
----
Primary::> volume snapshot policy add-schedule -vserver <> -policy <> -schedule <> -snapmirror-label <> -count <>
----



NOTE: A retenção de snapshots a longo prazo ainda pode ser ativada no volume de destino final do SnapMirror dentro de uma configuração em cascata do SnapMirror .
