---
permalink: upgrade/task_what_to_do_after_upgrade.html 
sidebar: sidebar 
keywords: ontap, upgrade, plan, planning, upgrade, how, post-checks 
summary: Depois de atualizar o software ONTAP, há várias tarefas que você deve executar para verificar a prontidão do cluster. 
---
= O que fazer após uma atualização do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de atualizar o ONTAP, há várias tarefas que você deve executar para verificar a prontidão do cluster.

. link:task_verify_cluster_after_upgrade.html["Verifique o cluster"].
+
Depois de atualizar o ONTAP, verifique a versão do cluster, a integridade do cluster e a integridade do storage. Se você estiver usando uma configuração MetroCluster FC, também precisará verificar se o cluster está habilitado para switchover automático não planejado.

. link:task_enabling_and_reverting_lifs_to_home_ports_post_upgrade.html["Verifique se todos os LIFs estão em portas residenciais"].
+
Durante uma reinicialização, alguns LIFs podem ter sido migrados para suas portas de failover atribuídas. Depois de atualizar um cluster, você deve habilitar e reverter quaisquer LIFs que não estejam em suas portas iniciais.

. Verifique link:concept_special_configurations_post_checks.html["considerações especiais"] específico para o cluster.
+
Se existirem determinadas configurações no cluster, poderá ser necessário executar passos adicionais após a atualização.

. link:concept_when_you_need_to_update_the_disk_qualification_package.html["Atualizar o Pacote de Qualificação de disco (DQP)"].
+
O DQP não é atualizado como parte de uma atualização do ONTAP.


