---
permalink: upgrade/task_verifying_the_san_configuration_after_an_upgrade.html 
sidebar: sidebar 
keywords: ontap, upgrade, post, after, san, verify 
summary: Após uma atualização do ONTAP, em um ambiente SAN, verifique se cada iniciador que foi conetado a um LIF antes da atualização foi reconetado com êxito ao LIF 
---
= Verifique a configuração da SAN após uma atualização do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Após uma atualização do ONTAP, em um ambiente SAN, você deve verificar se cada iniciador que foi conetado a um LIF antes da atualização foi reconetado com êxito ao LIF.

. Verifique se cada iniciador está conetado ao LIF correto.
+
Você deve comparar a lista de iniciadores com a lista que você fez durante a preparação da atualização. Se você estiver executando o ONTAP 9.11,1 ou posterior, use o Gerenciador do sistema para exibir o status da conexão, pois ele oferece uma exibição muito mais clara do que a CLI.

+
[role="tabbed-block"]
====
.System Manager
--
.. No System Manager, clique em *hosts > SAN Initiator Groups*.
+
A página exibe uma lista de grupos de iniciadores (grupos de iniciadores). Se a lista for grande, você pode visualizar páginas adicionais da lista clicando nos números de página no canto inferior direito da página.

+
As colunas exibem várias informações sobre os grupos. A partir de 9.11.1, o estado da ligação do grupo também é apresentado. Passe o Mouse sobre alertas de status para ver detalhes.



--
.CLI
--
** Listar iniciadores iSCSI:
+
[source, cli]
----
iscsi initiator show -fields igroup,initiator-name,tpgroup
----
** Listar iniciadores FC:
+
[source, cli]
----
fcp initiator show -fields igroup,wwpn,lif
----


--
====

