---
permalink: upgrade/task_enabling_and_reverting_lifs_to_home_ports_post_upgrade.html 
sidebar: sidebar 
keywords: ontap, upgrade, after, post, enable, enabling, revert, reverting, lifs, home, ports 
summary: Durante uma reinicialização da atualização, alguns LIFs podem ser migrados para suas portas de failover atribuídas. Após a atualização, habilite e reverta LIFs que não estão em suas portas domésticas. 
---
= Verifique se todos os LIFS estão em portas domésticas após a atualização do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durante a reinicialização que ocorre como parte do processo de atualização do ONTAP, alguns LIFs podem ser migrados de suas portas domésticas para suas portas de failover atribuídas. Após uma atualização, você precisa ativar e reverter quaisquer LIFs que não estejam em suas portas domésticas.

.Passos
. Apresentar o estado de todas as LIFs:
+
[source, cli]
----
network interface show -fields home-port,curr-port
----
+
Se *Status Admin* estiver "inativo" ou *for home* for "false" para quaisquer LIFs, continue com a próxima etapa.

. Ativar os LIFs de dados:
+
[source, cli]
----
network interface modify {-role data} -status-admin up
----
. Reverter LIFs para suas portas domésticas:
+
[source, cli]
----
network interface revert *
----
. Verifique se todos os LIFs estão em suas portas residenciais:
+
[source, cli]
----
network interface show
----
+
Este exemplo mostra que todos os LIFs para SVM vs0 estão em suas portas domésticas.

+
[listing]
----
cluster1::> network interface show -vserver vs0
         Logical    Status     Network         Current  Current Is
Vserver  Interface  Admin/Oper Address/Mask    Node     Port    Home
-------- ---------- ---------- --------------- -------- ------- ----
vs0
         data001    up/up      192.0.2.120/24  node0    e0e     true
         data002    up/up      192.0.2.121/24  node0    e0f     true
         data003    up/up      192.0.2.122/24  node0    e2a     true
         data004    up/up      192.0.2.123/24  node0    e2b     true
         data005    up/up      192.0.2.124/24  node1    e0e     true
         data006    up/up      192.0.2.125/24  node1    e0f     true
         data007    up/up      192.0.2.126/24  node1    e2a     true
         data008    up/up      192.0.2.127/24  node1    e2b     true
8 entries were displayed.
----

