---
permalink: zero-trust/zero-trust-cloud-deployments.html 
sidebar: sidebar 
keywords: tr-4829, zero trust, netapp, cloud, deployments, hybrid, amazon web services, aws, microsoft azure, google cloud platform, gcp 
summary: As opções do NetApp estendem os sistemas de gerenciamento de dados locais até a nuvem híbrida, com os principais fornecedores de nuvem, compatíveis com controles de segurança de confiança zero 
---
= Implantações de nuvem híbrida e de confiança zero
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A NetApp é a autoridade em dados para a nuvem híbrida. O NetApp oferece várias opções para estender os sistemas de gerenciamento de dados locais para a nuvem híbrida com o Amazon Web Services (AWS), o Microsoft Azure, o Google Cloud Platform (GCP) e outros fornecedores de nuvem líderes do setor. As soluções de nuvem híbrida da NetApp são compatíveis com os mesmos controles de segurança Zero Trust que estão disponíveis nos sistemas ONTAP no local e no storage definido por software da ONTAP Select.

Amplie a capacidade em nuvens públicas com facilidade sem restrições de capex típicas usando o NetApp Cloud Volumes Service, o primeiro serviço de arquivos nativo em nuvem de classe empresarial para AWS e GCP e o Azure NetApp Files para Microsoft Azure. Ideal para workloads com uso intenso de dados, como análises e DevOps, esses serviços de dados em nuvem combinam storage elástico sob demanda como serviço da NetApp com o gerenciamento de dados da ONTAP em uma oferta totalmente gerenciada.

Para aqueles que buscam serviços avançados de dados para serviços de storage de objetos ou bloco na nuvem, como AWS EBS e S3 ou Azure Storage, o Cloud Volumes ONTAP oferece gerenciamento de dados entre seu ambiente local e a nuvem pública com uma única visualização comum. Executado na AWS ou no Azure como uma instância sob demanda, o Cloud Volumes ONTAP fornece a eficiência de storage, a disponibilidade e a escalabilidade do software ONTAP. O ONTAP permite a movimentação de dados entre os sistemas ONTAP no local e o ambiente de storage da AWS ou do Azure com o software de replicação de dados NetApp SnapMirror.
