---
permalink: zero-trust/zero-trust-automation-orchestration.html 
sidebar: sidebar 
keywords: tr-4829, zero trust, ontap, netapp, security, automation, orchestration, control, ansible 
summary: A automação permite que as organizações escalem implantações Zero Trust além dos procedimentos manuais para se defenderem de atividades mal criadas que também são automatizadas 
---
= Controles de orquestração e automação de segurança da NetApp externos ao ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A automação permite que você execute um processo ou procedimento com o mínimo de assistência humana. A automação permite que as organizações escalem implantações Zero Trust muito além dos procedimentos manuais para se defenderem de atividades maliciosas que também são automatizadas.

O Ansible é uma ferramenta de provisionamento de software de código aberto, gerenciamento de configurações e implantação de aplicações. Ele é executado em muitos sistemas Unix-like, e pode configurar tanto sistemas Unix-like como Microsoft Windows. Ele inclui sua própria linguagem declarativa para descrever a configuração do sistema. Ansible foi escrito por Michael DeHaan e adquirido pela Red Hat em 2015. O Ansible está sem agente, conetando-se temporariamente remotamente por meio de SSH ou Gerenciamento remoto do Windows (permitindo a execução remota do PowerShell) para executar tarefas. O NetApp desenvolveu mais do que https://www.netapp.com/us/getting-started-with-netapp-approved-ansible-modules/index.aspx["150 módulos do Ansible para o software ONTAP"^]o , possibilitando ainda mais integração com a estrutura de automação do Ansible. Os módulos do Ansible para NetApp fornecem um conjunto de instruções para definir o estado desejado e reencaminhá-lo para o ambiente NetApp de destino. Os módulos são criados para dar suporte a tarefas como configuração de licenciamento, criação de agregados e máquinas virtuais de armazenamento, criação de volumes e restauração de instantâneos para citar alguns. Uma função do Ansible foi https://github.com/NetApp/ansible/tree/master/nar_ontap_security_ucd_guide["Publicado no GitHub"^] específica do Guia de implantação de recursos unificados (UC) do NetApp DoD.

Ao usar a biblioteca de módulos disponíveis, os usuários podem facilmente desenvolver playbooks do Ansible e personalizá-los de acordo com suas próprias aplicações e necessidades empresariais para automatizar tarefas mundanas. Depois que um manual é escrito, você pode executá-lo para executar a tarefa especificada, o que economiza tempo e melhora a produtividade. A NetApp criou e compartilhou exemplos de playbooks que podem ser usados diretamente ou personalizados para suas necessidades.

O Cloud Insights é uma ferramenta de monitoramento de infraestrutura que oferece visibilidade de toda a sua infraestrutura. Com o Cloud Insights, você pode monitorar, solucionar problemas e otimizar todos os recursos, incluindo instâncias de nuvem pública e data centers privados. O Cloud Insights pode reduzir o tempo médio de resolução em 90% e impedir que 80% dos problemas de nuvem afetem os usuários finais. Ele também pode reduzir os custos de infraestrutura de nuvem em uma média de 33% e reduzir a exposição a ameaças internas protegendo seus dados com inteligência acionável. O recurso de segurança de carga de trabalho de armazenamento do Cloud Insights permite que análises comportamentais de usuários com IA e ML alertem quando comportamentos aberrantes de usuários ocorrem devido a uma ameaça interna. Para o ONTAP, a segurança da carga de trabalho de storage faz uso do mecanismo de FPolicy Zero Trust.
