---
permalink: performance-admin/add-alerts-task.html 
sidebar: sidebar 
keywords: add, alerts 
summary: Você pode configurar alertas para notificá-lo quando um evento específico é gerado. Você pode configurar alertas para um único recurso, para um grupo de recursos ou para eventos de um tipo de gravidade específico. Você pode especificar a frequência com que deseja ser notificado e associar um script ao alerta. 
---
= Adicionar alertas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar alertas para notificá-lo quando um evento específico é gerado. Você pode configurar alertas para um único recurso, para um grupo de recursos ou para eventos de um tipo de gravidade específico. Você pode especificar a frequência com que deseja ser notificado e associar um script ao alerta.

.Antes de começar
* Você deve ter configurado configurações de notificação, como endereço de e-mail do usuário, servidor SMTP e host de intercetação SNMP, para permitir que o servidor Active IQ Unified Manager use essas configurações para enviar notificações aos usuários quando um evento é gerado.
* Você deve saber os recursos e eventos para os quais deseja acionar o alerta e os nomes de usuário ou endereços de e-mail dos usuários que deseja notificar.
* Se você quiser que um script seja executado com base no evento, você deve ter adicionado o script ao Unified Manager usando a página Scripts.
* Tem de ter a função Administrador de aplicações ou Administrador de armazenamento.


.Sobre esta tarefa
Você pode criar um alerta diretamente da página de detalhes do evento depois de receber um evento, além de criar um alerta na página Configuração de Alerta, conforme descrito aqui.

.Passos
. No painel de navegação esquerdo, clique em *Gerenciamento de armazenamento* > *Configuração de alerta*.
. Na página *Configuração de alerta*, clique em *Adicionar*.
. Na caixa de diálogo *Adicionar alerta*, clique em *Nome* e insira um nome e uma descrição para o alerta.
. Clique em *recursos* e selecione os recursos a serem incluídos ou excluídos do alerta.
+
Você pode definir um filtro especificando uma cadeia de texto no campo *Name contains* para selecionar um grupo de recursos. Com base na cadeia de texto especificada, a lista de recursos disponíveis exibe apenas os recursos que correspondem à regra de filtro. A cadeia de texto especificada é sensível a maiúsculas e minúsculas.

+
Se um recurso estiver em conformidade com as regras incluir e excluir que você especificou, a regra excluir terá precedência sobre a regra incluir e o alerta não será gerado para eventos relacionados ao recurso excluído.

. Clique em *Eventos* e selecione os eventos com base no nome do evento ou no tipo de gravidade do evento para os quais deseja acionar um alerta.
+
[TIP]
====
Para selecionar mais de um evento, pressione a tecla Ctrl enquanto você faz suas seleções.

====
. Clique em *ações* e selecione os usuários que você deseja notificar, escolha a frequência de notificação, escolha se uma trap SNMP será enviada ao recetor de trap e atribua um script a ser executado quando um alerta for gerado.
+
[NOTE]
====
Se você modificar o endereço de e-mail especificado para o usuário e reabrir o alerta para edição, o campo Nome será exibido em branco porque o endereço de e-mail modificado não será mais mapeado para o usuário selecionado anteriormente. Além disso, se você modificou o endereço de e-mail do usuário selecionado na página usuários, o endereço de e-mail modificado não será atualizado para o usuário selecionado.

====
+
Você também pode optar por notificar os usuários através de traps SNMP.

. Clique em *Salvar*.


.Exemplo de adição de um alerta
Este exemplo mostra como criar um alerta que atenda aos seguintes requisitos:

* Nome do alerta: HealthTest
* Recursos: Inclui todos os volumes cujo nome contém "abc" e exclui todos os volumes cujo nome contém "xyz"
* Eventos: Inclui todos os eventos críticos de saúde
* Ações: Inclui "sample@domain.com", um script "Test", e o usuário deve ser notificado a cada 15 minutos


Execute as seguintes etapas na caixa de diálogo Adicionar alerta:

. Clique em *Nome* e insira `HealthTest` no campo *Nome* do alerta.
. Clique em *recursos* e, na guia incluir, selecione *volumes* na lista suspensa.
+
.. Digite `abc` o campo *Name contains* para exibir os volumes cujo nome contém "abc".
.. Selecione *<<All Volumes whose name contains 'abc'>> na área recursos disponíveis e mova-o para a área recursos selecionados.
.. Clique em *Excluir*, digite `xyz` o campo *Nome contém* e clique em *Adicionar*.


. Clique em *Eventos* e selecione *Crítica* no campo gravidade do evento.
. Selecione *todos os Eventos críticos* na área Eventos correspondentes e mova-os para a área Eventos selecionados.
. Clique em *ações* e insira `sample@domain.com` no campo alertar esses usuários.
. Selecione *lembrar a cada 15 minutos* para notificar o usuário a cada 15 minutos.
+
Você pode configurar um alerta para enviar repetidamente notificações aos destinatários por um tempo especificado. Você deve determinar a hora a partir da qual a notificação de evento está ativa para o alerta.

. No menu Selecionar Script para execução, selecione *Test* script.
. Clique em *Salvar*.

