---
permalink: performance-admin/check-network-settings-task.html 
sidebar: sidebar 
keywords: check, mtu, network, setting, storage, system 
summary: Você pode alterar as configurações de rede no sistema de armazenamento se elas não forem as mesmas do cliente ou de outros endpoints de rede. Enquanto a configuração MTU da rede de gerenciamento está definida como 1500, o tamanho da MTU da rede de dados deve ser 9000. 
---
= Verifique a configuração de rede MTU no sistema de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar as configurações de rede no sistema de armazenamento se elas não forem as mesmas do cliente ou de outros endpoints de rede. Enquanto a configuração MTU da rede de gerenciamento está definida como 1500, o tamanho da MTU da rede de dados deve ser 9000.



== Sobre esta tarefa

Todas as portas dentro de um domínio de broadcast têm o mesmo tamanho MTU, com exceção do tráfego de gerenciamento de gerenciamento de gerenciamento de portas e0M. Se a porta for parte de um domínio de broadcast, use o `broadcast-domain modify` comando para alterar a MTU para todas as portas dentro do domínio de broadcast modificado.

Observe que os dispositivos de rede intermediários, como NICs e switches de dados, podem ser definidos para tamanhos de MTU mais altos do que os endpoints de rede. Para obter mais informações, link:../performance-admin/check-network-settings-data-switches-task.html["Verifique as definições de rede nos interrutores de dados"]consulte .

.Passos
. Verifique a configuração da porta MTU no sistema de armazenamento:
+
`network port show -instance`

+
Saiba mais sobre `network port show` o link:https://docs.netapp.com/us-en/ontap-cli/network-port-show.html["Referência do comando ONTAP"^]na .

. Altere a MTU no domínio de broadcast usado pelas portas:
+
`network port broadcast-domain modify -ipspace _ipspace_ -broadcast-domain _broadcast_domain_ -mtu _new _mtu_`



.Exemplo
O exemplo a seguir altera a configuração da porta MTU para 9000:

[listing]
----
network port broadcast-domain modify -ipspace Cluster -broadcast-domain Cluster -mtu 9000
----