---
permalink: performance-admin/check-fc-adapter-port-speed-task.html 
sidebar: sidebar 
keywords: check, fc, adapter, port, speed 
summary: A velocidade da porta de destino do adaptador deve corresponder à velocidade do dispositivo ao qual se coneta, para otimizar o desempenho. Se a porta estiver definida para negociação automática, pode demorar mais tempo para se reconetar após uma tomada de posse e giveback ou outra interrupção. 
---
= Verifique a velocidade da porta do adaptador ONTAP FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A velocidade da porta de destino do adaptador deve corresponder à velocidade do dispositivo ao qual se coneta, para otimizar o desempenho. Se a porta estiver definida para negociação automática, pode demorar mais tempo para se reconetar após uma tomada de posse e giveback ou outra interrupção.

.Antes de começar
Todos os LIFs que usam esse adaptador como porta inicial devem estar offline.

.Passos
. Coloque o adaptador offline:
+
`network fcp adapter modify -node _nodename_ -adapter _adapter_ -state _down_`

+
Saiba mais sobre `network fcp adapter modify` o link:https://docs.netapp.com/us-en/ontap-cli/network-fcp-adapter-modify.html["Referência do comando ONTAP"^]na .

. Verifique a velocidade máxima do adaptador de porta:
+
`fcp adapter show -instance`

+
Saiba mais sobre `fcp adapter show` o link:https://docs.netapp.com/us-en/ontap-cli/network-fcp-adapter-show.html["Referência do comando ONTAP"^]na .

. Altere a velocidade da porta, se necessário:
+
`network fcp adapter modify -node _nodename_ -adapter _adapter_ -speed {1|2|4|8|10|16|auto}`

. Coloque o adaptador online:
+
`network fcp adapter modify -node _nodename_ -adapter _adapter_ -state up`

. Coloque todos os LIFs no adaptador online:
+
`network interface modify -vserver * -lif * { -home-node node1 -home-port e0c } -status-admin up`

+
Saiba mais sobre `network interface modify` o link:https://docs.netapp.com/us-en/ontap-cli/network-interface-modify.html["Referência do comando ONTAP"^]na .



.Exemplo
O exemplo a seguir altera a velocidade da porta do adaptador `0d` `node1` para 2 Gbps:

[listing]
----
cluster1::> network fcp adapter modify -node node1 -adapter 0d -speed 2
----