---
permalink: performance-admin/check-network-settings-data-switches-task.html 
sidebar: sidebar 
keywords: check, network, settings, data, switches, mtu 
summary: 'Embora seja necessário manter as mesmas configurações de MTU em seus clientes, servidores e sistemas de armazenamento (ou seja, endpoints de rede), os dispositivos de rede intermediários, como NICs e switches, devem ser definidos para seus valores máximos de MTU para garantir que o desempenho não seja afetado.' 
---
= Verifique as definições de rede nos interrutores de dados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Embora seja necessário manter as mesmas configurações de MTU em seus clientes, servidores e sistemas de armazenamento (ou seja, endpoints de rede), os dispositivos de rede intermediários, como NICs e switches, devem ser definidos para seus valores máximos de MTU para garantir que o desempenho não seja afetado.

Para obter o melhor desempenho, todos os componentes da rede devem poder encaminhar quadros jumbo (9000 bytes IP, 9022 bytes incluindo Ethernet). Os switches de dados devem ser definidos para pelo menos 9022 bytes, mas um valor típico de 9216 é possível com a maioria dos switches.

.Procedimento
Para centrais de dados, verifique se o tamanho da MTU está definido para 9022 ou superior.

Para obter mais informações, consulte a documentação do fornecedor do switch.
