---
permalink: performance-admin/download-deploying-unified-manager-task.html 
sidebar: sidebar 
keywords: download, deploy, active iq unified manager 
summary: 'Para instalar o software, você deve baixar o arquivo de instalação do dispositivo virtual (VA) e usar um cliente VMware vSphere para implantar o arquivo em um servidor VMware ESXi. O VA está disponível num ficheiro OVA.' 
---
= Baixe e implante o ONTAP Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para instalar o software, você deve baixar o arquivo de instalação do dispositivo virtual (VA) e usar um cliente VMware vSphere para implantar o arquivo em um servidor VMware ESXi. O VA está disponível num ficheiro OVA.

.Passos
. Vá para a página *Download de software do site de suporte da NetApp* e localize o Active IQ Unified Manager.
+
https://mysupport.netapp.com/products/index.html[]

. Selecione *VMware vSphere* no menu suspenso *Select Platform* e clique em *Go!*
. Salve o arquivo "OVA" em um local local ou de rede acessível ao cliente VMware vSphere.
. No VMware vSphere Client, clique em *File* > *Deploy OVF Template*.
. Localize o arquivo "OVA" e use o assistente para implantar o dispositivo virtual no servidor ESXi.
+
Você pode usar a guia *Propriedades* no assistente para inserir suas informações de configuração estática.

. Ligue a VM.
. Clique na guia *Console* para exibir o processo de inicialização inicial.
. Siga o prompt para instalar o VMware Tools na VM.
. Configure o fuso horário.
. Introduza um nome de utilizador e uma palavra-passe de manutenção.
. Vá para o URL exibido pelo console da VM.

