---
permalink: performance-admin/enable-disable-throughput-floors-v2-task.html 
sidebar: sidebar 
keywords: enable, disable, throughput, floors v2 
summary: 'Você pode ativar ou desativar os andares de taxa de transferência v2 no AFF. A predefinição é Enabled (activado). Com os andares v2 ativados, os andares de taxa de transferência podem ser atendidos quando os controladores são muito usados em detrimento da latência mais alta em outros workloads. Os pisos v2 aplicam-se a QoS e QoS adaptável.' 
---
= Ativar ou desativar os pisos de rendimento v2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode ativar ou desativar os andares de taxa de transferência v2 no AFF. A predefinição é Enabled (activado). Com os andares v2 ativados, os andares de taxa de transferência podem ser atendidos quando os controladores são muito usados em detrimento da latência mais alta em outros workloads. Os pisos v2 aplicam-se a QoS e QoS adaptável.

.Passos
. Alterar para nível de privilégio avançado:
+
`set -privilege advanced`

. Introduza um dos seguintes comandos:
+
|===
| Se você quiser... | Use este comando: 


 a| 
Desativar pisos v2
 a| 
`qos settings throughput-floors-v2 -enable false`



 a| 
Ativar os pisos v2
 a| 
`qos settings throughput-floors-v2 -enable true`

|===
+
[NOTE]
====
Para desativar os pisos de taxa de transferência v2 num cluster MetroCluster, tem de executar o.

`qos settings throughput-floors-v2 -enable false`

comando nos clusters de origem e destino.

====
+
[listing]
----
cluster1::*> qos settings throughput-floors-v2 -enable false
----
+
Saiba mais sobre `qos settings throughput-floors-v2` o link:https://docs.netapp.com/us-en/ontap-cli/qos-settings-throughput-floors-v2.html["Referência do comando ONTAP"^]na .


