---
permalink: performance-admin/identify-performance-issues-unified-manager-task.html 
sidebar: sidebar 
keywords: identify, performance, issues, active iq unified manager 
summary: Se ocorrer um evento de desempenho, você poderá localizar a origem do problema no Active IQ Unified Manager e usar outras ferramentas para corrigi-lo. Você pode receber uma notificação por e-mail de um evento ou notar o evento durante o monitoramento diário. 
---
= Identificar problemas de desempenho no ONTAP Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se ocorrer um evento de desempenho, você poderá localizar a origem do problema no Active IQ Unified Manager e usar outras ferramentas para corrigi-lo. Você pode receber uma notificação por e-mail de um evento ou notar o evento durante o monitoramento diário.

.Passos
. Clique no link na notificação por e-mail, que o leva diretamente ao objeto de armazenamento com um evento de desempenho.
+
|===


| Se você... | Então... 


 a| 
Receba uma notificação por e-mail de um evento
 a| 
Clique no link para ir diretamente para a página de detalhes do evento.



 a| 
Observe o evento enquanto analisa a página Inventário de Eventos
 a| 
Selecione o evento para ir diretamente para a página de detalhes do evento.

|===
. Se o evento tiver cruzado um limite definido pelo sistema, siga as ações sugeridas na IU para solucionar o problema.
. Se o evento tiver atravessado um limite definido pelo usuário, analise o evento para determinar se você precisa agir.
. Se o problema persistir, verifique as seguintes definições:
+
** Definições de protocolo no sistema de armazenamento
** Configurações de rede em qualquer Ethernet ou switch de malha
** Definições de rede no sistema de armazenamento
** Layout de disco e métricas agregadas no sistema de storage


. Se o problema persistir, contacte o suporte técnico para obter assistência.

