---
permalink: performance-admin/policy-group-assignment-restrictions.html 
sidebar: sidebar 
keywords: use, adaptive, qos, policy, groups 
summary: Você pode usar um grupo de políticas de QoS adaptável para escalar automaticamente um limite de taxa de transferência ou um tamanho do chão ao volume, mantendo a proporção de IOPS para TBs|GBs conforme o tamanho do volume muda. Essa é uma vantagem significativa quando você gerencia centenas ou milhares de workloads em uma implantação grande. 
---
= Restrições de atribuição de grupo de política de QoS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.18.1, é possível usar políticas de QoS aninhadas, que permitem atribuir grupos de políticas tanto ao objeto que as contém, como uma SVM, quanto ao seu objeto filho, como um volume.  Em um ambiente multi-inquilino, as políticas de QoS aninhadas permitem que os administradores subdividam os limites de QoS em SVMs entre os volumes e qtrees dentro da SVM, e que forneçam a capacidade de equilibrar os recursos de armazenamento em ambientes de computação, além de permitir a priorização de cargas de trabalho críticas.

Políticas de QoS aninhadas são suportadas para os seguintes pares de objetos:

* SVMs e volumes FlexVol ou FlexGroup contidos pela SVM.
* Volumes FlexVol ou FlexGroup e qtrees dentro dos volumes.


Para políticas de QoS aninhadas, utiliza-se a política aplicável mais restritiva.

A tabela a seguir lista as restrições.

|===
| Se você atribuir... | Então você não poderá atribuir a um grupo de políticas... 


 a| 
SVM em um grupo de políticas
 a| 
Quaisquer objetos de armazenamento contidos pela SVM.


NOTE: Se você estiver executando o ONTAP 9.18.1, os volumes FlexVol e FlexGroup contidos em SVMs _podem_ ser atribuídos a um grupo de políticas.



 a| 
Volume para um grupo de políticas
 a| 
A SVM que contém o volume ou quaisquer LUNs filhos.


NOTE: Se você estiver executando o ONTAP 9.18.1 ou posterior, o SVM que contém o volume _pode_ ser atribuído a um grupo de políticas.  Além disso, é possível atribuir qtrees em volumes FlexVol ou FlexGroup .



 a| 
LUN para um grupo de políticas
 a| 
O volume ou SVM que contém os LUNs



 a| 
Arquivo para um grupo de políticas
 a| 
O volume ou SVM que contém o arquivo

|===