---
permalink: performance-admin/set-throughput-ceiling-qos-task.html 
sidebar: sidebar 
keywords: setting, throughput, ceiling, qos 
summary: Um limite máximo de QoS ou um teto de throughput garante que o throughput para uma carga de trabalho não exceda um número máximo de IOPS ou MBps, ou IOPS e MBps independentemente de cargas de trabalho concorrentes. Defina um teto de throughput para evitar que cargas de trabalho menos críticas consumam recursos de desempenho excessivos e degradem o desempenho de cargas de trabalho mais críticas 
---
= Defina um limite de taxa de transferência com grupos de políticas de QoS do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um limite máximo de QoS ou teto de throughput garante que o throughput para uma carga de trabalho não exceda um número máximo de IOPS ou MBps, ou IOPS e MBps, independentemente de cargas de trabalho concorrentes. Defina um teto de throughput para evitar que cargas de trabalho menos críticas consumam recursos de desempenho excessivos e degradem o desempenho de cargas de trabalho mais críticas.

Você pode especificar o limite de throughput ao criar um grupo de políticas de QoS ou pode esperar até monitorar suas cargas de trabalho para especificá-lo.

link:guarantee-throughput-qos-task.html["Saiba mais sobre limites de throughput"].

.Antes de começar
* Você precisa ser um administrador de cluster para criar um grupo de políticas e aplicá-lo a uma SVM.


.Sobre esta tarefa
* Os grupos de políticas de QoS adaptativas e não adaptativas são ativados automaticamente para aumentar temporariamente o limite de throughput de uma carga de trabalho em 50% por 1 segundo para responder a demandas de curto prazo por maior desempenho por padrão. A partir do ONTAP 9.19.1, é possível modificar essas configurações padrão. No ONTAP 9.18.1 e anteriores, essas configurações não podem ser alteradas.
+
Utilize as seguintes opções para modificar as configurações padrão:

+
[cols="3"]
|===
| Opção | Descrição | Predefinição 


 a| 
`burst-percent`
| Aumento percentual da taxa de transferência | 50% 


 a| 
`burst duration`
| Duração do aumento da taxa de transferência em segundos | 1 segundo 


 a| 
`burst-iops`
| Número máximo de IOPS acima do limite de taxa de transferência para a duração de rajada especificada | 0 
|===
* Você pode usar um grupo de políticas de QoS _não compartilhado_ para especificar que o limite de throughput definido se aplica a cada carga de trabalho membro individualmente. Caso contrário, o grupo de políticas é _compartilhado_: o throughput total para as cargas de trabalho atribuídas ao grupo de políticas não pode exceder o limite especificado.
+
Defina `-is-shared=false` para que o `qos policy-group create` comando especifique um grupo de políticas não compartilhado.

* Você pode especificar o limite de taxa de transferência para o limite máximo em IOPS, MB/s ou IOPS, MB/s. Se você especificar IOPS e MB/s, qualquer limite atingido primeiro será aplicado.
+
[NOTE]
====
Se você definir um teto e um piso para a mesma carga de trabalho, poderá especificar o limite de taxa de transferência para o limite máximo apenas em IOPS.

====
* Um objeto de storage que esteja sujeito a um limite de QoS precisa estar contido pelo SVM a que o grupo de políticas pertence. Vários grupos de políticas podem pertencer ao mesmo SVM.
* Não é possível atribuir um objeto de armazenamento a um grupo de políticas se o objeto que contém ou os objetos filho pertencerem ao grupo de políticas.
* É uma prática recomendada de QoS aplicar um grupo de políticas ao mesmo tipo de objetos de storage.


.Passos
. Criar um grupo de políticas:
+
[source, cli]
----
qos policy-group create -policy-group <policy_group> -vserver <SVM> -max-throughput <number_of_iops_|Mb/S|iops,Mb/S> -is-shared <true|false>
----
+
Saiba mais sobre `qos policy-group create` o link:https://docs.netapp.com/us-en/ontap-cli/qos-policy-group-create.html["Referência do comando ONTAP"^]na .

+
Você pode usar o `qos policy-group modify` comando para ajustar os tetos de taxa de transferência.

+
O exemplo a seguir cria o grupo de políticas compartilhadas `pg-vs1` com uma taxa de transferência máxima de 5.000 IOPS:

+
[listing]
----
cluster1::> qos policy-group create -policy-group pg-vs1 -vserver vs1 -max-throughput 5000iops -is-shared true
----
+
O exemplo a seguir cria o grupo de políticas não compartilhadas `pg-vs3` com uma taxa de transferência máxima de 100 IOPS e 400 Kb/S:

+
[listing]
----
cluster1::> qos policy-group create -policy-group pg-vs3 -vserver vs3 -max-throughput 100iops,400KB/s -is-shared false
----
+
O exemplo a seguir cria o grupo de políticas não compartilhado `pg-vs4` sem limite de taxa de transferência:

+
[listing]
----
cluster1::> qos policy-group create -policy-group pg-vs4 -vserver vs4 -is-shared false
----
+
Saiba mais sobre `qos policy-group modify` o link:https://docs.netapp.com/us-en/ontap-cli/qos-policy-group-modify.html["Referência do comando ONTAP"^]na .

. Aplique um grupo de políticas a um SVM, arquivo, volume ou LUN:
+
[source, cli]
----
vserver create -vserver <SVM> -qos-policy-group <policy_group>
----
+
O exemplo a seguir aplica o grupo de políticas `pg-vs1` ao SVM `vs1`:

+
[listing]
----
cluster1::> vserver create -vserver vs1 -qos-policy-group pg-vs1
----
+
Os exemplos a seguir aplicam o grupo de políticas `pg-app` aos volumes `app1` e `app2`:

+
[listing]
----
cluster1::> volume create -vserver vs2 -volume app1 -aggregate aggr1 -qos-policy-group pg-app
----
+
[listing]
----
cluster1::> volume create -vserver vs2 -volume app2 -aggregate aggr1 -qos-policy-group pg-app
----
. Monitorar o desempenho do grupo de políticas:
+
[source, cli]
----
qos statistics performance show
----
+
Saiba mais sobre `qos statistics performance show` o link:https://docs.netapp.com/us-en/ontap-cli/qos-statistics-performance-show.html["Referência do comando ONTAP"^]na .

+
[NOTE]
====
Monitore o desempenho do cluster. Não use uma ferramenta no host para monitorar o desempenho.

====
+
O exemplo a seguir mostra o desempenho do grupo de políticas:

+
[listing]
----
cluster1::> qos statistics performance show
Policy Group           IOPS      Throughput   Latency
-------------------- -------- --------------- ----------
-total-                 12316       47.76MB/s  1264.00us
pg_vs1                   5008       19.56MB/s     2.45ms
_System-Best-Effort        62       13.36KB/s     4.13ms
_System-Background         30           0KB/s        0ms
----
. Monitorar a performance do workload:
+
[source, cli]
----
qos statistics workload performance show
----
+
[NOTE]
====
Monitore o desempenho do cluster. Não use uma ferramenta no host para monitorar o desempenho.

====
+
O exemplo a seguir mostra o desempenho da carga de trabalho:

+
[listing]
----
cluster1::> qos statistics workload performance show
Workload          ID     IOPS      Throughput    Latency
--------------- ------ -------- ---------------- ----------
-total-              -    12320        47.84MB/s  1215.00us
app1-wid7967      7967     7219        28.20MB/s   319.00us
vs1-wid12279     12279     5026        19.63MB/s     2.52ms
_USERSPACE_APPS     14       55        10.92KB/s   236.00us
_Scan_Backgro..   5688       20            0KB/s        0ms
----
+
Segue abaixo um exemplo de saída para uma carga de trabalho com max-throughput definido em 2000 IOPS e burst-percent definido em 25 para uma duração de burst de 5 segundos.

+
[listing]
----
cluster1::> qos statistics workload performance show -workload test_vol_nfs_pct25-wid54260

Workload	                ID	    IOPS
--------------------------- -----   ----
test_vol_nfs_pct25-wid54260	54260	2564
-total-	-	                        3704
test_vol_nfs_pct25-wid54260	54260	2527
-total-	-	                        3105
test_vol_nfs_pct25-wid54260	54260	2550
-total-	-	                        3445
test_vol_nfs_pct25-wid54260	54260	2476
-total-	-	                        3460
test_vol_nfs_pct25-wid54260	54260	2479
-total-	-	                        3511
test_vol_nfs_pct25-wid54260	54260	1996
-total-	-	                        2197
test_vol_nfs_pct25-wid54260	54260	2068
-total-	-	                        2057
test_vol_nfs_pct25-wid54260	54260	2087
-total-	-	                        3119

----
+
Saiba mais sobre `qos statistics workload performance show` o link:https://docs.netapp.com/us-en/ontap-cli/qos-statistics-workload-performance-show.html["Referência do comando ONTAP"^]na .

+
Você pode usar o  `qos statistics workload latency show` comando para visualizar estatísticas detalhadas de latência para cargas de trabalho de QoS.

+
Saiba mais sobre  `qos statistics workload latency show` na link:https://docs.netapp.com/us-en/ontap-cli/qos-statistics-workload-latency-show.html["Referência do comando ONTAP"^].


