---
permalink: performance-admin/verify-environment-supported-task.html 
sidebar: sidebar 
keywords: verify, vmware, environment, supported 
summary: Para instalar o Active IQ Unified Manager com êxito, você deve verificar se o ambiente VMware atende aos requisitos necessários. 
---
= Verifique se seu ambiente VMware é compatível
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para instalar o Active IQ Unified Manager com êxito, você deve verificar se o ambiente VMware atende aos requisitos necessários.

.Passos
. Verifique se sua infraestrutura VMware atende aos requisitos de dimensionamento para a instalação do Unified Manager.
. Vá para a https://mysupport.netapp.com/matrix["Matriz de interoperabilidade"^] para verificar se você tem uma combinação suportada dos seguintes componentes:
+
** Versão de ONTAP
** Versão do sistema operacional ESXi
** Versão do VMware vCenter Server
** Versão do VMware Tools
** Tipo e versão do navegador


+
[NOTE]
====
A Matriz de interoperabilidade lista as configurações suportadas do Unified Manager.

====
. Clique no nome da configuração selecionada.
+
Os detalhes dessa configuração são exibidos na janela Detalhes da configuração.

. Revise as informações nas guias a seguir:
+
** Notas
+
Lista alertas importantes e informações específicas à sua configuração.

** Políticas e Diretrizes
+
Fornece diretrizes gerais para todas as configurações.




