---
permalink: performance-admin/weekly-monthly-performance-trends-identify-issues-task.html 
sidebar: sidebar 
keywords: Use, weekly, monthly, performance, trends, identify, issues 
summary: Identificar tendências de desempenho pode ajudá-lo a identificar se o cluster está sendo usado em excesso ou subusado analisando a latência do volume. Você pode usar etapas semelhantes para identificar gargalos de CPU, rede ou outros sistemas. 
---
= Use as tendências de desempenho semanais e mensais do ONTAP Active IQ Unified Manager para identificar problemas de desempenho
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Identificar tendências de desempenho pode ajudá-lo a identificar se o cluster está sendo usado em excesso ou subusado analisando a latência do volume. Você pode usar etapas semelhantes para identificar gargalos de CPU, rede ou outros sistemas.

.Passos
. Localize o volume que você suspeita estar sendo subutilizado ou sobreusado.
. Na guia *Detalhes do volume*, clique em *30 d* para exibir os dados históricos.
. No menu suspenso "dividir dados por", selecione *latência* e clique em *Enviar*.
. Desmarque *Aggregate* no gráfico de comparação de componentes de cluster e compare a latência do cluster com o gráfico de latência de volume.
. Selecione *agregar* e desmarque todos os outros componentes no gráfico de comparação de componentes de cluster e, em seguida, compare a latência agregada com o gráfico de latência de volume.
. Compare o gráfico de latência de leitura/gravação com o gráfico de latência de volume.
. Determinar se os workloads de aplicações cliente causaram uma contenção de workload e rebalancear os workloads conforme necessário.
. Determine se o agregado é usado demais e cause contenção e rebalancear os workloads conforme necessário.

