---
permalink: peering/configure-intercluster-lifs-use-dedicated-ports-task.html 
sidebar: sidebar 
keywords: configure, intercluster, lifs, dedicated, ports 
summary: Você pode configurar LIFs entre clusters em portas dedicadas. Isso normalmente aumenta a largura de banda disponível para o tráfego de replicação. 
---
= Configurar LIFs entre clusters em portas dedicadas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar LIFs entre clusters em portas dedicadas. Isso normalmente aumenta a largura de banda disponível para o tráfego de replicação.

.Passos
. Liste as portas no cluster:
+
`network port show`

+
Para obter a sintaxe completa do comando, consulte a página man.

+
O exemplo a seguir mostra as portas de rede no `cluster01`:

+
[listing]
----

cluster01::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
cluster01-01
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
       e0e       Default      Default          up     1500   auto/1000
       e0f       Default      Default          up     1500   auto/1000
cluster01-02
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
       e0e       Default      Default          up     1500   auto/1000
       e0f       Default      Default          up     1500   auto/1000
----
. Determine quais portas estão disponíveis para se dedicar à comunicação entre clusters:
+
`network interface show -fields home-port,curr-port`

+
Para obter a sintaxe completa do comando, consulte a página man.

+
O exemplo a seguir mostra que portas `e0e` e `e0f` não foram atribuídas LIFs:

+
[listing]
----

cluster01::> network interface show -fields home-port,curr-port
vserver lif                  home-port curr-port
------- -------------------- --------- ---------
Cluster cluster01-01_clus1   e0a       e0a
Cluster cluster01-01_clus2   e0b       e0b
Cluster cluster01-02_clus1   e0a       e0a
Cluster cluster01-02_clus2   e0b       e0b
cluster01
        cluster_mgmt         e0c       e0c
cluster01
        cluster01-01_mgmt1   e0c       e0c
cluster01
        cluster01-02_mgmt1   e0c       e0c
----
. Crie um grupo de failover para as portas dedicadas:
+
`network interface failover-groups create -vserver _system_SVM_ -failover-group _failover_group_ -targets _physical _or_logical_ports_`

+
O exemplo a seguir atribui portas `e0e` e `e0f` ao grupo de failover `intercluster01` no SVM do sistema `cluster01` :

+
[listing]
----
cluster01::> network interface failover-groups create -vserver cluster01 -failover-group
intercluster01 -targets
cluster01-01:e0e,cluster01-01:e0f,cluster01-02:e0e,cluster01-02:e0f
----
. Verifique se o grupo de failover foi criado:
+
`network interface failover-groups show`

+
Para obter a sintaxe completa do comando, consulte a página man.

+
[listing]
----
cluster01::> network interface failover-groups show
                                  Failover
Vserver          Group            Targets
---------------- ---------------- --------------------------------------------
Cluster
                 Cluster
                                  cluster01-01:e0a, cluster01-01:e0b,
                                  cluster01-02:e0a, cluster01-02:e0b
cluster01
                 Default
                                  cluster01-01:e0c, cluster01-01:e0d,
                                  cluster01-02:e0c, cluster01-02:e0d,
                                  cluster01-01:e0e, cluster01-01:e0f
                                  cluster01-02:e0e, cluster01-02:e0f
                 intercluster01
                                  cluster01-01:e0e, cluster01-01:e0f
                                  cluster01-02:e0e, cluster01-02:e0f
----
. Crie LIFs entre clusters no sistema e atribua-os ao grupo de failover.
+
|===
| Opção | Descrição 


 a| 
*Em ONTAP 9.6 e posteriores:*
 a| 
`network interface create -vserver _system_SVM_ -lif _LIF_name_ -service-policy default-intercluster -home-node _node_ -home- port _port_ -address _port_IP_ -netmask _netmask_ -failover-group _failover_group_`



 a| 
*Em ONTAP 9.5 e anteriores:*
 a| 
`network interface create -vserver _system_SVM_ -lif _LIF_name_ -role intercluster -home-node _node_ -home-port _port_ -address _port_IP_ -netmask _netmask_ -failover-group _failover_group_`

|===
+
Para obter a sintaxe completa do comando, consulte a página man.

+
O exemplo a seguir cria LIFs entre clusters `cluster01_icl01` e `cluster01_icl02` no grupo failover `intercluster01` :

+
[listing]
----
cluster01::> network interface create -vserver cluster01 -lif cluster01_icl01 -service-
policy default-intercluster -home-node cluster01-01 -home-port e0e -address 192.168.1.201
-netmask 255.255.255.0 -failover-group intercluster01

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl02 -service-
policy default-intercluster -home-node cluster01-02 -home-port e0e -address 192.168.1.202
-netmask 255.255.255.0 -failover-group intercluster01
----
. Verifique se as LIFs entre clusters foram criadas:
+
|===
| Opção | Descrição 


 a| 
*Em ONTAP 9.6 e posteriores:*
 a| 
`network interface show -service-policy default-intercluster`



 a| 
*Em ONTAP 9.5 e anteriores:*
 a| 
`network interface show -role intercluster`

|===
+
Para obter a sintaxe completa do comando, consulte a página man.

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster01
            cluster01_icl01
                       up/up      192.168.1.201/24   cluster01-01  e0e     true
            cluster01_icl02
                       up/up      192.168.1.202/24   cluster01-02  e0f     true
----
. Verifique se as LIFs entre clusters são redundantes:
+
|===
| Opção | Descrição 


 a| 
*Em ONTAP 9.6 e posteriores:*
 a| 
`network interface show -service-policy default-intercluster -failover`



 a| 
*Em ONTAP 9.5 e anteriores:*
 a| 
`network interface show -role intercluster -failover`

|===
+
Para obter a sintaxe completa do comando, consulte a página man.

+
O exemplo a seguir mostra que os LIFs entre clusters `cluster01_icl01` e `cluster01_icl02` a porta SVM``e0e`` farão failover para a `e0f` porta.

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster –failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- --------
cluster01
         cluster01_icl01 cluster01-01:e0e   local-only      intercluster01
                            Failover Targets:  cluster01-01:e0e,
                                               cluster01-01:e0f
         cluster01_icl02 cluster01-02:e0e   local-only      intercluster01
                            Failover Targets:  cluster01-02:e0e,
                                               cluster01-02:e0f
----

