---
permalink: peering/shared-dedicated-ports-intercluster-concept.html 
sidebar: sidebar 
keywords: use, shared, dedicated, ports, network, bandwidth, replication, interval, availability 
summary: Você pode usar portas dedicadas para comunicação entre clusters ou compartilhar portas usadas pela rede de dados. Ao decidir se deseja compartilhar portas, você precisa considerar a largura de banda da rede, o intervalo de replicação e a disponibilidade da porta. 
---
= Use portas ONTAP compartilhadas ou dedicadas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar portas dedicadas para comunicação entre clusters ou compartilhar portas usadas pela rede de dados. Ao decidir se deseja compartilhar portas, você precisa considerar a largura de banda da rede, o intervalo de replicação e a disponibilidade da porta.

[NOTE]
====
Você pode compartilhar portas em um cluster com peered enquanto usa portas dedicadas no outro.

====


== Largura de banda da rede

Se você tiver uma rede de alta velocidade, como 10 GbE, talvez tenha largura de banda local suficiente para executar a replicação usando as mesmas portas de 10 GbE usadas para acesso aos dados.

Mesmo assim, você deve comparar a largura de banda da WAN disponível com a largura de banda da LAN. Se a largura de banda da WAN disponível for significativamente menor que 10 GbE, talvez seja necessário usar portas dedicadas.

[TIP]
====
A única exceção a essa regra pode ser quando todos ou muitos nós no cluster replicarem dados, caso em que a utilização da largura de banda é normalmente espalhada pelos nós.

====
Se você não estiver usando portas dedicadas, o tamanho máximo da unidade de transmissão (MTU) da rede de replicação geralmente deve ser o mesmo que o tamanho da MTU da rede de dados.



== Intervalo de replicação

Se a replicação ocorrer em horas fora do pico, você poderá usar portas de dados para replicação mesmo sem uma conexão LAN de 10 GbE.

Se a replicação ocorrer durante o horário comercial normal, você precisa considerar a quantidade de dados que serão replicados e se ela precisará de tanta largura de banda que poderia causar contenção com protocolos de dados. Se a utilização da rede por protocolos de dados (SMB, NFS, iSCSI) for superior a 50%, deverá utilizar portas dedicadas para comunicação entre clusters, para permitir uma performance não degradada se ocorrer failover de nó.



== Disponibilidade da porta

Se você determinar que o tráfego de replicação está interferindo no tráfego de dados, poderá migrar LIFs para qualquer outra porta compartilhada com capacidade para clusters no mesmo nó.

Você também pode dedicar portas VLAN para replicação. A largura de banda da porta é compartilhada entre todas as VLANs e a porta base.
