---
permalink: san-admin/access-read-only-lun-copy-backup-vault-task.html 
sidebar: sidebar 
keywords: access, read-only, lun, copy, snapvault, backup 
summary: Você pode acessar uma cópia somente leitura de um LUN a partir do snapshot mais recente em um backup do SnapVault. O ID do LUN, o caminho e o número de série são diferentes do LUN de origem e devem primeiro ser mapeados. Reservas persistentes, mapeamentos de LUN e grupos não são replicados para o volume secundário do SnapVault. 
---
= Acesse uma cópia LUN somente leitura a partir de um backup do SnapVault
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode acessar uma cópia somente leitura de um LUN a partir do snapshot mais recente em um backup do SnapVault. O ID do LUN, o caminho e o número de série são diferentes do LUN de origem e devem primeiro ser mapeados. Reservas persistentes, mapeamentos de LUN e grupos não são replicados para o volume secundário do SnapVault.

.Antes de começar
* A relação SnapVault deve ser inicializada e o instantâneo mais recente no volume secundário SnapVault deve conter o LUN desejado.
* A máquina virtual de storage (SVM) que contém o backup do SnapVault deve ter uma ou mais LIFs com o protocolo SAN desejado acessível a partir do host usado para acessar a cópia LUN.
* Se você planeja acessar cópias LUN diretamente do volume secundário do SnapVault, crie seus grupos no SnapVault SVM com antecedência.
+
Você pode acessar um LUN diretamente do volume secundário do SnapVault sem precisar primeiro restaurar ou clonar o volume que contém o LUN.



.Sobre esta tarefa
Se um novo snapshot for adicionado ao volume secundário do SnapVault enquanto você tiver um LUN mapeado de um snapshot anterior, o conteúdo do LUN mapeado será alterado. O LUN ainda é mapeado com os mesmos identificadores, mas os dados são retirados do novo snapshot. Se o tamanho do LUN mudar, alguns hosts detetarão automaticamente a alteração de tamanho; os hosts do Windows exigem uma nova varredura de disco para pegar qualquer alteração de tamanho.

.Passos
. Execute o `lun show` comando para listar os LUNs disponíveis no volume secundário do SnapVault.
+
Neste exemplo, você pode ver os LUNs originais no volume primário srcvolA e as cópias no volume secundário do SnapVault dstvolB:

+
[listing]
----
cluster::> lun show

Vserver   Path                State   Mapped   Type          Size
--------  ------------------  ------  -------  --------      -------
vserverA  /vol/srcvolA/lun_A  online  mapped   windows  300.0GB
vserverA  /vol/srcvolA/lun_B  online  mapped   windows  300.0GB
vserverA  /vol/srcvolA/lun_C  online  mapped   windows  300.0GB
vserverB  /vol/dstvolB/lun_A  online  unmapped windows  300.0GB
vserverB  /vol/dstvolB/lun_B  online  unmapped windows  300.0GB
vserverB  /vol/dstvolB/lun_C  online  unmapped windows  300.0GB

6 entries were displayed.
----
+
Saiba mais sobre `lun show` o link:https://docs.netapp.com/us-en/ontap-cli/lun-show.html["Referência do comando ONTAP"^]na .

. Se o igrop para o host desejado ainda não existir no SVM que contém o volume secundário do SnapVault, execute o `igroup create` comando para criar um igrop.
+
Este comando cria um grupo para um host do Windows que usa o protocolo iSCSI:

+
[listing]
----
cluster::> igroup create -vserver vserverB -igroup temp_igroup
  -protocol iscsi -ostype windows
  -initiator iqn.1991-05.com.microsoft:hostA
----
. Execute o `lun mapping create` comando para mapear a cópia LUN desejada para o igroup.
+
[listing]
----
cluster::> lun mapping create -vserver vserverB -path /vol/dstvolB/lun_A
  -igroup temp_igroup
----
+
Saiba mais sobre `lun mapping create` o link:https://docs.netapp.com/us-en/ontap-cli/lun-mapping-create.html["Referência do comando ONTAP"^]na .

. Conete o host ao LUN e acesse o conteúdo do LUN conforme desejado.

