---
permalink: san-admin/calculate-rate-data-growth-luns-task.html 
sidebar: sidebar 
keywords: calculate, rate, data, growth, luns 
summary: Você precisa saber a taxa com que seus dados LUN estão crescendo ao longo do tempo para determinar se você deve usar LUNs com espaço reservado ou LUNs não reservados. 
---
= Calcule a taxa de crescimento de dados para LUNs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você precisa saber a taxa com que seus dados LUN estão crescendo ao longo do tempo para determinar se você deve usar LUNs com espaço reservado ou LUNs não reservados.

.Sobre esta tarefa
Se você tiver uma taxa consistente de crescimento de dados, as LUNs com espaço reservado podem ser a melhor opção para você. Se você tiver uma taxa baixa de crescimento de dados, considere LUNs não reservados para espaço.

Você pode usar ferramentas como o OnCommand Insight para calcular a taxa de crescimento de dados ou calculá-la manualmente. As etapas a seguir são para cálculo manual.

.Passos
. Configure um LUN com espaço reservado.
. Monitorize os dados no LUN durante um período de tempo definido, como uma semana.
+
Certifique-se de que seu período de monitoramento é longo o suficiente para formar uma amostra representativa de aumentos regulares no crescimento de dados. Por exemplo, é possível que você tenha uma grande quantidade de crescimento de dados consistentemente no final de cada mês.

. Todos os dias, Registre em GB quanto seus dados crescem.
. No final do período de monitoramento, adicione os totais de cada dia juntos e divida pelo número de dias no período de monitoramento.
+
Este cálculo produz a sua taxa média de crescimento.



.Exemplo
Neste exemplo, você precisa de um LUN de 200 GB. Você decide monitorar o LUN por uma semana e Registrar as seguintes alterações diárias de dados:

* Domingo: 20 GB
* Segunda-feira: 18 GB
* Terça-feira: 17 GB
* Quarta-feira: 20 GB
* Quinta-feira: 20 GB
* Sexta-feira: 23 GB
* Sábado: 22 GB


Neste exemplo, sua taxa de crescimento é (20-18-17-20-20-23-22) / 7 é de 20 GB por dia.
