---
permalink: san-admin/change-cna-uta2-optical-modules-task.html 
sidebar: sidebar 
keywords: change, cna/uta2, target, adapter, optical, modules 
summary: 'Você deve alterar os módulos óticos no adaptador de destino unificado (CNA/UTA2) para suportar o modo de personalidade que você selecionou para o adaptador.' 
---
= Altere os módulos óticos do adaptador de destino CNA/UTA2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve alterar os módulos óticos no adaptador de destino unificado (CNA/UTA2) para suportar o modo de personalidade que você selecionou para o adaptador.

.Passos
. Verifique o SFP atual usado na placa. Em seguida, substitua o SFP atual pelo SFP apropriado para a personalidade preferida (FC ou CNA).
. Remova os módulos óticos atuais do adaptador X1143A-R6.
. Insira os módulos corretos para a ótica do seu modo de personalidade (FC ou CNA) preferido.
. Verifique se você tem o SFP correto instalado:
+
`network fcp adapter show -instance -node -adapter`

+
Módulos SFP suportados e cabos de cobre (Twinax) da marca Cisco estão listados no _Hardware Universe_.



.Informações relacionadas
https://hwu.netapp.com["NetApp Hardware Universe"^]
