---
permalink: san-admin/clone-luns-active-volume-task.html 
sidebar: sidebar 
keywords: clone, luns, active, volume 
summary: É possível criar cópias dos LUNs clonando os LUNs no volume ativo. Esses LUNs FlexClone são cópias legíveis e graváveis dos LUNs originais no volume ativo. 
---
= Clonar LUNs de um volume ativo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível criar cópias dos LUNs clonando os LUNs no volume ativo. Esses LUNs FlexClone são cópias legíveis e graváveis dos LUNs originais no volume ativo.


NOTE: Este procedimento aplica-se aos sistemas FAS, AFF e ASA atuais. Se você tiver um sistema ASA R2 (ASA A1K, ASA A70 ou ASA A90), siga link:https://docs.netapp.com/us-en/asa-r2/manage-data/data-cloning.html["estes passos"^] para clonar dados. Os sistemas ASA R2 fornecem uma experiência de ONTAP simplificada específica para clientes somente SAN.

.O que você vai precisar
Uma licença FlexClone deve ser instalada. Esta licença está incluída no link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"].

.Sobre esta tarefa
Um LUN FlexClone reservado com espaço requer tanto espaço quanto o LUN pai reservado com espaço. Se o LUN FlexClone não tiver espaço reservado, você deve garantir que o volume tenha espaço suficiente para acomodar alterações no LUN FlexClone.

.Passos
. Você deve ter verificado que os LUNs não são mapeados para um iggroup ou são gravados antes de fazer o clone.
. Use o `lun show` comando para verificar se o LUN existe.
+
`lun show -vserver vs1`

+
[listing]
----
Vserver  Path              State     Mapped    Type     Size
-------- ----------------- --------- --------- -------- -------
vs1      /vol/vol1/lun1    online   unmapped  windows  47.07MB
----
. Use o `volume file clone create` comando para criar o LUN FlexClone.
+
`volume file clone create -vserver vs1 -volume vol1 -source-path lun1 -destination-path/lun1_clone`

+
Se você precisar que o LUN FlexClone esteja disponível para exclusão automática, inclua `-autodelete true`o . Se você estiver criando esse LUN FlexClone em um volume usando provisionamento semi-espesso, será necessário habilitar a exclusão automática para todos os LUNs FlexClone.

. Use o `lun show` comando para verificar se você criou um LUN.
+
`lun show -vserver vs1`

+
[listing]
----

Vserver  Path                    State    Mapped   Type     Size
-------- ----------------------- -------- -------- -------- ------
vs1      /vol/volX/lun1          online   unmapped windows  47.07MB
vs1      /vol/volX/lun1_clone    online   unmapped windows  47.07MB
----

