---
permalink: san-admin/commands-manage-fc-adapters-reference.html 
sidebar: sidebar 
keywords: commands, managing, fc, adapters 
summary: Você pode usar comandos FC para gerenciar adaptadores de destino FC, adaptadores iniciadores FC e adaptadores FC integrados para o controlador de storage. Os mesmos comandos são usados para gerenciar adaptadores FC para o protocolo FC e o protocolo FC-NVMe. 
---
= Comandos para gerenciar adaptadores FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar comandos FC para gerenciar adaptadores de destino FC, adaptadores iniciadores FC e adaptadores FC integrados para o controlador de storage. Os mesmos comandos são usados para gerenciar adaptadores FC para o protocolo FC e o protocolo FC-NVMe.

Os comandos do adaptador do iniciador FC funcionam apenas no nível do nó. Você deve usar o `run -node _node_name_` comando antes de usar os comandos do adaptador do iniciador FC.



== Comandos para gerenciar adaptadores de destino FC

[cols="2*"]
|===
| Se você quiser... | Use este comando... 


 a| 
Exibir as informações do adaptador FC em um nó
 a| 
`network fcp adapter show`



 a| 
Modifique os parâmetros do adaptador de destino FC
 a| 
`network fcp adapter modify`



 a| 
Apresentar informações de tráfego do protocolo FC
 a| 
`run -node _node_name_ sysstat -f`



 a| 
Apresentar durante quanto tempo o protocolo FC foi executado
 a| 
`run -node _node_name_ uptime`



 a| 
Exibir configuração e status do adaptador
 a| 
`run -node _node_name_ sysconfig -v _adapter_`



 a| 
Verifique quais placas de expansão estão instaladas e se existem erros de configuração
 a| 
`run -node _node_name_ sysconfig -ac`



 a| 
Exibir uma página de manual para um comando
 a| 
`man _command_name_`

|===


== Comandos para gerenciar adaptadores de iniciador FC

[cols="2*"]
|===
| Se você quiser... | Use este comando... 


 a| 
Exibir informações para todos os iniciadores e seus adaptadores em um nó
 a| 
`run -node _node_name_ storage show adapter`



 a| 
Exibir configuração e status do adaptador
 a| 
`run -node _node_name_ sysconfig -v _adapter_`



 a| 
Verifique quais placas de expansão estão instaladas e se existem erros de configuração
 a| 
`run -node _node_name_ sysconfig -ac`

|===


== Comandos para gerenciar adaptadores FC integrados

[cols="2*"]
|===
| Se você quiser... | Use este comando... 


 a| 
Exibir o status das portas FC integradas
 a| 
`run -node _node_name_ system hardware unified-connect show`

|===
Saiba mais sobre os comandos descritos neste procedimento no link:https://docs.netapp.com/us-en/ontap-cli/["Referência do comando ONTAP"^].
