---
permalink: san-admin/configure-fc-adapters-task.html 
sidebar: sidebar 
keywords: configure, fc, adapters, target, initiator, mode 
summary: Cada porta FC integrada pode ser configurada individualmente como iniciador ou destino. As portas em certos adaptadores FC também podem ser configuradas individualmente como uma porta de destino ou uma porta de iniciador, assim como as portas FC integradas. 
---
= Configurar adaptadores FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada porta FC integrada pode ser configurada individualmente como iniciador ou destino. As portas em certos adaptadores FC também podem ser configuradas individualmente como uma porta de destino ou uma porta de iniciador, assim como as portas FC integradas. Uma lista de adaptadores que podem ser configurados para o modo de destino está disponível no link:https://hwu.netapp.com["NetApp Hardware Universe"^].

O modo de destino é usado para conectar as portas aos iniciadores FC. O modo iniciador é usado para conectar as portas a unidades de fita, bibliotecas de fitas ou armazenamento de terceiros com Importação de LUN Estrangeiro (FLI).

As mesmas etapas são usadas na configuração de adaptadores FC para o protocolo FC e para o protocolo FC-NVMe. No entanto, apenas certos adaptadores FC são compatíveis com FC-NVMe. Consulte link:https://hwu.netapp.com["NetApp Hardware Universe"^] a para obter uma lista de adaptadores compatíveis com o protocolo FC-NVMe.



== Configurar adaptadores FC para o modo de destino

.Passos
. Coloque o adaptador offline:
+
`node run -node _node_name_ storage disable adapter _adapter_name_`

+
Se o adaptador não ficar offline, você também pode remover o cabo da porta apropriada do adaptador no sistema.

. Altere o adaptador do iniciador para o destino:
+
`system hardware unified-connect modify -t target -node _node_name_ adapter _adapter_name_`

. Reinicie o nó que hospeda o adaptador que você alterou.
. Verifique se a porta de destino tem a configuração correta:
+
`network fcp adapter show -node _node_name_`

+
Saiba mais sobre `network fcp adapter show` o link:https://docs.netapp.com/us-en/ontap-cli/network-fcp-adapter-show.html["Referência do comando ONTAP"^]na .

. Coloque o adaptador online:
+
`network fcp adapter modify -node _node_name_ -adapter _adapter_port_ -state up`





== Configurar adaptadores FC para o modo iniciador

.Antes de começar
* Os LIFs no adaptador devem ser removidos de quaisquer conjuntos de portas dos quais sejam membros.
* Todos os LIF de todas as máquinas virtuais de armazenamento (SVM) que usam a porta física a ser modificada devem ser migrados ou destruídos antes de alterar a personalidade da porta física de destino para iniciador.


[NOTE]
====
O NVMe/FC oferece suporte ao modo iniciador.

====
.Passos
. Remova todas as LIFs do adaptador:
+
`network interface delete -vserver _SVM_name_ -lif _LIF_name,LIF_name_`

+
Saiba mais sobre `network interface delete` o link:https://docs.netapp.com/us-en/ontap-cli/network-interface-delete.html["Referência do comando ONTAP"^]na .

. Coloque o adaptador offline:
+
`network fcp adapter modify -node _node_name_ -adapter _adapter_port_ -status-admin down`

+
Se o adaptador não ficar offline, você também pode remover o cabo da porta apropriada do adaptador no sistema.

. Altere o adaptador de destino para iniciador:
+
`system hardware unified-connect modify -t initiator _adapter_port_`

. Reinicie o nó que hospeda o adaptador que você alterou.
. Verifique se as portas FC estão configuradas no estado correto para sua configuração:
+
`system hardware unified-connect show`

. Coloque o adaptador novamente online:
+
`node run -node _node_name_ storage enable adapter _adapter_port_`


