---
permalink: san-admin/control-monitor-io-performance-luns-qos-task.html 
sidebar: sidebar 
keywords: control, monitor, i/o, performance, luns, using, storage qos 
summary: 'Você pode controlar a performance de entrada/saída (e/S) a LUNs atribuindo LUNs a grupos de políticas QoS de storage. Você pode controlar a performance de e/S para garantir que os workloads atinjam objetivos de performance específicos ou para controlar um workload que afeta negativamente outros workloads.' 
---
= Controle e monitore o desempenho de e/S para LUNs com o uso do QoS de storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode controlar a performance de entrada/saída (e/S) a LUNs atribuindo LUNs a grupos de políticas QoS de storage. Você pode controlar a performance de e/S para garantir que os workloads atinjam objetivos de performance específicos ou para controlar um workload que afeta negativamente outros workloads.

.Sobre esta tarefa
Os grupos de políticas aplicam um limite máximo de taxa de transferência (por exemplo, 100 MB/s). Você pode criar um grupo de políticas sem especificar uma taxa de transferência máxima, que permite monitorar o desempenho antes de controlar a carga de trabalho.

Também é possível atribuir máquinas virtuais de storage (SVMs) a volumes e LUNs do FlexVol a grupos de políticas.

Observe os seguintes requisitos sobre a atribuição de um LUN a um grupo de políticas:

* O LUN deve estar contido pelo SVM ao qual o grupo de políticas pertence.
+
Você especifica o SVM ao criar o grupo de políticas.

* Se você atribuir um LUN a um grupo de políticas, não será possível atribuir o volume ou SVM contendo LUN a um grupo de políticas.


Para obter mais informações sobre como usar QoS de armazenamento, consulte link:../system-admin/index.html["Referência de administração do sistema"].

.Passos
. Use o `qos policy-group create` comando para criar um grupo de políticas.
. Use o `lun create` comando ou o `lun modify` comando com o `-qos-policy-group` parâmetro para atribuir um LUN a um grupo de políticas.
. Use os `qos statistics` comandos para exibir dados de desempenho.
. Se necessário, use o `qos policy-group modify` comando para ajustar o limite máximo de taxa de transferência do grupo de políticas.

