---
permalink: san-admin/data-protection-methods-reference.html 
sidebar: sidebar 
keywords: data, protection, methods, san, environments, snapmirror business continuity, smbc, snapshot copy, mirror, update, flexclone luns, license required, snapvault, backups, snapdrive, windows, unix 
summary: Você pode proteger seus dados fazendo cópias deles para que fiquem disponíveis para restauração em caso de exclusão acidental, falhas no aplicativo, corrupção de dados ou desastre. Dependendo das suas necessidades de proteção e backup de dados, o ONTAP oferece uma variedade de métodos que permitem proteger seus dados. 
---
= Visão geral dos métodos de proteção de dados em ambientes SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode proteger seus dados fazendo cópias deles para que fiquem disponíveis para restauração em caso de exclusão acidental, falhas no aplicativo, corrupção de dados ou desastre. Dependendo das suas necessidades de proteção e backup de dados, o ONTAP oferece uma variedade de métodos que permitem proteger seus dados.



== Sincronização ativa do SnapMirror

A partir da disponibilidade geral no ONTAP 9.9,1, fornece objetivo de tempo de recuperação zero (rto zero) ou failover transparente de aplicações (TAF) para permitir o failover automático de aplicações essenciais aos negócios em ambientes SAN. O SnapMirror active Sync requer a instalação do ONTAP Mediator 1,2 em uma configuração com dois clusters AFF ou dois clusters All-Flash SAN Array (ASA).

link:../snapmirror-active-sync/index.html["Sincronização ativa do SnapMirror"^]



== Cópia Snapshot

Permite criar, agendar e manter, manualmente ou automaticamente, vários backups dos LUNs. As cópias snapshot usam apenas uma quantidade mínima de espaço de volume adicional e não têm custo de performance. Se seus dados LUN forem modificados ou excluídos acidentalmente, esses dados poderão ser restaurados de forma fácil e rápida a partir de uma das cópias Snapshot mais recentes.



== FlexClone LUNs (é necessária licença FlexClone)

Fornece cópias graváveis e pontuais de outro LUN em um volume ativo ou em uma cópia Snapshot. Um clone e seu pai podem ser modificados independentemente sem afetar um ao outro.



== SnapRestore (licença necessária)

Permite realizar uma recuperação de dados rápida, com uso eficiente de espaço e sob solicitação de cópias Snapshot em um volume inteiro. Você pode usar o SnapRestore para restaurar um LUN para um estado preservado anterior sem reiniciar o sistema de armazenamento.



== Cópias espelhadas de proteção de dados (é necessária licença SnapMirror)

Fornece recuperação assíncrona de desastres, permitindo que você crie periodicamente cópias Snapshot de dados em seu volume, copie essas cópias Snapshot em uma rede local ou de área ampla para um volume de parceiro, geralmente em outro cluster e retenha essas cópias Snapshot. A cópia espelhada no volume do parceiro fornece disponibilidade e restauração rápidas dos dados a partir do momento da última cópia Snapshot, se os dados no volume de origem estiverem corrompidos ou perdidos.



== Backups do SnapVault (é necessária licença SnapMirror)

Fornece retenção eficiente de backups a longo prazo e storage. Os relacionamentos do SnapVault permitem que você faça backup de cópias Snapshot selecionadas de volumes para um volume de destino e retenha os backups.

Se você conduzir backups em fita e operações de arquivamento, poderá executá-los nos dados que já tiverem backup no volume secundário do SnapVault.



== SnapDrive para Windows ou UNIX (é necessária licença SnapDrive)

Configura o acesso a LUNs, gerencia LUNs e gerencia cópias Snapshot do sistema de storage diretamente de hosts Windows ou UNIX.



== Backup e recuperação em fita nativa

O suporte para a maioria das unidades de fita existentes está incluído no ONTAP, bem como um método para que os fornecedores de fita adicionem suporte dinâmico a novos dispositivos. O ONTAP também suporta o protocolo de fita magnética remota (RMT), permitindo backup e recuperação para qualquer sistema capaz.

.Informações relacionadas
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30050["Documentação do NetApp: SnapDrive para UNIX"^]

http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30049["Documentação do NetApp: SnapDrive para Windows (versões atuais)"^]

link:../tape-backup/index.html["Proteção de dados usando backup em fita"]
