---
permalink: san-admin/define-authentication-method-initiator-task.html 
sidebar: sidebar 
keywords: define, security, policy, method, initiator 
summary: Você pode definir uma lista de iniciadores e seus métodos de autenticação. Você também pode modificar o método de autenticação padrão que se aplica a iniciadores que não possuem um método de autenticação definido pelo usuário. 
---
= Defina um método de política de segurança para um iniciador
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode definir uma lista de iniciadores e seus métodos de autenticação. Você também pode modificar o método de autenticação padrão que se aplica a iniciadores que não possuem um método de autenticação definido pelo usuário.

.Sobre esta tarefa
Você pode gerar senhas exclusivas usando algoritmos de política de segurança no produto ou especificar manualmente as senhas que deseja usar.

[NOTE]
====
Nem todos os iniciadores suportam senhas secretas CHAP hexadecimais.

====
.Passos
. Use o `vserver iscsi security create` comando para criar um método de diretiva de segurança para um iniciador.
+
`vserver iscsi security create -vserver vs2 -initiator iqn.1991-05.com.microsoft:host1 -auth-type CHAP -user-name bob1 -outbound-user-name bob2`

. Siga os comandos do ecrã para adicionar as palavras-passe.
+
Cria um método de política de segurança para o iniciador iqn.1991-05.com.microsoft:host1 com nomes de usuário CHAP de entrada e saída e senhas.



.Informações relacionadas
* xref:iscsi-authentication-concept.adoc[Como a autenticação iSCSI funciona]
* xref:chap-authentication-concept.adoc[Autenticação CHAP]

