---
permalink: san-admin/enable-space-allocation.html 
sidebar: sidebar 
keywords: enable, space allocation, space reclamation, unmap, lun, hole punching, namespace, nvme, san 
summary: Ative a alocação de espaço para permitir que o host e o sistema de armazenamento cooperem no gerenciamento de espaço. 
---
= Ativar a alocação de espaço ONTAP para protocolos SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A alocação de espaço do ONTAP ajuda a impedir que seus LUNs ou namespaces NVMe fiquem offline se eles ficarem sem espaço e permitir que seus hosts SAN recuperem espaço.

O suporte da ONTAP para alocação de espaço é baseado no protocolo SAN e na versão do ONTAP. A partir do ONTAP 9.16.1, a alocação de espaço é habilitada por padrão para protocolos iSCSI, FC e NVMe para LUNs recém-criados e todos os namespaces.

[cols="2,2,4a"]
|===
| Versão de ONTAP | Protocolos | A alocação de espaço é... 


| 9.16.1 ou posterior  a| 
* ISCSI
* FC
* NVMe

 a| 
Habilitado por padrão para LUNs recém-criados e todos os namespaces



.2+| 9.15.1  a| 
* ISCSI
* FC

 a| 
Habilitado por padrão para LUNs recém-criados



| NVMe | Não suportado 


.2+| 9.14.1 e anteriores  a| 
* ISCSI
* FC

 a| 
Desativado por padrão para LUNs recém-criados



| NVMe | Não suportado 
|===
Quando a alocação de espaço está ativada:

* Se um LUN ou namespace ficar sem espaço, o ONTAP se comunica com o host que nenhum espaço livre está disponível para operações de gravação. Como resultado, o LUN ou namespace permanece on-line e as operações de leitura continuam sendo atendidas. Dependendo da configuração do host, o host tenta novamente as operações de gravação até que ele seja bem-sucedido ou o sistema de arquivos do host seja colocado offline. As operações de gravação são retomadas quando espaço livre adicional se torna disponível para o LUN ou namespace.
+
Se a alocação de espaço não estiver ativada, quando um LUN ou namespace ficar sem espaço, todas as operações de e/S falharão e o LUN ou namespace for colocado off-line; o problema de espaço deve ser resolvido para retomar as operações normais. A nova digitalização de dispositivos LUN também pode ser necessária no host para restaurar caminhos e dispositivos para um estado operacional.

* Um host pode executar operações SCSI ou NVMe `UNMAP` (às vezes chamadas `TRIM`). As operações DE DESMAPEAMENTO permitem que um host identifique blocos de dados que não são mais necessários porque eles não contêm mais dados válidos. A identificação normalmente acontece após a exclusão do arquivo. O sistema de armazenamento pode então desalocar esses blocos de dados para que o espaço possa ser consumido em outro lugar. Essa realocação melhora significativamente a eficiência geral de armazenamento, especialmente com sistemas de arquivos que têm alta rotatividade de dados.


.Antes de começar
A ativação da alocação de espaço requer uma configuração de host que possa lidar corretamente com erros de alocação de espaço quando uma gravação não pode ser concluída. A utilização de SCSI ou NVMe `UNMAP` requer uma configuração que possa usar o provisionamento de bloco lógico conforme definido no padrão SCSI SBC-3.

Os hosts a seguir atualmente oferecem suporte a thin Provisioning quando você ativa a alocação de espaço:

* Citrix XenServer 6,5 e posterior
* VMware ESXi 5,0 e posterior
* Kernel Oracle Linux 6,2 UEK e posterior
* Red Hat Enterprise Linux 6,2 e posterior
* SUSE Linux Enterprise Server 11 e posterior
* Solaris 11,1 e posterior
* Windows


.Sobre esta tarefa
Quando você atualiza seu cluster para o ONTAP 9.15,1 ou posterior, a configuração de alocação de espaço para todos os LUNs criados antes da atualização de software permanece a mesma após a atualização, independentemente do tipo de host. Por exemplo, se um LUN foi criado no ONTAP 9.13,1 para um host VMware com alocação de espaço desativada, a alocação de espaço nesse LUN permanecerá desativada após a atualização para o ONTAP 9.15,1.

.Passos
. Ativar alocação de espaço:
+
[source, cli]
----
lun modify -vserver <vserver_name> -volume <volume_name> -lun <lun_name> -space-allocation enabled
----
. Verifique se a alocação de espaço está ativada:
+
[source, cli]
----
lun show -vserver <vserver_name> -volume <volume_name> -lun <lun_name> -fields space-allocation
----
. Verifique se a alocação de espaço está ativada no sistema operacional do host.
+

NOTE: Algumas configurações de host, incluindo algumas versões do VMware ESXi, podem reconhecer automaticamente a alteração de configuração e não exigem intervenção do usuário. Outras configurações podem exigir uma nova digitalização do dispositivo. Alguns sistemas de arquivos e gerenciadores de volume podem exigir configurações específicas adicionais para habilitar a recuperação de espaço usando `SCSI UNMAP`o . A reinstalação de sistemas de arquivos ou uma reinicialização total do sistema operacional pode ser necessária. Consulte a documentação do seu host específico para obter orientação.





== Configuração de host para hosts NVMe posteriores e VMware ESXi 8.x

Se você tiver um host VMware executando o ESXi 8.x ou posterior com o protocolo NVMe, depois de ativar a alocação de espaço no ONTAP, execute as etapas a seguir nos hosts.

.Passos
. No seu anfitrião ESXi, verifique se o DSM está desativado:
+
`esxcfg-advcfg -g /SCSi/NVmeUseDsmTp4040`

+
O valor esperado é 0.

. Ativar o NVMe DSM:
+
`esxcfg-advcfg -s 1 /Scsi/NvmeUseDsmTp4040`

. Verifique se o DSM está ativado:
+
`esxcfg-advcfg -g /SCSi/NVmeUseDsmTp4040`

+
O valor esperado é 1.



.Links relacionados
Saiba mais link:https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["Configuração de host NVMe-of para ESXi 8.x com ONTAP"^]sobre o .
