---
permalink: san-admin/enable-space-allocation.html 
sidebar: sidebar 
keywords: enable, space allocation, space reclamation, unmap, lun 
summary: Ative a alocação de espaço para permitir que o host e o sistema de armazenamento cooperem no gerenciamento de espaço. 
---
= Ativar alocação de espaço para SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ative a alocação de espaço para permitir que seus hosts e sistemas de armazenamento cooperem no gerenciamento de espaço LUN.

A partir do ONTAP 9.15,1, a alocação de espaço é ativada por padrão para LUNs recém-criados. A alocação de espaço foi desativada por padrão em versões anteriores do ONTAP (9.14.1 e anteriores).

A ativação da `space-allocation` configuração permite os seguintes benefícios:

* *O ONTAP pode comunicar a um host que nenhum espaço livre está disponível para prestar serviço de escrita*: Essa comunicação é uma maneira mais graciosa para os hosts lidarem com situações fora do espaço. O LUN permanece on-line, mas não consegue atender a uma e/S de gravação até que o espaço fique disponível. Leia IO ainda pode ser executado. O efeito exato em um sistema operacional do host depende da configuração do host. Em alguns casos, o sistema operacional tenta novamente escrever IO até que ele seja bem-sucedido. Em outros casos, o sistema de arquivos poderia ser colocado offline.
+

NOTE: Se a `space-allocation` configuração não estiver ativada, um LUN entrará em um estado de `space-error` quando atingir um limite de espaço baixo e todas as IO falharem. O LUN precisa ser alterado novamente para `online` o estado depois que o problema de espaço foi resolvido. A nova digitalização de dispositivos LUN também pode ser necessária no host para restaurar caminhos e dispositivos para um estado operacional.

* *Um host pode executar `SCSI UNMAP` (às vezes chamado `TRIM`) operações*: Essas operações permitem que um host identifique blocos de dados em um LUN que não são mais necessários porque eles não contêm mais dados válidos. A identificação normalmente acontece após a exclusão do arquivo. O sistema de armazenamento pode então desalocar esses blocos de dados para que o espaço possa ser consumido em outro lugar. Essa realocação melhora significativamente a eficiência geral de armazenamento, especialmente com sistemas de arquivos que têm alta rotatividade de dados.


.Antes de começar
A ativação da alocação de espaço requer uma configuração de host que possa lidar corretamente com erros de alocação de espaço quando uma gravação não pode ser concluída. A alavancagem `SCSI UNMAP` requer uma configuração que possa usar o provisionamento de blocos lógicos conforme definido no padrão SCSI SBC-3.

Os seguintes hosts atualmente suportam o provisionamento de thin Provisioning SCSI quando você ativa a alocação de espaço:

* Citrix XenServer 6,5 e posterior
* ESXi 5,0 e posterior
* Kernel Oracle Linux 6,2 UEK e posterior
* Red Hat Enterprise Linux 6,2 e posterior
* SUSE Linux Enterprise Server 11 e posterior
* Solaris 11,1 e posterior
* Windows


A alocação de espaço não é compatível com hosts NVMe.

.Sobre esta tarefa
Quando você atualiza seu cluster para o ONTAP 9.15,1, a configuração de alocação de espaço para todos os LUNs criados antes da atualização de software permanece a mesma após a atualização, independentemente do tipo de host. Por exemplo, se um LUN foi criado no ONTAP 9.13,1 para um host VMware com alocação de espaço desativada, a alocação de espaço nesse LUN permanecerá desativada após a atualização para o ONTAP 9.15,1.

.Passos
. Ativar alocação de espaço:
+
[source, cli]
----
lun modify -vserver <vserver_name> -volume <volume_name> -lun <lun_name> -space-allocation enabled
----
. Verifique se a alocação de espaço está ativada:
+
[source, cli]
----
lun show -vserver <vserver_name> -volume <volume_name> -lun <lun_name> -fields space-allocation
----
. Verifique se a alocação de espaço está ativada no sistema operacional do host.
+

NOTE: Algumas configurações de host, em particular o ESX, podem reconhecer automaticamente a alteração de configuração e não exigem intervenção do usuário. Outras configurações podem exigir uma nova digitalização do dispositivo. Alguns sistemas de arquivos e gerenciadores de volume podem exigir configurações específicas adicionais para habilitar a recuperação de espaço usando `SCSI UNMAP`o . A reinstalação de sistemas de arquivos ou uma reinicialização total do sistema operacional pode ser necessária. Consulte a documentação do sistema operacional específico para obter orientação.


