---
permalink: san-admin/flexclone-luns-protect-your-data-concept.html 
sidebar: sidebar 
keywords: use, flexclone, luns, protect, your, data 
summary: Um LUN FlexClone é uma cópia gravável de outro LUN em um volume ativo ou em um instantâneo. O clone e seu pai podem ser modificados independentemente sem afetar um ao outro. 
---
= Proteja seus dados com ONTAP FlexClone LUNs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um LUN FlexClone é uma cópia gravável de outro LUN em um volume ativo ou em um instantâneo. O clone e seu pai podem ser modificados independentemente sem afetar um ao outro.

Você pode usar LUNs do FlexClone para criar várias cópias de leitura/gravação de um LUN.

.Motivos para criar LUNs FlexClone
* Você precisa criar uma cópia temporária de um LUN para fins de teste.
* Você precisa disponibilizar uma cópia de seus dados para usuários adicionais sem dar acesso aos dados de produção.
* Você deseja criar um clone de um banco de dados para operações de manipulação e projeção, preservando os dados originais de uma forma inalterada.
* Você deseja acessar um subconjunto específico dos dados de um LUN (um volume lógico ou sistema de arquivos em um grupo de volume, ou um arquivo ou conjunto de arquivos específico em um sistema de arquivos) e copiá-lo para o LUN original, sem restaurar o restante dos dados no LUN original. Isso funciona em sistemas operacionais que suportam a montagem de um LUN e de um clone do LUN ao mesmo tempo.
* Você precisa de vários hosts de inicialização SAN com o mesmo sistema operacional.


Um LUN FlexClone compartilha espaço inicialmente com seu LUN pai. Por padrão, o LUN FlexClone herda o atributo espaço reservado do LUN pai. Por exemplo, se o LUN pai não for reservado com espaço, o LUN FlexClone também não é reservado com espaço por padrão. No entanto, você pode criar um LUN FlexClone não reservado com espaço a partir de um pai que seja um LUN reservado com espaço.

Quando você clonar um LUN, o compartilhamento de bloco ocorre em segundo plano e não é possível criar um instantâneo de volume até que o compartilhamento de bloco seja concluído.

Tem de configurar o volume para ativar a função de eliminação automática LUN FlexClone com o `volume snapshot autodelete modify` comando. Caso contrário, se você quiser que os LUNs do FlexClone sejam excluídos automaticamente, mas o volume não estiver configurado para a exclusão automática do FlexClone, nenhum dos LUNs do FlexClone será excluído.

Quando você cria um LUN FlexClone, a função de exclusão automática FlexClone LUN é desativada por padrão. Você deve ativá-lo manualmente em cada LUN FlexClone antes que esse LUN FlexClone possa ser excluído automaticamente. Se você estiver usando o provisionamento de volume semi-espesso e quiser a garantia de gravação "melhor esforço" fornecida por essa opção, você deve disponibilizar _All_ FlexClone LUNs para exclusão automática.

[NOTE]
====
Quando você cria um LUN FlexClone a partir de um instantâneo, o LUN é automaticamente dividido do instantâneo usando um processo em segundo plano com uso eficiente de espaço para que o LUN não continue a depender do instantâneo ou consumir nenhum espaço adicional. Se esta divisão em segundo plano não tiver sido concluída e este instantâneo for eliminado automaticamente, esse LUN FlexClone é eliminado mesmo que tenha desativado a função de eliminação automática do FlexClone para esse LUN FlexClone. Depois que a divisão de segundo plano estiver concluída, o LUN FlexClone não será excluído mesmo que esse instantâneo seja excluído.

====
.Informações relacionadas
* link:../volumes/create-flexclone-file-flexclone-lun-task.html["Crie um LUN FlexClone"]
* link:../volumes/configure-flexvol-delete-flexclone-files-luns-task.html["Configure um FlexVol volume para excluir automaticamente LUNs do FlexClone"]
* link:../volumes/prevent-flexclone-file-lun-automatic-deleted-task.html["Impedir que um LUN FlexClone seja excluído automaticamente"]

