---
permalink: san-admin/flexclone-luns-protect-your-data-concept.html 
sidebar: sidebar 
keywords: use, flexclone, luns, protect, your, data 
summary: Um LUN FlexClone é uma cópia gravável e pontual de outro LUN em um volume ativo ou em uma cópia Snapshot. O clone e seu pai podem ser modificados independentemente sem afetar um ao outro. 
---
= Use LUNs FlexClone para proteger a visão geral dos dados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um LUN FlexClone é uma cópia gravável e pontual de outro LUN em um volume ativo ou em uma cópia Snapshot. O clone e seu pai podem ser modificados independentemente sem afetar um ao outro.

Um LUN FlexClone compartilha espaço inicialmente com seu LUN pai. Por padrão, o LUN FlexClone herda o atributo espaço reservado do LUN pai. Por exemplo, se o LUN pai não for reservado com espaço, o LUN FlexClone também não é reservado com espaço por padrão. No entanto, você pode criar um LUN FlexClone não reservado com espaço a partir de um pai que seja um LUN reservado com espaço.

Quando você clonar um LUN, o compartilhamento de bloco ocorre em segundo plano e não é possível criar uma cópia Snapshot de volume até que o compartilhamento de bloco seja concluído.

Tem de configurar o volume para ativar a função de eliminação automática LUN FlexClone com o `volume snapshot autodelete modify` comando. Caso contrário, se você quiser que os LUNs do FlexClone sejam excluídos automaticamente, mas o volume não estiver configurado para a exclusão automática do FlexClone, nenhum dos LUNs do FlexClone será excluído.

Quando você cria um LUN FlexClone, a função de exclusão automática FlexClone LUN é desativada por padrão. Você deve ativá-lo manualmente em cada LUN FlexClone antes que esse LUN FlexClone possa ser excluído automaticamente. Se você estiver usando o provisionamento de volume semi-espesso e quiser a garantia de gravação "melhor esforço" fornecida por essa opção, você deve disponibilizar _All_ FlexClone LUNs para exclusão automática.

[NOTE]
====
Quando você cria um LUN FlexClone a partir de uma cópia Snapshot, o LUN é automaticamente dividido da cópia Snapshot usando um processo em segundo plano com uso eficiente de espaço para que o LUN não continue a depender da cópia Snapshot ou consumir nenhum espaço adicional. Se esta divisão em segundo plano não tiver sido concluída e esta cópia Snapshot for automaticamente eliminada, esse LUN FlexClone será eliminado mesmo que tenha desativado a função de eliminação automática do FlexClone para esse LUN FlexClone. Depois que a divisão em segundo plano estiver concluída, o LUN FlexClone não será excluído mesmo que essa cópia Snapshot seja excluída.

====
.Informações relacionadas
link:../volumes/index.html["Gerenciamento de storage lógico"]
