---
permalink: san-admin/host-side-management-concept.html 
sidebar: sidebar 
keywords: understand, host-side, space, management 
summary: Em um ambiente com provisionamento reduzido, o gerenciamento de espaço no lado do host conclui o processo de gerenciamento de espaço do sistema de storage que foi liberado no sistema de arquivos do host. 
---
= Gerenciamento de espaço no lado do host SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Em um ambiente com provisionamento reduzido, o gerenciamento de espaço no lado do host conclui o processo de gerenciamento de espaço do sistema de storage que foi liberado no sistema de arquivos do host.

Um sistema de arquivos host contém metadados para acompanhar quais blocos estão disponíveis para armazenar novos dados e quais blocos contêm dados válidos que não devem ser sobrescritos. Esses metadados são armazenados no LUN ou namespace. Quando um arquivo é excluído no sistema de arquivos host, os metadados do sistema de arquivos são atualizados para marcar os blocos desse arquivo como espaço livre. O espaço livre total do sistema de arquivos é então recalculado para incluir os blocos recém-liberados. Para o sistema de storage, essas atualizações de metadados não parecem diferentes de quaisquer outras gravações que estejam sendo executadas pelo host. Portanto, o sistema de armazenamento não tem conhecimento de que quaisquer exclusões ocorreram.

Isso cria uma discrepância entre a quantidade de espaço livre relatada pelo host e a quantidade de espaço livre relatada pelo sistema de armazenamento subjacente. Por exemplo, suponha que você tenha um LUN de 200 GB recém-provisionado atribuído ao seu host pelo sistema de armazenamento. Tanto o host quanto o sistema de armazenamento relatam 200 GB de espaço livre. Seu host então grava 100 GB de dados. Nesse ponto, tanto o host quanto o sistema de armazenamento relatam 100 GB de espaço usado e 100 GB de espaço não utilizado.

Em seguida, você exclui 50 GB de dados do seu host. Neste ponto, seu host irá relatar 50 GB de espaço usado e 150 GB de espaço não utilizado. No entanto, seu sistema de armazenamento irá relatar 100 GB de espaço usado e 100 GB de espaço não utilizado.

O gerenciamento de espaço no lado do host usa vários métodos para reconciliar o diferencial de espaço entre o host e o sistema de armazenamento.



== Gerenciamento de host simplificado com o SnapCenter

Você pode usar o software SnapCenter para simplificar algumas tarefas de gerenciamento e proteção de dados associadas ao storage iSCSI e FC. O SnapCenter é um pacote de gerenciamento opcional para hosts Windows e UNIX.

Você pode usar o software SnapCenter para criar facilmente discos virtuais de pools de storage que podem ser distribuídos entre vários sistemas de storage e para automatizar as tarefas de provisionamento de storage e simplificar o processo de criação de snapshots e clones com base em dados de host.

Consulte a documentação do produto NetApp para obter mais informações https://docs.netapp.com/us-en/snapcenter/index.html["SnapCenter"] sobre .

.Links relacionados
link:enable-space-allocation-scsi-thin-provisioned-luns-task.html["Ativar a alocação de espaço ONTAP para protocolos SAN"]
