---
permalink: san-admin/iscsi-authentication-concept.html 
sidebar: sidebar 
keywords: how, iscsi, authentication, works 
summary: Durante a fase inicial de uma sessão iSCSI, o iniciador envia uma solicitação de login ao sistema de armazenamento para iniciar uma sessão iSCSI. O sistema de armazenamento permite ou nega a solicitação de login ou determina que não é necessário fazer login. 
---
= Como a autenticação iSCSI funciona
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durante a fase inicial de uma sessão iSCSI, o iniciador envia uma solicitação de login ao sistema de armazenamento para iniciar uma sessão iSCSI. O sistema de armazenamento permite ou nega a solicitação de login ou determina que não é necessário fazer login.

Os métodos de autenticação iSCSI são:

* Challenge Handshake Authentication Protocol (CHAP) - o iniciador faz login usando um nome de usuário e senha CHAP.
+
Você pode especificar uma senha CHAP ou gerar uma senha secreta hexadecimal. Existem dois tipos de nomes de usuário CHAP e senhas:

+
** Entrada - o sistema de armazenamento autentica o iniciador.
+
As configurações de entrada são necessárias se você estiver usando a autenticação CHAP.

** Outbound -- esta é uma configuração opcional para permitir que o iniciador autentique o sistema de armazenamento.
+
Só pode utilizar as definições de saída se definir um nome de utilizador e uma palavra-passe de entrada no sistema de armazenamento.



* Negar - o iniciador tem acesso negado ao sistema de armazenamento.
* Nenhum - o sistema de storage não requer autenticação para o iniciador.


Pode definir a lista de iniciadores e os respetivos métodos de autenticação. Você também pode definir um método de autenticação padrão que se aplica a iniciadores que não estão nesta lista.

.Informações relacionadas
https://www.netapp.com/pdf.html?item=/media/19668-tr-3441.pdf["Opções de multipathing do Windows com Data ONTAP: Fibre Channel e iSCSI"]
