---
permalink: san-admin/iscsi-endpoint-isolation-concept.html 
sidebar: sidebar 
keywords: iscsi, endpoint, isolation, add, remove, initiator, address, range 
summary: A partir do ONTAP 9.1, os comandos de segurança iSCSI existentes foram melhorados para aceitar um intervalo de endereços IP ou vários endereços IP. 
---
= Isolamento do ponto de extremidade iSCSI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os comandos de segurança iSCSI existentes podem aceitar um intervalo de endereços IP ou vários endereços IP.

Todos os iniciadores iSCSI devem fornecer endereços IP de origem ao estabelecer uma sessão ou conexão com um destino. Essa nova funcionalidade impede que um iniciador faça login no cluster se o endereço IP de origem não for suportado ou desconhecido, fornecendo um esquema de identificação exclusivo. Qualquer iniciador originado de um endereço IP não suportado ou desconhecido terá seu login rejeitado na camada de sessão iSCSI, impedindo que o iniciador acesse qualquer LUN ou volume dentro do cluster.

Implemente essa nova funcionalidade com dois novos comandos para ajudar a gerenciar entradas pré-existentes.



== Adicionar intervalo de endereços do iniciador

Melhore o gerenciamento de segurança do iniciador iSCSI adicionando um intervalo de endereços IP ou vários endereços IP com o `vserver iscsi security add-initiator-address-range` comando.

`cluster1::> vserver iscsi security add-initiator-address-range`



== Remova o intervalo de endereços do iniciador

Remova um intervalo de endereços IP ou vários endereços IP com o `vserver iscsi security remove-initiator-address-range` comando.

`cluster1::> vserver iscsi security remove-initiator-address-range`
