---
permalink: san-admin/lun-san-environments-concept.html 
sidebar: sidebar 
keywords: lun, guidelines, assigning, assign, ids, mapping, map, igroups 
summary: Antes de começar a configurar os LUNs no cluster, é necessário rever as diretrizes de LUN. 
---
= O que saber antes de criar um LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== Por que os tamanhos reais de LUN variam ligeiramente

Você deve estar ciente do seguinte em relação ao tamanho de seus LUNs.

* Quando você cria um LUN , o tamanho real do LUN pode variar ligeiramente com base no tipo de SO do LUN. O tipo de SO LUN não pode ser modificado após a criação do LUN.
* Se você criar um LUN no tamanho máximo de LUN, esteja ciente de que o tamanho real do LUN pode ser um pouco menor. ONTAP arredonda o limite para ser um pouco menos.
* Os metadados para cada LUN requerem aproximadamente 64 KB de espaço no agregado que contém. Ao criar um LUN, você deve garantir que o agregado que contém tenha espaço suficiente para os metadados do LUN. Se o agregado não contiver espaço suficiente para os metadados do LUN, alguns hosts poderão não conseguir acessar o LUN.




== Diretrizes para a atribuição de IDs de LUN

Normalmente, o ID de LUN padrão começa com 0 e é atribuído em incrementos de 1 para cada LUN mapeado adicional. O host associa a ID LUN com o local e o nome do caminho do LUN. O intervalo de números de ID LUN válidos depende do host. Para obter informações detalhadas, consulte a documentação fornecida com seus Utilitários de host.



== Diretrizes para mapeamento de LUNs para grupos

* Você pode mapear um LUN apenas uma vez para um grupo.
* Como prática recomendada, você deve mapear um LUN para apenas um iniciador específico através do grupo.
* Você pode adicionar um único iniciador a vários grupos, mas o iniciador pode ser mapeado para apenas um LUN.
* Não é possível usar o mesmo ID de LUN para dois LUNs mapeados para o mesmo grupo.
* Você deve usar o mesmo tipo de protocolo para grupos e conjuntos de portas.

