---
permalink: san-admin/manage-systems-fc-adapters-concept.html 
sidebar: sidebar 
keywords: manage, systems, fc, adapters 
summary: Os comandos estão disponíveis para gerenciar adaptadores FC integrados e placas adaptadoras FC. Esses comandos podem ser usados para configurar o modo do adaptador, exibir informações do adaptador e alterar a velocidade. 
---
= Gerenciar sistemas com adaptadores FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os comandos estão disponíveis para gerenciar adaptadores FC integrados e placas adaptadoras FC. Esses comandos podem ser usados para configurar o modo do adaptador, exibir informações do adaptador e alterar a velocidade.

A maioria dos sistemas de armazenamento tem adaptadores FC integrados que podem ser configurados como iniciadores ou destinos.  Você também pode usar placas adaptadoras FC configuradas como iniciadores ou alvos.  Os iniciadores se conectam às prateleiras de disco de back-end e possivelmente a matrizes de armazenamento externas.  Os alvos se conectam apenas aos switches FC.  Tanto as portas HBA de destino do FC quanto a velocidade da porta do switch devem ser definidas com o mesmo valor e não devem ser definidas como automáticas.

.Informações relacionadas
link:../san-config/index.html["Configuração SAN"]
