---
permalink: san-admin/manage-nvme-concept.html 
sidebar: sidebar 
keywords: manage, nvme, overview, license 
summary: 'Você pode usar o protocolo NVMe (non-volátil Memory Express) para fornecer storage em um ambiente SAN. O protocolo NVMe é otimizado para performance com storage de estado sólido.' 
---
= Visão geral do NVMe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o protocolo NVMe (non-volátil Memory Express) para fornecer storage em um ambiente SAN. O protocolo NVMe é otimizado para performance com storage de estado sólido.

Para NVMe, os destinos de storage são chamados de namespaces. Um namespace NVMe é uma quantidade de storage não volátil que pode ser formatada em blocos lógicos e apresentada a um host como um dispositivo de bloco padrão. Você cria namespaces e subsistemas e, em seguida, mapeia os namespaces para os subsistemas, semelhante à maneira como os LUNs são provisionados e mapeados para grupos para FC e iSCSI.

Os destinos NVMe são conectados à rede por meio de uma infraestrutura FC padrão usando switches FC ou uma infraestrutura TCP padrão usando switches Ethernet e adaptadores no lado do host.

O suporte a NVMe varia de acordo com a sua versão do ONTAP. link:../nvme/support-limitations.html["Limitações e suporte do NVMe"]Consulte para obter detalhes.



== O que é NVMe

O protocolo não volátil Memory Express (NVMe) é um protocolo de transporte usado para acessar Mídia de storage não volátil.

O NVMe sobre Fabrics (NVMeoF) é uma extensão definida por especificação do NVMe que permite a comunicação baseada em NVMe por conexões que não PCIe. Esta interface permite que gabinetes de armazenamento externos sejam conetados a um servidor.

O NVMe foi desenvolvido para fornecer acesso eficiente a dispositivos de storage criados com memória não volátil, da tecnologia flash às tecnologias de memória persistente e de alta performance. Como tal, ele não tem as mesmas limitações que os protocolos de armazenamento projetados para unidades de disco rígido. Os dispositivos flash e de estado sólido (SSDs) são um tipo de memória não volátil (NVM). NVM é um tipo de memória que mantém seu conteúdo durante uma queda de energia. O NVMe é uma maneira de acessar essa memória.

Os benefícios do NVMe incluem maiores velocidades, produtividade, taxa de transferência e capacidade para transferência de dados. As caraterísticas específicas incluem o seguinte:

* O NVMe foi projetado para ter até 64 mil filas.
+
Cada fila, por sua vez, pode ter até 64 mil comandos simultâneos.

* O NVMe é compatível com vários fornecedores de hardware e software
* O NMVe é mais produtivo com as tecnologias Flash que permitem tempos de resposta mais rápidos
* O NVMe permite várias solicitações de dados para cada "demanda" enviada para o SSD.
+
O NVMe leva menos tempo para decodificar um "request" e não requer bloqueio de threads em um programa multithread.

* O NVMe oferece suporte a funcionalidades que impedem a perda de peso no nível da CPU e permitem escalabilidade massiva à medida que os sistemas se expandem.




== Sobre os namespaces NVMe

Um namespace NVMe é uma quantidade de memória não volátil (NVM) que pode ser formatada em blocos lógicos. Namespaces são usados quando uma máquina virtual de storage é configurada com o protocolo NVMe e são equivalentes a LUNs para protocolos FC e iSCSI.

Um ou mais namespaces são provisionados e conectados a um host NVMe. Cada namespace pode suportar vários tamanhos de bloco.

O protocolo NVMe fornece acesso a namespaces por meio de várias controladoras. Usando drivers NVMe, que são compatíveis com a maioria dos sistemas operacionais, os namespaces de unidade de estado sólido (SSD) aparecem como dispositivos de bloco padrão nos quais sistemas de arquivos e aplicativos podem ser implantados sem qualquer modificação.

Um ID de namespace (NSID) é um identificador usado por um controlador para fornecer acesso a um namespace. Ao definir o NSID para um host ou grupo de hosts, você também configura a acessibilidade a um volume por um host. Um bloco lógico só pode ser mapeado para um único grupo de host de cada vez, e um determinado grupo de host não tem NSIDs duplicados.



== Sobre os subsistemas NVMe

Um subsistema NVMe inclui uma ou mais controladores NVMe, namespaces, portas de subsistema NVM, um meio de storage NVM e uma interface entre a controladora e o meio de storage NVM. Quando você cria um namespace NVMe, por padrão ele não é mapeado para um subsistema. Você também pode optar por mapear um subsistema novo ou existente.

.Informações relacionadas
* Aprenda a link:create-nvme-namespace-subsystem-task.html["Provisionamento de storage NVMe"] usar os sistemas ASA, AFF e FAS
* Saiba mais sobre link:map-nvme-namespace-subsystem-task.html["Mapear um namespace NVMe para um subsistema"]os sistemas ASA AFF e FAS.
* link:https://docs.netapp.com/us-en/ontap-sanhost/["Configurar hosts SAN e clientes em nuvem"^]
* Aprenda a link:https://docs.netapp.com/us-en/asa-r2/manage-data/provision-san-storage.html["Provisionamento de storage SAN"^] usar os sistemas de armazenamento ASA R2 (ASA A1K, ASA A70 ou ASA A90).

