---
permalink: san-admin/manage-lifs-all-san-protocols-concept.html 
sidebar: sidebar 
keywords: manage, lifs, san protocols 
summary: As LIFs estão conectadas aos hosts SAN. Elas podem ser removidas de portsets, movidas para nós diferentes dentro de uma storage virtual machine e excluídas. 
---
= Saiba mais sobre LIFs do ONTAP para ambientes SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os LUNs e namespaces no seu sistema ONTAP estão contidos em máquinas virtuais de armazenamento (SVMs). As interfaces de rede (LIFs) permitem que seus clientes SAN se conectem a uma SVM e acessem os dados nos LUNs e namespaces que ela contém.

* Você deve configurar uma LIF de gerenciamento para cada máquina virtual de storage (SVM) que suporte SAN.
* É possível configurar duas LIFs por nó, uma para cada malha utilizada com FC e para separar as redes Ethernet para iSCSI.
* A conectividade pode ser feita por meio de conexão direta ou uso de switches Ethernet. É necessário configurar as LIFs para ambos os tipos de conectividade.


Aprenda a link:../networking/create_a_lif.html["Crie um LIF"]

.Informações relacionadas
* link:../networking/configure_lifs_cluster_administrators_only_overview.html["Saiba mais sobre a configuração do LIF"]
* link:multipath-automatic-lif-failover-support.html["Saiba mais sobre o suporte para failover automático de LIF em SAN"].

