---
permalink: san-admin/nvme-copy-offload.html 
sidebar: sidebar 
keywords: configure, ports 
summary: O recurso de descarregamento de cópia NVMe permite que um host NVMe transfira as operações de cópia de sua CPU para a CPU do controlador de armazenamento ONTAP . O host pode copiar dados de um namespace NVMe para outro, reservando seus recursos de CPU para cargas de trabalho de aplicativos. 
---
= Saiba mais sobre o descarregamento de cópia NVMe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O recurso de descarregamento de cópia NVMe permite que um host NVMe transfira as operações de cópia de sua CPU para a CPU do controlador de armazenamento ONTAP . O host pode copiar dados de um namespace NVMe para outro, reservando seus recursos de CPU para cargas de trabalho de aplicativos.

Suponha, por exemplo, que você precise reequilibrar suas cargas de trabalho de armazenamento para melhorar a distribuição de desempenho.  Isso requer a migração de dez máquinas virtuais (VMs) contendo 45 namespaces NVMe com um tamanho médio de 500 GB cada.  Isso significa que você precisa copiar cerca de 22,5 TB de dados.  Em vez de usar sua própria CPU para migração de dados, o host pode usar o descarregamento de cópia NVMe para evitar a redução de seus recursos de CPU para cargas de trabalho de aplicativos enquanto os dados estão sendo copiados.



== Suporte e limitações para descarregamento de cópia NVMe

O descarregamento de cópia NVMe é suportado a partir do ONTAP 9.18.1.  O ONTAP não pode iniciar o descarregamento de cópia NVMe; isso deve ser suportado e iniciado pelo host.

As seguintes limitações se aplicam às operações de descarregamento de cópia NVMe com o ONTAP:

* O tamanho máximo suportado para operações de cópia é de 16 MB.
* Os dados só podem ser migrados entre namespaces NVMe dentro do mesmo subsistema.
* Os dados só podem ser migrados entre nós do mesmo par de alta disponibilidade (HA).

