---
permalink: san-admin/register-svm-isns-server-task.html 
sidebar: sidebar 
keywords: register, svm, isns, server 
summary: 'Você pode usar o comando vserver iscsi isns para configurar a máquina virtual de armazenamento (SVM) para se Registrar em um servidor iSNS.' 
---
= Registre o SVM em um servidor iSNS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `vserver iscsi isns` comando para configurar a máquina virtual de armazenamento (SVM) para se Registrar em um servidor iSNS.

.Sobre esta tarefa
O `vserver iscsi isns create` comando configura o SVM para se Registrar no servidor iSNS. O SVM não fornece comandos que permitem configurar ou gerenciar o servidor iSNS. Para gerenciar o servidor iSNS, você pode usar as ferramentas de administração do servidor ou a interface fornecida pelo fornecedor para o servidor iSNS.

.Passos
. No servidor iSNS, certifique-se de que o serviço iSNS está ativo e disponível para serviço.
. Crie o LIF de gerenciamento de SVM em uma porta de dados:
+
`network interface create -vserver _SVM_name_ -lif _lif_name_ -role data -data-protocol none -home-node _home_node_name_ -home-port _home_port_ -address _IP_address_ -netmask _network_mask_`

+
Saiba mais sobre `network interface create` o link:https://docs.netapp.com/us-en/ontap-cli/network-interface-create.html["Referência do comando ONTAP"^]na .

. Crie um serviço iSCSI no SVM se ainda não existir um:
+
`vserver iscsi create -vserver _SVM_name_`

. Verifique se o serviço iSCSI foi criado com sucesso:
+
`iscsi show -vserver _SVM_name_`

. Verifique se existe uma rota padrão para o SVM:
+
`network route show -vserver _SVM_name_`

. Se uma rota padrão não existir para o SVM, crie uma rota padrão:
+
`network route create -vserver _SVM_name_ -destination _destination_ -gateway _gateway_`

. Configure o SVM para se Registrar no serviço iSNS:
+
`vserver iscsi isns create -vserver _SVM_name_ -address _IP_address_`

+
As famílias de endereços IPv4 e IPv6 são apoiadas. A família de endereços do servidor iSNS deve ser a mesma do LIF de gerenciamento do SVM.

+
Por exemplo, você não pode conetar um LIF de gerenciamento de SVM com um endereço IPv4 a um servidor iSNS com um endereço IPv6.

. Verifique se o serviço iSNS está em execução:
+
`vserver iscsi isns show -vserver _SVM_name_`

. Se o serviço iSNS não estiver em execução, inicie-o:
+
`vserver iscsi isns start -vserver _SVM_name_`


