---
permalink: san-admin/resolve-iscsi-error-messages-reference.html 
sidebar: sidebar 
keywords: resolve, iscsi, error messages, storage system 
summary: Há várias mensagens de erro comuns relacionadas ao iSCSI que você pode exibir com o comando event log show. Você precisa saber o que essas mensagens significam e o que você pode fazer para resolver os problemas que elas identificam. 
---
= Resolva mensagens de erro iSCSI no sistema de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Existem várias mensagens de erro comuns relacionadas ao iSCSI que podem ser visualizadas com o `event log show` comando. Você precisa saber o que essas mensagens significam e o que você pode fazer para resolver os problemas que elas identificam.

A tabela a seguir contém as mensagens de erro mais comuns e instruções para resolvê-las:

[cols="3*"]
|===
| Mensagem | Explicação | O que fazer 


 a| 
`ISCSI: network interface identifier disabled for use; incoming connection discarded`
 a| 
O serviço iSCSI não está ativado na interface.
 a| 
Pode utilizar o `iscsi interface enable` comando para ativar o serviço iSCSI na interface. Por exemplo:

`iscsi interface enable -vserver vs1 -lif lif1`



 a| 
`ISCSI: Authentication failed for initiator nodename`
 a| 
O CHAP não está configurado corretamente para o iniciador especificado.
 a| 
Deve verificar as definições CHAP; não pode utilizar o mesmo nome de utilizador e palavra-passe para as definições de entrada e saída no sistema de armazenamento:

* As credenciais de entrada no sistema de storage devem corresponder às credenciais de saída no iniciador.
* As credenciais de saída no sistema de storage devem corresponder às credenciais de entrada no iniciador.


|===