---
permalink: san-admin/restore-all-luns-volume-snapshot-copy-task.html 
sidebar: sidebar 
keywords: restore, all, luns in a volume, from, snapshot copy 
summary: Você pode usar o comando volume snapshot restore para restaurar todos os LUNs em um volume especificado de um snapshot. 
---
= Restaure todos os LUNs em um volume a partir de um snapshot do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar `volume snapshot restore` o comando para restaurar todos os LUNs em um volume especificado a partir de um snapshot.

.Passos
. No host, interrompa todo o acesso do host aos LUNs.
+
Usar o SnapRestore sem interromper todo o acesso do host aos LUNs no volume pode causar corrupção de dados e erros do sistema.

. Desmonte os LUNs nesse host para que o host não possa acessar os LUNs.
. Desmapear os LUNs:
+
[source, cli]
----
lun mapping delete -vserver <SVM_name> -volume <volume_name> -lun <lun_name> -igroup <igroup_name>
----
. Determine o instantâneo para o qual você deseja restaurar o volume:
+
[source, cli]
----
volume snapshot show -vserver <SVM_name> -volume <volume_name>

----
. Altere a configuração de privilégio para avançado:
+
[source, cli]
----
set -privilege advanced
----
. Restaure seus dados:
+
[source, cli]
----
volume snapshot restore -vserver <SVM_name> -volume <volume_name> -snapshot <snapshot_name>
----
. Siga as instruções apresentadas no ecrã.
. Remapear os LUNs:
+
[source, cli]
----
lun mapping create -vserver <SVM_name> -volume <volume_name> -lun <lun_name> -igroup <igroup_name>
----
. Verifique se os LUNs estão online:
+
[source, cli]
----
lun show -vserver <SVM_name> -path <lun_path> -fields state
----
. Se os LUNs não estiverem online, coloque-os online:
+
[source, cli]
----
lun modify -vserver <SVM_name> -path <lun_path> -state online
----
. Altere a configuração de privilégios para admin:
+
[source, cli]
----
set -privilege admin
----
. No host, remonte seus LUNs.
. No host, reinicie o acesso aos LUNs.

