---
permalink: san-admin/restore-single-lun-snapvault-backup-task.html 
sidebar: sidebar 
keywords: restore, single, lun, snapvault backup 
summary: Você pode restaurar um único LUN para um novo local ou para o local original. É possível restaurar a partir de qualquer snapshot no volume secundário do SnapVault. Para restaurar o LUN para o local original, primeiro restaure-o para um novo local e, em seguida, copie-o. 
---
= Restaure um único LUN a partir de um backup do ONTAP SnapVault
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode restaurar um único LUN para um novo local ou para o local original. É possível restaurar a partir de qualquer snapshot no volume secundário do SnapVault. Para restaurar o LUN para o local original, primeiro restaure-o para um novo local e, em seguida, copie-o.

.Antes de começar
* A relação SnapVault deve ser inicializada e o volume secundário SnapVault deve conter um instantâneo apropriado para restaurar.
* A máquina virtual de storage (SVM) que contém o volume secundário do SnapVault deve ter uma ou mais LIFs com o protocolo SAN desejado que podem ser acessados pelo host usado para acessar a cópia LUN.
* Os grupos já devem existir no SnapVault SVM.


.Sobre esta tarefa
O processo inclui a criação de um clone de volume de leitura e gravação a partir de um snapshot no volume secundário do SnapVault. Você pode usar o LUN diretamente do clone ou, opcionalmente, copiar o conteúdo do LUN de volta para o local original do LUN.

O LUN no clone tem um caminho e um número de série diferentes do LUN original. Reservas persistentes não são retidas.

.Passos
. Verifique o volume secundário que contém o backup do SnapVault.
+
[source, cli]
----
snapmirror show
----
+
[listing]
----
cluster::> snapmirror show

Source         Dest     Mirror  Relation  Total             Last
Path     Type  Path     State   Status    Progress  Healthy Updated
-------- ---- --------- ------- --------- --------- ------- -------
vserverA:srcvolA
         XDP  vserverB:dstvolB
                        Snapmirrored
                                Idle       -         true    -
----
. Identifique o instantâneo a partir do qual pretende restaurar o LUN.
+
[source, cli]
----
volume snapshot show
----
+
[listing]
----
cluster::> volume snapshot show

Vserver  Volume  Snapshot               State Size   Total% Used%
-------- ------- ---------------------- ----- ------ ------ -----
vserverB
         dstvolB
                 snap2.2013-02-10_0010  valid  124KB     0%    0%
                 snap1.2013-02-10_0015 valid  112KB     0%    0%
                 snap2.2013-02-11_0010  valid  164KB     0%    0%
----
. Crie um clone de leitura e gravação a partir do instantâneo desejado
+
[source, cli]
----
volume clone create -vserver <SVM_name> -flexclone <flexclone_name> -type <type> -parent-volume <parent_volume_name> -parent-snapshot <snapshot_name>
----
+
O clone de volume é criado no mesmo agregado que o backup do SnapVault. Deve haver espaço suficiente no agregado para armazenar o clone.

+
[listing]
----
cluster::> volume clone create -vserver vserverB
  -flexclone dstvolB_clone -type RW -parent-volume dstvolB
  -parent-snapshot daily.2013-02-10_0010
[Job 108] Job succeeded: Successful
----
. Listar os LUNs no clone de volume.
+
[source, cli]
----
lun show -vserver <SVM_name> -volume <flexclone_volume_name>
----
+
[listing]
----
cluster::> lun show -vserver vserverB -volume dstvolB_clone

Vserver   Path                      State   Mapped   Type
--------- ------------------------  ------- -------- --------
vserverB  /vol/dstvolB_clone/lun_A  online  unmapped windows
vserverB  /vol/dstvolB_clone/lun_B  online  unmapped windows
vserverB  /vol/dstvolB_clone/lun_C  online  unmapped windows

3 entries were displayed.
----
+
Saiba mais sobre `lun show` o link:https://docs.netapp.com/us-en/ontap-cli/lun-show.html["Referência do comando ONTAP"^]na .

. Se o igrop para o host desejado ainda não existir no SVM que contém o backup do SnapVault, crie um igrop.
+
[source, cli]
----
igroup create -vserver <SVM_name> -igroup <igroup_name> -protocol <protocol> -ostype <os_type> -initiator <initiator_name>
----
+
Este exemplo cria um grupo para um host do Windows que usa o protocolo iSCSI:

+
[listing]
----
cluster::> igroup create -vserver vserverB -igroup temp_igroup
  -protocol iscsi -ostype windows
  -initiator iqn.1991-05.com.microsoft:hostA
----
. Mapeie a cópia LUN desejada para o grupo.
+
[source, cli]
----
lun mapping create -vserver <SVM_name> -path <lun_path> -igroup <igroup_name>
----
+
[listing]
----
cluster::> lun mapping create -vserver vserverB
  -path /vol/dstvolB_clone/lun_C -igroup temp_igroup
----
+
Saiba mais sobre `lun mapping create` o link:https://docs.netapp.com/us-en/ontap-cli/lun-mapping-create.html["Referência do comando ONTAP"^]na .

. Conete o host ao LUN e acesse o conteúdo do LUN, conforme desejado.
+
O LUN é leitura-escrita e pode ser usado no lugar do LUN original. Como o número de série do LUN é diferente, o host o interpreta como um LUN diferente do original.

. Use um programa de cópia no host para copiar o conteúdo do LUN de volta para o LUN original.


.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["show de espelhos instantâneos"^]

