---
permalink: san-admin/restore-single-lun-snapshot-copy-task.html 
sidebar: sidebar 
keywords: restore, single lun, snapshot copy 
summary: Você pode restaurar um único LUN a partir de um instantâneo sem restaurar todo o volume que contém o único LUN. Você pode restaurar o LUN no lugar ou para um novo caminho no volume. A operação restaura apenas o único LUN sem afetar outros arquivos ou LUNs no volume. Você também pode restaurar arquivos com streams. 
---
= Restaure um único LUN a partir de um instantâneo do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode restaurar um único LUN a partir de um instantâneo sem restaurar todo o volume que contém o único LUN. Você pode restaurar o LUN no lugar ou para um novo caminho no volume. A operação restaura apenas o único LUN sem afetar outros arquivos ou LUNs no volume. Você também pode restaurar arquivos com streams.

.Antes de começar
* Você deve ter espaço suficiente no volume para concluir a operação de restauração:
+
** Se você estiver restaurando um LUN com espaço reservado em que a reserva fracionária seja de 0%, será necessário uma vez o tamanho do LUN restaurado.
** Se você estiver restaurando um LUN com espaço reservado em que a reserva fracionária seja de 100%, será necessário duas vezes o tamanho do LUN restaurado.
** Se você estiver restaurando um LUN não reservado com espaço, você só precisará do espaço real usado para o LUN restaurado.


* Deve ter sido criado um instantâneo do LUN de destino.
+
Se a operação de restauração falhar, o LUN de destino pode ser truncado. Nesses casos, você pode usar o snapshot para evitar a perda de dados.

* Um instantâneo do LUN de origem deve ter sido criado.
+
Em casos raros, a restauração LUN pode falhar, deixando o LUN de origem inutilizável. Se isso ocorrer, você pode usar o snapshot para retornar o LUN ao estado imediatamente antes da tentativa de restauração.

* O LUN de destino e o LUN de origem têm de ter o mesmo tipo de SO.
+
Se o LUN de destino tiver um tipo de SO diferente do LUN de origem, o anfitrião poderá perder o acesso aos dados ao LUN de destino após a operação de restauro.



.Passos
. A partir do host, pare todo o acesso do host ao LUN.
. Desmonte o LUN em seu host para que o host não possa acessar o LUN.
. Desmapear o LUN:
+
[source, cli]
----
lun mapping delete -vserver <SVM_name> -volume <volume_name> -lun <lun_name> -igroup <igroup_name>
----
. Determine o instantâneo para o qual deseja restaurar o LUN:
+
[source, cli]
----
volume snapshot show -vserver <SVM_name> -volume <volume_name>
----
. Crie um instantâneo do LUN antes de restaurar o LUN:
+
[source, cli]
----
volume snapshot create -vserver <SVM_name> -volume <volume_name> -snapshot <snapshot_name>
----
. Restaure o LUN especificado em um volume:
+
[source, cli]
----
volume snapshot restore-file -vserver <SVM_name> -volume <volume_name> -snapshot <snapshot_name> -path <lun_path>
----
. Siga os passos apresentados no ecrã.
. Se necessário, coloque o LUN online:
+
[source, cli]
----
lun modify -vserver <SVM_name> -path <lun_path> -state online
----
. Se necessário, remapear o LUN:
+
[souce]
----
lun mapping create -vserver <SVM_name> -volume <volume_name> -lun <lun_name> -igroup <igroup_name>
----
. Do host, remonte o LUN.
. A partir do host, reinicie o acesso ao LUN.

