---
permalink: san-admin/san-config-mcc-concept.html 
sidebar: sidebar 
keywords: metrocluster environments, considerations, san configuration, metrocluster, environments, san, configurations, cisco switch, brocade switch, 
summary: Você precisa estar ciente de algumas considerações ao usar configurações de SAN em um ambiente MetroCluster. 
---
= Configurações de SAN compatíveis em um ambiente ONTAP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você precisa estar ciente de algumas considerações ao usar configurações de SAN em um ambiente MetroCluster.

* As configurações do MetroCluster não são compatíveis com configurações VSAN "roteadas" de malha FC de front-end.
* A partir do ONTAP 9.15,1, as configurações de IP MetroCluster de quatro nós são compatíveis com NVMe/TCP.
* A partir do ONTAP 9.12,1, as configurações de IP MetroCluster de quatro nós são compatíveis com NVMe/FC. As configurações do MetroCluster não são compatíveis com redes NVMe front-end anteriores ao ONTAP 9.12,1.
* Outros protocolos SAN, como iSCSI, FC e FCoE, são compatíveis com configurações do MetroCluster.
* Ao usar configurações de cliente SAN, você deve verificar se quaisquer considerações especiais para configurações do MetroCluster estão incluídas nas notas fornecidas no link:https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^] (IMT).
* Os sistemas operacionais e os aplicativos devem fornecer resiliência de e/S de 120 segundos para dar suporte ao switchover não planejado automático da MetroCluster e ao switchover tiebreaker ou iniciado por Mediator.
* As configurações do MetroCluster usam as mesmas WWNNs e WWPNs em ambos os lados da malha FC de front-end.


.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html["Compreender a proteção de dados e a recuperação de desastres da MetroCluster"^]
* link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/What_are_AIX_Host_support_considerations_in_a_MetroCluster_configuration%3F["Base de conhecimento da NetApp : Quais são as considerações de suporte ao host AIX em uma configuração do MetroCluster ?"^]
* link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/Solaris_host_support_considerations_in_a_MetroCluster_configuration["Base de conhecimento da NetApp : considerações sobre suporte ao host Solaris em uma configuração MetroCluster"^]

