---
permalink: san-admin/transition-config-concept.html 
sidebar: sidebar 
keywords: transitioning, san, configurations, capabilities, restrictions, transitioned, luns 
summary: Em um ambiente SAN, é necessária uma interrupção no serviço durante a transição de um volume de 7 modos para o ONTAP. Você precisa encerrar seus hosts para concluir a transição. Após a transição, você precisa atualizar as configurações de seu host antes de começar a fornecer dados no ONTAP. 
---
= Funcionalidades e restrições de LUNs transicionados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Em um ambiente SAN, é necessária uma interrupção no serviço durante a transição de um volume de 7 modos para o ONTAP. Você precisa encerrar seus hosts para concluir a transição. Após a transição, você precisa atualizar as configurações de seu host antes de começar a fornecer dados no ONTAP

Você precisa agendar uma janela de manutenção durante a qual você pode encerrar seus hosts e concluir a transição.

Os LUNs transferidos do Data ONTAP que operam no modo 7 para o ONTAP têm certos recursos e restrições que afetam a maneira como os LUNs podem ser gerenciados.

Você pode fazer o seguinte com LUNs transicionados:

* Visualize o LUN usando o `lun show` comando
* Visualize o inventário de LUNs transferidos do volume do modo 7D usando o `transition 7-mode show` comando
* Restaure um volume a partir de uma cópia Snapshot de 7 modos
+
A restauração do volume faz a transição de todos os LUNs capturados na cópia Snapshot

* Restaure um único LUN a partir de uma cópia Snapshot de 7 modos usando o `snapshot restore-file` comando
* Crie um clone de um LUN em uma cópia Snapshot de 7 modos
* Restaure um intervalo de blocos a partir de um LUN capturado em uma cópia Snapshot de 7 modos
* Crie um FlexClone do volume usando uma cópia Snapshot do modo 7


Não é possível fazer o seguinte com LUNs transicionados:

* Acesse clones LUN com cópia Snapshot capturados no volume


.Informações relacionadas
link:https://docs.netapp.com/us-en/ontap-7mode-transition/copy-based/index.html["Transição baseada em cópia"]
