---
permalink: san-admin/volume-config-options-concept.html 
sidebar: sidebar 
keywords: san, volume, configuration, options 
summary: Tem de definir várias opções no volume que contém o LUN. A forma como definir as opções de volume determina a quantidade de espaço disponível para LUNs no volume. 
---
= Opções de configuração de VOLUME SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tem de definir várias opções no volume que contém o LUN. A forma como definir as opções de volume determina a quantidade de espaço disponível para LUNs no volume.



== Crescimento automático

Você pode ativar ou desativar o crescimento automático. Se você ativá-lo, o crescimento automático permite que o ONTAP aumente automaticamente o tamanho do volume até um tamanho máximo que você predeterminar. Deve haver espaço disponível no agregado contendo para suportar o crescimento automático do volume. Portanto, se você ativar o crescimento automático, você deve monitorar o espaço livre no agregado contendo e adicionar mais quando necessário.

O crescimento automático não pode ser acionado para suportar a criação de instantâneos. Se você tentar criar um snapshot e não houver espaço suficiente no volume, a criação do snapshot falhará, mesmo com o crescimento automático ativado.

Se o crescimento automático estiver desativado, o tamanho do seu volume permanecerá o mesmo.



== Auto-retrátil

Pode ativar ou desativar o Autoshink. Se você ativá-lo, o recurso de auto-redução permite que o ONTAP diminua automaticamente o tamanho geral de um volume quando a quantidade de espaço consumida no volume diminui um limite predeterminado. Isso aumenta a eficiência de storage acionando volumes para liberar espaço livre não utilizado automaticamente.



== snapshot Autodelete

O snapshot autodelete elimina automaticamente os instantâneos quando ocorre uma das seguintes situações:

* O volume está quase cheio.
* O espaço de reserva instantâneo está quase cheio.
* O espaço de reserva de substituição está cheio.


Você pode configurar o snapshot autodelete para excluir snapshots do mais antigo para o mais recente ou do mais recente para o mais antigo. O snapshot autodelete não exclui instantâneos vinculados a instantâneos em volumes clonados ou LUNs.

Se o seu volume precisar de espaço adicional e tiver ativado o crescimento automático e o instantâneo, por predefinição, o ONTAP tenta adquirir o espaço necessário, acionando primeiro o crescimento automático. Se o espaço suficiente não for adquirido através do crescimento automático, o instantâneo é acionado.



== Reserva do Snapshot

Reserva Instantânea define a quantidade de espaço no volume reservado para instantâneos. O espaço atribuído à reserva instantânea não pode ser utilizado para qualquer outra finalidade. Se todo o espaço alocado para reserva de snapshot for usado, os snapshots começarão a consumir espaço adicional no volume.
