---
permalink: smb-config/assess-networking-requirements-task.html 
sidebar: sidebar 
keywords: provide, smb, storage, client, verify, network, configure, provision, requirement, assess, assess networking requirements 
summary: Antes de fornecer armazenamento SMB aos clientes, você deve verificar se a rede está configurada corretamente para atender aos requisitos de provisionamento SMB. 
---
= Avaliar os requisitos de rede SMB do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de fornecer armazenamento SMB aos clientes, você deve verificar se a rede está configurada corretamente para atender aos requisitos de provisionamento SMB.

.Antes de começar
Os seguintes objetos de rede de cluster devem ser configurados:

* Portas físicas e lógicas
* Domínios de broadcast
* Sub-redes (se necessário)
* IPspaces (conforme necessário, além do IPspace padrão)
* Grupos de failover (conforme necessário, além do grupo de failover padrão para cada domínio de broadcast)
* Firewalls externos


.Passos
. Exiba as portas físicas e virtuais disponíveis: `network port show`
+
** Quando possível, você deve usar a porta com a velocidade mais alta para a rede de dados.
** Todos os componentes da rede de dados devem ter a mesma configuração de MTU para obter o melhor desempenho.


+
Saiba mais sobre `network port show` o link:https://docs.netapp.com/us-en/ontap-cli/network-port-show.html["Referência do comando ONTAP"^]na .

. Se você estiver planejando usar um nome de sub-rede para alocar o endereço IP e o valor de máscara de rede para um LIF, verifique se a sub-rede existe e tem endereços suficientes disponíveis: `network subnet show`
+
As sub-redes contêm um conjunto de endereços IP que pertencem à mesma sub-rede da camada 3. As sub-redes são criadas usando o `network subnet create` comando.

+
Saiba mais sobre `network subnet create` o link:https://docs.netapp.com/us-en/ontap-cli/network-subnet-create.html["Referência do comando ONTAP"^]na .

. Exibir IPspaces disponíveis: `network ipspace show`
+
Você pode usar o IPspace padrão ou um IPspace personalizado.

+
Saiba mais sobre `network ipspace show` o link:https://docs.netapp.com/us-en/ontap-cli/network-ipspace-show.html["Referência do comando ONTAP"^]na .

. Se você quiser usar endereços IPv6, verifique se IPv6 está ativado no cluster: `network options ipv6 show`
+
Se necessário, você pode ativar o IPv6 usando o `network options ipv6 modify` comando.

+
Saiba mais sobre `network options ipv6 show` e `network options ipv6 modify` no link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+options+ipv6["Referência do comando ONTAP"^].


