---
permalink: smb-config/commands-manage-ntp-servers-reference.html 
sidebar: sidebar 
keywords: ontap, network, time, protocol, ntp, version, support, ntpv3, symmetric, authentication, sha, security, commands for managing symmetric authentication on ntp servers 
summary: 'A partir do ONTAP 9.5, o protocolo de tempo de rede (NTP) versão 3 é suportado. O NTPv3 inclui autenticação simétrica usando chaves SHA-1, o que aumenta a segurança da rede.' 
---
= Comandos para gerenciar a autenticação simétrica em servidores NTP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.5, o protocolo de tempo de rede (NTP) versão 3 é suportado. O NTPv3 inclui autenticação simétrica usando chaves SHA-1, o que aumenta a segurança da rede.

|===
| Para fazer isso... | Use este comando... 


 a| 
Configurar um servidor NTP sem autenticação simétrica
 a| 
`cluster time-service ntp server create` `-server` `server_name`



 a| 
Configure um servidor NTP com autenticação simétrica
 a| 
`cluster time-service ntp server create` `-server` `server_ip_address` `-key-id` `key_id`



 a| 
Ativar autenticação simétrica para um servidor NTP existente pode ser modificado para ativar a autenticação adicionando o ID de chave necessária.
 a| 
`cluster time-service ntp server modify` `-server` `server_name` `-key-id` `key_id`



 a| 
Configurar uma chave NTP partilhada
 a| 
`cluster time-service ntp key create` `-id` `shared_key_id` `-type` `shared_key_type` `-value` `shared_key_value`

[NOTE]
====
As chaves compartilhadas são referidas por um ID. O ID, seu tipo e valor devem ser idênticos no nó e no servidor NTP

====


 a| 
Configure um servidor NTP com um ID de chave desconhecido
 a| 
`cluster time-service ntp server create` `-server` `server_name` `-key-id` `key_id`



 a| 
Configure um servidor com um ID de chave não configurado no servidor NTP.
 a| 
`cluster time-service ntp server create` `-server` `server_name` `-key-id` `key_id`

[NOTE]
====
O ID, tipo e valor da chave devem ser idênticos ao ID, tipo e valor da chave configurados no servidor NTP.

====


 a| 
Desativar a autenticação simétrica
 a| 
`cluster time-service ntp server modify` `-server` `server_name` `-authentication disabled`

|===