---
permalink: smb-config/configure-ntfs-windows-security-tab-task.html 
sidebar: sidebar 
keywords: enable, file, access, user, group, share, configure, ntfs, permission, directories, directory, share, windows, client, configure ntfs file permissions in a share 
summary: Para habilitar o acesso a arquivos aos usuários ou grupos que têm acesso a um compartilhamento, você deve configurar permissões de arquivo NTFS em arquivos e diretórios nesse compartilhamento a partir de um cliente Windows. 
---
= Configurar permissões de arquivos NTFS em compartilhamentos SMB do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para habilitar o acesso a arquivos aos usuários ou grupos que têm acesso a um compartilhamento, você deve configurar permissões de arquivo NTFS em arquivos e diretórios nesse compartilhamento a partir de um cliente Windows.

.Antes de começar
O administrador que executa esta tarefa deve ter permissões NTFS suficientes para alterar permissões nos objetos selecionados.

.Sobre esta tarefa
link:../smb-admin/index.html["Gerenciamento de SMB"] E a documentação do Windows contém informações sobre como definir permissões NTFS padrão e avançadas.

.Passos
. Inicie sessão num cliente Windows como administrador.
. No menu *Ferramentas* no Windows Explorer, selecione *Mapear unidade de rede*.
. Preencha a caixa *Map Network Drive*:
+
.. Selecione uma letra *Drive*.
.. Na caixa *pasta*, digite o nome do servidor SMB que contém o compartilhamento que contém os dados aos quais você deseja aplicar permissões e o nome do compartilhamento.
+
Se o nome do servidor SMB for SMB_SERVER01 e o compartilhamento for chamado "'SHARE1", você digitaria `\\SMB_SERVER01\SHARE1`.

+
[NOTE]
====
Você pode especificar o endereço IP da interface de dados para o servidor SMB em vez do nome do servidor SMB.

====
.. Clique em *Finish*.


+
A unidade selecionada está montada e pronta com a janela do Windows Explorer exibindo arquivos e pastas contidos no compartilhamento.

. Selecione o arquivo ou diretório para o qual você deseja definir permissões de arquivo NTFS.
. Clique com o botão direito do rato no ficheiro ou diretório e selecione *Propriedades*.
. Selecione a guia *Segurança*.
+
A guia Segurança exibe a lista de usuários e grupos para os quais a permissão NTFS está definida. A caixa permissões para <Object> exibe uma lista de permissões de permissão e negação em vigor para o usuário ou grupo selecionado.

. Clique em *Editar*.
+
A caixa permissões para <Object> será aberta.

. Execute as ações desejadas:
+
|===
| Se você quiser | Faça o seguinte... 


 a| 
Defina permissões NTFS padrão para um novo usuário ou grupo
 a| 
.. Clique em *Add*.
+
A janela Selecionar usuário, computadores, contas de serviço ou grupos será exibida.

.. Na caixa *Digite os nomes de objeto a selecionar*, digite o nome do usuário ou grupo no qual você deseja adicionar permissão NTFS.
.. Clique em *OK*.




 a| 
Alterar ou remover permissões NTFS padrão de um usuário ou grupo
 a| 
Na caixa *Group (Grupo) ou User Names (nomes de usuário)*, selecione o usuário ou grupo que deseja alterar ou remover.

|===
. Execute as ações desejadas:
+
|===
| Se você quiser... | Faça o seguinte 


 a| 
Defina permissões NTFS padrão para um usuário ou grupo novo ou existente
 a| 
Na caixa *Permissions for <Object>*, selecione as caixas *allow* ou *deny* para o tipo de acesso que você deseja permitir ou não permitir para o usuário ou grupo selecionado.



 a| 
Remover um usuário ou grupo
 a| 
Clique em *Remover*.

|===
+
[NOTE]
====
Se algumas ou todas as caixas de permissão padrão não forem selecionáveis, é porque as permissões são herdadas do objeto pai. A caixa *Special Permissions* não é selecionável. Se estiver selecionado, significa que um ou mais direitos avançados granulares foram definidos para o usuário ou grupo selecionado.

====
. Depois de terminar de adicionar, remover ou editar permissões NTFS nesse objeto, clique em *OK*.

