---
permalink: smb-config/create-share-access-control-lists-task.html 
sidebar: sidebar 
keywords: configure, configuring, share, permission, create, access, control, list, acl, smb, enable, level, access, user, group, create smb share access control lists 
summary: 'A configuração de permissões de compartilhamento criando listas de controle de acesso (ACLs) para compartilhamentos SMB permite controlar o nível de acesso a um compartilhamento para usuários e grupos.' 
---
= Criar listas de controle de acesso de compartilhamento de SMB do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A configuração de permissões de compartilhamento criando listas de controle de acesso (ACLs) para compartilhamentos SMB permite controlar o nível de acesso a um compartilhamento para usuários e grupos.

.Antes de começar
Você deve ter decidido quais usuários ou grupos terão acesso ao compartilhamento.

.Sobre esta tarefa
Você pode configurar ACLs de nível de compartilhamento usando nomes de usuário ou grupo do Windows locais ou de domínio.

Antes de criar uma nova ACL, você deve excluir a ACL de compartilhamento padrão `Everyone / Full Control` , que representa um risco de segurança.

No modo de grupo de trabalho, o nome de domínio local é o nome do servidor SMB.

.Passos
. Excluir a ACL de compartilhamento padrão:``vserver cifs share access-control delete -vserver _vserver_name_ -share _share_name_ -user-or-group everyone``
. Configure a nova ACL:
+
|===
| Se você quiser configurar ACLs usando um... | Digite o comando... 


 a| 
Usuário do Windows
 a| 
`vserver cifs share access-control create -vserver _vserver_name_ -share _share_name_ -user-group-type windows -user-or-group _Windows_domain_name\\user_name_ -permission access_right`



 a| 
Grupo Windows
 a| 
`vserver cifs share access-control create -vserver _vserver_name_ -share _share_name_ -user-group-type windows -user-or-group _Windows_group_name_ -permission access_right`

|===
. Verifique se a ACL aplicada ao compartilhamento está correta usando o `vserver cifs share access-control show` comando.


.Exemplo
O comando a seguir `Change` dá permissões ao grupo Windows "equipe de vendas" para o compartilhamento "vendas" no vs1.example.com`"SVM:

[listing]
----
cluster1::> vserver cifs share access-control create -vserver vs1.example.com -share sales -user-or-group "Sales Team" -permission Change

cluster1::> vserver cifs share access-control show
                 Share       User/Group              User/Group  Access
Vserver          Name        Name                    Type        Permission
---------------- ----------- --------------------    ---------   -----------
vs1.example.com  c$          BUILTIN\Administrators  windows     Full_Control
vs1.example.com  sales       DOMAIN\"Sales Team"     windows     Change
----
Os comandos a seguir `Change` dão permissão ao grupo local do Windows chamado "Tiger Team" e `Full_Control` permissão ao usuário local do Windows chamado "Sue Chang" para o compartilhamento "d.atavol5" no "VS1" SVM:

[listing]
----
cluster1::> vserver cifs share access-control create -vserver vs1 -share datavol5 -user-group-type windows -user-or-group "Tiger Team" -permission Change

cluster1::> vserver cifs share access-control create -vserver vs1 -share datavol5 -user-group-type windows -user-or-group "Sue Chang" -permission Full_Control

cluster1::> vserver cifs share access-control show -vserver vs1
               Share       User/Group                  User/Group  Access
Vserver        Name        Name                        Type        Permission
-------------- ----------- --------------------------- ----------- -----------
vs1            c$          BUILTIN\Administrators      windows     Full_Control
vs1            datavol5    DOMAIN\"Tiger Team"         windows     Change
vs1            datavol5    DOMAIN\"Sue Chang"          windows     Full_Control
----