---
permalink: smb-config/create-local-groups-task.html 
sidebar: sidebar 
keywords: create, local, group, authorize, authorizing, access, data, associate, svm, smb, connection, assign, privilege, define, right, capabilities, capability, member, create local groups 
summary: É possível criar grupos locais que podem ser usados para autorizar o acesso aos dados associados ao SVM em uma conexão SMB. Você também pode atribuir Privileges que definem quais direitos de usuário ou recursos um membro do grupo tem. 
---
= Crie grupos locais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível criar grupos locais que podem ser usados para autorizar o acesso aos dados associados ao SVM em uma conexão SMB. Você também pode atribuir Privileges que definem quais direitos de usuário ou recursos um membro do grupo tem.

.Sobre esta tarefa
A funcionalidade de grupo local é ativada por padrão quando o SVM é criado.

Ao criar um grupo local, você deve especificar um nome para o grupo e especificar o SVM para associar o grupo. Você pode especificar um nome de grupo com ou sem o nome de domínio local e, opcionalmente, especificar uma descrição para o grupo local. Não é possível adicionar um grupo local a outro grupo local.

Saiba mais sobre `vserver cifs users-and-groups local-group` parâmetros opcionais e requisitos de nomenclatura no link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs+users-and-groups+local-group["Referência do comando ONTAP"^].

.Passos
. Crie o grupo local: `vserver cifs users-and-groups local-group create -vserver vserver_name -group-name group_name`
+
O seguinte parâmetro opcional pode ser útil:

+
** `-description`
+
Uma descrição para o grupo local.



. Verifique se o grupo foi criado com sucesso: `vserver cifs users-and-groups local-group show -vserver vserver_name`


.Exemplo
O exemplo a seguir cria um grupo local "SMB_SERVER01" associado ao SVM VS1:

[listing]
----
cluster1::> vserver cifs users-and-groups local-group create -vserver vs1.example.com -group-name SMB_SERVER01\engineering

cluster1::> vserver cifs users-and-groups local-group show -vserver vs1.example.com
Vserver          Group Name                   Description
---------------- ---------------------------- ----------------------------
vs1.example.com  BUILTIN\Administrators       Built-in Administrators group
vs1.example.com  BUILTIN\Backup Operators     Backup Operators group
vs1.example.com  BUILTIN\Power Users          Restricted administrative privileges
vs1.example.com  BUILTIN\Users                All users
vs1.example.com  SMB_SERVER01\engineering
vs1.example.com  SMB_SERVER01\sales
----
.Depois de terminar
Você deve adicionar membros ao novo grupo.
