---
permalink: smb-config/index.html 
sidebar: sidebar 
keywords:  
summary: Você pode usar os comandos de CLI do ONTAP 9 para configurar o acesso de cliente SMB a arquivos contidos em um novo volume ou qtree em um SVM novo ou existente. 
---
= Saiba mais sobre a configuração do SMB com a CLI do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar os comandos de CLI do ONTAP 9 para configurar o acesso de cliente SMB a arquivos contidos em um novo volume ou qtree em um SVM novo ou existente.

[NOTE]
====
_SMB_ (bloco de mensagens de servidor) refere-se aos dialetos modernos do protocolo Common Internet File System (CIFS). Você ainda verá _CIFS_ na interface de linha de comando (CLI) do ONTAP e nas ferramentas de gerenciamento do OnCommand.

====
Use estes procedimentos se quiser configurar o acesso SMB a um volume ou qtree da seguinte maneira:

* Você deseja usar SMB versão 2 ou posterior.
* Você deseja atender apenas clientes SMB, não clientes NFS (não uma configuração multiprotocolo).
* As permissões de arquivo NTFS serão usadas para proteger o novo volume.
* Você tem o administrador de clusters Privileges, e não o Privileges do administrador da SVM.
+
Os Privileges do administrador de cluster são necessários para criar SVMs e LIFs. Os Privileges de administrador do SVM são suficientes para outras tarefas de configuração de SMB.

* Você deseja usar a CLI, não o System Manager ou uma ferramenta de script automatizado.
+
Para usar o System Manager para configurar o acesso multiprotocolo nas, link:../task_nas_provision_nfs_and_smb.html["Provisionar storage nas para Windows e Linux usando NFS e SMB"]consulte .

* Você quer usar as práticas recomendadas, não explorar todas as opções disponíveis.
+
Saiba mais sobre os comandos descritos neste procedimento no link:https://docs.netapp.com/us-en/ontap-cli/["Referência do comando ONTAP"^].



Se pretender obter detalhes sobre a gama de capacidades do protocolo SMB do ONTAP, consulte o link:../smb-admin/index.html["Visão geral de referência SMB"].



== Outras maneiras de fazer isso em ONTAP

|===


| Para executar estas tarefas com... | Consulte... 


| O Gerenciador de sistema redesenhado (disponível com o ONTAP 9.7 e posterior) | link:../task_nas_provision_windows_smb.html["Provisione storage nas para servidores Windows usando SMB"] 


| System Manager Classic (disponível com o ONTAP 9.7 e versões anteriores) | link:https://docs.netapp.com/us-en/ontap-system-manager-classic/smb-config/index.html["Visão geral da configuração SMB"^] 
|===