---
permalink: smb-config/manage-local-group-membership-task.html 
sidebar: sidebar 
keywords: manage, local, group, membership, add, remove, removing, local, domain, user, privilege, manage local group membership 
summary: Você pode gerenciar a associação de grupo local adicionando e removendo usuários locais ou de domínio ou adicionando e removendo grupos de domínio. Isso é útil se você quiser controlar o acesso a dados com base nos controles de acesso colocados no grupo ou se quiser que os usuários tenham o Privileges associado a esse grupo. 
---
= Gerenciar a associação de grupo SMB local do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode gerenciar a associação de grupo local adicionando e removendo usuários locais ou de domínio ou adicionando e removendo grupos de domínio. Isso é útil se você quiser controlar o acesso a dados com base nos controles de acesso colocados no grupo ou se quiser que os usuários tenham o Privileges associado a esse grupo.

.Sobre esta tarefa
Se você não quiser mais que um usuário local, usuário de domínio ou grupo de domínio tenha direitos de acesso ou Privileges com base na associação a um grupo, você pode remover o membro do grupo.

Você deve ter em mente o seguinte ao adicionar membros a um grupo local:

* Você não pode adicionar usuários ao grupo especial _todos_.
* Não é possível adicionar um grupo local a outro grupo local.
* Para adicionar um usuário ou grupo de domínio a um grupo local, o ONTAP deve ser capaz de resolver o nome para um SID.


Você deve ter em mente o seguinte ao remover membros de um grupo local:

* Você não pode remover membros do grupo especial _todos_.
* Para remover um membro de um grupo local, o ONTAP deve ser capaz de resolver seu nome para um SID.


.Passos
. Adicione um membro ou remova um membro de um grupo.
+
** Adicionar um membro: `+vserver cifs users-and-groups local-group add-members ‑vserver vserver_name -group-name group_name ‑member-names name[,...]+`
+
Você pode especificar uma lista delimitada por vírgulas de usuários locais, usuários de domínio ou grupos de domínio para adicionar ao grupo local especificado.

** Remover um membro: `+vserver cifs users-and-groups local-group remove-members -vserver vserver_name -group-name group_name ‑member-names name[,...]+`
+
Você pode especificar uma lista delimitada por vírgulas de usuários locais, usuários de domínio ou grupos de domínio a serem removidos do grupo local especificado.





.Exemplos
O exemplo a seguir adiciona um usuário local ""SMB_SERVER01"" ao grupo local ""SMB_SERVER01" engenharia" no SVM vs1.example.com:

[listing]
----
cluster1::> vserver cifs users-and-groups local-group add-members -vserver vs1.example.com -group-name SMB_SERVER01\engineering -member-names SMB_SERVER01\sue
----
O exemplo a seguir remove os usuários locais "'SMB_SERVER01''" e "'SMB_SERVER01' james' do grupo local "'SMB_SERVER01' Engineering" no SVM vs1.example.com:

[listing]
----
cluster1::> vserver cifs users-and-groups local-group remove-members -vserver vs1.example.com -group-name SMB_SERVER\engineering -member-names SMB_SERVER\sue,SMB_SERVER\james
----