---
permalink: smb-config/map-dns-server-task.html 
sidebar: sidebar 
keywords: site, dns, server, entry, point, smb, name, netbios, alias, ip, address, lif, windows, map the smb server on the dns server 
summary: O servidor DNS do seu site deve ter uma entrada apontando o nome do servidor SMB e quaisquer aliases NetBIOS, para o endereço IP do LIF de dados para que os usuários do Windows possam mapear uma unidade para o nome do servidor SMB. 
---
= Mapeie o servidor SMB no servidor DNS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O servidor DNS do seu site deve ter uma entrada apontando o nome do servidor SMB e quaisquer aliases NetBIOS para o endereço IP do LIF de dados para que os usuários do Windows possam mapear uma unidade para o nome do servidor SMB.

.Antes de começar
Você deve ter acesso administrativo ao servidor DNS do seu site. Se não tiver acesso administrativo, deverá pedir ao administrador DNS para executar esta tarefa.

.Sobre esta tarefa
Se você usar aliases NetBIOS para o nome do servidor SMB, é uma prática recomendada criar pontos de entrada de servidor DNS para cada alias.

.Passos
. Inicie sessão no servidor DNS.
. Criar entradas de pesquisa direta (A - Registro de endereço) e inversa (PTR - Registro de ponteiro) para mapear o nome do servidor SMB para o endereço IP do LIF de dados.
. Se você usar aliases NetBIOS, crie uma entrada de pesquisa de nome canônico Alias (CNAME resource record) para mapear cada alias para o endereço IP do LIF de dados do servidor SMB.


.Resultados
Depois que o mapeamento é propagado pela rede, os usuários do Windows podem mapear uma unidade para o nome do servidor SMB ou seus aliases NetBIOS.
