---
permalink: smb-config/verify-user-access-task.html 
sidebar: sidebar 
keywords: test, user, configure, access, smb, share, file, contain, verify user access 
summary: Você deve testar se os usuários configurados podem acessar o compartilhamento SMB e os arquivos nele contidos. 
---
= Verifique o acesso do usuário
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve testar se os usuários configurados podem acessar o compartilhamento SMB e os arquivos nele contidos.

.Passos
. Em um cliente Windows, faça login como um dos usuários que agora tem acesso ao compartilhamento.
. No menu *Ferramentas* no Windows Explorer, selecione *Mapear unidade de rede*.
. Preencha a caixa *Map Network Drive*:
+
.. Selecione uma letra *Drive*.
.. Na caixa *pasta*, digite o nome do compartilhamento que você fornecerá aos usuários.
+
Se o nome do servidor SMB for SMB_SERVER01 e o compartilhamento for chamado "'SHARE1", você digitaria `\\SMB_SERVER01\share1`.

.. Clique em *Finish*.


+
A unidade selecionada está montada e pronta com a janela do Windows Explorer exibindo arquivos e pastas contidos no compartilhamento.

. Crie um arquivo de teste, verifique se ele existe, escreva texto nele e remova o arquivo de teste.

