---
permalink: smb-config/where-provision-storage-capacity-task.html 
sidebar: sidebar 
keywords: create, smb, volume, qtree, exist, configuration, svm, decision, workflow, decide where to provision new SMB storage capacity 
summary: Antes de criar um novo volume ou qtree SMB, você precisa decidir se deve colocá-lo em uma SVM nova ou existente e quanto de configuração o SVM precisa. Esta decisão determina o seu fluxo de trabalho. 
---
= Saiba mais sobre o provisionamento de capacidade de armazenamento ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de criar um novo volume ou qtree SMB, você precisa decidir se deve colocá-lo em uma SVM nova ou existente e quanto de configuração o SVM precisa. Esta decisão determina o seu fluxo de trabalho.

.Opções
* Se você quiser provisionar um volume ou qtree em um novo SVM ou em um SVM existente que tenha o SMB habilitado, mas não configurado, execute as etapas em ""Configurando o acesso SMB a um SVM"" e "adicionando capacidade de storage a um SVM habilitado para SMB".
+
xref:configure-access-svm-task.adoc[Configurando o acesso SMB a uma SVM]

+
xref:configure-client-access-shared-storage-concept.adoc[Configurando o acesso de cliente SMB ao armazenamento compartilhado]

+
Você pode optar por criar um novo SVM se uma das seguintes opções for verdadeira:

+
** Você está habilitando o SMB em um cluster pela primeira vez.
** Você tem SVMs existentes em um cluster no qual não deseja ativar o suporte a SMB.
** Você tem um ou mais SVMs habilitados para SMB em um cluster e deseja uma das seguintes conexões:
+
*** Para uma floresta ou grupo de trabalho diferente do ative Directory.
*** Para um servidor SMB em um namespace isolado (cenário de alocação a vários clientes). Você também deve escolher essa opção para provisionar storage em uma SVM existente que tenha SMB habilitado, mas não configurado. Esse pode ser o caso se você criou o SVM para acesso à SAN ou se nenhum protocolo foi habilitado quando o SVM foi criado.




+
Depois de ativar o SMB no SVM, proceda ao provisionamento de um volume ou qtree.

* Se você quiser provisionar um volume ou qtree em um SVM existente totalmente configurado para acesso SMB, execute as etapas em ""adicionando capacidade de storage a um SVM habilitado para SMB"".
+
xref:configure-client-access-shared-storage-concept.adoc[Configurando o acesso de cliente SMB ao armazenamento compartilhado]


