---
permalink: disks-aggregates/assign-aggregates-svms-task.html 
sidebar: sidebar 
keywords: assign, aggregate, local tier, svm, storage vm, vserver 
summary: 'Se você atribuir uma ou mais camadas locais (agregados) a uma  máquina virtual de storage (VM de storage ou SVM, anteriormente conhecido como SVM), você poderá usar apenas essas camadas locais para conter volumes para esse SVM. A' 
---
= Atribuir camadas locais (agregados) a VMs de storage (SVMs)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você atribuir uma ou mais camadas locais (agregados) a uma máquina virtual de storage (VM de storage ou SVM, anteriormente conhecido como SVM), você poderá usar apenas essas camadas locais para conter volumes para essa VM de storage (SVM).

.O que você vai precisar
A VM de storage e os níveis locais que você deseja atribuir a essa VM de storage já devem existir.

.Sobre esta tarefa
A atribuição de camadas locais às VMs de storage ajuda a manter as VMs de storage isoladas umas das outras. Isso é especialmente importante em um ambiente de alocação a vários clientes.

.Passos
. Confira a lista de camadas locais (agregados) já atribuídas ao SVM:
+
`vserver show -fields aggr-list`

+
Os agregados atualmente atribuídos à SVM são exibidos. Se não houver agregados atribuídos, é apresentado "»-".

. Adicione ou remova agregados atribuídos, dependendo dos seus requisitos:
+
|===


| Se você quiser... | Use este comando... 


 a| 
Atribuir agregados adicionais
 a| 
`vserver add-aggregates`



 a| 
Anular a atribuição de agregados
 a| 
`vserver remove-aggregates`

|===
+
Os agregados listados são atribuídos ou removidos do SVM. Se o SVM já tiver volumes que usam um agregado que não está atribuído ao SVM, uma mensagem de aviso será exibida, mas o comando será concluído com êxito. Todos os agregados que já foram atribuídos ao SVM e que não foram nomeados no comando não são afetados.



.Exemplo
No exemplo a seguir, os agregados aggr1 e aggr2 são atribuídos ao SVM svm1:

`vserver add-aggregates -vserver svm1 -aggregates aggr1,aggr2`
