---
permalink: disks-aggregates/assign-aggregates-svms-task.html 
sidebar: sidebar 
keywords: assign, aggregate, local tier, svm, storage vm, vserver 
summary: 'Se você atribuir uma ou mais camadas locais a uma  máquina virtual de storage (Storage VM ou SVM, anteriormente conhecido como SVM), você poderá usar apenas essas camadas locais para conter volumes para esse SVM. A' 
---
= Atribua camadas locais a VMs de storage (SVMs) no ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você atribuir uma ou mais camadas locais a uma máquina virtual de storage (Storage VM ou SVM, anteriormente conhecido como SVM), você poderá usar apenas esses níveis locais para conter volumes para essa VM de storage (SVM).


NOTE: Antes do ONTAP 9,7, o Gerenciador de sistema usa o termo _agregado_ para descrever um nível _local_. Independentemente da sua versão do ONTAP, a CLI do ONTAP usa o termo _agregado_. Para saber mais sobre os níveis locais, link:../disks-aggregates/index.html["Discos e camadas locais"]consulte .

.Antes de começar
A VM de storage e os níveis locais que você deseja atribuir a essa VM de storage já devem existir.

.Sobre esta tarefa
A atribuição de camadas locais às VMs de storage ajuda a manter as VMs de storage isoladas umas das outras. Isso é especialmente importante em um ambiente de alocação a vários clientes.

.Passos
. Verifique a lista de níveis locais já atribuídos ao SVM:
+
`vserver show -fields aggr-list`

+
Os níveis locais atualmente atribuídos à SVM são exibidos. Se não houver níveis locais atribuídos, `-` será exibido.

. Adicione ou remova os níveis locais atribuídos, dependendo dos seus requisitos:
+
|===


| Se você quiser... | Use este comando... 


 a| 
Atribua níveis locais adicionais
 a| 
`vserver add-aggregates`



 a| 
Anular a atribuição de níveis locais
 a| 
`vserver remove-aggregates`

|===
+
Os níveis locais listados são atribuídos ou removidos do SVM. Se o SVM já tiver volumes que usam um agregado que não está atribuído ao SVM, uma mensagem de aviso será exibida, mas o comando será concluído com êxito. Todos os níveis locais que já foram atribuídos ao SVM e que não foram nomeados no comando não são afetados.



.Exemplo
No exemplo a seguir, as camadas locais aggr1 e aggr2 são atribuídas ao SVM svm1:

`vserver add-aggregates -vserver svm1 -aggregates aggr1,aggr2`
