---
permalink: disks-aggregates/commands-display-storage-shelves-reference.html 
sidebar: sidebar 
keywords: commands, display, information, storage, shelves 
summary: Você usa o comando storage shelf show para exibir informações de configuração e erro das prateleiras de disco. 
---
= Comandos do ONTAP para exibir informações sobre compartimentos de storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Use o `storage shelf show` comando para exibir informações de configuração e erro para as gavetas de disco.

|===
| Se você quiser exibir... | Use este comando... 


 a| 
Informações gerais sobre a configuração do compartimento e o status do hardware
 a| 
`storage shelf show`



 a| 
Informações detalhadas para um compartimento específico, incluindo ID da pilha
 a| 
`storage shelf show -shelf`



 a| 
Erros não resolvidos, acionáveis pelo cliente, por compartimento
 a| 
`storage shelf show -errors`



 a| 
Informações sobre a baía
 a| 
`storage shelf show -bay`



 a| 
Informações de conetividade
 a| 
`storage shelf show -connectivity`



 a| 
Informações de refrigeração, incluindo sensores de temperatura e ventoinhas de arrefecimento
 a| 
`storage shelf show -cooling`



 a| 
Informações sobre módulos de e/S.
 a| 
`storage shelf show -module`



 a| 
Informações da porta
 a| 
`storage shelf show -port`



 a| 
Informações de energia, incluindo PSUs (unidades de fonte de alimentação), sensores de corrente e sensores de tensão
 a| 
`storage shelf show -power`

|===
.Informações relacionadas
* https://docs.netapp.com/us-en/ontap-cli["Referência do comando ONTAP"^]

