---
permalink: disks-aggregates/commands-manage-disks-reference.html 
sidebar: sidebar 
keywords: commands, manage, disks 
summary: Você pode usar os comandos de armazenamento de dados e armazenamento de dados agregados para gerenciar seus discos. 
---
= Comandos ONTAP para gerenciar discos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar os `storage disk` comandos e `storage aggregate` para gerenciar seus discos.


NOTE: Antes do ONTAP 9,7, o Gerenciador de sistema usa o termo _agregado_ para descrever um nível _local_. Independentemente da sua versão do ONTAP, a CLI do ONTAP usa o termo _agregado_. Para saber mais sobre os níveis locais, link:../disks-aggregates/index.html["Discos e camadas locais"]consulte .

|===


| Se você quiser... | Use este comando... 


 a| 
Exibir uma lista de discos sobressalentes, incluindo discos particionados, pelo proprietário
 a| 
`storage aggregate show-spare-disks`



 a| 
Exiba o tipo de RAID do disco, o uso atual e o grupo RAID por nível local
 a| 
`storage aggregate show-status`



 a| 
Exibir o tipo de RAID, uso atual, nível local e grupo RAID, incluindo peças sobressalentes, para discos físicos
 a| 
`storage disk show -raid`



 a| 
Exibir uma lista de discos com falha
 a| 
`storage disk show -broken`



 a| 
Apresentar o nome da unidade do pré-cluster (nodescope) para um disco
 a| 
`storage disk show -primary-paths` (avançado)



 a| 
Acenda o LED de um determinado disco ou prateleira
 a| 
`storage disk set-led`



 a| 
Exiba o tipo de checksum de um disco específico
 a| 
`storage disk show -fields checksum-compatibility`



 a| 
Exiba o tipo de checksum para todos os discos sobressalentes
 a| 
`storage disk show -fields checksum-compatibility -container-type spare`



 a| 
Exibir informações de conetividade e posicionamento do disco
 a| 
`storage disk show -fields disk,primary-port,secondary-name,secondary-port,shelf,bay`



 a| 
Exibir os nomes de discos do pré-cluster para discos específicos
 a| 
`storage disk show -disk diskname -fields diskpathnames`



 a| 
Apresentar a lista de discos no centro de manutenção
 a| 
`storage disk show -maintenance`



 a| 
Exibir a vida útil do SSD
 a| 
`storage disk show -ssd-wear`



 a| 
Desparticionar um disco compartilhado
 a| 
`storage disk unpartition` (disponível no nível de diagnóstico)



 a| 
Zero todos os discos não zerados
 a| 
`storage disk zerospares`



 a| 
Parar um processo de sanitização contínuo em um ou mais discos especificados
 a| 
`system node run -node nodename -command disk sanitize`



 a| 
Exibir informações do disco de criptografia de armazenamento
 a| 
`storage encryption disk show`



 a| 
Recuperar chaves de autenticação de todos os servidores de gerenciamento de chaves vinculados
 a| 
`security key-manager restore`

|===
.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=storage+aggregate+show["show de agregados de storage"^]

