---
permalink: disks-aggregates/commands-display-space-usage-reference.html 
sidebar: sidebar 
keywords: commands, display, space usage, information 
summary: Você usa os comandos de volume e agregado de storage para ver como o espaço está sendo usado em agregados, volumes e snapshots. 
---
= Comandos para exibir informações de uso de espaço
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Use os `storage aggregate` comandos e `volume` para ver como o espaço está sendo usado em agregados e volumes e em seus snapshots.

|===


| Para exibir informações sobre... | Use este comando... 


 a| 
Agregados, incluindo detalhes sobre porcentagens de espaço usadas e disponíveis, tamanho da reserva de snapshot e outras informações de utilização de espaço
 a| 
`storage aggregate show`
`storage aggregate show-space -fields snap-size-total,used-including-snapshot-reserve`



 a| 
Como discos e grupos RAID são usados em um agregado e status RAID
 a| 
`storage aggregate show-status`



 a| 
A quantidade de espaço em disco que seria recuperada se você excluísse um snapshot específico
 a| 
`volume snapshot compute-reclaimable`



 a| 
A quantidade de espaço utilizada por um volume
 a| 
`volume show -fields size,used,available,percent-used`
`volume show-space`



 a| 
A quantidade de espaço usada por um volume no agregado que contém
 a| 
`volume show-footprint`

|===
.Informações relacionadas
* link:../concepts/manual-pages.html["Referência do comando ONTAP"]

