---
permalink: disks-aggregates/commands-aggregate-relocation-reference.html 
sidebar: sidebar 
keywords: commands, aggregate, relocation 
summary: Existem comandos ONTAP específicos para relocalizar a propriedade de nível local dentro de um par de HA. 
---
= Comandos do ONTAP para realocação de um nível local
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Existem comandos ONTAP específicos para relocalizar a propriedade de nível local dentro de um par de HA.


NOTE: Antes do ONTAP 9,7, o Gerenciador de sistema usa o termo _agregado_ para descrever um nível _local_. Independentemente da sua versão do ONTAP, a CLI do ONTAP usa o termo _agregado_. Para saber mais sobre os níveis locais, link:../disks-aggregates/index.html["Discos e camadas locais"]consulte .

|===


| Se você quiser... | Use este comando... 


 a| 
Inicie o processo de realocação de nível local
 a| 
`storage aggregate relocation start`



 a| 
Monitorar o processo de realocação da camada local
 a| 
`storage aggregate relocation show`

|===
.Informações relacionadas
* link:../concepts/manual-pages.html["Referência do comando ONTAP"]

