---
permalink: disks-aggregates/convert-raid-tec-dp-task.html 
sidebar: sidebar 
keywords: convert, raid-tec, raid-dp, raid policy 
summary: 'Se você reduzir o tamanho do seu nível local (agregado) e não precisar mais de tripla paridade, poderá converter sua política de RAID-teC em RAID-DP e reduzir o número de discos necessários para paridade RAID.' 
---
= Converter de RAID-teC em RAID-DP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você reduzir o tamanho do seu nível local (agregado) e não precisar mais de tripla paridade, poderá converter sua política de RAID-teC em RAID-DP e reduzir o número de discos necessários para paridade RAID.

.Antes de começar
O tamanho máximo do grupo RAID para RAID-teC é maior do que o tamanho máximo do grupo RAID para RAID-DP. Se o maior tamanho de grupo RAID-teC não estiver dentro dos limites RAID-DP, você não poderá converter para RAID-DP.

.Sobre esta tarefa
Para entender as implicações da conversão entre tipos de RAID, consulte o https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-modify.html#parameters["parâmetros"^] para obter o `storage aggregate modify` comando.

.Passos
. Verifique se o agregado está on-line e tem no mínimo seis discos:
+
`storage aggregate show-status -aggregate _aggregate_name_`

. Converter o agregado de RAID-teC em RAID-DP:
+
`storage aggregate modify -aggregate _aggregate_name_ -raidtype raid_dp`

. Verifique se a política RAID agregada é RAID-DP:
+
`storage aggregate show _aggregate_name_`


