---
permalink: disks-aggregates/convert-raid-dp-tec-task.html 
sidebar: sidebar 
keywords: convert, raid-dp, raid-tec, raid policy 
summary: Se você quiser obter proteção adicional de paridade tripla, poderá converter de RAID-DP em RAID-teC. O RAID-TEC é recomendado se o tamanho dos discos usados em seu nível local for maior que 4 TIB. 
---
= Converter de ONTAP RAID-DP em RAID-TEC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você quiser obter proteção adicional de paridade tripla, poderá converter de RAID-DP em RAID-teC. O RAID-TEC é recomendado se o tamanho dos discos usados em seu nível local for maior que 4 TIB.


NOTE: Antes do ONTAP 9,7, o Gerenciador de sistema usa o termo _agregado_ para descrever um nível _local_. Independentemente da sua versão do ONTAP, a CLI do ONTAP usa o termo _agregado_. Para saber mais sobre os níveis locais, link:../disks-aggregates/index.html["Discos e camadas locais"]consulte .

.Antes de começar
O nível local que deve ser convertido deve ter no mínimo sete discos.

.Sobre esta tarefa
* As camadas locais da unidade de disco rígido (HDD) podem ser convertidas de RAID-DP para RAID-teC. Isso inclui camadas de HDD nos níveis locais do Flash Pool.


.Processo para flashpools/agregados híbridos onde -disktype precisa ser usado para alterar o tipo de cada disco
[-T, -disktype {ATA | BSAS | FCAL | FSAS | LUN | MSATA | SAS | SSD | VMDISK | SSD-NVM | SSD-CAP | SSD-ZNS | VMLUN | VMLUN-SSD}] - Tipo de disco

Este parâmetro especifica o tipo de disco dos grupos RAID a serem modificados. No caso de Flash Pool, ele especifica a camada de HDD ou a camada de SSD. Se a camada de HDD for composta por mais de um tipo de disco, especificar qualquer um dos tipos de disco em uso faz com que essa camada seja modificada. Se o tipo de RAID agregado atual for mixed_raid_type, este parâmetro é obrigatório.

.Passos
. Verifique se o nível local está online e tem um mínimo de seis discos:
+
`storage aggregate show-status -aggregate _aggregate_name_`

. Converta o nível local de RAID-DP para RAID-TEC:
+
`storage aggregate modify -aggregate _aggregate_name_ -raidtype raid_tec`

. Verifique se a política de RAID de nível local é RAID-TEC:
+
`storage aggregate show _aggregate_name_`



.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-modify.html["modificação de agregado de armazenamento"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-status.html["status de exibição de agregado de armazenamento"^]

