---
permalink: disks-aggregates/convert-raid-dp-tec-task.html 
sidebar: sidebar 
keywords: convert, raid-dp, raid-tec, raid policy 
summary: Se você quiser obter proteção adicional de paridade tripla, poderá converter de RAID-DP em RAID-teC. O RAID-teC é recomendado se o tamanho dos discos usados em seu agregado for maior que 4 TIB. 
---
= Converter de RAID-DP em RAID-teC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você quiser obter proteção adicional de paridade tripla, poderá converter de RAID-DP em RAID-teC. O RAID-teC é recomendado se o tamanho dos discos usados em seu nível local (agregado) for maior que 4 TIB.

.O que você vai precisar
O nível local (agregado) que deve ser convertido deve ter no mínimo sete discos.

.Sobre esta tarefa
* As camadas locais da unidade de disco rígido (HDD) podem ser convertidas de RAID-DP para RAID-teC. Isso inclui camadas de HDD nos níveis locais do Flash Pool.
* Para entender as implicações da conversão entre tipos de RAID, consulte o https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-modify.html#parameters["parâmetros"^] para obter o `storage aggregate modify` comando.


.Passos
. Verifique se o agregado está on-line e tem no mínimo seis discos:
+
`storage aggregate show-status -aggregate _aggregate_name_`

. Converta o agregado de RAID-DP em RAID-teC:
+
`storage aggregate modify -aggregate _aggregate_name_ -raidtype raid_tec`

. Verifique se a política de RAID agregado é RAID-teC:
+
`storage aggregate show _aggregate_name_`


