---
permalink: disks-aggregates/customize-size-raid-groups-task.html 
sidebar: sidebar 
keywords: raidsize, customize, raid groups 
summary: 'Você pode personalizar o tamanho dos grupos RAID para garantir que os tamanhos dos grupos RAID sejam apropriados para a quantidade de storage que você planeja incluir em um nível local (agregado).' 
---
= Personalize o tamanho dos grupos RAID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode personalizar o tamanho dos grupos RAID para garantir que os tamanhos dos grupos RAID sejam apropriados para a quantidade de storage que você planeja incluir em um nível local (agregado).

.Sobre esta tarefa
Para camadas locais padrão (agregados), você altera o tamanho dos grupos RAID para cada categoria local separadamente. Para camadas locais do Flash Pool, é possível alterar o tamanho do grupo RAID para os grupos RAID SSD e RAID HDD de forma independente.

A lista a seguir descreve alguns fatos sobre como alterar o tamanho do grupo RAID:

* Por padrão, se o número de discos ou LUNs de matriz no grupo RAID criado mais recentemente for menor do que o novo tamanho do grupo RAID, os discos ou LUNs de matriz serão adicionados ao grupo RAID criado mais recentemente até atingir o novo tamanho.
* Todos os outros grupos RAID existentes nesse nível local permanecem do mesmo tamanho, a menos que você explicitamente adicione discos a eles.
* Nunca é possível fazer com que um grupo RAID fique maior do que o tamanho máximo atual do grupo RAID para o nível local.
* Não é possível diminuir o tamanho dos grupos RAID já criados.
* O novo tamanho se aplica a todos os grupos RAID nesse nível local (ou, no caso de um nível local do Flash Pool, todos os grupos RAID para o tipo de grupo RAID afetado - SSD ou HDD).


.Passos
. Use o comando aplicável:
+
|===


| Se você quiser... | Digite o seguinte comando... 


 a| 
Altere o tamanho máximo do grupo RAID para os grupos RAID SSD de um agregado Flash Pool
 a| 
`storage aggregate modify -aggregate aggr_name -cache-raid-group-size size`



 a| 
Altere o tamanho máximo de quaisquer outros grupos RAID
 a| 
`storage aggregate modify -aggregate aggr_name -maxraidsize size`

|===


.Exemplos
O comando a seguir altera o tamanho máximo do grupo RAID do agregado n1_A4 para 20 discos ou LUNs de matriz:

`storage aggregate modify -aggregate n1_a4 -maxraidsize 20`

O comando a seguir altera o tamanho máximo do grupo RAID dos grupos RAID de cache SSD do Flash Pool Aggregate n1_cache_A2 para 24:

`storage aggregate modify -aggregate n1_cache_a2 -cache-raid-group-size 24`
