---
permalink: disks-aggregates/decide-aggregate-creation-method-concept.html 
sidebar: sidebar 
keywords: decide, aggregate, create, add, method, local tier 
summary: Embora o ONTAP forneça recomendações de práticas recomendadas para a criação automática de camadas locais, você deve determinar se as configurações recomendadas são compatíveis com o seu ambiente. Se não estiver, você deverá tomar decisões sobre a política de RAID e a configuração de disco e, em seguida, criar manualmente as camadas locais. 
---
= Decida qual método usar para criar níveis locais no ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Embora o ONTAP forneça recomendações de práticas recomendadas para adicionar camadas locais automaticamente, você deve determinar se as configurações recomendadas são compatíveis com o seu ambiente. Se não estiverem, você deverá tomar decisões sobre a política de RAID e a configuração de disco e, em seguida, criar manualmente as camadas locais.

Quando um nível local é criado automaticamente, o ONTAP analisa os discos sobressalentes disponíveis no cluster e gera uma recomendação sobre como os discos sobressalentes devem ser usados para adicionar camadas locais de acordo com as práticas recomendadas. O ONTAP exibe as configurações recomendadas. Você pode aceitar as recomendações ou adicionar manualmente os níveis locais.


NOTE: Antes do ONTAP 9,7, o Gerenciador de sistema usa o termo _agregado_ para descrever um nível _local_. Independentemente da sua versão do ONTAP, a CLI do ONTAP usa o termo _agregado_. Para saber mais sobre os níveis locais, link:../disks-aggregates/index.html["Discos e camadas locais"]consulte .



== Antes de aceitar as recomendações do ONTAP

Se alguma das seguintes condições de disco estiver presente, elas devem ser abordadas antes de aceitar as recomendações do ONTAP:

* Discos em falta
* Flutuação nos números de disco sobressalente
* Discos não atribuídos
* Peças sobressalentes não zeradas
* Discos submetidos a testes de manutenção


Saiba mais sobre `storage aggregate auto-provision` o link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-auto-provision.html["Referência do comando ONTAP"^]na .



== Quando tem de utilizar o método manual

Em muitos casos, o layout recomendado do nível local será ideal para o seu ambiente. No entanto, se o seu ambiente incluir as configurações a seguir, você deverá criar o nível local usando o método manual.


NOTE: A partir do ONTAP 9.11,1, você pode adicionar manualmente camadas locais com o Gerenciador de sistema.

* Camadas locais usando LUNs de array de terceiros
* Discos virtuais com Cloud Volumes ONTAP ou ONTAP Select
* Sistema MetroCluster
* SyncMirror
* Discos MSATA
* Camadas do Flash Pool
* Vários tipos ou tamanhos de disco são conetados ao nó




== Selecione o método para criar níveis locais

Escolha o método que deseja usar:

* link:create-aggregates-auto-provision-task.html["Adicionar (criar) níveis locais automaticamente"]
* link:create-aggregates-manual-task.html["Adicione (crie) camadas locais manualmente"]


.Informações relacionadas
* https://docs.netapp.com/us-en/ontap-cli["Referência do comando ONTAP"^]

