---
permalink: disks-aggregates/decide-aggregate-creation-method-concept.html 
sidebar: sidebar 
keywords: decide, aggregate, create, add, method, local tier 
summary: 'Embora o ONTAP forneça recomendações de práticas recomendadas para a criação automática de camadas locais (agregados) (com provisionamento automático), é necessário determinar se as configurações recomendadas são compatíveis com o seu ambiente. Se não estiver, você deverá tomar decisões sobre a política de RAID e a configuração de disco e, em seguida, criar manualmente as camadas locais.' 
---
= Decidir qual método usar para criar camadas locais (agregados)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Embora o ONTAP forneça recomendações de práticas recomendadas para adicionar camadas locais automaticamente (criando agregados com provisionamento automático), é necessário determinar se as configurações recomendadas são compatíveis com o seu ambiente. Se não estiverem, você deverá tomar decisões sobre a política de RAID e a configuração de disco e, em seguida, criar manualmente as camadas locais.

Quando um nível local é criado automaticamente, o ONTAP analisa os discos sobressalentes disponíveis no cluster e gera uma recomendação sobre como os discos sobressalentes devem ser usados para adicionar camadas locais de acordo com as práticas recomendadas. O ONTAP exibe as configurações recomendadas. Você pode aceitar as recomendações ou adicionar manualmente os níveis locais.



== Antes de aceitar as recomendações do ONTAP

Se alguma das seguintes condições de disco estiver presente, elas devem ser abordadas antes de aceitar as recomendações do ONTAP:

* Discos em falta
* Flutuação nos números de disco sobressalente
* Discos não atribuídos
* Peças sobressalentes não zeradas
* Discos submetidos a testes de manutenção


Saiba mais sobre `storage aggregate auto-provision` o link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-auto-provision.html["Referência do comando ONTAP"^]na .



== Quando tem de utilizar o método manual

Em muitos casos, o layout recomendado do nível local será ideal para o seu ambiente. No entanto, se o cluster estiver executando o ONTAP 9.1 ou anterior, ou se o ambiente incluir as configurações a seguir, será necessário criar o nível local usando o método manual.


NOTE: A partir do ONTAP 9.11,1, você pode adicionar manualmente camadas locais com o Gerenciador de sistema.

* Agregados usando LUNs de array de terceiros
* Discos virtuais com Cloud Volumes ONTAP ou ONTAP Select
* Sistema MetroCluster
* SyncMirror
* Discos MSATA
* Camadas do FlashPool (agregados)
* Vários tipos ou tamanhos de disco são conetados ao nó




== Selecione o método para criar camadas locais (agregados)

Escolha o método que deseja usar:

* link:create-aggregates-auto-provision-task.html["Adicionar (criar) camadas locais (agregados) automaticamente"]
* link:create-aggregates-manual-task.html["Adicione (crie) camadas locais (agregados) manualmente"]


.Informações relacionadas
* https://docs.netapp.com/us-en/ontap-cli["Referência do comando ONTAP"^]

