---
permalink: disks-aggregates/determine-flash-pool-candidacy-cache-size-task.html 
sidebar: sidebar 
keywords: flash pool, candidacy, optimal cache size, local tier, aggregate 
summary: 'Antes de converter um nível local (agregado) existente em um nível local do Flash Pool, você pode determinar se o nível local está vinculado a e/S e o melhor tamanho de cache do Flash Pool para seu workload e orçamento. Você também pode verificar se o cache de um nível local do Flash Pool existente é dimensionado corretamente.' 
---
= Determine a candidatura do Flash Pool e o tamanho ideal do cache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de converter um nível local (agregado) existente em um nível local do Flash Pool, você pode determinar se o nível local está vinculado a e/S e o melhor tamanho de cache do Flash Pool para seu workload e orçamento. Você também pode verificar se o cache de um nível local do Flash Pool existente é dimensionado corretamente.

.Antes de começar
Você deve saber aproximadamente quando o nível local que você está analisando experimenta sua carga máxima.

.Passos
. Entrar no modo avançado:
+
`set advanced`

. Se você precisar determinar se um nível local (agregado) existente seria um bom candidato para conversão em um agregado de Flash Pool, determine o quão ocupados os discos no agregado estão durante um período de pico de carga e como isso está afetando a latência:
+
`statistics show-periodic -object disk:raid_group -instance _raid_group_name_ -counter disk_busy|user_read_latency -interval 1 -iterations 60`

+
Você pode decidir se reduzir a latência adicionando o cache Flash Pool faz sentido para esse agregado.

+
O comando a seguir mostra as estatísticas do primeiro grupo RAID do agregado "'aggr1":

+
`statistics show-periodic -object disk:raid_group -instance /aggr1/plex0/rg0 -counter disk_busy|user_read_latency -interval 1 -iterations 60`

. Inicie o Automated Workload Analyzer (AWA):
+
`storage automated-working-set-analyzer start -node _node_name_ -aggregate _aggr_name_`

+
A AWA começa a coletar dados da carga de trabalho para os volumes associados ao agregado especificado.

. Sair do modo avançado:
+
`set admin`

+
Permita que o AWA funcione até que um ou mais intervalos de pico de carga tenham ocorrido. O AWA coleta estatísticas de carga de trabalho para os volumes associados ao agregado especificado e analisa dados por até uma semana de duração. Executar AWA por mais de uma semana irá relatar apenas os dados coletados da semana mais recente. As estimativas de tamanho do cache baseiam-se nas cargas mais altas observadas durante o período de coleta de dados; a carga não precisa ser alta para todo o período de coleta de dados.

. Entrar no modo avançado:
+
`set advanced`

. Exibir a análise da carga de trabalho:
+
`storage automated-working-set-analyzer show -node _node_name_ -instance`

. Parar AWA:
+
`storage automated-working-set-analyzer stop _node_name_`

+
Todos os dados de workload são limpos e não estão mais disponíveis para análise.

. Sair do modo avançado:
+
`set admin`


