---
permalink: disks-aggregates/determine-flash-pool-aggregate-ssd-storage-task.html 
sidebar: sidebar 
keywords: determine, flash pool, aggregate, local tier, ssd storage pool 
summary: Você gerencia a camada local do Flash Pool de maneira diferente quando usa pools de storage SSD para fornecer seu cache do que quando usa SSDs discretos. 
---
= Determine se uma camada local de pool flash está usando um pool de storage SSD no ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar um nível local do Flash Pool adicionando uma ou mais unidades de alocação de um pool de storage SSD a um nível local de HDD existente.


NOTE: Antes do ONTAP 9,7, o Gerenciador de sistema usa o termo _agregado_ para descrever um nível _local_. Independentemente da sua versão do ONTAP, a CLI do ONTAP usa o termo _agregado_. Para saber mais sobre os níveis locais, link:../disks-aggregates/index.html["Discos e camadas locais"]consulte .

Você gerencia as camadas locais do Flash Pool de maneira diferente quando eles usam pools de storage SSD para fornecer seu cache do que quando usam SSDs discretos.

.Passo
. Exibir as unidades do nível local por grupo RAID:
+
`storage aggregate show-status _aggr_name_`

+
Se o nível local estiver usando um ou mais pools de armazenamento SSD, o valor `Position` da coluna para os grupos RAID SSD será exibido como `Shared`, e o nome do pool de armazenamento será exibido ao lado do nome do grupo RAID.


