---
permalink: disks-aggregates/determine-control-volume-space-aggregate-concept.html 
sidebar: sidebar 
keywords: determine, control, volume, space usage, aggregate, local tier 
summary: É possível determinar quais volumes do FlexVol estão usando mais espaço em um nível local e, especificamente, quais recursos estão usando o volume. 
---
= Determinar e controlar o uso de espaço de um volume em um nível local do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível determinar quais volumes do FlexVol estão usando mais espaço em um nível local e, especificamente, quais recursos estão usando o volume.

O `volume show-footprint` comando fornece informações sobre o espaço físico de um volume ou sobre o uso do espaço dentro do nível local que contém.


NOTE: Antes do ONTAP 9,7, o Gerenciador de sistema usa o termo _agregado_ para descrever um nível _local_. Independentemente da sua versão do ONTAP, a CLI do ONTAP usa o termo _agregado_. Para saber mais sobre os níveis locais, link:../disks-aggregates/index.html["Discos e camadas locais"]consulte .

O `volume show-footprint` comando mostra detalhes sobre o uso de espaço de cada volume em um nível local, incluindo volumes off-line. Este comando preenche a lacuna entre a saída `volume show-space` dos comandos e. `aggregate show-space` Todas as porcentagens são calculadas como uma porcentagem do tamanho do nível local.

O exemplo a seguir mostra a `volume show-footprint` saída do comando para um volume chamado testvol:

....
cluster1::> volume show-footprint testvol

      Vserver : thevs
      Volume  : testvol

      Feature                                   Used    Used%
      --------------------------------    ----------    -----
      Volume Data Footprint                  120.6MB       4%
      Volume Guarantee                        1.88GB      71%
      Flexible Volume Metadata               11.38MB       0%
      Delayed Frees                           1.36MB       0%
      Total Footprint                         2.01GB      76%
....
A tabela a seguir explica algumas das linhas-chave da saída do `volume show-footprint` comando e o que você pode fazer para tentar diminuir o uso do espaço por esse recurso:

|===


| Nome da linha/função | Descrição/conteúdo da linha | Algumas maneiras de diminuir 


 a| 
`Volume Data Footprint`
 a| 
A quantidade total de espaço usada no nível local contendo pelos dados de um volume no sistema de arquivos ativo e o espaço usado pelos snapshots do volume. Esta linha não inclui espaço reservado.
 a| 
* Eliminar dados do volume.
* Eliminar instantâneos do volume.




 a| 
`Volume Guarantee`
 a| 
A quantidade de espaço reservado pelo volume no nível local para gravações futuras. A quantidade de espaço reservado depende do tipo de garantia do volume.
 a| 
Alterar o tipo de garantia do volume para `none`.



 a| 
`Flexible Volume Metadata`
 a| 
A quantidade total de espaço usada no nível local pelos arquivos de metadados do volume.
 a| 
Nenhum método direto para controlar.



 a| 
`Delayed Frees`
 a| 
Blocos que o ONTAP usou para desempenho e não podem ser liberados imediatamente. Para destinos SnapMirror, esta linha tem um valor de `0` e não é apresentada.
 a| 
Nenhum método direto para controlar.



 a| 
`File Operation Metadata`
 a| 
A quantidade total de espaço reservado para metadados de operação de arquivo.
 a| 
Nenhum método direto para controlar.



 a| 
`Total Footprint`
 a| 
A quantidade total de espaço que o volume usa no nível local. É a soma de todas as linhas.
 a| 
Qualquer um dos métodos utilizados para diminuir o espaço utilizado por um volume.

|===
.Informações relacionadas
https://www.netapp.com/pdf.html?item=/media/19670-tr-3483.pdf["Relatório técnico da NetApp 3483: Provisionamento reduzido em um ambiente empresarial SAN NetApp ou SAN IP"^]
