---
permalink: disks-aggregates/fast-zeroing-drives-concept.html 
sidebar: sidebar 
keywords: fast, zero, drives 
summary: Em sistemas recém-instalados com o ONTAP 9.4 ou posterior e sistemas reinicializados com o ONTAP 9.4 ou posterior, _fast zero_ é usado para zero unidades. 
---
= Manualmente Fast zero drives
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Em sistemas recém-instalados com o ONTAP 9.4 ou posterior e sistemas reinicializados com o ONTAP 9.4 ou posterior, _fast zero_ é usado para zero unidades.

Com _fast zero_, as unidades são zeradas em segundos. Isso é feito automaticamente antes do provisionamento e reduz bastante o tempo necessário para inicializar o sistema, criar agregados ou expandir agregados quando unidades sobressalentes são adicionadas.

_A restauração rápida_ é suportada em SSDs e HDDs.


NOTE: _A restauração rápida_ não é suportada em sistemas atualizados a partir do ONTAP 9.3 ou anterior. O ONTAP 9.4 ou posterior deve ser instalado recentemente ou o sistema deve ser reinicializado. No ONTAP 9,3 e versões anteriores, as unidades também são zeradas automaticamente pelo ONTAP. No entanto, o processo leva mais tempo.

Se você precisar zerar manualmente uma unidade, você pode usar um dos seguintes métodos. No ONTAP 9.4 e posterior, a restauração manual de uma unidade também leva apenas segundos.

[role="tabbed-block"]
====
.Comando CLI
--
*Use um comando CLI para acelerar a zero unidades*

.Sobre esta tarefa
Admin Privileges são necessários para usar este comando.

.Passos
. Digite o comando CLI:
+
[source, cli]
----
storage disk zerospares
----


--
.Opções do menu de inicialização
--
*Selecione as opções no menu de inicialização para unidades de zero rápido*

.Sobre esta tarefa
* O aprimoramento de restauração rápida não suporta sistemas atualizados de uma versão anterior ao ONTAP 9.4.
* Se qualquer nó no cluster contiver um nível local (agregado) com unidades de zeragem rápida, não será possível reverter o cluster para o ONTAP 9.2 ou anterior.


.Passos
. No menu de inicialização, selecione uma das seguintes opções:
+
** (4) limpe a configuração e inicialize todos os discos
** (9a) Desparticionar todos os discos e remover suas informações de propriedade
** (9b) limpe a configuração e inicialize o nó com discos inteiros




--
====