---
permalink: disks-aggregates/manage-local-tiers-overview-concept.html 
sidebar: sidebar 
keywords: local tier, aggregate, prepare, add, create, disks, RAID, delete, manage local tier, manage aggregate 
summary: 'É possível adicionar camadas locais (agregados), gerenciar o uso e adicionar capacidade (discos) a elas usando o System Manager ou a CLI.' 
---
= Gerenciar camadas locais (agregados)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Use o Gerenciador do sistema ou a CLI do ONTAP para adicionar camadas locais (agregados), gerenciar seu uso e adicionar capacidade (discos) a elas.

Você pode executar as seguintes tarefas:

* link:add-local-tier-overview-task.html["Adicionar (criar) um nível local (agregado)"]
+
Para adicionar um nível local, você segue um fluxo de trabalho específico. Você determina o número de discos ou partições de disco que você precisa para o nível local e decide qual método usar para criar o nível local. Você pode adicionar níveis locais automaticamente permitindo que o ONTAP atribua a configuração ou especifique manualmente a configuração.

* link:manage-use-local-tiers-overview-task.html["Gerenciar o uso de camadas locais (agregados)"]
+
Para os níveis locais existentes, você pode renomeá-los, definir seus custos de Mídia ou determinar suas informações de unidade e grupo RAID. É possível modificar a configuração RAID de uma camada local e atribuir camadas locais a VMs de storage (SVMs). É possível modificar a configuração RAID de uma camada local e atribuir camadas locais a VMs de storage (SVMs). É possível determinar quais volumes residem em um nível local e quanto espaço eles usam em um nível local. Você pode controlar quanto espaço os volumes podem usar. Você pode realocar a propriedade do nível local com um par de HA. Você também pode excluir um nível local.

* link:add-capacity-local-tier-overview-task.html["Adicionar capacidade (discos) a um nível local (agregado)"]
+
Usando métodos diferentes, você segue um fluxo de trabalho específico para adicionar capacidade. É possível adicionar discos a uma camada local e adicionar unidades a um nó ou compartimento. Se necessário, você pode corrigir partições sobressalentes desalinhadas.


