---
permalink: disks-aggregates/methods-create-space-aggregate-concept.html 
sidebar: sidebar 
keywords: methods, create, space, aggregate, local tier, add capacity, disk 
summary: Se um nível local ficar sem espaço livre, vários problemas podem resultar que vão desde a perda de dados até a desativação da garantia de um volume. Há várias maneiras de criar mais espaço em um nível local. 
---
= Métodos para criar espaço em um nível local do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se um nível local ficar sem espaço livre, vários problemas podem resultar que vão desde a perda de dados até a desativação da garantia de um volume. Há várias maneiras de criar mais espaço em um nível local.

Todos os métodos têm várias consequências. Antes de tomar qualquer ação, você deve ler a seção relevante na documentação.

A seguir estão algumas maneiras comuns de fazer espaço no nível local, em ordem de menos para a maioria das consequências:

* Adicione discos ao nível local.
* Mova alguns volumes para outro nível local com espaço disponível.
* Diminua o tamanho dos volumes com garantia de volume no nível local.
* Exclua instantâneos de volume desnecessários se o tipo de garantia do volume for "'nenhum'".
* Eliminar volumes desnecessários.
* Habilite recursos de economia de espaço, como deduplicação ou compactação.
* (Temporariamente) desabilite recursos que estão usando uma grande quantidade de metadados .

