---
permalink: disks-aggregates/sanitization-tips-concept.html 
sidebar: sidebar 
keywords: disk, disk sanitization, local tier, aggregate, sensitive data, sanitize 
summary: Se você estiver criando ou fazendo backup de camadas locais para conter dados que possam precisar ser higienizados, seguir algumas diretrizes simples reduzirá o tempo necessário para higienizar seus dados. 
---
= Dicas para criar e fazer backup de camadas locais contendo dados a serem higienizados no ONTAP
:allow-uri-read: 


[role="lead"]
Se você estiver criando ou fazendo backup de camadas locais para conter dados que possam precisar ser higienizados, seguir algumas diretrizes simples reduzirá o tempo necessário para higienizar seus dados.

* Certifique-se de que os níveis locais que contêm dados confidenciais não sejam maiores do que o necessário.
+
Se forem maiores do que o necessário, a sanitização requer mais tempo, espaço em disco e largura de banda.

* Ao fazer backup de camadas locais que contêm dados confidenciais, evite fazer backup deles em níveis locais que também contenham grandes quantidades de dados não confidenciais.
+
Isso reduz os recursos necessários para mover dados não confidenciais antes de higienizar dados confidenciais.


