---
permalink: disks-aggregates/set-cache-data-retention-policy-flash-pool-task.html 
sidebar: sidebar 
keywords: set, cache-retention policy, flash pool 
summary: 'Você pode atribuir políticas de retenção de cache a volumes nas camadas locais (agregados) do Flash Pool. Os dados em volumes com uma política de alta retenção de cache permanecem no cache por mais tempo e os dados em volumes com uma política de baixa retenção de cache são removidos mais cedo. Isso aumenta o desempenho de seus workloads críticos, pois as informações de alta prioridade são acessíveis a uma taxa mais rápida por um período mais longo.' 
---
= Definir a política de retenção de cache para camadas locais (agregados) do Flash Pool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode atribuir políticas de retenção de cache a volumes nas camadas locais (agregados) do Flash Pool. Os dados em volumes com uma política de alta retenção de cache permanecem no cache por mais tempo e os dados em volumes com uma política de baixa retenção de cache são removidos mais cedo. Isso aumenta o desempenho de seus workloads críticos, pois as informações de alta prioridade são acessíveis a uma taxa mais rápida por um período mais longo.

.O que você vai precisar
Você deve saber se o seu sistema tem quaisquer condições que possam impedir que a política de retenção de cache tenha um impactos sobre quanto tempo seus dados permanecem no cache.

.Passos
Use a CLI no modo de privilégio avançado para executar as seguintes etapas:

. Altere a configuração de privilégios para avançado:
+
`set -privilege advanced`

. Verifique a política de retenção de cache do volume:
+
Por padrão, a política de retenção de cache é "normal".

. Defina a política de retenção de cache:
+
|===


| Versão de ONTAP | Comando 


 a| 
ONTAP 9.0, 9,1
 a| 
`priority hybrid-cache set volume_name read-cache=read_cache_value write-cache=write_cache_value cache-retention-priority=cache_retention_policy`

Defina `cache_retention_policy` como `high` para os dados que você deseja permanecer no cache por mais tempo. Defina `cache_retention_policy` como `low` para os dados que você deseja remover do cache mais cedo.



 a| 
ONTAP 9 .2 ou posterior
 a| 
`volume modify -volume volume_name -vserver vserver_name -caching-policy policy_name.`

|===
. Verifique se a política de retenção de cache do volume foi alterada para a opção selecionada.
. Retornar a configuração de privilégio para admin:
+
`set -privilege admin`


