---
permalink: disks-aggregates/sizing-raid-groups-concept.html 
sidebar: sidebar 
keywords: consideration, size, raid groups 
summary: 'A configuração de um tamanho de grupo RAID ideal requer uma troca de fatores. Você precisa decidir quais fatores, como a velocidade da recriação de RAID, a garantia contra o risco de perda de dados devido a falha da unidade, a otimização da performance de e/S e a maximização do espaço de storage, são os mais importantes para a categoria local (agregado) que você está configurando.' 
---
= Considerações para dimensionar grupos RAID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A configuração de um tamanho de grupo RAID ideal requer uma troca de fatores. Você precisa decidir quais fatores - velocidade da reconstrução RAID, garantia contra risco de perda de dados devido a falha da unidade, otimização do desempenho de e/S e maximização do espaço de storage de dados - são mais importantes para o agregado (camada local) que você está configurando.

Ao criar grupos RAID maiores, você maximiza o espaço disponível para armazenamento de dados para a mesma quantidade de armazenamento usada para paridade (também conhecido como o "'imposto de paridade"). Por outro lado, quando um disco falha em um grupo RAID maior, o tempo de reconstrução é aumentado, afetando o desempenho por um período de tempo maior. Além disso, ter mais discos em um grupo RAID aumenta a probabilidade de uma falha de vários discos dentro do mesmo grupo RAID.



== Grupos RAID de HDD ou LUN de matriz

Siga estas diretrizes ao dimensionar seus grupos RAID compostos por HDDs ou LUNs de storage:

* Todos os grupos RAID em um nível local (agregado) devem ter o mesmo número de discos.
+
Embora você possa ter até 50% menos ou mais do que o número de discos em diferentes grupos raid em um nível local, isso pode levar a gargalos de desempenho em alguns casos, por isso é melhor evitado.

* O intervalo recomendado de números de discos do grupo RAID está entre 12 e 20.
+
A confiabilidade dos discos de desempenho pode suportar um tamanho de grupo RAID de até 28 TB, se necessário.

* Se você puder satisfazer as duas primeiras diretrizes com vários números de disco do grupo RAID, escolha o número maior de discos.




== Grupos RAID de SSD em camadas locais (agregados) do Flash Pool

O tamanho do grupo RAID SSD pode ser diferente do tamanho do grupo RAID para os grupos RAID de HDD em um nível local do Flash Pool (agregado). Normalmente, você deve garantir que tenha apenas um grupo RAID SSD para uma camada local de Flash Pool, para minimizar o número de SSDs necessários para a paridade.



== Grupos RAID SSD em camadas locais de SSD (agregados)

Você deve seguir estas diretrizes ao dimensionar seus grupos RAID compostos de SSDs:

* Todos os grupos RAID em um nível local (agregado) devem ter um número semelhante de unidades.
+
Os grupos RAID não precisam ter exatamente o mesmo tamanho, mas você deve evitar ter qualquer grupo RAID que tenha menos de metade do tamanho de outros grupos RAID no mesmo nível local, quando possível.

* Para RAID-DP, o intervalo recomendado de tamanho do grupo RAID é entre 20 e 28.

