---
permalink: disks-aggregates/update-disk-qualification-package-concept.html 
sidebar: sidebar 
keywords: update, desk, qualification, package 
summary: 'O Pacote de Qualificação de disco (DQP) adiciona suporte completo para unidades recém-qualificadas. Antes de atualizar o firmware da unidade ou adicionar novos tipos ou tamanhos de unidade a um cluster, é necessário atualizar o DQP. Uma prática recomendada é também atualizar o DQP regularmente; por exemplo, a cada trimestre ou semestralmente.' 
---
= Saiba quando atualizar o Pacote de Qualificação de disco do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Pacote de Qualificação de disco (DQP) adiciona suporte completo para unidades recém-qualificadas. Antes de atualizar o firmware da unidade ou adicionar novos tipos ou tamanhos de unidade a um cluster, é necessário atualizar o DQP. Uma prática recomendada é também atualizar o DQP regularmente; por exemplo, a cada trimestre ou semestralmente.

Você precisa baixar e instalar o DQP nas seguintes situações:

* Sempre que você adicionar um novo tipo ou tamanho de unidade ao nó
+
Por exemplo, se você já tiver unidades de 1 TB e adicionar unidades de 2 TB, precisará verificar a atualização DQP mais recente.

* Sempre que atualizar o firmware do disco
* Sempre que estiverem disponíveis ficheiros DQP ou firmware de disco mais recentes
* Sempre que você atualizar para uma nova versão do ONTAP.
+
O DQP não é atualizado como parte de uma atualização do ONTAP.



.Informações relacionadas
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware/download/DISKQUAL/ALL/qual_devices.zip["NetApp Downloads: Pacote de Qualificação de disco"^]

https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Downloads do NetApp: Firmware da unidade de disco"^]
