---
permalink: flexgroup/configure-automatic-grow-shrink-task.html 
sidebar: sidebar 
keywords: configure, flexgroup, volume, automatic, grow, shrink, size 
summary: A partir do ONTAP 9.3, você pode configurar volumes FlexGroup para aumentar e diminuir automaticamente de acordo com a quantidade de espaço que eles atualmente exigem. 
---
= Configure os volumes do FlexGroup para aumentar e diminuir automaticamente o tamanho
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.3, você pode configurar volumes FlexGroup para aumentar e diminuir automaticamente de acordo com a quantidade de espaço que eles atualmente exigem.

.O que você vai precisar
O volume FlexGroup deve estar online.

.Sobre esta tarefa
É possível dimensionar volumes FlexGroup em dois modos:

* Aumentar o tamanho do volume automaticamente(`grow`)
+
O crescimento automático ajuda a evitar que um volume de FlexGroup fique sem espaço, se o agregado puder fornecer mais espaço. Pode configurar o tamanho máximo para o volume. O aumento é acionado automaticamente com base na quantidade de dados que estão sendo gravados no volume em relação à quantidade atual de espaço usado e quaisquer limites definidos.

+
Por padrão, o tamanho máximo para o qual um volume pode crescer é de 120% do tamanho no qual o crescimento automático é ativado. Se você precisar garantir que o volume pode crescer para ser maior do que isso, você deve definir o tamanho máximo para o volume de acordo.

* Reduzir o tamanho do volume automaticamente(`grow_shrink`)
+
O encolhimento automático impede que um volume seja maior do que o necessário, liberando espaço no agregado para uso por outros volumes.

+
O Autoshink só pode ser usado em combinação com o crescimento automático para atender às demandas de espaço em constante mudança e não está disponível sozinho. Quando a opção Autoshink está ativada, o ONTAP gerencia automaticamente o comportamento de encolhimento de um volume para evitar um ciclo infinito de ações com crescimento automático e com redução automática.



À medida que um volume aumenta, o número máximo de arquivos que ele pode conter pode ser aumentado automaticamente. Quando um volume é reduzido, o número máximo de arquivos que ele pode conter permanece inalterado e um volume não pode ser encolhido automaticamente abaixo do tamanho que corresponde ao número máximo de arquivos atual. Por esse motivo, pode não ser possível reduzir automaticamente um volume até o tamanho original.

.Passo
. Configure o volume para crescer e diminuir seu tamanho automaticamente: `volume autosize -vserver vserver_name -volume vol_name -mode [grow | grow_shrink]`
+
Você também pode especificar o tamanho máximo, o tamanho mínimo e os limites para aumentar ou diminuir o volume.

+
O comando a seguir habilita alterações automáticas de tamanho para um volume chamado FG1. O volume é configurado para crescer até um tamanho máximo de 5 TB quando está 70% cheio.

+
[listing]
----
cluster1::> volume autosize -volume fg1 -mode grow -maximum-size 5TB -grow-threshold-percent 70
vol autosize: volume "vs_src:fg1" autosize settings UPDATED.
----

