---
permalink: flexgroup/convert-flexvol-concept.html 
sidebar: sidebar 
keywords: consider, convert, flexvol, volume, flexgroup, autobalance, give back, giveback, revert, split, space limit, limit 
summary: Você deve estar ciente dos recursos e operações com suporte antes de decidir converter volumes do FlexVol para volumes do FlexGroup. 
---
= Saiba mais sobre a conversão de volumes ONTAP FlexVol para volumes FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você quiser expandir um FlexVol volume além do limite de espaço, você pode converter o FlexVol volume em um volume FlexGroup. A partir do ONTAP 9.7, você pode converter volumes FlexVol autônomos ou volumes FlexVol que estão em uma relação do SnapMirror para volumes do FlexGroup.



== Considerações para converter volumes FlexVol para volumes FlexGroup

Você deve estar ciente do link:supported-unsupported-config-concept.html["recursos e operações suportados"] antes de decidir converter volumes FlexVol em volumes FlexGroup .



== Operações não suportadas durante a conversão

As seguintes operações não são permitidas quando a conversão de volume está em andamento:

* Movimentação de volume
* Agregar o equilíbrio automático
* Realocação de agregados
* Takeover planejado e giveback em uma configuração de alta disponibilidade
* Giveback manual e automático em uma configuração de alta disponibilidade
* Atualização e reversão do cluster
* Divisão de volume FlexClone
* Rehost de volume
* Modificação de volume e dimensionamento automático
* Mudar o nome do volume
* Anexando um armazenamento de objetos a um agregado
* Switchover negociado na configuração do MetroCluster
* Operações da SnapMirror
* Restaurar a partir de um instantâneo
* Operações de cota
* Operações de eficiência de storage


Você pode executar essas operações no volume FlexGroup após a conversão bem-sucedida.



== Configurações que não são compatíveis com o FlexGroup volumes

* Volume off-line ou restrito
* Volume raiz do SVM
* SAN
* SMB 1,0
* Namespaces NVMe
* Serviço de cópia de sombra de volume remoto (VSS)

