---
permalink: flexgroup/create-qtrees-task.html 
sidebar: sidebar 
keywords: create, qtrees, flexgroup, volume, flex group, segment, smb oplock, 
summary: Você pode criar qtrees com volumes FlexGroup que permitem particionar seus volumes FlexGroup em segmentos menores e gerenciados individualmente. 
---
= Crie qtrees com volumes FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Começando com ONTAP 9.3, você pode criar qtrees com volumes FlexGroup. Qtrees permitem que você particione seus volumes FlexGroup em segmentos menores que você pode gerenciar individualmente.

.Sobre esta tarefa
* Se o volume FlexGroup de origem tiver qtrees em uma relação SnapMirror, o cluster de destino deve estar executando o ONTAP 9.3 ou posterior (uma versão do software ONTAP que suporta qtrees).
* A partir do ONTAP 9.5, as estatísticas de qtree são suportadas para volumes FlexGroup.


.Passos
. Crie uma qtree no volume FlexGroup:
+
[source, cli]
----
volume qtree create -vserver <vserver_name> -volume <volume_name> -qtree <qtree_name>
----
+
Opcionalmente, você pode especificar o estilo de segurança, os princípios SMB, as permissões UNIX e a política de exportação para a qtree.

+
[listing]
----
cluster1::> volume qtree create -vserver vs0 -volume fg1 -qtree qtree1 -security-style mixed
----


.Informações relacionadas
link:../volumes/index.html["Gerenciamento de storage lógico"]
