---
permalink: flexgroup/create-snapvault-relationship-task.html 
sidebar: sidebar 
keywords: create, snapvault, relationship, flexgroup, volumes 
summary: Você pode configurar uma relação do SnapVault e atribuir uma política do SnapVault à relação para criar um backup do SnapVault. 
---
= Criar relacionamentos do SnapVault para o ONTAP FlexGroup volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar uma relação do SnapVault e atribuir uma política do SnapVault à relação para criar um backup do SnapVault.

.Antes de começar
Você precisa estar ciente das considerações para criar uma relação do SnapVault para o FlexGroup volumes.

.Passos
. Crie um volume FlexGroup de destino do tipo `DP` que tenha o mesmo número de constituintes do volume FlexGroup de origem:
+
.. A partir do cluster de origem, determine o número de componentes no volume FlexGroup de origem: `volume show -volume volume_name* -is-constituent true`
+
[listing]
----
cluster1::> volume show  -volume src* -is-constituent true
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vss       src          -            online     RW         400TB   172.86GB  56%
vss       src__0001    Aggr_cmode   online     RW         25GB    10.86TB   56%
vss       src__0002    aggr1        online     RW         25TB    10.86TB   56%
vss       src__0003    Aggr_cmode   online     RW         25TB    10.72TB   57%
vss       src__0004    aggr1        online     RW         25TB    10.73TB   57%
vss       src__0005    Aggr_cmode   online     RW         25TB    10.67TB   57%
vss       src__0006    aggr1        online     RW         25TB    10.64TB   57%
vss       src__0007    Aggr_cmode   online     RW         25TB    10.63TB   57%
...
----
.. A partir do cluster de destino, crie um volume do tipo FlexGroup de destino `DP` com o mesmo número de componentes que o do volume FlexGroup de origem.
+
[listing]
----
cluster2::> volume create -vserver vsd -aggr-list aggr1,aggr2 -aggr-list-multiplier 8 -size 400TB -type DP dst

Warning: The FlexGroup volume "dst" will be created with the following number of constituents of size 25TB: 16.
Do you want to continue? {y|n}: y
[Job 766] Job succeeded: Successful
----
.. A partir do cluster de destino, verifique o número de componentes no volume FlexGroup de destino: `volume show -volume volume_name* -is-constituent true`
+
[listing]
----
cluster2::> volume show  -volume dst* -is-constituent true
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vsd       dst          -            online     RW         400TB   172.86GB  56%
vsd       dst__0001    Aggr_cmode   online     RW         25GB    10.86TB   56%
vsd       dst__0002    aggr1        online     RW         25TB    10.86TB   56%
vsd       dst__0003    Aggr_cmode   online     RW         25TB    10.72TB   57%
vsd       dst__0004    aggr1        online     RW         25TB    10.73TB   57%
vsd       dst__0005    Aggr_cmode   online     RW         25TB    10.67TB   57%
vsd       dst__0006    aggr1        online     RW         25TB    10.64TB   57%
vsd       dst__0007    Aggr_cmode   online     RW         25TB    10.63TB   57%
...
----


. Criar uma agenda de trabalhos: `job schedule cron create -name job_name -month month -dayofweek day_of_week -day day_of_month -hour hour -minute minute`
+
Para `-month`, , `-dayofweek`, e `-hour`, é possível especificar `all` para executar o trabalho todos os meses, dia da semana e hora, respetivamente.

+
O exemplo a seguir cria um horário de trabalho chamado `my_weekly` que é executado aos sábados às 3:00 da manhã:

+
[listing]
----
cluster1::> job schedule cron create -name my_weekly -dayofweek "Saturday" -hour 3 -minute 0
----
. Crie uma política SnapVault e defina uma regra para a política SnapVault:
+
.. Crie uma política de tipo personalizada `vault` para o relacionamento SnapVault: `snapmirror policy create -vserver svm_name -policy policy_name -type vault`
.. Defina uma regra para a política SnapVault que determina quais instantâneos são transferidos durante operações de inicialização e atualização: `snapmirror policy add-rule -vserver svm_name -policy policy_for_rule - snapmirror-label snapmirror-label -keep retention_count -schedule schedule`


+
Se você não criar uma política personalizada, especifique a `XDPDefault` política para relacionamentos do SnapVault.

. Criar uma relação SnapVault: `snapmirror create -source-path src_svm:src_flexgroup -destination-path dest_svm:dest_flexgroup -type XDP -schedule schedule_name -policy XDPDefault`
+
No ONTAP 9.4 e anteriores, se a política não for especificada com o `snapmirror create` comando, a `MirrorAllSnapshots` política será usada por padrão. No ONTAP 9.5, se a política não for especificada com o `snapmirror create` comando, a `MirrorAndVault` política será usada por padrão.

+
[listing]
----
cluster2::> snapmirror create -source-path vss:srcFG -destination-path vsd:dstFG -type XDP -schedule Daily -policy XDPDefault
----
. A partir do cluster de destino, inicialize a relação SnapVault executando uma transferência de linha de base: `snapmirror initialize -destination-path dest_svm:dest_flexgroup`
+
[listing]
----
cluster2::> snapmirror initialize -destination-path vsd:dst
Operation is queued: snapmirror initialize of destination "vsd:dst".
----

