---
permalink: flexgroup/enable-svm-protection-task.html 
sidebar: sidebar 
keywords: enable, svm, protection, flexgroup, volume 
summary: Quando o sinalizador de proteção SVM DR está definido como desprotegido em um volume FlexGroup, você pode definir o sinalizador como protegido para habilitar a proteção SVM DR. 
---
= Ativar a proteção contra SVM em um volume FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando o sinalizador de proteção do SVM DR está definido como `unprotected` em um volume FlexGroup, você pode definir o sinalizador para `protected` habilitar a proteção contra SVM DR.

.O que você vai precisar
* A relação do SVM DR entre o primário e o secundário está saudável.
* O parâmetro de proteção do SVM DR é definido como `unprotected`.


.Passos
. Ative a proteção utilizando o `volume modify` para alterar o `vserver-dr-protection` parâmetro do volume FlexGroup para `protected`.
+
[listing]
----
cluster2::> volume modify -vserver vs1 -volume fg_src -vserver-dr-protection protected
[Job 5384] Job is queued: Modify fg_src.
[Job 5384] Steps completed: 4 of 4.
cluster2::>
----
. Atualize o SVM no local secundário: `snapmirror update -destination-path destination_svm_name -source-path source_svm_name`
+
[listing]
----
snapmirror update -destination-path vs1_dst: -source-path vs1:
----
. Verifique se a relação SnapMirror está saudável: `snapmirror show`
+
[listing]
----
cluster2::> snapmirror show
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs1:        XDP  vs1_dst:     Snapmirrored
                                      Idle           -         true    -
----
. Verifique se a relação FlexGroup SnapMirror está saudável: `snapmirror show -expand`
+
[listing]
----
cluster2::> snapmirror show -expand
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs1:        XDP  vs1_dst:     Snapmirrored
                                      Idle           -         true    -
vs1:fg_src  XDP  vs1_dst:fg_src
                              Snapmirrored
                                      Idle           -         true    -
vs1:fg_src__0001
            XDP  vs1_dst:fg_src__0001
                              Snapmirrored
                                      Idle           -         true    -
vs1:fg_src__0002
            XDP  vs1_dst:fg_src__0002
                              Snapmirrored
                                      Idle           -         true    -
vs1:fg_src__0003
            XDP  vs1_dst:fg_src__0003
                              Snapmirrored
                                      Idle           -         true    -
vs1:fg_src__0004
            XDP  vs1_dst:fg_src__0004
                              Snapmirrored
                                      Idle           -         true    -
6 entries were displayed.
----

