---
permalink: flexgroup/expand-destination-snapmirror-relationship-task.html 
sidebar: sidebar 
keywords: expand, destination, flexgroup, volume, snapmirror, relationship 
summary: Você pode expandir o volume FlexGroup de destino e restabelecer a relação SnapMirror automaticamente ou manualmente. Por padrão, a relação SnapMirror é definida para expansão automática e o volume FlexGroup de destino se expande automaticamente se o volume de origem for expandido. 
---
= Expanda o volume ONTAP FlexGroup de destino de uma relação SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode expandir o volume FlexGroup de destino e restabelecer a relação SnapMirror automaticamente ou manualmente. Por padrão, a relação SnapMirror é definida para expansão automática e o volume FlexGroup de destino se expande automaticamente se o volume de origem for expandido.

.Antes de começar
* O volume FlexGroup de origem deve ter sido expandido.
* A relação SnapMirror deve estar `SnapMirrored` no estado.
+
A relação SnapMirror não deve ser quebrada ou excluída.



.Sobre esta tarefa
* Quando o volume FlexGroup de destino é criado, o volume é configurado para expansão automática por padrão.
+
Pode modificar o volume FlexGroup de destino para expansão manual, se necessário.

+
[NOTE]
====
A prática recomendada é expandir o volume FlexGroup de destino automaticamente.

====
* Todas as operações do SnapMirror falham até que o volume FlexGroup de origem e o volume FlexGroup de destino tenham expandido e tenham o mesmo número de componentes.
* Se você expandir o volume FlexGroup de destino depois que a relação SnapMirror for interrompida ou excluída, não será possível sincronizar novamente a relação original.
+
Se pretender reutilizar o volume FlexGroup de destino, não expanda o volume depois de eliminar a relação SnapMirror.



.Opções
* Execute uma transferência de atualização para expandir automaticamente o volume FlexGroup de destino:
+
.. Execute uma transferência de atualização do SnapMirror: `snapmirror update -destination-path svm:vol_name`
.. Verifique se o status da relação SnapMirror está no `SnapMirrored` estado: `snapmirror show`
+
[listing]
----
cluster2::> snapmirror show
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs_src:src_fg
            XDP  vs_dst:dst_fg
                              Snapmirrored
                                      Idle           -         true   -
----


+
Com base no tamanho e disponibilidade dos agregados, os agregados são selecionados automaticamente e novos constituintes que correspondem aos constituintes do volume FlexGroup de origem são adicionados ao volume FlexGroup de destino. Após a expansão, uma operação de ressincronização é acionada automaticamente.

* Expanda o volume FlexGroup de destino manualmente:
+
.. Se a relação SnapMirror estiver no modo de expansão automática, defina a relação SnapMirror para o modo de expansão manual: `snapmirror modify -destination-path svm:vol_name -is-auto-expand-enabled false`
+
[listing]
----
cluster2::> snapmirror modify -destination-path vs_dst:dst_fg -is-auto-expand-enabled false
Operation succeeded: snapmirror modify for the relationship with destination "vs_dst:dst_fg".
----
.. Quiesce a relação de SnapMirror: `snapmirror quiesce -destination-path svm:vol_name`
+
[listing]
----
cluster2::> snapmirror quiesce -destination-path vs_dst:dst_fg
Operation succeeded: snapmirror quiesce for destination "vs_dst:dst_fg".
----
.. Expanda o volume FlexGroup de destino: `+volume expand -vserver vserver_name -volume fg_name -aggr-list aggregate name,... [-aggr-list-multiplier constituents_per_aggr]+`
+
[listing]
----
cluster2::> volume expand -volume dst_fg -aggr-list aggr1 -aggr-list-multiplier 2  -vserver vs_dst

Warning: The following number of constituents of size 50GB will be added to FlexGroup "dst_fg": 2.
Do you want to continue? {y|n}: y
[Job 68] Job succeeded: Successful
----
.. Ressincronizar a relação SnapMirror: `snapmirror resync -destination-path svm:vol_name`
+
[listing]
----
cluster2::> snapmirror resync -destination-path vs_dst:dst_fg
Operation is queued: snapmirror resync to destination "vs_dst:dst_fg".
----
.. Verifique se o status da relação SnapMirror é `SnapMirrored`: `snapmirror show`
+
[listing]
----
cluster2::> snapmirror show
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs_src:src_fg
            XDP  vs_dst:dst_fg
                              Snapmirrored
                                      Idle           -         true   -
----




.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=snapmirror["SnapMirror"^]

