---
permalink: flexgroup/expand-snapmirror-relationship-task.html 
sidebar: sidebar 
keywords: expand, flexgroup, volume, snapmirror, relationship, snap mirror, flex group, manual, automatic, automatically, disaster 
summary: A partir do ONTAP 9.3, é possível expandir o volume FlexGroup de origem e o volume FlexGroup de destino que estão em uma relação do SnapMirror adicionando novos constituintes aos volumes. Pode expandir os volumes de destino manualmente ou automaticamente. 
---
= Expanda volumes do FlexGroup em uma relação do SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.3, é possível expandir o volume FlexGroup de origem e o volume FlexGroup de destino que estão em uma relação do SnapMirror adicionando novos constituintes aos volumes. Pode expandir os volumes de destino manualmente ou automaticamente.

.Sobre esta tarefa
* Após a expansão, o número de componentes no volume FlexGroup de origem e no volume FlexGroup de destino de uma relação SnapMirror deve corresponder.
+
Se o número de componentes nos volumes não corresponder, as transferências SnapMirror falharão.

* Você não deve executar nenhuma operação SnapMirror quando o processo de expansão estiver em andamento.
* Se um desastre ocorrer antes que o processo de expansão seja concluído, você deve quebrar o relacionamento do SnapMirror e esperar até que a operação seja bem-sucedida.
+
[NOTE]
====
Você deve quebrar o relacionamento do SnapMirror quando o processo de expansão estiver em andamento apenas no caso de um desastre. No caso de um desastre, a operação de interrupção pode levar algum tempo para ser concluída. Você deve esperar que a operação de interrupção seja concluída com êxito antes de executar uma operação ressincronizada. Se a operação de interrupção falhar, você deve tentar novamente a operação de interrupção. Se a operação de quebra falhar, alguns dos novos constituintes poderão permanecer no volume FlexGroup de destino após a operação de quebra. É melhor excluir esses constituintes manualmente antes de prosseguir.

====

