---
permalink: flexgroup/increase-capacity-task.html 
sidebar: sidebar 
keywords: increase, size, flexgroup, volume, flex group 
summary: Aumente o tamanho do volume FlexGroup adicionando mais capacidade aos constituintes existentes do volume ou expandindo o volume FlexGroup com novos volumes membros. 
---
= Aumente o tamanho dos volumes ONTAP FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode aumentar o tamanho de um volume FlexGroup adicionando mais capacidade a todos os volumes membros existentes (constituintes) do volume FlexGroup ou expandindo o volume FlexGroup com novos volumes membros.  Um volume FlexGroup não pode ter mais de 200 volumes membros.

Você também pode aumentar o tamanho de um volume individual dentro de um volume FlexGroup , se necessário.

.Antes de começar
Espaço suficiente deve estar disponível nos agregados.

.Sobre esta tarefa
Se você quiser adicionar mais espaço, você pode aumentar o tamanho coletivo do volume FlexGroup. Aumentar o tamanho de um volume FlexGroup redimensiona os volumes de membros existentes do volume FlexGroup.

Se você quiser melhorar o desempenho, pode expandir o volume FlexGroup. Você pode querer expandir um volume do FlexGroup e adicionar novos volumes de membros nas seguintes situações:

* Novos nós foram adicionados ao cluster.
* Novos níveis locais (agregados) foram criados nos nós existentes.
* Os volumes de membros existentes do volume FlexGroup atingiram o tamanho máximo de FlexVol para o hardware (100TB ou 300TB se link:../volumes/enable-large-vol-file-support-task.html["suporte de grande volume"] tiver sido ativado) e, portanto, o volume FlexGroup não pode ser redimensionado sem adicionar volumes de membros adicionais.


[NOTE]
====
Se você modificar um volume FlexGroup para incluir mais membros, os snapshots criados anteriormente serão considerados "parciais" e estarão disponíveis apenas para acesso por clientes do  `.snapshot` diretório ou na aba *Versões Anteriores*.

Se um snapshot for considerado "parcial", ele não poderá ser usado em operações de SnapRestore. No entanto, snapshots parciais podem ser usados para restaurar arquivos individuais de  `.snapshot` diretórios ou na aba *Versões Anteriores*.

====
Em versões anteriores ao ONTAP 9,3, não expanda volumes do FlexGroup depois que um relacionamento do SnapMirror for estabelecido. Se você expandir o volume FlexGroup de origem depois de quebrar a relação SnapMirror em versões anteriores ao ONTAP 9.3, será necessário realizar uma transferência de linha de base para o volume FlexGroup de destino novamente. A partir do ONTAP 9.3, é possível expandir volumes do FlexGroup que estão em uma relação do SnapMirror.

.Passos
. Aumente o tamanho do volume FlexGroup aumentando a capacidade ou a performance do volume FlexGroup, conforme necessário:
+
|===


| Se você quiser aumentar a... | Então faça isso... 


 a| 
Capacidade do volume FlexGroup
 a| 
Redimensione todos os volumes membros do volume FlexGroup :

`volume modify -vserver <svm_name> -volume <fg_name> -size <new_size>`



 a| 
Desempenho para o volume FlexGroup
 a| 
Expanda o volume FlexGroup adicionando novos volumes de membros (constituintes):

`+volume expand -vserver vserver_name -volume fg_name -aggr-list aggregate name,... [-aggr-list-multiplier constituents_per_aggr]+`

O valor padrão do `-aggr-list-multiplier` parâmetro é 1.

Ao expandir um volume FlexGroup com link:../fabricpool/index.html["FabricPool"]o , todas as camadas locais (agregados) precisam ser conectadas à mesma camada de nuvem.

|===


Supondo que agregados existentes (camadas locais) ou volumes de membros não tenham atingido suas capacidades máximas (100/300TB ou dois bilhões de arquivos cada), é preferível aumentar o tamanho geral do volume FlexGroup em vez de adicionar volumes de membros adicionais.

Use a expansão de volume somente se o aumento do tamanho do volume ou da contagem de arquivos existente não for uma opção ou se o FlexGroup estiver sendo expandido pelo novo hardware. O mesmo número de volumes de membros deve ser adicionado a todos os nós para garantir um desempenho consistente. Por exemplo, se um volume FlexGroup existente tiver 8 volumes membros com quatro volumes membros por nó, adicionar dois membros por nó resultará em 12 volumes membros, seis volumes membros por nó.

Ao adicionar novos membros a novos nós, tente manter um número consistente de volumes de membros por nó, como nos nós existentes. Por exemplo, se um volume FlexGroup existente tiver 8 volumes membros com quatro volumes membros por nó, se os volumes FlexGroup forem expandidos para o novo nó, quatro volumes membros deverão ser adicionados, resultando em um volume FlexGroup de 12 membros.

Adicionar novos membros a um volume do FlexGroup altera a heurística de ingestão para favorecer os novos volumes de membros vazios e pode afetar o desempenho geral do sistema para a nova ingestão de dados até que os novos volumes de membros fiquem equilibrados com os volumes de membros pré-existentes.

.Exemplos
*Exemplo de aumento da capacidade dos volumes de membros existentes*

O exemplo a seguir mostra como adicionar espaço de 20 TB a um volX de volume FlexGroup:

[listing]
----
cluster1::> volume modify -vserver svm1 -volume volX -size +20TB
----
Se o volume FlexGroup tiver 16 volumes de membros, o espaço de cada volume de membro será aumentado em 1,25 TB.

*Exemplo de melhoria do desempenho adicionando novos volumes de membros*

O exemplo a seguir mostra como adicionar quatro volumes de membros adicionais, dois para cada uma das camadas locais subjacentes (agregados) ao volume FlexGroup  `fg1` :

[listing]
----
cluster1::> volume expand -vserver svm1 -volume fg1 -aggr-list aggr1,aggr2 -aggr-list-multiplier 2
----
O tamanho dos novos volumes de membros é o mesmo dos volumes de membros existentes.

.Aumentar o tamanho de um volume individual
Se você quiser aumentar o tamanho de um volume de membro individual em um volume FlexGroup , você pode usar o `volume resize` comando.

.Passo
. Aumentar o tamanho de um único volume de membro do FlexGroup :
+
`volume size -volume <volume_name> -vserver <svm1> -new-size <new_size>`

+
O exemplo a seguir aumenta o tamanho do volume do membro FlexGroup FG_0003 para 3,7 GB:

+
[listing]
----
volume size -volume FG__0003 -vserver svm1 -new-size 3.7GB
vol size: Volume "svm1:FG__0003" size set to 3.70g.
----

