---
permalink: flexgroup/perform-snapmirror-single-file-restore-task.html 
sidebar: sidebar 
keywords: perform, snapmirror, single, file, restore, flexgroup, volume, snap mirror, flex group, vault, udp, destination, transfer 
summary: A partir do ONTAP 9.8, você pode restaurar um único arquivo a partir de um cofre FlexGroup SnapMirror ou de um destino UDP. 
---
= Execute uma restauração de arquivo único do SnapMirror a partir de um volume do ONTAP FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.8, você pode restaurar um único arquivo a partir de um cofre FlexGroup SnapMirror ou de um destino UDP.

.Sobre esta tarefa
* Você pode restaurar de um volume FlexGroup de qualquer geometria para o volume FlexGroup de qualquer geometria
* Apenas um arquivo por operação de restauração é suportado
* Você pode restaurar o volume FlexGroup de origem original ou um novo volume FlexGroup
* A pesquisa remota de ficheiros vedada não é suportada.
+
A restauração de um único arquivo falha se o arquivo de origem estiver cercado.

* Você pode reiniciar ou limpar uma restauração de arquivo único abortada
* Você deve limpar uma transferência de restauração de arquivo único com falha usando a `clean-up-failure` opção `snapmirror restore` do comando
* A expansão de volumes FlexGroup é suportada quando uma restauração de arquivo único FlexGroup está em andamento ou em um estado abortado


.Passos
. Restaurar um arquivo a partir de um volume FlexGroup:``snapmirror restore -destination-path destination_path -source-path source_path -file-list /f1 -throttle throttle -source-snapshot snapshot``
+
A seguir está um exemplo de uma operação de restauração de arquivo único de volume FlexGroup.

+
[listing]
----
vserverA::> snapmirror restore -destination-path vs0:fg2 -source-path vs0:fgd -file-list /f1 -throttle 5 -source-snapshot snapmirror.81072ce1-d57b-11e9-94c0-005056a7e422_2159190496.2019-09-19_062631
[Job 135] Job is queued: snapmirror restore from source "vs0:fgd" for the snapshot snapmirror.81072ce1-d57b-11e9-94c0-005056a7e422_2159190496.2019-09-19_062631.
vserverA::> snapmirror show
                                                                                         Source              Destination Mirror   Relationship                   Total Last
Path       Type   Path            State    Status           Progress Healthy Updated
----------- ----      ------------     -------    ---------          ----- --------- ------- --------
vs0:v1d RST    vs0:v2          -           Transferring Idle 83.12KB true 09/19 11:38:42

vserverA::*> snapmirror show vs0:fg2

Source Path: vs0:fgd
Source Cluster: -
Source Vserver: vs0
Source Volume: fgd
Destination Path: vs0:fg2
Destination Cluster: -
Destination Vserver: vs0
Destination Volume: fg2
Relationship Type: RST
Relationship Group Type: none
Managing Vserver: vs0
SnapMirror Schedule: -
SnapMirror Policy Type: -
SnapMirror Policy: -
Tries Limit: -
Throttle (KB/sec): unlimited
Current Transfer Throttle (KB/sec): 2
Mirror State: -
Relationship Status: Transferring
File Restore File Count: 1
File Restore File List: f1
Transfer Snapshot: snapmirror.81072ce1-d57b-11e9-94c0-005056a7e422_2159190496.2019-09-19_062631
Snapshot Progress: 2.87MB
Total Progress: 2.87MB
Network Compression Ratio: 1:1
Snapshot Checkpoint: 2.97KB
Newest Snapshot: -
Newest Snapshot Timestamp: -
Exported Snapshot: -
Exported Snapshot Timestamp: -
Healthy: true
Physical Replica: -
Relationship ID: e6081667-dacb-11e9-94c0-005056a7e422
Source Vserver UUID: 81072ce1-d57b-11e9-94c0-005056a7e422
Destination Vserver UUID: 81072ce1-d57b-11e9-94c0-005056a7e422
Current Operation ID: 138f12e6-dacc-11e9-94c0-005056a7e422
Transfer Type: cg_file_restore
Transfer Error: -
Last Transfer Type: -
Last Transfer Error: -
Last Transfer Error Codes: -
Last Transfer Size: -
Last Transfer Network Compression Ratio: -
Last Transfer Duration: -
Last Transfer From: -
Last Transfer End Timestamp: -
Unhealthy Reason: -
Progress Last Updated: 09/19 07:07:36
Relationship Capability: 8.2 and above
Lag Time: -
Current Transfer Priority: normal
SMTape Operation: -
Constituent Relationship: false
Destination Volume Node Name: vserverA
Identity Preserve Vserver DR: -
Number of Successful Updates: 0
Number of Failed Updates: 0
Number of Successful Resyncs: 0
Number of Failed Resyncs: 0
Number of Successful Breaks: 0
Number of Failed Breaks: 0
Total Transfer Bytes: 0
Total Transfer Time in Seconds: 0
Source Volume MSIDs Preserved: -
OpMask: ffffffffffffffff
Is Auto Expand Enabled: -
Source Endpoint UUID: -
Destination Endpoint UUID: -
Is Catalog Enabled: false
----

