---
permalink: flexgroup/protect-snapshot-copies-task.html 
sidebar: sidebar 
keywords: protect, flexgroup, volume, snapshot, copy, flex group, snap shot, manually, manual, automatically, automatic, policy 
summary: Você pode criar políticas de snapshot que gerenciam automaticamente a criação de snapshots ou pode criar snapshots manualmente para volumes do FlexGroup. Um instantâneo válido é criado para um volume FlexGroup somente depois que o ONTAP pode criar com êxito um instantâneo para cada componente do volume FlexGroup. 
---
= Proteger volumes FlexGroup usando snapshots
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode criar políticas de snapshot que gerenciam automaticamente a criação de snapshots ou pode criar snapshots manualmente para volumes do FlexGroup. Um instantâneo válido é criado para um volume FlexGroup somente depois que o ONTAP pode criar com êxito um instantâneo para cada componente do volume FlexGroup.

.Sobre esta tarefa
* Se você tiver vários volumes do FlexGroup associados a uma política de snapshot, verifique se as programações do FlexGroup volumes não se sobrepõem.
* A partir do ONTAP 9,8, o número máximo de instantâneos suportados num volume FlexGroup é 1023.



NOTE: A partir do ONTAP 9,8, o `volume snapshot show` comando para FlexGroup volumes relata o tamanho do snapshot usando blocos lógicos, em vez de calcular os blocos de propriedade mais novos. Esse novo método de cálculo de tamanho pode fazer com que o tamanho do instantâneo pareça maior do que os cálculos em versões anteriores do ONTAP.

.Passos
. Criar uma política de instantâneos ou criar manualmente um instantâneo:
+
|===


| Se você quiser criar um... | Digite este comando... 


 a| 
Política do Snapshot
 a| 
`volume snapshot policy create`


NOTE: As programações associadas à política de snapshot de um volume FlexGroup devem ter um intervalo maior que 30 minutos.

Quando você cria um volume FlexGroup, a `default` política de snapshot é aplicada ao volume FlexGroup.



 a| 
Instantâneo manualmente
 a| 
`volume snapshot create`


NOTE: Depois de criar um instantâneo para um volume FlexGroup, não é possível modificar os atributos do instantâneo. Se você quiser modificar os atributos, você deve excluir e recriar o instantâneo.

|===


O acesso do cliente ao volume FlexGroup é rapidamente interrompido quando um snapshot é criado.

. Verifique se foi criado um instantâneo válido para o volume FlexGroup: `volume snapshot show -volume volume_name -fields state`
+
[listing]
----
cluster1::> volume snapshot show -volume fg -fields state
vserver volume snapshot               state
------- ------ ---------------------- -----
fg_vs   fg     hourly.2016-08-23_0505 valid
----
. Veja os instantâneos para os constituintes do volume FlexGroup: `volume snapshot show -is-constituent true`
+
[listing]
----
cluster1::> volume snapshot show -is-constituent true
                                                                 ---Blocks---
Vserver  Volume   Snapshot                                  Size Total% Used%
-------- -------- ------------------------------------- -------- ------ -----
fg_vs    fg__0001
                  hourly.2016-08-23_0505                    72MB     0%   27%
         fg__0002
                  hourly.2016-08-23_0505                    72MB     0%   27%
         fg__0003
                  hourly.2016-08-23_0505                    72MB     0%   27%
...
         fg__0016
                  hourly.2016-08-23_0505                    72MB     0%   27%
----

