---
permalink: flexgroup/provision-automatically-task.html 
sidebar: sidebar 
keywords: provision, flexgroup, volume, automatic, create, flex group, aggregate, space 
summary: 'Ao criar um volume FlexGroup, você pode optar por fazer com que o ONTAP provisione o volume FlexGroup selecionando automaticamente as camadas locais (agregados). As camadas locais são selecionadas com base nas práticas recomendadas para performance ideal.' 
---
= Provisionar um volume ONTAP FlexGroup automaticamente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao criar um volume FlexGroup, você pode optar por fazer com que o ONTAP provisione automaticamente o volume FlexGroup selecionando as camadas locais subjacentes (agregados). As categorias locais são selecionadas com base nas práticas recomendadas para performance e capacidade ideais.

.Antes de começar
Cada nó no cluster precisa ter pelo menos um nível local.

[NOTE]
====
Ao criar um volume FlexGroup que categorize os dados inativos, cada nó precisa ter pelo menos um nível local com o FabricPool habilitado.

====
.Sobre esta tarefa
O ONTAP seleciona dois níveis locais com a maior quantidade de espaço utilizável em cada nó para criar o volume FlexGroup. Se dois níveis locais não estiverem disponíveis, o ONTAP selecionará um nível local por nó para criar o volume FlexGroup.

A partir do ONTAP 9.15.1, quando você provisiona automaticamente um volume FlexGroup, o ONTAP usa o posicionamento balanceado (BP) para escolher os níveis locais e o layout de volumes de membro (constituinte) do FlexGroup. Um aspeto da BP é como ele limita o provisionamento excessivo de camadas locais ao criar volumes FlexGroup sem garantia (thin Provisioning). O tamanho do volume FlexGroup geral é limitado pela quantidade de espaço livre na camada local, embora o limite seja maior do que para volumes FlexGroup garantidos (com provisionamento excessivo). Quando você cria um volume FlexGroup usando APIs REST ou `auto-provision-as` com a CLI do ONTAP, o provisionamento pode falhar devido ao espaço insuficiente devido a esse limite. Você pode evitar isso criando volumes FlexGroup menores ou link:create-task.html["Criando um volume FlexGroup e selecionando manualmente os níveis locais"]usando o `aggr-list` parâmetro.

.Passos
. Provisione o volume FlexGroup:
+
`volume create -vserver svm_name -volume fg_vol_name –auto-provision-as flexgroup -size fg_size [–encrypt true] [-qos-policy-group qos_policy_group_name] [-support-tiering true] [-granular-data advanced]`

+
A partir do ONTAP 9.16.1, é possível habilitar link:../enable-adv-capacity-flexgroup-task.html["balanceamento de capacidade avançado"] (`-granular-data advanced`na CLI) a gravação de dados em vários volumes de membros do FlexGroup quando arquivos são maiores que 10GB TB.

+
A partir do ONTAP 9,5, você pode criar volumes FlexGroup em camadas locais com o FabricPool habilitado. Para provisionar automaticamente um volume FlexGroup em camadas locais com o FabricPool habilitado, é necessário definir o `-support-tiering` parâmetro como `true`. A garantia de volume deve estar sempre definida como `none` para FabricPool. Você também pode especificar a política de disposição em categorias e o período mínimo de resfriamento de disposição em camadas para o volume FlexGroup.

+
link:../disks-aggregates/index.html["Gerenciamento de disco e agregado"]

+
É possível especificar um limite máximo de taxa de transferência (QoS máx.) para volumes FlexGroup. Isso limita os recursos de performance que o volume do FlexGroup pode consumir. A partir do ONTAP 9.4, é possível especificar andares de taxa de transferência (QoS min) e QoS adaptável para volumes FlexGroup.

+
link:../performance-admin/index.html["Gerenciamento de desempenho"]

+
Pode definir o `-encrypt` parâmetro para `true` se pretender ativar a encriptação no volume FlexGroup. Para criar um volume criptografado, você deve ter instalado a licença de criptografia de volume e o gerenciador de chaves.

+

NOTE: Você deve habilitar a criptografia em volumes FlexGroup no momento da criação. Não é possível ativar a encriptação em volumes FlexGroup existentes.

+
link:../encryption-at-rest/index.html["Criptografia de dados em repouso"]

+
O `size` parâmetro especifica o tamanho do volume FlexGroup em KB, MB, GB, TB ou PB.

+
O exemplo a seguir mostra como provisionar um volume FlexGroup de tamanho 400 TB:

+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
O exemplo a seguir mostra como criar um grupo de políticas de QoS para limite de taxa de transferência e como aplicá-lo a um volume FlexGroup:

+
[listing]
----
cluster1::> qos policy-group create -policy group pg-vs1 -vserver vs1 -max-throughput 5000iops
----
+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB -qos-policy-group pg-vs1
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
O exemplo a seguir mostra como provisionar um volume FlexGroup de tamanho 400 TB em camadas locais com o FabricPool habilitado:

+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB -support-tiering true -tiering-policy auto
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
O volume FlexGroup é criado com oito volumes de membros em cada nó no cluster. Os volumes de membros são distribuídos igualmente entre as duas maiores camadas locais em cada nó.

+
Por padrão, o volume FlexGroup é criado com a `volume` configuração de garantia de espaço, exceto em sistemas AFF. Para sistemas AFF, por padrão, o volume FlexGroup é criado com a `none` garantia de espaço.

. Monte o volume FlexGroup com um caminho de junção:
+
`volume mount -vserver vserver_name -volume vol_name -junction-path junction_path`

+
[listing]
----
cluster1::> volume mount -vserver vs0 -volume fg2 -junction-path /fg2
----


.Depois de terminar
Você deve montar o volume FlexGroup do cliente.

Se você estiver executando o ONTAP 9.6 ou anterior e se a máquina virtual de armazenamento (SVM) tiver o NFSv3 e o NFSv4 configurados, a montagem do volume FlexGroup do cliente poderá falhar. Nesses casos, você deve especificar explicitamente a versão NFS ao montar o volume FlexGroup do cliente.

[listing]
----
# mount -t nfs -o vers=3 192.53.19.64:/fg2 /mnt/fg2
# ls /mnt/fg2
file1  file2
----