---
sidebar: sidebar 
permalink: flexgroup/provision-nas-flexgroup-task.html 
keywords: netapp, ontap, provision, provisioning, nas, large file systems, using, FlexGroup, windows, servers, cifs, smb, FlexVol volume limits, load distribution, work load, workload, balancing, data 
summary: 'Um volume FlexGroup é um contêiner nas escalável que fornece alto desempenho junto com distribuição automática de carga. Os volumes FlexGroup fornecem uma capacidade enorme (em petabytes), que excede consideravelmente os limites do FlexVol volume, sem adicionar nenhuma sobrecarga no gerenciamento.' 
---
= Provisionar armazenamento NAS para grandes sistemas de arquivos usando volumes ONTAP FlexGroup
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Um volume FlexGroup é um contêiner nas escalável que fornece alto desempenho junto com distribuição automática de carga. Os volumes FlexGroup fornecem uma capacidade enorme (em petabytes), que excede consideravelmente os limites do FlexVol volume, sem adicionar nenhuma sobrecarga no gerenciamento.

Os tópicos nesta seção mostram como gerenciar volumes do FlexGroup com o Gerenciador de sistemas no ONTAP 9.7 e versões posteriores. Se você estiver usando o gerenciador de sistema clássico (disponível somente no ONTAP 9.7 e versões anteriores), veja este tópico:

* https://docs.netapp.com/us-en/ontap-system-manager-classic/online-help-96-97/task_creating_flexgroup_volumes.html["Criar volumes FlexGroup"^]


A partir do ONTAP 9.9,1, as relações de fanout do SnapMirror de dois ou mais volumes FlexGroup são suportadas, com um máximo de oito pernas de fanout. O System Manager não é compatível com relacionamentos de volume FlexGroup em cascata do SnapMirror.

O ONTAP seleciona automaticamente os níveis locais necessários para criar o volume FlexGroup.

A partir do ONTAP 9.8, quando você provisiona o storage, a QoS é habilitada por padrão. Você pode desativar o QoS ou escolher uma política de QoS personalizada durante o processo de provisionamento ou posteriormente.

.Passos
. Clique em *armazenamento > volumes*.
. Clique em *Add*.
. Clique em *mais Opções* e selecione *distribuir dados de volume pelo cluster*.
+

NOTE: Se você estiver executando o ONTAP 9.8 ou posterior e quiser desativar o QoS ou escolher uma política de QoS personalizada, clique em *mais opções* e, em *armazenamento e otimização*, selecione *nível de serviço de desempenho*.





== Vídeos



=== Criar e gerenciar um volume FlexGroup

video::gB-yF1UTv2I[youtube,width=848,height=480]


=== FlexGroup volumes - Faça mais com menos

video::0B4nlChf0b4[youtube,width=848,height=480]