---
permalink: flexgroup/restore-snapvault-backup-task.html 
sidebar: sidebar 
keywords: restore, flexgroup, volume, snapvault, backup 
summary: É possível executar uma operação de restauração de volume total do FlexGroup volumes a partir de um snapshot no volume secundário do SnapVault. Você pode restaurar o volume FlexGroup para o volume de origem original ou para um novo volume FlexGroup. 
---
= Restaure volumes do ONTAP FlexGroup a partir de backups do SnapVault
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível executar uma operação de restauração de volume total do FlexGroup volumes a partir de um snapshot no volume secundário do SnapVault. Você pode restaurar o volume FlexGroup para o volume de origem original ou para um novo volume FlexGroup.

.Antes de começar
Você precisa estar ciente de alguns considerações ao restaurar os backups do SnapVault para volumes FlexGroup.

* Somente a restauração de linha de base é suportada com snapshots parciais de um backup do SnapVault. O número de constituintes no volume de destino deve corresponder ao número de constituintes no volume de origem quando o instantâneo foi captado.
* Se uma operação de restauração falhar, nenhuma outra operação será permitida até que a operação de restauração esteja concluída. Você pode tentar novamente a operação de restauração ou executar a operação de restauração com o `cleanup` parâmetro.
* Um volume FlexGroup pode ser o volume de origem de apenas uma relação de backup ou restauração. Um volume FlexGroup não pode ser a origem de duas relações SnapVault, duas relações de restauração ou uma relação SnapVault e uma relação de restauração.
* As operações de backup e restauração do SnapVault não podem ser executadas em paralelo. Quando uma operação de restauração de linha de base ou uma operação de restauração incremental estiverem em andamento, você deverá desativar as operações de backup.
* É necessário cancelar uma operação de restauração de um instantâneo parcial do volume FlexGroup de destino. Não é possível cancelar a operação de restauração de um instantâneo parcial do volume de origem.
* Se cancelar uma operação de restauro, tem de reiniciar a operação de restauro com o mesmo instantâneo utilizado para a operação de restauro anterior.


.Sobre esta tarefa
Todas as regras de cota ativa no volume FlexGroup de destino são desativadas antes da restauração ser executada.

Você pode usar o `volume quota modify` comando para reativar regras de cota após a conclusão da operação de restauração.

.Passos
. Restaurar o volume FlexGroup: `snapmirror restore -source-path _src_svm:src_flexgroup_ -destination-path _dest_svm:dest_flexgroup_ -snapshot _snapshot_name_`
`snapshot_name` É o instantâneo que deve ser restaurado do volume de origem para o volume de destino. Se o instantâneo não for especificado, o volume de destino será restaurado a partir do instantâneo mais recente.
+
[listing]
----
vserverA::> snapmirror restore -source-path vserverB:dstFG -destination-path vserverA:newFG -snapshot daily.2016-07-15_0010
Warning: This is a disruptive operation and the volume vserverA:newFG will be read-only until the operation completes
Do you want to continue? {y|n}: y
----


.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-restore.html["restauração de SnapMirror"^]

