---
permalink: flexgroup/shrink-flexgroup-volume-task.html 
sidebar: sidebar 
keywords: reduce, size, flexgroup, volume, flex group, resize, shrink, shrinking, autosize 
summary: A partir do ONTAP 9.6, é possível redimensionar um volume FlexGroup para um valor menor do que o tamanho atual para liberar o espaço não utilizado do volume. Quando você reduz o tamanho de um volume FlexGroup, o ONTAP redimensiona automaticamente todos os componentes do FlexGroup. 
---
= Reduza o tamanho dos volumes ONTAP FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.6, é possível redimensionar um volume FlexGroup para um valor menor do que o tamanho atual para liberar o espaço não utilizado do volume. Quando você reduz o tamanho de um volume FlexGroup, o ONTAP redimensiona automaticamente todos os componentes do FlexGroup.

.Passo
. Verifique o tamanho atual do volume do FlexGroup: 'Tamanho do volume -vserver _vserver_name_ -volume _fg_name_'
. Reduza o tamanho do volume FlexGroup: `volume size -vserver _vserver_name_ -volume _fg_name_ _new_size_`
+
Quando você especifica o novo tamanho, você pode especificar um valor menor do que o tamanho atual ou um valor negativo usando o sinal de menos (-) pelo qual o tamanho atual do volume FlexGroup é reduzido.

+
[NOTE]
====
Se a redução automática estiver ativada para o comando volume(`volume autosize`), o dimensionamento mínimo será definido para o novo tamanho do volume.

====
+
O exemplo a seguir exibe o tamanho do volume atual do volume FlexGroup chamado volX e redimensiona o volume para 10TB:

+
[listing]
----
cluster1::> volume size -vserver svm1 -volume volX
(volume size)
vol size: FlexGroup volume 'svm1:volX' has size 15TB.

cluster1::> volume size -vserver svm1 -volume volX 10TB
(volume size)
vol size: FlexGroup volume 'svm1:volX' size set to 10TB.
----
+
O exemplo a seguir exibe o tamanho do volume atual para o volume FlexGroup chamado volX e reduz o tamanho do volume em 5TB:

+
[listing]
----
cluster1::> volume size -vserver svm1 -volume volX
(volume size)
vol size: FlexGroup volume 'svm1:volX' has size 15TB.

cluster1::> volume size -vserver svm1 -volume volX -5TB
(volume size)
vol size: FlexGroup volume 'svm1:volX' size set to 10TB.
----

