---
permalink: flexgroup/snapvault-backup-concept.html 
sidebar: sidebar 
keywords: consider, create, snapvault, backup, relation, unified, data, protection, flexgroup, volume 
summary: Você precisa estar ciente das considerações para criar uma relação de backup da SnapVault e uma relação unificada de proteção de dados para volumes do FlexGroup. 
---
= Considerações para a criação de relacionamentos de backup do SnapVault e relacionamentos de proteção de dados unificados para volumes do ONTAP FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você precisa estar ciente das considerações para criar uma relação de backup da SnapVault e uma relação unificada de proteção de dados para volumes do FlexGroup.

* É possível ressincronizar uma relação de backup do SnapVault e uma relação unificada de proteção de dados usando a `-preserve` opção que permite preservar snapshots no volume de destino mais recente que o snapshot comum mais recente.
* A retenção de longo prazo não é compatível com volumes FlexGroup.
+
A retenção de longo prazo permite criar snapshots diretamente no volume de destino sem a necessidade de armazenar os snapshots no volume de origem.

* A `snapshot` opção de comando `expiry-time` não é suportada para volumes FlexGroup.
* A eficiência de storage não pode ser configurada no volume FlexGroup de destino de uma relação de backup da SnapVault e no relacionamento unificado de proteção de dados.
* Não é possível renomear snapshots de uma relação de backup do SnapVault e do relacionamento de proteção de dados unificado para volumes do FlexGroup.
* Um volume FlexGroup pode ser o volume de origem de apenas uma relação de backup ou restauração.
+
Um volume FlexGroup não pode ser a origem de duas relações SnapVault, duas relações de restauração ou uma relação de backup SnapVault e uma relação de restauração.

* Se você excluir um instantâneo no volume FlexGroup de origem e recriar um instantâneo com o mesmo nome, a próxima transferência de atualização para o volume FlexGroup de destino falhará se o volume de destino tiver um instantâneo com o mesmo nome.
+
Isso ocorre porque os snapshots não podem ser renomeados para volumes FlexGroup.


