---
permalink: flexcache-writeback/flexcache-write-back-interoperability.html 
sidebar: sidebar 
keywords: tr-4743, flexcache writeback, flexcache write-back, interoperability, client, technical report, netapp tr, ontap tr 
summary: Entenda essas considerações de interoperabilidade ao implantar o FlexCache no modo write-back 
---
= Interoperabilidade de back-back do ONTAP FlexCache
:allow-uri-read: 


[role="lead"]
Entenda essas considerações de interoperabilidade ao implantar o FlexCache no modo write-back.



== Versão de ONTAP

Para usar o modo de operação write-back, tanto o cache quanto o Origin *devem* estar executando o ONTAP 9.15,1 ou posterior.


NOTE: Os clusters em que um cache habilitado para write-back é desnecessário podem executar versões anteriores do ONTAP, mas esse cluster só pode operar no modo write-around.

Você pode ter uma combinação de versões do ONTAP em seu ambiente.

[cols="1*,1*,1*"]
|===
| Cluster | Versão de ONTAP | Write-back suportado? 


| *Origem* | ONTAP 9.15,1 | N/A † 


| *Cluster 1* | ONTAP 9.15,1 | Sim 


| *Cluster 2* | ONTAP 9.14,1 | Não 
|===
[cols="1*,1*,1*"]
|===
| Cluster | Versão de ONTAP | Write-back suportado? 


| *Origem* | ONTAP 9.14,1 | N/A † 


| *Cluster 1* | ONTAP 9.15,1 | Não 


| *Cluster 2* | ONTAP 9.15,1 | Não 
|===
† _Origins não são um cache, então nem o suporte de write-back nem write-around é aplicável._


NOTE: No <<example2-table>>, nenhum dos clusters pode ativar o modo write-back porque a origem não está executando o ONTAP 9.15,1 ou posterior, o que é um requisito estrito.



== Interoperabilidade do cliente

Qualquer cliente geralmente suportado pelo ONTAP pode acessar um volume FlexCache, independentemente de estar operando no modo write-around ou write-back. Para obter uma lista atualizada dos clientes suportados, consulte NetApp's https://imt.netapp.com/matrix/#welcome["matriz de interoperabilidade"^].

Embora a versão do cliente não importa especificamente, o cliente deve ser novo o suficiente para suportar NFSv3, NFSv4,0, NFSv4,1, SMB2.x ou SMB3.x. SMB1 e NFSv2 são protocolos obsoletos e não são suportados.



== Escreva-back e escreva-around

Como visto <<example1-table>>no , o FlexCache operando no modo write-back pode coexistir com caches operando no modo write-around. É aconselhável comparar write-around com write-back com sua carga de trabalho específica.


TIP: Se a performance de um workload for a mesma entre write-back e write-around, use write-around.



== Interoperabilidade do recurso ONTAP

Para obter a lista mais atualizada de interoperabilidade de recursos do FlexCache, link:../flexcache/supported-unsupported-features-concept.html["Os recursos suportados e não suportados para volumes FlexCache"]consulte .
