---
permalink: s3-audit/modify-config-task.html 
sidebar: sidebar 
keywords: s3 audit, modify 
summary: É possível modificar os parâmetros de auditoria de buckets individuais ou a configuração de auditoria de todos os buckets selecionados para auditoria no SVM. 
---
= Modificar uma configuração de auditoria S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível modificar os parâmetros de auditoria de buckets individuais ou a configuração de auditoria de todos os buckets selecionados para auditoria no SVM.

[cols="2,4"]
|===
| Se você quiser modificar a configuração de auditoria para... | Digite... 


| Baldes individuais | `vserver object-store-server audit event-selector modify -vserver _svm_name_ [-bucket _bucket_name_] [_parameters to modify_]` 


| Todos os buckets no SVM  a| 
`vserver object-store-server audit modify -vserver _svm_name_ [_parameters to modify_]`

|===
.Exemplos
O exemplo a seguir modifica uma configuração de auditoria de bucket individual para auditar somente eventos de acesso somente gravação:

[listing]
----
cluster1::> vserver object-store-server audit event-selector modify -vserver vs1 -bucket test-bucket -access write-only
----
O exemplo a seguir modifica a configuração de auditoria de todos os buckets no SVM para alterar o limite de tamanho do log para 10MB e reter arquivos de log 3 antes de girar.

[listing]
----
cluster1::> vserver object-store-server audit modify -vserver vs1 -rotate-size 10MB -rotate-limit 3
----