---
sidebar: sidebar 
permalink: s3-snapmirror/requirements-cloud-targets-concept.html 
keywords: requirements for cloud target relationships, ontap s3, snapmirror, s3, cloud target 
summary: Certifique-se de que seus ambientes de origem e destino atendam aos requisitos de proteção de backup do SnapMirror S3 para destinos na nuvem. 
---
= Requisitos para relacionamentos de destino da nuvem do ONTAP SnapMirror S3
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Certifique-se de que seus ambientes de origem e destino atendam aos requisitos de proteção de backup do SnapMirror S3 para destinos na nuvem.

Você deve ter credenciais de conta válidas com o provedor de armazenamento de objetos para acessar o intervalo de dados.

LIFs entre clusters e um espaço IPspace devem ser configurados no cluster antes que o cluster possa se conetar a um armazenamento de objetos em nuvem. Você deve criar LIFs entre clusters em cada nó para transferir dados de forma otimizada do storage local para o armazenamento de objetos em nuvem.

Para alvos StorageGRID, você precisa saber as seguintes informações:

* Nome do servidor, expresso como um nome de domínio totalmente qualificado (FQDN) ou endereço IP
* nome do bucket; o bucket já deve existir
* chave de acesso
* chave secreta


Além disso, o certificado da CA usado para assinar o certificado do servidor StorageGRID precisa ser instalado na VM de armazenamento de administrador do cluster do ONTAP S3 usando o `security certificate install command`. Para obter mais informações, consulte link:../fabricpool/install-ca-certificate-storagegrid-task.html["Instalando um certificado CA"] se você usa o StorageGRID.

Para os destinos do AWS S3, você precisa saber as seguintes informações:

* Nome do servidor, expresso como um nome de domínio totalmente qualificado (FQDN) ou endereço IP
* nome do bucket; o bucket já deve existir
* chave de acesso
* chave secreta


O servidor DNS para a VM de armazenamento de administrador do cluster ONTAP deve ser capaz de resolver FQDNs (se usado) para endereços IP.
