= 
:allow-uri-read: 


. Use o `system license show` comando para verificar se você tem uma licença para FC ou iSCSI. Saiba mais sobre `system license show` o link:https://docs.netapp.com/us-en/ontap-cli/system-license-show.html["Referência do comando ONTAP"^]na .
+
`system license show`

+
[listing]
----

Package           Type    Description           Expiration
 ----------------- ------- --------------------- --------------------
 Base              site    Cluster Base License  -
 NFS               site    NFS License           -
 CIFS              site    CIFS License          -
 iSCSI             site    iSCSI License         -
 FCP               site    FCP License           -
----
. Se você não tiver uma licença para FC ou iSCSI, use o `license add` comando. Saiba mais sobre `license add` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=license+add["Referência do comando ONTAP"^]na .
+
`license add -license-code _your_license_code_`

. Habilite o serviço de protocolos no SVM:
+
*Para iSCSI:* `vserver iscsi create -vserver _vserver_name_ -target-alias _vserver_name_`

+
Saiba mais sobre `vserver iscsi create` o link:https://docs.netapp.com/us-en/ontap-cli/vserver-iscsi-create.html["Referência do comando ONTAP"^]na .

+
*Para FC:* `vserver fcp create -vserver _vserver_name_ -status-admin up`

+
Saiba mais sobre `vserver fcp create` o link:https://docs.netapp.com/us-en/ontap-cli/vserver-fcp-create.html["Referência do comando ONTAP"^]na .

. Crie duas LIFs para as SVMs em cada nó:
+
`network interface create -vserver _vserver_name_ -lif _lif_name_ -role data -data-protocol iscsi|fc -home-node _node_name_ -home-port _port_name_ -address _ip_address_ -netmask netmask`

+
O NetApp é compatível com, no mínimo, um iSCSI ou FC LIF por nó para cada SVM que fornece dados. No entanto, dois LIFS por nó são necessários para redundância. Saiba mais sobre `network interface create` o link:https://docs.netapp.com/us-en/ontap-cli/network-interface-create.html["Referência do comando ONTAP"^]na .

. Verifique se seus LIFs foram criados e se o status operacional deles é `online`:
+
`network interface show -vserver _vserver_name_ _lif_name_`

+
Saiba mais sobre `network interface show` o link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["Referência do comando ONTAP"^]na .

. Crie seus LUNs:
+
`lun create -vserver vserver_name -volume _volume_name_ -lun _lun_name_ -size _lun_size_ -ostype linux -space-reserve enabled|disabled`

+
O seu nome LUN não pode exceder 255 carateres e não pode conter espaços. Saiba mais sobre `lun create` o link:https://docs.netapp.com/us-en/ontap-cli/lun-create.html["Referência do comando ONTAP"^]na .

+

NOTE: A opção NVFAIL é ativada automaticamente quando um LUN é criado em um volume.

. Crie seus grupos:
+
`igroup create -vserver _vserver_name_ -igroup _igroup_name_ -protocol fcp|iscsi|mixed -ostype linux -initiator _initiator_name_`

+
Saiba mais sobre `igroup create` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=igroup+create["Referência do comando ONTAP"^]na .

. Mapeie seus LUNs para grupos:
+
`lun mapping create -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -igroup _igroup_name_`

+
Saiba mais sobre `lun mapping create` o link:https://docs.netapp.com/us-en/ontap-cli/lun-mapping-create.html["Referência do comando ONTAP"^]na .

. Verifique se os LUNs estão configurados corretamente:
+
`lun show -vserver _vserver_name_`

+
Saiba mais sobre `lun show` o link:https://docs.netapp.com/us-en/ontap-cli/lun-show.html["Referência do comando ONTAP"^]na .

. link:san-admin/create-port-sets-binding-igroups-task.html["Crie um conjunto de portas e vincule a um grupo"] (opcional).
. Siga as etapas na documentação do host para habilitar o acesso a blocos em seus hosts específicos.
. Use os Utilitários do host para concluir o mapeamento FC ou iSCSI e descobrir os LUNs no host.

