= Requisitos
:allow-uri-read: 


[role="lead"]
O TLS permite comunicações de rede criptografadas com segurança equivalente e menos complexidade do que o Kerberos e o IPsec. Como administrador, você pode habilitar, configurar e desabilitar o TLS para segurança forte com conexões NFSv3 e NFSv4.x usando o Gerenciador de sistema, a CLI do ONTAP ou a API REST do ONTAP.


NOTE: O NFS em TLS está disponível no ONTAP 9.15,1 como prévia pública. Como oferta de prévia, o NFS em TLS não é compatível com workloads de produção no ONTAP 9.15,1.

O ONTAP usa o TLS 1,3 para conexões NFS em TLS.



== Requisitos

O NFS em TLS requer certificados X,509. Você pode criar uma instalação de um certificado de servidor assinado pela CA no cluster do ONTAP ou instalar um certificado que o serviço NFS usa diretamente. Seus certificados devem atender às seguintes diretrizes:

* Cada certificado deve ser configurado com o nome de domínio totalmente qualificado (FQDN) do servidor NFS (o LIF de dados no qual o TLS será ativado/configurado) como um nome comum (CN).
* Cada certificado deve ser configurado com o endereço IP ou FQDN do servidor NFS (ou ambos) como o nome alternativo do assunto (SAN). Se o endereço IP e o FQDN estiverem configurados, os clientes NFS podem se conetar usando o endereço IP ou o FQDN.
* Você pode instalar vários certificados de serviço NFS para o mesmo LIF, mas apenas um deles pode ser usado de cada vez como parte da configuração TLS NFS.

