---
sidebar: sidebar 
permalink: networking/add_or_remove_ports_from_a_broadcast_domain97.html 
keywords: adding, add, create, creating, remove, removing, delete, deleting, port, broadcast, domain, reachability, repair, physical, switch, configuration, manually add or remove ports from a broadcast domain, network port broadcast-domain add-ports, network port broadcast-domain remove-ports, examples of adding and removing ports, move, moving, broadcast, domain, ipspace, remove ports from a broadcast domain, broadcast-domain remove-ports 
summary: Adicionar e remover manualmente portas de domínios de broadcast não é necessário ou recomendado 
---
= Adicionar ou remover portas de um domínio de broadcast (ONTAP 9.7 e anterior)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode adicionar portas de rede ao criar inicialmente um domínio de broadcast ou adicionar portas ou remover portas de um domínio de broadcast que já existe. Isso permite que você use com eficiência todas as portas no cluster.

Se as portas que você deseja adicionar ao novo domínio de broadcast já estiverem em outro domínio de broadcast, remova as portas desse domínio de broadcast antes de atribuí-las ao novo domínio de broadcast.


NOTE: Esta tarefa é relevante para o ONTAP 9.0 - 9,7, não para o ONTAP 9.8.

.Antes de começar
* Você deve ser um administrador de cluster para executar esta tarefa.
* As portas que pretende adicionar a um domínio de difusão não devem pertencer a outro domínio de difusão.
* As portas que já pertencem a um grupo de interfaces não podem ser adicionadas individualmente a um domínio de broadcast.


.Sobre esta tarefa
As regras a seguir se aplicam ao adicionar e remover portas de rede:

|===


| Ao adicionar portas... | Ao remover portas... 


| As portas podem ser portas de rede, VLANs ou grupos de interface (ifgrps). | N/A. 


| As portas são adicionadas ao grupo de failover definido pelo sistema do domínio de broadcast. | As portas são removidas de todos os grupos de failover no domínio de broadcast. 


| A MTU das portas é atualizada para o valor MTU definido no domínio de broadcast. | A MTU das portas não muda. 


| O IPspace das portas é atualizado para o valor IPspace do domínio de broadcast. | As portas são movidas para o espaço IPspace 'padrão' sem atributo de domínio de broadcast. 
|===

NOTE: Se você remover a última porta membro de um grupo de interfaces usando o `network port ifgrp remove-port` comando, isso fará com que a porta do grupo de interfaces seja removida do domínio de broadcast porque uma porta de grupo de interfaces vazia não é permitida em um domínio de broadcast.

.Passos
. Exiba as portas que estão atualmente atribuídas ou não atribuídas a um domínio de broadcast usando o `network port show` comando.
. Adicionar ou remover portas de rede do domínio de broadcast:
+
[cols="40,60"]
|===


| Se você quiser... | Utilizar... 


 a| 
Adicionar portas a um domínio de broadcast
 a| 
`network port broadcast-domain add-ports`



 a| 
Remover portas de um domínio de broadcast
 a| 
`network port broadcast-domain remove-ports`

|===
. Verifique se as portas foram adicionadas ou removidas do domínio de broadcast:
+
`network port show`





== Exemplos de adição e remoção de portas

O comando a seguir adiciona a porta e0g no cluster de nó-1-01 e a porta e0g no cluster de nó-1-02 para transmitir o domínio bcast1 no IPspace padrão:

`cluster-1::> network port broadcast-domain add-ports -broadcast-domain bcast1 -ports cluster-1-01:e0g,cluster1-02:e0g`

O comando a seguir adiciona duas portas de cluster ao cluster de domínio de broadcast no Cluster IPspace:

`cluster-1::> network port broadcast-domain add-ports -broadcast-domain Cluster -ports cluster-2-03:e0f,cluster2-04:e0f -ipspace Cluster`

O comando a seguir remove a porta e0e no nó cluster1-01 do domínio de broadcast bcast1 no IPspace padrão:

`cluster-1::> network port broadcast-domain remove-ports -broadcast-domain bcast1 -ports cluster-1-01:e0e`

.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/["Referência do comando ONTAP"^]

