---
sidebar: sidebar 
permalink: networking/balance_network_loads_to_optimize_user_traffic_@cluster_administrators_only@_overview.html 
keywords: balance, balanced, load, utilization, usage, lif, port, cluster, performance 
summary: Configure o cluster para atender solicitações de clientes a partir de LIFs adequadamente carregados. 
---
= Visão geral da rede de equilíbrio
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode configurar seu cluster para atender solicitações de clientes a partir de LIFs adequadamente carregados. Isso resulta em uma utilização mais equilibrada de LIFs e portas, o que, por sua vez, permite um melhor desempenho do cluster.

O balanceamento de carga DNS ajuda a selecionar um LIF de dados carregado adequadamente e equilibrar o tráfego de rede do usuário em todas as portas disponíveis (físicas, grupos de interfaces e VLANs).

Com o balanceamento de carga DNS, LIFs são associados à zona de balanceamento de carga de um SVM. Um servidor DNS em todo o site é configurado para encaminhar todas as solicitações DNS e retornar o LIF menos carregado com base no tráfego de rede e na disponibilidade dos recursos da porta (uso da CPU, taxa de transferência, conexões abertas, etc.). O balanceamento de carga DNS oferece os seguintes benefícios:

* Novas conexões de clientes equilibradas entre os recursos disponíveis.
* Nenhuma intervenção manual é necessária para decidir quais LIFs usar ao montar um SVM específico.
* O balanceamento de carga DNS suporta NFSv3, NFSv4, NFSv4,1, SMB 2,0, SMB 2,1, SMB 3,0 e S3.

