---
sidebar: sidebar 
permalink: networking/change_the_mtu_value_for_ports_in_a_broadcast_domain.html 
keywords: modify, modifying, mtu, mtu_value, change, changing, broadcast, domain, ports, port, change the mtu value for ports in a broadcast domain 
summary: Modifique o valor MTU de um domínio de broadcast para alterar esse valor para todas as portas no domínio de broadcast 
---
= Altere o valor MTU para portas em um domínio de broadcast ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode modificar o valor MTU de um domínio de broadcast para alterar o valor MTU para todas as portas nesse domínio de broadcast. Isso pode ser feito para suportar alterações de topologia que foram feitas na rede.


NOTE: O procedimento para alterar o valor MTU para portas de domínio de broadcast é diferente no ONTAP 9,7 e versões anteriores. Se for necessário alterar o valor MTU para portas de domínio de broadcast em uma rede executando o ONTAP 9,7 e anterior, link:https://docs.netapp.com/us-en/ontap-system-manager-classic/networking-bd/change_the_mtu_value_for_ports_in_a_broadcast_domain97.html["Alterar o valor MTU para portas em um domínio de broadcast (ONTAP 9.7 e anterior)"^]consulte .

.Antes de começar
O valor MTU deve corresponder a todos os dispositivos conetados a essa rede de camada 2, exceto para o tráfego de gerenciamento de manipulação de portas e0M.

.Sobre esta tarefa
A alteração do valor MTU provoca uma breve interrupção no tráfego nas portas afetadas. O sistema exibe um prompt que você deve responder com y para fazer a alteração da MTU.

.Passo
Altere o valor MTU para todas as portas em um domínio de broadcast:

....
network port broadcast-domain modify -broadcast-domain <broadcast_domain_name> -mtu <mtu_value> [-ipspace <ipspace_name>]
....
* `broadcast_domain` é o nome do domínio de broadcast.
* `mtu` É o tamanho MTU para pacotes IP; 1500 e 9000 são valores típicos.
* `ipspace` É o nome do IPspace no qual esse domínio de broadcast reside. O espaço IPspace "padrão" é usado a menos que você especifique um valor para esta opção. O comando a seguir altera o MTU para 9000 para todas as portas no domínio de broadcast bcast1:


....
network port broadcast-domain modify -broadcast-domain <Default-1> -mtu < 9000 >
Warning: Changing broadcast domain settings will cause a momentary data-serving interruption.
Do you want to continue? {y|n}: <y>
....
.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/network-port-broadcast-domain-modify.html["modificação do domínio de difusão da porta de rede"^]

