---
sidebar: sidebar 
permalink: networking/commands_for_managing_firewall_service_and_policies.html 
keywords: manage, managing, firewall, fire, wall, service, policy, policies, commands for managing firewall service and policies, system services firewall, system services firewall policy, network interface modify, system services firewall modify, system services firewall show, system services firewall policy create, network interface modify -lif lifname -firewall-policy, system services firewall policy modify, system services firewall policy show, system services firewall policy clone, system services firewall policy delete 
summary: Gerenciar o serviço de firewall 
---
= Comandos ONTAP para gerenciar o serviço e as políticas de firewall
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode usar os `system services firewall` comandos para gerenciar o serviço de firewall, os `system services firewall policy` comandos para gerenciar políticas de firewall e o `network interface modify` comando para gerenciar configurações de firewall para LIFs.

Começando com ONTAP 9.10,1:

* As políticas de firewall são obsoletas e são substituídas por políticas de serviço LIF. Anteriormente, o firewall integrado era gerenciado usando políticas de firewall. Essa funcionalidade agora é realizada usando uma política de serviço LIF.
* Todas as políticas de firewall estão vazias e não abrem nenhuma porta no firewall subjacente. Em vez disso, todas as portas devem ser abertas usando uma política de serviço LIF.
* Nenhuma ação é necessária após uma atualização para 9.10.1 ou posterior para a transição de políticas de firewall para políticas de serviço LIF. O sistema constrói automaticamente políticas de serviço LIF consistentes com as políticas de firewall em uso na versão anterior do ONTAP. Se você usar scripts ou outras ferramentas que criam e gerenciam políticas de firewall personalizadas, talvez seja necessário atualizar esses scripts para criar políticas de serviço personalizadas.


Para saber mais, link:lifs_and_service_policies96.html["LIFs e políticas de serviço no ONTAP 9.6 e posteriores"]consulte .

|===


| Se você quiser... | Use este comando... 


 a| 
Ativar ou desativar o serviço de firewall
 a| 
`system services firewall modify`



 a| 
Exibir a configuração atual do serviço de firewall
 a| 
`system services firewall show`



 a| 
Crie uma política de firewall ou adicione um serviço a uma política de firewall existente
 a| 
`system services firewall policy create`



 a| 
Aplique uma política de firewall a um LIF
 a| 
`network interface modify -lif lifname -firewall-policy`



 a| 
Modifique os endereços IP e as máscaras de rede associadas a uma política de firewall
 a| 
`system services firewall policy modify`



 a| 
Exibir informações sobre políticas de firewall
 a| 
`system services firewall policy show`



 a| 
Crie uma nova política de firewall que seja uma cópia exata de uma política existente
 a| 
`system services firewall policy clone`



 a| 
Exclua uma política de firewall que não seja usada por um LIF
 a| 
`system services firewall policy delete`

|===
.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+services+firewall["firewall dos serviços do sistema"^]
* link:https://docs.netapp.com/us-en/ontap-cli/network-interface-modify.html["modificação da interface de rede"^]

