---
sidebar: sidebar 
permalink: networking/configure-tls-offload.html 
keywords: TLS offload, TLS, performance 
summary: Configurar as definições de descarregamento TLS 
---
= Configurar o descarregamento de hardware TLS do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.19.1, você pode configurar o descarregamento de TLS para melhorar o desempenho pós-handshake do TLS, utilizando recursos em placas Ethernet compatíveis. Esse recurso descarrega a criptografia e a descriptografia, reduzindo a sobrecarga da CPU e melhorando o desempenho.

Você pode habilitar o descarregamento de TLS apenas para o tráfego que usa KTLS. Essa configuração não se aplica a todo o tráfego habilitado para TLS. O tráfego de gerenciamento, como HTTPS e tráfego de API REST, não é afetado por essa configuração. O tráfego de HA não é compatível.

.Sobre esta tarefa
* O descarregamento TLS está desativado por padrão.
* Apenas os conjuntos de cifras AES-GCM (TLSv1.2/TLSv1.3, 128/256-bit) são descarregados.
* A fase de handshake TLS não é descarregada. Apenas a fase de dados pós-handshake é descarregada.
* A migração da interface lógica de rede (LIF) para portas que não possuem capacidade de offload causa um fallback automático de software.
+
Para conexões com TLS descarregado, as operações criptográficas do TLS normalmente ignoram o software e são tratadas por uma NIC com capacidade de descarregamento. Se a LIF associada a essa conexão migrar para uma porta de rede sem capacidade de descarregamento de TLS, as operações criptográficas passam a ser tratadas por software e pelo kernel do sistema.

* As interfaces de gerenciamento (HTTPS, API REST) não são afetadas por essa configuração.
* O descarregamento de hardware TLS é uma configuração que se aplica a todo o cluster.
* O tráfego HA não é compatível com o descarregamento de hardware TLS.


.Placas de rede e plataformas suportadas
O descarregamento de hardware TLS requer uma placa de rede compatível. A tabela a seguir lista as placas de rede compatíveis por plataforma.

[cols="1,2,3a"]
|===
| Família de plataformas | Plataformas | Placas de rede suportadas 


| AFF e FAS | AFF A20, AFF A30, AFF A50, AFF C30, AFF C60, FAS50  a| 
* CX7 de 4 portas 10/25 GbE
* CX6-DX de 2 portas 40/100 GbE
* CX7 de 2 portas 40/100 GbE




| AFF e FAS | AFF A70, AFF A90, AFF C80, FAS70, FAS90, AFF A1K  a| 
* CX6-DX de 2 portas 40/100 GbE
* CX7 de 2 portas 40/100 GbE
* CX7 de 2 portas 40/100/200/400 GbE




| ASA | ASA A20, ASA A30, ASA A50, ASA C30  a| 
* CX7 de 4 portas 10/25 GbE
* CX6-DX de 2 portas 40/100 GbE
* CX7 de 2 portas 40/100 GbE




| ASA | ASA A70, ASA A90, ASA A1K  a| 
* CX6-DX de 2 portas 40/100 GbE
* CX7 de 2 portas 40/100 GbE
* CX7 de 2 portas 40/100/200/400 GbE




| AFX | AFX 1K  a| 
* CX6-DX de 2 portas 40/100 GbE
* CX7 de 2 portas 40/100 GbE
* CX7 de 2 portas 40/100/200/400 GbE




| AFX | AFX 2K  a| 
* CX7 de 2 portas 40/100/200/400 GbE


|===
.Tipos de tráfego suportados
A tabela a seguir mostra se o descarregamento de hardware TLS é compatível com cada tipo de tráfego.

[cols="1,1,2"]
|===
| Tipo de tráfego | Suportado | Notas 


| NVMe/TCP | Sim | Compatível com plataformas e placas de rede que suportam o descarregamento de TLS. 


| Criptografia de emparelhamento de cluster | Sim | Compatível com tráfego de rede do cluster. Isso não inclui tráfego de alta disponibilidade (HA). 


| FabricPool | Sim | Compatível com plataformas e placas de rede que suportam o descarregamento de TLS. 


| S3 | Sim | Compatível com plataformas e placas de rede que suportam o descarregamento de TLS. 


| NFS sobre TLS | Sim, a partir do ONTAP 9.19.1 | Compatível para o tráfego de NFS do ONTAP sobre TLS onde KTLS é utilizado. 


| KMIP | Não | Não suportado. 


| System Manager | Não | As interfaces de gerenciamento não são afetadas por esta configuração. 


| API REST | Não | As interfaces de gerenciamento não são afetadas por esta configuração. 


| Tráfego HA | Não | O descarregamento de hardware TLS não se aplica ao tráfego HA. 
|===

NOTE: Em sistemas ASA, o descarregamento de hardware TLS se aplica apenas ao tráfego NVMe/TCP. NFS sobre TLS, FabricPool e S3 não são suportados em plataformas ASA.


NOTE: Nas plataformas AFX, o descarregamento de hardware TLS suporta NFS sobre TLS e tipos de tráfego front-end S3. NVMe/TCP não é suportado nas plataformas AFX porque o AFX não suporta protocolos SAN/block.

.Antes de começar
* Você precisa ser um administrador do ONTAP no `admin` Nível de privilégio necessário para executar as seguintes tarefas.
* Todos os nós devem estar executando ONTAP 9.19.1 ou posterior.




[[enable-or-disable-tls-offload]]
== Ativar ou desativar o offload de TLS

.Passos
. Veja o status atual do descarregamento TLS:
+
[source, cli]
----
security config show
----
+
Este comando exibe a configuração de descarregamento TLS em todo o cluster:

+
[listing]
----
cluster1::*> security config show
Cluster    Supported Offload
FIPS Mode  Protocols Enabled Supported Cipher Suites
---------- --------- ------- --------------------------------------------------
false      TLSv1.3,  false   TLS_RSA_WITH_AES_128_CCM,
           TLSv1.2           TLS_RSA_WITH_AES_128_CCM_8,
                             TLS_RSA_WITH_AES_128_GCM_SHA256,
                             TLS_RSA_WITH_AES_128_CBC_SHA,
                             TLS_RSA_WITH_AES_128_CBC_SHA256,
                             TLS_RSA_WITH_AES_256_CCM,
[...]
----
. Ativar ou desativar o descarregamento TLS:
+
[source, cli]
----
security config modify * -is-offload-enabled {true|false}
----
+
Este comando ativa ou desativa o descarregamento de hardware para a fase de dados TLS em novas conexões. Conexões existentes criadas antes da ativação do recurso de descarregamento de TLS não são descarregadas até que essas conexões sejam removidas e recriadas.



.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/security-config-show.html["security config show"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-config-modify.html["modificar configuração de segurança"^]

