---
sidebar: sidebar 
permalink: networking/configure_failover_groups_and_policies_for_lifs_overview.html 
keywords: lif, failover, fail, over, target, automatic, automatically, port, link, failure, group, broadcast, domain, lif failover is the automatic migration of a lif to a different network port in response to a link failure, configure failover groups and policies for lifs overview, network interface show -failover 
summary: O failover de LIF é a migração automática de um LIF para uma porta de rede diferente em resposta a uma falha de link 
---
= Saiba mais sobre o failover de LIF em redes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Failover de LIF refere-se à migração automática de um LIF para uma porta de rede diferente em resposta a uma falha de link na porta atual do LIF. Este é um componente chave para fornecer alta disponibilidade para as conexões com SVMs. A configuração do failover de LIF envolve a criação de um grupo de failover, a modificação do LIF para usar o grupo de failover e a especificação de uma política de failover.

Um grupo de failover contém um conjunto de portas de rede (portas físicas, VLANs e grupos de interfaces) de um ou mais nós em um cluster. As portas de rede que estão presentes no grupo failover definem os destinos de failover disponíveis para o LIF. Um grupo de failover pode ter gerenciamento de clusters, gerenciamento de nós, clusters e LIFs de dados nas atribuídos a ele.


IMPORTANT: Quando um LIF é configurado sem um destino de failover válido, ocorre uma interrupção quando o LIF tenta fazer failover. Você pode usar o `network interface show -failover` comando para verificar a configuração de failover. Saiba mais sobre `network interface show` o link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["Referência do comando ONTAP"^]na .

Quando você cria um domínio de broadcast, um grupo de failover com o mesmo nome é criado automaticamente que contém as mesmas portas de rede. Esse grupo de failover é gerenciado automaticamente pelo sistema, o que significa que, à medida que as portas são adicionadas ou removidas do domínio de broadcast, elas são adicionadas ou removidas automaticamente desse grupo de failover. Isso é fornecido como uma eficiência para administradores que não desejam gerenciar seus próprios grupos de failover.
