---
sidebar: sidebar 
permalink: networking/configure_host-name_resolution_overview.html 
keywords: dns, translate, ddns, introduction, introducing, overview, configure host name resolution overview, translate host names 
summary: Traduzir nomes de host para endereços IP numéricos 
---
= Visão geral da resolução do nome do host
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O ONTAP deve ser capaz de traduzir nomes de host para endereços IP numéricos, a fim de fornecer acesso aos clientes e aos serviços de acesso. Você deve configurar máquinas virtuais de armazenamento (SVMs) para usar serviços de nome locais ou externos para resolver informações de host. O ONTAP suporta a configuração de um servidor DNS externo ou a configuração do arquivo hosts local para resolução de nome de host.

Ao usar um servidor DNS externo, você pode configurar o DNS dinâmico (DDNS), que envia automaticamente informações DNS novas ou alteradas do seu sistema de armazenamento para o servidor DNS. Sem atualizações de DNS dinâmicas, você deve adicionar manualmente informações de DNS (nome de DNS e endereço IP) aos servidores DNS identificados quando um novo sistema é colocado on-line ou quando as informações de DNS existentes forem alteradas. Este processo é lento e propenso a erros. Durante a recuperação de desastres, a configuração manual pode resultar em um longo tempo de inatividade.
