---
sidebar: sidebar 
permalink: networking/configure_dns_for_host-name_resolution.html 
keywords: configure, configuring, configuration, setup, set, setting, dns, local, remote, host, name, host-name, resolution, configure dns for host-name resolution, nsswitch.conf, configure an svm and data lifs for host-name resolution using an external dns server, vserver services name-service dns, vserver services name-service dns create, network interface modify -lif lifname -dns-zone, network interface create -lif lifname -dns-zone, vserver services name-service dns check, configure the name service switch table for host-name resolution 
summary: Use o DNS para acessar fontes locais ou remotas para obter informações sobre o host 
---
= Configurar DNS para resolução de nome de host
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você usa o DNS para acessar fontes locais ou remotas para obter informações sobre o host. Você deve configurar o DNS para acessar uma ou ambas as fontes.

O ONTAP deve ser capaz de procurar informações de host para fornecer acesso adequado aos clientes. Você deve configurar serviços de nomes para permitir que o ONTAP acesse serviços DNS locais ou externos para obter as informações do host.

O ONTAP armazena informações de configuração do serviço de nomes em uma tabela equivalente `/etc/nsswitch.conf` ao arquivo em sistemas UNIX.



== Configurar uma SVM e LIFs de dados para resolução de nome de host usando um servidor DNS externo

Você pode usar o `vserver services name-service dns` comando para habilitar o DNS em uma SVM e configurá-lo para usar o DNS para resolução de nome de host. Os nomes de host são resolvidos usando servidores DNS externos.

.Antes de começar
Um servidor DNS em todo o site deve estar disponível para pesquisas de nome de host.

Você deve configurar mais de um servidor DNS para evitar um único ponto de falha. O `vserver services name-service dns create` comando emite um aviso se você inserir apenas um nome de servidor DNS.

.Sobre esta tarefa
Consulte xref:configure_dynamic_dns_services.html[Configurar serviços DNS dinâmicos] para obter mais informações sobre como configurar o DNS dinâmico no SVM.

.Passos
. Habilite o DNS na SVM:
+
....
vserver services name-service dns create -vserver <vserver_name> -domains <domain_name> -name-servers <ip_addresses> -state enabled
....
+
O comando a seguir habilita servidores de servidor DNS externos no SVM VS1:

+
....
vserver services name-service dns create -vserver vs1.example.com -domains example.com -name-servers 192.0.2.201,192.0.2.202 -state enabled
....
+

NOTE: O `vserver services name-service dns create` comando executa uma validação automática de configuração e relata uma mensagem de erro se o ONTAP não puder entrar em Contato com o servidor de nomes.

. Valide o status dos servidores de nomes usando o `vserver services name-service dns check` comando.
+
....
vserver services name-service dns check -vserver vs1.example.com
                                    Name Server
Vserver             Name Server     Status       Status Details
-------------       --------------- ------------ --------------------------
vs1.example.com     10.0.0.50       up           Response time (msec): 2
vs1.example.com     10.0.0.51       up           Response time (msec): 2
....


Para obter informações sobre políticas de serviço relacionadas ao DNS, link:lifs_and_service_policies96.html["LIFs e políticas de serviço no ONTAP 9.6 e posteriores"]consulte .



== Configure a Tabela de interrutores do serviço de nomes para resolução de nome de host

Você deve configurar a tabela de switch de serviço de nomes corretamente para permitir que o ONTAP consulte o serviço de nomes local ou externo para recuperar informações do host.

.Antes de começar
Você deve ter decidido qual serviço de nomes usar para mapeamento de host em seu ambiente.

.Passos
. Adicione as entradas necessárias à tabela do switch de serviço de nomes:
+
....
vserver services name-service ns-switch modify -vserver <vserver_name> -database <database_name> -source <source_names>
....
. Verifique se a tabela do switch de serviço de nomes contém as entradas esperadas na ordem desejada:
+
....
vserver services name-service ns-switch show -vserver <vserver_name>
....


.Exemplo
O exemplo a seguir modifica uma entrada na tabela de switch de serviço de nomes para SVM VS1 para primeiro usar o arquivo hosts locais e, em seguida, um servidor DNS externo para resolver nomes de host:

....
vserver services name-service ns-switch modify -vserver vs1 -database hosts -sources files,dns
....