---
sidebar: sidebar 
permalink: networking/configure_qos_marking_cluster_administrators_only_overview.html 
keywords: quality, service, qos, marking, network, traffic, DSCP, IP, IPspace, protocol, NFS, SMB, iSCSI, SnapMirror, NDMP, FTP, HTTP, HTTPS, SSH, Telnet, SNMP 
summary: A marcação QoS ajuda a priorizar diferentes tipos de tráfego com base nas condições de rede para usar efetivamente os recursos de rede. 
---
= Visão geral do QoS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A marcação de qualidade de serviço (QoS) da rede ajuda a priorizar diferentes tipos de tráfego com base nas condições da rede para usar efetivamente os recursos da rede. Você pode definir o valor de ponto de código de serviços diferenciados (DSCP) dos pacotes IP de saída para os tipos de tráfego suportados por espaço de IPspace.



== Marcação DSCP para conformidade com UC

Você pode ativar a marcação DSCP (Differentiated Services Code Point) no tráfego de pacotes IP de saída (saída) para um determinado protocolo com um código DSCP padrão ou fornecido pelo usuário. A marcação DSCP é um mecanismo para classificar e gerenciar o tráfego de rede e é um componente da conformidade com a capacidade Unificada (UC).

A marcação DSCP (também conhecida como _marcação QoS_ ou _marcação de qualidade de serviço_) é ativada fornecendo um valor IPspace, protocolo e DSCP. Os protocolos nos quais a marcação DSCP pode ser aplicada são NFS, SMB, iSCSI, SnapMirror, NDMP, FTP, HTTP/HTTPS, SSH, Telnet e SNMP.

Se você não fornecer um valor DSCP ao ativar a marcação DSCP para um determinado protocolo, um padrão será usado:

* O valor predefinido para protocolos/tráfego de dados é 0x0A (10).
* O valor predefinido para protocolos de controlo/tráfego é 0x30 (48).

