---
sidebar: sidebar 
permalink: networking/configure_subnets_cluster_administrators_only_overview.html 
keywords: configure, configuration, configuring, setup, setting, set, up, subnet, overview, introduction, introducing, network interface create, configure subnets overview, introducing subnets 
summary: Introdução às sub-redes 
---
= Saiba mais sobre sub-redes para a rede ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
As sub-redes permitem alocar blocos ou pools específicos de endereços IP para a configuração da rede ONTAP. Isso permite que você crie LIFs mais facilmente especificando um nome de sub-rede em vez de precisar especificar o endereço IP e os valores de máscara de rede.

Uma sub-rede é criada dentro de um domínio de broadcast e contém um conjunto de endereços IP que pertencem à mesma sub-rede de camada 3. Os endereços IP em uma sub-rede são alocados às portas no domínio de broadcast quando os LIFs são criados. Quando os LIFs são removidos, os endereços IP são retornados ao pool de sub-redes e estão disponíveis para LIFs futuros.

É recomendável que você use sub-redes porque elas facilitam muito o gerenciamento de endereços IP e tornam a criação de LIFs um processo mais simples. Além disso, se você especificar um gateway ao definir uma sub-rede, uma rota padrão para esse gateway será adicionada automaticamente ao SVM quando um LIF é criado usando essa sub-rede.
