---
sidebar: sidebar 
permalink: networking/convert_40gbe_nic_ports_into_multiple_10gbe_ports_for_10gbe_connectivity.html 
keywords: configure, configuration, configuring, setup, setting, set, up, network, interface, card, nic, gigabit, ethernet, 40, 10, port, convert, convert 40gbe nic ports into multiple 10gbe ports for 10gbe connectivity 
summary: 40GbE NICs podem suportar quatro portas 10GbE 
---
= Converta 40GbE portas NIC em várias portas 10GbE para conetividade 10GbE
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Pode converter as placas de interface de rede (NICs) X1144A-R6 e X91440A-R6 40GbE para suportar quatro portas 10GbE.

Se você estiver conetando uma plataforma de hardware que suporte uma dessas NICs a um cluster que suporte a interconexão de cluster 10GbE e conexões de dados do cliente, a NIC deve ser convertida para fornecer as conexões 10GbE necessárias.

.Antes de começar
Você deve estar usando um cabo multicondutor suportado.

.Sobre esta tarefa
Para obter uma lista completa de plataformas que suportam NICs, consulte https://hwu.netapp.com/["Hardware Universe"^] .


NOTE: Na NIC X1144A-R6, somente a porta A pode ser convertida para suportar as quatro conexões 10GbE. Uma vez que a porta A é convertida, a porta e não está disponível para uso.

.Passos
. Entre no modo de manutenção.
. Converta a NIC do suporte 40GbE para o suporte 10GbE.
+
....
nicadmin convert –m [40G | 10G] [port-name]
....
. Depois de usar o comando Convert, interrompa o nó.
. Instale ou substitua o cabo.
. Dependendo do modelo de hardware, use o SP (processador de serviço) ou o BMC (controlador de gerenciamento de placa base) para ligar o nó para que a conversão entre em vigor.

