---
sidebar: sidebar 
permalink: networking/display_ipspaces.html 
keywords: display, view, show, ipspace, display ipspaces, list the ipspaces and view ipspace information for the cluster 
summary: Liste os IPspaces e exiba informações de IPspace para o cluster 
---
= Apresentar IPspaces
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode exibir a lista de IPspaces que existem em um cluster e pode exibir as máquinas virtuais de armazenamento (SVMs), domínios de broadcast e portas que são atribuídas a cada IPspace.

.Passo
Exibir os IPspaces e SVMs em um cluster:

....
network ipspace show [-ipspace ipspace_name]
....
O comando a seguir exibe todos os domínios IPspaces, SVMs e broadcast no cluster:

....
network ipspace show
IPspace        Vserver List             Broadcast Domains
-------------  -----------------------  -------------------
Cluster
               Cluster                  Cluster
Default
               vs1, cluster-1            Default
ipspace1
               vs3, vs4, ipspace1       bcast1
....
O comando a seguir exibe os nós e as portas que fazem parte do IPspace ipspace1:

....
network ipspace show -ipspace ipspace1
IPspace name: ipspace1
Ports: cluster-1-01:e0c, cluster-1-01:e0d, cluster-1-01:e0e, cluster-1-02:e0c, cluster-1-02:e0d, cluster-1-02:e0e
Broadcast Domains: Default-1
Vservers: vs3, vs4, ipspace1
....