---
sidebar: sidebar 
permalink: networking/display_interface_group_information_@cluster_administrators_only@.html 
keywords: 'display, view, show, interface, group, information, display interface group information (cluster administrators only), verify interface group configuration, network port ifgrp show' 
summary: Verifique a configuração do grupo de interfaces 
---
= Exibir informações do grupo de interfaces (somente administradores de cluster)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode exibir informações sobre um grupo de interfaces para determinar sua configuração.

.Sobre esta tarefa
São apresentadas as seguintes informações:

* Nó no qual o grupo de interfaces está localizado
* Lista de portas de rede incluídas no grupo de interfaces
* Nome do grupo de interfaces
* Função de distribuição (MAC, IP, porta ou sequencial)
* Endereço MAC (Media Access Control) do grupo de interfaces
* Status da atividade da porta; ou seja, se todas as portas agregadas estão ativas (participação total), se algumas estão ativas (participação parcial) ou se nenhuma está ativa


.Passo
Exiba informações sobre grupos de interface usando o `network port ifgrp show` comando.

Você pode exibir informações detalhadas para cada nó especificando o `-instance` parâmetro. Você pode exibir informações específicas especificando nomes de campos usando o `-fields` parâmetro.

O comando a seguir exibe informações sobre todos os grupos de interface no cluster:

....
network port ifgrp show
         Port     Distribution                    Active
Node     IfGrp    Function     MAC Address        Ports   Ports
-------- -------- ------------ -----------------  ------- --------
cluster-1-01
         a0a      ip           02:a0:98:06:10:b2  full    e7a, e7b
cluster-1-02
         a0a      sequential   02:a0:98:06:10:ca  full    e7a, e7b
cluster-1-03
         a0a      port         02:a0:98:08:5b:66  full    e7a, e7b
cluster-1-04
         a0a      mac          02:a0:98:08:61:4e  full    e7a, e7b
....
O comando a seguir exibe informações detalhadas do grupo de interfaces para um único nó:

....
network port ifgrp show -instance -node cluster-1-01

                 Node: cluster-1-01
 Interface Group Name: a0a
Distribution Function: ip
        Create Policy: multimode
          MAC Address: 02:a0:98:06:10:b2
   Port Participation: full
        Network Ports: e7a, e7b
             Up Ports: e7a, e7b
           Down Ports: -
....