---
sidebar: sidebar 
permalink: networking/display_cluster_connections.html 
keywords: 'display, view, show, cluster, connections, active, client, listening, lif, protocol, service, display cluster connections, view all the active or listening connections in the cluster or a count of active connections on the node by client, lif, protocol, or service, display active connections by client (cluster administrators only), network connections active show-clients, display active connections by protocol (cluster administrators only), network connections active show-protocols, display active connections by service (cluster administrators only), network connections active show-services, display active connections by lif on a node and svm, network connections active show-lifs, display active connections in a cluster, network connections active show, display listening connections in a cluster, network connections listening show' 
summary: Visualize todas as conexões ativas ou de escuta no cluster ou uma contagem de conexões ativas no nó por cliente, LIF, protocolo ou serviço 
---
= Veja as conexões do cluster do ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode exibir todas as conexões ativas no cluster ou uma contagem de conexões ativas no nó por cliente, interface lógica, protocolo ou serviço. Também pode apresentar todas as ligações de audição no cluster.



== Exibir conexões ativas pelo cliente (somente administradores de cluster)

Você pode exibir as conexões ativas por cliente para verificar o nó que um cliente específico está usando e para exibir possíveis desequilíbrios entre contagens de clientes por nó.

.Sobre esta tarefa
A contagem de conexões ativas por cliente é útil nos seguintes cenários:

* Encontrando um nó ocupado ou sobrecarregado.
* Determinar por que o acesso de um cliente específico a um volume é lento.
+
Você pode ver detalhes sobre o nó que o cliente está acessando e compará-lo com o nó no qual o volume reside. Se o acesso ao volume exigir a travessia da rede do cluster, os clientes podem ter um desempenho reduzido devido ao acesso remoto ao volume em um nó remoto substituído.

* Verificar se todos os nós estão sendo usados igualmente para acesso aos dados.
* Encontrando clientes que têm um número inesperadamente alto de conexões.
* Verificando se certos clientes têm conexões com um nó.


.Passo
Exibir uma contagem das conexões ativas por cliente em um nó usando o `network connections active show-clients` comando.

Saiba mais sobre `network connections active show-clients` o link:http://docs.netapp.com/us-en/ontap-cli/network-connections-active-show-clients.html["Referência do comando ONTAP"^]na .

....
network connections active show-clients
Node    Vserver Name    Client IP Address     Count
------  --------------  -----------------     ------
node0   vs0             192.0.2.253                1
        vs0             192.0.2.252                2
        Cluster         192.10.2.124               5
node1   vs0             192.0.2.250                1
        vs0             192.0.2.252                3
        Cluster         192.10.2.123               4
node2   vs1             customer.example.com       1
        vs1             192.0.2.245                3
        Cluster         192.10.2.122               4
node3   vs1             customer.example.org       1
        vs1             customer.example.net       3
        Cluster         192.10.2.121               4
....


== Exibir conexões ativas por protocolo (somente administradores de cluster)

É possível exibir uma contagem das conexões ativas por protocolo (TCP ou UDP) em um nó para comparar o uso de protocolos dentro do cluster.

.Sobre esta tarefa
A contagem de conexões ativas por protocolo é útil nos seguintes cenários:

* Encontrando os clientes UDP que estão perdendo sua conexão.
+
Se um nó estiver próximo ao limite de conexão, os clientes UDP serão os primeiros a serem descartados.

* Verificar se não estão a ser utilizados outros protocolos.


.Passo
Exibir uma contagem das conexões ativas por protocolo em um nó usando o `network connections active show-protocols` comando.

Saiba mais sobre `network connections active show-protocols` o link:https://docs.netapp.com/us-en/ontap-cli/network-connections-active-show-protocols.html["Referência do comando ONTAP"^]na .

....
network connections active show-protocols
Node     Vserver Name  Protocol   Count
-------  ------------  ---------  ------
node0
         vs0           UDP            19
         Cluster       TCP            11
node1
         vs0           UDP            17
         Cluster       TCP             8
node2
         vs1           UDP            14
         Cluster       TCP            10
node3
         vs1           UDP            18
         Cluster       TCP             4
....


== Exibir conexões ativas por serviço (somente administradores de cluster)

É possível exibir uma contagem das conexões ativas por tipo de serviço (por exemplo, por NFS, SMB, montagem etc.) para cada nó em um cluster. Isso é útil para comparar o uso de serviços no cluster, o que ajuda a determinar a carga de trabalho principal de um nó.

.Sobre esta tarefa
A contagem de conexões ativas por serviço é útil nos seguintes cenários:

* Verificar se todos os nós estão sendo usados para os serviços apropriados e se o balanceamento de carga para esse serviço está funcionando.
* Verificar se não estão a ser utilizados outros serviços. Exibir uma contagem das conexões ativas por serviço em um nó usando o `network connections active show-services` comando.


Saiba mais sobre `network connections active show-services` o link:https://docs.netapp.com/us-en/ontap-cli/network-connections-active-show-services.html["Referência do comando ONTAP"^]na .

....
network connections active show-services
Node       Vserver Name    Service    Count
---------  --------------  ---------  ------
node0
           vs0             mount           3
           vs0             nfs            14
           vs0             nlm_v4          4
           vs0             cifs_srv        3
           vs0             port_map       18
           vs0             rclopcp        27
           Cluster         ctlopcp        60
node1
           vs0             cifs_srv        3
           vs0             rclopcp        16
           Cluster         ctlopcp        60
node2
           vs1             rclopcp        13
           Cluster         ctlopcp        60
node3
           vs1             cifs_srv        1
           vs1             rclopcp        17
           Cluster         ctlopcp        60
....


== Exibir conexões ativas por LIF em um nó e SVM

É possível exibir uma contagem de conexões ativas para cada LIF, por nó e máquina virtual de armazenamento (SVM), para visualizar desequilíbrios de conexão entre LIFs no cluster.

.Sobre esta tarefa
A contagem de conexões ativas por LIF é útil nos seguintes cenários:

* Encontrando um LIF sobrecarregado comparando o número de conexões em cada LIF.
* Verificando se o balanceamento de carga DNS está funcionando para todas as LIFs de dados.
* Comparando o número de conexões com os vários SVMs para encontrar os SVMs que são mais usados.


.Passo
Exiba uma contagem de conexões ativas para cada LIF por SVM e nó usando o `network connections active show-lifs` comando.

Saiba mais sobre `network connections active show-lifs` o link:https://docs.netapp.com/us-en/ontap-cli/network-connections-active-show-lifs.html["Referência do comando ONTAP"^]na .

....
network connections active show-lifs
Node      Vserver Name  Interface Name  Count
--------  ------------  --------------- ------
node0
          vs0           datalif1             3
          Cluster       node0_clus_1         6
          Cluster       node0_clus_2         5
node1
          vs0           datalif2             3
          Cluster       node1_clus_1         3
          Cluster       node1_clus_2         5
node2
          vs1           datalif2             1
          Cluster       node2_clus_1         5
          Cluster       node2_clus_2         3
node3
          vs1           datalif1             1
          Cluster       node3_clus_1         2
          Cluster       node3_clus_2         2
....


== Exibir conexões ativas em um cluster

Você pode exibir informações sobre as conexões ativas em um cluster para exibir o LIF, a porta, o host remoto, o serviço, as máquinas virtuais de armazenamento (SVMs) e o protocolo usado por conexões individuais.

.Sobre esta tarefa
Visualizar as conexões ativas em um cluster é útil nos seguintes cenários:

* Verificar se clientes individuais estão usando o protocolo e o serviço corretos no nó correto.
* Se um cliente estiver tendo problemas para acessar dados usando uma certa combinação de nó, protocolo e serviço, você pode usar este comando para encontrar um cliente semelhante para comparação de configuração ou rastreamento de pacotes.


.Passo
Exiba as conexões ativas em um cluster usando o `network connections active show` comando.

Saiba mais sobre `network connections active show` o link:https://docs.netapp.com/us-en/ontap-cli/network-connections-active-show.html["Referência do comando ONTAP"^]na .

O comando a seguir mostra as conexões ativas no nó node1:

....
network connections active show -node node1
Vserver  Interface           Remote
Name     Name:Local Port     Host:Port           Protocol/Service
-------  ------------------  ------------------  ----------------
Node: node1
Cluster  node1_clus_1:50297  192.0.2.253:7700    TCP/ctlopcp
Cluster  node1_clus_1:13387  192.0.2.253:7700    TCP/ctlopcp
Cluster  node1_clus_1:8340   192.0.2.252:7700    TCP/ctlopcp
Cluster  node1_clus_1:42766  192.0.2.252:7700    TCP/ctlopcp
Cluster  node1_clus_1:36119  192.0.2.250:7700    TCP/ctlopcp
vs1      data1:111           host1.aa.com:10741  UDP/port-map
vs3      data2:111           host1.aa.com:10741  UDP/port-map
vs1      data1:111           host1.aa.com:12017  UDP/port-map
vs3      data2:111           host1.aa.com:12017  UDP/port-map
....
O comando a seguir mostra as conexões ativas no SVM VS1:

....
network connections active show -vserver vs1
Vserver  Interface           Remote
Name     Name:Local Port     Host:Port           Protocol/Service
-------  ------------------  ------------------  ----------------
Node: node1
vs1      data1:111           host1.aa.com:10741  UDP/port-map
vs1      data1:111           host1.aa.com:12017  UDP/port-map
....


== Exibir conexões de escuta em um cluster

Você pode exibir informações sobre as conexões de escuta em um cluster para exibir os LIFs e as portas que estão aceitando conexões para um determinado protocolo e serviço.

.Sobre esta tarefa
Visualizar as conexões de escuta em um cluster é útil nos seguintes cenários:

* Verificar se o protocolo ou serviço desejado está escutando em um LIF se as conexões do cliente a esse LIF falharem consistentemente.
* Verificar se um ouvinte UDP/rclopcp é aberto em cada LIF de cluster se o acesso remoto de dados a um volume em um nó por meio de um LIF em outro nó falhar.
* Verificar se um ouvinte UDP/rclopcp é aberto em cada LIF de cluster se as transferências SnapMirror entre dois nós no mesmo cluster falharem.
* Verificando se um ouvinte TCP/ctlopcp é aberto em cada LIF entre clusters se as transferências SnapMirror entre dois nós em clusters diferentes falharem.


.Passo
Exiba as conexões de escuta por nó usando o `network connections listening show` comando.

....
network connections listening show
Vserver Name     Interface Name:Local Port        Protocol/Service
---------------- -------------------------------  ----------------
Node: node0
Cluster          node0_clus_1:7700                TCP/ctlopcp
vs1              data1:4049                       UDP/unknown
vs1              data1:111                        TCP/port-map
vs1              data1:111                        UDP/port-map
vs1              data1:4046                       TCP/sm
vs1              data1:4046                       UDP/sm
vs1              data1:4045                       TCP/nlm-v4
vs1              data1:4045                       UDP/nlm-v4
vs1              data1:2049                       TCP/nfs
vs1              data1:2049                       UDP/nfs
vs1              data1:635                        TCP/mount
vs1              data1:635                        UDP/mount
Cluster          node0_clus_2:7700                TCP/ctlopcp
....
Saiba mais sobre `network connections listening show` o link:https://docs.netapp.com/us-en/ontap-cli/network-connections-listening-show.html["Referência do comando ONTAP"^]na .
