---
sidebar: sidebar 
permalink: networking/display_dns_host_table_entries_@cluster_administrators_only@.html 
keywords: 'display, view, show, dns, host, names, alias, display dns host table entries (cluster administrators only), view the host and alias names and the mapped ip addresses for all svms in a cluster, vserver services name-service dns' 
summary: Exibir os nomes de host e alias e os endereços IP mapeados para todos os SVMs em um cluster 
---
= Exibir entradas da tabela do host DNS (somente administradores de cluster)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
As entradas da tabela de hosts DNS mapeiam nomes de host para endereços IP. É possível exibir os nomes de host e os nomes de alias e o endereço IP para o qual eles mapeiam para todos os SVMs em um cluster.

.Passo
Exiba as entradas de nome de host para todos os SVMs usando o comando show de hosts dns de serviços vserver.

O exemplo a seguir exibe as entradas da tabela do host:

....
vserver services name-service dns hosts show
Vserver    Address        Hostname        Aliases
---------- -------------- --------------- ---------------------
cluster-1
           10.72.219.36   lnx219-36       -
vs1
           10.72.219.37   lnx219-37       lnx219-37.example.com
....
Você pode usar o `vserver services name-service dns` comando para habilitar o DNS em uma SVM e configurá-lo para usar o DNS para resolução de nome de host. Os nomes de host são resolvidos usando servidores DNS externos.
