---
sidebar: sidebar 
permalink: networking/display_routing_information.html 
keywords: display, view, show, route, svm, storage, virtual, machine, display routing information, view information about the routing configuration for each svm on your cluster, network route show, network route show-lifs, network route active-entry show 
summary: Veja informações sobre a configuração de roteamento para cada SVM no cluster 
---
= Exibir informações de roteamento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode exibir informações sobre a configuração de roteamento para cada SVM no cluster. Isso pode ajudá-lo a diagnosticar problemas de roteamento envolvendo problemas de conetividade entre aplicativos ou serviços cliente e um LIF em um nó no cluster.

.Passos
. Use o `network route show` comando para exibir rotas dentro de um ou mais SVMs. O exemplo a seguir mostra uma rota configurada no vs0 SVM:
+
....
network route show
  (network route show)
Vserver             Destination     Gateway         Metric
------------------- --------------- --------------- ------
vs0
                    0.0.0.0/0       172.17.178.1    20
....
. Use o `network route show-lifs` comando para exibir a associação de rotas e LIFs em um ou mais SVMs.
+
O exemplo a seguir mostra LIFs com rotas pertencentes ao SVM vs0:

+
....
network route show-lifs
  (network route show-lifs)

Vserver: vs0
Destination             Gateway                 Logical Interfaces
----------------------  --------------          --------------------
0.0.0.0/0               172.17.178.1            cluster_mgmt,
                                                LIF-b-01_mgmt1,
                                                LIF-b-02_mgmt1
....
. Use o `network route active-entry show` comando para exibir rotas instaladas em um ou mais nós, SVMs, sub-redes ou rotas com destinos especificados.
+
O exemplo a seguir mostra todas as rotas instaladas em um SVM específico:

+
....
network route active-entry show -vserver Data0

Vserver: Data0
Node: node-1
Subnet Group: 0.0.0.0/0
Destination             Gateway              Interface   Metric  Flags
----------------------  -------------------  ---------   ------  -----
127.0.0.1               127.0.0.1            lo              10  UHS
127.0.10.1              127.0.20.1           losk            10  UHS
127.0.20.1              127.0.20.1           losk            10  UHS

Vserver: Data0
Node: node-1
Subnet Group: fd20:8b1e:b255:814e::/64
Destination             Gateway              Interface   Metric  Flags
----------------------  -------------------  ---------   ------  -----
default                 fd20:8b1e:b255:814e::1
                                             e0d             20  UGS
fd20:8b1e:b255:814e::/64
                        link#4               e0d              0  UC

Vserver: Data0
Node: node-2
Subnet Group: 0.0.0.0/0
Destination             Gateway              Interface   Metric  Flags
----------------------  -------------------  ---------   ------  -----
127.0.0.1               127.0.0.1            lo              10  UHS

Vserver: Data0
Node: node-2
Subnet Group: 0.0.0.0/0
Destination             Gateway              Interface   Metric  Flags
----------------------  -------------------  ---------   ------  -----
127.0.10.1              127.0.20.1           losk            10  UHS
127.0.20.1              127.0.20.1           losk            10  UHS

Vserver: Data0
Node: node-2
Subnet Group: fd20:8b1e:b255:814e::/64
Destination             Gateway              Interface   Metric  Flags
----------------------  -------------------  ---------   ------  -----
default                 fd20:8b1e:b255:814e::1
                                             e0d             20  UGS
fd20:8b1e:b255:814e::/64
                        link#4               e0d              0  UC
fd20:8b1e:b255:814e::1  link#4               e0d              0  UHL
11 entries were displayed.
....

