---
sidebar: sidebar 
permalink: networking/enable_multipath_routing.html 
keywords: enable, multipath, routing, load balance, available routes, network, traffic, outgoing traffic, ECMP routing, multipath routing, network options, advanced privilege level, cluster, nodes, metrics 
summary: Ative o roteamento multipath para equilibrar a carga e usar todas as rotas disponíveis 
---
= Ative o roteamento multipath para a rede ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se várias rotas tiverem a mesma métrica para um destino, apenas uma das rotas será selecionada para o tráfego de saída. Isso leva a que outras rotas não sejam utilizadas para enviar tráfego de saída. Você pode habilitar o roteamento multipath para o balanceamento de carga em todas as rotas disponíveis proporcionalmente às suas métricas, em vez do roteamento ECMP, que equilibra a carga entre as rotas disponíveis da mesma métrica.

.Passos
. Inicie sessão no nível de privilégio avançado:
+
`set -privilege advanced`

. Ativar o roteamento multipath:
+
`network options multipath-routing modify -is-enabled true`

+
O roteamento multipath está habilitado para todos os nós no cluster.



....
network options multipath-routing modify -is-enabled true
....