---
sidebar: sidebar 
permalink: networking/merge_broadcast_domains.html 
keywords: merge, combine, broadcast, domain, reachability, merge broadcast domains, merge the ports from one broadcast domain into an existing broadcast domain 
summary: Mesclar as portas de um domínio de broadcast em um domínio de broadcast existente 
---
= Mesclar domínios de broadcast (ONTAP 9.8 e posterior)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se a acessibilidade da porta de rede tiver sido alterada, seja por meio de conetividade de rede física ou configuração de switch, e dois grupos de portas de rede previamente configurados em vários domínios de broadcast agora todos compartilham acessibilidade, a mesclagem de dois domínios de broadcast pode ser usada para sincronizar a configuração do ONTAP com a topologia de rede física.

Para determinar se vários domínios de broadcast pertencem a um conjunto de acessibilidade, use o comando "network port alcançability show -details" e preste atenção às portas que são configuradas em outro domínio de broadcast realmente têm conetividade entre si ("portas inesperadas"). Normalmente, a lista de portas inesperadas define o conjunto de portas que devem ser mescladas no domínio de broadcast depois de verificar se a configuração física e do switch é precisa.

.Passo
Mesclar as portas de um domínio de broadcast em um domínio de broadcast existente:

....
network port broadcast-domain merge -ipspace <ipspace_name> -broadcast-domain <broadcast_domain_name> -into-broadcast-domain <broadcast_domain_name>
....
* `ipspace_name` é o nome do ipspace onde os domínios de broadcast residem.
* `-broadcast-domain` é o nome do domínio de broadcast que será mesclado.
* `-into-broadcast-domain` é o nome do domínio de broadcast que receberá portas adicionais.

