---
sidebar: sidebar 
permalink: networking/modify_mtu_setting_for_interface_group_ports.html 
keywords: modify, modifying, change, changing, mtu, modify mtu setting for interface group ports, modify the mtu of the broadcast domain 
summary: Modifique a MTU do domínio de broadcast 
---
= Modifique a configuração MTU para portas do grupo de interfaces ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para modificar a configuração MTU para grupos de interface, você deve modificar a MTU do domínio de broadcast.

O tamanho da MTU da VLAN deve corresponder à MTU do domínio de broadcast dos grupos de interface subjacentes e das portas físicas. Se for necessária uma configuração de VLAN diferente para uma VLAN, ela não deve exceder o tamanho especificado pelo domínio de broadcast subjacente.

.Passos
. Modificar as definições do domínio de difusão:
+
`broadcast-domain modify -broadcast-domain _broadcast_domain_name_ -mtu _mtu_setting_`

+
É apresentada a seguinte mensagem de aviso:

+
....
Warning: Changing broadcast domain settings will cause a momentary data-serving interruption.
Do you want to continue? {y|n}: y
....
. Introduza y para continuar.
. Verifique se a configuração MTU foi modificada corretamente:
+
`network port show`



....
network port show
(network port show)
Node: vsim-01
                                                              Ignore
                                         Speed(Mbps) Health   Health
Port IPspace Broadcast Domain  Link  MTU Admin/Oper  Status   Status
---- ------- ----------------  ---- ---- ----------- -------- ------
a0a  Default Default-1         up   1300 auto/1000   healthy  false
e0a  Default Default-1         up   1300 auto/1000   healthy  false
e0b  Default Default           up   1500 auto/1000   healthy  false
e0c  Default Default           up   1500 auto/1000   healthy  false
e0d  Default Default           up   1500 auto/1000   healthy  false
5 entries were displayed.
....
Saiba mais sobre `network port show` o link:https://docs.netapp.com/us-en/ontap-cli/network-port-show.html["Referência do comando ONTAP"^]na .
