---
sidebar: sidebar 
permalink: networking/modify_qos_marking_values.html 
keywords: change, changing, modify, modifying, qos, quality, service, marking, performance, modify qos marking values, change the qos marking values for different protocols, network qos-marking modify 
summary: Altere os valores de marcação de QoS para diferentes protocolos 
---
= Modificar valores de marcação QoS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode modificar os valores de marcação de qualidade do serviço (QoS) para diferentes protocolos, para cada IPspace.

.Antes de começar
Todos os nós no cluster devem estar executando a mesma versão do ONTAP.

.Passo
Modifique os valores de marcação de QoS usando o `network qos-marking modify` comando.

* O `–ipspace` parâmetro especifica o espaço IPspace para o qual a entrada de marcação QoS deve ser modificada.
* O `–protocol` parâmetro especifica o protocolo para o qual a entrada de marcação QoS deve ser modificada. A `network qos-marking modify` página man descreve os possíveis valores do protocolo.
* O `–dscp` parâmetro especifica o valor DSCP (Differentiated Services Code Point). Os valores possíveis variam de 0 a 63.
* O `-is-enabled` parâmetro é utilizado para ativar ou desativar a marcação QoS para o protocolo especificado no espaço IPspace fornecido pelo `–ipspace` parâmetro.


O comando a seguir habilita a marcação QoS para o protocolo NFS no IPspace padrão:

....
network qos-marking modify -ipspace Default -protocol NFS -is-enabled true
....
O comando a seguir define o valor DSCP como 20 para o protocolo NFS no IPspace padrão:

....
network qos-marking modify -ipspace Default -protocol NFS -dscp 20
....