---
sidebar: sidebar 
permalink: networking/remove_dynamic_routes_from_routing_tables.html 
keywords: dynamic, route, routes, icmp, ipv4, ipv6, routing, table, timeout, expire, expiry, performance, delete, deleting, remove, removing, remove dynamic routes to prevent a loss of connectivity when routes expire, remove dynamic routes from routing tables, network tuning icmp show, network tuning icmp6 show 
summary: Remova rotas dinâmicas para evitar a perda de conetividade quando as rotas expirarem 
---
= Remover rotas dinâmicas das tabelas de roteamento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Quando os redirecionamentos ICMP são recebidos para IPv4 e IPv6, as rotas dinâmicas são adicionadas à tabela de roteamento. Por padrão, as rotas dinâmicas são removidas após 300 segundos. Se você quiser manter rotas dinâmicas por um período de tempo diferente, você pode alterar o valor do tempo limite.

.Sobre esta tarefa
Você pode definir o valor de tempo limite de 0 a 65.535 segundos. Se você definir o valor como 0, as rotas nunca expiram. A remoção de rotas dinâmicas impede a perda de conetividade causada pela persistência de rotas inválidas.

.Passos
. Apresentar o valor atual do tempo limite.
+
** Para IPv4:
+
....
network tuning icmp show
....
** Para IPv6:
+
....
network tuning icmp6 show
....


. Modifique o valor de tempo limite.
+
** Para IPv4:
+
....
network tuning icmp modify -node node_name -redirect-timeout timeout_value
....
** Para IPv6:
+
....
network tuning icmp6 modify -node node_name -redirect-v6-timeout timeout_value
....


. Verifique se o valor de tempo limite foi modificado corretamente.
+
** Para IPv4:
+
....
network tuning icmp show
....
** Para IPv6:
+
....
network tuning icmp6 show
....



