---
sidebar: sidebar 
permalink: networking/set_up_nas_path_failover_9_to_97_cli.html 
keywords: 'set up nas path failover (ontap 9.0 - 9.7 cli), setup nas path failover, nas path failover, nas path failover workflow' 
summary: Bem-vindo ao fluxo de trabalho de failover de caminho nas ONTAP 9.0 - 9,7 
---
= Configurar failover de caminho nas (ONTAP 9 .7 e anterior)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Esse fluxo de trabalho orienta você pelas etapas de configuração de rede para configurar o failover de caminho nas para o ONTAP 9.0 - 9,7. Este fluxo de trabalho assume o seguinte:

* Você deseja usar as práticas recomendadas de failover de caminho nas que simplificam a configuração de rede.
* Você deseja usar a CLI, não o System Manager.
* Você está configurando a rede em um novo sistema executando o ONTAP 9.0 a 9,7.


Se você estiver executando uma versão do ONTAP posterior a 9,7, use o procedimento de failover de caminho nas para o ONTAP 9.8 ou posterior:

* xref:set_up_nas_path_failover_98_and_later_cli.adoc[Fluxo de trabalho de failover de caminho nas do ONTAP 9.8 e posterior]


Se você quiser detalhes sobre componentes e gerenciamento de rede, use o material de referência de gerenciamento de rede:

* xref:networking_reference.adoc[Visão geral do gerenciamento de rede]

