---
sidebar: sidebar 
permalink: networking/task_testing_snmp_polling.html 
keywords: configure, snmp, verify, poll, cluster, test, test snmp poll 
summary: Depois de configurar o SNMP, você deve verificar se você pode poll o cluster. 
---
= Verifique a polling SNMP em um cluster ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de configurar o SNMP, você deve verificar se você pode poll o cluster.

.Sobre esta tarefa
Para fazer polling de um cluster, você precisa usar um comando de terceiros, `snmpwalk` como o .

.Passos
. Envie um comando SNMP para poll o cluster a partir de um cluster diferente.
+
Para sistemas que executam o SNMPv1, use o comando CLI `snmpwalk -v version -c community_stringip_address_or_host_name system` para descobrir o conteúdo do MIB (Management Information base).

+
Neste exemplo, o endereço IP do LIF de gerenciamento de cluster que você está polling é 10.11.12.123. O comando exibe as informações solicitadas do MIB:

+
[listing]
----
C:\Windows\System32>snmpwalk -v 1 -c public 10.11.12.123 system

SNMPv1-MIB::sysDescr.0 = STRING: NetApp Release 8.3.0
            Cluster-Mode: Tue Apr 22 16:24:48 EDT 2014
SNMPv1-MIB::sysObjectID.0 = OID: SNMPv1-SMI::enterprises.789.2.5
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (162644448) 18 days, 19:47:24.48
SNMPv1-MIB::sysContact.0 = STRING:
SNMPv1-MIB::sysName.0 = STRING: systemname.testlabs.com
SNMPv1-MIB::sysLocation.0 = STRING: Floor 2 Row B Cab 2
SNMPv1-MIB::sysServices.0 = INTEGER: 72
----
+
Para sistemas que executam o SNMPv2c, use o comando CLI `snmpwalk -v version -c community_stringip_address_or_host_name system` para descobrir o conteúdo do MIB (Management Information base).

+
Neste exemplo, o endereço IP do LIF de gerenciamento de cluster que você está polling é 10.11.12.123. O comando exibe as informações solicitadas do MIB:

+
[listing]
----
C:\Windows\System32>snmpwalk -v 2c -c public 10.11.12.123 system

SNMPv2-MIB::sysDescr.0 = STRING: NetApp Release 8.3.0
            Cluster-Mode: Tue Apr 22 16:24:48 EDT 2014
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.789.2.5
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (162635772) 18 days, 19:45:57.72
SNMPv2-MIB::sysContact.0 = STRING:
SNMPv2-MIB::sysName.0 = STRING: systemname.testlabs.com
SNMPv2-MIB::sysLocation.0 = STRING: Floor 2 Row B Cab 2
SNMPv2-MIB::sysServices.0 = INTEGER: 72
----
+
Para sistemas que executam o SNMPv3, use o comando CLI `snmpwalk -v 3 -a MD5 or SHA -l authnopriv -u username -A passwordip_address_or_host_name system` para descobrir o conteúdo do MIB (Management Information base).

+
Neste exemplo, o endereço IP do LIF de gerenciamento de cluster que você está polling é 10.11.12.123. O comando exibe as informações solicitadas do MIB:

+
[listing]
----
C:\Windows\System32>snmpwalk -v 3 -a MD5 -l authnopriv -u snmpv3
       -A password123 10.11.12.123 system

SNMPv3-MIB::sysDescr.0 = STRING: NetApp Release 8.3.0
       Cluster-Mode: Tue Apr 22 16:24:48 EDT 2014
SNMPv3-MIB::sysObjectID.0 = OID: SNMPv3-SMI::enterprises.789.2.5
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (162666569) 18 days, 19:51:05.69
SNMPv3-MIB::sysContact.0 = STRING:
SNMPv3-MIB::sysName.0 = STRING: systemname.testlabs.com
SNMPv3-MIB::sysLocation.0 = STRING: Floor 2 Row B Cab 2
SNMPv3-MIB::sysServices.0 = INTEGER: 72
----

