---
sidebar: sidebar 
permalink: networking/worksheet_for_nas_path_failover_configuration_manual.html 
keywords: ipspace configuration, broadcast domain configuration, subnet configuration, SVM configuration, LIF configuration, DNS configuration, dynamic DNS configuration, worksheet for nas path failover configuration for ontap 9.8 and later, complete all sections of the worksheet before configuring nas path failover for ontap 9.7 and earlier, ipspace configuration, broadcast domain configuration, mtu, maximum transmission unit, mtu is 1500 mtu is 9000, subnet configuration, storage virtual machine configuration, svm configuration, lif configuration, dynamic dns configuration, dns configuration 
summary: Complete todas as seções da Planilha antes de configurar o failover de caminho nas para ONTAP 9.0 - 9,7 
---
= Planilha para a configuração de failover de caminho nas (ONTAP 9.7 e anterior)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você deve concluir todas as seções da Planilha antes de configurar o failover de caminho nas.



== Configuração IPspace

Você pode usar um espaço de IPspace para criar um espaço de endereço IP distinto para cada SVM em um cluster. Isso permite que os clientes em domínios de rede separados administrativamente acessem os dados do cluster ao usar endereços IP sobrepostos do mesmo intervalo de sub-rede de endereços IP.

|===


| Informações | Obrigatório? | Seus valores 


 a| 
Nome do IPspace

* O nome do IPspace.
* O nome deve ser exclusivo no cluster.

| Sim |  
|===


== Configuração do domínio de difusão

Um domínio de broadcast agrupa portas que pertencem à mesma rede de camada 2 e define a MTU para as portas do domínio de broadcast.

Os domínios de broadcast são atribuídos a um IPspace. Um IPspace pode conter um ou mais domínios de broadcast.


NOTE: A porta para a qual um LIF falha deve ser membro do grupo de failover para o LIF. Quando você cria um domínio de broadcast, o ONTAP cria automaticamente um grupo de failover com o mesmo nome. O grupo failover contém todas as portas atribuídas ao domínio de broadcast.

|===


| Informações | Obrigatório? | Seus valores 


 a| 
Nome do IPspace

* O espaço IPspace ao qual o domínio de broadcast é atribuído.
* O espaço IPspace deve existir.

| Sim |  


 a| 
Nome de domínio de broadcast

* O nome do domínio de difusão.
* Esse nome deve ser único no IPspace.

| Sim |  


 a| 
MTU

* A MTU do domínio de broadcast.
* Normalmente definido para *1500* ou *9000*.
* O valor MTU é aplicado a todas as portas no domínio de broadcast e a todas as portas que forem adicionadas posteriormente ao domínio de broadcast.



NOTE: O valor MTU deve corresponder a todos os dispositivos ligados a essa rede. Observe que o gerenciamento de gerenciamento de portas e0M e o tráfego do processador de serviços devem ter o MTU definido para não mais de 1500 bytes.
| Sim |  


 a| 
Portas

* As portas de rede a serem adicionadas ao domínio de broadcast.
* As portas atribuídas ao domínio de broadcast podem ser portas físicas, VLANs ou grupos de interface (ifgroups).
* Se uma porta estiver em outro domínio de broadcast, ela deve ser removida antes que ela possa ser adicionada ao domínio de broadcast.
* As portas são atribuídas especificando o nome do nó e a porta: Por exemplo, node1:e0d.

| Sim |  
|===


== Configuração de sub-rede

Uma sub-rede contém pools de endereços IP e um gateway padrão que pode ser atribuído a LIFs usados por SVMs residentes no IPspace.

* Ao criar um LIF em uma SVM, você pode especificar o nome da sub-rede em vez de fornecer um endereço IP e uma sub-rede.
* Como uma sub-rede pode ser configurada com um gateway padrão, você não precisa criar o gateway padrão em uma etapa separada ao criar um SVM.
* Um domínio de broadcast pode conter uma ou mais sub-redes. Você pode configurar LIFs SVM que estão em sub-redes diferentes associando mais de uma sub-rede ao domínio de broadcast do IPspace.
* Cada sub-rede deve conter endereços IP que não se sobreponham aos endereços IP atribuídos a outras sub-redes no mesmo espaço IPspace.
* Você pode atribuir endereços IP específicos a LIFs de dados do SVM e criar um gateway padrão para o SVM em vez de usar uma sub-rede.


|===


| Informações | Obrigatório? | Seus valores 


 a| 
Nome do IPspace

* O espaço IPspace ao qual a sub-rede será atribuída.
* O espaço IPspace deve existir.

| Sim |  


 a| 
Nome da sub-rede

* O nome da sub-rede.
* O nome deve ser único no IPspace.

| Sim |  


 a| 
Nome de domínio de broadcast

* O domínio de broadcast ao qual a sub-rede será atribuída.
* O domínio de broadcast deve residir no espaço IPspace especificado.

| Sim |  


 a| 
Nome e máscara da sub-rede

* A sub-rede e a máscara em que os endereços IP residem.

| Sim |  


 a| 
Gateway

* Você pode especificar um gateway padrão para a sub-rede.
* Se você não atribuir um gateway ao criar a sub-rede, poderá atribuir um à sub-rede a qualquer momento.

| Não |  


 a| 
Intervalos de endereços IP

* Você pode especificar um intervalo de endereços IP ou endereços IP específicos. Por exemplo, você pode especificar um intervalo como:
`192.168.1.1-192.168.1.100, 192.168.1.112, 192.168.1.145`
* Se você não especificar um intervalo de endereços IP, todo o intervalo de endereços IP na sub-rede especificada estará disponível para atribuir a LIFs.

| Não |  


 a| 
Forçar atualização de associações de LIF

* Especifica se deve-se forçar a atualização das associações de LIF existentes.
* Por padrão, a criação de sub-rede falhará se qualquer interface de processador de serviço ou interfaces de rede estiver usando os endereços IP nos intervalos fornecidos.
* O uso deste parâmetro associa quaisquer interfaces endereçadas manualmente à sub-rede e permite que o comando seja bem-sucedido.

| Não |  
|===


== Configuração SVM

Você usa SVMs para fornecer dados a clientes e hosts.

Os valores que você Registra são para criar um SVM de dados padrão. Se você estiver criando uma SVM de origem MetroCluster, consulte link:https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["Instale um MetroCluster conectado à malha"]ou link:https://docs.netapp.com/us-en/ontap-metrocluster/install-stretch/index.html["Instale um Stretch MetroCluster"].

|===


| Informações | Obrigatório? | Seus valores 


 a| 
Nome do SVM

* O nome do SVM.
* Você deve usar um nome de domínio totalmente qualificado (FQDN) para garantir nomes exclusivos de SVM em ligas de cluster.

| Sim |  


 a| 
Nome do volume raiz

* O nome do volume raiz do SVM.

| Sim |  


 a| 
Nome agregado

* O nome do agregado que contém o volume raiz da SVM.
* Este agregado deve existir.

| Sim |  


 a| 
Estilo de segurança

* O estilo de segurança do volume raiz da SVM.
* Os valores possíveis são *NTFS*, *unix* e *Mixed*.

| Sim |  


 a| 
Nome do IPspace

* O IPspace ao qual o SVM é atribuído.
* Este espaço IPspace tem de existir.

| Não |  


 a| 
Configuração de idioma SVM

* O idioma padrão a ser usado para o SVM e seus volumes.
* Se você não especificar um idioma padrão, o idioma SVM padrão será definido como *C.UTF-8*.
* A configuração de idioma SVM determina o conjunto de carateres usado para exibir nomes e dados de arquivos para todos os volumes nas no SVM. Você pode modificar o idioma após a criação do SVM.

| Não |  
|===


== Configuração LIF

Um SVM fornece dados a clientes e hosts por meio de uma ou mais interfaces lógicas de rede (LIFs).

|===


| Informações | Obrigatório? | Seus valores 


 a| 
Nome do SVM

* O nome do SVM para o LIF.

| Sim |  


 a| 
Nome LIF

* O nome do LIF.
* Você pode atribuir várias LIFs de dados por nó e pode atribuir LIFs a qualquer nó no cluster, desde que o nó tenha portas de dados disponíveis.
* Para fornecer redundância, você deve criar pelo menos duas LIFs de dados para cada sub-rede de dados e as LIFs atribuídas a uma sub-rede específica devem ser atribuídas portas residenciais em diferentes nós. *Importante:* se você estiver configurando um servidor SMB para hospedar Hyper-V ou SQL Server em SMB para soluções de operação sem interrupções, o SVM deve ter pelo menos um LIF de dados em cada nó no cluster.

| Sim |  


 a| 
Função do LIF

* O papel do LIF.
* Os LIFs de dados recebem a função de dados.

| Sim Decoreated from ONTAP 9.6 | dados 


| Política de serviço Política de serviço para o LIF. A política de serviço define quais serviços de rede podem usar o LIF. Serviços incorporados e políticas de serviço estão disponíveis para gerenciar dados e tráfego de gerenciamento em SVMs de dados e do sistema. | Sim começando com ONTAP 9.6 |  


 a| 
Protocolos permitidos

* Os protocolos que podem usar o LIF.
* Por padrão, SMB, NFS e FlexCache são permitidos. O protocolo FlexCache permite que um volume seja usado como um volume de origem para um volume FlexCache em um sistema executando o Data ONTAP operando no modo 7D.



NOTE: Os protocolos que usam o LIF não podem ser modificados após a criação do LIF. Você deve especificar todos os protocolos ao configurar o LIF.
| Não |  


 a| 
Nó inicial

* O nó para o qual o LIF retorna quando o LIF é revertido para sua porta inicial.
* Você deve gravar um nó inicial para cada LIF de dados.

| Sim |  


 a| 
Porta inicial ou domínio de broadcast

* A porta para a qual a interface lógica retorna quando o LIF é revertido para sua porta inicial.
* Você deve gravar uma porta inicial para cada LIF de dados.

| Sim |  


 a| 
Nome da sub-rede

* A sub-rede a atribuir ao SVM.
* Todas as LIFs de dados usadas para criar conexões SMB continuamente disponíveis para servidores de aplicativos devem estar na mesma sub-rede.

| Sim (se estiver usando uma sub-rede) |  
|===


== Configuração DNS

Você deve configurar o DNS na SVM antes de criar um servidor NFS ou SMB.

|===


| Informações | Obrigatório? | Seus valores 


 a| 
Nome do SVM

* O nome do SVM no qual você deseja criar um servidor NFS ou SMB.

| Sim |  


 a| 
Nome de domínio DNS

* Uma lista de nomes de domínio a anexar a um nome de host ao executar a resolução de nome de host para IP.
* Liste primeiro o domínio local, seguido pelos nomes de domínio para os quais as consultas DNS são mais frequentemente feitas.

| Sim |  


 a| 
Endereços IP dos servidores DNS

* Lista de endereços IP para os servidores DNS que fornecerão a resolução de nomes para o servidor NFS ou SMB.
* Os servidores DNS listados devem conter os Registros de localização de serviço (SRV) necessários para localizar os servidores LDAP do ative Directory e os controladores de domínio para o domínio em que o servidor SMB irá ingressar. O Registro SRV é usado para mapear o nome de um serviço para o nome de computador DNS de um servidor que oferece esse serviço. A criação do servidor SMB falhará se o ONTAP não conseguir obter os Registros de localização do serviço por meio de consultas DNS locais. A maneira mais simples de garantir que o ONTAP possa localizar os Registros SRV do ative Directory é configurar servidores DNS integrados ao ative Directory como servidores DNS SVM. Você pode usar servidores DNS não integrados ao ative Directory desde que o administrador DNS tenha adicionado manualmente os Registros SRV à zona DNS que contém informações sobre os controladores de domínio do ative Directory.
* Para obter informações sobre os Registros SRV integrados ao ative Directory, consulte o link:http://technet.microsoft.com/library/cc759550(WS.10).aspx["Como o suporte DNS para ative Directory funciona no Microsoft TechNet"^]tópico .

| Sim |  
|===


== Configuração de DNS dinâmico

Antes de poder utilizar o DNS dinâmico para adicionar automaticamente entradas de DNS aos servidores DNS integrados do ative Directory, tem de configurar o DNS dinâmico (DDNS) no SVM.

Registros DNS são criados para cada LIF de dados na SVM. Ao criar vários dados LIFS no SVM, você pode equilibrar as conexões de clientes com os endereços IP de dados atribuídos. A carga de DNS equilibra as conexões que são feitas usando o nome do host para os endereços IP atribuídos de forma redonda.

|===


| Informações | Obrigatório? | Seus valores 


 a| 
Nome do SVM

* SVM no qual você deseja criar um servidor NFS ou SMB.

| Sim |  


 a| 
Se deve usar DDNS

* Especifica se o DDNS deve ser usado.
* Os servidores DNS configurados no SVM devem oferecer suporte a DDNS. Por padrão, o DDNS está desativado.

| Sim |  


 a| 
Se usar DDNS seguro

* O DDNS seguro é suportado apenas com DNS integrado ao ative Directory.
* Se o DNS integrado ao ative Directory permitir apenas atualizações seguras de DDNS, o valor deste parâmetro deve ser verdadeiro.
* Por padrão, o DDNS seguro está desativado.
* O DDNS seguro só pode ser ativado depois de um servidor SMB ou uma conta do ative Directory ter sido criada para o SVM.

| Não |  


 a| 
FQDN do domínio DNS

* O FQDN do domínio DNS.
* Você deve usar o mesmo nome de domínio configurado para serviços de nome DNS na SVM.

| Não |  
|===