---
sidebar: sidebar 
permalink: multi-admin-verify/request-operation-task.html 
keywords: ontap, mav, multi, admin, multi admin verify, verification, administrator, protected, operation, rules, request, cluster, approve, rbac 
summary: 'Quando você inicia uma operação protegida em um cluster habilitado para verificação multi-admin (MAV), o ONTAP interceta automaticamente a operação e solicita a geração de uma solicitação, que deve ser aprovada por um ou mais administradores em um grupo de aprovação MAV (administradores MAV).' 
---
= Solicitar a execução de operações protegidas MAV em ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando você inicia uma operação ou comando protegidos em um cluster habilitado para verificação multi-admin (MAV), o ONTAP interceta automaticamente a operação e solicita a geração de uma solicitação, que deve ser aprovada por um ou mais administradores em um grupo de aprovação MAV (administradores MAV). Alternativamente, você pode criar uma solicitação MAV sem a caixa de diálogo.

Se aprovado, você deve responder à consulta para concluir a operação dentro do período de expiração da solicitação. Se vetado, ou se a solicitação ou os períodos de expiração forem excedidos, você deverá excluir a solicitação e reenviar.

A funcionalidade MAV homenageia as configurações RBAC existentes. Ou seja, sua função de administrador deve ter privilégio suficiente para executar uma operação protegida sem considerar as configurações de MAV. link:../authentication/create-svm-user-accounts-task.html["Saiba mais sobre o RBAC"].

Se você for um administrador do MAV, suas solicitações para executar operações protegidas também devem ser aprovadas por um administrador do MAV.



== Procedimento do System Manager

Quando um usuário clica em um item de menu para iniciar uma operação e a operação é protegida, uma solicitação de aprovação é gerada e o usuário recebe uma notificação semelhante à seguinte:

[listing]
----
Approval request to delete the volume was sent.
Track the request ID 356 from Events & Jobs > Multi-Admin Requests.
----
A janela *pedidos Multi-Admin* está disponível quando o MAV está ativado, mostrando solicitações pendentes com base no ID de login do usuário e na função MAV (aprovador ou não). Para cada solicitação pendente, os seguintes campos são exibidos:

* Operação
* Índice (número)
* Estado (pendente, aprovado, rejeitado, executado ou expirado)
+
Se uma solicitação for rejeitada por um aprovador, nenhuma outra ação será possível.

* Consulta (quaisquer parâmetros ou valores para a operação solicitada)
* Utilizador a solicitar
* A solicitação expira em
* (Número de) Aprovadores pendentes
* (Número de) potenciais Aprovadores


Quando a solicitação for aprovada, o usuário solicitante poderá tentar novamente a operação dentro do período de expiração.

Se o utilizador voltar a tentar a operação sem aprovação, é apresentada uma notificação semelhante à seguinte:

[listing]
----
Request to perform delete operation is pending approval.
Retry the operation after request is approved.
----


== Procedimento CLI

. Introduzir diretamente a operação protegida ou através do comando pedido MAV.
+
*Exemplos – para excluir um volume, digite um dos seguintes comandos:*

+
** `volume delete`
+
[listing]
----
cluster-1::*> volume delete -volume vol1 -vserver vs0

Warning: This operation requires multi-admin verification. To create a
         verification request use "security multi-admin-verify request
         create".

         Would you like to create a request for this operation?
          {y|n}: y

Error: command failed: The security multi-admin-verify request (index 3) is
       auto-generated and requires approval.
----
** `security multi-admin-verify request create "volume delete"`
+
[listing]
----
Error: command failed: The security multi-admin-verify request (index 3)
       requires approval.
----


. Verifique o status da solicitação e responda ao aviso MAV.
+
.. Se a solicitação for aprovada, responda à mensagem CLI para concluir a operação.
+
*Exemplo:*

+
[listing]
----
cluster-1::> security multi-admin-verify request show 3

     Request Index: 3
         Operation: volume delete
             Query: -vserver vs0 -volume vol1
             State: approved
Required Approvers: 1
 Pending Approvers: 0
   Approval Expiry: 2/25/2022 14:32:03
  Execution Expiry: 2/25/2022 14:35:36
         Approvals: admin2
       User Vetoed: -
           Vserver: cluster-1
    User Requested: admin
      Time Created: 2/25/2022 13:32:03
     Time Approved: 2/25/2022 13:35:36
           Comment: -
   Users Permitted: -

cluster-1::*> volume delete -volume vol1 -vserver vs0

Info: Volume "vol1" in Vserver "vs0" will be marked as deleted and placed in the volume recovery queue. The space used by the volume will be recovered only after the retention period of 12 hours has completed. To recover the space immediately, get the volume name using (privilege:advanced) "volume recovery-queue show vol1_*" and then "volume recovery-queue purge -vserver vs0 -volume <volume_name>" command. To recover the volume use the (privilege:advanced) "volume recovery-queue recover -vserver vs0       -volume <volume_name>" command.

Warning: Are you sure you want to delete volume "vol1" in Vserver "vs0" ?
{y|n}: y
----
.. Se a solicitação for vetada ou se o período de expiração tiver passado, exclua a solicitação e envie novamente ou entre em Contato com o administrador do MAV.
+
*Exemplo:*

+
[listing]
----
cluster-1::> security multi-admin-verify request show 3

     Request Index: 3
         Operation: volume delete
             Query: -vserver vs0 -volume vol1
             State: vetoed
Required Approvers: 1
 Pending Approvers: 1
   Approval Expiry: 2/25/2022 14:38:47
  Execution Expiry: -
         Approvals: -
       User Vetoed: admin2
           Vserver: cluster-1
    User Requested: admin
      Time Created: 2/25/2022 13:38:47
     Time Approved: -
           Comment: -
   Users Permitted: -

cluster-1::*> volume delete -volume vol1 -vserver vs0

Error: command failed: The security multi-admin-verify request (index 3) hasbeen vetoed. You must delete it and create a new verification request.
To delete, run "security multi-admin-verify request delete 3".
----



