---
permalink: concepts/builtin-storage-efficiency-concept.html 
sidebar: sidebar 
keywords: storage efficiency, built-in, platform, controller, offload 
summary: A partir do ONTAP 9.15,1, a eficiência de storage e a compactação de dados incorporadas e ativadas automaticamente estão nas plataformas AFF A70, AFF A90 e AFF A1K. 
---
= CPU ou eficiência de storage do processador de descarga dedicado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.15,1, o ONTAP oferece eficiência de storage e compactação de dados nas plataformas AFF A70, AFF A90 e AFF A1K. Dependendo da plataforma, a compactação é realizada usando a CPU principal ou com um processador de descarga dedicado. A eficiência de storage é ativada automaticamente e não requer configuração. A eficiência de storage é habilitada por padrão em volumes thin Provisioning recém-criados e é aplicada aos dados existentes, incluindo volumes movidos de outras plataformas para as plataformas AFF A70, AFF A90 ou AFF A1K.

A eficiência de storage sensível à temperatura não é aplicada nas plataformas AFF A70, AFF A90 e AFF A1K. A compactação não se baseia em dados ativos ou inativos nessas plataformas. Portanto, a compactação começa sem esperar que os dados fiquem inativos.

A eficiência de storage nas plataformas AFF A70, AFF A90 e AFF A1K usa a embalagem sequencial de blocos físicos contíguos para aprimorar ainda mais a eficiência de storage para dados compatados.

Os dados migrados para as plataformas AFF A70, AFF A90 ou AFF A1K com movimentação de volume ou tecnologia SnapMirror são convertidos automaticamente para compactação in-line de 32k TB. A eficiência de storage para dados migrados de uma plataforma AFF A70, A90 ou A1K para uma plataforma anterior é transformada automaticamente com base nos recursos de eficiência da plataforma de destino.

Para obter informações sobre como atualizar uma controladora para um AFF A70, AFF A90 ou AFF A1K, consulte https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["Documentação de atualização de hardware da ONTAP"^].
