---
permalink: concepts/builtin-storage-efficiency-concept.html 
sidebar: sidebar 
keywords: storage efficiency, built-in, platform, controller, offload 
summary: A partir do ONTAP 9.15,1, a eficiência de storage e a compactação de dados incorporadas e ativadas automaticamente estão nas plataformas AFF A70, AFF A90 e AFF A1K. 
---
= CPU ou eficiência de storage do processador de descarga dedicado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A eficiência de armazenamento da CPU ou do processador de offload dedicado é habilitada por padrão em determinadas plataformas AFF e FAS .  Essas plataformas não usam eficiência de armazenamento sensível à temperatura.  A compactação começa sem esperar que os dados esfriem e é realizada usando a CPU principal ou um processador de descarregamento dedicado.  Essas plataformas também usam empacotamento sequencial de blocos físicos contíguos para melhorar ainda mais a eficiência de armazenamento de dados compactados.

A eficiência de armazenamento da CPU ou do processador de descarregamento dedicado está disponível nas seguintes plataformas e versões ONTAP :

[cols="2"]
|===
| Plataforma | Versão de ONTAP 


 a| 
* AFF A1K
* AFF A90
* AFF A70
* FAS90
* FAS70

| 9.15.1 ou posterior 


 a| 
* AFF A50
* AFF A30

| 9.16.1 ou posterior 
|===

NOTE: Os dados migrados usando a tecnologia SnapMirror são convertidos automaticamente para compactação inline de 32k nas plataformas AFF A20.  Entretanto, a plataforma AFF A20 não oferece suporte à eficiência de armazenamento de CPU ou processador de offload dedicado.

Para as seguintes plataformas, a eficiência de armazenamento é ativada automaticamente e não requer configuração.  Isso se aplica a todos os volumes de provisionamento fino recém-criados e dados existentes, incluindo volumes movidos de outras plataformas.  A desduplicação é ativada independentemente da configuração de garantia de espaço.  Tanto a compactação quanto a compactação de dados exigem que a garantia de espaço seja definida como nenhuma.  Os dados migrados usando a tecnologia Volume Move ou SnapMirror são convertidos automaticamente para compactação inline de 32k.

* AFF A1K
* AFF A90
* AFF A70
* AFF A50
* AFF A30


Para as seguintes plataformas, a eficiência de armazenamento é habilitada por padrão somente em volumes de provisionamento fino existentes que tinham a eficiência de armazenamento habilitada antes da atualização para o ONTAP 9.15.1 ou posterior.  Você pode habilitar a eficiência de armazenamento em volumes recém-criados usando o método CLI ou REST API.  Os dados migrados usando a tecnologia Volume Move ou SnapMirror são convertidos para compactação inline de 32k somente se a compactação estiver habilitada na plataforma original.

* FAS90
* FAS70


Para obter informações sobre como atualizar um controlador para uma das plataformas suportadas, consulte o https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["Documentação de atualização de hardware da ONTAP"^] .
