---
permalink: concepts/cloud-backup-support-traditional-backups-concept.html 
sidebar: sidebar 
keywords: cloud backup, support, traditional backups 
summary: Além dos relacionamentos de proteção de dados do SnapMirror e do SnapVault, que eram disco a disco somente para o ONTAP 9.7 e anteriores, agora há várias soluções de backup que oferecem uma alternativa mais econômica para a retenção de dados a longo prazo. 
---
= Backup em nuvem e suporte para backups tradicionais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Além dos relacionamentos de proteção de dados do SnapMirror e do SnapVault, que eram disco a disco somente para o ONTAP 9.7 e anteriores, agora há várias soluções de backup que oferecem uma alternativa mais econômica para a retenção de dados a longo prazo.

Várias aplicações de proteção de dados de terceiros oferecem backup tradicional para dados gerenciados pela ONTAP. Veeam, Veritas e CommVault, entre outros, oferecem backup integrado para sistemas ONTAP.

A partir do ONTAP 9,8, a nuvem SnapMirror oferece replicação assíncrona de snapshots de instâncias do ONTAP para pontos de extremidade de storage de objetos. A replicação de nuvem do SnapMirror requer uma aplicação licenciada para orquestração e gerenciamento de workflows de proteção de dados. Os relacionamentos de nuvem da SnapMirror são compatíveis com sistemas ONTAP para selecionar destinos de storage de objetos no local e na nuvem pública, incluindo AWS S3, Google Cloud Storage Platform ou storage de Blobs do Microsoft Azure, o que fornece eficiência aprimorada com software de backup de fornecedor. Entre em Contato com seu representante da NetApp para obter uma lista de aplicativos certificados compatíveis e fornecedores de storage de objetos.

Se você estiver interessado em proteção de dados nativa da nuvem, o NetApp Console pode ser usado para configurar relacionamentos SnapMirror ou SnapVault entre volumes locais e instâncias do Cloud Volumes ONTAP na nuvem pública.

O Console também fornece backups de instâncias do Cloud Volumes ONTAP usando um modelo de Software como Serviço (SaaS).  Os usuários podem fazer backup de suas instâncias do Cloud Volumes ONTAP no S3 e no armazenamento de objetos em nuvem pública compatível com S3 usando o NetApp Backup and Recovery.

link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/index.html["Documentação do Cloud Volumes ONTAP"^]

link:https://docs.netapp.com/us-en/console-family/index.html["Documentação do NetApp Console"^]

link:https://console.netapp.com/["Console NetApp"^]
