---
permalink: concepts/fabricpool-concept.html 
sidebar: sidebar 
keywords: storagegrid, storage grid, fabricpool, cloud tier, local tier, aggregate 
summary: Muitos clientes da NetApp têm quantidades significativas de dados armazenados que raramente são acessados. Chamamos isso de dados inativos. Os clientes também têm dados que são acessados com frequência, os quais chamamos de dados ativos. Idealmente, você deseja manter seus dados ativos em seu storage mais rápido para obter a melhor performance. Os dados inativos podem se mover para um armazenamento mais lento, desde que estejam imediatamente disponíveis, se necessário. Mas como você sabe quais partes de seus dados estão quentes e quais são frios? 
---
= FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Muitos clientes da NetApp têm quantidades significativas de dados armazenados que raramente são acessados. Chamamos isso de _cold_ dados. Os clientes também têm dados que são acessados com frequência, que chamamos de _hot_ data. Idealmente, você deseja manter seus dados ativos em seu storage mais rápido para obter a melhor performance. Os dados inativos podem se mover para um armazenamento mais lento, desde que estejam imediatamente disponíveis, se necessário. Mas como você sabe quais partes de seus dados estão quentes e quais são frios?

O FabricPool é um recurso do ONTAP que move dados automaticamente entre uma categoria local de alta performance e uma categoria de nuvem com base em padrões de acesso. A disposição em categorias libera espaço no storage local caro para os dados ativos enquanto mantém os dados inativos prontamente disponíveis no storage de objetos de baixo custo na nuvem. O FabricPool monitora constantemente o acesso aos dados e migra os dados entre as camadas para melhor performance e máxima economia.

Usar o FabricPool para categorizar dados pouco acessados na nuvem é uma das maneiras mais fáceis de ganhar eficiência e criar uma configuração de nuvem híbrida. O FabricPool trabalha em nível de bloco de storage, portanto, trabalha com dados LUN e de arquivo.

Mas o FabricPool não se destina apenas a separar os dados no local para a nuvem. Muitos clientes usam o FabricPool em Cloud Volumes ONTAP para categorizar dados inativos de storage de nuvem mais caro para storage de objetos de baixo custo dentro do fornecedor de nuvem. A partir do ONTAP 9.8, é possível capturar análises em volumes habilitados para FabricPool com link:../concept_nas_file_system_analytics_overview.html["Análise do sistema de arquivos"] ou link:../volumes/enable-temperature-sensitive-efficiency-concept.html["eficiência de storage sensível à temperatura"].

As aplicações que usam os dados não sabem que eles estão dispostos em categorias, portanto, não são necessárias alterações nas aplicações. A disposição em camadas é totalmente automática, portanto, não é necessária administração contínua.

Você pode armazenar dados inativos no storage de objetos de um dos principais fornecedores de nuvem. Ou escolha a NetApp StorageGRID para manter seus dados inativos na sua própria nuvem privada, proporcionando a melhor performance e controle total sobre seus dados.

.Informações relacionadas
https://docs.netapp.com/us-en/ontap/concept_cloud_overview.html["Doc do Gestor de sistema FabricPool"^]

https://docs.netapp.com/us-en/data-services-cloud-tiering/index.html["Camadas de nuvem da NetApp"^]

https://www.youtube.com/playlist?list=PLdXI3bZJEw7mcD3RnEcdqZckqKkttoUpS["Lista de reprodução do FabricPool na NetApp TechComm TV"^]
