---
permalink: concepts/introducing-ontap-interfaces-concept.html 
sidebar: sidebar 
keywords: ontap interfaces, interfaces, system manager, bluexp, cli, rest api, ontapi 
summary: O software de gerenciamento de dados ONTAP oferece muitas interfaces que você pode usar para gerenciar seus dados protegidos pela ONTAP. 
---
= Interfaces de usuário do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O software de gerenciamento de dados ONTAP oferece várias interfaces que você pode usar para gerenciar clusters do ONTAP. Essas opções de interface oferecem diferentes níveis de acesso e funcionalidade, além de oferecer flexibilidade para gerenciar clusters do ONTAP, conforme apropriado, com base no ambiente.

Use qualquer uma dessas interfaces para administrar clusters do ONTAP e executar operações de gerenciamento de dados



== Gerente do sistema da ONTAP

O ONTAP System Manager é uma interface de usuário baseada na Web que oferece uma maneira simplificada e intuitiva de gerenciar seu cluster. É possível administrar operações comuns, como configuração de storage, proteção de dados e configuração e gerenciamento de rede. O System Manager também fornece insights e monitoramento de desempenho de cluster e risco para ajudar você a reagir a problemas do cluster e se antecipar aos problemas antes que eles ocorram. link:../concept_administration_overview.html["Saiba mais"].

A interface do ONTAP System Manager foi redesenhada no ONTAP 9.7 para proporcionar uma experiência de usuário mais simplificada e intuitiva. Os procedimentos neste site de documentação descrevem a interface do Gerenciador de sistema redesenhada, que continua a oferecer mais opções em cada versão do ONTAP.


NOTE: A interface mais antiga do Gerenciador de sistema é referida na documentação do ONTAP como o Gerenciador de sistema clássico. A última versão do ONTAP em que a interface do Gerenciador de sistema clássico está disponível é ONTAP 9.7.



== BlueXP

A partir do ONTAP 9.12,1, você pode usar a interface BlueXP  baseada na Web para gerenciar sua infraestrutura multicloud híbrida a partir de um único painel de controle, mantendo o já conhecido dashboard do System Manager. O BlueXP  permite que você crie e administre armazenamento em nuvem (por exemplo, Cloud Volumes ONTAP), use os serviços de dados do NetApp (por exemplo, backup em nuvem) e controle muitos dispositivos de armazenamento no local e na borda. A adição de sistemas ONTAP locais ao BlueXP  permite que você gerencie todos os ativos de storage e dados em uma única interface. https://docs.netapp.com/us-en/bluexp-family/["Saiba mais"^].



== Interface de linha de comando ONTAP

O link:../system-admin/index.html["Interface de linha de comando ONTAP (CLI)"] é uma interface baseada em texto que permite interagir com um cluster, nó, SVM e muito mais usando link:../concepts/manual-pages.html["comandos"]o . Os comandos CLI estão disponíveis com base link:../system-admin/cluster-svm-administrators-concept.html["tipo de função"]no . Você pode acessar a CLI do ONTAP por meio de SSH ou uma conexão de console a um nó no cluster.



== API REST do ONTAP

A partir do ONTAP 9.6, você pode acessar uma API RESTful que permite gerenciar e automatizar programaticamente as operações de cluster. Use a API para executar várias tarefas administrativas do ONTAP, como criar e gerenciar volumes, snapshots e agregados, além de monitorar a performance do cluster. Você pode acessar a API REST do ONTAP diretamente usando um utilitário como curl ou com qualquer linguagem de programação compatível com um CLIENTE REST, como Python, PowerShell e Java. https://docs.netapp.com/us-en/ontap-automation/get-started/ontap_automation_options.html["Saiba mais"^].


NOTE: ONTAPI é uma API ONTAP proprietária que precede a API REST do ONTAP. A interface ONTAPI será desativada em versões futuras do ONTAP. Se você estiver usando o ONTAPI, você deve Planejar o https://docs.netapp.com/us-en/ontap-automation/migrate/ontapi_disablement.html["Migração para a API REST do ONTAP"^].



== Kits de ferramentas e frameworks NetApp

O NetApp fornece kits de ferramentas de cliente para linguagens e ambientes de desenvolvimento específicos que abstraem a API REST do ONTAP e facilitam a criação de código de automação. https://docs.netapp.com/us-en/ontap-automation/get-started/ontap_automation_options.html#client-software-toolkits["Saiba mais"^].

Além desses kits de ferramentas, você pode criar e implantar código de automação usando frameworks. https://docs.netapp.com/us-en/ontap-automation/get-started/ontap_automation_options.html#automation-frameworks["Saiba mais"^].
