---
permalink: concepts/manual-pages.html 
sidebar: sidebar 
keywords: CLI commands, manual pages, volume create, volume modify, volume show, volume move, snapmirror show, snapmirror create, vserver create, network interface show, storage disk show, volume delete, man pages, cli comparison tool, cli diff 
summary: As páginas do manual do ONTAP explicam como usar os comandos do ONTAP CLI. Encontre a referência de comando para a versão do ONTAP que você está usando. 
---
= Referência do comando ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para cada versão principal do ONTAP , os comandos CLI comumente disponíveis (páginas de manual do ONTAP ou páginas de manual) são agrupados no link:https://docs.netapp.com/us-en/ontap-cli/["Referência de comando ONTAP"^] . Estas referências de comando explicam como usar os comandos CLI em cada versão do ONTAP .

As páginas de manual também estão disponíveis na linha de comando do ONTAP com o  `man` comando. Saiba mais sobre  `man` no link:https://docs.netapp.com/us-en/ontap-cli/man.html["Referência do comando ONTAP"^] .



== Referências de comandos para versões de suporte limitado do ONTAP (apenas PDF)

* link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2843631["ONTAP 9,4"^]




== Ferramenta de comparação CLI

Você pode aprender sobre alterações nos comandos da interface de linha de comando (CLI) entre as versões do ONTAP usando o link:https://mysupport.netapp.com/site/info/cli-comparison["Ferramenta de comparação CLI"^] no site de suporte da NetApp.

.Informações relacionadas
* xref:../system-admin/command-line-interface-concept.html[Use a interface de linha de comando ONTAP]
* xref:../system-admin/methods-navigating-cli-command-directories-concept.html[Métodos de navegação de diretórios de comando CLI]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-show.html["exibição do disco de armazenamento"^]

