---
permalink: concepts/rdma-concept.html 
sidebar: sidebar 
keywords: Remote Direct Memory Access, NFS over RDMA, RoCE, intercluster 
summary: 'As ofertas de acesso remoto à memória direta (RDMA) da ONTAP são compatíveis com cargas de trabalho sensíveis à latência e de alta largura de banda. O RDMA permite que os dados sejam copiados diretamente entre a memória do sistema de armazenamento e a memória do sistema host, contornando as interrupções da CPU e a sobrecarga' 
---
= Visão geral da RDMA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As ofertas de acesso remoto à memória direta (RDMA) da ONTAP são compatíveis com cargas de trabalho sensíveis à latência e de alta largura de banda. O RDMA permite que os dados sejam copiados diretamente entre a memória do sistema de armazenamento e a memória do sistema host, contornando as interrupções da CPU e a sobrecarga.



== NFS sobre RDMA

A partir do ONTAP 9.10,1, você pode configurar link:../nfs-rdma/index.html["NFS sobre RDMA"] para habilitar o uso do armazenamento GPUDirect do NVIDIA para cargas de trabalho aceleradas por GPU em hosts com GPUs NVIDIA compatíveis.



== Interconexão de cluster RDMA

O RDMA de interconexão de cluster reduz a latência, diminui os tempos de failover e acelera a comunicação entre nós em um cluster.

A partir do ONTAP 9.10,1, o RDMA de interconexão de cluster é suportado para determinados sistemas de hardware quando usado com placas de rede de cluster X1151A. A partir do ONTAP 9.13,1, as placas de rede X91153A também suportam RDMA de interconexão de cluster. Consulte a tabela para saber quais sistemas são suportados em diferentes versões do ONTAP.

|===
| Sistemas | Versões de ONTAP compatíveis 


 a| 
* AFF A50
* AFF A30
* AFF A20
* AFF C80
* AFF C60
* AFF C30
* ASA A50
* ASA A30
* ASA A20

| ONTAP 9.16,1 e posterior 


 a| 
* AFF A1K
* AFF A90
* AFF A70
* ASA A1K
* ASA A90
* ASA A70
* FAS90
* FAS70

| ONTAP 9.15,1 e posterior 


 a| 
* AFF A400
* ASA A400

| ONTAP 9.10,1 e posterior 


 a| 
* AFF A900
* ASA A900
* FAS9500

| ONTAP 9.13,1 e posterior 
|===
Dada a configuração apropriada do sistema de armazenamento, nenhuma configuração adicional é necessária para usar RDMA de interconexão de cluster.
