---
sidebar: sidebar 
permalink: concepts/sysmgr-integration-bluexp-concept.html 
keywords: netapp, ontap, system manager, experience, integrate, integration, bluexp, hybrid, cloud, dashboard, multicloud 
summary: A partir do ONTAP 9.12,1, o Gerenciador de sistema é totalmente integrado ao BlueXP . Com o BlueXP , você pode gerenciar sua infraestrutura multicloud híbrida a partir de um único painel de controle enquanto mantém o já conhecido painel do System Manager. 
---
= Integração do System Manager com o BlueXP 
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.12,1, o Gerenciador de sistema é totalmente integrado ao BlueXP . Com o BlueXP , você pode gerenciar sua infraestrutura multicloud híbrida a partir de um único painel de controle enquanto mantém o já conhecido painel do System Manager.

O BlueXP  permite que você crie e administre armazenamento em nuvem (por exemplo, Cloud Volumes ONTAP), use os serviços de dados do NetApp (por exemplo, backup em nuvem) e controle muitos dispositivos de armazenamento no local e na borda.

Para usar o Gerenciador de sistema no BlueXP , execute as seguintes etapas:

.Passos
. Abra um navegador da Web e insira o endereço IP da interface de rede de gerenciamento de cluster.
+
Se o cluster tiver conetividade com o BlueXP , será exibido um prompt de login.

. Clique em *Continue to BlueXP * para seguir o link para BlueXP .
+

NOTE: Se as configurações do sistema bloquearam redes externas, você não poderá acessar o BlueXP . Para acessar o Gerenciador de sistema usando o BlueXP , você deve garantir que o endereço "'cloudmanager.cloud.NetApp.com'" possa ser acessado pelo seu sistema. Caso contrário, no prompt, você pode optar por usar a versão do Gerenciador de sistema que está instalada com seu sistema ONTAP.

. Na página de login do BlueXP , selecione *Faça login com suas credenciais do site de suporte da NetApp* e insira suas credenciais.
+
Se você já usou o BlueXP  e tem um login usando um e-mail e senha, então você precisará continuar usando essa opção de login.

+
https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-logging-in.html["Saiba mais sobre como fazer login no BlueXP "^].

. Se você for solicitado, insira um nome para sua nova conta do BlueXP .
+
Na maioria dos casos, o BlueXP  cria automaticamente uma conta para você com base nos dados do cluster.

. Insira as credenciais de administrador do cluster para o cluster.


.Resultado
O Gerenciador do sistema é exibido e agora você pode gerenciar o cluster a partir do BlueXP .



== Descubra seus clusters diretamente do BlueXP 

O BlueXP  oferece duas maneiras de descobrir e gerenciar clusters:

* Descoberta direta para gerenciamento por meio do System Manager
+
Esta é a mesma opção de descoberta descrita na seção anterior com a qual você segue o redirecionamento.

* Descoberta através de um conetor
+
O Connector é um software instalado no seu ambiente que permite acessar funções de gerenciamento por meio do System Manager e também acessar serviços de nuvem da BlueXP  que fornecem recursos como replicação de dados, backup e recuperação, classificação de dados, disposição em categorias de dados e muito mais.



Vá para a https://docs.netapp.com/us-en/cloud-manager-family/index.html["Documentação do BlueXP"^] para saber mais sobre essas opções de descoberta e gerenciamento.



== Saiba mais sobre o BlueXP 

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["Visão geral do BlueXP "^]
* https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/index.html["Gerencie seus sistemas NetApp AFF e FAS por meio do BlueXP "^]

