---
permalink: concepts/thin-provisioning-concept.html 
sidebar: sidebar 
keywords: thin provision 
summary: Um volume ou LUN com thin Provisioning é aquele para o qual o storage não é reservado com antecedência. Em vez disso, o storage é alocado dinamicamente, conforme necessário. O espaço livre é liberado de volta ao sistema de armazenamento quando os dados no volume ou LUN são excluídos. 
---
= Thin Provisioning
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A ONTAP oferece uma ampla variedade de tecnologias de eficiência de storage, além das cópias Snapshot. As principais tecnologias incluem thin Provisioning, deduplicação, compactação e volumes, arquivos e LUNs do FlexClone. Assim como as cópias Snapshot, todas são criadas no WAFL (Write Anywhere File Layout) do ONTAP.

Um volume ou LUN _thin-provisionado_ é aquele para o qual o armazenamento não é reservado com antecedência. Em vez disso, o storage é alocado dinamicamente, conforme necessário. O espaço livre é liberado de volta ao sistema de armazenamento quando os dados no volume ou LUN são excluídos.

Suponha que sua organização precisa fornecer aos usuários do 5.000 o armazenamento para diretórios base. Você estima que os maiores diretórios base consumirão 1 GB de espaço.

Nesta situação, você pode comprar 5 TB de armazenamento físico. Para cada volume que armazena um diretório home, você reservaria espaço suficiente para satisfazer as necessidades dos maiores consumidores.

No entanto, como uma questão prática, você também sabe que os requisitos de capacidade do diretório base variam muito em toda a sua comunidade. Para cada grande usuário de armazenamento, há dez que consomem pouco ou nenhum espaço.

O thin Provisioning permite que você atenda às necessidades dos grandes consumidores de storage sem ter que comprar storage que você talvez nunca use. Como o espaço de armazenamento não é alocado até ser consumido, você pode "'comprometer'" um agregado de 2 TB, atribuindo nominalmente um tamanho de 1 GB a cada um dos 5.000 volumes que o agregado contém.

Contanto que você esteja correto que haja uma proporção de 10:1 de usuários leves para pesados, e contanto que você assuma um papel ativo no monitoramento de espaço livre no agregado, você pode ter certeza de que as gravações de volume não falharão devido à falta de espaço.
