---
permalink: nfs-rdma/configure-nfs-task.html 
sidebar: sidebar 
keywords: networking, NFS over RDMA, NVIDIA, NFS, v4 grace period 
summary: este artigo explica uma etapa opcional para otimizar o desempenho do NFS sobre RDMA. 
---
= Modificar a configuração NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Na maioria dos casos, você não precisa modificar a configuração da VM de storage habilitada por NFS para NFS em RDMA.

Se você está, no entanto, lidando com problemas relacionados a chips de Mellanox e migração de LIF, você deve aumentar o período de graça de bloqueio de NFSv4. Por padrão, o período de carência é definido como 45 segundos. A partir de ONTAP 9.10,1, o período de carência tem um valor máximo de 180 (segundos).

.Passos
. Defina o nível de privilégio como avançado:
+
`set -privilege advanced`

. Introduza o seguinte comando:
+
`vserver nfs modify -vserver _SVM_name_ -v4-grace-seconds _number_of_seconds_`



Para obter mais informações sobre esta tarefa, xref:../nfs-admin/specify-nfsv4-locking-grace-period-task.adoc[Especifique o período de tolerância de bloqueio NFSv4]consulte .
