---
permalink: pnfs/pnfs-overview.html 
sidebar: sidebar 
keywords: tr-4063, technical report, pnfs, parallel nfs, nfsv4.1, nfsv4.2, performance, metadata, data path 
summary: 'O NFS paralelo (pNFS) melhora o desempenho ao permitir que os clientes NFS executem operações de leitura/gravação em dispositivos de armazenamento diretamente e em paralelo, evitando o servidor NFS como um possível gargalo.' 
---
= Saiba mais sobre NFS paralelo (pNFS) no ONTAP.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O NFS paralelo foi introduzido como um padrão RFC em janeiro de 2010, sob o RFC-5661, para permitir que os clientes acessem diretamente os dados de arquivos em servidores NFSv4.1, separando os caminhos de metadados e de dados. Esse acesso direto oferece benefícios de desempenho por meio da localização de dados, eficiência da CPU e paralelização de operações. Uma RFC posterior foi elaborada em 2018, abrangendo os tipos de layout pNFS (RFC-8434), que define padrões para layouts de arquivos, blocos e objetos. O ONTAP utiliza o tipo de layout de arquivo para operações pNFS.


NOTE: A partir de julho de 2024, o conteúdo de relatórios técnicos publicados anteriormente como PDFs foi integrado à documentação do produto ONTAP . A documentação de gerenciamento de armazenamento NFS do ONTAP agora inclui conteúdo do _TR-4063: Sistema de Arquivos de Rede Paralelo (pNFS) no NetApp ONTAP_.

Durante anos, o NFSv3 foi a versão padrão do protocolo NFS, utilizada em praticamente todos os casos de uso. No entanto, o protocolo apresentava limitações, como a falta de capacidade de manter estado, um modelo de permissões rudimentar e recursos básicos de bloqueio. O NFSv4.0 (RFC 7530) introduziu uma série de melhorias em relação ao NFSv3 e foi ainda mais aprimorado com as versões subsequentes NFSv4.1 (RFC 5661) e NFSv4.2 (RFC 7862), que adicionaram recursos como o NFS paralelo (pNFS).



== Benefícios do NFSv4.x

O NFSv4.x oferece as seguintes vantagens em relação ao NFSv3:

* Compatível com firewalls, pois o NFSv4 utiliza apenas uma única porta (2049) para suas operações.
* Gerenciamento de cache avançado e agressivo, como delegações no NFSv4.x
* Opções robustas de segurança RPC que empregam criptografia
* Internacionalização de caracteres
* Operações compostas
* Funciona apenas com TCP
* Protocolo com estado (não sem estado como o NFSv3)
* Integração completa do Kerberos para mecanismos de autenticação eficientes
* Encaminhamentos NFS
* Suporte para controle de acesso compatível com UNIX e Windows.
* Identificadores de usuário e grupo baseados em strings
* pNFS (NFSv4.1)
* Atributos estendidos (NFSv4.2)
* Etiquetas de segurança (NFSv4.2)
* Operações de arquivo esparsas (FALLOCATE) (NFSv4.2)


Para obter mais informações sobre o NFSv4.x em geral, incluindo as melhores práticas e detalhes sobre os recursos, consulte https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["Relatório técnico da NetApp 4067: Guia de práticas recomendadas e implementação de NFS"^].

.Informações relacionadas
* link:../nfs-config/index.html["Visão geral da configuração NFS"]
* link:../nfs-admin/index.html["Visão geral do gerenciamento do NFS"]
* link:../flexgroup/index.html["Gerenciamento de volumes do FlexGroup"]
* link:../nfs-trunking/index.html["Visão geral do trunking NFS"]
* https://www.netapp.com/pdf.html?item=/media/19370-tr-4523.pdf[]
* link:https://www.netapp.com/pdf.html?item=/media/19384-tr-4616.pdf["Relatório técnico do NetApp 4616: Kerberos NFS no ONTAP com o Microsoft ative Directory"^]

