---
permalink: pnfs/pnfs-commands.html 
sidebar: sidebar 
keywords: tr-4063, pnfs, commands, technical report 
summary: Utilize estes comandos da CLI do ONTAP para configurar, solucionar problemas e coletar estatísticas do pNFS. 
---
= Comandos pNFS, estatísticas e registros de eventos
:allow-uri-read: 


[role="lead"]
Esses comandos da CLI do ONTAP referem-se especificamente ao pNFS. Você pode usá-los para configurar, solucionar problemas e coletar estatísticas.



== Ativar NFSv4.1

[listing]
----
nfs modify -vserver SVM -v4.1 enabled
----


== Ativar pNFS

[listing]
----
nfs modify -vserver SVM -v4.1-pnfs enabled
----


== Exibir dispositivos pNFS (privilégios avançados)

[listing]
----
pnfs devices show -vserver SVM
----
[listing]
----
Vserver Name     Mapping ID      Volume MSID     Mapping Status  Generation
---------------  --------------- --------------- --------------- -------------
SVM              17              2157024470      notavailable    2
SVM              18              2157024463      notavailable    2
SVM              19              2157024469      available       3
SVM              20              2157024465      available       4
SVM              21              2157024467      available       3
SVM              22              2157024462      available       1
----


== Exibir mapeamentos de dispositivos pNFS (privilégios avançados)

[listing]
----
pnfs devices mappings show -vserver SVM
----
[listing]
----
Vserver Name    Mapping ID      Dsid            LIF IP
--------------  --------------- --------------- --------------------
SVM             19              2449            10.x.x.x
SVM             20              2512            10.x.x.y
SVM             21              2447            10.x.x.x
SVM             22              2442            10.x.x.y
----


== Capturar contadores de desempenho específicos do pNFS (privilégios avançados)

[listing]
----
statistics start -object nfsv4_1 -vserver SVM -sample-id [optional-name]
----


== Visualizar contadores de desempenho específicos do pNFS (privilégios avançados)

[listing]
----
statistics show -object nfsv4_1 -vserver SVM
----


== Veja a lista de contadores específicos do pNFS (privilégios avançados)

[listing]
----
statistics catalog counter show -object nfsv4_1 -counter *layout*|*device*
----
[listing]
----
Object: nfsv4_1

Counter                     Description
--------------------------- ----------------------------------------------
getdeviceinfo_avg_latency   Average latency of NFSv4.1 GETDEVICEINFO operations.
getdeviceinfo_error         The number of failed NFSv4.1 GETDEVICEINFO operations.
getdeviceinfo_percent       Percentage of NFSv4.1 GETDEVICEINFO operations.
getdeviceinfo_success       The number of successful NFSv4.1 GETDEVICEINFO operations.
getdeviceinfo_total         Total number of NFSv4.1 GETDEVICEINFO operations.
getdevicelist_avg_latency   Average latency of NFSv4.1 GETDEVICELIST operations.
getdevicelist_error         The number of failed NFSv4.1 GETDEVICELIST operations.
getdevicelist_percent       Percentage of NFSv4.1 GETDEVICELIST operations.
getdevicelist_success       The number of successful NFSv4.1 GETDEVICELIST operations.
getdevicelist_total         Total number of NFSv4.1 GETDEVICELIST operations.
layoutcommit_avg_latency    Average latency of NFSv4.1 LAYOUTCOMMIT operations.
layoutcommit_error          The number of failed NFSv4.1 LAYOUTCOMMIT operations.
layoutcommit_percent        Percentage of NFSv4.1 LAYOUTCOMMIT operations.
layoutcommit_success        The number of successful NFSv4.1 LAYOUTCOMMIT operations.
layoutcommit_total          Total number of NFSv4.1 LAYOUTCOMMIT operations.
layoutget_avg_latency       Average latency of NFSv4.1 LAYOUTGET operations.
layoutget_error             The number of failed NFSv4.1 LAYOUTGET operations.
layoutget_percent           Percentage of NFSv4.1 LAYOUTGET operations.
layoutget_success           The number of successful NFSv4.1 LAYOUTGET operations.
layoutget_total             Total number of NFSv4.1 LAYOUTGET operations.
layoutreturn_avg_latency    Average latency of NFSv4.1 LAYOUTRETURN operations.
layoutreturn_error          The number of failed NFSv4.1 LAYOUTRETURN operations.
layoutreturn_percent        Percentage of NFSv4.1 LAYOUTRETURN operations.
layoutreturn_success        The number of successful NFSv4.1 LAYOUTRETURN operations.
layoutreturn_total          Total number of NFSv4.1 LAYOUTRETURN operations.
----


== Visualizar conexões de rede ativas para NFS

Você pode verificar se várias conexões TCP estão sendo feitas com a SVM usando o `network connections active show` comando.

Por exemplo, se você quiser visualizar os troncos de sessão NFS, procure por conexões dos mesmos clientes em diferentes interfaces por nó:

[listing]
----
cluster::*> network connections active show -node cluster-0* -vserver PNFS
              Vserver   Interface         Remote
      CID Ctx Name      Name:Local Port   Host:Port            Protocol/Service
--------- --- --------- ----------------- -------------------- ----------------
Node: node-01
2304333128 14 PNFS      data1:2049        ubuntu22-224:740     TCP/nfs
2304333144 10 PNFS      data3:2049        ubuntu22-224:864     TCP/nfs
2304333151  5 PNFS      data1:2049        ubuntu22-226:848     TCP/nfs
2304333167 15 PNFS      data3:2049        ubuntu22-226:684     TCP/nfs
Node: node-02
2497668321 12 PNFS      data2:2049        ubuntu22-224:963     TCP/nfs
2497668337 18 PNFS      data4:2049        ubuntu22-224:859     TCP/nfs
2497668344 14 PNFS      data2:2049        ubuntu22-226:675     TCP/nfs
2497668360  7 PNFS      data4:2049        ubuntu22-226:903     TCP/nfs
----


== Exibir informações da versão NFS para clientes conectados

Você também pode visualizar conexões NFS com o `nfs connected-clients show` comando. Lembre-se de que a lista de clientes exibida inclui aqueles que tiveram tráfego NFS ativo nas últimas 48 horas. Clientes NFS ociosos (mesmo que ainda estejam montados) podem não aparecer até que o ponto de montagem seja acessado. Você pode filtrar esses resultados para exibir apenas os clientes acessados mais recentemente, especificando o `-idle-time` recurso.

Por exemplo, para visualizar os clientes com atividade nos últimos 10 minutos para o pNFS SVM:

[listing]
----
cluster::*> nfs connected-clients show -vserver PNFS -idle-time <10m>

 Node: node-01

Vserver: PNFS Data-Ip: 10.x.x.x Local Remote Client-Ip Protocol Volume Policy Idle-Time Reqs Reqs Trunking

10.x.x.a nfs4.2 PNFS_root default 9m 10s 0 149 false 10.x.x.a nfs4.2 FG_0001 default 9m 10s 135847 0 false 10.x.x.b nfs4.2 PNFS_root default 8m 12s 0 157 false 10.x.x.b nfs4.2 FG_0001 default 8m 12s 52111 0 false
----
.Informações relacionadas
* link:pnfs-overview.html["Saiba mais sobre NFS paralelo (pNFS) no ONTAP."]

