---
permalink: error-messages/index.html 
sidebar: sidebar 
keywords: ems, configuration, event, management, system, events, notifications 
summary: 'Você pode configurar rapidamente o ONTAP para enviar notificações importantes de eventos do EMS (sistema de Gerenciamento de Eventos) diretamente para um endereço de e-mail, um servidor syslog ou um traphost de protocolo de rede de Gerenciamento simples (SNMP) para que você seja notificado imediatamente sobre problemas do sistema que exigem atenção imediata.' 
---
= Visão geral da configuração EMS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar o ONTAP 9 para enviar notificações de eventos importantes do EMS (sistema de gerenciamento de eventos) diretamente para um endereço de e-mail, servidor syslog, traphost de protocolo de rede de gerenciamento simples (SNMP) ou aplicativo webhook para que você seja imediatamente notificado sobre problemas do sistema que exigem atenção imediata.

Como as notificações de eventos importantes não estão habilitadas por padrão, você precisa configurar o EMS para enviar notificações para um endereço de e-mail, um servidor syslog, um traphost SNMP ou um aplicativo webhook.

Reveja as versões específicas da versão do link:https://docs.netapp.com/us-en/ontap-ems-9131/["Referência EMS da ONTAP 9"^].

Se o mapeamento de eventos do EMS usar conjuntos de comandos ONTAP obsoletos (como destino de eventos, rota de eventos), é recomendável atualizar o mapeamento. link:../error-messages/convert-ems-routing-to-notifications-task.html["Saiba como atualizar seu mapeamento EMS a partir de comandos ONTAP obsoletos"].
