---
permalink: nfs-admin/break-locks-task.html 
sidebar: sidebar 
keywords: breaking, locks 
summary: Quando os bloqueios de arquivos estão impedindo o acesso do cliente aos arquivos, você pode exibir informações sobre os bloqueios atualmente mantidos e, em seguida, quebrar bloqueios específicos. Exemplos de cenários em que você pode precisar quebrar bloqueios incluem depuração de aplicativos. 
---
= Travas de quebra
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando os bloqueios de arquivos estão impedindo o acesso do cliente aos arquivos, você pode exibir informações sobre os bloqueios atualmente mantidos e, em seguida, quebrar bloqueios específicos. Exemplos de cenários em que você pode precisar quebrar bloqueios incluem depuração de aplicativos.

.Sobre esta tarefa
O `vserver locks break` comando está disponível apenas no nível de privilégio avançado e superior. A página de manual do comando contém informações detalhadas.

.Passos
. Para encontrar as informações que você precisa para quebrar um bloqueio, use o `vserver locks show` comando.
+
A página de manual do comando contém informações detalhadas.

. Defina o nível de privilégio como avançado:
+
`set -privilege advanced`

. Execute uma das seguintes ações:
+
[cols="35,65"]
|===


| Se você quiser quebrar um bloqueio especificando... | Digite o comando... 


 a| 
O nome do SVM, o nome do volume, o nome LIF e o caminho do arquivo
 a| 
`vserver locks break -vserver vserver_name -volume volume_name -path path -lif lif`



 a| 
A ID de bloqueio
 a| 
`vserver locks break -lockid UUID`

|===
. Voltar ao nível de privilégio de administrador:
+
`set -privilege admin`


