---
permalink: nfs-admin/commands-manage-name-service-switch-entries-reference.html 
sidebar: sidebar 
keywords: command, manage, name, service, switch, entry 
summary: Você pode gerenciar entradas de switch de serviço de nomes criando, exibindo, modificando e excluindo-as. 
---
= Comandos para gerenciar entradas de switch de serviço de nomes no ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode gerenciar entradas de switch de serviço de nomes criando, exibindo, modificando e excluindo-as.

[cols="35,65"]
|===


| Se você quiser... | Use este comando... 


 a| 
Crie uma entrada de switch de serviço de nomes
 a| 
`vserver services name-service ns-switch create`



 a| 
Exibir entradas do switch de serviço de nomes
 a| 
`vserver services name-service ns-switch show`



 a| 
Modificar uma entrada de switch de serviço de nomes
 a| 
`vserver services name-service ns-switch modify`



 a| 
Excluir uma entrada de switch de serviço de nomes
 a| 
`vserver services name-service ns-switch delete`

|===
Saiba mais sobre `vserver services name-service ns-switch` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+services+name-service+ns-switch["Referência do comando ONTAP"^]na .

.Informações relacionadas
https://www.netapp.com/pdf.html?item=/media/16328-tr-4668pdf.pdf["Relatório técnico da NetApp 4668: Guia de práticas recomendadas para serviços de nomes"^]
