---
permalink: nfs-admin/configure-time-to-live-cached-user-credentials-task.html 
sidebar: sidebar 
keywords: configure, time, live, cache, nfs, user, credential 
summary: 'Você pode configurar o período de tempo que o ONTAP armazena credenciais para usuários NFS em seu cache interno (time-to-live ou TTL) modificando o servidor NFS da máquina virtual de armazenamento (SVM). Isso permite que você solucione certos problemas relacionados à alta carga nos servidores de nomes ou alterações nas credenciais que afetam o acesso do usuário NFS.' 
---
= Configurar o tempo de vida para credenciais de usuário NFS armazenadas em cache para SVMs ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar o período de tempo que o ONTAP armazena credenciais para usuários NFS em seu cache interno (time-to-live ou TTL) modificando o servidor NFS da máquina virtual de armazenamento (SVM). Isso permite que você solucione certos problemas relacionados à alta carga nos servidores de nomes ou alterações nas credenciais que afetam o acesso do usuário NFS.

.Sobre esta tarefa
Estes parâmetros estão disponíveis no nível de privilégio avançado.

.Passos
. Defina o nível de privilégio como avançado:
+
`set -privilege advanced`

. Execute a ação desejada:
+
[cols="35,65"]
|===


| Se você quiser modificar o TTL para cache... | Use o comando... 


 a| 
Credenciais positivas
 a| 
`vserver nfs modify -vserver vserver_name -cached-cred-positive-ttl time_to_live`

O TTL é medido em milissegundos. A partir do ONTAP 9.10.1 e posterior, o padrão é de 1 hora (3.600.000 milissegundos). No ONTAP 9.9,1 e anterior, o padrão é 24 horas (86.400.000 milissegundos). O intervalo permitido para este valor é de 1 minuto (60000 milissegundos) a 7 dias (604.800.000 milissegundos).



 a| 
Credenciais negativas
 a| 
`vserver nfs modify -vserver vserver_name -cached-cred-negative-ttl time_to_live`

O TTL é medido em milissegundos. O padrão é 2 horas (7.200.000 milissegundos). O intervalo permitido para este valor é de 1 minuto (60000 milissegundos) a 7 dias (604.800.000 milissegundos).

|===
. Voltar ao nível de privilégio de administrador:
+
`set -privilege admin`


