---
permalink: nfs-admin/configure-security-styles-task.html 
sidebar: sidebar 
keywords: configure, security, style, flexvol, volume 
summary: 'Você configura o estilo de segurança do FlexVol volume para determinar o tipo de permissões usadas para dados nos volumes do FlexVol da máquina virtual de storage (SVM).' 
---
= Configurar estilos de segurança em volumes ONTAP NFS FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você configura o estilo de segurança do FlexVol volume para determinar o tipo de permissões usadas para dados nos volumes do FlexVol da máquina virtual de storage (SVM).

.Passos
. Execute uma das seguintes ações:
+
[cols="30,70"]
|===


| Se o FlexVol volume... | Use o comando... 


 a| 
Ainda não existe
 a| 
`volume create` e inclua o `-security-style` parâmetro para especificar o estilo de segurança.



 a| 
Já existe
 a| 
`volume modify` e inclua o `-security-style` parâmetro para especificar o estilo de segurança.

|===
+
As opções possíveis para o estilo de segurança do FlexVol volume são `unix`, `ntfs` ou `mixed`.

+
Se você não especificar um estilo de segurança ao criar um FlexVol volume, o volume herdará o estilo de segurança do volume raiz.

+
Para obter mais informações sobre os `volume create` comandos ou `volume modify`, link:../volumes/index.html["Gerenciamento de storage lógico"]consulte .

. Para exibir a configuração, incluindo o estilo de segurança do FlexVol volume criado, digite o seguinte comando:
+
`volume show -volume volume_name -instance`


