---
permalink: nfs-admin/control-nfs-access-over-tcp-udp-task.html 
sidebar: sidebar 
keywords: control, nfs, access, tcp, udp 
summary: 'Você pode ativar ou desativar o acesso NFS a máquinas virtuais de armazenamento (SVMs) em TCP e UDP, modificando os parâmetros -tcp e -udp, respetivamente. Isso permite que você controle se os clientes NFS podem acessar dados via TCP ou UDP em seu ambiente.' 
---
= Controle o acesso NFS por TCP e UDP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode ativar ou desativar o acesso NFS a máquinas virtuais de armazenamento (SVMs) em TCP e UDP, modificando os `-tcp` parâmetros e `-udp`, respetivamente. Isso permite que você controle se os clientes NFS podem acessar dados via TCP ou UDP em seu ambiente.

.Sobre esta tarefa
Estes parâmetros aplicam-se apenas ao NFS. Não afetam protocolos auxiliares. Por exemplo, se o NFS sobre TCP estiver desativado, as operações de montagem sobre TCP ainda terão êxito. Para bloquear completamente o tráfego TCP ou UDP, você pode usar regras de política de exportação.

[NOTE]
====
Você deve desativar o SnapDiff RPC Server antes de desativar o TCP para NFS para evitar um erro de falha de comando. Você pode desativar o TCP usando o comando `vserver snapdiff-rpc-server off -vserver vserver name`.

====
.Passo
. Execute uma das seguintes ações:
+
[cols="30,70"]
|===


| Se você quiser que o acesso NFS seja... | Digite o comando... 


 a| 
Ativado em TCP
 a| 
`vserver nfs modify -vserver vserver_name -tcp enabled`



 a| 
Desativado por TCP
 a| 
`vserver nfs modify -vserver vserver_name -tcp disabled`



 a| 
Ativado em UDP
 a| 
`vserver nfs modify -vserver vserver_name -udp enabled`



 a| 
Desativado por UDP
 a| 
`vserver nfs modify -vserver vserver_name -udp disabled`

|===

