---
permalink: nfs-admin/control-nfs-requests-nonreserved-ports-task.html 
sidebar: sidebar 
keywords: control, nfs, request, nonreserved, port 
summary: Você pode rejeitar solicitações de montagem NFS de portas não reservadas habilitando a opção -mount-rootonly. Para rejeitar todas as solicitações NFS de portas não reservadas, você pode ativar a opção -nfs-rootonly. 
---
= Controle solicitações NFS de portas não reservadas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode rejeitar solicitações de montagem NFS de portas não reservadas habilitando a `-mount-rootonly` opção. Para rejeitar todas as solicitações NFS de portas não reservadas, você pode ativar a `-nfs-rootonly` opção.

.Sobre esta tarefa
Por padrão, a opção `-mount-rootonly` é `enabled`.

Por padrão, a opção `-nfs-rootonly` é `disabled`.

Estas opções não se aplicam ao procedimento NULL.

.Passo
. Execute uma das seguintes ações:
+
[cols="35,65"]
|===


| Se você quiser... | Digite o comando... 


 a| 
Permitir solicitações de montagem NFS de portas não reservadas
 a| 
`vserver nfs modify -vserver vserver_name -mount-rootonly disabled`



 a| 
Rejeitar solicitações de montagem NFS de portas não reservadas
 a| 
`vserver nfs modify -vserver vserver_name -mount-rootonly enabled`



 a| 
Permitir todas as solicitações NFS de portas não reservadas
 a| 
`vserver nfs modify -vserver vserver_name -nfs-rootonly disabled`



 a| 
Rejeitar todas as solicitações NFS de portas não reservadas
 a| 
`vserver nfs modify -vserver vserver_name -nfs-rootonly enabled`

|===

