---
permalink: nfs-admin/display-export-policy-netgroup-queue-cache-task.html 
sidebar: sidebar 
keywords: display, export, policy, netgroup, queue, cache 
summary: O ONTAP usa a fila netgroup ao importar e resolver netgroups e usa o cache netgroup para armazenar as informações resultantes. Ao solucionar problemas relacionados ao netgroup da política de exportação, você pode usar os comandos vserver export-policy netgroup queue show e vserver export-policy netgroup cache show para exibir o status da fila do netgroup e o conteúdo do cache do netgroup. 
---
= Exiba a fila e o cache do netgroup da política de exportação no ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O ONTAP usa a fila netgroup ao importar e resolver netgroups e usa o cache netgroup para armazenar as informações resultantes. Ao solucionar problemas relacionados ao netgroup da política de exportação, você pode usar os `vserver export-policy netgroup queue show` comandos e `vserver export-policy netgroup cache show` para exibir o status da fila do netgroup e o conteúdo do cache do netgroup.

.Passo
. Execute uma das seguintes ações:
+
[cols="20,80"]
|===


| Para exibir o netgroup da política de exportação... | Digite o comando... 


 a| 
Fila de espera
 a| 
`vserver export-policy netgroup queue show`



 a| 
Cache
 a| 
`vserver export-policy netgroup cache show -vserver vserver_name`

|===
+
Saiba mais sobre `vserver export-policy netgroup` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+export-policy+netgroup["Referência do comando ONTAP"^]na .


