---
permalink: nfs-admin/display-statistics-task.html 
sidebar: sidebar 
keywords: display, nfs, statistics 
summary: 'É possível exibir estatísticas NFS para máquinas virtuais de storage (SVMs) no sistema de storage para monitorar a performance e diagnosticar problemas.' 
---
= Exibir estatísticas NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível exibir estatísticas NFS para máquinas virtuais de storage (SVMs) no sistema de storage para monitorar a performance e diagnosticar problemas.

.Passos
. Use o `statistics catalog object show` comando para identificar os objetos NFS a partir dos quais você pode exibir dados.
+
`statistics catalog object show -object nfs*`

. Use os `statistics start` comandos e opcionais `statistics stop` para coletar uma amostra de dados de um ou mais objetos.
. Use o `statistics show` comando para exibir os dados de amostra.


.Exemplo: Monitorando o desempenho do NFSv3
O exemplo a seguir mostra os dados de desempenho do protocolo NFSv3.

O comando a seguir inicia a coleta de dados para uma nova amostra:

[listing]
----
vs1::> statistics start -object nfsv3 -sample-id nfs_sample
----
O comando a seguir mostra os dados da amostra especificando contadores que mostram o número de solicitações de leitura e gravação bem-sucedidas versus o número total de solicitações de leitura e gravação:

[listing]
----

vs1::> statistics show -sample-id nfs_sample -counter read_total|write_total|read_success|write_success

Object: nfsv3
Instance: vs1
Start-time: 2/11/2013 15:38:29
End-time: 2/11/2013 15:38:41
Cluster: cluster1

    Counter                                           Value
    --------------------------- ---------------------------
    read_success                                      40042
    read_total                                        40042
    write_success                                   1492052
    write_total                                     1492052
----
.Informações relacionadas
link:../performance-config/index.html["Configuração do monitoramento de desempenho"]
