---
permalink: nfs-admin/enable-disable-rquota-support-task.html 
sidebar: sidebar 
keywords: enable, disable, rquota, support 
summary: 'O ONTAP suporta o protocolo de cota remota versão 1 (rquota v1). O protocolo rquota permite que os clientes NFS obtenham informações de quota para os utilizadores a partir de uma máquina remota. Você pode habilitar o rquota em máquinas virtuais de armazenamento (SVMs) usando o comando vserver nfs Modify.' 
---
= Ativar ou desativar o suporte rquota
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O ONTAP suporta o protocolo de cota remota versão 1 (rquota v1). O protocolo rquota permite que os clientes NFS obtenham informações de quota para os utilizadores a partir de uma máquina remota. Você pode ativar o rquota em máquinas virtuais de armazenamento (SVMs) usando o `vserver nfs modify` comando.

.Sobre esta tarefa
Por padrão, rquota está desativada.

.Passo
. Execute uma das seguintes ações:
+
[cols="2*"]
|===
| Se você quiser... | Digite o seguinte comando... 


 a| 
Habilite o suporte a rquota para SVMs
 a| 
`vserver nfs modify -vserver vserver_name -rquota enable`



 a| 
Desative o suporte rquota para SVMs
 a| 
`vserver nfs modify -vserver vserver_name -rquota disable`

|===
+
Para obter mais informações sobre cotas, link:../volumes/index.html["Gerenciamento de storage lógico"]consulte .


