---
permalink: nfs-admin/enable-disable-nfsv4-referrals-task.html 
sidebar: sidebar 
keywords:  
summary: 'Você pode habilitar referências NFSv4 em máquinas virtuais de armazenamento (SVMs) habilitando as opções -v4-fsid-change e -v4,0-referencies ou -v4,1-referencies. Habilitar referências NFSv4 pode resultar em acesso mais rápido aos dados para clientes NFSv4 que suportam esse recurso.' 
---
= Ativar ou desativar referências NFSv4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode habilitar referências NFSv4D em máquinas virtuais de armazenamento (SVMs) habilitando as opções `-v4-fsid-change` e ``-v4.0-referrals``ou. Habilitar referências NFSv4 pode resultar em acesso mais rápido aos dados para clientes NFSv4 que suportam esse recurso.

.O que você vai precisar
Se você quiser ativar as referências NFS, primeiro desative o NFS paralelo. Não é possível ativar ambos ao mesmo tempo.

.Passos
. Defina o nível de privilégio como avançado:
+
`set -privilege advanced`

. Execute uma das seguintes ações:
+
[cols="35,65"]
|===


| Se você quiser... | Digite o comando... 


 a| 
Ativar NFSv4 referências
 a| 
`vserver nfs modify -vserver vserver_name -v4-fsid-change enabled` `vserver nfs modify -vserver vserver_name -v4.0-referrals enabled`



 a| 
Desative as referências NFSv4
 a| 
`vserver nfs modify -vserver vserver_name -v4.0-referrals disabled`



 a| 
Ativar NFSv4,1 referências
 a| 
`vserver nfs modify -vserver vserver_name -v4-fsid-change enabled` `vserver nfs modify -vserver vserver_name -v4.1-referrals enabled`



 a| 
Desative as referências NFSv4,1
 a| 
`vserver nfs modify -vserver vserver_name -v4.1-referrals disabled`

|===
. Voltar ao nível de privilégio de administrador:
+
`set -privilege admin`


