---
permalink: nfs-admin/enable-disable-modification-nfsv4-acls-task.html 
sidebar: sidebar 
keywords: enable, disable, modification, nfsv4, acl 
summary: Quando o ONTAP recebe um comando chmod para um arquivo ou diretório com uma ACL, por padrão a ACL é mantida e modificada para refletir a alteração de bit de modo. Você pode desativar o parâmetro -v4-ACL-Preserve para alterar o comportamento se quiser que a ACL seja descartada. 
---
= Ativar ou desativar a modificação das ACLs NFSv4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando o ONTAP recebe um `chmod` comando para um arquivo ou diretório com uma ACL, por padrão a ACL é mantida e modificada para refletir a alteração de bit de modo. Você pode desativar o `-v4-acl-preserve` parâmetro para alterar o comportamento se quiser que a ACL seja descartada.

.Sobre esta tarefa
Ao usar estilo de segurança unificado, esse parâmetro também especifica se as permissões de arquivo NTFS são preservadas ou descartadas quando um cliente envia um comando chmod, chgroup ou chown para um arquivo ou diretório.

A predefinição para este parâmetro está ativada.

.Passos
. Defina o nível de privilégio como avançado:
+
`set -privilege advanced`

. Execute uma das seguintes ações:
+
[cols="35,65"]
|===


| Se você quiser... | Digite o seguinte comando... 


 a| 
Ativar retenção e modificação de ACLs NFSv4 existentes (padrão)
 a| 
`vserver nfs modify -vserver vserver_name -v4-acl-preserve enabled`



 a| 
Desative a retenção e solte as ACLs NFSv4 ao alterar os bits de modo
 a| 
`vserver nfs modify -vserver vserver_name -v4-acl-preserve disabled`

|===
. Voltar ao nível de privilégio de administrador:
+
`set -privilege admin`


