---
permalink: nfs-admin/enable-disable-vmware-vstorage-over-nfs-task.html 
sidebar: sidebar 
keywords: enable, disable, vmware, vstorage, nfs 
summary: 'Você pode ativar ou desativar o suporte para VMware vStorage sobre NFS em máquinas virtuais de armazenamento (SVMs) usando o comando vserver nfs Modify.' 
---
= Habilitar ou desabilitar VMware vStorage sobre ONTAP NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode ativar ou desativar o suporte para VMware vStorage sobre NFS em máquinas virtuais de armazenamento (SVMs) usando o `vserver nfs modify` comando.

.Sobre esta tarefa
Por padrão, o suporte ao VMware vStorage sobre NFS está desativado.

.Passos
. Exibir o status atual de suporte do vStorage para SVMs:
+
`vserver nfs show -vserver vserver_name -instance`

. Execute uma das seguintes ações:
+
[cols="2*"]
|===
| Se você quiser... | Digite o seguinte comando... 


 a| 
Habilite o suporte ao VMware vStorage
 a| 
`vserver nfs modify -vserver vserver_name -vstorage enabled`



 a| 
Desative o suporte ao VMware vStorage
 a| 
`vserver nfs modify -vserver vserver_name -vstorage disabled`

|===


.Depois de terminar
Você deve instalar o plug-in NFS para VMware VAAI antes de usar essa funcionalidade. Para obter mais informações, consulte _Instalando o plug-in NFS do NetApp para VMware VAAI_.

.Informações relacionadas
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61278["Documentação do NetApp: Plug-in NFS do NetApp para VMware VAAI"^]
