---
permalink: nfs-admin/how-ontap-creates-file-directory-names-concept.html 
sidebar: sidebar 
keywords: ontap, create, file, directory, name 
summary: 'O ONTAP cria e mantém dois nomes para arquivos ou diretórios em qualquer diretório que tenha acesso de um cliente SMB: O nome longo original e um nome no formato 8,3.' 
---
= Como o ONTAP cria nomes de arquivo e diretório
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O ONTAP cria e mantém dois nomes para arquivos ou diretórios em qualquer diretório que tenha acesso de um cliente SMB: O nome longo original e um nome no formato 8,3.

Para nomes de arquivo ou diretório que excedam o nome de oito carateres ou o limite de extensão de três carateres (para arquivos), o ONTAP gera um nome de formato 8,3 da seguinte forma:

* Ele trunca o nome do arquivo ou diretório original para seis carateres, se o nome exceder seis carateres.
* Ele adiciona um til (...) e um número, um a cinco, aos nomes de arquivo ou diretório que não são mais exclusivos depois de serem truncados.
+
Se ele ficar sem números porque há mais de cinco nomes semelhantes, ele cria um nome exclusivo que não tem relação com o nome original.

* No caso dos arquivos, ele trunca a extensão do nome do arquivo para três carateres.


Por exemplo, se um cliente NFS criar um arquivo chamado `specifications.html`, o nome do arquivo de formato 8,3 criado pelo ONTAP será `specif~1.htm`. Se esse nome já existir, o ONTAP usará um número diferente no final do nome do arquivo. Por exemplo, se um cliente NFS criar outro arquivo chamado `specifications_new.html`, o formato 8,3 do `specifications_new.html` é `specif~2.htm`.
