---
permalink: nfs-admin/how-name-mappings-used-concept.html 
sidebar: sidebar 
keywords: configure, name, mapping 
summary: O ONTAP usa mapeamento de nomes para mapear identidades SMB para identidades UNIX, identidades Kerberos para identidades UNIX e identidades UNIX para identidades SMB. Ele precisa dessas informações para obter credenciais de usuário e fornecer acesso adequado aos arquivos, independentemente de estarem se conetando a partir de um cliente NFS ou de um cliente SMB. 
---
= Configure a visão geral dos mapeamentos de nomes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O ONTAP usa mapeamento de nomes para mapear identidades SMB para identidades UNIX, identidades Kerberos para identidades UNIX e identidades UNIX para identidades SMB. Ele precisa dessas informações para obter credenciais de usuário e fornecer acesso adequado aos arquivos, independentemente de estarem se conetando a partir de um cliente NFS ou de um cliente SMB.

Há duas exceções em que você não precisa usar o mapeamento de nomes:

* Você configura um ambiente UNIX puro e não planeja usar o acesso SMB ou o estilo de segurança NTFS em volumes.
* Em vez disso, você configura o usuário padrão a ser usado.
+
Nesse cenário, o mapeamento de nomes não é necessário porque, em vez de mapear cada credencial de cliente individual, todas as credenciais de cliente são mapeadas para o mesmo usuário padrão.



Observe que você pode usar o mapeamento de nomes somente para usuários, não para grupos.

No entanto, você pode mapear um grupo de usuários individuais para um usuário específico. Por exemplo, você pode mapear todos os usuários do AD que começam ou terminam com a palavra VENDAS para um usuário UNIX específico e para o UID do usuário.
