---
permalink: nfs-admin/limitations-support-nfsv4-concept.html 
sidebar: sidebar 
keywords: limitation, ontap, support, nfsv4 
summary: Você deve estar ciente de várias limitações do suporte do ONTAP para NFSv4. 
---
= Saiba mais sobre as limitações de suporte ONTAP para NFSv4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve estar ciente de várias limitações do suporte do ONTAP para NFSv4.

* O recurso de delegação não é suportado por todos os tipos de cliente.
* No ONTAP 9.4 e versões anteriores, nomes com carateres não-ASCII em volumes diferentes de UTF8 volumes são rejeitados pelo sistema de armazenamento.
+
No ONTAP 9.5 e versões posteriores, os volumes criados com a configuração de linguagem utf8mb4 e montados usando NFS v4 não estão mais sujeitos a essa restrição.

* Todos os identificadores de arquivo são persistentes; o servidor não fornece alças de arquivo voláteis.
* Migração e replicação não são compatíveis.
* Os clientes NFSv4 não são suportados com espelhos de compartilhamento de carga somente leitura.
+
O ONTAP encaminha clientes NFSv4 para a fonte do espelho de compartilhamento de carga para acesso direto de leitura e gravação.

* Atributos nomeados não são suportados.
* Todos os atributos recomendados são suportados, exceto para o seguinte:
+
** `archive`
** `hidden`
** `homogeneous`
** `mimetype`
** `quota_avail_hard`
** `quota_avail_soft`
** `quota_used`
** `system`
** `time_backup`
+

NOTE: Embora não ofereça suporte aos `quota*` atributos, o ONTAP oferece suporte a cotas de usuário e grupo por meio do protocolo RQUOTA de banda lateral.




