---
permalink: nfs-admin/limits-local-unix-users-groups--concept.html 
sidebar: sidebar 
keywords: limit, local, unix, user, group, member 
summary: O ONTAP introduziu limites para o número máximo de usuários e grupos UNIX no cluster e comandos para gerenciar esses limites. Esses limites podem ajudar a evitar problemas de desempenho, impedindo que os administradores criem muitos usuários e grupos UNIX locais no cluster. 
---
= Limites para usuários, grupos e membros de grupo UNIX locais para SVMs ONTAP NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O ONTAP introduziu limites para o número máximo de usuários e grupos UNIX no cluster e comandos para gerenciar esses limites. Esses limites podem ajudar a evitar problemas de desempenho, impedindo que os administradores criem muitos usuários e grupos UNIX locais no cluster.

Há um limite para o número combinado de grupos de usuários UNIX locais e membros de grupo. Há um limite separado para usuários UNIX locais. Os limites são em todo o cluster. Cada um desses novos limites é definido como um valor padrão que você pode modificar até um limite rígido pré-atribuído.

[cols="3*"]
|===
| Banco de dados | Limite padrão | Limite rígido 


 a| 
Usuários locais do UNIX
 a| 
32.768
 a| 
65.536



 a| 
Grupos UNIX locais e membros do grupo
 a| 
32.768
 a| 
65.536

|===