---
permalink: nfs-admin/manage-limits-local-unix-users-groups-task.html 
sidebar: sidebar 
keywords: manage, limit, local, unix, user, group 
summary: Existem comandos ONTAP específicos para gerenciar limites para usuários e grupos UNIX locais. Os administradores de cluster podem usar esses comandos para solucionar problemas de desempenho no cluster que se acredita estar relacionado a um número excessivo de usuários e grupos UNIX locais. 
---
= Gerenciar limites para usuários e grupos UNIX locais no ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Existem comandos ONTAP específicos para gerenciar limites para usuários e grupos UNIX locais. Os administradores de cluster podem usar esses comandos para solucionar problemas de desempenho no cluster que se acredita estar relacionado a um número excessivo de usuários e grupos UNIX locais.

.Sobre esta tarefa
Esses comandos estão disponíveis para o administrador do cluster no nível avançado de privilégio.

.Passo
. Execute uma das seguintes ações:
+
[cols="2*"]
|===
| Se você quiser... | Use o comando... 


 a| 
Exibir informações sobre os limites de usuários UNIX locais
 a| 
`vserver services unix-user max-limit show`



 a| 
Exibir informações sobre os limites de grupos UNIX locais
 a| 
`vserver services unix-group max-limit show`



 a| 
Modifique os limites de usuários UNIX locais
 a| 
`vserver services unix-user max-limit modify`



 a| 
Modificar limites de grupo UNIX local
 a| 
`vserver services unix-group max-limit modify`

|===
+
Saiba mais sobre `vserver services unix` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+services+unix["Referência do comando ONTAP"^]na .


