---
permalink: nfs-admin/modify-credential-cache-time-to-live-reference.html 
sidebar: sidebar 
keywords: reason, modify, nfs, credential, cache, time, live 
summary: 'Há vários cenários ao modificar o cache de credenciais NFS Time-to-live (TTL) pode ajudar a resolver problemas. Você deve entender quais são esses cenários, bem como as consequências de fazer essas modificações.' 
---
= Motivos para modificar o tempo de vida do cache de credenciais NFS para SVMs ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O ONTAP usa um cache de credenciais para armazenar as informações necessárias para autenticação de usuário para acesso de exportação NFS para fornecer acesso mais rápido e melhorar o desempenho. Você pode configurar por quanto tempo as informações são armazenadas no cache de credenciais para personalizá-las para o seu ambiente.

Há vários cenários ao modificar o cache de credenciais NFS Time-to-live (TTL) pode ajudar a resolver problemas. Você deve entender quais são esses cenários, bem como as consequências de fazer essas modificações.



== Razões

Considere alterar o TTL padrão nas seguintes circunstâncias:

[cols="2*"]
|===
| Problema | Medidas corretivas 


 a| 
Os servidores de nomes no seu ambiente estão sofrendo degradação no desempenho devido a uma alta carga de solicitações do ONTAP.
 a| 
Aumente o TTL para credenciais positivas e negativas armazenadas em cache para reduzir o número de solicitações do ONTAP para servidores de nomes.



 a| 
O administrador do servidor de nomes fez alterações para permitir o acesso a usuários NFS que foram negados anteriormente.
 a| 
Diminua o TTL para credenciais negativas armazenadas em cache para reduzir o tempo que os usuários NFS precisam esperar que o ONTAP solicite novas credenciais de servidores de nomes externos para que eles possam obter acesso.



 a| 
O administrador do servidor de nomes fez alterações para negar acesso a usuários NFS que anteriormente eram permitidos.
 a| 
Reduza o TTL para credenciais positivas armazenadas em cache para reduzir o tempo antes que o ONTAP solicite novas credenciais de servidores de nomes externos para que os usuários NFS agora tenham acesso negado.

|===


== Consequências

Você pode modificar o tempo individualmente para armazenar credenciais positivas e negativas em cache. No entanto, você deve estar ciente das vantagens e desvantagens de fazê-lo.

[cols="3*"]
|===
| Se você... | A vantagem é... | A desvantagem é... 


 a| 
Aumente o tempo de cache de credenciais positivas
 a| 
O ONTAP envia solicitações de credenciais para nomear servidores com menos frequência, reduzindo a carga nos servidores de nomes.
 a| 
Leva mais tempo para negar acesso a usuários NFS que anteriormente eram permitidos acesso, mas não são mais.



 a| 
Diminua o tempo de cache positivo de credenciais
 a| 
Leva menos tempo para negar acesso a usuários NFS que anteriormente eram permitidos acesso, mas não são mais.
 a| 
O ONTAP envia solicitações de credenciais para nomear servidores com mais frequência, aumentando a carga nos servidores de nomes.



 a| 
Aumente o tempo de cache de credenciais negativas
 a| 
O ONTAP envia solicitações de credenciais para nomear servidores com menos frequência, reduzindo a carga nos servidores de nomes.
 a| 
Leva mais tempo para conceder acesso a usuários NFS que anteriormente não tinham acesso permitido, mas agora.



 a| 
Diminua o tempo de cache de credenciais negativas
 a| 
Leva menos tempo para conceder acesso a usuários NFS que anteriormente não tinham acesso permitido, mas agora.
 a| 
O ONTAP envia solicitações de credenciais para nomear servidores com mais frequência, aumentando a carga nos servidores de nomes.

|===