---
permalink: nfs-admin/modify-maximum-ace-limit-nfsv4-acls-task.html 
sidebar: sidebar 
keywords:  
summary: Você pode modificar o número máximo de ACEs permitidos para cada ACL NFSv4 modificando o parâmetro -v4-ACL-max-aces. Por padrão, o limite é definido como 400 ACEs para cada ACL. Aumentar esse limite pode ajudar a garantir a migração bem-sucedida de dados com ACLs que contêm mais de 400 ACEs para sistemas de storage que executam ONTAP. 
---
= Modifique o limite máximo de ACE para ACLs NFSv4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível modificar o número máximo de ACEs permitidos para cada ACL NFSv4 modificando o parâmetro `-v4-acl-max-aces`. Por padrão, o limite é definido como 400 ACEs para cada ACL. Aumentar esse limite pode ajudar a garantir a migração bem-sucedida de dados com ACLs que contêm mais de 400 ACEs para sistemas de storage que executam ONTAP.

.Sobre esta tarefa
Aumentar esse limite pode afetar o desempenho dos clientes que acessam arquivos com ACLs NFSv4.

.Passos
. Defina o nível de privilégio como avançado:
+
`set -privilege advanced`

. Modifique o limite máximo de ACE para ACLs NFSv4:
+
`vserver nfs modify -v4-acl-max-aces max_ace_limit`

+
O intervalo válido de

+
`max_ace_limit` é a. `192` `1024.`

. Voltar ao nível de privilégio de administrador:
+
`set -privilege admin`


