---
permalink: nfs-admin/nfs-credential-cache-concept.html 
sidebar: sidebar 
keywords: nfs, credential, cache 
summary: Quando um usuário NFS solicita acesso às exportações de NFS no sistema de storage, o ONTAP deve recuperar as credenciais de usuário de servidores de nomes externos ou de arquivos locais para autenticar o usuário. Em seguida, o ONTAP armazena essas credenciais em um cache interno de credenciais para referência posterior. Entender como os caches de credenciais NFS funcionam permite que você lide com possíveis problemas de desempenho e acesso. 
---
= Como funciona o cache de credenciais ONTAP NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando um usuário NFS solicita acesso às exportações de NFS no sistema de storage, o ONTAP deve recuperar as credenciais de usuário de servidores de nomes externos ou de arquivos locais para autenticar o usuário. Em seguida, o ONTAP armazena essas credenciais em um cache interno de credenciais para referência posterior. Entender como os caches de credenciais NFS funcionam permite que você lide com possíveis problemas de desempenho e acesso.

Sem o cache de credenciais, o ONTAP teria que consultar serviços de nomes sempre que um usuário NFS solicitou acesso. Em um sistema de armazenamento ocupado que é acessado por muitos usuários, isso pode rapidamente levar a sérios problemas de desempenho, causando atrasos indesejados ou até mesmo negações ao acesso do cliente NFS.

Com o cache de credenciais, o ONTAP recupera as credenciais do usuário e as armazena por um período predeterminado de tempo para acesso rápido e fácil caso o cliente NFS envie outra solicitação. Este método oferece as seguintes vantagens:

* Ele facilita a carga no sistema de armazenamento, manipulando menos solicitações para servidores de nomes externos (como NIS ou LDAP).
* Ele facilita a carga em servidores de nomes externos, enviando menos solicitações para eles.
* Ele acelera o acesso do usuário eliminando o tempo de espera para obter credenciais de fontes externas antes que o usuário possa ser autenticado.


O ONTAP armazena credenciais positivas e negativas no cache de credenciais. Credenciais positivas significa que o usuário foi autenticado e recebeu acesso. Credenciais negativas significa que o usuário não foi autenticado e foi negado o acesso.

Por padrão, o ONTAP armazena credenciais positivas por 24 horas; ou seja, após a autenticação inicial de um usuário, o ONTAP usa as credenciais em cache para quaisquer solicitações de acesso por esse usuário por 24 horas. Se o usuário solicitar acesso após 24 horas, o ciclo será iniciado novamente: O ONTAP descarta as credenciais armazenadas em cache e obtém as credenciais novamente a partir da fonte de serviço de nome apropriada. Se as credenciais tiverem sido alteradas no servidor de nomes durante as 24 horas anteriores, o ONTAP armazena em cache as credenciais atualizadas para uso nas próximas 24 horas.

Por padrão, o ONTAP armazena credenciais negativas por duas horas; ou seja, depois de inicialmente negar acesso a um usuário, o ONTAP continua negando quaisquer solicitações de acesso por esse usuário por duas horas. Se o usuário solicitar acesso após 2 horas, o ciclo será iniciado novamente: O ONTAP obtém as credenciais novamente da fonte de serviço de nome apropriada. Se as credenciais tiverem sido alteradas no servidor de nomes durante as duas horas anteriores, o ONTAP armazena em cache as credenciais atualizadas para uso nas próximas duas horas.
