---
permalink: nfs-admin/nfsv40-functionality-supported-concept.html 
sidebar: sidebar 
keywords: nfsv4.0, functionality, support, ontap 
summary: O ONTAP suporta todas as funcionalidades obrigatórias no NFSv4,0, exceto os mecanismos de segurança SPKM3 e LIPKEY. 
---
= NFSv4,0 funcionalidade suportada pelo ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O ONTAP suporta todas as funcionalidades obrigatórias no NFSv4,0, exceto os mecanismos de segurança SPKM3 e LIPKEY.

A seguinte funcionalidade NFSv4 é suportada:

* *COMPOSTO*
+
Permite que um cliente solicite várias operações de arquivo em uma única solicitação RPC (chamada de procedimento remoto).

* * Delegação de arquivos*
+
Permite que o servidor delege o controle de arquivos a alguns tipos de clientes para acesso de leitura e gravação.

* *Pseudo-fs*
+
Usado por servidores NFSv4 para determinar pontos de montagem no sistema de armazenamento. Não existe nenhum protocolo de montagem no NFSv4.

* *Bloqueio*
+
Baseado em leasing. Não existem protocolos NLM (Network Lock Manager) ou NSM (Network Status Monitor) separados no NFSv4.



Para obter mais informações sobre o protocolo NFSv4,0, consulte RFC 3530.
