---
permalink: nfs-admin/ontap-differs-windows-locks-share-path-concept.html 
sidebar: sidebar 
keywords: ontap, windows, handle, locks, share, path, component 
summary: Ao contrário do Windows, o ONTAP não bloqueia cada componente do caminho para um arquivo aberto enquanto o arquivo está aberto. Esse comportamento também afeta os caminhos de compartilhamento SMB. 
---
= Como o ONTAP difere do Windows no gerenciamento de bloqueios em componentes de caminho de compartilhamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao contrário do Windows, o ONTAP não bloqueia cada componente do caminho para um arquivo aberto enquanto o arquivo está aberto. Esse comportamento também afeta os caminhos de compartilhamento SMB.

Como o ONTAP não bloqueia cada componente do caminho, é possível renomear um componente do caminho acima do arquivo aberto ou do compartilhamento, o que pode causar problemas para determinados aplicativos ou fazer com que o caminho de compartilhamento na configuração do SMB seja inválido. Isso pode fazer com que o compartilhamento seja inacessível.

Para evitar problemas causados pela renomeação de componentes de caminho, você pode aplicar configurações de segurança da Lista de Controle de Acesso (ACL) do Windows que impedem que usuários ou aplicativos renomeem diretórios críticos.

Saiba mais link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_prevent_directories_from_being_renamed_while_clients_are_accessing_them["Como impedir que diretórios sejam renomeados enquanto os clientes os acessam"^]sobre o .
