---
permalink: nfs-admin/ontap-controls-access-files-concept.html 
sidebar: sidebar 
keywords: ontap, control, access, file 
summary: O ONTAP controla o acesso aos arquivos de acordo com as restrições baseadas em autenticação e em arquivo especificadas. 
---
= Como o ONTAP controla o acesso aos arquivos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O ONTAP controla o acesso aos arquivos de acordo com as restrições baseadas em autenticação e em arquivo especificadas.

Quando um cliente se coneta ao sistema de armazenamento para acessar arquivos, o ONTAP tem que executar duas tarefas:

* Autenticação
+
O ONTAP tem que autenticar o cliente verificando a identidade com uma fonte confiável. Além disso, o tipo de autenticação do cliente é um método que pode ser usado para determinar se um cliente pode acessar dados ao configurar políticas de exportação (opcional para CIFS).

* Autorização
+
O ONTAP tem que autorizar o usuário comparando as credenciais do usuário com as permissões configuradas no arquivo ou diretório e determinando que tipo de acesso, se houver, a fornecer.



Para gerenciar adequadamente o controle de acesso a arquivos, o ONTAP deve se comunicar com serviços externos, como NIS, LDAP e servidores do ative Directory. A configuração de um sistema de storage para acesso a arquivos usando CIFS ou NFS requer a configuração dos serviços apropriados, dependendo do seu ambiente no ONTAP.
