---
permalink: nfs-admin/setup-file-access-concept.html 
sidebar: sidebar 
keywords: setting, file, access, nfs 
summary: 'Você deve concluir várias etapas para permitir que os clientes acessem arquivos em máquinas virtuais de armazenamento (SVMs) usando NFS. Existem algumas etapas adicionais que são opcionais, dependendo da configuração atual do seu ambiente.' 
---
= Configure o acesso a arquivos usando a visão geral do NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve concluir várias etapas para permitir que os clientes acessem arquivos em máquinas virtuais de armazenamento (SVMs) usando NFS. Existem algumas etapas adicionais que são opcionais, dependendo da configuração atual do seu ambiente.

Para que os clientes possam acessar arquivos em SVMs usando NFS, você deve concluir as seguintes tarefas:

. Habilite o protocolo NFS na SVM.
+
Você precisa configurar o SVM para permitir acesso a dados de clientes em NFS.

. Criar um servidor NFS no SVM.
+
Um servidor NFS é uma entidade lógica no SVM que permite que o SVM forneça arquivos em NFS. Você deve criar o servidor NFS e especificar as versões do protocolo NFS que deseja permitir.

. Configurar políticas de exportação no SVM.
+
Você deve configurar políticas de exportação para tornar os volumes e qtrees disponíveis para os clientes.

. Configure o servidor NFS com a segurança adequada e outras configurações, dependendo da rede e do ambiente de armazenamento.
+
Esta etapa pode incluir a configuração Kerberos, link:tls-nfs-strong-security-concept.html["NFS em TLS"], LDAP, NIS, mapeamentos de nomes e usuários locais.


