---
permalink: nfs-admin/specify-nfsv4-locking-lease-period-task.html 
sidebar: sidebar 
keywords: specify, nfsv4, lock, lease, period 
summary: 'Para especificar o período de locação de bloqueio NFSv4 (ou seja, o período de tempo em que o ONTAP concede irrevogavelmente um bloqueio a um cliente), você pode modificar a opção -v4-lease-seconds. Períodos de leasing mais curtos aceleram a recuperação do servidor, enquanto períodos de leasing mais longos são benéficos para servidores que lidam com uma grande quantidade de clientes.' 
---
= Especifique o período de concessão de bloqueio NFSv4 para SVMs ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para especificar o período de locação de bloqueio NFSv4 (ou seja, o período de tempo em que o ONTAP concede irrevogavelmente um bloqueio a um cliente), você pode modificar a `-v4-lease-seconds` opção. Períodos de leasing mais curtos aceleram a recuperação do servidor, enquanto períodos de leasing mais longos são benéficos para servidores que lidam com uma grande quantidade de clientes.

.Sobre esta tarefa
Por padrão, essa opção está definida como `30`. O valor mínimo para esta opção é `10`. O valor máximo para esta opção é o período de tolerância de bloqueio, que pode ser definido com a `locking.lease_seconds` opção.

.Passos
. Defina o nível de privilégio como avançado:
+
`set -privilege advanced`

. Introduza o seguinte comando:
+
`vserver nfs modify -vserver vserver_name -v4-lease-seconds number_of_seconds`

. Voltar ao nível de privilégio de administrador:
+
`set -privilege admin`


