---
permalink: nfs-admin/validate-qtree-ids-qtree-file-operations-task.html 
sidebar: sidebar 
keywords: validate, qtree, id, file, operation 
summary: O ONTAP pode executar uma validação adicional opcional de IDs de qtree. Essa validação garante que as solicitações de operação de arquivo cliente usem um ID de qtree válido e que os clientes só possam mover arquivos dentro da mesma qtree. Você pode ativar ou desativar essa validação modificando o parâmetro -validate-qtree-export. Este parâmetro está ativado por predefinição. 
---
= Valide as IDs de qtree para operações de arquivos de qtree
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O ONTAP pode executar uma validação adicional opcional de IDs de qtree. Essa validação garante que as solicitações de operação de arquivo cliente usem um ID de qtree válido e que os clientes só possam mover arquivos dentro da mesma qtree. Pode ativar ou desativar esta validação modificando o `-validate-qtree-export` parâmetro. Este parâmetro está ativado por predefinição.

.Sobre esta tarefa
Esse parâmetro só é efetivo quando você atribuiu uma política de exportação diretamente a um ou mais qtrees na máquina virtual de armazenamento (SVM).

.Passos
. Defina o nível de privilégio como avançado:
+
`set -privilege advanced`

. Execute uma das seguintes ações:
+
[cols="2*"]
|===
| Se pretender que a validação da ID de qtree seja... | Digite o seguinte comando... 


 a| 
Ativado
 a| 
`vserver nfs modify -vserver vserver_name -validate-qtree-export enabled`



 a| 
Desativado
 a| 
`vserver nfs modify -vserver vserver_name -validate-qtree-export disabled`

|===
. Voltar ao nível de privilégio de administrador:
+
`set -privilege admin`


