---
sidebar: sidebar 
permalink: anti-ransomware/enable-arp-ai-with-au.html 
keywords: ransomware, arp, enable, ai, automatic, update, upgrade, autonomous ransomware protection 
summary: A partir do ONTAP 9.16,1, ative automaticamente o ARP/AI para instalações FlexVol com ARP ativado ou ative-o manualmente após atender aos pré-requisitos. 
---
= Ative o ONTAP ARP/AI com a atualização automática
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.16,1, o ARP adotou a proteção autônoma contra ransomware com Inteligência artificial (ARP/AI) para melhorar a deteção e a resposta de ameaças. Depois de atualizar o cluster para o ONTAP 9.16,1, o ARP/AI será ativado automaticamente para volumes FlexVol se o ARP já estiver ativado para esses volumes. Se você não ativou o ARP ou não ativou as atualizações automáticas para o cluster, siga um dos cenários descritos neste procedimento.


IMPORTANT: Antes de atualizar para o ONTAP 9.16,1, link:../upgrade/arp-warning-clear.html["Feche todas as deteções ARP existentes"].

.Antes de começar
* Você deve ter volumes FlexVol para usar ARP/AI. Se você tiver volumes FlexGroup, o modelo ARP usado antes do ARP/AI continuará funcionando após a atualização para o ONTAP 9.16,1.



NOTE: Quando você atualiza para o ONTAP 9.16.1, o ARP é ativado e fica ativo automaticamente para quaisquer instâncias ARP existentes com volumes FlexVol. Como o ARP/AI é treinado em um modelo extensivo de aprendizado de máquina, um período de aprendizado não é mais necessário. Quaisquer períodos de aprendizado que não tenham sido concluídos antes da atualização serão automaticamente encerrados e os volumes serão transferidos para ARP/AI ativo.

.Passos
. Siga o cenário específico da sua configuração:
+
** *Para novos clusters executando o ONTAP 9.16,1*link:enable-task.html["Ativar ARP"]: . O ARP não está ativado por padrão. Depois de ativar o ARP, a funcionalidade ARP/AI é automaticamente ativada e ativa nos volumes que você escolher proteger.
** *Para clusters existentes recentemente atualizados para ONTAP 9.16,1 que têm ARP ativado*: Nenhuma ação necessária. O ARP/AI se tornará automaticamente o novo método ARP de proteção contra ameaças nos volumes FlexVol que você escolheu proteger.
** *Para clusters existentes recentemente atualizados para o ONTAP 9.16,1 que não tenham o ARP ativado*: link:enable-task.html["Ativar ARP"]. O ARP/AI se tornará automaticamente o novo método ARP de proteção contra ameaças depois de ativar o ARP.


. Depois que o ARP/AI estiver ativado, decida se deseja que as atualizações de proteção ARP/AI sejam entregues e link:arp-ai-automatic-updates.html["automaticamente ou manualmente"]instaladas.


.Informações relacionadas
* link:arp-ai-automatic-updates.html["Atualizar ARP/AI"]

