---
sidebar: sidebar 
permalink: anti-ransomware/pause-task.html 
keywords: anti-ransomware, ransomware, pause, autonomous, protection, arp 
summary: Se você está esperando eventos de carga de trabalho incomuns, você pode suspender temporariamente e retomar a análise Autonomous ransomware Protection a qualquer momento. 
---
= Interrompa a proteção do ONTAP Autonomous ransomware para excluir eventos de workload da análise
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se você está esperando eventos de carga de trabalho incomuns, você pode suspender e retomar temporariamente a análise ARP (Autonomous ransomware Protection) a qualquer momento.

A partir do ONTAP 9.13.1, você pode habilitar a verificação multi-admin (MAV) para que dois ou mais administradores de usuário autenticados sejam necessários para pausar o ARP.

link:../multi-admin-verify/enable-disable-task.html["Saiba mais sobre o MAV"].

.Sobre esta tarefa
Durante uma pausa ARP, nenhum evento é registrado nem nenhuma ação para novas gravações. No entanto, a operação de análise continua para logs anteriores em segundo plano.


NOTE: Não use a função de desativação ARP para pausar a análise. Isso desativa o ARP no volume e todas as informações existentes sobre o comportamento da carga de trabalho aprendida são perdidas. Isso exigiria um reinício do período de aprendizagem.

.Passos
Você pode usar o Gerenciador do sistema ou a CLI do ONTAP para pausar o ARP.

[role="tabbed-block"]
====
.System Manager
--
. Selecione *armazenamento > volumes* e, em seguida, selecione o volume em que deseja pausar ARP.
. Na guia **Segurança** da visão geral dos volumes, selecione *Pausa anti-ransomware* na caixa *Anti-ransomware*.
+

NOTE: A partir do ONTAP 9.13,1, se você estiver usando MAV para proteger suas configurações ARP, a operação de pausa solicitará que você obtenha a aprovação de um ou mais administradores adicionais. link:../multi-admin-verify/request-operation-task.html["A aprovação deve ser recebida de todos os administradores"] Associado ao grupo de aprovação MAV ou à operação falhará.



--
.CLI
--
. Pausar ARP em um volume:
+
`security anti-ransomware volume pause -vserver _svm_name_ -volume _vol_name_`

. Para retomar o processamento, use o `resume` comando:
+
`security anti-ransomware volume resume -vserver _svm_name_ -volume _vol_name_`

. Se você estiver usando MAV (disponível com ARP começando com ONTAP 9.13,1) para proteger suas configurações ARP, a operação de pausa solicitará que você obtenha a aprovação de um ou mais administradores adicionais. A aprovação deve ser recebida de todos os administradores associados ao grupo de aprovação MAV ou a operação falhará.
+
Se você estiver usando MAV e uma operação de pausa esperada precisar de aprovações adicionais, cada aprovador de grupo MAV faz o seguinte:

+
.. Mostrar o pedido:
+
`security multi-admin-verify request show`

.. Aprovar a solicitação:
+
`security multi-admin-verify request approve -index[_number returned from show request_]`

+
A resposta para o último aprovador de grupo indica que o volume foi modificado e o estado de ARP está pausado.

+
Se você estiver usando MAV e for um aprovador de grupo MAV, poderá rejeitar uma solicitação de operação de pausa:

+
`security multi-admin-verify request veto -index[_number returned from show request_]`





--
====