---
sidebar: sidebar 
permalink: anti-ransomware/switch-learning-to-active-mode.html 
keywords: ransomware, arp, mode, switch, active, learning, autonomous ransomware protection 
summary: Para ARP 9.15.1 e versões anteriores em ambientes NAS, alterne manualmente ou automaticamente um volume habilitado para ARP do modo de aprendizagem para o modo ativo. 
---
= Mude para o modo ativo no ONTAP ARP após um período de aprendizagem
:allow-uri-read: 


[role="lead"]
Em ambientes NAS, alterne manual ou automaticamente um volume habilitado para ARP do modo de aprendizagem para o modo ativo. Será necessário alternar entre os modos se você estiver usando ARP com o ONTAP 9.15.1 ou versões anteriores, ou se o ARP estiver sendo executado em volumes FlexGroup com o ONTAP 9.17.1 ou versões anteriores.

Após o ARP concluir uma execução no modo de aprendizado com duração mínima recomendada de 30 dias, você poderá alternar manualmente para o modo ativo. A partir do ONTAP 9.13.1, o ARP determina automaticamente o intervalo ideal do período de aprendizado e automatiza a alternância, o que pode ocorrer antes dos 30 dias.

Se você estiver usando ARP com proteção ARP/AI, o ARP será ativado automaticamente. Não é necessário período de aprendizagem.


NOTE: Nos volumes existentes, os modos de aprendizagem e ativos aplicam-se apenas a dados recém-gravados, não a dados já existentes no volume. Os dados existentes não são digitalizados e analisados, porque as caraterísticas do tráfego de dados normal anterior são assumidas com base nos novos dados depois que o volume é ativado para ARP.



== Mude manualmente para o modo ativo após o período de aprendizagem

Para o ONTAP 9.10.1 a 9.15.1 (ONTAP 9.17.1 e versões anteriores com volumes FlexGroup ), você pode fazer a transição manual do modo de aprendizado ARP para o modo ativo usando o System Manager ou a CLI do ONTAP após a conclusão do período de aprendizado.

.Sobre esta tarefa
A transição manual para o modo ativo após um período de aprendizado descrito neste procedimento é específica para ambientes NAS.

.Passos
Você pode usar o System Manager ou o ONTAP CLI para alternar do modo de aprendizagem para o modo ativo.

[role="tabbed-block"]
====
.System Manager
--
. Selecione *armazenamento > volumes* e, em seguida, selecione o volume que está pronto para o modo ativo.
. Na guia *Segurança* da visão geral *volumes*, selecione *mudar para o modo ativo* na caixa Anti-ransomware.
. Você pode verificar o estado ARP do volume na caixa *Anti-ransomware*.


--
.CLI
--
. Modifique o volume protegido para alternar para o modo ativo, caso isso não tenha sido feito automaticamente:
+
[source, cli]
----
security anti-ransomware volume enable -volume <vol_name> -vserver <svm_name>
----
+
Você também pode alternar para o modo ativo com o comando modificar volume:

+
[source, cli]
----
volume modify -volume <vol_name> -vserver <svm_name> -anti-ransomware-state enabled
----
. Verifique o estado ARP do volume.
+
[source, cli]
----
security anti-ransomware volume show
----


--
====


== Mudança automática do modo de aprendizagem para o modo ativo

A partir do ONTAP 9.13.1, o aprendizado adaptativo foi adicionado ao ARP Analytics, e a alternância do modo de aprendizado para o modo ativo é feita automaticamente. A decisão autônoma do ARP de alternar automaticamente do modo de aprendizado para o modo ativo é baseada nas configurações das seguintes opções:

[listing]
----
 -anti-ransomware-auto-switch-minimum-incoming-data-percent
 -anti-ransomware-auto-switch-duration-without-new-file-extension
 -anti-ransomware-auto-switch-minimum-learning-period
 -anti-ransomware-auto-switch-minimum-file-count
 -anti-ransomware-auto-switch-minimum-file-extension
----
Se a alternância automática estiver habilitada, o volume mudará para o modo ativo automaticamente após um máximo de 30 dias, mesmo que todas as condições não sejam atendidas. Esse limite de 30 dias é fixo e não pode ser alterado.

Para obter mais informações sobre opções de configuração ARP, incluindo valores padrão, consulte link:https://docs.netapp.com/us-en/ontap-cli/security-anti-ransomware-volume-auto-switch-to-enable-mode-show.html["Referência do comando ONTAP"^].

.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+anti-ransomware+volume["volume anti-ransomware de segurança"^]

