---
sidebar: sidebar 
permalink: snapmirror-active-sync/aufo-site-b-troubleshoot-task.html 
keywords: SM-BC, SMBC, troubleshooting, automatic unplanned failover, aufo, failover, Mediator, Cloud Mediator, quorum, snapmirror active sync 
summary: Uma falha no local A não aciona um failover não planejado no local B.. 
---
= Failover não planejado automático não acionado no local B.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Use as seguintes informações se uma falha no Site A não acionar um failover não planejado no Site B.

.Problema:
Uma falha no local A não aciona um failover não planejado no local B..

.Causa possível n.o 1:
O ONTAP Mediator ou o ONTAP Cloud Mediator não está configurado. Para determinar se esta é a causa, emita o  `snapmirror mediator show` comando no cluster do Site B.

....
Cluster2::> snapmirror mediator show
This table is currently empty.
....
Este exemplo indica que o Mediador não está configurado no Site B.

.Solução:
Certifique-se de que o Mediador esteja configurado em ambos os clusters, que o status esteja conectado e que o quorum esteja definido como Verdadeiro.

.Causa possível n.o 2:
O grupo de consistência do SnapMirror está fora de sincronia. Para determinar se essa é a causa, exiba o log de eventos para ver se o grupo de consistência estava em sincronia durante o momento em que ocorreu a falha do Site A.

....
cluster::> event log show -event *out.of.sync*

Time                Node             Severity      Event
------------------- ---------------- ------------- ---------------------------
10/1/2020 23:26:12  sti42-vsim-ucs511w ERROR       sms.status.out.of.sync: Source volume "vs0:zrto_cg_556844_511u_RW1" and destination volume "vs1:zrto_cg_556881_511w_DP1" with relationship UUID "55ab7942-03e5-11eb-ba5a-005056a7dc14" is in "out-of-sync" status due to the following reason: "Transfer failed."
....
.Solução:
Conclua as etapas a seguir para executar um failover forçado no local B.

. Desmapear todos os LUNs pertencentes ao grupo de consistência do Site B..
. Exclua a relação do grupo de consistência do SnapMirror usando a `force` opção.
. Digite o `snapmirror break` comando nos volumes constituintes do grupo de consistência para converter volumes de DP para R/W, para habilitar e/S do local B.
. Inicialize os nós do local A para criar uma relação rto zero do local B para o local A..
. Libere o grupo de consistência com `relationship-info-only` o no local A para reter o instantâneo comum e desmapear os LUNs pertencentes ao grupo de consistência.
. Converta volumes no local A de R/W para DP configurando uma relação de nível de volume usando a política de sincronização ou a política de sincronização.
. Emita o `snapmirror resync` para sincronizar as relações.
. Exclua os relacionamentos do SnapMirror com a política de sincronização no local A..
. Liberar as relações SnapMirror com a política de sincronização usando `relationship-info-only true` no local B..
. Crie uma relação de grupo de consistência do local B para o local A..
. Execute uma ressincronização do grupo de consistência no Site A e verifique se o grupo de consistência está em sincronia.
. Pode novamente hospedar caminhos de e/S LUN para restaurar todos os caminhos para os LUNs.


.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-break.html["quebra de espelho instantâneo"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-mediator-show.html["show do mediador snapmirror"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["ressincronização do snapmirror"^]

