---
sidebar: sidebar 
permalink: snapmirror-active-sync/cluster-config-task.html 
keywords: SM-BC, SMBC, cluster, peering, ONTAP, Mediator, ONTAP Cloud Mediator, initialize, snapmirror active sync 
summary: Ao usar o ONTAP Mediator ou o ONTAP Cloud Mediator com sincronização ativa do SnapMirror , você deve primeiro garantir que o cluster esteja configurado corretamente. 
---
= Configurar clusters ONTAP para sincronização ativa do SnapMirror
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A sincronização ativa do SnapMirror utiliza clusters pareados para proteger seus dados em caso de failover. Antes de configurar o ONTAP Mediator ou o ONTAP Cloud Mediator para a sincronização ativa do SnapMirror , você precisa primeiro garantir que o cluster esteja configurado corretamente.

.Antes de começar
Antes de configurar o ONTAP Mediator ou o ONTAP Cloud Mediator, você deve confirmar o seguinte:

. Existe um relacionamento de peering de cluster entre os clusters.
+

NOTE: O espaço IPspace padrão é exigido pela sincronização ativa do SnapMirror para relacionamentos de pares de cluster. Um espaço IPspace personalizado não é suportado.

+
link:../peering/create-cluster-relationship-93-later-task.html["Criando um relacionamento de cluster peer"]

. As SVMs são criadas em cada cluster.
+
link:../smb-config/create-svms-data-access-task.html["Criação de um SVM"]

. Existe um relacionamento de pares entre as SVMs em cada cluster.
+
link:../peering/create-intercluster-svm-peer-relationship-93-later-task.html["Criando uma relação de peering SVM"]

. Os volumes existem para seus LUNs.
+
link:../smb-config/create-volume-task.html["Criando um volume"]

. Pelo menos uma LIF SAN (FC ou iSCSI, conforme aplicável) para sua configuração SAN é criada em cada nó em ambos os clusters, ou pelo menos uma LIF NAS (NFS ou SMB, conforme aplicável) é criada em cada nó no cluster primário para replicação para o cluster secundário.
+
link:../san-admin/manage-lifs-all-san-protocols-concept.html["Considerações para LIFs em um ambiente de SAN de cluster"]

+
link:../networking/create_a_lif.html["Criando um LIF"]

+
link:../nfs-config/index.html["Saiba mais sobre a configuração do NFS"]

+
link:../smb-config/index.html["Saiba mais sobre a configuração do SMB"]

. Somente SAN: Os LUNs necessários são criados e mapeados para um igroup, que é usado para mapear os LUNs para o iniciador no host do aplicativo.
+
link:../san-admin/provision-storage.html["Crie LUNs e mapeie grupos"]

. O host da aplicação é verificado novamente para descobrir quaisquer novos LUNs ou volumes.

