---
sidebar: sidebar 
permalink: snapmirror-active-sync/convert-relationships-task.html 
keywords: SM-BC, SMBC, convert, SnapMirror synchronous, zero RPO, zero recovery time objective, zero RTO, existing, snapmirror active sync 
summary: Converta entre proteção simétrica e assimétrica em sua configuração de sincronização ativa do SnapMirror. 
---
= Converter tipo de relação de sincronização ativa do SnapMirror
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.15,1, você pode converter entre os tipos de proteção de sincronização ativa SnapMirror: De assimétrica a simétrica ativa ativa/ativa e vice-versa.



== Converter em um relacionamento ativo-ativo simétrico

Você pode converter uma relação de sincronização ativa do SnapMirror com proteção assíncrona para usar ativo-ativo simétrico.

.Antes de começar
* Ambos os clusters devem estar executando o ONTAP 9.15,1 ou posterior.
* Configurações ativo-ativo simétricas exigem a `AutomatedFailoverDuplex` política de proteção. Como alternativa, você pode xref:../data-protection/create-custom-replication-policy-concept.html[Crie uma política de SnapMirror personalizada] fornecer o `-type` is `automated-failover-duplex`.


[role="tabbed-block"]
====
.System Manager
--
.Passos para uma configuração uniforme
. Remova o igrop de destino:
+
.. No cluster de destino, navegue até **hosts** > **grupos de iniciadores SAN**.
.. Selecione o grupo com o relacionamento SnapMirror e, em seguida, **Excluir**.
.. Na caixa de diálogo, selecione a caixa **Unmap the Associated LUNs** (Anular mapeamento dos LUNs associados) e **Delete** (Excluir).


. Edite a relação de sincronização ativa do SnapMirror.
+
.. Navegue até **proteção** > **relacionamentos**.
.. Selecione o menu kabob ao lado do relacionamento que você deseja modificar e, em seguida, **Editar**.
.. Modifique a **Política de proteção** para AutomatedFailoverDuplex.
.. A seleção `AutoMatedFailoverDuplex` de solicita uma caixa de diálogo para modificar as configurações de proximidade do host. Para os iniciadores, selecione a opção apropriada para **Iniciador proximal a** e, em seguida, **Guardar**.
.. Selecione **Guardar**.


. No menu **proteção**, confirme a operação bem-sucedida quando a relação for exibida como `InSync`.


.Passos para uma configuração não uniforme
. Remova o igrop de destino:
+
.. No local secundário, navegue até **hosts** > **grupos de iniciadores SAN**.
.. Selecione o grupo com o relacionamento SnapMirror e, em seguida, **Excluir**.
.. Na caixa de diálogo, selecione a caixa **Unmap the Associated LUNs** (Anular mapeamento dos LUNs associados) e **Delete** (Excluir).


. Crie um novo grupo:
+
.. No menu **SAN Initiator Groups** no local de destino, selecione **Add**.
.. Forneça um ** Nome**, selecione **sistema operacional anfitrião** e, em seguida, escolha **Membros do Grupo Iniciador**.
.. Selecione **Guardar**.


. Mapeie o novo grupo para os LUNs de destino.
+
.. Navegue até **armazenamento** > **LUNs**.
.. Selecione todos os LUNs para mapear para o grupo.
.. Selecione **More** (mais) e depois **Map to Initiator Groups (mapa para grupos de iniciadores)**.


. Edite a relação de sincronização ativa do SnapMirror.
+
.. Navegue até **proteção** > **relacionamentos**.
.. Selecione o menu kabob ao lado do relacionamento que você deseja modificar e, em seguida, **Editar**.
.. Modifique a **Política de proteção** para AutomatedFailoverDuplex.
.. Selecionar AutoMatedFailoverDuplex inicia a opção para modificar as configurações de proximidade do host. Para os iniciadores, selecione a opção apropriada para **Iniciador proximal a** e, em seguida, **Guardar**.
.. Selecione **Guardar**.


. No menu **proteção**, confirme a operação bem-sucedida quando a relação for exibida como `InSync`.


--
.CLI
--
.Passos para uma configuração uniforme
. Modifique a política SnapMirror de `AutomatedFailover` para `AutomatedFailoverDuplex`:
+
`snapmirror modify -destination-path <destination_path> -policy AutomatedFailoverDuplex`

. A modificação da política aciona uma ressincronização. Aguarde até que a ressincronização seja concluída e confirme que a relação é `Insync`:
+
`snapmirror show -destination-path <destination_path>`

. Se os hosts existentes forem locais, o cluster primário, adicione o host ao segundo cluster e estabeleça conetividade com o respetivo acesso a cada cluster.
. No site secundário, exclua os mapas LUN nos grupos associados aos hosts remotos.
+

NOTE: Certifique-se de que o grupo não contenha mapas para LUNs não replicados.

+
`SiteB::> lun mapping delete -vserver <svm_name> -igroup <igroup> -path <>`

. No local principal, modifique a configuração do iniciador para os hosts existentes para definir o caminho proximal para os iniciadores no cluster local.
+
`SiteA::> igroup initiator add-proximal-vserver -vserver <svm_name> -initiator <host> -proximal-vserver <server>`

. Adicione um novo grupo e iniciador para os novos hosts e defina a proximidade do host para a afinidade do host para seu site local. Replicação do igroup para replicar a configuração e inverter a localidade do host no cluster remoto.
+
``
SiteA::> igroup modify -vserver vsA -igroup ig1 -replication-peer vsB
SiteA::> igroup initiator add-proximal-vserver -vserver vsA -initiator host2 -proximal-vserver vsB
``

. Descubra os caminhos nos hosts e verifique se os hosts têm um caminho Ativo/otimizado para o LUN de armazenamento a partir do cluster preferido
. Implante o aplicativo e distribua as cargas de trabalho da VM entre clusters.


.Passos para uma configuração não uniforme
. Modifique a política SnapMirror de `AutomatedFailover` para `AutomatedFailoverDuplex`:
+
`snapmirror modify -destination-path <destination_path> -policy AutomatedFailoverDuplex`

. A modificação da política aciona uma ressincronização. Aguarde até que a ressincronização seja concluída e confirme que a relação é `Insync`:
+
`snapmirror show -destination-path <destination_path>`

. Se os hosts existentes forem locais para o cluster primário, adicione o host ao segundo cluster e estabeleça conetividade com o respetivo acesso a cada cluster.
. No site secundário, exclua os mapas LUN nos grupos associados aos hosts remotos.
+

NOTE: Certifique-se de que o grupo não contenha mapas para LUNs não replicados.

+
`SiteB::> lun mapping delete -vserver <svm_name> -igroup <igroup> -path <>`

. No local principal, modifique a configuração do iniciador para os hosts existentes para definir o caminho proximal para os iniciadores no cluster local.
+
`SiteA::> igroup initiator add-proximal-vserver -vserver <svm_name> -initiator <host> -proximal-vserver <server>`

. No site secundário, adicione um novo grupo e iniciador para os novos hosts e defina a proximidade do host para a afinidade do host para seu site local. Mapeie os LUNs para o grupo.
+
``
SiteB::> igroup create -vserver <svm_name> -igroup <igroup>
SiteB::> igroup add -vserver <svm_name> -igroup  <igroup> -initiator <host_name>
SiteB::> lun mapping create -igroup  <igroup> -path <path_name>
``

. Descubra os caminhos nos hosts e verifique se os hosts têm um caminho Ativo/otimizado para o LUN de armazenamento a partir do cluster preferido
. Implante o aplicativo e distribua as cargas de trabalho da VM entre clusters.


--
====


== Converter de ativo-ativo simétrico para uma relação assimétrica

Se você configurou a proteção ativa/ativa simétrica, você pode converter a relação para proteção assimétrica usando a CLI do ONTAP.

.Passos
. Mova todos os workloads de VM para o host local para o cluster de origem.
. Remova a configuração do grupo para os hosts que não gerenciam as instâncias da VM, em seguida, modifique a configuração do grupo para encerrar a replicação do grupo.
+
`igroup modify -vserver <svm_name> -igroup <igroup> -replication-peer -`

. No local secundário, desmapeie os LUNs.
+
`SiteB::> lun mapping delete -vserver <svm_name> -igroup <igroup> -path <>`

. No site secundário, exclua a relação ativo-ativo simétrica.
+
`SiteB::> snapmirror delete -destination-path <destination_path>`

. No local principal, libere o relacionamento ativo-ativo simétrico.
`SiteA::> snapmirror release -destination-path <destination_path> -relationship-info-only true`
. A partir do site secundário, crie uma relação com o mesmo conjunto de volumes com a `AutomatedFailover` política para ressincronizar a relação.
+
``
SiteB::> snapmirror create -source-path <source_path> -destination-path <destination_path> -cg-item-mappings <source:@destination> -policy AutomatedFailover
SiteB::> snapmirror resync -destination-path vs1:/cg/cg1_dst -policy <policy_type>
``

+

NOTE: O grupo de consistência no site secundário precisa link:../consistency-groups/delete-task.html["a eliminar"] antes de recriar a relação. Os volumes de link:https://kb.netapp.com/onprem/ontap/dp/SnapMirror/How_to_change_a_volume_type_from_RW_to_DP["Tem de ser convertido para o tipo DP"^]destino . Para converter os volumes para DP, execute o `snapmirror resync` comando com uma não-`AutomatedFailover` política: `MirrorAndVault` `MirrorAllSnapshots` , Ou `Sync`.

. Confirme se o estado do espelho de relacionamento é `Snapmirrored` o Status do relacionamento é `Insync`.
+
`snapmirror show -destination-path _destination_path_`

. Redescubra os caminhos do anfitrião.

