---
sidebar: sidebar 
permalink: snapmirror-active-sync/index.html 
keywords: SM-BC, SMBC, failover, terms, benefits, snapmirror active sync, TR-4878 
summary: Use a sincronização ativa do SnapMirror para proteger aplicações com LUNs, possibilitando o failover de aplicações de forma transparente, garantindo a continuidade dos negócios em caso de desastre. 
---
= Saiba mais sobre a sincronização ativa do ONTAP SnapMirror
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O SnapMirror Active Sync, também conhecido como SnapMirror Business Continuity (SM-BC), permite que os serviços empresariais continuem funcionando em caso de falha completa do site.  Essa tecnologia permite que os aplicativos façam failover perfeitamente para uma cópia secundária, sem intervenção manual ou scripts personalizados.

O NetApp SnapMirror Active Sync (SM-as) foi projetado para ser uma proteção em nível de aplicativo mais granular, de menor custo e mais fácil de usar, com failover automático.  A sincronização ativa do SnapMirror permite que serviços empresariais de missão crítica continuem operando, mesmo durante uma falha completa do site.  Com a sincronização ativa do SnapMirror , agora você pode replicar de forma síncrona vários volumes de um aplicativo (adicionando-os a um grupo de consistência) entre sites em locais geograficamente dispersos.  Você pode fazer failover automaticamente para a cópia secundária em caso de interrupção da primária, permitindo assim a continuidade dos negócios para aplicativos de nível um.

Os regulamentos para instituições financeiras em alguns países exigem que as empresas sejam periodicamente atendidas por seus data centers secundários.  O SnapMirror Active Sync, com seus clusters de alta disponibilidade, permite essas trocas de data center para continuidade dos negócios.

Disponível a partir do ONTAP 9.9.1, a sincronização ativa do SnapMirror é suportada em clusters AFF e All-Flash SAN Array (ASA).  Os clusters primário e secundário devem ser do mesmo tipo: ASA, ASA r2 ou AFF.  A sincronização ativa do SnapMirror protege aplicativos com LUNs iSCSI ou FCP ou namespaces NVMe.

A sincronização ativa do SnapMirror suporta configurações simétricas e assimétricas.  O suporte para simétrico ativo/ativo foi introduzido no ONTAP 9.15.1.  A configuração simétrica ativa/ativa permite que ambas as cópias de um LUN protegido executem operações de E/S de leitura e gravação com replicação síncrona bidirecional, permitindo que cada cópia de LUN atenda a solicitações de E/S locais.


NOTE: A partir de julho de 2024, o conteúdo de relatórios técnicos publicados anteriormente como PDFs foi integrado à documentação do produto ONTAP. A documentação de sincronização ativa do ONTAP SnapMirror agora inclui conteúdo de _TR-4878: SnapMirror active Sync_.



== Benefícios

O SnapMirror ative Sync oferece os seguintes benefícios:

* Disponibilidade contínua para aplicações essenciais aos negócios.
* Capacidade de hospedar aplicações críticas alternadamente de locais primários e secundários.
* Gerenciamento simplificado de aplicações usando grupos de consistência para consistência dependente da ordem de gravação.
* Capacidade de testar failover em cada aplicação.
* Criação instantânea de clones espelhados sem afetar a disponibilidade da aplicação.
* Capacidade de implantar workloads protegidos e não protegidos no mesmo cluster do ONTAP.
* A identidade do LUN, do namespace NVMe, do subsistema NVMe ou da unidade de armazenamento permanece a mesma, de modo que o aplicativo os vê como um dispositivo virtual compartilhado.
* Capacidade de reutilizar clusters secundários com flexibilidade para criar clones instantâneos para uso da aplicação para fins de desenvolvimento/teste, UAT ou geração de relatórios, sem impactar a performance ou a disponibilidade da aplicação.


A sincronização ativa do SnapMirror permite proteger seus LUNs de dados ou namespaces NVMe, o que permite que os aplicativos realizem failover de forma transparente para fins de continuidade dos negócios em caso de desastre. Para mais informações, consulte link:use-cases-concept.html["Casos de uso"] .



== Conceitos-chave

A sincronização ativa do SnapMirror usa grupos de consistência para garantir que seus dados sejam replicados.  A sincronização ativa do SnapMirror usa o ONTAP Mediator ou, a partir do ONTAP 9.17.1, o Cloud Mediator para failover automatizado, garantindo que os dados sejam fornecidos em caso de um cenário de desastre. Ao planejar a implantação da sincronização ativa do SnapMirror , é importante entender os conceitos essenciais da sincronização ativa do SnapMirror e sua arquitetura.

.Assimetria e simetria
Em configurações simétricas ativas/ativas, ambos os sites podem acessar o armazenamento local para E/S ativas. A configuração simétrica ativa/ativa é otimizada para aplicativos em cluster, incluindo VMware vMSC, Windows Failover Cluster com SQL e Oracle RAC.

Em configurações ativas/ativas assimétricas, os dados no site secundário são enviados por proxy para um LUN, namespace ou unidade de armazenamento.

Para obter mais informações, xref:architecture-concept.html[Arquitetura de sincronização ativa do SnapMirror]consulte .

.Grupo de consistência
Para sistemas AFF e ASA, um link:../consistency-groups/index.html["grupo de consistência"] é uma coleção de volumes FlexVol que fornecem uma garantia de consistência para a carga de trabalho do aplicativo que deve ser protegida para a continuidade dos negócios. Em sistemas ASA r2, um grupo de consistência é uma coleção de unidades de armazenamento.

O objetivo de um grupo de consistência é capturar imagens instantâneas simultâneas de uma coleção de volumes ou unidades de armazenamento, garantindo, assim, cópias consistentes em caso de falhas da coleção em um determinado momento. Um grupo de consistência garante que todos os volumes de um conjunto de dados sejam desativados e, em seguida, capturados precisamente no mesmo momento. Isso fornece um ponto de restauração consistente em todos os volumes ou unidades de armazenamento que suportam o conjunto de dados. Um grupo de consistência, portanto, mantém a consistência da ordem de gravação dependente. Se você decidir proteger aplicativos para continuidade dos negócios, o grupo de volumes ou unidades de armazenamento correspondente a esse aplicativo deverá ser adicionado a um grupo de consistência para que uma relação de proteção de dados seja estabelecida entre um grupo de consistência de origem e um de destino. A consistência de origem e de destino deve conter o mesmo número e tipo de volumes.

.Constituinte
Um volume individual, LUN ou namespace NVMe (começando com ONTAP 9.17.1) que faz parte do grupo de consistência protegido no relacionamento de sincronização ativa do SnapMirror .

.ONTAP Mediador
O link:../mediator/index.html["ONTAP Mediador"] Recebe informações de integridade sobre clusters e nós ONTAP pareados, orquestrando entre eles e determinando se cada nó/cluster está íntegro e em execução. O Mediador ONTAP fornece informações de integridade sobre:

* Clusters peer ONTAP
* Nós de cluster de peer ONTAP
* Grupos de consistência (que definem as unidades de failover em uma relação de sincronização ativa do SnapMirror); para cada grupo de consistência, as seguintes informações são fornecidas:
+
** Estado de replicação: Não inicializado, em Sincronizar ou fora de Sincronizar
** Qual cluster hospeda a cópia primária
** Contexto de operação (usado para failover planejado)




Com essas informações de integridade do ONTAP Mediator, os clusters podem diferenciar entre tipos distintos de falhas e determinar se devem executar um failover automatizado. O Mediador ONTAP é uma das três partes no quorum de sincronização ativa do SnapMirror, juntamente com os clusters do ONTAP (primário e secundário). Para chegar a um consenso, pelo menos duas partes no quórum devem concordar com uma determinada operação.


NOTE: A partir do ONTAP 9.15.1, o Gerenciador do sistema exibe o status da relação de sincronização ativa do SnapMirror de qualquer cluster. Você também pode monitorar o status do Mediador ONTAP de qualquer cluster no Gerenciador de sistema. Em versões anteriores do ONTAP, o Gerenciador de sistema exibe o status das relações de sincronização ativa do SnapMirror a partir do cluster de origem.

.Mediador de Nuvem ONTAP
O ONTAP Cloud Mediator está disponível a partir do ONTAP 9.17.1. O ONTAP Cloud Mediator fornece os mesmos serviços que o ONTAP Mediator, exceto que ele é hospedado na nuvem usando o NetApp Console.

.Failover planejado
Uma operação manual para alterar as funções das cópias em uma relação de sincronização ativa do SnapMirror. Os locais primários se tornam secundários, e o secundário se torna o primário.

.Failover não planejado automático (AUFO)
Uma operação automática para executar um failover para a cópia espelhada. A operação requer a assistência do Mediador ONTAP para detetar que a cópia primária não está disponível.

.Viés primário e primário
A sincronização ativa do SnapMirror usa um princípio primário que dá preferência à cópia primária para servir e/S no caso de uma partição de rede.

Primary-bias é uma implementação de quórum especial que melhora a disponibilidade de um conjunto de dados protegido por sincronização ativa do SnapMirror. Se a cópia primária estiver disponível, o viés primário entrará em vigor quando o Mediador ONTAP não estiver acessível a partir de ambos os clusters.

Primary-first e Primary bias são suportadas na sincronização ativa do SnapMirror a partir do ONTAP 9.15,1. As cópias primárias são designadas no System Manager e são enviadas com a API REST e CLI.

.Fora de sincronização (OOS)
Quando a e/S do aplicativo não estiver replicando para o sistema de storage secundário, ela será reportada como ** fora de sincronia**. Um status fora de sincronia significa que os volumes secundários não são sincronizados com o primário (origem) e que a replicação do SnapMirror não está ocorrendo.

Se o estado do espelho for `Snapmirrored` , isso indica que um relacionamento SnapMirror foi estabelecido e a transferência de dados foi concluída, o que significa que o volume de destino está atualizado com o volume de origem.

A sincronização ativa do SnapMirror suporta ressincronização automática, permitindo que as cópias voltem a um estado InSync.

A partir do ONTAP 9.15,1, a sincronização ativa do SnapMirror suporta link:interoperability-reference.html#fan-out-configurations["reconfiguração automática em configurações de fan-out"].

.Configuração uniforme e não uniforme
* **O acesso uniforme ao host** significa que os hosts de ambos os locais estão conetados a todos os caminhos para os clusters de armazenamento em ambos os locais. Os caminhos entre locais são estendidos por distâncias.
* **Acesso não uniforme ao host** significa que os hosts em cada local são conetados apenas ao cluster no mesmo local. Caminhos entre locais e caminhos esticados não estão conetados.



NOTE: O acesso uniforme de host é compatível com qualquer implantação de sincronização ativa do SnapMirror. O acesso de host não uniforme só é compatível com implantações ativas/ativas simétricas.

.RPO zero
RPO significa objetivo do ponto de restauração, que é a quantidade de perda de dados considerada aceitável durante um determinado período de tempo. Zero RPO significa que nenhuma perda de dados é aceitável.

.Rto zero
Rto representa o objetivo de tempo de recuperação, que é o tempo que é considerado aceitável para um aplicativo retornar às operações normais sem interrupções, após uma interrupção, falha ou outro evento de perda de dados. Zero rto significa que nenhuma quantidade de tempo de inatividade é aceitável.



== Suporte à configuração de sincronização ativa do SnapMirror pela versão ONTAP

O suporte para sincronização ativa do SnapMirror varia dependendo da sua versão do ONTAP:

[cols="4*"]
|===


| Versão de ONTAP | Clusters suportados | Protocolos compatíveis | Configurações compatíveis 


| 9.17.1 e posterior  a| 
* AFF
* ASA
* Série C.
* ASA r2

 a| 
* ISCSI
* FC
* NVMe para cargas de trabalho VMware

 a| 
* Assimétrico ativo/ativo



NOTE: Ativo-ativo não é compatível com ASA r2 e NVMe. Para obter mais informações sobre a compatibilidade com NVMe, consulte link:../nvme/support-limitations.html["Configuração, suporte e limitações do NVMe"].

* Ativo-ativo simétrico




| 9.16.1 e mais tarde  a| 
* AFF
* ASA
* Série C.
* ASA r2

 a| 
* ISCSI
* FC

 a| 
* Assimétrico ativo/ativo
* Configurações simétricas ativo-ativo suportam clusters de 4 nós para 4 nós no ONTAP 9.16.1 e versões posteriores. Para ASA r2, apenas clusters de 2 nós são suportados.




| 9.15.1 e posterior  a| 
* AFF
* ASA
* Série C.

 a| 
* ISCSI
* FC

 a| 
* Assimétrico ativo/ativo
* Configurações simétricas ativo-ativo suportam clusters de 2 nós no ONTAP 9.15.1. Clusters de 2 nós para 2 nós e de 4 nós para 4 nós são suportados no ONTAP 9.16.1 e versões posteriores.




| 9.9.1 e mais tarde  a| 
* AFF
* ASA
* Série C.

 a| 
* ISCSI
* FC

 a| 
Assimétrico ativo/ativo

|===
Os clusters primários e secundários devem ser do mesmo tipo: link:../san-admin/learn-about-asa.html["ASA"] , link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA r2"^] , ou AFF.
