---
sidebar: sidebar 
permalink: snapmirror-active-sync/limits-reference.html 
keywords: SM-BC, SMBC, restrictions, consistency group, endpoint limits, solaris, aix, hp-ux, fanout, snapmirror active sync 
summary: Existem várias restrições e limitações adicionais ao usar a sincronização ativa do SnapMirror. 
---
= Limites de objeto para sincronização ativa do ONTAP SnapMirror
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ao se preparar para usar a sincronização ativa do SnapMirror, esteja ciente dos seguintes limites de objeto.



[[consistency-groups-in-a-cluster]]
== Grupos de consistência em um cluster

Os limites do grupo de consistência para um cluster com uma configuração SAN de sincronização ativa SnapMirror são calculados com base em relacionamentos e dependem da versão do ONTAP utilizada. Os limites são independentes da plataforma.

|===
| Versão de ONTAP | Número máximo de relacionamentos 


| ONTAP 9.11,1 e posterior | 50* 


| ONTAP 9.10,1 | 20 


| ONTAP 9.9,1 | 5 
|===
A partir do ONTAP 9.16.1, o SnapMirror active Sync suporta clusters de quatro nós em configurações ativo-ativo simétricas. Em um cluster de quatro nós, são suportados 100 grupos de consistência.



[[volumes-per-consistency-group]]
== Volumes por grupo de consistência

O número máximo de volumes por grupo de consistência com SnapMirror active sync para configurações SAN é independente da plataforma.

|===
| Versão de ONTAP | Número máximo de volumes suportados em uma relação de grupo de consistência 


| ONTAP 9.15,1 e posterior | 80 


| ONTAP 9.10,1-9.14.1 | 16 


| ONTAP 9.9,1 | 12 
|===


[[volumes]]
== Volumes

Os limites de volume em SnapMirror active sync para configurações SAN são calculados com base no número de endpoints, não no número de relacionamentos. Um grupo de consistência com 12 volumes contribui com 12 endpoints tanto no cluster primário quanto no cluster secundário. Tanto SnapMirror active sync quanto os relacionamentos síncronos de SnapMirror contribuem para o número total de endpoints.


IMPORTANT: Esses limites se aplicam aos sistemas FAS, AFF e ASA . Se você tiver um sistema ASA r2 (ASA A1K, ASA A90, ASA A70, ASA A50, ASA A30 ou ASA A20), consulte link:https://docs.netapp.com/us-en/asa-r2/data-protection/manage-consistency-groups.html["Documentação do ASA r2"^] .

Os pontos finais máximos por plataforma estão incluídos na tabela a seguir.

|===
| Plataforma 3+| Pontos de extremidade por HA para sincronização ativa do SnapMirror 3+| Pontos de extremidade de sincronização total e de sincronização ativa do SnapMirror por HA 


|  | ONTAP 9.11,1 e posterior | ONTAP 9.10,1 | ONTAP 9.9,1 | ONTAP 9.11,1 e posterior | ONTAP 9.10,1 | ONTAP 9.9,1 


| AFF | 400* | 200 | 60 | 400 | 200 | 80 


| ASA | 400* | 200 | 60 | 400 | 200 | 80 
|===
A partir do ONTAP 9.16.1, o SnapMirror active Sync suporta clusters de quatro nós em configurações ativo-ativo simétricas. O limite total para um cluster de quatro nós é de 800 pontos de extremidade.



[[san-object-limits]]
== Limites de objetos SAN

Os limites de objetos SAN estão incluídos na tabela a seguir. Os limites se aplicam independentemente da plataforma.

|===
| Objeto em um relacionamento de sincronização ativa do SnapMirror | Contar 


| LUNs por volume  a| 
* 256 (ONTAP 9.9.1 - ONTAP 9.15.0)
* 512 (ONTAP 9.15.1 e posterior)




| Número de LUNs, namespaces ou unidades de armazenamento exclusivos por solução de sincronização ativa SnapMirror 2 x 2 | 4.096 


| Número de LUNs, namespaces ou unidades de armazenamento exclusivos por solução de sincronização ativa SnapMirror 4 x 4 (disponível a partir do ONTAP 9.16.1) | 6.144 


| LIFs por SVM (com pelo menos um volume em um relacionamento de sincronização ativa do SnapMirror ) | 256 


| LIFs entre clusters por nó | 4 


| LIFs inter-cluster por cluster | 8 
|===


[[nas-object-limits]]
== Limites de objetos NAS

A partir do ONTAP 9.19.1, SnapMirror active sync oferece suporte a protocolos NAS. Os limites de objetos NAS estão incluídos na tabela a seguir.

|===
| Máximo de objetos em um relacionamento de sincronização ativo do SnapMirror | Contar 


| Número de unidades de failover por par de HA | 50 


| Número de SVMs NAS por par de HA | 50 


| Número de volumes por SVM | 80 


| Número de grupos de consistência de aplicação por par de HA | Não suportado 


| Número de volumes por grupo de consistência | Não aplicável 


| Número de volumes por par de HA | 400 


| Pares de clusters gerenciáveis por um único mediador | 10 


| Número de nós em um cluster  a| 
2 (somente clusters AFF)

4 (somente para clusters AFX)

|===


[[nvme-object-limits]]
== Limites de objetos NVMe

A partir do ONTAP 9.17.1, a sincronização ativa do SnapMirror oferece suporte ao protocolo NVMe. Os limites de objetos NVMe estão incluídos na tabela a seguir.

|===
| Máximo de objetos em um relacionamento de sincronização ativo do SnapMirror | Contar 


| Número de mapas de namespace por nó | 4K 


| Tamanho do cluster | 2 nós 


| Número de grupos de consistência por par de HA | 50 


| Número de volumes em um único grupo de consistência de sincronização ativa NVMe SnapMirror | 80 


| Número de volumes em um par HA | 400 


| Subsistemas NVMe por grupo de consistência | 16 


| Mapas de namespace por grupo de consistência | 256 
|===
.Informações relacionadas
* link:https://hwu.netapp.com/["Hardware Universe"^]
* link:../consistency-groups/limits.html["Limites do grupo de consistência"]

