---
sidebar: sidebar 
permalink: snapmirror-active-sync/mediator-troubleshoot-task.html 
keywords: troubleshooting, SM-BC, SMBC, Mediator, Cloud Mediator, quorum, quorum status, failover, network, snapmirror active sync 
summary: Depois de executar o comando SnapMirror failover start, a saída para o comando SnapMirror failover show exibe uma mensagem indicando que o Mediador não está configurado. 
---
= ONTAP Mediator ou ONTAP Cloud Mediator não acessível ou o status de quórum do Mediador é falso
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Use as seguintes informações se o ONTAP Mediator ou o ONTAP Cloud Mediator não estiver acessível ou se o status de quorum do Mediador for falso.

.Problema:
Após executar o  `snapmirror failover start` comando, a saída para o  `snapmirror failover show` O comando exibe uma mensagem indicando que o ONTAP Mediator ou o ONTAP Cloud Mediator não está configurado.

Ver link:mediator-install-task.html["Configure o Mediador e os clusters do ONTAP para a sincronização ativa do SnapMirror"] ou link:cloud-mediator-config-task.html["Configurar o ONTAP Cloud Mediator para sincronização ativa do SnapMirror"] .

....
Cluster1::> snapmirror failover show
Source Destination Error
Path Path Type Status start-time end-time Reason
-------- ----------- -------- --------- ---------- ---------- ----------
vs0:/cg/cg vs1:/cg/cg planned failed 10/1/2020 10/1/2020 SnapMirror failover cannot start because the source-side precheck failed. reason: Mediator not configured.
05:50:42 05:50:43
....
.Causa:
O mediador não está configurado ou há problemas de conetividade de rede.

.Solução:
Se o Mediador do ONTAP não estiver configurado, você deverá configurar o Mediador do ONTAP antes de estabelecer uma relação de sincronização ativa do SnapMirror. Corrija quaisquer problemas de conetividade de rede. Certifique-se de que o Mediador esteja conetado e o status do quórum seja verdadeiro no local de origem e destino usando o comando SnapMirror Mediator show. Para obter mais informações, link:mediator-install-task.html["Configure o Mediador ONTAP"]consulte .

....
cluster::> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
10.234.10.143    cluster2         connected         true
....