---
sidebar: sidebar 
permalink: snapmirror-active-sync/prerequisites-reference.html 
keywords: SM-BC, SMBC, prerequisites, planning, software, hardware, licensing, protocols, network, snapmirror active sync 
summary: Existem vários pré-requisitos que você deve considerar como parte do Planejamento de uma implantação de solução de sincronização ativa do SnapMirror. 
---
= Pré-requisitos para a sincronização ativa do SnapMirror no ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ao Planejar sua implantação de sincronização ativa do SnapMirror, verifique se você atendeu aos vários requisitos de hardware, software e configuração do sistema.



== Hardware

A tabela a seguir descreve as configurações de cluster do NetApp compatíveis.

[cols="25,25,25,25"]
|===


| Tipo de cluster | Modelos suportados | Recursos suportados | Nós com suporte 


 a| 
AFF
 a| 
Série a, série C.
 a| 
Duplex de failover automatizado (ativo/ativo simétrico), failover automatizado (ativo/ativo assimétrico)
 a| 
Cluster de dois nós ou quatro nós 1



 a| 
Todos os hotéis em San Array (ASA)
 a| 
Série a, série C.
 a| 
Duplex de failover automatizado (Symmetric AA), failover automatizado (Asymmetric AA)
 a| 
Cluster de dois nós ou quatro nós 1



 a| 
ASA r2
 a| 
-
 a| 
Duplex de failover automatizado (Symmetric AA)
 a| 
Clusters de dois nós de alta disponibilidade (HA)

|===
. O suporte para clusters de quatro nós está disponível a partir do ONTAP 9.16.1 e requer AA simétrico.


A tabela abaixo descreve a capacidade de replicação entre tipos de cluster.

[cols="33,33,33"]
|===


| Tipo de cluster 1 | Tipo de cluster 2 | Replicação compatível? 


 a| 
Série A.
 a| 
Série C.
 a| 
Sim



 a| 
AFF
 a| 
ASA
 a| 
Não



 a| 
ASA 1
 a| 
ASA r2
 a| 
Não

|===
. Para obter mais informações sobre os tipos de cluster compatíveis com o ASA, link:../asa/support-limitations.html["Limites de configuração e suporte do All-Flash SAN Array"]consulte .




== Software

* ONTAP 9.9,1 ou posterior
* ONTAP Mediador 1,2 ou posterior
* Um servidor Linux ou máquina virtual para o ONTAP Mediator executando um dos seguintes:


[cols="30,70"]
|===


| ONTAP versão mediadora | Versões Linux suportadas 


 a| 
1,9
 a| 
* Red Hat Enterprise Linux
+
** Compatível: 8,4, 8,5, 8,6, 8,7, 8,9, 9,1 e 9,3 1
** Recomendado: 8,8, 8,10, 9,0, 9,2, 9,4 e 9,5


* Rocky Linux 8 e 9




 a| 
1,8
 a| 
* Red Hat Enterprise Linux: 8,4, 8,5, 8,6, 8,7, 8,8, 8,9, 8,10, 9,0, 9,1, 9,2, 9,3 e 9,4
* Rocky Linux 8 e 9




 a| 
1,7
 a| 
* Red Hat Enterprise Linux: 8,4, 8,5, 8,6, 8,7, 8,8, 8,9, 9,0, 9,1, 9,2 e 9,3
* Rocky Linux 8 e 9




 a| 
1,6
 a| 
* Red Hat Enterprise Linux: 8,4, 8,5, 8,6, 8,7, 8,8, 9,0, 9,1, 9,2
* Rocky Linux 8 e 9




 a| 
1,5
 a| 
* Red Hat Enterprise Linux: 7,6, 7,7, 7,8, 7,9, 8,0, 8,1, 8,2, 8,3, 8,4, 8,5
* CentOS: 7,6, 7,7, 7,8, 7,9




 a| 
1,4
 a| 
* Red Hat Enterprise Linux: 7,6, 7,7, 7,8, 7,9, 8,0, 8,1, 8,2, 8,3, 8,4, 8,5
* CentOS: 7,6, 7,7, 7,8, 7,9




 a| 
1,3
 a| 
* Red Hat Enterprise Linux: 7,6, 7,7, 7,8, 7,9, 8,0, 8,1, 8,2, 8,3
* CentOS: 7,6, 7,7, 7,8, 7,9




 a| 
1,2
 a| 
* Red Hat Enterprise Linux: 7,6, 7,7, 7,8, 7,9, 8,0, 8,1
* CentOS: 7,6, 7,7, 7,8, 7,9


|===
. Compatível significa que o RHEL não suporta mais esta versão, mas o ONTAP Mediator ainda pode ser instalado.




== Licenciamento

* A licença síncrona do SnapMirror deve ser aplicada em ambos os clusters.
* A licença do SnapMirror deve ser aplicada em ambos os clusters.
+

NOTE: Se os sistemas de storage da ONTAP tiverem sido adquiridos antes de junho de 2019, consulte link:https://mysupport.netapp.com/site/systems/master-license-keys["Chaves de licença principal do NetApp ONTAP"^] para obter a licença síncrona SnapMirror necessária.





== Ambiente de rede

* O tempo de ida e volta (RTT) de latência entre clusters deve ser inferior a 10 milissegundos.
* A partir do ONTAP 9.14,1, link:https://kb.netapp.com/onprem/ontap/da/SAN/What_are_SCSI_Reservations_and_SCSI_Persistent_Reservations["Reservas persistentes SCSI-3"] são suportados com a sincronização ativa do SnapMirror.




== Protocolos compatíveis

* Somente protocolos SAN são compatíveis (não NFS/SMB).
* Apenas são suportados protocolos Fibre Channel e iSCSI.
* O espaço IPspace padrão é exigido pela sincronização ativa do SnapMirror para relacionamentos de pares de cluster. IPspace personalizado não é suportado.




== Estilo de segurança NTFS

O estilo de segurança NTFS é *não* suportado em volumes de sincronização ativos do SnapMirror.



== ONTAP Mediador

* O ONTAP Mediator deve ser provisionado externamente e anexado ao ONTAP para failover de aplicativo transparente.
* Para ser totalmente funcional e permitir failover automático não planejado, o Mediador ONTAP externo deve ser provisionado e configurado com clusters ONTAP.
* O ONTAP Mediator deve ser instalado em um terceiro domínio de falha, separado dos dois clusters ONTAP.
* Ao instalar o ONTAP Mediator, você deve substituir o certificado autoassinado por um certificado válido assinado por uma CA confiável.
* Para obter mais informações sobre o ONTAP Mediator, consulte link:../mediator/index.html["Preparar para instalar o ONTAP Mediator"] .




== Outros pré-requisitos

* As relações de sincronização ativa do SnapMirror não são compatíveis com volumes de destino de leitura e gravação. Antes de usar um volume de leitura e gravação, você deve convertê-lo em um volume DP criando uma relação de SnapMirror em nível de volume e excluindo a relação. Para obter detalhes, link:convert-active-sync-task.html["Converta relações SnapMirror existentes para a sincronização ativa do SnapMirror"]consulte .
* As VMs de armazenamento que usam a sincronização ativa do SnapMirror não podem ser Unidas ao ative Directory como um cliente computado.




== Mais informações

* link:https://hwu.netapp.com/["Hardware Universe"^]
* link:../mediator/mediator-overview-concept.html["Visão geral do Mediador ONTAP"^]

