---
sidebar: sidebar 
permalink: snapmirror-active-sync/volume-move-stuck-task.html 
keywords: SM-BC, SMBC, volume move, troubleshooting, primary down, snapmirror active sync 
summary: Você pode remover a proteção síncrona de rto SnapMirror zero e excluir a configuração da relação de sincronização ativa do SnapMirror. 
---
= A operação de movimentação de volume trava quando o ONTAP primário está inativo
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Use as seguintes informações se uma operação de movimentação de volume ficar travada indefinidamente no estado de transição adiada quando o site principal estiver inativo em um relacionamento de sincronização ativa do SnapMirror .

.Problema:
Uma operação de movimentação de volume fica presa indefinidamente no estado de transição adiada quando o local principal está inativo em uma relação de sincronização ativa do SnapMirror. Quando o local principal está inativo, o local secundário executa um failover não planejado automático (AUFO). Quando uma operação de movimentação de volume está em andamento quando o AUFO é acionado, o movimento de volume fica preso.

.Solução:
Abortar a instância de movimentação de volume que está emperrada e reiniciar a operação de movimentação de volume.
