---
permalink: smb-hyper-v-sql/determine-statistics-objects-counters-task.html 
sidebar: sidebar 
keywords: determine, statistics, objects, counters, cifs, smb, audit, branchcache, hash, monitor, performance 
summary: Antes de obter informações sobre as estatísticas de hash CIFS, SMB, auditoria e BranchCache e monitorar o desempenho, você deve saber quais objetos e contadores estão disponíveis a partir dos quais você pode obter dados. 
---
= Determine quais objetos e contadores de estatísticas estão disponíveis
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de obter informações sobre as estatísticas de hash CIFS, SMB, auditoria e BranchCache e monitorar o desempenho, você deve saber quais objetos e contadores estão disponíveis a partir dos quais você pode obter dados.

.Passos
. Defina o nível de privilégio como avançado:
+
`*set -privilege advanced*`

. Execute uma das seguintes ações:
+
|===
| Se você quiser determinar... | Digite... 


 a| 
Quais objetos estão disponíveis
 a| 
`*statistics catalog object show*`



 a| 
Objetos específicos que estão disponíveis
 a| 
`*statistics catalog object show object _object_name_*`



 a| 
Quais contadores estão disponíveis
 a| 
`*statistics catalog counter show object _object_name_*`

|===
+
Consulte as páginas man para obter mais informações sobre quais objetos e contadores estão disponíveis.

. Voltar ao nível de privilégio de administrador:
+
`*set -privilege admin*`



.Exemplos
O comando a seguir exibe descrições de objetos estatísticos selecionados relacionados ao acesso CIFS e SMB no cluster, como visto no nível avançado de privilégio:

[listing]
----
cluster1::> set -privilege advanced

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by support personnel.
Do you want to continue? {y|n}: y

cluster1::*> statistics catalog object show -object audit
    audit_ng                    CM object for exporting audit_ng performance counters

cluster1::*> statistics catalog object show -object cifs
    cifs                        The CIFS object reports activity of the
                                Common Internet File System protocol
                                ...

cluster1::*> statistics catalog object show -object nblade_cifs
    nblade_cifs                 The Common Internet File System (CIFS)
                                protocol is an implementation of the Server
                                ...

cluster1::*> statistics catalog object show -object smb1
    smb1                        These counters report activity from the SMB
                                revision of the protocol. For information
                                ...

cluster1::*> statistics catalog object show -object smb2
    smb2                        These counters report activity from the
                                SMB2/SMB3 revision of the protocol. For
                                ...

cluster1::*> statistics catalog object show -object hashd
    hashd                       The hashd object provides counters to measure
                                the performance of the BranchCache hash daemon.
cluster1::*> set -privilege admin
----
O comando a seguir exibe informações sobre alguns dos contadores para o `cifs` objeto, como visto no nível de privilégio avançado:

[NOTE]
====
Este exemplo não exibe todos os contadores disponíveis para o `cifs` objeto; a saída é truncada.

====
[listing]
----
cluster1::> set -privilege advanced

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by support personnel.
Do you want to continue? {y|n}: y

cluster1::*> statistics catalog counter show -object cifs

Object: cifs
    Counter                     Description
    --------------------------- ----------------------------------------------
    active_searches             Number of active searches over SMB and SMB2
    auth_reject_too_many        Authentication refused after too many
                                requests were made in rapid succession
    avg_directory_depth         Average number of directories crossed by SMB
                                and SMB2 path-based commands
    ...                         ...

cluster2::> statistics start -object client -sample-id
Object: client
    Counter                                                     Value
    -------------------------------- --------------------------------
    cifs_ops                                                        0
    cifs_read_ops                                                   0
    cifs_read_recv_ops                                              0
    cifs_read_recv_size                                            0B
    cifs_read_size                                                 0B
    cifs_write_ops                                                  0
    cifs_write_recv_ops                                             0
    cifs_write_recv_size                                           0B
    cifs_write_size                                                0B
    instance_name                             vserver_1:10.72.205.179
    instance_uuid                                     2:10.72.205.179
    local_ops                                                       0
    mount_ops                                                       0


[...]
----