---
permalink: smb-hyper-v-sql/enable-disable-vss-shadow-copies-backups-task.html 
sidebar: sidebar 
keywords: enable, disable, vss, aware, backup, hyper, v, virtual, machine, files, smb, shares, shadow, copy 
summary: Se você usar um aplicativo de backup com reconhecimento VSS para fazer backup de arquivos de máquina virtual Hyper-V armazenados em compartilhamentos SMB, a cópia de sombra VSS deve estar habilitada. Você pode desativar a cópia de sombra do VSS se não usar aplicativos de backup com reconhecimento VSS. O padrão é ativar a cópia de sombra VSS. 
---
= Ative ou desative cópias de sombra VSS para backups Hyper-V em SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você usar um aplicativo de backup com reconhecimento VSS para fazer backup de arquivos de máquina virtual Hyper-V armazenados em compartilhamentos SMB, a cópia de sombra VSS deve estar habilitada. Você pode desativar a cópia de sombra do VSS se não usar aplicativos de backup com reconhecimento VSS. O padrão é ativar a cópia de sombra VSS.

.Sobre esta tarefa
Você pode ativar ou desativar cópias de sombra VSS a qualquer momento.

.Passos
. Defina o nível de privilégio como avançado:
+
`*set -privilege advanced*`

. Execute uma das seguintes ações:
+
|===
| Se você quiser que cópias de sombra VSS sejam... | Digite o comando... 


 a| 
Ativado
 a| 
`*vserver cifs options modify -vserver _vserver_name_ -shadowcopy-enabled true*`



 a| 
Desativado
 a| 
`*vserver cifs options modify -vserver _vserver_name_ -shadowcopy-enabled false*`

|===
. Voltar ao nível de privilégio de administrador:
+
`*set -privilege admin*`



.Exemplo
Os comandos a seguir habilitam cópias de sombra do VSS no SVM VS1:

[listing]
----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options modify -vserver vs1 -shadowcopy-enabled true

cluster1::*> set -privilege admin
----