---
permalink: smb-hyper-v-sql/health-monitoring-nondisruptive-operation-concept.html 
sidebar: sidebar 
keywords: health, monitoring, nondisruptive, operation, status, healthy, ndo, hyper, v, sql, server, recovery, cluster, system 
summary: 'O monitoramento de integridade fornece informações sobre o status de integridade do sistema em todo o cluster. O monitor de integridade monitora as configurações Hyper-V e SQL Server em SMB para garantir operações ininterruptas (NDOs) para os servidores de aplicações. Se o estado estiver degradado, pode visualizar detalhes sobre o problema, incluindo a causa provável e as ações de recuperação recomendadas.' 
---
= Use o monitoramento de integridade para determinar se o status de operação sem interrupções está íntegro
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O monitoramento de integridade fornece informações sobre o status de integridade do sistema em todo o cluster. O monitor de integridade monitora as configurações Hyper-V e SQL Server em SMB para garantir operações ininterruptas (NDOs) para os servidores de aplicações. Se o estado estiver degradado, pode visualizar detalhes sobre o problema, incluindo a causa provável e as ações de recuperação recomendadas.

Existem vários monitores de saúde. O ONTAP monitora a integridade e a integridade geral do sistema para monitores de integridade individuais. O monitor de integridade da conetividade do nó contém o subsistema CIFS-NDO. O monitor tem um conjunto de políticas de integridade que acionam alertas se certas condições físicas podem causar interrupções e, se houver uma condição disruptiva, gera alertas e fornece informações sobre ações corretivas. Para configurações NDO sobre SMB, alertas são gerados para as duas condições a seguir:

|===
| ID de alerta | Gravidade | Condição 


 a| 
`*HaNotReadyCifsNdo_Alert*`
 a| 
Maior
 a| 
Um ou mais arquivos hospedados por um volume em um agregado no nó foram abertos por meio de um compartilhamento SMB continuamente disponível com a promessa de persistência em caso de falha. No entanto, o relacionamento de HA com o parceiro não está configurado ou não está íntegro.



 a| 
`*NoStandbyLifCifsNdo_Alert*`
 a| 
Menor
 a| 
A máquina virtual de storage (SVM) está fornecendo dados ativamente sobre SMB por meio de um nó e há arquivos SMB abertos persistentemente por compartilhamentos disponíveis continuamente. No entanto, seu nó de parceiro não expõe LIFs de dados ativos para o SVM.

|===