---
permalink: smb-hyper-v-sql/licensing-requirements-concept.html 
sidebar: sidebar 
keywords: ontap, license, requirement, nondisruptive, hyper, v, smb, sql, server 
summary: Você precisa estar ciente de certos requisitos de licenciamento e ONTAP ao criar soluções SQL Server ou Hyper-V em SMB para operações ininterruptas em SVMs. 
---
= Requisitos de ONTAP e licenciamento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você precisa estar ciente de certos requisitos de licenciamento e ONTAP ao criar soluções SQL Server ou Hyper-V em SMB para operações ininterruptas em SVMs.



== Requisitos de versão do ONTAP

* Hyper-V em SMB
+
O ONTAP é compatível com operações ininterruptas por compartilhamentos SMB para Hyper-V executados no Windows 2012 ou posterior.

* SQL Server sobre SMB
+
O ONTAP é compatível com operações ininterruptas por compartilhamentos SMB para SQL Server 2012 ou posterior executados no Windows 2012 ou posterior.



Para obter as informações mais recentes sobre versões com suporte do ONTAP, Windows Server e SQL Server para operações ininterruptas em compartilhamentos SMB, consulte a Matriz de interoperabilidade.

https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^]



== Requisitos de licenciamento

São necessárias as seguintes licenças:

* CIFS
* FlexClone (somente para Hyper-V em SMB)
+
Esta licença é necessária se o VSS remoto for usado para backups. O serviço de cópia de sombra usa o FlexClone para criar cópias pontuais de arquivos que são então usados ao criar um backup.

+
Uma licença do FlexClone é opcional se você usar um método de backup que não use o VSS remoto.



A licença FlexClone está incluída no link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"]. Se não tiver o ONTAP One, deverá link:../system-admin/manage-license-task.html["verifique se as licenças necessárias estão instaladas"], e, se necessáriolink:../system-admin/install-license-task.html["instale-os"], .
