---
permalink: smb-hyper-v-sql/odx-copy-offload-requirements-concept.html 
sidebar: sidebar 
keywords: odx, copy, offload, requirements, sql, server, hyper, v, smb, virtual 
summary: A descarga de cópia ODX deve ser ativada se você quiser migrar arquivos de máquina virtual ou exportar e importar arquivos de banco de dados diretamente da origem para o local de armazenamento de destino sem enviar dados através dos servidores de aplicativos. Há certos requisitos que você deve entender sobre o uso de descarga de cópia ODX com soluções SQL Server e Hyper-V sobre SMB. 
---
= Requisitos de descarga de cópia ODX para SQL Server e Hyper-V sobre SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A descarga de cópia ODX deve ser ativada se você quiser migrar arquivos de máquina virtual ou exportar e importar arquivos de banco de dados diretamente da origem para o local de armazenamento de destino sem enviar dados através dos servidores de aplicativos. Há certos requisitos que você deve entender sobre o uso de descarga de cópia ODX com soluções SQL Server e Hyper-V sobre SMB.

O uso de descarga de cópia ODX proporciona um benefício significativo de desempenho. Esta opção de servidor CIFS está ativada por predefinição.

* O SMB 3,0 deve estar habilitado para usar a descarga de cópia ODX.
* Os volumes de origem devem ter no mínimo 1,25 GB.
* A deduplicação deve ser habilitada em volumes usados com descarga de cópia.
* Se você usar volumes compatados, o tipo de compactação deve ser adaptável e somente o tamanho do grupo de compactação 8K é suportado.
+
O tipo de compressão secundária não é suportado

* Para usar a descarga de cópia ODX para migrar convidados Hyper-V dentro e entre discos, os servidores Hyper-V devem ser configurados para usar discos SCSI.
+
O padrão é configurar discos IDE, mas a descarga de cópia ODX não funciona quando os convidados são migrados se os discos são criados usando discos IDE.


