---
permalink: antivirus/commands-manage-on-access-policies-reference.html 
sidebar: sidebar 
keywords: commands, manage, on-access, policies 
summary: Você pode modificar, desativar ou excluir uma política de acesso. Você pode exibir um resumo e detalhes da política. 
---
= Comandos ONTAP Vscan para gerenciar políticas de acesso
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode modificar, desativar ou excluir uma política de acesso. Você pode exibir um resumo e detalhes da política.

|===


| Se você quiser... | Digite o seguinte comando... 


 a| 
Crie uma política de acesso
 a| 
`vserver vscan on-access-policy create`



 a| 
Modificar uma política de acesso
 a| 
`vserver vscan on-access-policy modify`



 a| 
Ative uma política de acesso
 a| 
`vserver vscan on-access-policy enable`



 a| 
Desative uma política de acesso
 a| 
`vserver vscan on-access-policy disable`



 a| 
Eliminar uma política de acesso
 a| 
`vserver vscan on-access-policy delete`



 a| 
Veja o resumo e os detalhes de uma política de acesso
 a| 
`vserver vscan on-access-policy show`



 a| 
Adicionar à lista de caminhos a excluir
 a| 
`vserver vscan on-access-policy paths-to-exclude add`



 a| 
Excluir da lista de caminhos a serem excluídos
 a| 
`vserver vscan on-access-policy paths-to-exclude remove`



 a| 
Exibir a lista de caminhos a serem excluídos
 a| 
`vserver vscan on-access-policy paths-to-exclude show`



 a| 
Adicionar à lista de extensões de arquivo a excluir
 a| 
`vserver vscan on-access-policy file-ext-to-exclude add`



 a| 
Excluir da lista de extensões de arquivo a serem excluídas
 a| 
`vserver vscan on-access-policy file-ext-to-exclude remove`



 a| 
Veja a lista de extensões de arquivo a excluir
 a| 
`vserver vscan on-access-policy file-ext-to-exclude show`



 a| 
Adicionar à lista de extensões de arquivo a incluir
 a| 
`vserver vscan on-access-policy file-ext-to-include add`



 a| 
Excluir da lista de extensões de arquivo a incluir
 a| 
`vserver vscan on-access-policy file-ext-to-include remove`



 a| 
Veja a lista de extensões de arquivo a incluir
 a| 
`vserver vscan on-access-policy file-ext-to-include show`

|===
Saiba mais sobre os comandos descritos neste procedimento no link:https://docs.netapp.com/us-en/ontap-cli/["Referência do comando ONTAP"^].
