---
permalink: antivirus/commands-manage-on-demand-tasks-reference.html 
sidebar: sidebar 
keywords: commands, manage, on-demand, tasks 
summary: Você pode modificar, excluir ou desagendar uma tarefa sob demanda. Você pode exibir um resumo e detalhes da tarefa e gerenciar relatórios para a tarefa. 
---
= Comandos para gerenciar tarefas sob demanda
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode modificar, excluir ou desagendar uma tarefa sob demanda. Você pode exibir um resumo e detalhes da tarefa e gerenciar relatórios para a tarefa.

|===


| Se você quiser... | Digite o seguinte comando... 


 a| 
Crie uma tarefa sob demanda
 a| 
`vserver vscan on-demand-task create`



 a| 
Modifique uma tarefa sob demanda
 a| 
`vserver vscan on-demand-task modify`



 a| 
Eliminar uma tarefa a pedido
 a| 
`vserver vscan on-demand-task delete`



 a| 
Execute uma tarefa sob demanda
 a| 
`vserver vscan on-demand-task run`



 a| 
Agende uma tarefa sob demanda
 a| 
`vserver vscan on-demand-task schedule`



 a| 
Anule a programação de uma tarefa sob demanda
 a| 
`vserver vscan on-demand-task unschedule`



 a| 
Exibir resumo e detalhes de uma tarefa sob demanda
 a| 
`vserver vscan on-demand-task show`



 a| 
Veja relatórios sob demanda
 a| 
`vserver vscan on-demand-task report show`



 a| 
Eliminar relatórios a pedido
 a| 
`vserver vscan on-demand-task report delete`

|===
Saiba mais sobre os comandos descritos neste procedimento no link:https://docs.netapp.com/us-en/ontap-cli/["Referência do comando ONTAP"^].
