---
permalink: antivirus/commands-manage-scanner-pools-reference.html 
sidebar: sidebar 
keywords: commands, manage, scanner pools 
summary: Você pode modificar e excluir pools de scanner e gerenciar usuários privilegiados e servidores Vscan para um pool de scanner. Você também pode exibir informações resumidas sobre o pool do scanner. 
---
= Comandos para gerenciar pools de scanner
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode modificar e excluir pools de scanner e gerenciar usuários privilegiados e servidores Vscan para um pool de scanner. Você também pode exibir informações resumidas sobre o pool do scanner.

|===


| Se você quiser... | Digite o seguinte comando... 


 a| 
Modifique um conjunto de scanners
 a| 
`vserver vscan scanner-pool modify`



 a| 
Exclua um pool de scanner
 a| 
`vserver vscan scanner-pool delete`



 a| 
Adicione usuários privilegiados a um pool de scanners
 a| 
`vserver vscan scanner-pool privileged-users add`



 a| 
Excluir usuários privilegiados de um pool de scanner
 a| 
`vserver vscan scanner-pool privileged-users remove`



 a| 
Adicione servidores Vscan a um pool de scanners
 a| 
`vserver vscan scanner-pool servers add`



 a| 
Excluir servidores Vscan de um pool de scanners
 a| 
`vserver vscan scanner-pool servers remove`



 a| 
Exibir resumo e detalhes de um pool de scanners
 a| 
`vserver vscan scanner-pool show`



 a| 
Exibir usuários privilegiados de um pool de scanners
 a| 
`vserver vscan scanner-pool privileged-users show`



 a| 
Veja os servidores Vscan para todos os pools de scanners
 a| 
`vserver vscan scanner-pool servers show`

|===
Para obter mais informações sobre esses comandos, consulte as páginas man.
