---
permalink: antivirus/commands-view-vscan-server-reference.html 
sidebar: sidebar 
keywords: commands, view, vscan, server, connection, status 
summary: Você pode usar os comandos vserver vscan Connection-status show para exibir resumo e informações detalhadas sobre o status da conexão do servidor Vscan. 
---
= Comandos para visualizar o estado da ligação do servidor Vscan
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pode utilizar os `vserver vscan connection-status show` comandos para visualizar informações resumidas e detalhadas sobre o estado da ligação do servidor Vscan.

|===
| Se você quiser... | Digite o seguinte comando... 


 a| 
Ver um resumo das ligações do servidor Vscan
 a| 
`vserver vscan connection-status show`



 a| 
Ver detalhes das ligações do servidor Vscan
 a| 
`vserver vscan connection-status show-all`



 a| 
Ver detalhes dos servidores Vscan ligados
 a| 
`vserver vscan connection-status show-connected`



 a| 
Ver detalhes dos servidores Vscan disponíveis que não estão ligados
 a| 
`vserver vscan connection-status show-not-connected`

|===
Saiba mais sobre `vserver vscan connection-status show` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+vscan+connection-status+show["Referência do comando ONTAP"^]na .
