---
permalink: antivirus/create-scanner-pool-single-cluster-task.html 
sidebar: sidebar 
keywords: create, scanner pool, single cluster 
summary: Um pool de scanners define os servidores Vscan e os usuários privilegiados que podem se conetar a SVMs. Você pode criar um pool de varredor para uma SVM individual ou para todos os SVMs em um cluster. 
---
= Crie um pool de scanners em um único cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um pool de scanners define os servidores Vscan e os usuários privilegiados que podem se conetar a SVMs. Você pode criar um pool de varredor para uma SVM individual ou para todos os SVMs em um cluster.

.O que você vai precisar
* Os servidores SVMs e Vscan devem estar no mesmo domínio ou em domínios confiáveis.
* Para pools de scanners definidos para SVM individual, você precisa ter o ONTAP Antivirus Connector configurado com o SVM Management LIF ou LIF de dados SVM.
* Para pools de scanners definidos para todos os SVMs em um cluster, você deve ter configurado o conetor antivírus ONTAP com o LIF de gerenciamento de cluster.
* A lista de usuários privilegiados deve incluir a conta de usuário do domínio que o servidor Vscan usa para se conetar ao SVM.
* Depois que o pool do scanner estiver configurado, verifique o status da conexão com os servidores.


.Passos
. Criar um conjunto de scanners:
+
`vserver vscan scanner-pool create -vserver data_SVM|cluster_admin_SVM -scanner-pool scanner_pool -hostnames Vscan_server_hostnames -privileged-users privileged_users`

+
** Especifique um SVM de dados para um pool definido para um SVM individual e especifique um SVM admin de cluster para um pool definido para todas as SVMs em um cluster.
** Especifique um endereço IP ou FQDN para cada nome de host do servidor Vscan.
** Especifique o domínio e o nome de usuário para cada usuário privilegiado. Para obter uma lista completa de opções, consulte a página de manual do comando.


+
O comando a seguir cria um pool de scanner chamado `SP` na `vs1` SVM:

+
[listing]
----
cluster1::> vserver vscan scanner-pool create -vserver vs1 -scanner-pool SP -hostnames 1.1.1.1,vmwin204-27.fsct.nb -privileged-users cifs\u1,cifs\u2
----
. Verifique se o conjunto do scanner foi criado:
+
`vserver vscan scanner-pool show -vserver _data_SVM|cluster_admin_SVM_ -scanner-pool _scanner_pool_`

+
Para obter uma lista completa de opções, consulte a página de manual do comando.

+
O comando a seguir exibe os detalhes do `SP` pool do scanner:

+
[listing]
----
cluster1::> vserver vscan scanner-pool show -vserver vs1 -scanner-pool SP

                                    Vserver: vs1
                               Scanner Pool: SP
                             Applied Policy: idle
                             Current Status: off
         Cluster on Which Policy Is Applied: -
                  Scanner Pool Config Owner: vserver
       List of IPs of Allowed Vscan Servers: 1.1.1.1, 10.72.204.27
List of Host Names of Allowed Vscan Servers: 1.1.1.1, vmwin204-27.fsct.nb
                   List of Privileged Users: cifs\u1, cifs\u2
----
+
Você também pode usar o `vserver vscan scanner-pool show` comando para exibir todos os pools de scanner em um SVM. Para obter a sintaxe de comando completa, consulte a página man para o comando.


