---
permalink: antivirus/create-scanner-pool-single-cluster-task.html 
sidebar: sidebar 
keywords: create, scanner pool, single cluster 
summary: Um pool de scanners define os servidores Vscan e os usuários privilegiados que podem se conetar a SVMs. 
---
= Crie um pool de scanners em um único cluster com o ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um pool de scanners define os servidores Vscan e os usuários privilegiados que podem se conetar a SVMs.

.Antes de começar
* Os servidores SVMs e Vscan devem estar no mesmo domínio ou em domínios confiáveis.
* Configure um conetor antivírus ONTAP com o LIF de gerenciamento de cluster.
* A lista de usuários privilegiados deve incluir o domínio e o nome de usuário que o servidor Vscan usa para se conetar ao SVM.
* Depois que o pool do scanner estiver configurado, verifique o status da conexão com os servidores.


.Passos
. Criar um conjunto de scanners:
+
`vserver vscan scanner-pool create -vserver cluster_admin_SVM -scanner-pool scanner_pool -hostnames Vscan_server_hostnames -privileged-users privileged_users`

+
** Especifique um administrador de cluster SVM.
** Especifique um endereço IP ou FQDN para cada nome de host do servidor Vscan.
** Especifique o domínio e o nome de usuário para cada usuário privilegiado. Saiba mais sobre os comandos descritos neste procedimento no link:https://docs.netapp.com/us-en/ontap-cli/["Referência do comando ONTAP"^].


. Verifique se o conjunto do scanner foi criado:
+
`vserver vscan scanner-pool show -vserver cluster_admin_SVM -scanner-pool _scanner_pool_`

+
O comando a seguir exibe os detalhes do `SP` pool do scanner:

+
[listing]
----
cluster1::> vserver vscan scanner-pool show -vserver cluster_admin_SVM -scanner-pool SP

                                    Vserver: cluster_admin_SVM
                               Scanner Pool: SP
                             Applied Policy: idle
                             Current Status: off
         Cluster on Which Policy Is Applied: -
                  Scanner Pool Config Owner: cluster
       List of IPs of Allowed Vscan Servers: 1.1.1.1, 10.72.204.27
List of Host Names of Allowed Vscan Servers: 1.1.1.1, vmwin204-27.fsct.nb
                   List of Privileged Users: cifs\u1, cifs\u2
----
+
Você também pode usar o `vserver vscan scanner-pool show` comando para exibir todos os pools de scanner no cluster. Saiba mais sobre `vserver vscan scanner-pool show` o link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-scanner-pool-show.html["Referência do comando ONTAP"^]na .


