---
permalink: antivirus/enable-on-access-policy-task.html 
sidebar: sidebar 
keywords: enable, on-access, policy 
summary: Uma política de acesso define o escopo de uma digitalização no acesso. Você deve habilitar uma política de acesso em um SVM antes que seus arquivos possam ser digitalizados. 
---
= Habilitar políticas de acesso do ONTAP Vscan
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Uma política de acesso define o escopo de uma digitalização no acesso. Você deve habilitar uma política de acesso em um SVM antes que seus arquivos possam ser digitalizados.

Se você criou uma política de acesso para todos os SVMs em um cluster, habilite a política em cada SVM individualmente. Você pode ativar apenas uma política de acesso em um SVM de cada vez.

.Passos
. Ativar uma política de acesso:
+
`vserver vscan on-access-policy enable -vserver data_SVM -policy-name policy_name`

+
O comando a seguir habilita uma política de acesso denominada `Policy1` na `vs1` SVM:

+
[listing]
----
cluster1::> vserver vscan on-access-policy enable -vserver vs1 -policy-name Policy1
----
. Verifique se a política de acesso está ativada:
+
`vserver vscan on-access-policy show -instance _data_SVM_ -policy-name _policy_name_`

+
Saiba mais sobre `vserver vscan on-access-policy show` o link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-on-access-policy-show.html["Referência do comando ONTAP"^]na .

+
O comando a seguir exibe os detalhes da `Policy1` política de acesso:

+
[listing]
----
cluster1::> vserver vscan on-access-policy show -instance vs1 -policy-name Policy1

                           Vserver: vs1
                            Policy: Policy1
                     Policy Status: on
               Policy Config Owner: vserver
              File-Access Protocol: CIFS
                           Filters: scan-ro-volume
                    Mandatory Scan: on
Max File Size Allowed for Scanning: 3GB
            File Paths Not to Scan: \vol\a b\, \vol\a,b\
       File Extensions Not to Scan: mp3, txt
           File Extensions to Scan: mp*, tx*
      Scan Files with No Extension: false
----

