---
permalink: antivirus/modify-vscan-file-profile-smb-share-task.html 
sidebar: sidebar 
keywords: modify, vscan, file-operations, profile, cifs share 
summary: 'O perfil _Vscan file-operations_ de um compartilhamento SMB define as operações no compartilhamento que podem acionar a digitalização. Por padrão, o parâmetro é definido como `standard`. Você pode ajustar o parâmetro conforme necessário ao criar ou modificar um compartilhamento SMB.' 
---
= Modifique o perfil de operações de arquivo Vscan para um compartilhamento SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O perfil _Vscan file-operations_ de um compartilhamento SMB define as operações no compartilhamento que podem acionar a digitalização. Por padrão, o parâmetro é definido como `standard`. Você pode ajustar o parâmetro conforme necessário ao criar ou modificar um compartilhamento SMB.

Consulte link:architecture-concept.html["Arquitetura antivírus"]a seção para obter detalhes sobre o perfil _Vscan file-operations_.

[NOTE]
====
A verificação de vírus não é realizada em um compartilhamento SMB que tenha o `continuously-available` parâmetro definido como `Yes`.

====
.Passo
. Modifique o valor do perfil de operações de ficheiros Vscan para uma partilha SMB:
+
`vserver cifs share modify -vserver _data_SVM_ -share-name _share_ -path _share_path_ -vscan-fileop-profile no-scan|standard|strict|writes-only`

+
Para obter uma lista completa de opções, consulte a página de manual do comando.

+
O comando a seguir altera o perfil de operações do arquivo Vscan para um compartilhamento SMB para `strict`:

+
[listing]
----
cluster1::> vserver cifs share modify -vserver vs1 -share-name SALES_SHARE -path /sales -vscan-fileop-profile strict
----

