---
permalink: antivirus/vscan-server-install-config-concept.html 
sidebar: sidebar 
keywords: vscan, server installation, configuration 
summary: Tem de configurar e configurar um ou mais servidores Vscan para ativar a verificação de antivírus. 
---
= Instalação e configuração do servidor Vscan
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Configure um ou mais servidores Vscan para garantir que os arquivos no seu sistema sejam verificados por vírus. Siga as instruções fornecidas pelo fornecedor para instalar e configurar o software antivírus no servidor.

Siga as instruções no arquivo README fornecido pelo NetApp para instalar e configurar o conetor antivírus do ONTAP. Em alternativa, siga as instruções na link:install-ontap-antivirus-connector-task.html["Instale a página do conetor antivírus do ONTAP"].

[NOTE]
====
Para a recuperação de desastres e configurações do MetroCluster, é necessário configurar servidores Vscan separados para os clusters ONTAP primário, local e secundário/parceiro.

====


== Requisitos de software antivírus

* Para obter informações sobre os requisitos de software antivírus, consulte a documentação do fornecedor.
* Para obter informações sobre os fornecedores, software e versões compatíveis com o Vscan, consulte a link:../antivirus/vscan-partner-solutions.html["Soluções de parceiros Vscan"] página.




== Requisitos do conetor antivírus do ONTAP

* Você pode baixar o conetor antivírus da ONTAP na página *Download de software* no site de suporte da NetApp. link:http://mysupport.netapp.com/NOW/cgi-bin/software["Downloads de NetApp: Software"^]
* Para obter informações sobre as versões do Windows suportadas pelo conetor antivírus do ONTAP e os requisitos de interoperabilidade, link:../antivirus/vscan-partner-solutions.html["Soluções de parceiros Vscan"]consulte .
+
[NOTE]
====
Você pode instalar versões diferentes de servidores Windows para diferentes servidores Vscan em um cluster.

====
* .NET 3,0 ou posterior deve ser instalado no servidor Windows.
* O SMB 2,0 deve estar ativado no servidor Windows.

