---
permalink: revert/arp-warning-clear-revert.html 
sidebar: sidebar 
keywords: ontap, revert, ransomware, protection, security, arp 
summary: Antes de reverter o ONTAP, responda a quaisquer avisos de atividade anormal na Proteção Autônoma contra Ransomware 
---
= Resolva os avisos de atividade na Proteção Autônoma contra Ransomware antes de uma reversão do ONTAP.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de reverter para o ONTAP 9.17.1 ou anterior, você deve responder a quaisquer avisos de atividade anormal relatados pelo Autonomous Ransomware Protection e excluir quaisquer snapshots associados do Autonomous Ransomware Protection.

.Antes de começar
Você precisa de privilégios "Advanced" para excluir snapshots da Proteção Autônoma contra Ransomware.

.Passos
. Responda a quaisquer avisos de atividade anormal relatados por link:../anti-ransomware/respond-abnormal-task.html["Proteção autônoma contra ransomware"] e resolva quaisquer problemas potenciais.
. Confirme a resolução desses problemas antes de reverter, selecionando *Atualizar e Limpar Tipos de Arquivos Suspeitos* para registrar sua decisão e retomar o monitoramento normal da Proteção Autônoma contra Ransomware.
. Liste todos os snapshots do Autonomous Ransomware Protection associados aos avisos executando o seguinte comando:
+
[source, cli]
----
volume snapshot snapshot show -fs-version 9.18
----
. Exclua quaisquer instantâneos da Proteção Autônoma contra Ransomware associados aos avisos:
+

NOTE: Este comando exclui todos os snapshots que possuem o formato usado pela versão atual do ONTAP, potencialmente não apenas os snapshots do Autonomous Ransomware Protection. Certifique-se de ter tomado todas as medidas necessárias para todos os snapshots que serão removidos antes de executar este comando.

+
[source, cli]
----
volume snapshot prepare-for-revert -node <node_name>
----

