---
permalink: revert/arp-warning-clear-revert.html 
sidebar: sidebar 
keywords: ontap, revert, ransomware, protection, security, arp 
summary: Antes de reverter para o ONTAP, responda a quaisquer avisos de atividade anormal no ARP. 
---
= Resolver avisos de atividade no Autonomous Ransomware Protection (ARP) antes de uma reversão do ONTAP.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de reverter para o ONTAP 9.17.1 ou anterior, você deve responder a quaisquer avisos de atividade anormal relatados pela Proteção Autônoma contra Ransomware (ARP) e excluir quaisquer capturas de tela da ARP associadas.

.Antes de começar
Você precisa de privilégios "Avançados" para excluir snapshots ARP.

.Passos
. Responda a quaisquer avisos de atividade anormais comunicados pela link:../anti-ransomware/respond-abnormal-task.html["ARP"] e resolva quaisquer problemas potenciais.
. Confirme a resolução desses problemas antes de reverter, selecionando *Atualizar e limpar tipos de arquivo suspeitos* para registrar sua decisão e retomar o monitoramento normal de ARP.
. Liste todas as capturas de tela de ARP associadas aos avisos executando o seguinte comando:
+
[source, cli]
----
volume snapshot snapshot show -fs-version 9.18
----
. Exclua quaisquer capturas de tela de ARP associadas aos avisos:
+

NOTE: Este comando exclui todos os snapshots que possuem o formato usado pela versão atual do ONTAP, potencialmente não apenas snapshots ARP.  Certifique-se de ter tomado todas as medidas necessárias para todos os snapshots que serão removidos antes de executar este comando.

+
[source, cli]
----
volume snapshot prepare-for-revert -node <node_name>
----

