---
permalink: revert/concept_revert_paths.html 
sidebar: sidebar 
keywords: ontap, downgrade, revert, paths 
summary: Você pode reverter diretamente seu software ONTAP para apenas uma versão anterior à versão atual do ONTAP. Você não deve reverter para versões sem suporte do ONTAP. 
---
= Reverter caminhos de ONTAP compatíveis
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode reverter diretamente seu software ONTAP para apenas uma versão anterior à versão atual do ONTAP. Por exemplo, se você estiver executando 9.15.1, não poderá reverter diretamente para 9.13.1. Você deve reverter para 9.14.1; em seguida, executar uma reversão separada de 9.14.1 para 9.13.1.

Reverter para o ONTAP 9.4 ou anterior não é suportado. Você não deve reverter para versões sem suporte do ONTAP.

Você pode usar o `system image show` comando para determinar a versão do ONTAP em execução em cada nó.

Os seguintes caminhos de reversão compatíveis referem-se apenas a versões ONTAP locais. Para obter informações sobre como reverter o ONTAP na nuvem, https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html#reverting-or-downgrading["Revertendo ou baixando Cloud Volumes ONTAP"^] consulte .

[cols="2*"]
|===
| Você pode reverter de... | Para... 


 a| 
ONTAP 9.18.1
| ONTAP 9.17.1 


 a| 
ONTAP 9.17.1
| ONTAP 9.16,1 


 a| 
ONTAP 9.16,1
| ONTAP 9.15,1 


 a| 
ONTAP 9.15,1
| ONTAP 9.14,1 


 a| 
ONTAP 9.14,1
| ONTAP 9.13,1 


 a| 
ONTAP 9.13,1
| ONTAP 9.12,1 


 a| 
ONTAP 9.12,1
| ONTAP 9.11,1 


 a| 
ONTAP 9.11,1
| ONTAP 9.10,1 


 a| 
ONTAP 9.10,1
| ONTAP 9.9,1 


 a| 
ONTAP 9.9,1
| ONTAP 9,8 


 a| 
ONTAP 9,8
| ONTAP 9,7 


 a| 
ONTAP 9,7
| ONTAP 9,6 


 a| 
ONTAP 9,6
| ONTAP 9,5 
|===