---
permalink: revert/concept_consideration_for_reverting_systems_with_snapmirror_synchronous_relationships.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, considerations, snapmirror, synchronous, relationships 
summary: Você deve estar ciente das considerações para relacionamentos síncronos do SnapMirror antes de reverter do ONTAP 9.6 para o ONTAP 9.5. 
---
= Considerações para reverter sistemas de ONTAP 9,6 com relações síncronas SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve estar ciente das considerações para relacionamentos síncronos do SnapMirror antes de reverter do ONTAP 9.6 para o ONTAP 9.5.

Antes de reverter, você deve seguir as seguintes etapas se tiver relações síncronas do SnapMirror:

* É necessário excluir qualquer relacionamento síncrono do SnapMirror no qual o volume de origem esteja fornecendo dados usando NFSv4 ou SMB.
+
O ONTAP 9.5 não oferece suporte a NFSv4 e SMB.

* Você deve excluir quaisquer relações síncronas do SnapMirror em uma implantação em cascata espelhada.
+
Uma implantação em cascata espelhada não é suportada para relacionamentos síncronos do SnapMirror no ONTAP 9.5.

* Se as cópias Snapshot comuns no ONTAP 9.5 não estiverem disponíveis durante a reversão, será necessário inicializar o relacionamento síncrono do SnapMirror após a reversão.
+
Após duas horas de atualização para o ONTAP 9.6, as cópias Snapshot comuns do ONTAP 9.5 são automaticamente substituídas pelas cópias Snapshot comuns no ONTAP 9.6. Portanto, não é possível ressincronizar a relação síncrona do SnapMirror após reverter se as cópias Snapshot comuns do ONTAP 9.5 não estiverem disponíveis.


