---
permalink: revert/concept_support_of_sp_firmware_automatic_revert.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, considerations, manual, manually, update, updating, sp, firmware 
summary: Se a funcionalidade de atualização automática do SP estiver ativada, fazer downgrade ou reverter para o ONTAP 8,3.x não requer uma atualização manual do firmware do SP. O firmware do SP é atualizado automaticamente para a versão compatível mais recente que é suportada pela versão do ONTAP para a qual você reverteu ou baixou. 
---
= Considerações sobre se deseja atualizar manualmente o firmware do SP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se a funcionalidade de atualização automática do SP estiver ativada (o padrão), fazer downgrade ou reverter para o ONTAP 8,3.x não requer uma atualização manual do firmware do SP. O firmware do SP é atualizado automaticamente para a versão compatível mais recente que é suportada pela versão do ONTAP para a qual você reverteu ou baixou.

Se a funcionalidade de atualização automática do SP estiver desativada (não recomendada), após o processo de reversão ou downgrade do ONTAP ser concluído, você deverá atualizar manualmente o firmware do SP para uma versão compatível com a versão do ONTAP para a qual você reverteu ou baixou.

http://mysupport.netapp.com/NOW/download/tools/serviceimage/support/["Matriz de suporte do BIOS/ONTAP da NetApp"^]

https://mysupport.netapp.com/site/downloads/firmware/system-firmware-diagnostics["Downloads do NetApp: Firmware e Diagnóstico do sistema"^]
