---
permalink: revert/concept_when_to_call_technical_support.html 
sidebar: sidebar 
keywords: ontap, downgrade, revert, paths 
summary: É possível reverter sem assistência em clusters novos ou de teste. Ligue para o suporte técnico para reverter clusters de produção. 
---
= Preciso de suporte técnico para reverter um cluster do ONTAP?
:allow-uri-read: 


[role="lead"]
Você deve entrar em Contato com o suporte técnico antes de tentar reverter um cluster do ONTAP nas seguintes situações:

* Um ambiente de produção
+
Não tente reverter um cluster de produção sem a assistência do suporte técnico.

* Você criou volumes no ONTAP 9.5 ou posterior e precisa reverter para uma versão anterior.
+
Os volumes que utilizam a compressão adaptável devem ser descomprimidos antes de reverter.



É possível reverter clusters novos ou de teste sem assistência. Se você tentar reverter um cluster sozinho e tiver algum dos seguintes problemas, ligue para o suporte técnico:

* A reversão falha ou não pode terminar.
* A reversão termina, mas o cluster não é utilizável em um ambiente de produção.
* A reversão termina e o cluster entra em produção, mas você não está satisfeito com seu comportamento.

