---
permalink: revert/remove-nfs-trunking-task.html 
sidebar: sidebar 
keywords: nfsv4.1, trunking, revert 
summary: Se você ativou o entroncamento para conexões de cliente e reverte para uma versão anterior ao ONTAP 9.12,1, você deve desativar o entroncamento em qualquer servidor NFSv4,1 antes de reverter. 
---
= Remova a configuração do entroncamento de sessão NFSv4,1 antes de reverter do ONTAP 9.14,1 ou posterior
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você ativou o entroncamento para conexões de cliente e reverte para uma versão anterior ao ONTAP 9.14,1, você deve desativar o entroncamento em qualquer servidor NFSv4,1 antes de reverter.

Ao inserir o `revert-to` comando, você verá uma mensagem de aviso aconselhando você a desativar o entroncamento antes de prosseguir.

Depois de reverter para uma versão anterior do ONTAP, os clientes que usam conexões truncadas voltam a usar uma única conexão. A taxa de transferência de dados será afetada, mas não haverá interrupções. O comportamento de reversão é o mesmo que modificar a opção de entroncamento NFSv4,1 para o SVM de habilitado para desativado.

.Passos
. Desativar o entroncamento no servidor NFSv4,1
`vserver nfs modify -vserver _svm_name_ -v4.1-trunking disabled`
. Verifique se o NFS está configurado como desejado
`vserver nfs show -vserver _svm_name_`

