---
permalink: revert/task_quiesce_snapmirror_relationships_before_downgrade.html 
sidebar: sidebar 
keywords: ontap, downgrade, downgrading, snapmirror, operations, quisce 
summary: Recomenda-se que você conclua suas operações do SnapMirror antes de executar um downgrade do ONTAP sem interrupções. 
---
= Quiesce relações SnapMirror antes de downgrade
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É recomendável que você silencie suas operações do SnapMirror antes de executar um downgrade do ONTAP.

. Use o comando SnapMirror show para determinar o caminho de destino para cada relacionamento do SnapMirror.
. Para cada volume de destino, suspenda futuras transferências SnapMirror: `snapmirror quiesce -destination-path destination`
+
Se não houver transferências ativas para o relacionamento SnapMirror, este comando define seu status como Quiesced. Se o relacionamento tiver transferências ativas, o status será definido como Quiescente até que a transferência seja concluída e, em seguida, o status se tornará Quiesced.

+
Este exemplo anula transferências envolvendo o volume de destino vol1 a partir de SVMvs0.example.com:

+
[listing]
----
cluster1::> snapmirror quiesce -destination-path vs0.example.com:vol1
----
. Verifique se todos os relacionamentos do SnapMirror estão desativados: `snapmirror show -status !Quiesced`
+
Este comando exibe quaisquer relações SnapMirror que são _não_ quiesced.

+
Este exemplo mostra que todos os relacionamentos do SnapMirror são quiesced:

+
[listing]
----
cluster1::> snapmirror show -status !Quiesced
There are no entries matching your query.
----
. Se algum relacionamento do SnapMirror estiver sendo transferido atualmente, execute uma das seguintes opções:
+
[cols="2*"]
|===
| Opção | Descrição 


 a| 
Aguarde até que as transferências terminem antes de executar o downgrade do ONTAP.
 a| 
Após cada transferência terminar, a relação muda para o status Quiesced.



 a| 
Parar as transferências: `snapmirror abort -destination-path destination -h` *Nota:* você deve usar o parâmetro -foreground true se estiver abortando transferências de espelhamento de compartilhamento de carga.
 a| 
Este comando interrompe a transferência SnapMirror e restaura o volume de destino para a última cópia Snapshot que foi transferida com êxito. O relacionamento é definido como status Quiesced.

|===

