---
permalink: revert/task_preparing_snapshot_copies_before_reverting.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, snapshot, copies, prepare, preparing, disable, delete 
summary: Antes de reverter para uma versão anterior do ONTAP, você deve desativar todas as políticas de snapshot e excluir todos os snapshots que foram criados após a atualização para a versão atual. 
---
= Prepare instantâneos antes de reverter um cluster ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de reverter um cluster do ONTAP de qualquer versão do ONTAP 9, você deve desativar todas as políticas de snapshot e excluir todos os snapshots que foram criados após a atualização para a versão atual.

Se você estiver revertendo em um ambiente SnapMirror, primeiro você deve excluir as seguintes relações de espelhamento:

* Todas as relações de espelhamento de compartilhamento de carga
* Todas as relações espelhadas de proteção de dados que foram criadas no ONTAP 8,3.x
* Todas as relações espelhadas de proteção de dados se o cluster foi recriado no ONTAP 8,3.x


.Passos
. Desativar políticas de snapshot para todos os SVMs de dados:
+
[source, cli]
----
volume snapshot policy modify -vserver * -enabled false
----
. Desative políticas de snapshot para agregados de cada nó:
+
.. Identificar os agregados do nó:
+
[source, cli]
----
run -node <nodename> -command aggr status
----
.. Desative a política de snapshot para cada agregado:
+
[source, cli]
----
run -node <nodename> -command aggr options aggr_name nosnap on
----
.. Repita esta etapa para cada nó restante.


. Desativar políticas de snapshot para o volume raiz de cada nó:
+
.. Identificar o volume raiz do nó:
+
[source, cli]
----
run-node <node_name> -command vol status
----
+
Você identifica o volume raiz pela palavra root na coluna *Opções* da `vol status` saída do comando.

+
[listing]
----
vs1::> run -node node1 vol status

         Volume State           Status            Options
           vol0 online          raid_dp, flex     root, nvfail=on
                                64-bit
----
.. Desative a política de instantâneos no volume raiz:
+
[source, cli]
----
run -node <node_name> vol options root_volume_name nosnap on
----
.. Repita esta etapa para cada nó restante.


. Exclua todos os snapshots criados após a atualização para a versão atual:
+
.. Defina o nível de privilégio como avançado:
+
[source, cli]
----
set -privilege advanced
----
.. Desativar os instantâneos:
+
[source, cli]
----
snapshot policy modify -vserver * -enabled false
----
.. Exclua os instantâneos da versão mais recente do nó:
+
[source, cli]
----
volume snapshot prepare-for-revert -node <node_name>
----
+
Esse comando exclui os snapshots da versão mais recente em cada volume de dados, agregado de raiz e volume de raiz.

+
Se não for possível eliminar quaisquer instantâneos, o comando falhará e notifica-o de quaisquer acões necessárias que tenha de tomar antes de os instantâneos poderem ser eliminados. Você deve concluir as ações necessárias e executar novamente o `volume snapshot prepare-for-revert` comando antes de prosseguir para a próxima etapa.

+
[listing]
----
cluster1::*> volume snapshot prepare-for-revert -node node1

Warning: This command will delete all snapshots that have the format used by the current version of ONTAP. It will fail if any snapshot polices are enabled, or
         if any snapshots have an owner. Continue? {y|n}: y
----
.. Verifique se os instantâneos foram excluídos:
+
[source, cli]
----
volume snapshot show -node nodename
----
.. Se quaisquer instantâneos da versão mais recente permanecerem, force-os a serem excluídos:
+
[source, cli]
----
volume snapshot delete {-fs-version 9.0 -node nodename -is-constituent true} -ignore-owners -force
----
.. Repita estas etapas para cada nó restante.
.. Voltar ao nível de privilégio de administrador:
+
[source, cli]
----
set -privilege admin
----





NOTE: Siga estas etapas nos dois clusters na configuração do MetroCluster.
