---
permalink: revert/task_things_to_verify_before_revert.html 
sidebar: sidebar 
keywords: ontap, revert, reversion, reverting, downgrade, downgrading, preparation, pre-revert, checks, verification, cluster health, storage health, system time, jobs 
summary: Antes de reverter o ONTAP, você deve verificar a integridade do cluster, a integridade do storage e a hora do sistema. Você também deve verificar se nenhum trabalho está sendo executado no cluster. 
---
= Verificações do sistema a serem executadas antes de reverter um cluster ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de reverter um cluster do ONTAP, verifique a integridade do cluster, a integridade do storage e a hora do sistema. Você também deve verificar se nenhum trabalho está sendo executado no cluster.



== Verifique a integridade do cluster

Antes de reverter um cluster do ONTAP, verifique se os nós estão íntegros e qualificados para participar do cluster e se o cluster está quórum.

.Passos
. Verifique se os nós do cluster estão online e estão qualificados para participar do cluster:
+
[source, cli]
----
cluster show
----
+
Neste exemplo, todos os nós estão íntegros e qualificados para participar do cluster.

+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
node0                 true    true
node1                 true    true
----
+
Se algum nó não for saudável ou não for elegível, verifique se há erros nos logs do EMS e tome medidas corretivas.

. Defina o nível de privilégio como avançado:
+
[source, cli]
----
set -privilege advanced
----
+
Entre `y` para continuar.

. Verifique os detalhes de configuração para cada processo RDB.
+
** A época do banco de dados relacional e as epochs do banco de dados devem corresponder para cada nó.
** O mestre de quórum por anel deve ser o mesmo para todos os nós.
+
Observe que cada anel pode ter um mestre de quórum diferente.

+
[cols="2*"]
|===
| Para exibir este processo RDB... | Digite este comando... 


 a| 
Aplicação de gerenciamento
 a| 
[source, cli]
----
cluster ring show -unitname mgmt
----


 a| 
Base de dados de localização de volume
 a| 
[source, cli]
----
cluster ring show -unitname vldb
----


 a| 
Gerenciador de interface virtual
 a| 
[source, cli]
----
cluster ring show -unitname vifmgr
----


 a| 
Daemon de gerenciamento SAN
 a| 
[source, cli]
----
cluster ring show -unitname bcomd
----
|===
+
Este exemplo mostra o processo do banco de dados de localização de volume:

+
[listing]
----
cluster1::*> cluster ring show -unitname vldb
Node      UnitName Epoch    DB Epoch DB Trnxs Master    Online
--------- -------- -------- -------- -------- --------- ---------
node0     vldb     154      154      14847    node0     master
node1     vldb     154      154      14847    node0     secondary
node2     vldb     154      154      14847    node0     secondary
node3     vldb     154      154      14847    node0     secondary
4 entries were displayed.
----


. Voltar ao nível de privilégio de administrador:
+
[source, cli]
----
set -privilege admin
----
. Se você estiver operando em um ambiente SAN, verifique se cada nó está em um quórum de SAN:
+
[source, cli]
----
event log show  -severity informational -message-name scsiblade.*
----
+
A mensagem de evento scsipblade mais recente para cada nó deve indicar que o scsi-blade está em quórum.

+
[listing]
----
cluster1::*> event log show  -severity informational -message-name scsiblade.*
Time             Node       Severity       Event
---------------  ---------- -------------- ---------------------------
MM/DD/YYYY TIME  node0      INFORMATIONAL  scsiblade.in.quorum: The scsi-blade ...
MM/DD/YYYY TIME  node1      INFORMATIONAL  scsiblade.in.quorum: The scsi-blade ...
----


.Informações relacionadas
link:../system-admin/index.html["Administração do sistema"]



== Verifique a integridade do armazenamento

Antes de reverter um cluster do ONTAP, verifique o status dos discos, agregados e volumes.

.Passos
. Verifique o status do disco:
+
[cols="2*"]
|===
| Para verificar... | Faça isso... 


 a| 
Discos quebrados
 a| 
.. Exibir todos os discos quebrados:
+
[source, cli]
----
storage disk show -state broken
----
.. Remova ou substitua quaisquer discos quebrados.




 a| 
Discos em manutenção ou reconstrução
 a| 
.. Exiba todos os discos em estados de manutenção, pendentes ou reconstrução:
+
[source, cli]
----
storage disk show -state maintenance|pending|reconstructing
----
.. Aguarde até que a operação de manutenção ou reconstrução termine antes de prosseguir.


|===
. Verifique se todos os agregados estão online, exibindo o estado do storage físico e lógico, incluindo agregados de storage
+
[source, cli]
----
storage aggregate show -state !online
----
+
Este comando exibe os agregados que estão _não_ online. Todos os agregados devem estar online antes e depois de realizar uma grande atualização ou reversão.

+
[listing]
----
cluster1::> storage aggregate show -state !online
There are no entries matching your query.
----
. Verifique se todos os volumes estão online exibindo quaisquer volumes que estejam _não_ online:
+
[source, cli]
----
volume show -state !online
----
+
Todos os volumes devem estar online antes e depois de realizar uma grande atualização ou reversão.

+
[listing]
----
cluster1::> volume show -state !online
There are no entries matching your query.
----
. Verifique se não existem volumes inconsistentes:
+
[source, cli]
----
volume show -is-inconsistent true
----
+
Veja olink:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Volume_Showing_WAFL_Inconsistent["Base de conhecimento da NetApp : volume mostrando WAFL inconsistente"^] sobre como lidar com volumes inconsistentes.



.Informações relacionadas
link:../disks-aggregates/index.html["Gerenciamento de disco e agregado"]



== Verifique a hora do sistema

Antes de reverter um cluster ONTAP, você deve verificar se o NTP está configurado e se o tempo está sincronizado no cluster.

.Passos
. Verifique se o cluster está associado a um servidor NTP:
+
[source, cli]
----
cluster time-service ntp server show
----
. Verifique se cada nó tem a mesma data e hora:
+
[source, cli]
----
cluster date show
----
+
[listing]
----
cluster1::> cluster date show
Node      Date                Timezone
--------- ------------------- -------------------------
node0     4/6/2013 20:54:38   GMT
node1     4/6/2013 20:54:38   GMT
node2     4/6/2013 20:54:38   GMT
node3     4/6/2013 20:54:38   GMT
4 entries were displayed.
----




== Verifique se nenhum trabalho está em execução

Antes de reverter um cluster do ONTAP, verifique o status dos trabalhos do cluster. Se qualquer agregado, volume, NDMP (despejo ou restauração) ou trabalhos instantâneos (como criar, excluir, mover, modificar, replicar e montar trabalhos) estiver em execução ou na fila de espera, você deve permitir que os trabalhos terminem com êxito ou interrompam as entradas na fila.

.Passos
. Reveja a lista de quaisquer trabalhos de agregados, volume ou instantâneos em execução ou em fila:
+
[source, cli]
----
job show
----
+
Neste exemplo, existem dois trabalhos em fila:

+
[listing]
----
cluster1::> job show
                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
8629   Vol Reaper           cluster1   -              Queued
       Description: Vol Reaper Job
8630   Certificate Expiry Check
                            cluster1   -              Queued
       Description: Certificate Expiry Check
----
. Excluir qualquer agregado, volume ou trabalho de snapshot em execução ou na fila:
+
[source, cli]
----
job delete -id <job_id>
----
. Verifique se nenhum agregado, volume ou trabalho instantâneo está em execução ou na fila:
+
[source, cli]
----
job show
----
+
Neste exemplo, todos os trabalhos em execução e em fila foram excluídos:

+
[listing]
----
cluster1::> job show
                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
9944   SnapMirrorDaemon_7_2147484678
                            cluster1   node1          Dormant
       Description: Snapmirror Daemon for 7_2147484678
18377  SnapMirror Service Job
                            cluster1   node0          Dormant
       Description: SnapMirror Service Job
2 entries were displayed
----


.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-show.html["exibição do disco de armazenamento"^]

