---
permalink: revert/task_verify_health.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, downgrade, downgrading, verifying, verify, cluster, health 
summary: Depois de reverter um cluster do ONTAP, você deve verificar se os nós estão íntegros e qualificados para participar do cluster e se o cluster está em quórum. 
---
= Verifique a integridade do cluster e do storage após uma reversão do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de reverter um cluster do ONTAP, verifique se os nós estão íntegros e qualificados para participar do cluster e se o cluster está quórum. Você também deve verificar o status dos discos, agregados e volumes.



== Verifique a integridade do cluster

.Passos
. Verifique se os nós do cluster estão online e estão qualificados para participar do cluster:
+
[source, cli]
----
cluster show
----
+
Neste exemplo, o cluster está íntegro e todos os nós estão qualificados para participar do cluster.

+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
node0                 true    true
node1                 true    true
----
+
Se algum nó não for saudável ou não for elegível, verifique se há erros nos logs do EMS e tome medidas corretivas.

. Defina o nível de privilégio como avançado:
+
[source, cli]
----
set -privilege advanced
----
+
Entre `y` para continuar.

. Verifique os detalhes de configuração para cada processo RDB.
+
** A época do banco de dados relacional e as epochs do banco de dados devem corresponder para cada nó.
** O mestre de quórum por anel deve ser o mesmo para todos os nós.
+
Observe que cada anel pode ter um mestre de quórum diferente.

+
[cols="2*"]
|===
| Para exibir este processo RDB... | Digite este comando... 


 a| 
Aplicação de gerenciamento
 a| 
[source, cli]
----
cluster ring show -unitname mgmt
----


 a| 
Base de dados de localização de volume
 a| 
[source, cli]
----
cluster ring show -unitname vldb
----


 a| 
Gerenciador de interface virtual
 a| 
[source, cli]
----
cluster ring show -unitname vifmgr
----


 a| 
Daemon de gerenciamento SAN
 a| 
[source, cli]
----
cluster ring show -unitname bcomd
----
|===
+
Este exemplo mostra o processo do banco de dados de localização de volume:

+
[listing]
----
cluster1::*> cluster ring show -unitname vldb
Node      UnitName Epoch    DB Epoch DB Trnxs Master    Online
--------- -------- -------- -------- -------- --------- ---------
node0     vldb     154      154      14847    node0     master
node1     vldb     154      154      14847    node0     secondary
node2     vldb     154      154      14847    node0     secondary
node3     vldb     154      154      14847    node0     secondary
4 entries were displayed.
----


. Voltar ao nível de privilégio de administrador:
+
[source, cli]
----
set -privilege admin
----
. Se você estiver operando em um ambiente SAN, verifique se cada nó está em um quórum de SAN:
+
[source, cli]
----
event log show  -severity informational -message-name scsiblade.*
----
+
A mensagem de evento scsipblade mais recente para cada nó deve indicar que o scsi-blade está em quórum.

+
[listing]
----
cluster1::*> event log show  -severity informational -message-name scsiblade.*
Time             Node       Severity       Event
---------------  ---------- -------------- ---------------------------
MM/DD/YYYY TIME  node0      INFORMATIONAL  scsiblade.in.quorum: The scsi-blade ...
MM/DD/YYYY TIME  node1      INFORMATIONAL  scsiblade.in.quorum: The scsi-blade ...
----


.Informações relacionadas
link:../system-admin/index.html["Administração do sistema"]



== Verifique a integridade do armazenamento

Depois de reverter ou fazer downgrade de um cluster, você deve verificar o status dos discos, agregados e volumes.

.Passos
. Verifique o status do disco:
+
[cols="2*"]
|===
| Para verificar... | Faça isso... 


 a| 
Discos quebrados
 a| 
.. Exibir todos os discos quebrados:
+
[source, cli]
----
storage disk show -state broken
----
.. Remova ou substitua quaisquer discos quebrados.




 a| 
Discos em manutenção ou reconstrução
 a| 
.. Exiba todos os discos em estados de manutenção, pendentes ou reconstrução:
+
[source, cli]
----
storage disk show -state maintenance|pending|reconstructing
----
.. Aguarde até que a operação de manutenção ou reconstrução termine antes de prosseguir.


|===
. Verifique se todos os agregados estão online exibindo o estado do storage físico e lógico, incluindo agregados de storage:
+
[source, cli]
----
storage aggregate show -state !online
----
+
Este comando exibe os agregados que estão _não_ online. Todos os agregados devem estar online antes e depois de realizar uma grande atualização ou reversão.

+
[listing]
----
cluster1::> storage aggregate show -state !online
There are no entries matching your query.
----
. Verifique se todos os volumes estão online exibindo quaisquer volumes que estejam _não_ online:
+
[source, cli]
----
volume show -state !online
----
+
Todos os volumes devem estar online antes e depois de realizar uma grande atualização ou reversão.

+
[listing]
----
cluster1::> volume show -state !online
There are no entries matching your query.
----
. Verifique se não existem volumes inconsistentes:
+
[source, cli]
----
volume show -is-inconsistent true
----
+
Veja olink:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Volume_Showing_WAFL_Inconsistent["Base de conhecimento da NetApp : volume mostrando WAFL inconsistente"^] sobre como lidar com volumes inconsistentes.





== Verificação do acesso do cliente (SMB e NFS)

Para os protocolos configurados, teste o acesso de clientes SMB e NFS para verificar se o cluster está acessível.

.Informações relacionadas
* link:../disks-aggregates/index.html["Gerenciamento de disco e agregado"]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-show.html["exibição do disco de armazenamento"^]

