---
permalink: revert/task_reverting_an_ontap_cluster.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, cluster 
summary: Para colocar o cluster offline para reverter para uma versão anterior do ONTAP, você deve desativar o failover de armazenamento e os LIFs de dados, pré-condições de reversão de endereço, reverter as configurações do cluster e do sistema de arquivos em um nó e repetir o processo para cada nó adicional no cluster. 
---
= Reverter um cluster ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Reverter um cluster ONTAP causa interrupções. Você deve colocar o cluster off-line durante a reversão. Você não deve reverter um cluster de produção sem a assistência do suporte técnico.

Para reverter um cluster novo ou de teste, você deve desativar failover de armazenamento e LIFs de dados e pré-condições de reversão de endereço; em seguida, você deve reverter a configuração do cluster e do sistema de arquivos em cada nó no cluster.

.Antes de começar.
* Você deve ter concluído o link:task_things_to_verify_before_revert.html["verificações pré-revertidas"].
* Você deve ter concluído o link:concept_pre_revert_checks.html["Pré-verificações para sua versão específica do ONTAP"]necessário .




== Passo 1: Prepare o cluster para reversão

Antes de reverter qualquer um dos nós de cluster, você deve verificar se a imagem do ONTAP de destino está instalada e desativar todas as LIFs de dados no cluster.

.Passos
. Defina o nível de privilégio como avançado:
+
[source, cli]
----
set -privilege advanced
----
+
Digite *y* quando solicitado a continuar.

. Verifique se o software ONTAP de destino está instalado:
+
[source, cli]
----
system image show
----
+
O exemplo a seguir mostra que a versão 9.13.1 está instalada como a imagem alternativa em ambos os nós:

+
[listing]
----
cluster1::*> system image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    9.14.1      MM/DD/YYYY TIME
         image2  false   false   9.13.1      MM/DD/YYYY TIME
node1
         image1  true    true    9.14.1      MM/DD/YYYY TIME
         image2  false   false   9.13.1      MM/DD/YYYY TIME
4 entries were displayed.
----
. Desative todas as LIFs de dados no cluster:
+
[source, cli]
----
network interface modify {-role data} -status-admin down
----
. Determine se você tem relacionamentos FlexCache entre clusters:
+
[source, cli]
----
flexcache origin show-caches -relationship-type inter-cluster
----
. Se os flexcaches entre clusters estiverem presentes, desative os dados de vida no cluster de cache:
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -status-admin down
----




== Etapa 2: Reverter nós de cluster

Para reverter o cluster, você precisa reverter o primeiro nó em um par de HA e, em seguida, reverter o nó de parceiro. Em seguida, repita esse processo para cada par de HA no cluster até que todos os nós sejam revertidos. Se você tiver uma configuração do MetroCluster, precisará repetir essas etapas para ambos os clusters na configuração.

[role="tabbed-block"]
====
.4 ou mais nós
--
.Passos
. Faça login no nó que você deseja reverter.
+
Para reverter um nó, você deve estar conetado ao cluster por meio do LIF de gerenciamento de nós do nó.

. Desative o failover de storage para os nós no par de HA:
+
[source, cli]
----
storage failover modify -node <nodename> -enabled false
----
+
Você só precisa desativar o failover de storage uma vez para o par de HA. Quando você desativa o failover de armazenamento para um nó, o failover de armazenamento também é desativado no parceiro do nó.

. Defina a imagem de software ONTAP de destino do nó para ser a imagem padrão:
+
[source, cli]
----
system image modify -node <nodename> -image <target_image> -isdefault true
----
. Verifique se a imagem do software ONTAP de destino está definida como a imagem padrão para o nó que você está revertendo:
+
[source, cli]
----
system image show
----
+
O exemplo a seguir mostra que a versão 9.13.1 está definida como a imagem padrão no node0:

+
[listing]
----
cluster1::*> system image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  false   true    9.14.1      MM/DD/YYYY TIME
         image2  true    false   9.13.1      MM/DD/YYYY TIME
node1
         image1  true    true    9.14.1      MM/DD/YYYY TIME
         image2  false   false   9.13.1      MM/DD/YYYY TIME
4 entries were displayed.
----
. Verifique se o nó está pronto para reversão:
+
[source, cli]
----
system node revert-to -node <nodename> -check-only true -version 9.x
----
+
O `check-only` parâmetro identifica quaisquer pré-condições que devem ser abordadas antes de reverter, como desabilitar a política de snapshot ou excluir snapshots que foram criados após a atualização para a versão posterior do ONTAP.

+
A `-version` opção refere-se à versão ONTAP para a qual você está revertendo. Por exemplo, se você estiver revertendo de 9.14.1 para 9.13.1, o valor correto `-version` da opção é 9.13.1.

. Reverter a configuração do cluster do nó:
+
[source, cli]
----
system node revert-to -node <nodename> -version 9.x
----
+
A configuração do cluster é revertida e, em seguida, você é desconetado do clustershell.

. Aguarde o prompt de login; em seguida, digite *não* quando você for perguntado se deseja fazer login no systemshell.
+
Pode demorar até 30 minutos ou mais para que o prompt de login apareça.

. Faça login no clustershell com admin.
. Mude para o nodeshell:
+
[source, cli]
----
run -node <nodename>
----
+
Depois de fazer login no clustershell novamente, pode demorar alguns minutos até que ele esteja pronto para aceitar o comando nodeshell. Então, se o comando falhar, aguarde alguns minutos e tente novamente.

. Reverter a configuração do sistema de arquivos do nó:
+
[source, cli]
----
revert_to 9.x
----
+
Este comando verifica se a configuração do sistema de arquivos do nó está pronta para ser revertida e, em seguida, reverte-a. Se quaisquer pré-condições forem identificadas, você deve abordá-las e, em seguida, executar novamente o `revert_to` comando.

+

NOTE: Usar um console do sistema para monitorar o processo de reversão exibe maiores detalhes do que o visto no nodeshell.

+
Se AUTOBOOT for true, quando o comando terminar, o nó será reiniciado para ONTAP.

+
Se AUTOBOOT for false, quando o comando terminar, o prompt Loader será exibido. Digite `yes` para reverter; em seguida, use `boot_ontap` para reinicializar manualmente o nó.

. Depois que o nó reiniciar, confirme se o novo software está em execução:
+
[source, cli]
----
system node image show
----
+
No exemplo a seguir, image1 é a nova versão do ONTAP e é definida como a versão atual no node0:

+
[listing]
----
cluster1::*> system node image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    X.X.X       MM/DD/YYYY TIME
         image2  false   false   Y.Y.Y      MM/DD/YYYY TIME
node1
         image1  true    false   X.X.X      MM/DD/YYYY TIME
         image2  false   true    Y.Y.Y      MM/DD/YYYY TIME
4 entries were displayed.
----
. Verifique se o status de reversão para o nó está concluído:
+
[source, cli]
----
system node upgrade-revert show -node <nodename>
----
+
O status deve ser listado como "completo", "não necessário" ou "não há entradas de tabela retornadas."

. Repita essas etapas no outro nó do par de HA e, em seguida, repita essas etapas para cada par de HA adicional.
+
Se você tiver uma Configuração do MetroCluster, precisará repetir essas etapas em ambos os clusters na configuração

. Depois de todos os nós terem sido revertidos, reative a alta disponibilidade para o cluster:
+
[source, cli]
----
cluster ha modify -configured true
----


--
.cluster de 2 nós
--
. Faça login no nó que você deseja reverter.
+
Para reverter um nó, você deve estar conetado ao cluster por meio do LIF de gerenciamento de nós do nó.

. Desativar a alta disponibilidade do cluster (HA):
+
[source, cli]
----
cluster ha modify -configured false
----
. Desativar failover de armazenamento:
+
[source, cli]
----
storage failover modify -node <nodename> -enabled false
----
+
Você só precisa desativar o failover de storage uma vez para o par de HA. Quando você desativa o failover de armazenamento para um nó, o failover de armazenamento também é desativado no parceiro do nó.

. Defina a imagem de software ONTAP de destino do nó para ser a imagem padrão:
+
[source, cli]
----
system image modify -node <nodename> -image <target_image> -isdefault true
----
. Verifique se a imagem do software ONTAP de destino está definida como a imagem padrão para o nó que você está revertendo:
+
[source, cli]
----
system image show
----
+
O exemplo a seguir mostra que a versão 9,1 está definida como a imagem padrão no node0:

+
[listing]
----
cluster1::*> system image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  false   true    9.2        MM/DD/YYYY TIME
         image2  true    false   9.1        MM/DD/YYYY TIME
node1
         image1  true    true    9.2        MM/DD/YYYY TIME
         image2  false   false   9.1        MM/DD/YYYY TIME
4 entries were displayed.
----
. Verifique se o nó atualmente contém epsilon:
+
[source, cli]
----
cluster show -node <nodename>
----
+
O exemplo a seguir mostra que o nó contém epsilon:

+
[listing]
----
cluster1::*> cluster show -node node1

          Node: node1
          UUID: 026efc12-ac1a-11e0-80ed-0f7eba8fc313
       Epsilon: true
   Eligibility: true
        Health: true
----
+
.. Se o nó possuir epsilon, marque epsilon como false no nó para que o epsilon possa ser transferido para o parceiro do nó:
+
[source, cli]
----
cluster modify -node <nodename> -epsilon false
----
.. Transfira o epsilon para o parceiro do nó marcando o epsilon true no nó do parceiro:
+
[source, cli]
----
cluster modify -node <node_partner_name> -epsilon true
----


. Verifique se o nó está pronto para reversão:
+
[source, cli]
----
system node revert-to -node <nodename> -check-only true -version 9.x
----
+
O `check-only` parâmetro identifica quaisquer condições que devem ser abordadas antes de reverter, como desabilitar a política de snapshot ou excluir snapshots que foram criados após a atualização para a versão posterior do ONTAP.

+
A `-version` opção refere-se à versão ONTAP para a qual você está revertendo. Por exemplo, se você estiver revertendo de 9.14.1 para 9.13.1, o valor correto `-version` da opção é 9.13.1.

+
A configuração do cluster é revertida e, em seguida, você é desconetado do clustershell.

. Reverter a configuração do cluster do nó:
+
[source, cli]
----
system node revert-to -node <nodename> -version 9.x
----
. Aguarde o prompt de login; em seguida, digite `No` quando você for perguntado se deseja fazer login no systemshell.
+
Pode demorar até 30 minutos ou mais para que o prompt de login apareça.

. Faça login no clustershell com admin.
. Mude para o nodeshell:
+
[source, cli]
----
run -node <nodename>
----
+
Depois de fazer login no clustershell novamente, pode demorar alguns minutos até que ele esteja pronto para aceitar o comando nodeshell. Então, se o comando falhar, aguarde alguns minutos e tente novamente.

. Reverter a configuração do sistema de arquivos do nó:
+
[source, cli]
----
revert_to 9.x
----
+
Este comando verifica se a configuração do sistema de arquivos do nó está pronta para ser revertida e, em seguida, reverte-a. Se quaisquer pré-condições forem identificadas, você deve abordá-las e, em seguida, executar novamente o `revert_to` comando.

+

NOTE: Usar um console do sistema para monitorar o processo de reversão exibe maiores detalhes do que o visto no nodeshell.

+
Se AUTOBOOT for true, quando o comando terminar, o nó será reiniciado para ONTAP.

+
Se AUTOBOOT for false, quando o comando terminar, o prompt Loader será exibido. Digite `yes` para reverter; em seguida, use `boot_ontap` para reinicializar manualmente o nó.

. Depois que o nó reiniciar, confirme se o novo software está em execução:
+
[source, cli]
----
system node image show
----
+
No exemplo a seguir, image1 é a nova versão do ONTAP e é definida como a versão atual no node0:

+
[listing]
----
cluster1::*> system node image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    X.X.X       MM/DD/YYYY TIME
         image2  false   false   Y.Y.Y      MM/DD/YYYY TIME
node1
         image1  true    false   X.X.X      MM/DD/YYYY TIME
         image2  false   true    Y.Y.Y      MM/DD/YYYY TIME
4 entries were displayed.
----
. Verifique se o status Reverter está concluído para o nó:
+
[source, cli]
----
system node upgrade-revert show -node <nodename>
----
+
O status deve ser listado como "completo", "não necessário" ou "não há entradas de tabela retornadas."

. Repita essas etapas no outro nó no par de HA.
. Depois que ambos os nós tiverem sido revertidos, reative a alta disponibilidade para o cluster:
+
[source, cli]
----
cluster ha modify -configured true
----
. Reative o failover de storage em ambos os nós:
+
[source, cli]
----
storage failover modify -node <nodename> -enabled true
----


--
====