---
permalink: revert/task-disable-tls-nvme-host.html 
sidebar: sidebar 
keywords: ontap, revert, reversion, reverting, tls, nvme, host, controller, subsystem, tls secure channel 
summary: Antes de reverter para uma versão anterior do ONTAP que não suporte TLS para hosts NVMe, você precisa desativar o TLS nos hosts NVMe. 
---
= Desative o canal seguro TLS em um host NVMe antes de reverter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.16,1, você pode configurar o canal seguro TLS para conexões NVMe/TCP. Se você tiver configurado o canal seguro TLS para conexões NVMe/TCP no ONTAP 9.16,1 ou versões posteriores, será necessário desativar a configuração TLS nos hosts NVMe antes de reverter o ONTAP para uma versão que não ofereça suporte ao canal seguro TLS para NVMe/TCP.

.Passos
. Remova a configuração de canal seguro TLS do host:
+
[source, cli]
----
vserver nvme subsystem host unconfigure-tls-for-revert -vserver <svm_name> -subsystem <subsystem> -host-nqn <host_nqn>
----
+
Este comando remove o host do subsistema e, em seguida, recria o host no subsistema sem a configuração TLS.

. Verifique se o canal seguro TLS é removido do host:
+
[source, cli]
----
vserver nvme subsystem host show
----


.Saiba mais
Visite as páginas do manual do ONTAP para estes comandos:

* https://docs.netapp.com/us-en/ontap-cli/vserver-nvme-subsystem-host-unconfigure-tls-for-revert.html["svm nvme subsistema host unconfigure-tls-for-revert"^]
* https://docs.netapp.com/us-en/ontap-cli/vserver-nvme-subsystem-host-show.html["mostra o host do subsistema nvme do svm"^]

