---
permalink: smb-admin/access-snapshot-directories-clients-smb2-concept.html 
sidebar: sidebar 
keywords: method, access, snapshot, directory, windows, client, smb, data, store, copies, copy, how to access the snapshot directory from windows clients using smb 2.x 
summary: O método usado para acessar o diretório instantâneo de clientes do Windows usando SMB 2.x difere do método usado para SMB 1,0. Você precisa entender como acessar o diretório instantâneo quando usar conexões SMB 2.x para acessar com êxito os dados armazenados em snapshots. 
---
= Aprenda sobre como acessar o diretório ONTAP ~snapshot de clientes Windows usando SMB 2.x
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O método usado para acessar o `~snapshot` diretório de clientes do Windows usando SMB 2.x difere do método usado para SMB 1,0. Você precisa entender como acessar o `~snapshot` diretório ao usar conexões SMB 2.x para acessar com êxito os dados armazenados em snapshots.

O administrador do SVM controla se os usuários em clientes Windows podem exibir e acessar o `~snapshot` diretório em um compartilhamento ativando ou desativando a `showsnapshot` propriedade de compartilhamento usando comandos das famílias de propriedades de compartilhamento cifs do vserver.

Quando a `showsnapshot` propriedade compartilhar está desativada, um usuário em um cliente Windows que usa SMB 2.x não pode exibir o `~snapshot` diretório e não pode acessar snapshots dentro do `~snapshot` diretório, mesmo quando manualmente inserir o caminho para `~snapshot` o diretório ou para snapshots específicos dentro do diretório.

Quando a `showsnapshot` propriedade compartilhar está ativada, um usuário em um cliente Windows que usa SMB 2.x ainda não pode exibir o `~snapshot` diretório na raiz do compartilhamento ou em qualquer junção ou diretório abaixo da raiz do compartilhamento. No entanto, depois de se conetar a um compartilhamento, o usuário pode acessar o diretório oculto `~snapshot` anexando manualmente `\~snapshot` ao final do caminho de compartilhamento. O diretório oculto `~snapshot` é acessível a partir de dois pontos de entrada:

* Na raiz da partilha
* Em cada ponto de junção no espaço de partilha


O diretório oculto `~snapshot` não é acessível a partir de subdiretórios que não sejam de junção dentro do compartilhamento.

.Exemplo
Com a configuração mostrada no exemplo a seguir, um usuário em um cliente Windows com uma conexão SMB 2.x ao compartilhamento "'eng'" pode acessar o `~snapshot` diretório anexando manualmente `\~snapshot` o caminho de compartilhamento na raiz do compartilhamento e em cada ponto de junção no caminho. O diretório oculto `~snapshot` é acessível a partir dos seguintes três caminhos:

* `\\vs1\eng\~snapshot`
* `\\vs1\eng\projects1\~snapshot`
* `\\vs1\eng\projects2\~snapshot`


[listing]
----
cluster1::> volume show -vserver vs1 -fields volume,junction-path
vserver volume       junction-path
------- ------------ ----------------------------------------
vs1     vs1_root      /
vs1     vs1_vol1      /eng
vs1     vs1_vol2      /eng/projects1
vs1     vs1_vol3      /eng/projects2

cluster1::> vserver cifs share show
Vserver  Share   Path     Properties    Comment  ACL
-------- ------  -------  ----------    -------- ----------
vs1      eng     /eng     oplocks       -        Everyone / Full Control
                          changenotify
                          browsable
                          showsnapshot
----