---
permalink: smb-admin/add-remove-share-properties-existing-share-task.html 
sidebar: sidebar 
keywords: customize, exist, smb, share, add, remove, removing, properties, useful, configuration, changing, change, requirement, environment, add or remove share properties on an existing smb share 
summary: Você pode personalizar um compartilhamento SMB existente adicionando ou removendo propriedades de compartilhamento. Isso pode ser útil se você quiser alterar a configuração de compartilhamento para atender às mudanças nos requisitos do seu ambiente. 
---
= Adicione ou remova propriedades de compartilhamento em compartilhamentos SMB existentes do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode personalizar um compartilhamento SMB existente adicionando ou removendo propriedades de compartilhamento. Isso pode ser útil se você quiser alterar a configuração de compartilhamento para atender às mudanças nos requisitos do seu ambiente.

.Antes de começar
O compartilhamento cujas propriedades você deseja modificar deve existir.

.Sobre esta tarefa
Diretrizes para adicionar propriedades de compartilhamento:

* Você pode adicionar uma ou mais propriedades de compartilhamento usando uma lista delimitada por vírgulas.
* Quaisquer propriedades de compartilhamento que você especificou anteriormente permanecem em vigor.
+
As propriedades recém-adicionadas são anexadas à lista existente de propriedades de compartilhamento.

* Se você especificar um novo valor para as propriedades de compartilhamento que já são aplicadas ao compartilhamento, o valor recém-especificado substituirá o valor original.
* Não é possível remover propriedades de compartilhamento usando o `vserver cifs share properties add` comando.
+
Você pode usar o `vserver cifs share properties remove` comando para remover propriedades de compartilhamento.



Diretrizes para remover propriedades de compartilhamento:

* Você pode remover uma ou mais propriedades de compartilhamento usando uma lista delimitada por vírgulas.
* Todas as propriedades de compartilhamento que você especificou anteriormente, mas não as removem, permanecem em vigor.


.Passos
. Introduza o comando adequado:
+
|===
| Se você quiser... | Digite o comando... 


 a| 
Adicione propriedades de compartilhamento
 a| 
`+vserver cifs share properties add -vserver _vserver_name_ -share-name _share_name_ -share-properties _properties_,...+`



 a| 
Remover propriedades de compartilhamento
 a| 
`+vserver cifs share properties remove -vserver _vserver_name_ -share-name _share_name_ -share-properties _properties_,...+`

|===
. Verifique as configurações da propriedade de compartilhamento: `vserver cifs share show -vserver vserver_name -share-name share_name`


.Exemplos
O comando a seguir adiciona a `showsnapshot` propriedade share a uma ação chamada "hare1" no SVM VS1:

[listing]
----
cluster1::> vserver cifs share properties add -vserver vs1 -share-name share1 -share-properties showsnapshot

cluster1::> vserver cifs share show -vserver vs1
Vserver    Share   Path      Properties   Comment    ACL
---------  ------  --------  ----------   --------   -----------
vs1        share1  /share1   oplocks      -          Everyone / Full Control
                             browsable
                             changenotify
                             showsnapshot
----
O comando a seguir remove a `browsable` propriedade share de um compartilhamento chamado "hare2" no SVM VS1:

[listing]
----
cluster1::> vserver cifs share properties remove -vserver vs1 -share-name share2 -share-properties browsable

cluster1::> vserver cifs share show -vserver vs1
Vserver    Share   Path      Properties   Comment    ACL
---------  ------  --------  ----------   --------   -----------
vs1        share2  /share2   oplocks      -          Everyone / Full Control
                             changenotify
----
.Informações relacionadas
xref:commands-manage-shares-reference.adoc[Comandos para gerenciar compartilhamentos]
