---
permalink: smb-admin/apply-security-policies-file-task.html 
sidebar: sidebar 
keywords: apply, file, security, policy, svm, creating, create, folder, apply security policies 
summary: Aplicar uma política de segurança de arquivos a SVMs é a última etapa na criação e aplicação de ACLs NTFS a arquivos ou pastas. 
---
= Aplicar políticas de segurança ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aplicar uma política de segurança de arquivos a SVMs é a última etapa na criação e aplicação de ACLs NTFS a arquivos ou pastas.

.Sobre esta tarefa
Você pode aplicar as configurações de segurança definidas na diretiva de segurança a arquivos e pastas NTFS residentes em volumes FlexVol (NTFS ou estilo de segurança misto).


NOTE: Quando uma política de auditoria e SACLs associados são aplicados, todas as DACLs existentes são substituídas. Quando uma diretiva de segurança e suas DACLs associadas são aplicadas, todas as DACLs existentes são substituídas. Você deve revisar as políticas de segurança existentes antes de criar e aplicar novas.

.Passo
. Aplicar uma política de segurança: `vserver security file-directory apply -vserver vserver_name ‑policy-name policy_name`
+
`vserver security file-directory apply -vserver vs1 -policy-name policy1`

+
O trabalho de aplicação de política está agendado e o Código trabalho é devolvido.

+
[listing]
----
[Job 53322]Job is queued: Fsecurity Apply. Use the "Job show 53322 –id 53322" command to view the status of the operation
----

