---
permalink: smb-admin/applying-group-policy-objects-concept.html 
sidebar: sidebar 
keywords: cifs, server, support, group, policy, object, gpo, set, rule, attribute, apply, computer, active, directory, environment, domain 
summary: 'O servidor SMB oferece suporte a objetos de diretiva de grupo (GPOs), um conjunto de regras conhecidas como atributos de diretiva de grupo que se aplicam a computadores em um ambiente do ative Directory. Você pode usar GPOs para gerenciar centralmente as configurações de todas as máquinas virtuais de storage (SVMs) no cluster que pertence ao mesmo domínio do ative Directory.' 
---
= Aplicar objetos de Diretiva de Grupo à visão geral dos servidores SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Seu servidor SMB oferece suporte a objetos de Diretiva de Grupo (GPOs), um conjunto de regras conhecidas como _atributos de diretiva de grupo_ que se aplicam a computadores em um ambiente do ative Directory. Você pode usar GPOs para gerenciar centralmente as configurações de todas as máquinas virtuais de storage (SVMs) no cluster que pertence ao mesmo domínio do ative Directory.

Quando os GPOs estão ativados no servidor SMB, o ONTAP envia consultas LDAP ao servidor do ative Directory solicitando informações de GPO. Se houver definições de GPO aplicáveis ao servidor SMB, o servidor do ative Directory retornará as seguintes informações de GPO:

* Nome GPO
* Versão GPO atual
* Localização da definição GPO
* Listas de UUIDs (identificadores universalmente exclusivos) para conjuntos de políticas GPO


.Informações relacionadas
xref:secure-file-access-dynamic-access-control-concept.adoc[Protegendo o acesso aos arquivos usando o controle de acesso dinâmico (DAC)]

link:../nas-audit/index.html["Auditoria de SMB e NFS e rastreamento de segurança"]
