---
permalink: smb-admin/assign-privileges-concept.html 
sidebar: sidebar 
keywords: assign, privilege, direct, local, user, domain, group, capabilities, capability, how to assign privileges, supported privileges, list of supported privileges, smb 
summary: Você pode atribuir Privileges diretamente a usuários locais ou usuários de domínio. Como alternativa, você pode atribuir usuários a grupos locais cujos Privileges atribuídos correspondem aos recursos que você deseja que esses usuários tenham. 
---
= Saiba mais sobre os privilégios SMB do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode atribuir Privileges diretamente a usuários locais ou usuários de domínio. Como alternativa, você pode atribuir usuários a grupos locais cujos Privileges atribuídos correspondem aos recursos que você deseja que esses usuários tenham.

* Você pode atribuir um conjunto de Privileges a um grupo que você criar.
+
Em seguida, adicione um utilizador ao grupo que tem o Privileges que pretende que esse utilizador tenha.

* Você também pode atribuir usuários locais e usuários de domínio a grupos predefinidos cujo Privileges padrão corresponde ao Privileges que você deseja conceder a esses usuários.


.Informações relacionadas
* xref:manage-local-privileges.adoc[Adicionar, remover ou redefinir privilégios para usuários ou grupos locais ou de domínio]
* xref:configure-bypass-traverse-checking-concept.adoc[Aprenda sobre a configuração da verificação de desvio transversal]




[[list-of-supported-ontap-smb-privileges]]
== Lista de privilégios ONTAP SMB suportados

O ONTAP tem um conjunto predefinido de Privileges suportados. Alguns grupos locais predefinidos têm alguns desses Privileges adicionados a eles por padrão. Você também pode adicionar ou remover Privileges dos grupos predefinidos ou criar novos usuários ou grupos locais e adicionar Privileges aos grupos criados ou aos usuários e grupos de domínio existentes.

A tabela a seguir lista os Privileges suportados na máquina virtual de armazenamento (SVM) e fornece uma lista de grupos BUILTIN com Privileges atribuídos:

|===
| Nome do privilégio | Configuração de segurança padrão | Descrição 


 a| 
`SeTcbPrivilege`
 a| 
Nenhum
 a| 
Agir como parte do sistema operacional



 a| 
`SeBackupPrivilege`
 a| 
`BUILTIN\Administrators`, `BUILTIN\Backup Operators`
 a| 
Faça backup de arquivos e diretórios, substituindo quaisquer ACLs



 a| 
`SeRestorePrivilege`
 a| 
`BUILTIN\Administrators`, `BUILTIN\Backup Operators`
 a| 
Restaurar arquivos e diretórios, substituindo quaisquer ACLs. Definir qualquer SID de usuário ou grupo válido como proprietário do arquivo



 a| 
`SeTakeOwnershipPrivilege`
 a| 
`BUILTIN\Administrators`
 a| 
Assuma a propriedade de arquivos ou outros objetos



 a| 
`SeSecurityPrivilege`
 a| 
`BUILTIN\Administrators`
 a| 
Gerenciar a auditoria

Isso inclui a visualização, o dumping e a limpeza do log de segurança.



 a| 
`SeChangeNotifyPrivilege`
 a| 
`BUILTIN\Administrators` `BUILTIN\Backup Operators`, , `BUILTIN\Power Users` `BUILTIN\Users` , , , `Everyone`
 a| 
Verificação da travessa de derivação

Os usuários com esse privilégio não são obrigados a ter permissões de avanço (x) para percorrer pastas, links simbólicos ou junções.

|===
.Informações relacionadas
* xref:assign-privileges-concept.adoc[Saiba mais sobre como atribuir privilégios]
* xref:configure-bypass-traverse-checking-concept.adoc[Aprenda sobre a configuração da verificação de desvio transversal]

