---
permalink: smb-admin/authentication-access-security-concept.html 
sidebar: sidebar 
keywords: create, smb, connection, contain, svm, authenticate, domain, smb, server, support, authentication, method, ntlm, ntlmv1, ntlmv2, kerberos, default, method, user, ontap, how ontap handles smb client authentication 
summary: 'Antes que os usuários possam criar conexões SMB para acessar dados contidos no SVM, elas devem ser autenticadas pelo domínio ao qual o servidor SMB pertence. O servidor SMB suporta dois métodos de autenticação, Kerberos e NTLM (NTLMv1 ou NTLMv2). Kerberos é o método padrão usado para autenticar usuários de domínio.' 
---
= Saiba mais sobre como lidar com a autenticação de cliente SMB do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes que os usuários possam criar conexões SMB para acessar dados contidos no SVM, elas devem ser autenticadas pelo domínio ao qual o servidor SMB pertence. O servidor SMB suporta dois métodos de autenticação, Kerberos e NTLM (NTLMv1 ou NTLMv2). Kerberos é o método padrão usado para autenticar usuários de domínio.



== Autenticação Kerberos

O ONTAP oferece suporte à autenticação Kerberos ao criar sessões SMB autenticadas.

Kerberos é o serviço de autenticação principal do ative Directory. O servidor Kerberos, ou serviço KDC (Centro de distribuição de chaves Kerberos), armazena e recupera informações sobre princípios de segurança no ative Directory. Ao contrário do modelo NTLM, os clientes do ative Directory que desejam estabelecer uma sessão com outro computador, como o servidor SMB, contatam diretamente um KDC para obter suas credenciais de sessão.



== Autenticação NTLM

A autenticação de cliente NTLM é feita usando um protocolo de resposta de desafio baseado no conhecimento compartilhado de um segredo específico do usuário com base em uma senha.

Se um usuário criar uma conexão SMB usando uma conta de usuário local do Windows, a autenticação é feita localmente pelo servidor SMB usando NTLMv2.
