---
permalink: smb-admin/branchcache-recommendations-concept.html 
sidebar: sidebar 
keywords: configure, branchcache, recommendation, mind, smb, enable, caching, cache, branchcache recommendations 
summary: Antes de configurar o BranchCache, há certas recomendações que você deve ter em mente ao decidir quais compartilhamentos SMB você deseja ativar o armazenamento em cache do BranchCache. 
---
= Recomendações do BranchCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de configurar o BranchCache, há certas recomendações que você deve ter em mente ao decidir quais compartilhamentos SMB você deseja ativar o armazenamento em cache do BranchCache.

Você deve ter em mente as seguintes recomendações ao decidir em qual modo de operação usar e em quais compartilhamentos SMB para ativar o BranchCache:

* Os benefícios do BranchCache são reduzidos quando os dados a serem armazenados remotamente em cache são alterados com frequência.
* Os serviços BranchCache são benéficos para compartilhamentos que contêm conteúdo de arquivo que é reutilizado por vários clientes de escritório remoto ou por conteúdo de arquivo que é repetidamente acessado por um único usuário remoto.
* Considere ativar o armazenamento em cache para conteúdo somente leitura, como dados em cópias Snapshot e destinos SnapMirror.

