---
permalink: smb-admin/break-locks-task.html 
sidebar: sidebar 
keywords: file, lock, prevent, client, access, display, information, held, break, scenario, debug, application, break locks 
summary: Quando os bloqueios de arquivos estão impedindo o acesso do cliente aos arquivos, você pode exibir informações sobre os bloqueios atualmente mantidos e, em seguida, quebrar bloqueios específicos. Exemplos de cenários em que você pode precisar quebrar bloqueios incluem depuração de aplicativos. 
---
= Quebrar bloqueios ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando os bloqueios de arquivos estão impedindo o acesso do cliente aos arquivos, você pode exibir informações sobre os bloqueios atualmente mantidos e, em seguida, quebrar bloqueios específicos. Exemplos de cenários em que você pode precisar quebrar bloqueios incluem depuração de aplicativos.

.Sobre esta tarefa
O `vserver locks break` comando está disponível apenas no nível de privilégio avançado e superior. Saiba mais sobre `vserver locks break` o link:https://docs.netapp.com/us-en/ontap-cli/vserver-locks-break.html["Referência do comando ONTAP"^]na .

.Passos
. Para encontrar as informações que você precisa para quebrar um bloqueio, use o `vserver locks show` comando.
+
Saiba mais sobre `vserver locks show` o link:https://docs.netapp.com/us-en/ontap-cli/vserver-locks-show.html["Referência do comando ONTAP"^]na .

. Defina o nível de privilégio como avançado: `set -privilege advanced`
. Execute uma das seguintes ações:
+
|===
| Se você quiser quebrar um bloqueio especificando... | Digite o comando... 


 a| 
O nome do SVM, o nome do volume, o nome LIF e o caminho do arquivo
 a| 
`vserver locks break -vserver vserver_name -volume volume_name -path path -lif lif`



 a| 
A ID de bloqueio
 a| 
`vserver locks break -lockid UUID`

|===
. Voltar ao nível de privilégio de administrador: `set -privilege admin`


Saiba mais sobre os comandos descritos neste procedimento no link:https://docs.netapp.com/us-en/ontap-cli/["Referência do comando ONTAP"^].
