---
permalink: smb-admin/builtin-groups-default-privileges-reference.html 
sidebar: sidebar 
keywords: assign, membership, local, user, domain, predefined, builtin, ontap, predefined builtin groups and default privileges 
summary: Você pode atribuir a associação de um usuário local ou usuário de domínio a um conjunto predefinido de grupos BUILTIN fornecidos pelo ONTAP. Grupos predefinidos têm Privileges predefinidos atribuídos. 
---
= Grupos BUILTIN predefinidos e privilégios ONTAP SMB padrão
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode atribuir a associação de um usuário local ou usuário de domínio a um conjunto predefinido de grupos BUILTIN fornecidos pelo ONTAP. Grupos predefinidos têm Privileges predefinidos atribuídos.

A tabela a seguir descreve os grupos predefinidos:

|===
| Grupo BUILTIN predefinido | Privileges padrão 


 a| 
``BUILTIN\Administrators``LIVRAR-SE 544

Quando criada pela primeira vez, a conta local `Administrator`, com um RID de 500, é automaticamente feita um membro deste grupo. Quando a máquina virtual de storage (SVM) é unida a um domínio, o `domain\Domain Admins` grupo é adicionado ao grupo. Se o SVM sair do domínio, o `domain\Domain Admins` grupo será removido do grupo.
 a| 
* `SeBackupPrivilege`
* `SeRestorePrivilege`
* `SeSecurityPrivilege`
* `SeTakeOwnershipPrivilege`
* `SeChangeNotifyPrivilege`




 a| 
``BUILTIN\Power Users``LIVRAR-SE 547

Quando criado pela primeira vez, este grupo não tem nenhum membro. Os membros deste grupo têm as seguintes caraterísticas:

* Pode criar e gerenciar usuários e grupos locais.
* Não é possível adicionar a si mesmos ou qualquer outro objeto ao `BUILTIN\Administrators` grupo.

 a| 
`SeChangeNotifyPrivilege`



 a| 
``BUILTIN\Backup Operators``LIVRAR-SE 551

Quando criado pela primeira vez, este grupo não tem nenhum membro. Os membros deste grupo podem substituir as permissões de leitura e gravação em arquivos ou pastas se forem abertos com intenção de backup.
 a| 
* `SeBackupPrivilege`
* `SeRestorePrivilege`
* `SeChangeNotifyPrivilege`




 a| 
``BUILTIN\Users``LIVRAR-SE 545

Quando criado pela primeira vez, este grupo não tem nenhum membro (além do grupo especial implícito `Authenticated Users`). Quando o SVM é associado a um domínio, o `domain\Domain Users` grupo é adicionado a esse grupo. Se o SVM sair do domínio, o `domain\Domain Users` grupo será removido desse grupo.
 a| 
`SeChangeNotifyPrivilege`



 a| 
``Everyone``SID S-1-1-0

Este grupo inclui todos os utilizadores, incluindo convidados (mas não utilizadores anónimos). Este é um grupo implícito com uma associação implícita.
 a| 
`SeChangeNotifyPrivilege`

|===
.Informações relacionadas
* xref:builtin-groups-local-administrator-account-concept.adoc[Saiba mais sobre grupos BUILTIN e contas de administrador local em servidores]
* xref:list-supported-privileges-reference.adoc[Lista de Privileges suportados]
* xref:configure-bypass-traverse-checking-concept.adoc[Aprenda sobre a configuração da verificação de desvio transversal]

