---
permalink: smb-admin/change-local-user-account-passwords-task.html 
sidebar: sidebar 
keywords: change, local, user, account, password, useful, compromised, forgotten, change local user account passwords 
summary: Você pode alterar a senha da conta de um usuário local. Isso pode ser útil se a senha do usuário for comprometida ou se o usuário tiver esquecido a senha. 
---
= Altere as senhas da conta de usuário local
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pode alterar a palavra-passe da conta de um utilizador local. Isso pode ser útil se a senha do usuário for comprometida ou se o usuário tiver esquecido a senha.

.Passo
. Altere a senha executando a ação apropriada: `vserver cifs users-and-groups local-user set-password -vserver _vserver_name_ -user-name _user_name_`


.Exemplo
O exemplo a seguir define a senha do usuário local "'CIFS_Server'" associada à máquina virtual de armazenamento (SVM, anteriormente conhecida como SVM) VS1:

[listing]
----
cluster1::> vserver cifs users-and-groups local-user set-password -user-name CIFS_SERVER\sue -vserver vs1

Enter the new password:
Confirm the new password:
----
.Informações relacionadas
xref:enable-disable-password-complexity-local-users-task.adoc[Ativar ou desativar a complexidade de senha necessária para usuários SMB locais]

xref:display-server-security-settings-task.adoc[Exibindo informações sobre as configurações de segurança do servidor CIFS]
