---
permalink: smb-admin/client-performance-traditional-lease-oplocks-concept.html 
sidebar: sidebar 
keywords: traditional, oplocks, opportunistic, locks, lease, smb, client, client-side, read-ahead, file-sharing, write-behind, information, access, reducing, reduce, network, traffic, improve client performance with traditional and lease oplocks 
summary: 'Os oplocks tradicionais (bloqueios oportunistas) e os oplocks de leasing permitem que um cliente SMB em determinados cenários de compartilhamento de arquivos execute o armazenamento em cache do lado do cliente de informações de leitura antecipada, gravação e bloqueio. Um cliente pode então ler ou gravar em um arquivo sem lembrar regularmente o servidor de que precisa de acesso ao arquivo em questão. Isso melhora o desempenho reduzindo o tráfego de rede.' 
---
= Saiba mais sobre como melhorar o desempenho do cliente ONTAP SMB com os princípios tradicionais e de leasing
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os oplocks tradicionais (bloqueios oportunistas) e os oplocks de leasing permitem que um cliente SMB em determinados cenários de compartilhamento de arquivos execute o armazenamento em cache do lado do cliente de informações de leitura antecipada, gravação e bloqueio. Um cliente pode então ler ou gravar em um arquivo sem lembrar regularmente o servidor de que precisa de acesso ao arquivo em questão. Isso melhora o desempenho reduzindo o tráfego de rede.

Os calços de leasing são uma forma melhorada de oplocks disponíveis com o protocolo SMB 2,1 e posterior. Os locks permitem que um cliente obtenha e preserve o estado de cache do cliente em várias aberturas SMB originadas de si mesmo.

Os calços podem ser controlados de duas maneiras:

* Por uma propriedade share, usando o `vserver cifs share create` comando quando o compartilhamento é criado, ou o `vserver share properties` comando após a criação.
* Por uma propriedade de qtree, usando o `volume qtree create` comando quando a qtree é criada, ou os `volume qtree oplock` comandos após a criação.

