---
permalink: smb-admin/command-options-limit-client-resource-concept.html 
sidebar: sidebar 
keywords: option, vserver, cifs, modify, command, enable, control, resource, consumption, windows, client, bound, notify, request, command options to limit excessive windows client resource consumption 
summary: Opções para o comando modificar opções cifs vserver permitem controlar o consumo de recursos para clientes Windows. Isso pode ser útil se algum cliente estiver fora dos limites normais de consumo de recursos, por exemplo, se houver um número excepcionalmente alto de arquivos abertos, sessões abertas ou solicitações Change Notify. 
---
= Opções de comando para limitar o consumo excessivo de recursos do cliente Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As opções para o `vserver cifs options modify` comando permitem controlar o consumo de recursos para clientes Windows. Isso pode ser útil se algum cliente estiver fora dos limites normais de consumo de recursos, por exemplo, se houver um número excepcionalmente alto de arquivos abertos, sessões abertas ou solicitações Change Notify.

As seguintes opções para o `vserver cifs options modify` comando foram adicionadas para controlar o consumo de recursos do cliente Windows. Se o valor máximo de qualquer uma dessas opções for excedido, a solicitação será negada e uma mensagem EMS será enviada. Uma mensagem de aviso EMS também é enviada quando 80% do limite configurado para essas opções é atingido.

* `-max-opens-same-file-per-tree`
+
Número máximo de aberturas no mesmo arquivo por árvore CIFS

* `-max-same-user-sessions-per-connection`
+
Número máximo de sessões abertas pelo mesmo usuário por conexão

* `-max-same-tree-connect-per-session`
+
O número máximo de árvores se coneta no mesmo compartilhamento por sessão

* `-max-watches-set-per-tree`
+
Número máximo de relógios (também conhecido como _change notifica_) estabelecido por árvore



Consulte as páginas man para ver os limites padrão e para exibir a configuração atual.

A partir do ONTAP 9.4, os servidores que executam o SMB versão 2 ou posterior podem limitar o número de solicitações pendentes (_créditos SMB_) que o cliente pode enviar para o servidor em uma conexão SMB. O gerenciamento de créditos SMB é iniciado pelo cliente e controlado pelo servidor.

O número máximo de solicitações pendentes que podem ser concedidas em uma conexão SMB é controlado pela `-max-credits` opção. O valor padrão para essa opção é 128.
