---
permalink: smb-admin/commands-manage-ntfs-smb.html 
sidebar: sidebar 
keywords: ontap, command, managing, manage, security, descriptor, create, modify, delete, display, information, commands for managing ntfs security descriptors 
summary: 'Use os comandos do ONTAP para criar, modificar, excluir e exibir informações sobre descritores de segurança NTFS e entradas de controle de acesso (ACEs) em DACLs e SACLs. Você também pode usar os comandos do ONTAP para gerenciar políticas de segurança SMB, tarefas de política e trabalhos de política.' 
---
= Comandos ONTAP para gerenciar políticas de segurança NTFS e SMB e entradas de controle de acesso
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Use os comandos do ONTAP para criar, modificar, excluir e exibir informações sobre descritores de segurança NTFS e entradas de controle de acesso (ACEs) em DACLs e SACLs. Você também pode usar os comandos do ONTAP para gerenciar políticas de segurança SMB, tarefas de política e trabalhos de política.



== Comandos ONTAP para gerenciar descritores de segurança NTFS em servidores SMB

Existem comandos ONTAP específicos para gerenciar descritores de segurança. Você pode criar, modificar, excluir e exibir informações sobre descritores de segurança.

|===
| Se você quiser... | Use este comando... 


 a| 
Crie descritores de segurança NTFS
 a| 
`vserver security file-directory ntfs create`



 a| 
Modificar descritores de segurança NTFS existentes
 a| 
`vserver security file-directory ntfs modify`



 a| 
Exibir informações sobre descritores de segurança NTFS existentes
 a| 
`vserver security file-directory ntfs show`



 a| 
Excluir descritores de segurança NTFS
 a| 
`vserver security file-directory ntfs delete`

|===
Saiba mais sobre `vserver security file-directory ntfs` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+ntfs["Referência do comando ONTAP"^]na .



== Comandos ONTAP para gerenciar entradas de controle de acesso NTFS DACL em servidores SMB

Existem comandos ONTAP específicos para gerenciar entradas de controle de acesso DACL (ACEs). Você pode adicionar ACEs a DACLs NTFS a qualquer momento. Você também pode gerenciar DACLs NTFS existentes modificando, excluindo e exibindo informações sobre ACEs em DACLs.

|===
| Se você quiser... | Use este comando... 


 a| 
Crie ACEs e adicione-os a DACLs NTFS
 a| 
`vserver security file-directory ntfs dacl add`



 a| 
Modificar ACEs existentes em DACLs NTFS
 a| 
`vserver security file-directory ntfs dacl modify`



 a| 
Exibir informações sobre ACEs existentes em DACLs NTFS
 a| 
`vserver security file-directory ntfs dacl show`



 a| 
Remover ACEs existentes de DACLs NTFS
 a| 
`vserver security file-directory ntfs dacl remove`

|===
Saiba mais sobre `vserver security file-directory ntfs dacl` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+ntfs+dacl["Referência do comando ONTAP"^]na .



== Comandos ONTAP para gerenciar entradas de controle de acesso NTFS SACL em servidores SMB

Existem comandos ONTAP específicos para gerenciar entradas de controle de acesso SACL (ACEs). Você pode adicionar ACEs a SACLs NTFS a qualquer momento. Você também pode gerenciar SACLs NTFS existentes modificando, excluindo e exibindo informações sobre ACEs em SACLs.

|===
| Se você quiser... | Use este comando... 


 a| 
Crie ACEs e adicione-os a SACLs NTFS
 a| 
`vserver security file-directory ntfs sacl add`



 a| 
Modificar ACEs existentes em SACLs NTFS
 a| 
`vserver security file-directory ntfs sacl modify`



 a| 
Exibir informações sobre ACEs existentes em SACLs NTFS
 a| 
`vserver security file-directory ntfs sacl show`



 a| 
Remover ACEs existentes de SACLs NTFS
 a| 
`vserver security file-directory ntfs sacl remove`

|===
Saiba mais sobre `vserver security file-directory ntfs sacl` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+ntfs+sacl["Referência do comando ONTAP"^]na .



== Comandos ONTAP para gerenciar políticas de segurança de SMB

Existem comandos ONTAP específicos para gerenciar políticas de segurança. Você pode exibir informações sobre políticas e excluir políticas. Não é possível modificar uma política de segurança.

|===
| Se você quiser... | Use este comando... 


 a| 
Crie políticas de segurança
 a| 
`vserver security file-directory policy create`



 a| 
Exibir informações sobre políticas de segurança
 a| 
`vserver security file-directory policy show`



 a| 
Eliminar políticas de segurança
 a| 
`vserver security file-directory policy delete`

|===
Saiba mais sobre `vserver security file-directory policy` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+policy["Referência do comando ONTAP"^]na .



== Comandos ONTAP para gerenciar tarefas de política de segurança de SMB

Existem comandos ONTAP para adicionar, modificar, remover e exibir informações sobre tarefas de diretiva de segurança.

|===
| Se você quiser... | Use este comando... 


 a| 
Adicione tarefas de política de segurança
 a| 
`vserver security file-directory policy task add`



 a| 
Modificar tarefas de política de segurança
 a| 
`vserver security file-directory policy task modify`



 a| 
Exibir informações sobre as tarefas da diretiva de segurança
 a| 
`vserver security file-directory policy task show`



 a| 
Remover tarefas de política de segurança
 a| 
`vserver security file-directory policy task remove`

|===
Saiba mais sobre `vserver security file-directory policy task` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+policy+task["Referência do comando ONTAP"^]na .



== Comandos ONTAP para gerenciar tarefas de política de segurança de SMB

Existem comandos ONTAP para pausar, retomar, parar e exibir informações sobre tarefas de diretiva de segurança.

|===
| Se você quiser... | Use este comando... 


 a| 
Pausar trabalhos de diretiva de segurança
 a| 
`vserver security file-directory job pause ‑vserver vserver_name -id integer`



 a| 
Retomar os trabalhos de política de segurança
 a| 
`vserver security file-directory job resume ‑vserver vserver_name -id integer`



 a| 
Exibir informações sobre os trabalhos de diretiva de segurança
 a| 
`vserver security file-directory job show ‑vserver vserver_name` Pode determinar a ID da tarefa de uma tarefa utilizando este comando.



 a| 
Interromper trabalhos de política de segurança
 a| 
`vserver security file-directory job stop ‑vserver vserver_name -id integer`

|===
Saiba mais sobre `vserver security file-directory job` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+job["Referência do comando ONTAP"^]na .
