---
permalink: smb-admin/commands-manage-security-policy-tasks-reference.html 
sidebar: sidebar 
keywords: ontap, command, add, modify, removing, remove, display, information, security, policy, task, commands for managing security policy tasks 
summary: Existem comandos ONTAP para adicionar, modificar, remover e exibir informações sobre tarefas de diretiva de segurança. 
---
= Comandos para gerenciar tarefas de diretiva de segurança
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Existem comandos ONTAP para adicionar, modificar, remover e exibir informações sobre tarefas de diretiva de segurança.

|===
| Se você quiser... | Use este comando... 


 a| 
Adicione tarefas de política de segurança
 a| 
`vserver security file-directory policy task add`



 a| 
Modificar tarefas de política de segurança
 a| 
`vserver security file-directory policy task modify`



 a| 
Exibir informações sobre as tarefas da diretiva de segurança
 a| 
`vserver security file-directory policy task show`



 a| 
Remover tarefas de política de segurança
 a| 
`vserver security file-directory policy task remove`

|===
Consulte as páginas de manual para `vserver security file-directory policy task` obter mais informações.
