---
permalink: smb-admin/commands-manage-servers-reference.html 
sidebar: sidebar 
keywords: command, creating, create, display, modify, stop, start, deleting, delete 
summary: Você precisa saber os comandos para criar, exibir, modificar, parar, iniciar e excluir servidores SMB. Há também comandos para redefinir e redescobrir servidores, alterar ou redefinir senhas de conta de máquina, agendar alterações para senhas de conta de máquina e adicionar ou remover aliases NetBIOS. 
---
= Comandos ONTAP para gerenciar servidores SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você precisa saber os comandos para criar, exibir, modificar, parar, iniciar e excluir servidores SMB. Há também comandos para redefinir e redescobrir servidores, alterar ou redefinir senhas de conta de máquina, agendar alterações para senhas de conta de máquina e adicionar ou remover aliases NetBIOS.

|===


| Se você quiser... | Use este comando... 


 a| 
Crie um servidor SMB
 a| 
`vserver cifs create`



 a| 
Exibir informações sobre um servidor SMB
 a| 
`vserver cifs show`



 a| 
Modifique um servidor SMB
 a| 
`vserver cifs modify`



 a| 
Mova um servidor SMB para outro domínio
 a| 
`vserver cifs modify`



 a| 
Parar um servidor SMB
 a| 
`vserver cifs stop`



 a| 
Inicie um servidor SMB
 a| 
`vserver cifs start`



 a| 
Excluir um servidor SMB
 a| 
`vserver cifs delete`



 a| 
Redefinir e redescobrir servidores para o servidor SMB
 a| 
`vserver cifs domain discovered-servers reset-servers`



 a| 
Altere a senha da conta de máquina do servidor SMB
 a| 
`vserver cifs domain password change`



 a| 
Redefina a senha da conta da máquina do servidor SMB
 a| 
`vserver cifs domain password change`



 a| 
Agendar alterações automáticas de senha para a conta de máquina do servidor SMB
 a| 
`vserver cifs domain password schedule modify`



 a| 
Adicione aliases NetBIOS para o servidor SMB
 a| 
`vserver cifs add-netbios-aliases`



 a| 
Remova os aliases NetBIOS para o servidor SMB
 a| 
`vserver cifs remove-netbios-aliases`

|===
Saiba mais sobre `vserver cifs` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs["Referência do comando ONTAP"^]na .

.Informações relacionadas
link:local-users-groups-when-deleting-servers-concept.html["O que acontece com usuários e grupos locais ao excluir servidores SMB"]
