---
permalink: smb-admin/commands-manage-ntfs-sacl-reference.html 
sidebar: sidebar 
keywords: ontap, command, managing, manage, managing, sacl, access, control, entries, aces, ntfs, exist, modify, deleting, delete, display, commands for managing ntfs sacl access control entries 
summary: 'Existem comandos ONTAP específicos para gerenciar entradas de controle de acesso SACL (ACEs). Você pode adicionar ACEs a SACLs NTFS a qualquer momento. Você também pode gerenciar SACLs NTFS existentes modificando, excluindo e exibindo informações sobre ACEs em SACLs.' 
---
= Comandos para gerenciar entradas de controle de acesso NTFS SACL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Existem comandos ONTAP específicos para gerenciar entradas de controle de acesso SACL (ACEs). Você pode adicionar ACEs a SACLs NTFS a qualquer momento. Você também pode gerenciar SACLs NTFS existentes modificando, excluindo e exibindo informações sobre ACEs em SACLs.

|===
| Se você quiser... | Use este comando... 


 a| 
Crie ACEs e adicione-os a SACLs NTFS
 a| 
`vserver security file-directory ntfs sacl add`



 a| 
Modificar ACEs existentes em SACLs NTFS
 a| 
`vserver security file-directory ntfs sacl modify`



 a| 
Exibir informações sobre ACEs existentes em SACLs NTFS
 a| 
`vserver security file-directory ntfs sacl show`



 a| 
Remover ACEs existentes de SACLs NTFS
 a| 
`vserver security file-directory ntfs sacl remove`

|===
Consulte as páginas de manual para `vserver security file-directory ntfs sacl` obter mais informações.
