---
permalink: smb-admin/commands-oplocks-volumes-qtrees-reference.html 
sidebar: sidebar 
keywords: oplock, client, lock, file, cache, performance, operation, qtree, command, enabling, enable, disabling, disable, volume, commands for enabling or disabling oplocks on volumes and qtrees 
summary: Oplocks permitem que os clientes bloqueiem arquivos e armazenem conteúdo de cache localmente, o que pode aumentar o desempenho para operações de arquivos. Você precisa saber os comandos para ativar ou desativar os oplocks em volumes ou qtrees. Você também deve saber quando você pode ativar ou desativar os oplocks em volumes e qtrees. 
---
= Comandos ONTAP para ativar ou desativar os oplocks em volumes SMB e qtrees
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Oplocks permitem que os clientes bloqueiem arquivos e armazenem conteúdo de cache localmente, o que pode aumentar o desempenho para operações de arquivos. Você precisa saber os comandos para ativar ou desativar os oplocks em volumes ou qtrees. Você também deve saber quando você pode ativar ou desativar os oplocks em volumes e qtrees.

* Os calços são ativados em volumes por predefinição.
* Não é possível desativar os oplocks ao criar um volume.
* Você pode ativar ou desativar os oplocks em volumes existentes para SVMs a qualquer momento.
* Você pode ativar os oplocks em qtrees para SVMs.
+
A configuração do modo de oplock é uma propriedade da ID de qtree 0, a qtree padrão que todos os volumes têm. Se você não especificar uma configuração de oplock ao criar uma qtree, a qtree herdará a configuração de oplock do volume pai, que é habilitada por padrão. No entanto, se você especificar uma configuração de oplock na nova qtree, ela terá precedência sobre a configuração de oplock no volume.



|===
| Se você quiser... | Use este comando... 


 a| 
Ative os oplocks em volumes ou qtrees
 a| 
`volume qtree oplocks` com o `-oplock-mode` parâmetro definido como `enable`



 a| 
Desative os oplocks em volumes ou qtrees
 a| 
`volume qtree oplocks` com o `-oplock-mode` parâmetro definido como `disable`

|===
.Informações relacionadas
xref:monitor-oplock-status-task.adoc[Monitorar o status de oplock]
