---
permalink: smb-admin/commands-manage-character-mappings-file-name-reference.html 
sidebar: sidebar 
keywords: manage, character, mapping, creating, create, modify, information, deleting, delete, file, smb, translation, flexvol, volume, commands for managing character mappings for smb file name translation 
summary: É possível gerenciar o mapeamento de carateres criando, modificando, exibindo informações ou excluindo mapeamentos de carateres de arquivo usados para a tradução de nomes de arquivo SMB em volumes FlexVol. 
---
= Comandos para gerenciar mapeamentos de carateres para a tradução de nome de arquivo SMB no ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível gerenciar o mapeamento de carateres criando, modificando, exibindo informações ou excluindo mapeamentos de carateres de arquivo usados para a tradução de nomes de arquivo SMB em volumes FlexVol.

|===
| Se você quiser... | Use este comando... 


 a| 
Criar novos mapeamentos de carateres de arquivo
 a| 
`vserver cifs character-mapping create`



 a| 
Exibir informações sobre mapeamentos de carateres de arquivo
 a| 
`vserver cifs character-mapping show`



 a| 
Modificar mapeamentos de carateres de arquivo existentes
 a| 
`vserver cifs character-mapping modify`



 a| 
Excluir mapeamentos de carateres de arquivo
 a| 
`vserver cifs character-mapping delete`

|===
Saiba mais sobre `vserver cifs character-mapping` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs+character-mapping["Referência do comando ONTAP"^]na .

.Informações relacionadas
xref:configure-character-mappings-file-name-translation-task.adoc[Configurando o mapeamento de carateres para a tradução de nome de arquivo SMB em volumes]
