---
permalink: smb-admin/configure-security-styles-qtrees-task.html 
sidebar: sidebar 
keywords: configure, qtree, volume, security, style, permission, data, configure security styles on qtrees 
summary: Você configura o estilo de segurança do volume de qtree para determinar o tipo de permissões usadas para dados no qtrees. 
---
= Configurar estilos de segurança no qtrees
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você configura o estilo de segurança do volume de qtree para determinar o tipo de permissões usadas para dados no qtrees.

.Passos
. Execute uma das seguintes ações:
+
|===
| Se a qtree... | Use o comando... 


 a| 
Ainda não existe
 a| 
`volume qtree create` e inclua o `-security-style` parâmetro para especificar o estilo de segurança.



 a| 
Já existe
 a| 
`volume qtree modify` e inclua o `-security-style` parâmetro para especificar o estilo de segurança.

|===
+
As opções possíveis para o estilo de segurança de qtree são `unix`, `ntfs`, ou `mixed`.

+
Se você não especificar um estilo de segurança ao criar uma qtree, o estilo de segurança padrão será `mixed`.

+
Para obter mais informações sobre os `volume qtree create` comandos ou `volume qtree modify`, link:../volumes/index.html["Gerenciamento de storage lógico"]consulte .

. Para exibir a configuração, incluindo o estilo de segurança da qtree que você criou, digite o seguinte comando: `volume qtree show -qtree qtree_name -instance`

