---
permalink: smb-admin/control-domain-controller-discovery-task.html 
sidebar: sidebar 
keywords: ontap, modify, default, process, domain, controller, dc, enable, limit, site, pool, performance, improvement, environment, manage, manage domain controller discovery 
summary: 'A partir do ONTAP 9.3, você pode modificar o processo padrão pelo qual controladores de domínio (DCs) são descobertos. Isso permite limitar a descoberta ao seu site ou a um pool de DCs preferenciais, o que pode levar a melhorias de desempenho, dependendo do ambiente.' 
---
= Gerenciar a descoberta do controlador de domínio SMB do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.3, você pode modificar o processo padrão pelo qual controladores de domínio (DCs) são descobertos. Isso permite limitar a descoberta ao seu site ou a um pool de DCs preferenciais, o que pode levar a melhorias de desempenho, dependendo do ambiente.

.Sobre esta tarefa
Por padrão, o processo de descoberta dinâmica descobre todos os DCs disponíveis, incluindo todos os DCs preferenciais, todos os DCs no local e todos os DCs remotos. Essa configuração pode levar à latência na autenticação e ao acesso a compartilhamentos em determinados ambientes. Se você já determinou o pool de DCs que deseja usar, ou se os DCs remotos são inadequados ou inacessíveis, você pode alterar o método de descoberta.

No ONTAP 9.3 e versões posteriores, o `discovery-mode` parâmetro `cifs domain discovered-servers` do comando permite selecionar uma das seguintes opções de descoberta:

* Todos os DCs no domínio são descobertos.
* Apenas DCs no local são descobertos.
+
O `default-site` parâmetro para o servidor SMB pode ser definido para usar esse modo com LIFs que não são atribuídos a um site em sites e serviços.

* A deteção de servidor não é realizada, a configuração do servidor SMB depende apenas de DCs preferenciais.
+
Para utilizar este modo, tem de definir primeiro os DCs preferidos para o servidor SMB.



.Antes de começar
Você deve estar no nível de privilégio avançado.

.Passo
. Especifique a opção de descoberta desejada: `vserver cifs domain discovered-servers discovery-mode modify -vserver _vserver_name_ -mode {all|site|none}`
+
Opções para o `mode` parâmetro:

+
** `all`
+
Descubra todos os DCs disponíveis (padrão).

** `site`
+
Limite a descoberta DC ao seu site.

** `none`
+
Use apenas DCs preferenciais e não execute a descoberta.




