---
permalink: smb-admin/create-configure-shares-concept.html 
sidebar: sidebar 
keywords: user, application, access, data, cifs, server, smb, create, configure, smb, share, name, point, volume, customize, parameter, properties, property, modify, exist, create and configure smb shares 
summary: Para que usuários e aplicativos possam acessar dados no servidor CIFS em SMB, você deve criar e configurar compartilhamentos SMB, que é um ponto de acesso nomeado em um volume. Você pode personalizar compartilhamentos especificando parâmetros de compartilhamento e propriedades de compartilhamento. Você pode modificar um compartilhamento existente a qualquer momento. 
---
= Saiba mais sobre como criar e configurar compartilhamentos SMB do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para que usuários e aplicativos possam acessar dados no servidor CIFS em SMB, você deve criar e configurar compartilhamentos SMB, que é um ponto de acesso nomeado em um volume. Você pode personalizar compartilhamentos especificando parâmetros de compartilhamento e propriedades de compartilhamento. Você pode modificar um compartilhamento existente a qualquer momento.

Quando você cria um compartilhamento SMB, o ONTAP cria uma ACL padrão para as permissões de compartilhamento com controle total para todos.

Os compartilhamentos SMB estão vinculados ao servidor CIFS na máquina virtual de storage (SVM). Os compartilhamentos de SMB serão excluídos se o SVM for excluído ou se o servidor CIFS ao qual ele está associado for excluído do SVM. Se você recriar o servidor CIFS na SVM, será necessário recriar os compartilhamentos SMB.

.Informações relacionadas
xref:local-users-groups-concepts-concept.html[Gerencie o acesso a arquivos usando SMB]

link:../smb-hyper-v-sql/index.html["Configuração SMB para Microsoft Hyper-V e SQL Server"]

xref:configure-character-mappings-file-name-translation-task.adoc[Configure o mapeamento de carateres para a tradução de nomes de arquivo SMB em volumes]
