---
permalink: smb-admin/create-snapshot-config-previous-versions-access-task.html 
sidebar: sidebar 
keywords: previous, version, functionality, available, client, access, snapshot, copies, copy, enable, snapshot, exist, configuration, requirement, create a snapshot configuration to enable previous versions access 
summary: A funcionalidade de versões anteriores está sempre disponível, desde que o acesso do cliente às cópias Snapshot esteja habilitado e desde que existam cópias Snapshot. Se a configuração da cópia Snapshot não atender a esses requisitos, você poderá criar uma configuração de cópia Snapshot correspondente. 
---
= Crie uma configuração Snapshot para habilitar o acesso a versões anteriores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A funcionalidade de versões anteriores está sempre disponível, desde que o acesso do cliente às cópias Snapshot esteja habilitado e desde que existam cópias Snapshot. Se a configuração da cópia Snapshot não atender a esses requisitos, você poderá criar uma configuração de cópia Snapshot correspondente.

.Passos
. Se o volume que contém o compartilhamento ao qual você deseja permitir o acesso a versões anteriores não tiver uma política Snapshot associada, associe uma política Snapshot ao volume e ative-a usando o `volume modify` comando.
+
Para obter mais informações sobre como usar o `volume modify` comando, consulte as páginas de manual.

. Habilite o acesso às cópias Snapshot usando o `volume modify` comando para definir a `-snap-dir` opção como `true`.
+
Para obter mais informações sobre como usar o `volume modify` comando, consulte as páginas de manual.

. Verifique se as políticas Snapshot estão ativadas e se o acesso aos diretórios Snapshot está ativado usando os `volume show` comandos e. `volume snapshot policy show`
+
Para obter mais informações sobre como usar os `volume show` comandos e `volume snapshot policy show`, consulte as páginas de manual.

+
Para obter mais informações sobre como configurar e gerenciar políticas de Snapshot e programações de snapshot, link:../data-protection/index.html["Proteção de dados"]consulte .



.Informações relacionadas
link:../data-protection/index.html["Proteção de dados"]
