---
permalink: smb-admin/create-ntfs-security-descriptor-file-task.html 
sidebar: sidebar 
keywords: create, creating, ntfs, security, descriptor, file, policy, configuring, configure, apply, access, control, acl, file, folder, residing, reside, storage, virtual, machine, svm, associate, task 
summary: 'Criar um descritor de segurança NTFS (política de segurança de arquivos) é a primeira etapa na configuração e aplicação de listas de controle de acesso (ACLs) NTFS a arquivos e pastas residentes em máquinas virtuais de armazenamento (SVMs). Você pode associar o descritor de segurança ao caminho do arquivo ou da pasta em uma tarefa de diretiva.' 
---
= Crie um descritor de segurança NTFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Criar um descritor de segurança NTFS (política de segurança de arquivos) é a primeira etapa na configuração e aplicação de listas de controle de acesso (ACLs) NTFS a arquivos e pastas residentes em máquinas virtuais de armazenamento (SVMs). Você pode associar o descritor de segurança ao caminho do arquivo ou da pasta em uma tarefa de diretiva.

.Sobre esta tarefa
Você pode criar descritores de segurança NTFS para arquivos e pastas que residem em volumes de estilo de segurança NTFS ou para arquivos e pastas que residem em volumes de estilo de segurança misto.

Por padrão, quando um descritor de segurança é criado, quatro entradas de controle de acesso (ACEs) da lista de controle de acesso discricionária (DACL) são adicionadas a esse descritor de segurança. Os quatro ACEs predefinidos são os seguintes:

|===
| Objeto | Tipo de acesso | Direitos de acesso | Onde aplicar as permissões 


 a| 
CRIAR/Administradores
 a| 
Permitir
 a| 
Controlo total
 a| 
esta pasta, subpastas, ficheiros



 a| 
CONSTRUIR/usuários
 a| 
Permitir
 a| 
Controlo total
 a| 
esta pasta, subpastas, ficheiros



 a| 
PROPRIETÁRIO DO CRIADOR
 a| 
Permitir
 a| 
Controlo total
 a| 
esta pasta, subpastas, ficheiros



 a| 
AUTORIDADE NT/SISTEMA
 a| 
Permitir
 a| 
Controlo total
 a| 
esta pasta, subpastas, ficheiros

|===
Você pode personalizar a configuração do descritor de segurança usando os seguintes parâmetros opcionais:

* Proprietário do descritor de segurança
* Grupo primário do proprietário
* Flags de controle bruto


O valor de qualquer parâmetro opcional é ignorado para o Storage-Level Access Guard. Consulte as páginas de manual para obter mais informações.
