---
permalink: smb-admin/create-snapshot-config-previous-versions-access-task.html 
sidebar: sidebar 
keywords: previous, version, functionality, available, client, access, snapshot, copies, copy, enable, snapshot, exist, configuration, requirement, create a snapshot configuration to enable previous versions access 
summary: A funcionalidade versões anteriores está sempre disponível, desde que o acesso do cliente a instantâneos esteja ativado e desde que existam instantâneos. Se a configuração do snapshot não atender a esses requisitos, você poderá criar uma configuração de snapshot que o atenda. 
---
= Crie configurações de snapshot ONTAP SMB para habilitar o acesso às versões anteriores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A funcionalidade versões anteriores está sempre disponível, desde que o acesso do cliente a instantâneos esteja ativado e desde que existam instantâneos. Se a configuração do snapshot não atender a esses requisitos, você poderá criar uma configuração de snapshot que o atenda.

.Passos
. Se o volume que contém o compartilhamento ao qual você deseja permitir o acesso a versões anteriores não tiver uma política de snapshot associada, associe uma política de snapshot ao volume e ative-a usando o `volume modify` comando.
+
Saiba mais sobre `volume modify` o link:https://docs.netapp.com/us-en/ontap-cli/volume-modify.html["Referência do comando ONTAP"^]na .

. Ative o acesso aos instantâneos usando o `volume modify` comando para definir a `-snap-dir` opção como `true`.
+
Saiba mais sobre `volume modify` o link:https://docs.netapp.com/us-en/ontap-cli/volume-modify.html["Referência do comando ONTAP"^]na .

. Verifique se as políticas de snapshot estão ativadas e se o acesso aos diretórios de snapshot está ativado usando os `volume show` comandos e. `volume snapshot policy show`
+
Saiba mais sobre `volume show` e `volume snapshot policy show` no link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume+show["Referência do comando ONTAP"^].

+
Para obter mais informações sobre como configurar e gerenciar políticas de snapshot e programações de snapshot, link:../data-protection/index.html["Proteção de dados"]consulte .



.Informações relacionadas
link:../data-protection/index.html["Proteção de dados"]
