---
permalink: smb-admin/decide-security-style-svm-flexvol-concept.html 
sidebar: sidebar 
keywords: security, style, volume, factor, primary, administrator, manage, file, system, type, secondary, service, access, data, how to decide which security style to use on svms 
summary: Para ajudá-lo a decidir qual estilo de segurança usar em um volume, você deve considerar dois fatores. O fator principal é o tipo de administrador que gerencia o sistema de arquivos. O fator secundário é o tipo de usuário ou serviço que acessa os dados no volume. 
---
= Decida quais estilos de segurança SMB usar em SVMs ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para ajudá-lo a decidir qual estilo de segurança usar em um volume, você deve considerar dois fatores. O fator principal é o tipo de administrador que gerencia o sistema de arquivos. O fator secundário é o tipo de usuário ou serviço que acessa os dados no volume.

Ao configurar o estilo de segurança em um volume, você deve considerar as necessidades do seu ambiente para garantir que você selecione o melhor estilo de segurança e evite problemas com o gerenciamento de permissões. As seguintes considerações podem ajudá-lo a decidir:

|===
| Estilo de segurança | Escolha se... 


 a| 
UNIX
 a| 
* O sistema de arquivos é gerenciado por um administrador UNIX.
* A maioria dos usuários são clientes NFS.
* Um aplicativo que acessa os dados usa um usuário UNIX como a conta de serviço.




 a| 
NTFS
 a| 
* O sistema de arquivos é gerenciado por um administrador do Windows.
* A maioria dos usuários são clientes SMB.
* Um aplicativo que acessa os dados usa um usuário do Windows como a conta de serviço.




 a| 
Misto
 a| 
O sistema de arquivos é gerenciado por administradores UNIX e Windows e os usuários consistem em clientes NFS e SMB.

|===