---
permalink: smb-admin/determine-clients-connected-netbios-aliases-task.html 
sidebar: sidebar 
keywords: determine, smb, client, connect, netbios, alias, connection, troubleshoot, issue, determine whether smb clients are connected using netbios aliases 
summary: Você pode determinar se os clientes SMB estão conetados usando aliases NetBIOS e, em caso afirmativo, qual alias NetBIOS é usado para fazer a conexão. Isso pode ser útil ao solucionar problemas de conexão. 
---
= Determine se os clientes SMB estão conetados usando aliases NetBIOS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode determinar se os clientes SMB estão conetados usando aliases NetBIOS e, em caso afirmativo, qual alias NetBIOS é usado para fazer a conexão. Isso pode ser útil ao solucionar problemas de conexão.

.Sobre esta tarefa
Você deve usar o `-instance` parâmetro para exibir o alias NetBIOS (se houver) associado a uma conexão SMB. Se o nome do servidor CIFS ou um endereço IP for usado para fazer a conexão SMB, a saída para o `NetBIOS Name` campo é `-` (hífen).

.Passo
. Execute a ação desejada:
+
|===
| Se você quiser exibir informações do NetBIOS para... | Digite... 


 a| 
Conexões SMB
 a| 
`vserver cifs session show -instance`



 a| 
Conexões usando um alias NetBIOS especificado:
 a| 
`vserver cifs session show -instance -netbios-name _netbios_name_`

|===
+
O exemplo a seguir exibe informações sobre o alias NetBIOS usado para fazer a conexão SMB com o Session ID 1:

+
`vserver cifs session show -session-id 1 -instance`

+
[listing]
----

                        Node: node1
                     Vserver: vs1
                  Session ID: 1
               Connection ID: 127834
Incoming Data LIF IP Address: 10.1.1.25
                 Workstation: 10.2.2.50
    Authentication Mechanism: NTLMv2
                Windows User: EXAMPLE\user1
                   UNIX User: user1
                 Open Shares: 2
                  Open Files: 2
                  Open Other: 0
              Connected Time: 1d 1h 10m 5s
                   Idle Time: 22s
            Protocol Version: SMB3
      Continuously Available: No
           Is Session Signed: true
       User Authenticated as: domain-user
                NetBIOS Name: ALIAS1
       SMB Encryption Status: Unencrypted
----

