---
permalink: smb-admin/determine-snapshot-copies-available-task.html 
sidebar: sidebar 
keywords: view, snapshot, copies, copy, previous, version, enable, policy, applied, apply, contain, share, previous, version, access, determine whether snapshot copies are available for previous versions use 
summary: Você pode exibir snapshots da guia versões anteriores somente se uma política de snapshot habilitada for aplicada ao volume que contém o compartilhamento e se a configuração de volume permitir acesso a snapshots. Determinar a disponibilidade de instantâneos é útil ao ajudar um usuário com acesso a versões anteriores. 
---
= Determine se os instantâneos estão disponíveis para uso em versões anteriores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode exibir snapshots da guia versões anteriores somente se uma política de snapshot habilitada for aplicada ao volume que contém o compartilhamento e se a configuração de volume permitir acesso a snapshots. Determinar a disponibilidade de instantâneos é útil ao ajudar um usuário com acesso a versões anteriores.

.Passos
. Determine se o volume no qual residem os dados de compartilhamento tem snapshots automáticos ativados e se os clientes têm acesso a diretórios de snapshot: `volume show -vserver vserver-name -volume volume-name -fields vserver,volume,snapdir-access,snapshot-policy,snapshot-count`
+
A saída exibe qual política de snapshot está associada ao volume, se o acesso ao diretório de snapshot do cliente está habilitado e o número de snapshots disponíveis.

. Determine se a política de snapshot associada está ativada: `volume snapshot policy show -policy policy-name`
. Liste os instantâneos disponíveis: `volume snapshot show -volume volume_name`
+
Para obter mais informações sobre como configurar e gerenciar políticas de snapshot e programações de snapshot, link:../data-protection/index.html["Proteção de dados"]consulte .



.Exemplo
O exemplo a seguir exibe informações sobre políticas de snapshot associadas ao volume chamado "ATA1" que contém os dados compartilhados e os snapshots disponíveis em "ATA1".

[listing]
----
cluster1::> volume show -vserver vs1 -volume data1 -fields vserver,volume,snapshot-policy,snapdir-access,snapshot-count
vserver  volume snapdir-access snapshot-policy snapshot-count
-------- ------ -------------- --------------- --------------
vs1      data1  true           default         10

cluster1::> volume snapshot policy show -policy default
Vserver: cluster1
                   Number of Is
Policy Name        Schedules Enabled Comment
------------------ --------- ------- ----------------------------------
default                    3 true    Default policy with hourly, daily & weekly schedules.
    Schedule         Count     Prefix                 SnapMirror Label
    ---------------- -----     ---------------------- -------------------
    hourly               6     hourly                 -
    daily                2     daily                  daily
    weekly               2     weekly                 weekly

cluster1::> volume snapshot show -volume data1
                                                             ---Blocks---
Vserver  Volume  Snapshot                  State        Size Total% Used%
-------- ------- ------------------------- -------- -------- ------ -----
vs1      data1
                 weekly.2012-12-16_0015    valid       408KB     0%    1%
                 daily.2012-12-22_0010     valid       420KB     0%    1%
                 daily.2012-12-23_0010     valid       192KB     0%    0%
                 weekly.2012-12-23_0015    valid       360KB     0%    1%
                 hourly.2012-12-23_1405    valid       196KB     0%    0%
                 hourly.2012-12-23_1505    valid       196KB     0%    0%
                 hourly.2012-12-23_1605    valid       212KB     0%    0%
                 hourly.2012-12-23_1705    valid       136KB     0%    0%
                 hourly.2012-12-23_1805    valid       200KB     0%    0%
                 hourly.2012-12-23_1905    valid       184KB     0%    0%
----
.Informações relacionadas
xref:create-snapshot-config-previous-versions-access-task.adoc[Criando uma configuração de snapshot para habilitar o acesso a versões anteriores]

link:../data-protection/index.html["Proteção de dados"]
