---
permalink: smb-admin/disable-enable-branchcache-task.html 
sidebar: sidebar 
keywords: disable, branchcache, storage, virtual, machine, svm, changing, change, operating, mode, disable, operate, per-share, automatic, disable or enable branchcache 
summary: 'Você pode desativar o BranchCache na máquina virtual de armazenamento (SVM) alterando o modo operacional BranchCache para desativado. Você pode ativar o BranchCache a qualquer momento alterando o modo operacional para oferecer serviços BranchCache por compartilhamento ou automaticamente para todos os compartilhamentos.' 
---
= Desative ou ative o BranchCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode desativar o BranchCache na máquina virtual de armazenamento (SVM) alterando o modo operacional BranchCache para `disabled`. Você pode ativar o BranchCache a qualquer momento alterando o modo operacional para oferecer serviços BranchCache por compartilhamento ou automaticamente para todos os compartilhamentos.

.Passos
. Execute o comando apropriado:
+
|===
| Se você quiser... | Em seguida, digite o seguinte... 


 a| 
Desativar BranchCache
 a| 
`vserver cifs branchcache modify -vserver vserver_name -operating-mode disable`



 a| 
Ativar BranchCache por partilha
 a| 
`vserver cifs branchcache modify -vserver vserver_name -operating-mode per-share`



 a| 
Ative o BranchCache para todos os compartilhamentos
 a| 
`vserver cifs branchcache modify -vserver vserver_name -operating-mode all-shares`

|===
. Verifique se o modo de operação BranchCache está configurado com a configuração desejada: `vserver cifs branchcache show -vserver vserver_name`


.Exemplo
O exemplo a seguir desativa o BranchCache no SVM VS1:

[listing]
----
cluster1::> vserver cifs branchcache modify -vserver vs1 -operating-mode disable

cluster1::> vserver cifs branchcache show -vserver vs1

                                 Vserver: vs1
          Supported BranchCache Versions: enable_all
                      Path to Hash Store: /hash_data
          Maximum Size of the Hash Store: 20GB
Encryption Key Used to Secure the Hashes: -
        CIFS BranchCache Operating Modes: disable
----