---
permalink: smb-admin/display-restricted-group-gpos-task.html 
sidebar: sidebar 
keywords: display, detail, information, restrict, group, define, group, policy, object, gpo, active, directory, applied, apply, cifs, server, display detailed information about restricted group gpos 
summary: 'Você pode exibir informações detalhadas sobre grupos restritos definidos como objetos de Diretiva de Grupo (GPOs) no ative Directory e aplicados ao servidor CIFS.' 
---
= Exibir informações sobre GPOs de grupo restrito ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode exibir informações detalhadas sobre grupos restritos definidos como objetos de Diretiva de Grupo (GPOs) no ative Directory e aplicados ao servidor CIFS.

.Sobre esta tarefa
Por padrão, as seguintes informações são exibidas:

* Nome da política de grupo
* Versão da política de grupo
* Link
+
Especifica o nível no qual a diretiva de grupo está configurada. Os possíveis valores de saída incluem o seguinte:

+
** `Local` Quando a política de grupo é configurada no ONTAP
** `Site` quando a política de grupo é configurada no nível do site no controlador de domínio
** `Domain` quando a política de grupo é configurada no nível do domínio no controlador de domínio
** `OrganizationalUnit` Quando a política de grupo é configurada no nível de unidade organizacional (ou) no controlador de domínio
** `RSOP` para o conjunto resultante de políticas derivadas de todas as políticas de grupo definidas em vários níveis


* Nome do grupo restrito
* Os usuários e grupos que pertencem e que não pertencem ao grupo restrito
* A lista de grupos aos quais o grupo restrito é adicionado
+
Um grupo pode ser membro de grupos que não sejam os listados aqui.



.Passo
. Exiba informações sobre todos os GPOs de grupo restrito executando uma das seguintes ações:
+
|===
| Se você quiser exibir informações sobre todos os GPOs de grupo restrito... | Digite o comando... 


 a| 
Definido no ative Directory
 a| 
`vserver cifs group-policy restricted-group show-defined -vserver vserver_name`



 a| 
Aplicado a um servidor CIFS
 a| 
`vserver cifs group-policy restricted-group show-applied -vserver vserver_name`

|===


.Exemplo
O exemplo a seguir exibe informações sobre GPOs de grupo restrito definidos no domínio do ative Directory ao qual pertence o SVM habilitado para CIFS chamado VS1:

[listing]
----
cluster1::> vserver cifs group-policy restricted-group show-defined -vserver vs1

Vserver: vs1
-------------

     Group Policy Name: gpo1
               Version: 16
                  Link: OrganizationalUnit
            Group Name: group1
               Members: user1
              MemberOf: EXAMPLE\group9

     Group Policy Name: Resultant Set of Policy
               Version: 0
                  Link: RSOP
            Group Name: group1
               Members: user1
              MemberOf: EXAMPLE\group9
----
O exemplo a seguir exibe informações sobre GPOs de grupos restritos aplicados ao SVM VS1 habilitado para CIFS:

[listing]
----
cluster1::> vserver cifs group-policy restricted-group show-applied -vserver vs1

Vserver: vs1
-------------

     Group Policy Name: gpo1
               Version: 16
                  Link: OrganizationalUnit
            Group Name: group1
               Members: user1
              MemberOf: EXAMPLE\group9

     Group Policy Name: Resultant Set of Policy
               Version: 0
                  Link: RSOP
            Group Name: group1
               Members: user1
              MemberOf: EXAMPLE\group9
----
.Informações relacionadas
xref:display-gpo-config-task.adoc[Exibindo informações sobre as configurações do GPO]
