---
permalink: smb-admin/display-local-groups-task.html 
sidebar: sidebar 
keywords: display, list, local, group, configure, cluster, storage, virtual, machine, svm, information, useful, troubleshoot, issue, data, user-right, privilege, display information about local groups 
summary: 'É possível exibir uma lista de todos os grupos locais configurados no cluster ou em uma máquina virtual de armazenamento (SVM) especificada. Essas informações podem ser úteis ao solucionar problemas de acesso a arquivos para dados contidos no SVM ou problemas de direitos de usuário (privilégios) no SVM.' 
---
= Exibir informações sobre grupos locais no ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível exibir uma lista de todos os grupos locais configurados no cluster ou em uma máquina virtual de armazenamento (SVM) especificada. Essas informações podem ser úteis ao solucionar problemas de acesso a arquivos para dados contidos no SVM ou problemas de direitos de usuário (privilégios) no SVM.

.Passo
. Execute uma das seguintes ações:
+
|===
| Se você quiser informações sobre... | Digite o comando... 


 a| 
Todos os grupos locais no cluster
 a| 
`vserver cifs users-and-groups local-group show`



 a| 
Todos os grupos locais no SVM
 a| 
`vserver cifs users-and-groups local-group show -vserver _vserver_name_`

|===
+
Há outros parâmetros opcionais que você pode escolher quando você executar este comando. Saiba mais sobre `vserver cifs` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs["Referência do comando ONTAP"^]na .



.Exemplo
O exemplo a seguir exibe informações sobre todos os grupos locais no SVM VS1:

[listing]
----
cluster1::> vserver cifs users-and-groups local-group show -vserver vs1
Vserver  Group Name                  Description
-------- --------------------------- ----------------------------
vs1      BUILTIN\Administrators      Built-in Administrators group
vs1      BUILTIN\Backup Operators    Backup Operators group
vs1      BUILTIN\Power Users         Restricted administrative privileges
vs1      BUILTIN\Users               All users
vs1      CIFS_SERVER\engineering
vs1      CIFS_SERVER\sales
----