---
permalink: smb-admin/display-branchcache-config-task.html 
sidebar: sidebar 
keywords: display, information, branchcache, configuration, storage, virtual, machine, svm, verify, setting, modify, display information about branchcache configurations 
summary: 'Você pode exibir informações sobre as configurações do BranchCache em máquinas virtuais de armazenamento (SVMs), que podem ser usadas ao verificar uma configuração ou ao determinar as configurações atuais antes de modificar uma configuração.' 
---
= Exibir informações sobre as configurações do BranchCache em compartilhamentos ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode exibir informações sobre as configurações do BranchCache em máquinas virtuais de armazenamento (SVMs), que podem ser usadas ao verificar uma configuração ou ao determinar as configurações atuais antes de modificar uma configuração.

.Passo
. Execute uma das seguintes ações:
+
|===
| Se você quiser exibir... | Digite este comando... 


 a| 
Informações resumidas sobre as configurações do BranchCache em todos os SVMs
 a| 
`vserver cifs branchcache show`



 a| 
Informações detalhadas sobre a configuração em uma SVM específica
 a| 
`vserver cifs branchcache show -vserver _vserver_name_`

|===


.Exemplo
O exemplo a seguir exibe informações sobre a configuração BranchCache no SVM VS1:

[listing]
----
cluster1::> vserver cifs branchcache show -vserver vs1

                                   Vserver: vs1
            Supported BranchCache Versions: enable_all
                        Path to Hash Store: /hash_data
            Maximum Size of the Hash Store: 20GB
  Encryption Key Used to Secure the Hashes: -
          CIFS BranchCache Operating Modes: per_share
----