---
permalink: smb-admin/display-central-access-policy-rules-task.html 
sidebar: sidebar 
keywords: display, detail, information, central, access, policy, rule, policies, define, active, directory, group, object, display information about central access policy rules 
summary: 'Você pode exibir informações detalhadas sobre regras de política de acesso central associadas a políticas de acesso centrais definidas no ative Directory. Você também pode exibir informações sobre regras de políticas de acesso centrais aplicadas ao servidor CIFS por meio de GPOs de diretiva de acesso central (objetos de diretiva de grupo).' 
---
= Exibir informações sobre as regras da política de acesso central do ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode exibir informações detalhadas sobre regras de política de acesso central associadas a políticas de acesso centrais definidas no ative Directory. Você também pode exibir informações sobre regras de políticas de acesso centrais aplicadas ao servidor CIFS por meio de GPOs de diretiva de acesso central (objetos de diretiva de grupo).

.Sobre esta tarefa
Você pode exibir informações detalhadas sobre regras de política de acesso central definidas e aplicadas. Por padrão, as seguintes informações são exibidas:

* Nome do SVM
* Nome da regra de acesso central
* Descrição
* Tempo de criação
* Tempo de modificação
* Permissões atuais
* Permissões propostas
* Direcionar recursos


|===
| Se você quiser exibir informações sobre todas as regras de política de acesso central associadas às políticas de acesso central... | Digite o comando... 


 a| 
Definido no ative Directory
 a| 
`vserver cifs group-policy central-access-rule show-defined -vserver vserver_name`



 a| 
Aplicado a um servidor CIFS
 a| 
`vserver cifs group-policy central-access-rule show-applied -vserver vserver_name`

|===
.Exemplo
O exemplo a seguir exibe informações de todas as regras de política de acesso central associadas às políticas de acesso central definidas no ative Directory:

[listing]
----
cluster1::> vserver cifs group-policy central-access-rule show-defined

Vserver    Name
---------- --------------------
vs1        r1
           Description: rule #1
         Creation Time: Tue Oct 22 09:33:48 2013
     Modification Time: Tue Oct 22 09:33:48 2013
   Current Permissions: O:SYG:SYD:AR(A;;FA;;;WD)
  Proposed Permissions: O:SYG:SYD:(A;;FA;;;OW)(A;;FA;;;BA)(A;;FA;;;SY)

vs1        r2
           Description: rule #2
         Creation Time: Tue Oct 22 10:27:57 2013
     Modification Time: Tue Oct 22 10:27:57 2013
   Current Permissions: O:SYG:SYD:AR(A;;FA;;;WD)
  Proposed Permissions: O:SYG:SYD:(A;;FA;;;OW)(A;;FA;;;BA)(A;;FA;;;SY)
----
O exemplo a seguir exibe informações de todas as regras de política de acesso central associadas às políticas de acesso central aplicadas a máquinas virtuais de armazenamento (SVMs) no cluster:

[listing]
----
cluster1::> vserver cifs group-policy central-access-rule show-applied

Vserver    Name
---------- --------------------
vs1        r1
           Description: rule #1
         Creation Time: Tue Oct 22 09:33:48 2013
     Modification Time: Tue Oct 22 09:33:48 2013
   Current Permissions: O:SYG:SYD:AR(A;;FA;;;WD)
  Proposed Permissions: O:SYG:SYD:(A;;FA;;;OW)(A;;FA;;;BA)(A;;FA;;;SY)

vs1        r2
           Description: rule #2
         Creation Time: Tue Oct 22 10:27:57 2013
     Modification Time: Tue Oct 22 10:27:57 2013
   Current Permissions: O:SYG:SYD:AR(A;;FA;;;WD)
  Proposed Permissions: O:SYG:SYD:(A;;FA;;;OW)(A;;FA;;;BA)(A;;FA;;;SY)
----
.Informações relacionadas
* xref:secure-file-access-dynamic-access-control-concept.adoc[Saiba mais sobre segurança de acesso a arquivos para servidores]
* xref:display-gpo-config-task.adoc[Apresentar informações sobre as configurações do GPO]
* xref:display-central-access-policies-task.adoc[Exibir informações sobre políticas de acesso centrais]

