---
permalink: smb-admin/display-preferred-trusted-domain-list-task.html 
sidebar: sidebar 
keywords: display, information, trust, domain, perfer, list, order, multidomain, name, map, search, enable, configure, alternative, display information about the preferred trusted domain list 
summary: Você pode exibir informações sobre quais domínios confiáveis estão na lista de domínios confiáveis preferenciais e a ordem em que eles são pesquisados se as pesquisas de mapeamento de nomes de vários domínios estiverem ativadas. Você pode configurar uma lista de domínio confiável preferida como alternativa ao uso da lista de domínio confiável descoberta automaticamente. 
---
= Exibir informações sobre a lista de domínios confiáveis preferencial
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode exibir informações sobre quais domínios confiáveis estão na lista de domínios confiáveis preferenciais e a ordem em que eles são pesquisados se as pesquisas de mapeamento de nomes de vários domínios estiverem ativadas. Você pode configurar uma lista de domínio confiável preferida como alternativa ao uso da lista de domínio confiável descoberta automaticamente.

.Passos
. Execute uma das seguintes ações:
+
|===
| Se você quiser exibir informações sobre o seguinte... | Use o comando... 


 a| 
Todos os domínios confiáveis preferenciais no cluster agrupados por máquina virtual de armazenamento (SVM)
 a| 
`vserver cifs domain name-mapping-search show`



 a| 
Todos os domínios confiáveis preferenciais para um SVM especificado
 a| 
`vserver cifs domain name-mapping-search show -vserver _vserver_name_`

|===
+
O comando a seguir exibe informações sobre todos os domínios confiáveis preferenciais no cluster:

+
[listing]
----
cluster1::> vserver cifs domain name-mapping-search show
Vserver         Trusted Domains
--------------  ----------------------------------
vs1             CIFS1.EXAMPLE.COM
----


.Informações relacionadas
xref:add-remove-replace-trusted-domains-preferred-lists-task.adoc[Adicionar, remover ou substituir domínios confiáveis em listas de domínios confiáveis preferenciais]
