---
permalink: smb-admin/display-privilege-overrides-task.html 
sidebar: sidebar 
keywords: display, information, custom, privilege, assign, domain, local, user, account, group, desire, right, applied, apply, display information about privilege overrides 
summary: Você pode exibir informações sobre Privileges personalizados atribuídos a grupos ou contas de usuário locais ou de domínio. Essas informações ajudam a determinar se os direitos de usuário desejados são aplicados. 
---
= Exibir informações sobre substituições de privilégios no ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode exibir informações sobre Privileges personalizados atribuídos a grupos ou contas de usuário locais ou de domínio. Essas informações ajudam a determinar se os direitos de usuário desejados são aplicados.

.Passo
. Execute uma das seguintes ações:
+
|===
| Se você quiser exibir informações sobre... | Digite este comando... 


 a| 
Privileges personalizado para todos os usuários e grupos de domínio e locais na máquina virtual de storage (SVM)
 a| 
`vserver cifs users-and-groups privilege show -vserver _vserver_name_`



 a| 
Privileges personalizado para um domínio específico ou usuário local e grupo no SVM
 a| 
`vserver cifs users-and-groups privilege show -vserver _vserver_name_ -user-or-group-name _name_`

|===
+
Há outros parâmetros opcionais que você pode escolher quando você executar este comando. Saiba mais sobre `vserver cifs users-and-groups privilege show` o link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-users-and-groups-privilege-show.html["Referência do comando ONTAP"^]na .



.Exemplo
O comando a seguir exibe todos os Privileges explicitamente associados a usuários e grupos locais ou de domínio para o SVM VS1:

[listing]
----
cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver    User or Group Name     Privileges
--------- ---------------------   ---------------
vs1       BUILTIN\Administrators  SeTakeOwnershipPrivilege
                                  SeRestorePrivilege
vs1       CIFS_SERVER\sue         SeTcbPrivilege
                                  SeTakeOwnershipPrivilege
----