---
permalink: smb-admin/display-list-netbios-aliases-task.html 
sidebar: sidebar 
keywords: display, list, netbios, alias, useful, determine, name, smb, client, connection, cifs, server, display the list of netbios aliases on cifs servers 
summary: Você pode exibir a lista de aliases NetBIOS. Isso pode ser útil quando você deseja determinar a lista de nomes sobre os quais clientes SMB podem fazer conexões com o servidor CIFS. 
---
= Exiba a lista de aliases NetBIOS para servidores SMB do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode exibir a lista de aliases NetBIOS. Isso pode ser útil quando você deseja determinar a lista de nomes sobre os quais clientes SMB podem fazer conexões com o servidor CIFS.

.Passo
. Execute uma das seguintes ações:
+
|===
| Se você quiser exibir informações sobre... | Digite... 


 a| 
Os aliases NetBIOS de um servidor CIFS
 a| 
`vserver cifs show -display-netbios-aliases`



 a| 
A lista de aliases NetBIOS como parte das informações detalhadas do servidor CIFS
 a| 
`vserver cifs show -instance`

|===
+
O exemplo a seguir exibe informações sobre os aliases NetBIOS de um servidor CIFS:

+
`vserver cifs show -display-netbios-aliases`

+
[listing]
----
Vserver: vs1

         Server Name: CIFS_SERVER
         NetBIOS Aliases: ALIAS_1, ALIAS_2, ALIAS_3
----
+
O exemplo a seguir exibe a lista de aliases NetBIOS como parte das informações detalhadas do servidor CIFS:

+
`vserver cifs show -instance`

+
[listing]
----

                                          Vserver: vs1
                         CIFS Server NetBIOS Name: CIFS_SERVER
                    NetBIOS Domain/Workgroup Name: EXAMPLE
                      Fully Qualified Domain Name: EXAMPLE.COM
Default Site Used by LIFs Without Site Membership:
                             Authentication Style: domain
                CIFS Server Administrative Status: up
                          CIFS Server Description:
                          List of NetBIOS Aliases: ALIAS_1, ALIAS_2, ALIAS_3
----
+
Saiba mais sobre `vserver cifs show` o link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-show.html["Referência do comando ONTAP"^]na .



.Informações relacionadas
* xref:add-list-netbios-aliases-server-task.adoc[Adicionar listas de alias NetBIOS aos servidores]
* xref:commands-manage-servers-reference.adoc[Comandos para gerenciamento de servidores]

