---
permalink: smb-admin/display-local-users-task.html 
sidebar: sidebar 
keywords: display, list, local, user, summary, form, determine, account, setting, configure, specific, user, detail, troubleshoot, authentication, file, access, issue, display information about local users 
summary: Você pode exibir uma lista de todos os usuários locais em um formulário de resumo. Se você quiser determinar quais configurações de conta estão configuradas para um usuário específico, você pode exibir informações detalhadas de conta para esse usuário, bem como as informações de conta para vários usuários. Essas informações podem ajudá-lo a determinar se você precisa modificar as configurações de um usuário e também solucionar problemas de autenticação ou acesso a arquivos. 
---
= Exibir informações sobre usuários locais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode exibir uma lista de todos os usuários locais em um formulário de resumo. Se você quiser determinar quais configurações de conta estão configuradas para um usuário específico, você pode exibir informações detalhadas de conta para esse usuário, bem como as informações de conta para vários usuários. Essas informações podem ajudá-lo a determinar se você precisa modificar as configurações de um usuário e também solucionar problemas de autenticação ou acesso a arquivos.

.Sobre esta tarefa
As informações sobre a palavra-passe de um utilizador nunca são apresentadas.

.Passo
. Execute uma das seguintes ações:
+
|===
| Se você quiser... | Digite o comando... 


 a| 
Exibir informações sobre todos os usuários na máquina virtual de storage (SVM)
 a| 
`vserver cifs users-and-groups local-user show -vserver _vserver_name_`



 a| 
Exibir informações detalhadas da conta para um usuário
 a| 
`vserver cifs users-and-groups local-user show -instance -vserver _vserver_name_ -user-name _user_name_`

|===
+
Há outros parâmetros opcionais que você pode escolher quando você executa o comando. Consulte a página de manual para obter mais informações.



.Exemplo
O exemplo a seguir exibe informações sobre todos os usuários locais no SVM VS1:

[listing]
----
cluster1::> vserver cifs users-and-groups local-user show -vserver vs1
Vserver  User Name                   Full Name     Description
-------- --------------------------- ------------- -------------
vs1      CIFS_SERVER\Administrator   James Smith   Built-in administrator account
vs1      CIFS_SERVER\sue             Sue   Jones
----