---
permalink: smb-admin/display-group-memberships-local-users-task.html 
sidebar: sidebar 
keywords: display, information, local, group, user, belong, folder, determine, access, file, useful, troubleshoot, display information about group memberships for local users 
summary: Você pode exibir informações sobre os grupos locais aos quais um usuário local pertence. Você pode usar essas informações para determinar qual acesso o usuário deve ter aos arquivos e pastas. Essas informações podem ser úteis para determinar quais direitos de acesso o usuário deve ter a arquivos e pastas ou ao solucionar problemas de acesso ao arquivo. 
---
= Exibir informações sobre associações de grupos para usuários locais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode exibir informações sobre os grupos locais aos quais um usuário local pertence. Você pode usar essas informações para determinar qual acesso o usuário deve ter aos arquivos e pastas. Essas informações podem ser úteis para determinar quais direitos de acesso o usuário deve ter a arquivos e pastas ou ao solucionar problemas de acesso ao arquivo.

.Sobre esta tarefa
Você pode personalizar o comando para exibir apenas as informações que deseja ver.

.Passo
. Execute uma das seguintes ações:
+
|===
| Se você quiser... | Digite o comando... 


 a| 
Exibir informações de associação de usuário local para um usuário local especificado
 a| 
`vserver cifs users-and-groups local-user show-membership -user-name _user_name_`



 a| 
Exibir informações de associação de usuários locais para o grupo local do qual esse usuário local é membro
 a| 
`vserver cifs users-and-groups local-user show-membership -membership _group_name_`



 a| 
Exibir informações de associação de usuários para usuários locais associados a uma máquina virtual de armazenamento (SVM) especificada
 a| 
`vserver cifs users-and-groups local-user show-membership -vserver _vserver_name_`



 a| 
Exibir informações detalhadas de todos os usuários locais em um SVM especificado
 a| 
`vserver cifs users-and-groups local-user show-membership -instance ‑vserver _vserver_name_`

|===


.Exemplo
O exemplo a seguir exibe as informações de associação para todos os usuários locais no SVM VS1; o usuário "CIFS_SERVER" é membro do grupo "BUILTIN" Administradores, e "'CIFS_Server'" é membro do grupo "'CIFS_Server' G1":

[listing]
----
cluster1::> vserver cifs users-and-groups local-user show-membership -vserver vs1
Vserver    User Name                    Membership
---------- ---------------------------- ------------------------
vs1        CIFS_SERVER\Administrator    BUILTIN\Administrators
           CIFS_SERVER\sue              CIFS_SERVER\g1
----