---
permalink: smb-admin/effective-slag-matrix-reference.html 
sidebar: sidebar 
keywords: configure, slag, volume, qtree, matrix, define, configuration, applicable, scenario, list, table, effective slag matrix 
summary: Você pode configurar O SLAG em um volume ou uma qtree ou ambos. A matriz DE ESCÓRIA define em que volume ou qtree é a configuração DE ESCÓRIA aplicável em vários cenários listados na tabela. 
---
= Matriz DE ESCÓRIA eficaz
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar O SLAG em um volume ou uma qtree ou ambos. A matriz DE ESCÓRIA define em que volume ou qtree é a configuração DE ESCÓRIA aplicável em vários cenários listados na tabela.

|===
|  | ESCÓRIA de volume num AFS | ESCÓRIA de volume em uma cópia Snapshot | ESCÓRIA de Qtree em um AFS | ESCÓRIA de Qtree em uma cópia Snapshot 


 a| 
Acesso de volume num sistema de ficheiros de acesso (AFS)
 a| 
SIM
 a| 
NÃO
 a| 
N/A.
 a| 
N/A.



 a| 
Acesso de volume em uma cópia Snapshot
 a| 
SIM
 a| 
NÃO
 a| 
N/A.
 a| 
N/A.



 a| 
Acesso Qtree em um AFS (quando ESCÓRIA está presente na qtree)
 a| 
NÃO
 a| 
NÃO
 a| 
SIM
 a| 
NÃO



 a| 
Acesso Qtree em um AFS (quando ESCÓRIA não está presente em qtree)
 a| 
SIM
 a| 
NÃO
 a| 
NÃO
 a| 
NÃO



 a| 
Acesso Qtree na cópia Snapshot (quando A ESCÓRIA está presente no qtree AFS)
 a| 
NÃO
 a| 
NÃO
 a| 
SIM
 a| 
NÃO



 a| 
Acesso Qtree na cópia Snapshot (quando A ESCÓRIA não está presente na qtree AFS)
 a| 
SIM
 a| 
NÃO
 a| 
NÃO
 a| 
NÃO

|===