---
permalink: smb-admin/enable-metadata-cache-task.html 
sidebar: sidebar 
keywords: smb, performance, client, enabling, enable, metadata, cache, disable, enable the smb metadata cache 
summary: Você pode melhorar o desempenho do SMB para clientes SMB 1,0 ativando o cache de metadados SMB. Por padrão, o armazenamento em cache de metadados SMB está desativado. 
---
= Habilitar o cache de metadados ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode melhorar o desempenho do SMB para clientes SMB 1,0 ativando o cache de metadados SMB. Por padrão, o armazenamento em cache de metadados SMB está desativado.

.Passo
. Execute a ação desejada:
+
|===
| Se você quiser... | Digite o comando... 


 a| 
Ative o armazenamento em cache de metadados SMB ao criar um compartilhamento
 a| 
`vserver cifs share create -vserver _vserver_name_ -share-name _share_name_ -path _path_ -share-properties attributecache`



 a| 
Habilite o armazenamento em cache de metadados SMB em um compartilhamento existente
 a| 
`vserver cifs share properties add -vserver _vserver_name_ -share-name _share_name_ -share-properties attributecache`

|===


.Informações relacionadas
* xref:configure-lifetime-metadata-cache-entries-task.adoc[Configurar o tempo de vida das entradas do cache de metadados]
* xref:add-remove-share-properties-existing-share-task.adoc[Adicionar ou remover propriedades de compartilhamento em compartilhamentos existentes]

