---
permalink: smb-admin/enable-disable-automatic-node-referrals-task.html 
sidebar: sidebar 
keywords: enable, smb, automatic, node, referral, client, access, performance, disable, ontap, enable or disable smb automatic node referrals 
summary: Você pode habilitar referências de nó automáticas SMB para aumentar o desempenho de acesso de cliente SMB. Você pode desativar referências automáticas de nós se não quiser que o ONTAP faça referências a clientes SMB. 
---
= Ative ou desative referências de nó automáticas SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode habilitar referências de nó automáticas SMB para aumentar o desempenho de acesso de cliente SMB. Você pode desativar referências automáticas de nós se não quiser que o ONTAP faça referências a clientes SMB.

.Antes de começar
Um servidor CIFS deve ser configurado e executado na máquina virtual de storage (SVM).

.Sobre esta tarefa
A funcionalidade de referências de nó automático SMB está desativada por predefinição. Você pode ativar ou desativar essa funcionalidade em cada SVM conforme necessário.

Esta opção está disponível no nível de privilégio avançado.

.Passos
. Defina o nível de privilégio como avançado: `set -privilege advanced`
. Ative ou desative referências de nó automáticas SMB conforme necessário:
+
|===
| Se você quiser que as referências de nó automático SMB sejam... | Digite o seguinte comando... 


 a| 
Ativado
 a| 
`vserver cifs options modify -vserver vserver_name -is-referral-enabled true`



 a| 
Desativado
 a| 
`vserver cifs options modify -vserver vserver_name -is-referral-enabled false`

|===
+
A configuração de opção entra em vigor para novas sessões SMB. Os clientes com conexão existente podem utilizar referência de nó somente quando o tempo limite de cache existente expirar.

. Mudar para o nível de privilégio de administrador: `set -privilege admin`


.Informações relacionadas
xref:server-options-reference.adoc[Opções de servidor SMB disponíveis]
