---
permalink: smb-admin/enable-disable-dynamic-access-control-task.html 
sidebar: sidebar 
keywords: option, enable, dynamic, access, control, dac, secure, object, cifs, server, disable, default, enable or disable dynamic access control 
summary: 'A opção que permite utilizar o controlo de Acesso Dinâmico (DAC) para proteger objetos no servidor CIFS está desativada por predefinição. Você deve ativar a opção se quiser usar o Controle de Acesso Dinâmico no servidor CIFS. Se decidir mais tarde que não pretende utilizar o controlo de Acesso Dinâmico para proteger objetos armazenados no servidor CIFS, pode desativar a opção.' 
---
= Habilitar ou desabilitar DAC para servidores ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A opção que permite utilizar o controlo de Acesso Dinâmico (DAC) para proteger objetos no servidor CIFS está desativada por predefinição. Você deve ativar a opção se quiser usar o Controle de Acesso Dinâmico no servidor CIFS. Se decidir mais tarde que não pretende utilizar o controlo de Acesso Dinâmico para proteger objetos armazenados no servidor CIFS, pode desativar a opção.

Você pode encontrar informações sobre como configurar o Controle de Acesso Dinâmico no ative Directory na Biblioteca Microsoft TechNet.

http://technet.microsoft.com/library/hh831717.aspx["Microsoft TechNet: Visão geral do cenário Dynamic Access Control"^]

.Sobre esta tarefa
Uma vez que o Controle de Acesso Dinâmico esteja ativado, o sistema de arquivos pode conter ACLs com entradas relacionadas ao Controle de Acesso Dinâmico. Se o controlo de Acesso Dinâmico estiver desativado, as entradas atuais do controlo de Acesso Dinâmico serão ignoradas e as novas não serão permitidas.

Esta opção está disponível apenas no nível de privilégio avançado.

.Passo
. Defina o nível de privilégio como avançado: `set -privilege advanced`
. Execute uma das seguintes ações:
+
|===


| Se você quiser que o Controle de Acesso Dinâmico seja... | Digite o comando... 


 a| 
Ativado
 a| 
`vserver cifs options modify -vserver _vserver_name_ -is-dac-enabled true`



 a| 
Desativado
 a| 
`vserver cifs options modify -vserver _vserver_name_ -is-dac-enabled false`

|===
. Voltar ao nível de privilégio de administrador: `set -privilege admin`


.Informações relacionadas
xref:configure-central-access-policies-secure-data-task.adoc[Configurar políticas de acesso central para proteger dados em servidores]
