---
permalink: smb-admin/enable-ipv6-task.html 
sidebar: sidebar 
keywords: ipv6, network, enable, cluster, setup, administrator, smb, enable ipv6 for smb, cluster administrator only 
summary: As redes IPv6 não estão ativadas durante a configuração do cluster. Um administrador de cluster deve habilitar o IPv6 após a conclusão da configuração do cluster para usar o IPv6 para SMB. Quando o administrador do cluster ativa o IPv6, ele é ativado para todo o cluster. 
---
= Ative o IPv6 para servidores SMB do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As redes IPv6 não estão ativadas durante a configuração do cluster. Um administrador de cluster deve habilitar o IPv6 após a conclusão da configuração do cluster para usar o IPv6 para SMB. Quando o administrador do cluster ativa o IPv6, ele é ativado para todo o cluster.

.Passo
. Ativar IPv6: `network options ipv6 modify -enabled true`
+
Para obter mais informações sobre como ativar o IPv6 no cluster e configurar LIFs IPv6, consulte o _Network Management Guide_.

+
IPv6 está ativado. LIFs de dados IPv6 para acesso SMB podem ser configurados.



.Informações relacionadas
* xref:monitor-display-ipv6-sessions-task.adoc[Monitoramento e exibição de informações sobre IPv6 sessões SMB]
* link:../networking/networking_reference.html["Visualize a rede usando o System Manager"]
* link:https://docs.netapp.com/us-en/ontap-cli/network-options-ipv6-modify.html["opções de rede ipv6 modificar"^]

