---
permalink: smb-admin/enable-netbios-name-service-task.html 
sidebar: sidebar 
keywords: ontap, netbios, name, service, nbns, windows, internet, name, service, wins, disable, default, cifs-enable, storage, virtual, machine, svm, registration, broadcast, network, server, wnable the netbios name service 
summary: 'Começando com ONTAP 9, o serviço de nomes NetBIOS (NBNS, às vezes chamado de Serviço de nomes de Internet do Windows ou WINS) é desativado por padrão. Anteriormente, as máquinas virtuais de armazenamento (SVMs) habilitadas por CIFS enviavam transmissões de Registro de nomes, independentemente de o WINS estar habilitado em uma rede. Para limitar tais transmissões a configurações em que o NBNS é necessário, você deve habilitar o NBNS explicitamente para novos servidores CIFS.' 
---
= Ative o serviço de nomes NetBIOS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Começando com ONTAP 9, o serviço de nomes NetBIOS (NBNS, às vezes chamado de Serviço de nomes de Internet do Windows ou WINS) é desativado por padrão. Anteriormente, as máquinas virtuais de armazenamento (SVMs) habilitadas por CIFS enviavam transmissões de Registro de nomes, independentemente de o WINS estar habilitado em uma rede. Para limitar tais transmissões a configurações em que o NBNS é necessário, você deve habilitar o NBNS explicitamente para novos servidores CIFS.

.Antes de começar
* Se você já estiver usando NBNS e atualizar para o ONTAP 9, não é necessário concluir esta tarefa. NBNS continuará a funcionar como antes.
* O NBNS é ativado por UDP (porta 137).
* NBNS sobre IPv6 não é suportado.


.Passos
. Defina o nível de privilégio como avançado.
+
[listing]
----
set -privilege advanced
----
. Ative NBNS em um servidor CIFS.
+
[listing]
----
vserver cifs options  modify -vserver <vserver name> -is-nbns-enabled true
----
. Retorne ao nível de privilégio de administrador.
+
[listing]
----
set -privilege admin
----

