---
permalink: smb-admin/enable-encrypted-connections-domain-controllers-task.html 
sidebar: sidebar 
keywords: ontap, connection, domain, controller, encrypt, enable, enable encrypted connections to domain controllers 
summary: A partir do ONTAP 9.8, você pode especificar que as conexões aos controladores de domínio sejam criptografadas. 
---
= Ative conexões criptografadas com controladores de domínio SMB do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.8, você pode especificar que as conexões aos controladores de domínio sejam criptografadas.

.Sobre esta tarefa
O ONTAP requer criptografia para comunicações de controlador de domínio (DC) quando a `-encryption-required-for-dc-connection` opção está definida como `true`; o padrão é `false`. Quando a opção está definida, apenas o protocolo SMB3 será utilizado para ligações ONTAP-DC, uma vez que a encriptação é suportada apenas pelo SMB3.

Quando as comunicações CC criptografadas são necessárias, a `-smb2-enabled-for-dc-connections` opção é ignorada, porque o ONTAP negocia somente conexões SMB3. Se um DC não suportar SMB3 e criptografia, o ONTAP não se conetará a ele.

.Passo
. Ative a comunicação encriptada com o DC: `vserver cifs security modify -vserver _svm_name_ -encryption-required-for-dc-connection true`

