---
permalink: smb-admin/enable-smb2-connections-domain-controllers-task.html 
sidebar: sidebar 
keywords: ontap, enable, smb, version, connect, domain, controller, default, smb2, enable smb2 connections to domain controllers 
summary: A partir do ONTAP 9.1, você pode habilitar o SMB versão 2,0 para se conetar a um controlador de domínio. Isso é necessário se você desativou o SMB 1,0 em controladores de domínio. A partir do ONTAP 9.2, o SMB2 é ativado por predefinição. 
---
= Ative as conexões SMB2 aos controladores de domínio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.1, você pode habilitar o SMB versão 2,0 para se conetar a um controlador de domínio. Isso é necessário se você desativou o SMB 1,0 em controladores de domínio. A partir do ONTAP 9.2, o SMB2 é ativado por predefinição.

.Sobre esta tarefa
A `smb2-enabled-for-dc-connections` opção de comando ativa o padrão do sistema para o lançamento do ONTAP que você está usando. O padrão do sistema para o ONTAP 9.1 está ativado para o SMB 1,0 e desativado para o SMB 2,0. O padrão do sistema para o ONTAP 9.2 está habilitado para o SMB 1,0 e habilitado para o SMB 2,0. Se o controlador de domínio não puder negociar o SMB 2,0 inicialmente, ele usará o SMB 1,0.

O SMB 1,0 pode ser desativado do ONTAP para um controlador de domínio. No ONTAP 9.1, se o SMB 1,0 tiver sido desativado, o SMB 2,0 deve ser ativado para se comunicar com um controlador de domínio.

Saiba mais sobre:

* link:../smb-config/verify-enabled-versions-task.html["Verificando versões SMB ativadas"].
* link:supported-versions-functionality-concept.html["Versões e funcionalidade SMB compatíveis"].


[NOTE]
====
Se `-smb1-enabled-for-dc-connections` estiver definido como `false` enquanto `-smb1-enabled` estiver definido como `true`, o ONTAP nega conexões SMB 1,0 como cliente, mas continua a aceitar conexões SMB 1,0 de entrada como servidor.

====
.Passos
. Antes de alterar as configurações de segurança SMB, verifique quais versões SMB estão ativadas: `vserver cifs security show`
. Role a lista para baixo para ver as versões SMB.
. Execute o comando apropriado, usando a `smb2-enabled-for-dc-connections` opção.
+
|===
| Se você quiser que SMB2 seja... | Digite o comando... 


 a| 
Ativado
 a| 
`vserver cifs security modify -vserver _vserver_name_ -smb2-enabled-for-dc-connections true`



 a| 
Desativado
 a| 
`vserver cifs security modify -vserver _vserver_name_ -smb2-enabled-for-dc-connections false`

|===

