---
permalink: smb-admin/enable-disable-gpo-support-task.html 
sidebar: sidebar 
keywords: enable, disable, group, policy, object, gpo, support, cifs, server, applicable, define, policy, organizational, unit, ou, enable or disable gpo support on a cifs server 
summary: 'Você pode ativar ou desativar o suporte de GPO (Group Policy Object) em um servidor CIFS. Se você habilitar o suporte a GPO em um servidor CIFS, os GPOs aplicáveis definidos na diretiva de grupo, a diretiva aplicada à unidade organizacional (ou) que contém o objeto computador servidor CIFS, serão aplicados ao servidor CIFS.' 
---
= Ative ou desative o suporte GPO em servidores SMB do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode ativar ou desativar o suporte de GPO (Group Policy Object) em um servidor CIFS. Se você habilitar o suporte a GPO em um servidor CIFS, os GPOs aplicáveis definidos na diretiva de grupo - a diretiva aplicada à unidade organizacional (ou) que contém o objeto computador servidor CIFS - serão aplicados ao servidor CIFS.

[NOTE]
.Sobre esta tarefa
====
Os GPOs não podem ser ativados em servidores CIFS no modo de grupo de trabalho.

====
.Passos
. Execute uma das seguintes ações:
+
|===
| Se você quiser... | Digite o comando... 


 a| 
Ativar GPOs
 a| 
`vserver cifs group-policy modify -vserver _vserver_name_ -status enabled`



 a| 
Desativar GPOs
 a| 
`vserver cifs group-policy modify -vserver _vserver_name_ -status disabled`

|===
. Verifique se o suporte GPO está no estado desejado: `vserver cifs group-policy show -vserver +vserver_name_`
+
O status da Diretiva de Grupo para servidores CIFS no modo de grupo de trabalho é exibido como "habilitado".



.Exemplo
O exemplo a seguir habilita o suporte a GPO na máquina virtual de storage (SVM) VS1:

[listing]
----
cluster1::> vserver cifs group-policy modify -vserver vs1 -status enabled

cluster1::> vserver cifs group-policy show -vserver vs1

            Vserver: vs1
Group Policy Status: enabled
----
.Informações relacionadas
xref:supported-gpos-concept.adoc[GPOs compatíveis]

xref:requirements-gpos-concept.adoc[Requisitos para usar GPOs com seu servidor CIFS]

xref:gpos-updated-server-concept.adoc[Como os GPOs são atualizados no servidor CIFS]

xref:manual-update-gpo-settings-task.adoc[Atualizar manualmente as definições de GPO no servidor CIFS]

xref:display-gpo-config-task.adoc[Exibindo informações sobre as configurações do GPO]
