---
permalink: smb-admin/enable-disable-oplocks-when-creating-shares-task.html 
sidebar: sidebar 
keywords: oplock, client, lock, file, cache, content, local, performance, operation, storage, virtual, machine, svm, circumstance, disable, share-by-share, basis, enable, disable, enable or disable oplocks when creating smb shares 
summary: 'Oplocks permitem que os clientes bloqueiem arquivos e armazenem conteúdo de cache localmente, o que pode aumentar o desempenho para operações de arquivos. Os Oplocks são ativados em compartilhamentos SMB residentes em máquinas virtuais de armazenamento (SVMs). Em algumas circunstâncias, você pode querer desativar os oplocks. Você pode ativar ou desativar os oplocks em uma base de compartilhamento por compartilhamento.' 
---
= Ative ou desative os oplocks ao criar compartilhamentos SMB do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Oplocks permitem que os clientes bloqueiem arquivos e armazenem conteúdo de cache localmente, o que pode aumentar o desempenho para operações de arquivos. Os Oplocks são ativados em compartilhamentos SMB residentes em máquinas virtuais de armazenamento (SVMs). Em algumas circunstâncias, você pode querer desativar os oplocks. Você pode ativar ou desativar os oplocks em uma base de compartilhamento por compartilhamento.

.Sobre esta tarefa
Se os oplocks estiverem ativados no volume que contém uma partilha, mas a propriedade de partilha de oplock para essa partilha estiver desativada, os oplocks serão desativados para essa partilha. A desativação de oplocks em um compartilhamento tem precedência sobre a configuração de volume de oplock A desativação de oplocks na partilha desativa os oplocks oportunistas e de leasing.

Você pode especificar outras propriedades de compartilhamento além de especificar a propriedade de compartilhamento de oplock usando uma lista delimitada por vírgulas. Você também pode especificar outros parâmetros de compartilhamento.

.Passos
. Execute a ação aplicável:
+
|===
| Se você quiser... | Então... 


 a| 
Ative os oplocks em um compartilhamento durante a criação de compartilhamento
 a| 
Introduza o seguinte comando: `+vserver cifs share create -vserver _vserver_name_ -share-name share_name -path path_to_share -share-properties [oplocks,...]+`

[NOTE]
====
Se desejar que o compartilhamento tenha apenas as propriedades padrão de compartilhamento, que são `oplocks`, `browsable` e `changenotify` ativadas, não será necessário especificar o `-share-properties` parâmetro ao criar um compartilhamento SMB. Se você quiser qualquer combinação de propriedades de compartilhamento diferente do padrão, especifique o `-share-properties` parâmetro com a lista de propriedades de compartilhamento a ser usada para esse compartilhamento.

====


 a| 
Desative os oplocks em um compartilhamento durante a criação de compartilhamento
 a| 
Introduza o seguinte comando: `+vserver cifs share create -vserver _vserver_name_ -share-name _share_name_ -path _path_to_share_ -share-properties [other_share_property,...]+`

[NOTE]
====
Ao desativar os oplocks, você deve especificar uma lista de propriedades de compartilhamento ao criar o compartilhamento, mas não deve especificar a `oplocks` propriedade.

====
|===


.Informações relacionadas
xref:enable-disable-oplocks-existing-shares-task.adoc[Ativar ou desativar os oplocks em compartilhamentos SMB existentes]

xref:monitor-oplock-status-task.adoc[Monitorização do estado de oplock]
