---
permalink: smb-admin/enable-client-access-unix-symbolic-links-concept.html 
sidebar: sidebar 
keywords: smybol, link, file, create, unix, environment, reference, directory, client, access, redirect, target, absolute, widelinks, local, file, system, how ontap enables you to provide smb client access to unix symbolic links 
summary: 'Um link simbólico é um arquivo criado em um ambiente UNIX que contém uma referência a outro arquivo ou diretório. Se um cliente acessar um link simbólico, o cliente será redirecionado para o arquivo de destino ou diretório ao qual o link simbólico se refere. O ONTAP suporta links simbólicos relativos e absolutos, incluindo widelinks (links absolutos com alvos fora do sistema de arquivos local).' 
---
= Saiba mais sobre como fornecer acesso de cliente ONTAP SMB a links simbólicos UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um link simbólico é um arquivo criado em um ambiente UNIX que contém uma referência a outro arquivo ou diretório. Se um cliente acessar um link simbólico, o cliente será redirecionado para o arquivo de destino ou diretório ao qual o link simbólico se refere. O ONTAP suporta links simbólicos relativos e absolutos, incluindo widelinks (links absolutos com alvos fora do sistema de arquivos local).

O ONTAP fornece aos clientes SMB a capacidade de seguir links simbólicos UNIX configurados no SVM. Este recurso é opcional, e você pode configurá-lo por compartilhamento, usando a `-symlink-properties` opção `vserver cifs share create` do comando, com uma das seguintes configurações:

* Habilitado com acesso de leitura/gravação
* Habilitado com acesso somente leitura
* Desabilitado ocultando links simbólicos de clientes SMB
* Desativado sem acesso a links simbólicos de clientes SMB


Se você habilitar links simbólicos em um compartilhamento, links simbólicos relativos funcionam sem configuração adicional.

Se você habilitar links simbólicos em um compartilhamento, links simbólicos absolutos não funcionam imediatamente. Você deve primeiro criar um mapeamento entre o caminho UNIX do link simbólico para o caminho SMB de destino. Ao criar mapeamentos de links simbólicos absolutos, você pode especificar se é um link local ou um _widelink_; widelinks podem ser links para sistemas de arquivos em outros dispositivos de armazenamento ou links para sistemas de arquivos hospedados em SVMs separadas no mesmo sistema ONTAP. Quando você cria um widelink, ele deve incluir as informações para o cliente seguir; ou seja, você cria um ponto de reparação para o cliente descobrir o ponto de junção do diretório. Se você criar um link simbólico absoluto para um arquivo ou diretório fora do compartilhamento local, mas definir a localidade como local, o ONTAP não permite o acesso ao destino.

[NOTE]
====
Se um cliente tentar excluir um link simbólico local (absoluto ou relativo), apenas o link simbólico é excluído, não o arquivo ou diretório de destino. No entanto, se um cliente tentar excluir um widelink, ele pode excluir o arquivo ou diretório de destino real ao qual o widelink se refere. O ONTAP não tem controle sobre isso porque o cliente pode abrir explicitamente o arquivo ou diretório de destino fora do SVM e excluí-lo.

====
* *Reparse Points e serviços de sistema de arquivos ONTAP*
+
Um _ponto de reparação_ é um objeto de sistema de arquivos NTFS que pode ser opcionalmente armazenado em volumes junto com um arquivo. Os pontos Reparse fornecem aos clientes SMB a capacidade de receber serviços de sistema de arquivos aprimorados ou estendidos ao trabalhar com volumes de estilo NTFS. Os pontos Reparse consistem em tags padrão que identificam o tipo de ponto de reparação e o conteúdo do ponto de reparação que pode ser recuperado por clientes SMB para processamento posterior pelo cliente. Dos tipos de objeto disponíveis para a funcionalidade estendida do sistema de arquivos, o ONTAP implementa suporte para links simbólicos NTFS e pontos de junção de diretório usando tags de ponto de reparação. Os clientes SMB que não conseguem entender o conteúdo de um ponto de reparação simplesmente ignoram e não fornecem o serviço de sistema de arquivos estendido que o ponto de reparação pode habilitar.

* * Diretório de pontos de junção e suporte ONTAP para links simbólicos*
+
Os pontos de junção de diretório são locais dentro de uma estrutura de diretórios do sistema de arquivos que podem se referir a locais alternativos onde os arquivos são armazenados, seja em um caminho diferente (links simbólicos) ou em um dispositivo de armazenamento separado (widelinks). Os servidores SMB do ONTAP expõem pontos de junção de diretório para clientes Windows como pontos de reparação, permitindo que clientes capazes obtenham conteúdos de pontos de reparação do ONTAP quando um ponto de junção de diretório é atravessado. Eles podem, assim, navegar e se conetar a diferentes caminhos ou dispositivos de armazenamento como se fossem parte do mesmo sistema de arquivos.

* * Habilitando o suporte de widelink usando opções de ponto de reparação*
+
A `-is-use-junctions-as-reparse-points-enabled` opção está ativada por predefinição no ONTAP 9. Nem todos os clientes SMB suportam widelinks, portanto, a opção de ativar as informações é configurável com base na versão por protocolo, permitindo que os administradores acomodem clientes SMB com suporte e não suporte. No ONTAP 9.2 e versões posteriores, você deve habilitar a opção `-widelink-as-reparse-point-versions` para cada protocolo cliente que acessa o compartilhamento usando widelinks; o padrão é SMB1. Em versões anteriores, apenas os widelinks acessados usando o SMB1 padrão foram relatados e os sistemas que usam SMB2 ou SMB3 não conseguiram acessar os widelinks.



.Informações relacionadas
* link:windows-backup-symlinks.html["Aplicativos de backup do Windows e links simbólicos em estilo Unix"]
* https://docs.microsoft.com/en-us/windows/win32/fileio/reparse-points["Documentação da Microsoft: Pontos de reanálise"^]

