---
permalink: smb-admin/enable-ldap-signing-sealing-task.html 
sidebar: sidebar 
keywords: cifs, server, sign, seal, secure, communication, active, directory, ldap, modify, security, setting, sign, seal, enable, enable ldap signing and sealing on the cifs server 
summary: Antes que o servidor CIFS possa usar assinatura e vedação para comunicação segura com um servidor LDAP do ative Directory, você deve modificar as configurações de segurança do servidor CIFS para habilitar a assinatura e a vedação LDAP. 
---
= Ative a assinatura LDAP e a vedação em servidores SMB do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes que o servidor CIFS possa usar assinatura e vedação para comunicação segura com um servidor LDAP do ative Directory, você deve modificar as configurações de segurança do servidor CIFS para habilitar a assinatura e a vedação LDAP.

.Antes de começar
Você deve consultar o administrador do servidor AD para determinar os valores de configuração de segurança apropriados.

.Passos
. Configure a configuração de segurança do servidor CIFS que permite o tráfego assinado e selado com servidores LDAP do ative Directory: `vserver cifs security modify -vserver _vserver_name_ -session-security-for-ad-ldap {none|sign|seal}`
+
Você pode ativar assinatura (`sign`, integridade de dados), assinatura e vedação (`seal`, integridade e criptografia de dados) ou nenhum  `none`, sem assinatura ou vedação). O valor padrão é `none`.

. Verifique se a configuração de segurança de assinatura e vedação LDAP está definida corretamente: `vserver cifs security show -vserver _vserver_name_`
+
[NOTE]
====
Se o SVM usar o mesmo servidor LDAP para consultar o mapeamento de nomes ou outras informações do UNIX, como usuários, grupos e netgroups, você deverá ativar a configuração correspondente com `-session-security` a opção do `vserver services name-service ldap client modify` comando.

====

