---
permalink: smb-admin/enable-branchcache-existing-share-task.html 
sidebar: sidebar 
keywords: enable, branchcache, exist, smb, share, add, share, property, exist, list, enable branchcache on an existing smb share 
summary: Você pode ativar o BranchCache em um compartilhamento SMB existente adicionando a propriedade de compartilhamento branchcache à lista existente de propriedades de compartilhamento. 
---
= Ative o BranchCache em um compartilhamento SMB existente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode ativar o BranchCache em um compartilhamento SMB existente adicionando a `branchcache` propriedade share à lista existente de propriedades de compartilhamento.

.Sobre esta tarefa
* Se o BranchCache estiver ativado no compartilhamento SMB, o compartilhamento deve ter a configuração de arquivos off-line definida como cache manual.
+
Se a configuração arquivos offline do compartilhamento existente não estiver definida como armazenamento manual em cache, você deverá configurá-lo modificando o compartilhamento.

* Você pode definir a `branchcache` propriedade em um compartilhamento, mesmo que o BranchCache não esteja configurado e habilitado na máquina virtual de storage (SVM).
+
No entanto, se você quiser que o compartilhamento ofereça conteúdo em cache, configure e ative o BranchCache no SVM.

* Quando você adiciona a `branchcache` propriedade de compartilhamento ao compartilhamento, as configurações de compartilhamento existentes e as propriedades de compartilhamento são preservadas.
+
A propriedade de compartilhamento BranchCache é adicionada à lista existente de propriedades de compartilhamento. Para obter mais informações sobre como usar o `vserver cifs share properties add` comando, consulte as páginas de manual.



.Passos
. Se necessário, configure a configuração de compartilhamento de arquivos offline para cache manual:
+
.. Determine qual é a configuração de compartilhamento de arquivos off-line usando o `vserver cifs share show` comando.
.. Se a definição de partilha de ficheiros offline não estiver definida para manual, altere-a para o valor pretendido: `vserver cifs share modify -vserver vserver_name -share-name share_name -offline-files manual`


. Ativar BranchCache em um compartilhamento SMB existente: `vserver cifs share properties add -vserver vserver_name -share-name share_name -share-properties branchcache`
. Verifique se a propriedade BranchCache Share está definida no compartilhamento SMB: `vserver cifs share show -vserver vserver_name -share-name share_name`


.Exemplo
O comando a seguir habilita o BranchCache em um compartilhamento SMB existente chamado "ata2" com um caminho `/data2` de no SVM VS1:

[listing]
----
cluster1::> vserver cifs share show -vserver vs1 -share-name data2

                      Vserver: vs1
                        Share: data2
     CIFS Server NetBIOS Name: VS1
                         Path: /data2
             Share Properties: oplocks
                               browsable
                               changenotify
                               showsnapshot
           Symlink Properties: -
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: 10s
                  Volume Name: -
                Offline Files: manual
Vscan File-Operations Profile: standard

cluster1::> vserver cifs share properties add  -vserver vs1 -share-name data2 -share-properties branchcache

cluster1::> vserver cifs share show -vserver vs1 -share-name data2

                      Vserver: vs1
                        Share: data2
     CIFS Server NetBIOS Name: VS1
                         Path: /data2
             Share Properties: oplocks
                               browsable
                               showsnapshot
                               changenotify
                               branchcache
           Symlink Properties: -
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: 10s
                  Volume Name: -
                Offline Files: manual
Vscan File-Operations Profile: standard
----
.Informações relacionadas
xref:add-remove-share-properties-existing-share-task.adoc[Adicionar ou remover propriedades de compartilhamento em um compartilhamento SMB existente]

xref:disable-branchcache-single-share-task.adoc[Desativar BranchCache em um único compartilhamento SMB]
