---
permalink: smb-admin/enable-disable-local-users-groups-task.html 
sidebar: sidebar 
keywords: smb, access, storage, virtual, machine, svm, functionality, default 
summary: 'Você pode ativar ou desativar usuários locais e grupos para acesso SMB em máquinas virtuais de armazenamento (SVMs). A funcionalidade de utilizadores e grupos locais está ativada por predefinição.' 
---
= Habilitar ou desabilitar usuários e grupos locais em servidores ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode ativar ou desativar usuários locais e grupos para acesso SMB em máquinas virtuais de armazenamento (SVMs). A funcionalidade de utilizadores e grupos locais está ativada por predefinição.

.Sobre esta tarefa
Você pode usar usuários e grupos locais ao configurar permissões de compartilhamento SMB e arquivos NTFS e pode, opcionalmente, usar usuários locais para autenticação ao criar uma conexão SMB. Para utilizar utilizadores locais para autenticação, também tem de ativar a opção de autenticação utilizadores locais e grupos.

.Passos
. Defina o nível de privilégio como avançado: `set -privilege advanced`
. Execute uma das seguintes ações:
+
|===
| Se você quiser que os usuários e grupos locais sejam... | Digite o comando... 


 a| 
Ativado
 a| 
`vserver cifs options modify -vserver _vserver_name_ -is-local-users-and-groups-enabled true`



 a| 
Desativado
 a| 
`vserver cifs options modify -vserver _vserver_name_ -is-local-users-and-groups-enabled false`

|===
. Voltar ao nível de privilégio de administrador: `set -privilege admin`


.Exemplo
O exemplo a seguir habilita a funcionalidade de usuários e grupos locais no SVM VS1:

[listing]
----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options modify -vserver vs1 -is-local-users-and-groups-enabled true

cluster1::*> set -privilege admin
----
.Informações relacionadas
xref:enable-disable-local-user-authentication-task.adoc[Ativar ou desativar a autenticação de utilizador local]

xref:enable-disable-local-user-accounts-task.adoc[Ativar ou desativar contas de utilizador locais]
