---
permalink: smb-admin/flush-hashes-svm-branchcache-task.html 
sidebar: sidebar 
keywords: flush, cache, hash, branchcache, store, storage, virtual, machine, svm, caching, mode, distribute, host, flush hashes from the svm branchcache hash store 
summary: 'Você pode lavar todos os hashes armazenados em cache do armazenamento de hash BranchCache na máquina virtual de armazenamento (SVM). Isso pode ser útil se você tiver alterado a configuração BranchCache da filial. Por exemplo, se você reconfigurou recentemente o modo de armazenamento em cache de armazenamento distribuído para o modo de armazenamento em cache hospedado, você deseja limpar o armazenamento de hash.' 
---
= Liberar hashes do repositório de hashes ONTAP SMB SVM BranchCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode lavar todos os hashes armazenados em cache do armazenamento de hash BranchCache na máquina virtual de armazenamento (SVM). Isso pode ser útil se você tiver alterado a configuração BranchCache da filial. Por exemplo, se você reconfigurou recentemente o modo de armazenamento em cache de armazenamento distribuído para o modo de armazenamento em cache hospedado, você deseja limpar o armazenamento de hash.

.Sobre esta tarefa
Depois de limpar os hashes, o ONTAP cria novos hashes à medida que novas solicitações são feitas por clientes habilitados para BranchCache.

.Passo
. Lave os hashes do armazenamento de hash BranchCache: `vserver cifs branchcache hash-flush -vserver _vserver_name_`
+
`vserver cifs branchcache hash-flush -vserver vs1`


