---
permalink: smb-admin/gpos-updated-server-concept.html 
sidebar: sidebar 
keywords: default, ontap, retrieve, applies, apply, group, policy, object, gpo, minute, security, refresh, update, automatic, manual, cifs, server, command, how gpos are updated on the cifs server 
summary: 'Por padrão, o ONTAP recupera e aplica alterações de Objeto de Diretiva de Grupo (GPO) a cada 90 minutos. As configurações de segurança são atualizadas a cada 16 horas. Se você quiser atualizar os GPOs para aplicar novas configurações de política de GPO antes que o ONTAP as atualize automaticamente, você pode acionar uma atualização manual em um servidor CIFS com um comando ONTAP.' 
---
= Saiba mais sobre como atualizar GPOs em servidores SMB do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Por padrão, o ONTAP recupera e aplica alterações de Objeto de Diretiva de Grupo (GPO) a cada 90 minutos. As configurações de segurança são atualizadas a cada 16 horas. Se você quiser atualizar os GPOs para aplicar novas configurações de política de GPO antes que o ONTAP as atualize automaticamente, você pode acionar uma atualização manual em um servidor CIFS com um comando ONTAP.

* Por padrão, todos os GPOs são verificados e atualizados conforme necessário a cada 90 minutos.
+
Este intervalo é configurável e pode ser definido utilizando as `Refresh interval` definições e `Random offset` GPO.

+
O ONTAP consulta o ative Directory quanto a alterações nos GPOs. Se os números de versão do GPO registrados no ative Directory forem maiores do que os do servidor CIFS, o ONTAP recuperará e aplicará os novos GPOs. Se os números de versão forem os mesmos, os GPOs no servidor CIFS não serão atualizados.

* Os GPOs são atualizados a cada 16 horas.
+
O ONTAP recupera e aplica GPOs de configurações de segurança a cada 16 horas, independentemente de estes GPOs terem sido alterados ou não.

+
[NOTE]
====
O valor padrão de 16 horas não pode ser alterado na versão atual do ONTAP. É uma configuração padrão do cliente Windows.

====
* Todos os GPOs podem ser atualizados manualmente com um comando ONTAP.
+
Este comando simula o comando Windows `gpupdate.exe``/force.



.Informações relacionadas
xref:manual-update-gpo-settings-task.adoc[Atualizar manualmente as definições de GPO no servidor CIFS]
