---
permalink: smb-admin/install-self-signed-root-ca-certificate-svm-task.html 
sidebar: sidebar 
keywords: ldap, authentication, tls, bind, server, install, self-signed, root, ca, certificate, svm, install the self-signed root ca certificate on the svm 
summary: Se a autenticação LDAP com TLS for necessária ao vincular a servidores LDAP, primeiro você deverá instalar o certificado de CA raiz autoassinado no SVM. 
---
= Instale o certificado de CA raiz autoassinado no SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se a autenticação LDAP com TLS for necessária ao vincular a servidores LDAP, primeiro você deverá instalar o certificado de CA raiz autoassinado no SVM.

.Sobre esta tarefa
Quando o LDAP sobre TLS está ativado, o cliente LDAP do ONTAP no SVM não oferece suporte a certificados revogados no ONTAP 9.0 e 9,1.

A partir do ONTAP 9.2, todos os aplicativos do ONTAP que usam comunicações TLS podem verificar o status do certificado digital usando o protocolo OCSP (Online Certificate Status Protocol). Se o OCSP estiver ativado para LDAP através de TLS, os certificados revogados serão rejeitados e a conexão falhará.

.Passos
. Instale o certificado CA raiz autoassinado:
+
.. Inicie a instalação do certificado: `security certificate install -vserver vserver_name -type server-ca`
+
A saída do console exibe a seguinte mensagem: `Please enter Certificate: Press <Enter> when done`

.. Abra o arquivo de certificado `.pem` com um editor de texto, copie o certificado, incluindo as linhas que começam com `-----BEGIN CERTIFICATE-----` e terminam com `-----END CERTIFICATE-----`, e cole o certificado após o prompt de comando.
.. Verifique se o certificado é exibido corretamente.
.. Conclua a instalação pressionando Enter.


. Verifique se o certificado está instalado: `security certificate show -vserver _vserver_name_`

