---
permalink: smb-admin/ipv6-connect-external-servers-concept.html 
sidebar: sidebar 
keywords: create, configuration, requirement, aware, cifs, server, ipv6, connection, external, server, how cifs servers use ipv6 to connect to external servers 
summary: Para criar uma configuração que atenda aos seus requisitos, você deve estar ciente de como os servidores CIFS usam o IPv6 ao fazer conexões com servidores externos. 
---
= Como os servidores CIFS usam o IPv6 para se conetar a servidores externos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para criar uma configuração que atenda aos seus requisitos, você deve estar ciente de como os servidores CIFS usam o IPv6 ao fazer conexões com servidores externos.

* Seleção do endereço de origem
+
Se for feita uma tentativa de ligação a um servidor externo, o endereço de origem selecionado tem de ser do mesmo tipo que o endereço de destino. Por exemplo, se estiver conetando a um endereço IPv6, a máquina virtual de armazenamento (SVM) que hospeda o servidor CIFS deve ter um LIF de dados ou LIF de gerenciamento que tenha um endereço IPv6 para usar como endereço de origem. Da mesma forma, se estiver conetando a um endereço IPv4, o SVM precisa ter um LIF de dados ou um LIF de gerenciamento que tenha um endereço IPv4 para usar como endereço de origem.

* Para servidores dinamicamente descobertos usando DNS, a descoberta do servidor é executada da seguinte forma:
+
** Se o IPv6 estiver desativado no cluster, apenas serão detetados IPv4 endereços de servidores.
** Se IPv6 estiver ativado no cluster, os endereços de servidor IPv4 e IPv6 serão descobertos. Qualquer tipo pode ser usado dependendo da adequação do servidor ao qual o endereço pertence e da disponibilidade de dados IPv6 ou IPv4 ou LIFs de gerenciamento. A descoberta dinâmica de servidor é usada para descobrir controladores de domínio e seus serviços associados, como LSA, NETLOGON, Kerberos e LDAP.


* Conetividade do servidor DNS
+
Se o SVM usa IPv6 ao se conetar a um servidor DNS depende da configuração dos serviços de nome DNS. Se os serviços DNS estiverem configurados para usar endereços IPv6, as conexões serão feitas usando IPv6. Se desejar, a configuração dos serviços de nomes DNS pode usar endereços IPv4 para que as conexões com servidores DNS continuem a usar endereços IPv4. Combinações de endereços IPv4 e IPv6 podem ser especificadas ao configurar serviços de nomes DNS.

* Conetividade do servidor LDAP
+
Se o SVM usa IPv6 ao se conetar a um servidor LDAP depende da configuração do cliente LDAP. Se o cliente LDAP estiver configurado para usar endereços IPv6, as conexões serão feitas usando IPv6. Se desejar, a configuração do cliente LDAP pode usar endereços IPv4 para que as conexões com servidores LDAP continuem a usar endereços IPv4. Combinações de endereços IPv4 e IPv6 podem ser especificadas ao configurar a configuração do cliente LDAP.

+
[NOTE]
====
A configuração do cliente LDAP é usada ao configurar o LDAP para serviços de nome de usuário, grupo e netgroup UNIX.

====
* Conetividade do servidor NIS
+
Se o SVM usa IPv6 ao conetar-se a um servidor NIS depende da configuração dos serviços de nome NIS. Se os serviços NIS estiverem configurados para usar endereços IPv6, as conexões serão feitas usando IPv6. Se desejar, a configuração dos serviços de nomes NIS pode usar endereços IPv4 para que as conexões com servidores NIS continuem a usar endereços IPv4. Combinações de endereços IPv4 e IPv6 podem ser especificadas ao configurar serviços de nomes NIS.

+
[NOTE]
====
Os serviços de nomes NIS são usados para armazenar e gerenciar objetos de nome de usuário, grupo, netgroup e host UNIX.

====


.Informações relacionadas
xref:enable-ipv6-task.adoc[Habilitação do IPv6 para SMB (somente administradores de cluster)]

xref:monitor-display-ipv6-sessions-task.adoc[Monitoramento e exibição de informações sobre IPv6 sessões SMB]
