---
permalink: smb-admin/limits-configuring-unix-symbolic-links-concept.html 
sidebar: sidebar 
keywords: limit, configuring, configure, unix, symbolic, link, smb, access, limits when configuring unix symbolic links for smb access 
summary: Você precisa estar ciente de certos limites ao configurar links simbólicos UNIX para acesso SMB. 
---
= Limites ao configurar links simbólicos UNIX para acesso SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você precisa estar ciente de certos limites ao configurar links simbólicos UNIX para acesso SMB.

|===
| Limite | Descrição 


 a| 
45
 a| 
Comprimento máximo do nome do servidor CIFS que você pode especificar ao usar um FQDN para o nome do servidor CIFS.

[NOTE]
====
Você pode, alternativamente, especificar o nome do servidor CIFS como um nome NetBIOS, que é limitado a 15 carateres.

====


 a| 
80
 a| 
Comprimento máximo do nome da partilha.



 a| 
256
 a| 
Comprimento máximo do caminho UNIX que você pode especificar ao criar um link simbólico ou ao modificar o caminho UNIX de um link simbólico existente. O caminho UNIX deve começar com um "'/`" (slash) and end with a "`/'". As barras de início e fim contam como parte do limite de 256 carateres.



 a| 
256
 a| 
Comprimento máximo do caminho CIFS que você pode especificar ao criar um link simbólico ou ao modificar o caminho CIFS de um link simbólico existente. O caminho CIFS deve começar com um "'/`" (slash) and end with a "`/'". As barras de início e fim contam como parte do limite de 256 carateres.

|===
.Informações relacionadas
xref:create-symbolic-link-mappings-task.adoc[Criando mapeamentos de links simbólicos para compartilhamentos SMB]
