---
permalink: smb-admin/local-users-groups-concepts-concept.html 
sidebar: sidebar 
keywords: local, user, group, basic, information, determine, determining, configure, environment, local users and groups concepts 
summary: Você deve saber o que são usuários e grupos locais e algumas informações básicas sobre eles, antes de determinar se deseja configurar e usar usuários e grupos locais em seu ambiente. 
---
= Conceitos de usuários e grupos locais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve saber o que são usuários e grupos locais e algumas informações básicas sobre eles, antes de determinar se deseja configurar e usar usuários e grupos locais em seu ambiente.

* *Usuário local*
+
Uma conta de usuário com um identificador de segurança exclusivo (SID) que tem visibilidade somente na máquina virtual de armazenamento (SVM) na qual é criada. As contas de usuário locais têm um conjunto de atributos, incluindo nome de usuário e SID. Uma conta de usuário local autentica localmente no servidor CIFS usando autenticação NTLM.

+
As contas de usuário têm vários usos:

+
** Usado para conceder _Gerenciamento de Direitos de Usuário_ Privileges a um usuário.
** Usado para controlar o acesso em nível de compartilhamento e em nível de arquivo aos recursos de arquivo e pasta que o SVM possui.


* *Grupo local*
+
Um grupo com um SID exclusivo tem visibilidade somente na SVM em que ele é criado. Grupos contêm um conjunto de membros. Os membros podem ser usuários locais, usuários de domínio, grupos de domínio e contas de máquinas de domínio. Os grupos podem ser criados, modificados ou excluídos.

+
Os grupos têm vários usos:

+
** Usado para conceder _Gerenciamento de Direitos de Usuário_ Privileges aos seus membros.
** Usado para controlar o acesso em nível de compartilhamento e em nível de arquivo aos recursos de arquivo e pasta que o SVM possui.


* *Domínio local*
+
Um domínio que tem escopo local, limitado pelo SVM. O nome do domínio local é o nome do servidor CIFS. Os usuários e grupos locais estão contidos no domínio local.

* *Identificador de segurança (SID)*
+
Um SID é um valor numérico de comprimento variável que identifica os princípios de segurança do estilo Windows. Por exemplo, um SID típico assume a seguinte forma: S-1-5-21-3139654847-1303905135-2517279418-123456.

* * Autenticação NTLM*
+
Um método de segurança do Microsoft Windows usado para autenticar usuários em um servidor CIFS.

* *Banco de dados replicado em cluster (RDB)*
+
Um banco de dados replicado com uma instância em cada nó em um cluster. Os objetos de usuário local e grupo são armazenados no RDB.


