---
permalink: smb-admin/manage-smb-level-acls-concept.html 
sidebar: sidebar 
keywords: change, share-level, acl, user, access, right, share, configure, windows, unix, group, guidelines for managing smb share-level acls 
summary: Você pode alterar ACLs de nível de compartilhamento para dar aos usuários mais ou menos direitos de acesso ao compartilhamento. Você pode configurar ACLs de nível de compartilhamento usando usuários e grupos do Windows ou usuários e grupos UNIX. 
---
= Saiba mais sobre como gerenciar ACLs de nível de compartilhamento do ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode alterar ACLs de nível de compartilhamento para dar aos usuários mais ou menos direitos de acesso ao compartilhamento. Você pode configurar ACLs de nível de compartilhamento usando usuários e grupos do Windows ou usuários e grupos UNIX.

Por padrão, a ACL de nível de compartilhamento dá controle total ao grupo padrão chamado Everyone. Controle total na ACL significa que todos os usuários no domínio e todos os domínios confiáveis têm acesso total ao compartilhamento. Você pode controlar o nível de acesso de uma ACL de nível de compartilhamento usando o link:../smb-admin/create-share-access-control-lists-task.html["Console de Gerenciamento Microsoft (MMC) em um cliente Windows ou na linha de comando ONTAP"].

As diretrizes a seguir se aplicam quando você usa o MMC:

* Os nomes de usuário e grupo especificados devem ser nomes do Windows.
* Você pode especificar apenas permissões do Windows.


As diretrizes a seguir se aplicam quando você usa a linha de comando ONTAP:

* Os nomes de usuário e grupo especificados podem ser nomes do Windows ou nomes UNIX.
+
Se um tipo de usuário e grupo não for especificado ao criar ou modificar ACLs, o tipo padrão será usuários e grupos do Windows.

* Você pode especificar apenas permissões do Windows.

