---
permalink: smb-admin/manage-netbios-aliases-concept.html 
sidebar: sidebar 
keywords: netbios, alternative, name, smb, client, configuring, configure, consolidate, consolidating, data, original, file, server, manage netbios aliases for smb servers 
summary: Os aliases NetBIOS são nomes alternativos para o servidor SMB que os clientes SMB podem usar ao se conetar ao servidor SMB. A configuração de aliases NetBIOS para um servidor SMB pode ser útil quando você está consolidando dados de outros servidores de arquivos para o servidor SMB e deseja que o servidor SMB responda aos nomes dos servidores de arquivos originais. 
---
= Saiba mais sobre como gerenciar aliases NetBIOS para servidores SMB ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os aliases NetBIOS são nomes alternativos para o servidor SMB que os clientes SMB podem usar ao se conetar ao servidor SMB. A configuração de aliases NetBIOS para um servidor SMB pode ser útil quando você está consolidando dados de outros servidores de arquivos para o servidor SMB e deseja que o servidor SMB responda aos nomes dos servidores de arquivos originais.

Você pode especificar uma lista de aliases NetBIOS ao criar o servidor SMB ou a qualquer momento depois de criar o servidor SMB. Você pode adicionar ou remover aliases NetBIOS da lista a qualquer momento. Você pode se conetar ao servidor SMB usando qualquer um dos nomes na lista de alias do NetBIOS.

.Informações relacionadas
xref:display-netbios-over-tcp-connections-task.adoc[Exibir informações sobre NetBIOS sobre conexões TCP]
