---
permalink: smb-admin/manual-update-gpo-settings-task.html 
sidebar: sidebar 
keywords: update, group, policy, object, gpo, setting, cifs, server, manual, update, applied, apply, manual updating gpo settings on the cifs server 
summary: 'Se pretender atualizar imediatamente as definições do GPO (Group Policy Object) no servidor CIFS, pode atualizar manualmente as definições. Você pode atualizar apenas as configurações alteradas ou forçar uma atualização para todas as configurações, incluindo as configurações que foram aplicadas anteriormente, mas não foram alteradas.' 
---
= Atualizar manualmente as configurações do GPO em servidores SMB do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se pretender atualizar imediatamente as definições do GPO (Group Policy Object) no servidor CIFS, pode atualizar manualmente as definições. Você pode atualizar apenas as configurações alteradas ou forçar uma atualização para todas as configurações, incluindo as configurações que foram aplicadas anteriormente, mas não foram alteradas.

.Passo
. Execute a ação apropriada:
+
|===
| Se você quiser atualizar... | Digite o comando... 


 a| 
Definições GPO alteradas
 a| 
`vserver cifs group-policy update -vserver _vserver_name_`



 a| 
Todas as definições do GPO
 a| 
`vserver cifs group-policy update -vserver _vserver_name_ -force-reapply-all-settings true`

|===


.Informações relacionadas
xref:gpos-updated-server-concept.adoc[Como os GPOs são atualizados no servidor CIFS]
