---
permalink: smb-admin/metadata-caching-concept.html 
sidebar: sidebar 
keywords: enable, smb, metadata, cache, store, path, file, attribute, data, performance, client, workload, how smb metadata caching works 
summary: Quando ativado, o cache de metadados SMB armazena dados de caminho e atributo de arquivo por um período limitado de tempo. Isso pode melhorar a performance do SMB para clientes SMB 1,0 com workloads comuns. 
---
= Saiba mais sobre o cache de metadados ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O armazenamento em cache de metadados permite o armazenamento em cache de atributos de arquivo em clientes SMB 1,0 para fornecer acesso mais rápido aos atributos de arquivo e pasta. Você pode ativar ou desativar o cache de atributos por compartilhamento. Você também pode configurar o tempo de permanência para entradas em cache se o armazenamento em cache de metadados estiver habilitado. A configuração do cache de metadados não é necessária se os clientes estiverem se conetando a compartilhamentos por SMB 2.x ou SMB 3,0.

Quando ativado, o cache de metadados SMB armazena dados de caminho e atributo de arquivo por um período limitado de tempo. Isso pode melhorar a performance do SMB para clientes SMB 1,0 com workloads comuns.

Para certas tarefas, o SMB cria uma quantidade significativa de tráfego que pode incluir várias consultas idênticas para metadados de caminho e arquivo. Você pode reduzir o número de consultas redundantes e melhorar o desempenho para clientes SMB 1,0 usando o cache de metadados SMB para buscar informações do cache.

[NOTE]
====
Embora improvável, é possível que o cache de metadados possa servir informações obsoletas para clientes SMB 1,0. Se o seu ambiente não puder suportar esse risco, você não deve habilitar esse recurso.

====