---
permalink: smb-admin/modify-dynamic-dns-domain-before-moving-server-task.html 
sidebar: sidebar 
keywords: active, directory-integrated, dns, server, dynamic, register, smb, server, record, modify, ddns, storage, virtual, machine, svm, modify the dynamic dns domain on the svm before moving the smb server 
summary: 'Se desejar que o servidor DNS integrado ao ative Directory Registre dinamicamente os Registros DNS do servidor SMB no DNS ao mover o servidor SMB para outro domínio, você deverá modificar o DNS dinâmico (DDNS) na máquina virtual de armazenamento (SVM) antes de mover o servidor SMB.' 
---
= Modifique o domínio DNS dinâmico na SVM antes de mover o servidor SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se desejar que o servidor DNS integrado ao ative Directory Registre dinamicamente os Registros DNS do servidor SMB no DNS ao mover o servidor SMB para outro domínio, você deve modificar DNS dinâmico (DDNS) na máquina virtual de armazenamento (SVM) antes de mover o servidor SMB.

.Antes de começar
Os serviços de nomes DNS devem ser modificados no SVM para usar o domínio DNS que contém os Registros de localização do serviço para o novo domínio que conterá a conta de computador do servidor SMB. Se você estiver usando DDNS seguro, você deve usar servidores de nomes DNS integrados ao ative Directory.

.Sobre esta tarefa
Embora o DDNS (se configurado no SVM) adicione automaticamente os Registros DNS para LIFs de dados ao novo domínio, os Registros DNS para o domínio original não são excluídos automaticamente do servidor DNS original. Você deve excluí-los manualmente.

Para concluir as modificações do DDNS antes de mover o servidor SMB, consulte o seguinte tópico:

link:../networking/configure_dynamic_dns_services.html["Configurar serviços DNS dinâmicos"]
