---
permalink: smb-admin/monitor-security-policy-job-task.html 
sidebar: sidebar 
keywords: apply, security, policy, storage, virtual, machine, svm, monitor, progress, policy, job, ascertain, application, long-running, bulk, security, file, folder, monitor the security policy job 
summary: 'Ao aplicar a diretiva de segurança a máquinas virtuais de armazenamento (SVMs), você pode monitorar o progresso da tarefa monitorando a tarefa de diretiva de segurança. Isso é útil se você quiser verificar se a aplicação da diretiva de segurança foi bem-sucedida. Isso também é útil se você tiver um trabalho de longa duração onde você estiver aplicando segurança em massa a um grande número de arquivos e pastas.' 
---
= Monitorar tarefas de política de segurança do ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao aplicar a diretiva de segurança a máquinas virtuais de armazenamento (SVMs), você pode monitorar o progresso da tarefa monitorando a tarefa de diretiva de segurança. Isso é útil se você quiser verificar se a aplicação da diretiva de segurança foi bem-sucedida. Isso também é útil se você tiver um trabalho de longa duração onde você estiver aplicando segurança em massa a um grande número de arquivos e pastas.

.Sobre esta tarefa
Para exibir informações detalhadas sobre um trabalho de política de segurança, use o `-instance` parâmetro.

.Passo
. Monitorar o trabalho de política de segurança: `vserver security file-directory job show -vserver vserver_name`
+
`vserver security file-directory job show -vserver vs1`

+
[listing]
----

Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
53322  Fsecurity Apply      vs1        node1          Success
       Description: File Directory Security Apply Job
----

