---
permalink: smb-admin/network-protocol-support-requirements-concept.html 
sidebar: sidebar 
keywords: network, protocol, requirement, implement, ontap, branchcache, support, network protocol support requirement 
summary: Você deve estar ciente dos requisitos de protocolo de rede para implementar o ONTAP BranchCache. 
---
= Requisitos de suporte ao protocolo de rede
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve estar ciente dos requisitos de protocolo de rede para implementar o ONTAP BranchCache.

Você pode implementar o recurso ONTAP BranchCache em redes IPv4 e IPv6 usando SMB 2,1 ou posterior.

Todos os servidores CIFS e máquinas de filiais que participam da implementação do BranchCache devem ter o protocolo SMB 2,1 ou posterior ativado. O SMB 2,1 tem extensões de protocolo que permitem que um cliente participe de um ambiente BranchCache. Esta é a versão mínima do protocolo SMB que oferece suporte ao BranchCache. O SMB 2,1 suporta a versão BranchCache 1.

Se você quiser usar o BranchCache versão 2, o SMB 3,0 é a versão mínima suportada. Todos os servidores CIFS e máquinas de filiais que participam de uma implementação BranchCache 2 devem ter o SMB 3,0 ou posterior habilitado.

Se você tiver escritórios remotos onde alguns dos clientes suportam apenas o SMB 2,1 e alguns dos clientes suportam o SMB 3,0, você pode implementar uma configuração BranchCache no servidor CIFS que fornece suporte de cache tanto no BranchCache 1 quanto no BranchCache 2.

[NOTE]
====
Embora o recurso Microsoft BranchCache suporte ao uso dos protocolos HTTP/HTTPS e SMB como protocolos de acesso a arquivos, o ONTAP BranchCache só suporta o uso de SMB.

====