---
permalink: smb-admin/performance-impact-encryption-concept.html 
sidebar: sidebar 
keywords: smb, session, encryption, communication, windows, client, experience, performance, impact, affect, server, node, svm, performance impact of smb encryption 
summary: 'Quando as sessões SMB usam criptografia SMB, todas as comunicações SMB de e para clientes Windows têm um impactos na performance, o que afeta tanto os clientes quanto o servidor (ou seja, os nós no cluster que executa o SVM que contém o servidor SMB).' 
---
= Impacto na performance da criptografia SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando as sessões SMB usam criptografia SMB, todas as comunicações SMB de e para clientes Windows têm um impactos na performance, o que afeta tanto os clientes quanto o servidor (ou seja, os nós no cluster que executa o SVM que contém o servidor SMB).

O impactos no desempenho mostra como aumento do uso da CPU tanto nos clientes quanto no servidor, embora a quantidade de tráfego de rede não mude.

A extensão do impactos no desempenho depende da versão do ONTAP 9 que você está executando. A partir do ONTAP 9.7, um novo algoritmo de criptografia off-load pode permitir melhor desempenho no tráfego SMB criptografado. A descarga de criptografia SMB é ativada por padrão quando a criptografia SMB está ativada.

O desempenho aprimorado da criptografia SMB requer a capacidade de descarga AES-NI. Consulte o Hardware Universe (HWU) para verificar se a descarga AES-NI é suportada para sua plataforma.

Melhorias adicionais de desempenho também são possíveis se você for capaz de usar SMB versão 3,11, que suporta o algoritmo GCM muito mais rápido.

Dependendo da sua rede, versão do ONTAP 9, versão do SMB e implementação do SVM, o impacto na performance da criptografia SMB pode variar muito. Você pode verificá-lo somente por meio de testes em seu ambiente de rede.

A encriptação SMB está desativada por predefinição no servidor SMB. Você deve habilitar a criptografia SMB somente nos compartilhamentos SMB ou servidores SMB que exigem criptografia. Com a criptografia SMB, o ONTAP realiza processamento adicional de descriptografar as solicitações e criptografar as respostas para cada solicitação. A criptografia SMB deve, portanto, ser ativada somente quando necessário.
