---
permalink: smb-admin/provide-security-access-based-enumeration-task.html 
sidebar: sidebar 
keywords: access-based, enumeration, abe, enable, smb, share, user, folder, file, contain, within, share, individual, permission, restriction, resource, environment, provide folder security on shares with access-based enumeration 
summary: 'Quando a enumeração baseada em acesso (ABE) está ativada em um compartilhamento SMB, os usuários que não têm permissão para acessar uma pasta ou arquivo contido no compartilhamento (seja por restrições de permissão individuais ou de grupo) não veem esse recurso compartilhado exibido em seu ambiente.' 
---
= Forneça segurança de pastas em compartilhamentos com visão geral de enumeração baseada em acesso
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando a enumeração baseada em acesso (ABE) está ativada em um compartilhamento SMB, os usuários que não têm permissão para acessar uma pasta ou arquivo contido no compartilhamento (seja por restrições de permissão individuais ou de grupo) não veem esse recurso compartilhado exibido em seu ambiente, embora o próprio compartilhamento permaneça visível.

As propriedades de compartilhamento convencionais permitem especificar quais usuários (individualmente ou em grupos) têm permissão para exibir ou modificar arquivos ou pastas contidos no compartilhamento. No entanto, eles não permitem que você controle se pastas ou arquivos dentro do compartilhamento são visíveis para usuários que não têm permissão para acessá-los. Isso pode causar problemas se os nomes dessas pastas ou arquivos dentro do compartilhamento descreverem informações confidenciais, como os nomes de clientes ou produtos em desenvolvimento.

A enumeração baseada em acesso (ABE) estende as propriedades de compartilhamento para incluir a enumeração de arquivos e pastas dentro do compartilhamento. Portanto, O ABE permite filtrar a exibição de arquivos e pastas dentro do compartilhamento com base nos direitos de acesso do usuário. Ou seja, o compartilhamento em si seria visível para todos os usuários, mas os arquivos e pastas dentro do compartilhamento poderiam ser exibidos ou ocultados de usuários designados. Além de proteger informações confidenciais em seu local de trabalho, o ABE permite simplificar a exibição de grandes estruturas de diretórios para benefício dos usuários que não precisam acessar toda a sua gama de conteúdo. Por exemplo, o compartilhamento em si seria visível para todos os usuários, mas arquivos e pastas dentro do compartilhamento poderiam ser exibidos ou ocultos.

Saiba mais link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Performance_impact_when_using_CIFS_Access_Based_Enumeration["Impacto no desempenho ao usar enumeração baseada em acesso SMB/CIFS"^]sobre .
