---
permalink: smb-admin/reasons-creating-local-users-groups-concept.html 
sidebar: sidebar 
keywords: creating, create, local, user, group, storage, virtual, machine, svm, access, smb, domain, controllers, dc, assign, privilege, workgroup, server, reasons for creating local users and local groups 
summary: 'Há várias razões para criar usuários locais e grupos locais na sua máquina virtual de storage (SVM). Por exemplo, você pode acessar um servidor SMB usando uma conta de usuário local se os controladores de domínio (DCs) não estiverem disponíveis, talvez queira usar grupos locais para atribuir Privileges ou se o servidor SMB estiver em um grupo de trabalho.' 
---
= Razões para criar usuários locais ONTAP SMB e grupos locais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Há várias razões para criar usuários locais e grupos locais na sua máquina virtual de storage (SVM). Por exemplo, você pode acessar um servidor SMB usando uma conta de usuário local se os controladores de domínio (DCs) não estiverem disponíveis, talvez queira usar grupos locais para atribuir Privileges ou se o servidor SMB estiver em um grupo de trabalho.

Você pode criar uma ou mais contas de usuário locais pelos seguintes motivos:

* Seu servidor SMB está em um grupo de trabalho e os usuários de domínio não estão disponíveis.
+
Os utilizadores locais são necessários nas configurações do grupo de trabalho.

* Você deseja a capacidade de autenticar e fazer login no servidor SMB se os controladores de domínio não estiverem disponíveis.
+
Os usuários locais podem se autenticar com o servidor SMB usando a autenticação NTLM quando o controlador de domínio está inativo ou quando problemas de rede impedem que o servidor SMB entre em Contato com o controlador de domínio.

* Você deseja atribuir _User Rights Management_ Privileges a um usuário local.
+
_User Rights Management_ é a capacidade de um administrador de servidor SMB controlar quais direitos os usuários e grupos têm no SVM. Você pode atribuir Privileges a um usuário atribuindo o Privileges à conta do usuário ou tornando o usuário membro de um grupo local que tenha esses Privileges.



Você pode criar um ou mais grupos locais pelos seguintes motivos:

* O servidor SMB está em um grupo de trabalho e os grupos de domínio não estão disponíveis.
+
Os grupos locais não são necessários nas configurações do grupo de trabalho, mas podem ser úteis para gerenciar o Access Privileges para usuários locais do grupo de trabalho.

* Você deseja controlar o acesso aos recursos de arquivos e pastas usando grupos locais para controle de compartilhamento e acesso a arquivos.
* Você deseja criar grupos locais com _User Rights Management_ Privileges personalizado.
+
Alguns grupos de utilizadores incorporados têm Privileges predefinidos. Para atribuir um conjunto personalizado de Privileges, você pode criar um grupo local e atribuir o Privileges necessário a esse grupo. Em seguida, você pode adicionar usuários locais, usuários de domínio e grupos de domínio ao grupo local.



.Informações relacionadas
* xref:local-user-authentication-concept.adoc[Saiba mais sobre autenticação de usuário local]
* xref:list-supported-privileges-reference.html[Lista de Privileges suportados]

