---
permalink: smb-admin/recover-files-folders-previous-versions-concept.html 
sidebar: sidebar 
keywords: ability, microsoft, previous, version, applicable, file, system, support, snapshot, copies, copy, form, enable, technolofy, integral, ontap, recover, file, recover files and folders using previous versions 
summary: A capacidade de usar as versões anteriores da Microsoft é aplicável a sistemas de arquivos que suportam cópias Snapshot de alguma forma e as habilitam. A tecnologia Snapshot faz parte integrante do ONTAP. Os usuários podem recuperar arquivos e pastas de cópias Snapshot de seu cliente Windows usando o recurso versões anteriores da Microsoft. 
---
= Recupere arquivos e pastas usando a visão geral das versões anteriores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A capacidade de usar as versões anteriores da Microsoft é aplicável a sistemas de arquivos que suportam cópias Snapshot de alguma forma e as habilitam. A tecnologia Snapshot faz parte integrante do ONTAP. Os usuários podem recuperar arquivos e pastas de cópias Snapshot de seu cliente Windows usando o recurso versões anteriores da Microsoft.

A funcionalidade de versões anteriores fornece um método para os usuários navegarem pelas cópias Snapshot ou restaurarem dados de uma cópia Snapshot sem a intervenção do administrador de storage. As versões anteriores não são configuráveis. Está sempre ativado. Se o administrador de storage disponibilizar cópias Snapshot em um compartilhamento, o usuário poderá usar versões anteriores para executar as seguintes tarefas:

* Recuperar arquivos que foram excluídos acidentalmente.
* Recuperar de acidentalmente sobrescrever um arquivo.
* Compare versões do arquivo enquanto trabalha.


Os dados armazenados nas cópias Snapshot são somente leitura. Os usuários devem salvar uma cópia de um arquivo em outro local para fazer quaisquer alterações no arquivo. As cópias snapshot são excluídas periodicamente; portanto, os usuários precisam criar cópias de arquivos contidos em versões anteriores se quiserem manter indefinidamente uma versão anterior de um arquivo.
