---
permalink: smb-admin/recommendations-configure-signing-concept.html 
sidebar: sidebar 
keywords: configure, smb, sign, behavior, client, cifs, security, requirement, setting, configuring, configure, security, recommendations for configuring smb signing 
summary: Você pode configurar o comportamento de assinatura SMB entre clientes SMB e o servidor CIFS para atender aos seus requisitos de segurança. As configurações escolhidas ao configurar a assinatura SMB no servidor CIFS dependem de quais são os requisitos de segurança. 
---
= Recomendações de configuração de assinatura SMB do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode configurar o comportamento de assinatura SMB entre clientes SMB e o servidor CIFS para atender aos seus requisitos de segurança. As configurações escolhidas ao configurar a assinatura SMB no servidor CIFS dependem de quais são os requisitos de segurança.

Você pode configurar a assinatura SMB no cliente ou no servidor CIFS. Considere as seguintes recomendações ao configurar a assinatura SMB:

|===
| Se... | Recomendação... 


 a| 
Você deseja aumentar a segurança da comunicação entre o cliente e o servidor
 a| 
Torne a assinatura SMB necessária no cliente ativando a `Require Option (Sign always)` configuração de segurança no cliente.



 a| 
Você deseja que todo o tráfego SMB para uma determinada máquina virtual de storage (SVM) seja assinado
 a| 
Torne necessária a assinatura SMB no servidor CIFS configurando as configurações de segurança para exigir assinatura SMB.

|===
Consulte a documentação da Microsoft para obter mais informações sobre como configurar as configurações de segurança do cliente Windows.
