---
permalink: smb-admin/remove-netbios-aliases-from-list-task.html 
sidebar: sidebar 
keywords: netbios, alias, cifs, server, remove, list, remove netbios aliases from the netbios alias list 
summary: Se você não precisar de aliases NetBIOS específicos para um servidor CIFS, você poderá remover esses aliases NetBIOS da lista. Você também pode remover todos os aliases NetBIOS da lista. 
---
= Remova os aliases NetBIOS da lista de alias NetBIOS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você não precisar de aliases NetBIOS específicos para um servidor CIFS, você poderá remover esses aliases NetBIOS da lista. Você também pode remover todos os aliases NetBIOS da lista.

.Sobre esta tarefa
Você pode remover mais de um alias NetBIOS usando uma lista delimitada por vírgulas. Você pode remover todos os aliases NetBIOS em um servidor CIFS especificando `-` como o valor para o `-netbios-aliases` parâmetro.

.Passos
. Execute uma das seguintes ações:
+
|===
| Se você quiser remover... | Digite... 


 a| 
Aliases NetBIOS específicos da lista
 a| 
`+vserver cifs remove-netbios-aliases -vserver _vserver_name_ -netbios-aliases _NetBIOS_alias_,...+`



 a| 
Todos os aliases NetBIOS da lista
 a| 
`vserver cifs remove-netbios-aliases -vserver _vserver_name_ -netbios-aliases -`

|===
+
`vserver cifs remove-netbios-aliases -vserver vs1 -netbios-aliases alias_1`

. Verifique se os aliases NetBIOS especificados foram removidos: `vserver cifs show -vserver _vserver_name_ -display-netbios-aliases`
+
`vserver cifs show -vserver vs1 -display-netbios-aliases`

+
[listing]
----
Vserver: vs1

         Server Name: CIFS_SERVER
         NetBIOS Aliases: ALIAS_2, ALIAS_3
----

