---
permalink: smb-admin/requirements-roaming-profiles-concept.html 
sidebar: sidebar 
keywords: microsoft, roam, profile, cifs, server, version, ontap, smb, windows, client, support, feature 
summary: Antes de poder utilizar os perfis de roaming da Microsoft com o seu servidor CIFS, tem de saber quais versões do ONTAP e SMB e quais clientes do Windows suportam a funcionalidade. 
---
= Requisitos para usar perfis de roaming
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de poder utilizar os perfis de roaming da Microsoft com o seu servidor CIFS, tem de saber quais versões do ONTAP e SMB e quais clientes do Windows suportam a funcionalidade.



== Requisitos de versão do ONTAP

ONTAP suporta perfis de roaming.



== Requisitos de versão do protocolo SMB

Para máquina virtual de armazenamento (SVM), o ONTAP oferece suporte a perfis de roaming em todas as versões do SMB.



== Requisitos do cliente Windows

Antes que um usuário possa usar os perfis de roaming, o cliente Windows deve suportar o recurso.

Para obter as informações mais recentes sobre quais clientes Windows suportam perfis de roaming, consulte a Matriz de interoperabilidade.

https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^]
