---
permalink: smb-admin/requirements-odx-concept.html 
sidebar: sidebar 
keywords: odx, copy, offload, storage, virtual, machine, svm, requirement, requirements for using odx, odx 
summary: 'Antes de usar o ODX para descarregar cópias com sua máquina virtual de armazenamento (SVM), você precisa estar ciente de certos requisitos.' 
---
= Requisitos para usar ODX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de usar o ODX para descarregar cópias com sua máquina virtual de armazenamento (SVM), você precisa estar ciente de certos requisitos.



== Requisitos de versão do ONTAP

As versões do ONTAP suportam ODX para descarregamentos de cópias.



== Requisitos de versão SMB

* O ONTAP suporta ODX com SMB 3,0 e posterior.
* O SMB 3,0 deve estar habilitado no servidor CIFS antes que o ODX possa ser habilitado:
+
** Ativar o ODX também ativa o SMB 3,0, se ele ainda não estiver ativado.
** Desativar o SMB 3,0 também desativa o ODX.






== Requisitos de servidor e cliente do Windows

Antes de poder utilizar o ODX para descarregar cópias, o cliente Windows tem de suportar a funcionalidade.

O link:https://mysupport.netapp.com/matrix["Matriz de interoperabilidade do NetApp"^]contém as informações mais recentes sobre clientes Windows suportados.



== Requisitos de volume

* Os volumes de origem devem ter no mínimo 1,25 GB.
* Se você usar volumes compatados, o tipo de compactação deve ser adaptável e somente o tamanho do grupo de compactação 8K é suportado.
+
O tipo de compressão secundária não é suportado.


