---
permalink: smb-admin/requirements-microsoft-previous-versions-concept.html 
sidebar: sidebar 
keywords: version, cifs, server, ontap, smb, windows, client, support, snapshot, setting, requirement 
summary: Antes de poder utilizar versões anteriores com o seu servidor CIFS, precisa de saber quais as versões do ONTAP e SMB e quais os clientes do Windows que o suportam. Você também precisa saber sobre o requisito de configuração de snapshot. 
---
= Requisitos do ONTAP SMB para usar versões anteriores do Microsoft
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de poder utilizar versões anteriores com o seu servidor CIFS, precisa de saber quais as versões do ONTAP e SMB e quais os clientes do Windows que o suportam. Você também precisa saber sobre o requisito de configuração de snapshot.



== Requisitos de versão do ONTAP

Suporta versões anteriores.



== Requisitos de versão do protocolo SMB

Para máquina virtual de storage (SVM), o ONTAP é compatível com versões anteriores em todas as versões do SMB.



== Requisitos do cliente Windows

Antes que um usuário possa usar versões anteriores para acessar dados em snapshots, o cliente do Windows deve suportar o recurso.

Para obter as informações mais recentes sobre quais clientes Windows suportam versões anteriores, consulte a Matriz de interoperabilidade.

https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^]



== Requisitos para definições de instantâneos

Para usar versões anteriores para acessar dados em snapshots, uma política de snapshot habilitada deve ser associada ao volume que contém os dados, os clientes devem ser capazes de acessar os dados de snapshot e os snapshots devem existir.
