---
permalink: smb-admin/requirements-gpos-concept.html 
sidebar: sidebar 
keywords: group, policy, object, gpo, smb, server, system, requirement, requirements for using gpos with your smb server 
summary: 'Para usar objetos de diretiva de grupo (GPOs) com seu servidor SMB, o sistema deve atender a vários requisitos.' 
---
= Requisitos de servidor SMB do ONTAP para GPOs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para usar objetos de diretiva de grupo (GPOs) com seu servidor SMB, o sistema deve atender a vários requisitos.

* O SMB deve ser licenciado no cluster. A licença SMB está incluída no link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"]. Se não tiver o ONTAP One e a licença não estiver instalada, contacte o seu representante de vendas.
* Um servidor SMB deve ser configurado e Unido a um domínio do ative Directory do Windows.
* O status de administrador do servidor SMB deve estar ativado.
* Os GPOs devem ser configurados e aplicados à Unidade organizacional do ative Directory (ou) do Windows que contém o objeto de computador servidor SMB.
* O suporte ao GPO deve estar ativado no servidor SMB.

