---
permalink: smb-admin/requirements-local-user-passwords-concept.html 
sidebar: sidebar 
keywords: default, local, user, password, complexity, requirement, password, microsoft, windows, security, policy, requirements for local user passwords 
summary: Por padrão, as senhas de usuário local devem atender aos requisitos de complexidade. Os requisitos de complexidade de senha são semelhantes aos requisitos definidos na diretiva de segurança local do Microsoft Windows. 
---
= Requisitos para senhas de usuários locais do ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Por padrão, as senhas de usuário local devem atender aos requisitos de complexidade. Os requisitos de complexidade de senha são semelhantes aos requisitos definidos na política de segurança local do Microsoft Windows _diretiva de segurança_.

A senha deve atender aos seguintes critérios:

* Deve ter pelo menos seis carateres de comprimento
* Não deve conter o nome da conta de utilizador
* Deve conter carateres de pelo menos três das quatro categorias seguintes:
+
** Carateres maiúsculos em inglês (A a Z)
** Carateres minúsculos em inglês (a a z)
** Base 10 dígitos (0 a 9)
** Carateres especiais:
+
... ! ( ) [ ] : ; " ' > , . ? /





.Informações relacionadas
* xref:enable-disable-password-complexity-local-users-task.adoc[Configurar a complexidade da senha para usuários locais]
* xref:display-server-security-settings-task.adoc[Exibir informações sobre as configurações de segurança do servidor]
* xref:change-local-user-account-passwords-task.adoc[Altere as senhas da conta de usuário local]

