---
permalink: smb-admin/requirements-configuring-branchcache-concept.html 
sidebar: sidebar 
keywords: meet, prerequisite, branchcache, requirement, requirements for configuring branchcache, configure, configuring 
summary: Depois de atender a alguns pré-requisitos, você pode configurar o BranchCache. 
---
= Requisitos para configurar o ONTAP SMB BranchCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de atender a alguns pré-requisitos, você pode configurar o BranchCache.

Antes de configurar o BranchCache no servidor CIFS para sua SVM, você precisa atender aos requisitos a seguir:

* O ONTAP deve ser instalado em todos os nós do cluster.
* O CIFS deve ser licenciado e um servidor SMB deve ser configurado. A licença SMB está incluída no link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"]. Se não tiver o ONTAP One e a licença não estiver instalada, contacte o seu representante de vendas.
* A conetividade de rede IPv4G ou IPv6G deve ser configurada.
* Para BranchCache 1, o SMB 2,1 ou posterior deve estar ativado.
* Para BranchCache 2, o SMB 3,0 deve estar ativado e os clientes remotos do Windows devem suportar o BranchCache 2.

