---
permalink: smb-admin/reset-rediscovering-servers-task.html 
sidebar: sidebar 
keywords: reset, discover, rediscover, server, cifs, server, discard, store, information, ldap, domain, controller, information, external, respond, reset and rediscover servers 
summary: Redefinir e redescobrir servidores no servidor CIFS permite que o servidor CIFS descarte informações armazenadas sobre servidores LDAP e controladores de domínio. Depois de descartar as informações do servidor, o servidor CIFS readquire as informações atuais sobre esses servidores externos. Isso pode ser útil quando os servidores conetados não estão respondendo adequadamente. 
---
= Redefina e redescubra os servidores SMB do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Redefinir e redescobrir servidores no servidor CIFS permite que o servidor CIFS descarte informações armazenadas sobre servidores LDAP e controladores de domínio. Depois de descartar as informações do servidor, o servidor CIFS readquire as informações atuais sobre esses servidores externos. Isso pode ser útil quando os servidores conetados não estão respondendo adequadamente.

.Passos
. Introduza o seguinte comando: `vserver cifs domain discovered-servers reset-servers -vserver _vserver_name_`
. Exibir informações sobre os servidores recém-redescobertos: `vserver cifs domain discovered-servers show -vserver _vserver_name_`


.Exemplo
O exemplo a seguir redefine e redescobre servidores para máquina virtual de armazenamento (SVM, anteriormente conhecido como SVM) VS1:

[listing]
----
cluster1::> vserver cifs domain discovered-servers reset-servers -vserver vs1

cluster1::> vserver cifs domain discovered-servers show

Node: node1
Vserver: vs1

Domain Name     Type     Preference DC-Name     DC-Address    Status
--------------- -------- ---------- ----------- ------------- -------
example.com     MS-LDAP  adequate   DC-1        1.1.3.4       OK
example.com     MS-LDAP  adequate   DC-2        1.1.3.5       OK
example.com     MS-DC    adequate   DC-1        1.1.3.4       OK
example.com     MS-DC    adequate   DC-2        1.1.3.5       OK
----
.Informações relacionadas
* xref:display-discovered-servers-task.adoc[Exibir informações sobre servidores descobertos]
* xref:stop-start-server-task.adoc[Parar ou iniciar servidores]

