---
permalink: smb-admin/restore-directories-that-contain-junctions-concept.html 
sidebar: sidebar 
keywords: guideline, version, restore, folder, junction, point, guidelines for restoring directories that contain junctions 
summary: Existem certas diretrizes que você deve ter em mente ao usar versões anteriores para restaurar pastas que contêm pontos de junção. 
---
= Saiba mais sobre como restaurar diretórios de versões anteriores que contêm junções ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Existem certas diretrizes que você deve ter em mente ao usar versões anteriores para restaurar pastas que contêm pontos de junção.

Ao usar versões anteriores para restaurar pastas com pastas filhas que são pontos de junção, a restauração pode falhar com um `Access Denied` erro.

Você pode determinar se a pasta que você está tentando restaurar contém uma junção usando o `vol show` comando com a `-parent` opção. Você também pode usar os `vserver security trace` comandos para criar logs detalhados sobre problemas de acesso a arquivos e pastas.

.Informações relacionadas
xref:create-manage-data-volumes-nas-namespaces-concept.adoc[Criação e gerenciamento de volumes de dados em namespaces nas]
