---
permalink: smb-admin/security-descriptors-apply-file-folder-security-concept.html 
sidebar: sidebar 
keywords: security, descriptor, contain, access, control, list, file, folder, audit, user, how security descriptors are used to apply file and folder security 
summary: Os descritores de segurança contêm as listas de controle de acesso que determinam quais ações um usuário pode executar em arquivos e pastas e o que é auditado quando um usuário acessa arquivos e pastas. 
---
= Use descritores de segurança para aplicar a segurança de arquivos e pastas ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os descritores de segurança contêm as listas de controle de acesso que determinam quais ações um usuário pode executar em arquivos e pastas e o que é auditado quando um usuário acessa arquivos e pastas.

* *Permissões*
+
As permissões são permitidas ou negadas pelo proprietário de um objeto e determinam quais ações um objeto (usuários, grupos ou objetos de computador) pode executar em arquivos ou pastas especificados.

* *Descritores de segurança*
+
Descritores de segurança são estruturas de dados que contêm informações de segurança que definem permissões associadas a um arquivo ou pasta.

* *Listas de controle de acesso (ACLs)*
+
Listas de controle de acesso são as listas contidas em um descritor de segurança que contêm informações sobre quais ações os usuários, grupos ou objetos de computador podem executar no arquivo ou pasta à qual o descritor de segurança é aplicado. O descritor de segurança pode conter os dois tipos de ACLs a seguir:

+
** Listas de controle de acesso discricionárias (DACLs)
** Listas de controle de acesso do sistema (SACLs)


* *Listas de controle de acesso discricionárias (DACLs)*
+
As DACLs contêm a lista de SIDS para os usuários, grupos e objetos de computador que têm acesso permitido ou negado para executar ações em arquivos ou pastas. As DACLs contêm zero ou mais entradas de controle de acesso (ACEs).

* *Listas de controle de acesso do sistema (SACLs)*
+
Os SACLs contêm a lista de SIDS para os usuários, grupos e objetos de computador para os quais eventos de auditoria bem-sucedidos ou com falha são registrados. SACLs contêm zero ou mais entradas de controle de acesso (ACEs).

* *Entradas de Controle de Acesso (ACEs)*
+
Os ases são entradas individuais em DACLs ou SACLs:

+
** Uma entrada de controle de acesso DACL especifica os direitos de acesso que são permitidos ou negados para usuários, grupos ou objetos de computador específicos.
** Uma entrada de controle de acesso SACL especifica os eventos de sucesso ou falha a serem registrados ao auditar ações especificadas executadas por determinados usuários, grupos ou objetos de computador.


* * Herança de permissão*
+
A herança de permissões descreve como as permissões definidas em descritores de segurança são propagadas para um objeto de um objeto pai. Somente permissões herdáveis são herdadas por objetos filho. Ao definir permissões no objeto pai, você pode decidir se pastas, subpastas e arquivos podem herdá-los com ""aplicar a `this-folder`, `sub-folders` e 'arquivos"".



.Informações relacionadas
* link:../nas-audit/index.html["Auditoria de SMB e NFS e rastreamento de segurança"]
* xref:configure-apply-audit-policies-ntfs-files-folders-task.adoc[Comandos para configurar e aplicar políticas de auditoria a arquivos e pastas]

