---
permalink: smb-admin/server-support-concept.html 
sidebar: sidebar 
keywords: enable, configure, smb, server, storage, virtual, machine, svm, client, access, file, cluster, smb server support 
summary: 'Você pode ativar e configurar servidores SMB em máquinas virtuais de armazenamento (SVMs) para permitir que os clientes SMB acessem arquivos no cluster.' 
---
= Visão geral do suporte ao servidor SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode ativar e configurar servidores SMB em máquinas virtuais de armazenamento (SVMs) para permitir que os clientes SMB acessem arquivos no cluster.

* Cada SVM de dados no cluster pode ser vinculado a exatamente um domínio do active Directory.
* Os SVMs de dados não precisam estar vinculados ao mesmo domínio.
* Vários SVMs podem ser vinculados ao mesmo domínio.


Você deve configurar as SVMs e LIFs que você está usando para fornecer dados antes de criar um servidor SMB. Se sua rede de dados não for plana, talvez você também precise configurar IPspaces, domínios de broadcast e sub-redes.

.Informações relacionadas
link:../networking/networking_reference.html["Gerenciamento de rede"]

xref:modify-servers-task.html[Modificar servidores SMB]

link:../system-admin/index.html["Administração do sistema"]
