---
permalink: smb-admin/set-server-minimum-authentication-security-level-task.html 
sidebar: sidebar 
keywords: cifs, server, minimum, security, level, lmcompatibilitylevel, smb, token, set the cifs server minimum authentication security level 
summary: Você pode definir o nível mínimo de segurança do servidor SMB, também conhecido como LMCompatibilityLevel, no servidor SMB para atender aos requisitos de segurança da sua empresa para acesso SMB. O nível mínimo de segurança é o nível mínimo dos tokens de segurança que o servidor SMB aceita de clientes SMB. 
---
= Defina o nível mínimo de segurança de autenticação do servidor SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode definir o nível mínimo de segurança do servidor SMB, também conhecido como _LMCompatibilityLevel_, em seu servidor SMB para atender aos requisitos de segurança da sua empresa para acesso ao cliente SMB. O nível mínimo de segurança é o nível mínimo dos tokens de segurança que o servidor SMB aceita de clientes SMB.

[NOTE]
.Sobre esta tarefa
====
* Os servidores SMB no modo de grupo de trabalho suportam apenas a autenticação NTLM. A autenticação Kerberos não é suportada.
* LMCompatibilityLevel aplica-se apenas à autenticação de cliente SMB, não à autenticação de administrador.


====
Você pode definir o nível mínimo de segurança de autenticação para um dos quatro níveis de segurança suportados.

|===
| Valor | Descrição 


 a| 
`lm-ntlm-ntlmv2-krb` (predefinição)
 a| 
A máquina virtual de armazenamento (SVM) aceita segurança de autenticação LM, NTLM, NTLMv2 e Kerberos.



 a| 
`ntlm-ntlmv2-krb`
 a| 
O SVM aceita segurança de autenticação NTLM, NTLMv2 e Kerberos. O SVM nega a autenticação LM.



 a| 
`ntlmv2-krb`
 a| 
O SVM aceita a segurança de autenticação NTLMv2 e Kerberos. O SVM nega a autenticação LM e NTLM.



 a| 
`krb`
 a| 
O SVM aceita apenas a segurança de autenticação Kerberos. O SVM nega a autenticação LM, NTLM e NTLMv2.

|===
.Passos
. Defina o nível mínimo de segurança de autenticação: `vserver cifs security modify -vserver _vserver_name_ -lm-compatibility-level {lm-ntlm-ntlmv2-krb|ntlm-ntlmv2-krb|ntlmv2-krb|krb}`
. Verifique se o nível de segurança de autenticação está definido para o nível desejado: `vserver cifs security show -vserver _vserver_name_`


.Informações relacionadas
xref:enable-disable-aes-encryption-kerberos-task.adoc[Ativar ou desativar a encriptação AES para comunicação baseada no Kerberos]
