---
permalink: smb-admin/share-properties-concept.html 
sidebar: sidebar 
keywords: customize, properties, property, smb, share, how to use smb share properties 
summary: Você pode personalizar as propriedades dos compartilhamentos SMB. 
---
= Use a visão geral das propriedades de compartilhamento SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode personalizar as propriedades dos compartilhamentos SMB.

As propriedades de compartilhamento disponíveis são as seguintes:

|===
| Compartilhar propriedades | Descrição 


 a| 
`oplocks`
 a| 
Esta propriedade especifica que o compartilhamento usa bloqueios oportunistas, também conhecidos como cache do lado do cliente.



 a| 
`browsable`
 a| 
Esta propriedade permite que os clientes Windows naveguem na partilha.



 a| 
`showsnapshot`
 a| 
Essa propriedade especifica que as cópias Snapshot podem ser visualizadas e atravessadas por clientes.



 a| 
`changenotify`
 a| 
Esta propriedade especifica que o compartilhamento suporta solicitações Change Notify. Para compartilhamentos em um SVM, esta é uma propriedade inicial padrão.



 a| 
`attributecache`
 a| 
Essa propriedade permite que o cache de atributos de arquivo no compartilhamento SMB forneça acesso mais rápido aos atributos. O padrão é desabilitar o cache de atributos. Esta propriedade só deve ser ativada se houver clientes conetando-se a compartilhamentos sobre SMB 1,0. Essa propriedade de compartilhamento não se aplica se os clientes estiverem se conetando a compartilhamentos em SMB 2.x ou SMB 3,0.



 a| 
`continuously-available`
 a| 
Esta propriedade permite que clientes SMB que a suportam para abrir arquivos de forma persistente. Os arquivos abertos desta maneira são protegidos contra eventos disruptivos, como failover e giveback.



 a| 
`branchcache`
 a| 
Esta propriedade especifica que o compartilhamento permite que os clientes solicitem hashes BranchCache nos arquivos desse compartilhamento. Esta opção é útil somente se você especificar "'per-share'" como o modo operacional na configuração do CIFS BranchCache.



 a| 
`access-based-enumeration`
 a| 
Esta propriedade especifica que _Access Based Enumeração_ (ABE) está ativada neste compartilhamento. As pastas compartilhadas filtradas por ABE são visíveis para um usuário com base nos direitos de acesso desse usuário individual, impedindo a exibição de pastas ou outros recursos compartilhados que o usuário não tem direitos de acesso.



 a| 
`namespace-caching`
 a| 
Esta propriedade especifica que os clientes SMB que se conetam a esse compartilhamento podem armazenar em cache os resultados da enumeração de diretórios retornados pelos servidores CIFS, o que pode fornecer melhor desempenho. Por padrão, os clientes SMB 1 não armazenam em cache os resultados da enumeração de diretórios. Como os clientes SMB 2 e SMB 3 armazenam resultados de enumeração de diretório em cache por padrão, especificar essa propriedade de compartilhamento fornece benefícios de desempenho apenas para conexões de cliente SMB 1.



 a| 
`encrypt-data`
 a| 
Esta propriedade especifica que a criptografia SMB deve ser usada ao acessar esse compartilhamento. Os clientes SMB que não suportam encriptação ao aceder a dados SMB não poderão aceder a esta partilha.

|===