---
permalink: smb-admin/snapmirror-svms-local-groups-concept.html 
sidebar: sidebar 
keywords: aware, guideline, configure, snapmirror, volume, svm, contain, local, group, guidelines for using snapmirror on svms that contain local groups 
summary: Você deve estar ciente das diretrizes ao configurar o SnapMirror em volumes de propriedade de SVMs que contêm grupos locais. 
---
= Diretrizes para o uso do SnapMirror em SVMs que contêm grupos locais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve estar ciente das diretrizes ao configurar o SnapMirror em volumes de propriedade de SVMs que contêm grupos locais.

Não é possível usar grupos locais em ACEs aplicados a arquivos, diretórios ou compartilhamentos replicados pelo SnapMirror para outro SVM. Se você usar o recurso SnapMirror para criar um espelhamento de DR para um volume em outro SVM e o volume tiver um ACE para um grupo local, o ACE não será válido no espelhamento. Se os dados forem replicados para uma SVM diferente, eles serão migrados para um domínio local diferente. As permissões concedidas a usuários e grupos locais são válidas somente dentro do escopo do SVM no qual foram criados originalmente.
