---
permalink: smb-admin/static-home-directory-share-names-upgrading-concept.html 
sidebar: sidebar 
keywords: home, directory, share, name, dynamic, variable, aware, exist, static, ontap, requirement, what happens to static home directory share names after upgrading 
summary: 'Os nomes de compartilhamento do diretório base devem conter a variável dinâmica %W ou %u. Você deve estar ciente do que acontece com nomes de compartilhamento de diretório home estático existentes após atualizar para uma versão do ONTAP com o novo requisito.' 
---
= O que acontece com nomes estáticos de compartilhamento de diretório base após a atualização
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os nomes de compartilhamento de diretório base devem conter a `%w` variável dinâmica ou `%u` . Você deve estar ciente do que acontece com nomes de compartilhamento de diretório home estático existentes após atualizar para uma versão do ONTAP com o novo requisito.

Se a configuração do diretório base contiver nomes de compartilhamento estáticos e você atualizar para o ONTAP, os nomes de compartilhamento do diretório base estático não serão alterados e ainda serão válidos. No entanto, você não pode criar novos compartilhamentos de diretório base que não contenham a `%w` variável ou `%u`.

Exigir que uma dessas variáveis seja incluída no nome de compartilhamento do diretório home do usuário garante que cada nome de compartilhamento seja exclusivo em toda a configuração do diretório home. Se desejar, você pode alterar os nomes estáticos de compartilhamento do diretório base para nomes que contêm a `%w` variável ou `%u`.
