---
permalink: smb-admin/support-branchcache-group-policy-objects-concept.html 
sidebar: sidebar 
keywords: ontap, branchcache, support, group, policy, object, gpo, centralize, management, configuration, parameter, hash, publication, support for branchcache group policy objects 
summary: 'O ONTAP BranchCache fornece suporte para objetos de Diretiva de Grupo (GPOs) do BranchCache, que permitem o gerenciamento centralizado para determinados parâmetros de configuração do BranchCache. Existem dois GPOs usados para BranchCache, a publicação Hash para BranchCache GPO e o suporte de versão Hash para BranchCache GPO.' 
---
= Saiba mais sobre o suporte do ONTAP SMB para objetos de política de grupo do BranchCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O ONTAP BranchCache fornece suporte para objetos de Diretiva de Grupo (GPOs) do BranchCache, que permitem o gerenciamento centralizado para determinados parâmetros de configuração do BranchCache. Existem dois GPOs usados para BranchCache, a publicação Hash para BranchCache GPO e o suporte de versão Hash para BranchCache GPO.

* *Publicação Hash para o GPO BranchCache*
+
A publicação Hash para BranchCache GPO corresponde ao `-operating-mode` parâmetro. Quando ocorrem atualizações de GPO, esse valor é aplicado a objetos de máquina virtual de armazenamento (SVM) contidos na unidade organizacional (ou) à qual a diretiva de grupo se aplica.

* *Suporte a versão Hash para o GPO BranchCache*
+
O suporte de versão Hash para GPO BranchCache corresponde ao `-versions` parâmetro. Quando ocorrem atualizações de GPO, esse valor é aplicado a objetos SVM contidos na unidade organizacional à qual a diretiva de grupo se aplica.



.Informações relacionadas
xref:applying-group-policy-objects-concept.adoc[Saiba mais sobre como aplicar Objetos de Política de Grupo a servidores SMB]
