---
permalink: smb-admin/support-automatic-node-referrals-concept.html 
sidebar: sidebar 
keywords: enable, smb, automatic, node, referral, aware, ontap, functionality, support, support for smb automatic node referrals 
summary: Antes de ativar as referências de nó automático SMB, você deve estar ciente de que certas funcionalidades do ONTAP não suportam referências. 
---
= Suporte para referências automáticas de nós ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de ativar as referências de nó automático SMB, você deve estar ciente de que certas funcionalidades do ONTAP não suportam referências.

* Os seguintes tipos de volumes não suportam referências de nó automáticas SMB:
+
** Membros somente leitura de um espelho de compartilhamento de carga
** Volume de destino de um espelho de proteção de dados


* As referências de nó não se movem ao lado de uma movimentação de LIF.
+
Se um cliente estiver usando uma conexão referida por meio de uma conexão SMB 2.x ou SMB 3,0 e um LIF de dados se mover sem interrupções, o cliente continuará a usar a mesma conexão referida, mesmo que o LIF não seja mais local para os dados.

* As referências de nó não se movem ao lado de uma movimentação de volume.
+
Se um cliente estiver usando uma conexão referida em qualquer conexão SMB e ocorrer uma movimentação de volume, o cliente continuará a usar a mesma conexão referida, mesmo que o volume não esteja mais localizado no mesmo nó que o LIF de dados.


