---
permalink: smb-admin/use-cases-storage-level-access-guard-concept.html 
sidebar: sidebar 
keywords: storage-level, access, guard, additional, security, storage, level, visible, administrator, client, side, desktop, revoke, user, beneficial, use cases for using storage-level access guard 
summary: O Storage-Level Access Guard fornece segurança adicional no nível de armazenamento, que não é visível do lado do cliente; portanto, ele não pode ser revogado por nenhum dos usuários ou administradores de seus desktops. Há certos casos de uso em que a capacidade de controlar o acesso no nível de storage é benéfica. 
---
= Casos de uso para usar o Storage-Level Access Guard
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Storage-Level Access Guard fornece segurança adicional no nível de armazenamento, que não é visível do lado do cliente; portanto, ele não pode ser revogado por nenhum dos usuários ou administradores de seus desktops. Há certos casos de uso em que a capacidade de controlar o acesso no nível de storage é benéfica.

Os casos de uso típicos para esse recurso incluem os seguintes cenários:

* Proteção da propriedade intelectual através da auditoria e controlo do acesso de todos os utilizadores ao nível do armazenamento
* Armazenamento para empresas de serviços financeiros, incluindo bancos e grupos de negociação
* Serviços governamentais dos EUA com storage de arquivos separado para departamentos individuais
* Universidades protegendo todos os arquivos dos alunos

