---
permalink: smb-admin/using-odx-concept.html 
sidebar: sidebar 
keywords: odx, copy, offload, aware, guideline, volume, intra-cluster, inter-cluster, consideration, guidelines for using odx 
summary: Antes de poder usar o ODX para descarga de cópia, você precisa estar ciente das diretrizes. Por exemplo, você precisa saber em quais tipos de volumes você pode usar ODX e você precisa entender as considerações do ODX intra-cluster e inter-cluster. 
---
= Diretrizes para o uso do ODX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de poder usar o ODX para descarga de cópia, você precisa estar ciente das diretrizes. Por exemplo, você precisa saber em quais tipos de volumes você pode usar ODX e você precisa entender as considerações do ODX intra-cluster e inter-cluster.



== Diretrizes de volume

* Você não pode usar o ODX para descarga de cópia com as seguintes configurações de volume:
+
** O tamanho do volume de origem é inferior a 1,25 GB
+
O tamanho do volume deve ser de 1,25 GB ou maior para usar o ODX.

** Volumes só de leitura
+
O ODX não é usado para arquivos e pastas residentes em espelhos de compartilhamento de carga ou em volumes de destino SnapMirror ou SnapVault.

** Se o volume de origem não for desduplicado


* Cópias ODX são suportadas apenas para cópias intra-cluster.
+
Não é possível usar o ODX para copiar arquivos ou pastas para um volume em outro cluster.





== Outras diretrizes

* Em ambientes SMB, para usar o ODX para descarga de cópia, os arquivos devem ter 256 kb ou mais.
+
Arquivos menores são transferidos usando uma operação de cópia tradicional.

* O descarregamento de cópia ODX usa a deduplicação como parte do processo de cópia.
+
Se você não quiser que a deduplicação ocorra em volumes SVM ao copiar ou mover dados, desative a descarga de cópia ODX nesse SVM.

* O aplicativo que executa a transferência de dados deve ser escrito para suportar ODX.
+
As operações de aplicação que suportam ODX incluem o seguinte:

+
** Operações de gerenciamento do Hyper-V, como criar e converter discos rígidos virtuais (VHDs), gerenciar snapshots e copiar arquivos entre máquinas virtuais
** Operações do Windows Explorer
** Comandos de cópia do Windows PowerShell
** Comandos de cópia do prompt de comando do Windows
+
Robocopy no prompt de comando do Windows suporta ODX.

+
[NOTE]
====
Os aplicativos devem estar em execução em servidores Windows ou clientes que suportem ODX.

====
+
Para obter mais informações sobre aplicativos ODX compatíveis em servidores e clientes Windows, consulte a Biblioteca Microsoft TechNet.





.Informações relacionadas
http://technet.microsoft.com/en-us/library/["Microsoft TechNet Library: technet.microsoft.com/en-us/library/"]
