---
permalink: smb-admin/view-shares-mmc-task.html 
sidebar: sidebar 
keywords: information, smb, share, svm, perform, management, task, microsoft, management, console, mmc, view, share, connect, svm, view information about smb shares using the mmc 
summary: 'Você pode exibir informações sobre compartilhamentos SMB no SVM e executar algumas tarefas de gerenciamento usando o Console de Gerenciamento da Microsoft (MMC). Antes de poder visualizar os compartilhamentos, você precisa conetar o MMC ao SVM.' 
---
= Exibir informações sobre compartilhamentos SMB usando o MMC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode exibir informações sobre compartilhamentos SMB no SVM e executar algumas tarefas de gerenciamento usando o Console de Gerenciamento da Microsoft (MMC). Antes de poder visualizar os compartilhamentos, você precisa conetar o MMC ao SVM.

.Sobre esta tarefa
Você pode executar as seguintes tarefas em compartilhamentos contidos em SVMs usando o MMC:

* Ver compartilhamentos
* Ver sessões ativas
* Exibir arquivos abertos
* Enumerar a lista de sessões, ficheiros e ligações em árvore no sistema
* Feche os ficheiros abertos no sistema
* Feche as sessões abertas
* Criar/gerenciar compartilhamentos


[NOTE]
====
As visualizações exibidas pelos recursos anteriores são específicas de nós e não específicas de cluster. Portanto, quando você usa o MMC para se conetar ao nome do host do servidor SMB (ou seja, cifs01.domain.local), você é encaminhado, com base em como configurou o DNS, para um único LIF dentro do cluster.

====
As seguintes funções não são suportadas no MMC para ONTAP:

* Criando novos usuários/grupos locais
* Gerir/visualizar utilizadores/grupos locais existentes
* Visualização de eventos ou registos de desempenho
* Armazenamento
* Serviços e aplicações


Nos casos em que a operação não é suportada, você pode ter `remote procedure call failed` erros.

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/FAQ%3A_Using_Windows_MMC_with_ONTAP["Perguntas frequentes: Usando o Windows MMC com ONTAP"]

.Passos
. Para abrir o MMC de Gerenciamento de computador em qualquer servidor Windows, no *Painel de Controle*, selecione *Ferramentas administrativas* > *Gerenciamento de computador*.
. Selecione *Ação* > *ligar a outro computador*.
+
A caixa de diálogo Selecionar computador é exibida.

. Digite o nome do sistema de armazenamento ou clique em *Procurar* para localizar o sistema de armazenamento.
. Clique em *OK*.
+
O MMC se coneta ao SVM.

. No painel de navegação, clique em *pastas compartilhadas* > *compartilhamentos*.
+
Uma lista de compartilhamentos no SVM é exibida no painel de exibição direito.

. Para exibir as propriedades de compartilhamento de um compartilhamento, clique duas vezes no compartilhamento para abrir a caixa de diálogo *Propriedades*.
. Se você não puder se conetar ao sistema de armazenamento usando o MMC, você poderá adicionar o usuário ao grupo BUILTIN ou BUILTIN/Power Users usando um dos seguintes comandos no sistema de armazenamento:
+
[listing]
----

cifs users-and-groups local-groups add-members -vserver <vserver_name> -group-name BUILTIN\Administrators -member-names <domainuser>

cifs users-and-groups local-groups add-members -vserver <vserver_name> -group-name "BUILTIN\Power Users" -member-names <domainuser>
----

