---
permalink: smb-admin/windows-hosts-version-requirements-concept.html 
sidebar: sidebar 
keywords: ontap, branch, office, windows, host, version, requirement, configure, branchcache, ontap and windows hosts version requirements 
summary: Os hosts do ONTAP e da filial do Windows devem atender a certos requisitos de versão antes de poder configurar o BranchCache. 
---
= O ONTAP e o Windows hosts requisitos de versão
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os hosts do ONTAP e da filial do Windows devem atender a certos requisitos de versão antes de poder configurar o BranchCache.

Antes de configurar o BranchCache, você deve garantir que a versão do ONTAP no cluster e clientes de filiais participantes ofereçam suporte ao SMB 2,1 ou posterior e ofereça suporte ao recurso BranchCache. Se você configurar o modo Cache hospedado, você também deve garantir que você use um host suportado para o servidor de cache.

O BranchCache 1 é compatível com as seguintes versões do ONTAP e hosts do Windows:

* Servidor de conteúdo: Máquina virtual de storage (SVM) com ONTAP
* Servidor de cache: Windows Server 2008 R2 ou Windows Server 2012 ou posterior
* Peer ou cliente: Windows 7 Enterprise, Windows 7 Ultimate, Windows 8, Windows Server 2008 R2 ou Windows Server 2012 ou posterior


O BranchCache 2 é compatível com as seguintes versões do ONTAP e hosts do Windows:

* Servidor de conteúdo: SVM com ONTAP
* Servidor de cache: Windows Server 2012 ou posterior
* Peer ou cliente: Windows 8 ou Windows Server 2012 ou posterior

