---
permalink: svm-migrate/cancel-task.html 
sidebar: sidebar 
keywords: svm, migrate, cancel, abort 
summary: 'Se você precisar cancelar uma migração SVM antes que ela seja concluída, use o `vserver migrate abort` comando. Você pode cancelar uma migração SVM somente quando a operação estiver no estado pausado ou com falha. Você não pode cancelar uma migração para o SVM quando o status for "iniciado na transição" ou após a conclusão da transição. Não é possível usar a `abort` opção quando uma migração para SVM estiver em andamento.' 
---
= Cancelar uma migração para SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você precisar cancelar uma migração SVM antes que ela seja concluída, use o `vserver migrate abort` comando. Você pode cancelar uma migração SVM somente quando a operação estiver no estado pausado ou com falha. Você não pode cancelar uma migração para o SVM quando o status for "iniciado na transição" ou após a conclusão da transição. Não é possível usar a `abort` opção quando uma migração para SVM estiver em andamento.

.Passos
. Verifique o status da migração:
+
`dest_cluster> vserver migrate show -vserver <vserver name>`

. Cancelar a migração:
+
`dest_cluster> vserver migrate abort -vserver <vserver name>`

. Verifique o andamento da operação de cancelamento:
+
`dest_cluster> vserver migrate show`

+
O estado de migração mostra migrar-abortar enquanto a operação cancelar está em curso. Quando a operação de cancelamento for concluída, o status de migração não mostra nada.


