---
permalink: svm-migrate/cancel-task.html 
sidebar: sidebar 
keywords: svm, migrate, cancel, abort 
summary: Se precisar cancelar uma migração de SVM antes de ela ser concluída, você poderá cancelá-la somente quando a operação estiver no estado pausado ou com falha. 
---
= Cancelar migração de SVM ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você precisar cancelar uma migração SVM antes de sua conclusão, você pode usar o `vserver migrate abort` comando. Você pode cancelar uma migração SVM somente quando a operação estiver no estado pausado ou com falha. Não é possível cancelar uma migração SVM quando o status for "cutover iniciado" ou após a conclusão da transição. Você não pode usar o `abort` opção quando uma migração de SVM está em andamento.

.Passos
. No cluster de destino, verifique o status da migração:
+
[source, cli]
----
vserver migrate show -vserver <SVM_name>
----
. Cancelar a migração:
+
[source, cli]
----
vserver migrate abort -vserver <SVM_name>
----
. Verifique o andamento da operação de cancelamento:
+
[source, cli]
----
vserver migrate show
----
+
O estado de migração mostra migrar-abortar enquanto a operação cancelar está em curso. Quando a operação de cancelamento for concluída, o status de migração não mostra nada.


