---
permalink: mediator/download-install-pkg-task.html 
sidebar: sidebar 
keywords: mediator, new, release, update, install, download, package 
summary: Faça o download do pacote de instalação do Mediator como parte do processo de instalação. 
---
= Baixe o pacote de instalação do Mediator
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Faça o download do pacote de instalação do Mediator como parte do processo de instalação.

.Passos
. Faça o download do pacote de instalação do Mediador na página do Mediador do ONTAP.
+
https://mysupport.netapp.com/site/products/all/details/ontap-mediator/downloads-tab["Página de download do ONTAP Mediator"^]

. Confirme se o pacote de instalação do Mediator está no diretório de trabalho atual:
+
[listing]
----
[root@sdot-r730-0003a-d6 ~]# ls ontap-mediator-1.8.0.tgz
----
+
[listing]
----
ontap-mediator-1.8.0.tgz
----
+

NOTE: Para o ONTAP Mediator versões 1,4 e anteriores, o instalador é `ontap-mediator` chamado .

+
Se você estiver em um local sem acesso à internet, você deve garantir que o instalador tenha acesso aos pacotes necessários.

. Se necessário, mova o pacote de instalação do Mediator do diretório de download para o diretório de instalação no host do Linux Mediator.
. Descompacte o pacote de instalação:
+
`tar xvfz ontap-mediator-1.8.0.tgz`

+
[listing]
----
ontap-mediator-1.8.0/
ontap-mediator-1.8.0/csc-prod-ONTAP-Mediator.pem
ontap-mediator-1.8.0/csc-prod-chain-ONTAP-Mediator.pem
ontap-mediator-1.8.0/tsa-prod-ONTAP-Mediator.pem
ontap-mediator-1.8.0/tsa-prod-chain-ONTAP-Mediator.pem
ontap-mediator-1.8.0/ONTAP-Mediator-production.pub
ontap-mediator-1.8.0/ontap-mediator-1.8.0
ontap-mediator-1.8.0/ontap-mediator-1.8.0.sig.tsr
ontap-mediator-1.8.0/ontap-mediator-1.8.0.tsr
ontap-mediator-1.8.0/ontap-mediator-1.8.0.sig
----

