---
sidebar: sidebar 
permalink: flexcache-hot-spot/flexcache-hotspot-remediation-overview.html 
keywords: hotspot, FlexCache, HDFA, problem, solution, ONTAP 
summary: Saiba como corrigir hotspotting, um problema comum em muitos workloads de computação de alto desempenho, como renderização de animações ou EDA, com o FlexCache. 
---
= Correção de hotspots em workloads de computação de alta performance com o ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um problema comum em muitos workloads de computação de alta performance, como renderização de animações ou EDA, é o hotspotting. Hotspotting é uma situação que ocorre quando uma parte específica do cluster ou da rede experimenta uma carga significativamente maior em comparação com outras áreas, levando a gargalos de desempenho e eficiência geral reduzida devido ao tráfego de dados excessivo concentrado nesse local. Por exemplo, um arquivo, ou vários arquivos, está em alta demanda para a tarefa em execução, o que resulta em um gargalo na CPU usada para atender solicitações (por meio de uma afinidade de volume) a esse arquivo. O FlexCache pode ajudar a aliviar esse gargalo, mas deve ser configurado corretamente.

Esta documentação explica como configurar o FlexCache para corrigir hotspotting.


NOTE: A partir de julho de 2024, o conteúdo de relatórios técnicos publicados anteriormente como PDFs foi integrado à documentação do produto ONTAP. Este conteúdo de relatório técnico de correção de hotspot ONTAP é novo na data de sua publicação e nenhum formato anterior foi produzido.



== Conceitos-chave

Ao Planejar a correção de hotspot, é importante entender esses conceitos essenciais.

* *FlexCache de alta densidade (HDF)*: Um FlexCache que é condensado para abranger apenas nós como os requisitos de capacidade de cache permitem
* *HDF Array (HDFA)*: Um grupo de HDFS que são caches da mesma origem, distribuídos pelo cluster
* *Inter-SVM HDFA*: Um HDF do HDFA por máquina virtual de servidor (SVM)
* *Intra-SVM HDFA*: Todos os HDFS no HDFA em um SVM
* *Tráfego leste-oeste*: Tráfego de back-end de cluster gerado a partir de acesso indireto a dados


.O que vem a seguir
* link:flexcache-hotspot-remediation-architecture.html["Entenda como fazer a arquitetura com FlexCache de alta densidade para ajudar a corrigir hotspotting"]
* link:flexcache-hotspot-remediation-hdfa-examples.html["Decida qual a densidade do array do FlexCache"]
* link:flexcache-hotspot-remediation-intra-inter-svm-hdfa.html["Determine a densidade do seu HDFS e decida se você acessará o HDFS usando o NFS com HDFAs inter-SVM e HDFAs intra-SVM"]
* link:flexcache-hotspot-remediation-ontap-config.html["Configurar o HDFA e as LIFs de dados para aproveitar os benefícios do uso do armazenamento em cache sem clusters com configuração ONTAP"]
* link:flexcache-hotspot-remediation-client-config.html["Saiba como configurar clientes para distribuir conexões ONTAP nas com a configuração do cliente"]

