---
permalink: update/index.html 
sidebar: sidebar 
keywords: ontap, upgrade, update, automatic, automated, firmware, bmc, sp, system, timezone database, timezone, security, arp 
summary: Dependendo da sua versão do ONTAP, você pode ativar atualizações automáticas de firmware, sistema e segurança. 
---
= Visão geral das atualizações de firmware, sistema e segurança no ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dependendo da sua versão do ONTAP, você pode ativar atualizações automáticas de firmware, sistema e segurança.

[cols="25,75"]
|===
| Versão de ONTAP | O que está incluído nas atualizações automáticas 


| 9.16.1 e mais tarde  a| 
* Proteção autônoma contra ransomware com inteligência artificial (ARP/AI)
* Base de dados de Fuso horário do ONTAP
* Firmware de storage para dispositivos de storage, discos e compartimentos de disco
* Firmware SP/BMC para processadores de serviço e módulos BMC




| 9.13.1 e mais tarde  a| 
* Base de dados de Fuso horário do ONTAP
* Firmware de storage para dispositivos de storage, discos e compartimentos de disco
* Firmware SP/BMC para processadores de serviço e módulos BMC




| 9.10.1 e mais tarde  a| 
* Firmware de storage para dispositivos de storage, discos e compartimentos de disco
* Firmware SP/BMC para processadores de serviço e módulos BMC




| 9.9.1 e anteriores | Não suportado 
|===
Se uma atualização automática não estiver disponível para a sua versão do ONTAP ou se não tiver atualizações automáticas ativadas, pode executar atualizações de firmware, base de dados de fuso horário e segurança manualmente.

.Links relacionados
* link:firmware-task.html["Aprenda a fazer atualizações de firmware manualmente"]
* link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_update_time_zone_information_in_ONTAP_9["artigo da Knowledge base, como atualizar informações de fuso horário no ONTAP 9"^]
* link:../anti-ransomware/enable-arp-ai-with-au.html["Aprenda a fazer atualizações de segurança manualmente"]




== Vídeo: Recurso de atualização automática de firmware

Veja o recurso de atualização automática de firmware disponível a partir do ONTAP 9.10.1.

video::GoABILT85hQ[youtube,width=848,height=480]