---
permalink: data-protection/configure-custom-snapshot-policies-concept.html 
sidebar: sidebar 
keywords: configure, custom, snapshot, policy 
summary: 'Uma política de snapshot define como o sistema cria snapshots. A política especifica quando criar snapshots, quantas cópias devem ser mantidas e como nomeá-las. Por exemplo, um sistema pode criar um snapshot todos os dias às 12:10 da manhã, manter as duas cópias mais recentes e nomear as cópias "daily.timestamp".' 
---
= Saiba mais sobre como configurar políticas de snapshot personalizadas do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Uma política _snapshot_ define como o sistema cria snapshots. A política especifica quando criar snapshots, quantas cópias devem ser mantidas e como nomeá-las. Por exemplo, um sistema pode criar um snapshot todos os dias às 12:10 da manhã, manter as duas cópias mais recentes e nomear as cópias "diárias.`_timestamp_`".

A política padrão de um volume cria automaticamente snapshots na programação a seguir, com os snapshots mais antigos excluídos para abrir espaço para cópias mais recentes:

* Um máximo de seis snapshots por hora feitos cinco minutos depois da hora.
* Um máximo de dois instantâneos diários tirados de segunda a sábado, 10 minutos após a meia-noite.
* Um máximo de dois instantâneos semanais tirados todos os domingos, 15 minutos após a meia-noite.


A menos que você especifique uma política de snapshot ao criar um volume, o volume herda a política de snapshot associada à máquina virtual de armazenamento (SVM).
