---
permalink: data-protection/convert-mode-snapmirror-synchronous-task.html 
sidebar: sidebar 
keywords: convert, mode, snapmirror, synchronous, relationship 
summary: A partir do ONTAP 9.5, as relações síncronas do SnapMirror são suportadas. Você pode converter o modo de uma relação síncrona SnapMirror de StrictSync para sincronização ou vice-versa. 
---
= Converta o modo de uma relação síncrona ONTAP SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.5, as relações síncronas do SnapMirror são suportadas. Você pode converter o modo de uma relação síncrona SnapMirror de StrictSync para sincronização ou vice-versa.

.Sobre esta tarefa
Você não pode modificar a política de uma relação síncrona SnapMirror para converter seu modo.

.Passos
. A partir do cluster de destino, quiesce a relação síncrona SnapMirror existente:
+
`snapmirror quiesce -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster2::> snapmirror quiesce -destination-path vs1_dr:vol1
----
. No cluster de destino, exclua a relação síncrona SnapMirror existente:
+
`snapmirror delete -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster2::> snapmirror delete -destination-path vs1_dr:vol1
----
. No cluster de origem, libere a relação SnapMirror sem excluir os snapshots comuns:
+
`snapmirror release -relationship-info-only true -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster1::> snapmirror release -relationship-info-only true -destination-path vs1_dr:vol1
----
. No cluster de destino, crie uma relação síncrona SnapMirror especificando o modo para o qual você deseja converter a relação síncrona SnapMirror:
+
`snapmirror create -source-path vs1:vol1 -destination-path <destination_SVM>:<destination_volume> -policy Sync|StrictSync`

+
[listing]
----
cluster2::> snapmirror create -source-path vs1:vol1 -destination-path vs1_dr:vol1 -policy Sync
----
. A partir do cluster de destino, ressincronize a relação SnapMirror:
+
`snapmirror resync -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster2::> snapmirror resync -destination-path vs1_dr:vol1
----


.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["SnapMirror create"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["eliminar SnapMirror"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["silenciamento do snapmirror"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-release.html["lançamento do SnapMirror"^]

