---
permalink: data-protection/define-schedule-create-local-copy-destination-task.html 
sidebar: sidebar 
keywords: define, schedule, create, local copy, destination 
summary: 'Para relacionamentos de replicação unificada e SnapVault, você pode se proteger contra a possibilidade de que uma cópia Snapshot atualizada seja corrompida criando uma cópia da última cópia Snapshot transferida no destino. Essa "cópia local" é mantida independentemente das regras de retenção na origem, de modo que, mesmo que o Snapshot originalmente transferido pelo SnapMirror não esteja mais disponível na origem, uma cópia dele estará disponível no destino.' 
---
= Defina uma agenda para criar uma cópia local no destino com o ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para relacionamentos de replicação unificada e SnapVault, você pode se proteger contra a possibilidade de que uma cópia Snapshot atualizada seja corrompida criando uma cópia da última cópia Snapshot transferida no destino. Essa cópia local é mantida independentemente das regras de retenção na origem, de modo que, mesmo que o Snapshot originalmente transferido pelo SnapMirror não esteja mais disponível na origem, uma cópia dele estará disponível no destino.

.Sobre esta tarefa
Você especifica a programação para criar uma cópia local na `-schedule` opção `snapmirror policy add-rule` do comando.

.Passo
. Defina uma agenda para criar uma cópia local no destino:
+
`snapmirror policy add-rule -vserver _SVM_ -policy _policy_for_rule_ -snapmirror-label _snapmirror-label_ -schedule _schedule_`

+
Saiba mais sobre `snapmirror policy add-rule` o link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-add-rule.html["Referência do comando ONTAP"^]na . Para obter um exemplo de como criar uma agenda de trabalhos, link:create-replication-job-schedule-task.html["Criando um agendamento de trabalho de replicação"]consulte .

+
O exemplo a seguir adiciona uma programação para criar uma cópia local à política padrão `MirrorAndVault`:

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy MirrorAndVault -snapmirror-label my_monthly -schedule my_monthly
----
+
O exemplo a seguir adiciona uma programação para criar uma cópia local à política personalizada `my_unified`:

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy my_unified -snapmirror-label my_monthly -schedule my_monthly
----

