---
permalink: data-protection/define-rule-policy-task.html 
sidebar: sidebar 
keywords: define, rule, policy, data protection 
summary: 'Para políticas personalizadas com o tipo de diretiva "Vault" ou "mirror-Vault", você deve definir pelo menos uma regra que determina quais snapshots são transferidos durante a inicialização e atualização. Você também pode definir regras para políticas padrão com o tipo de política "Vault" ou "mirror-Vault".' 
---
= Defina uma regra para uma política
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para políticas personalizadas com o tipo de política "'Vault'" ou "mirror-Vault", você deve definir pelo menos uma regra que determina quais snapshots são transferidos durante a inicialização e atualização. Você também pode definir regras para políticas padrão com o tipo de política "'Vault'" ou "mirror-Vault".

.Sobre esta tarefa
Cada política com o tipo de política "'Vault'" ou "mirror-Vault" deve ter uma regra que especifique quais snapshots replicar. A regra "bimestral", por exemplo, indica que apenas os instantâneos atribuídos ao rótulo SnapMirror devem ser replicados. Você especifica o rótulo SnapMirror ao configurar a política de snapshot na origem.

Cada tipo de política está associado a uma ou mais regras definidas pelo sistema. Essas regras são atribuídas automaticamente a uma política quando você especifica seu tipo de política. A tabela abaixo mostra as regras definidas pelo sistema.

[cols="3*"]
|===


| Regra definida pelo sistema | Usado em tipos de política | Resultado 


 a| 
sm_created
 a| 
Espelho assíncrono, espelho-Vault, sincronização, StrictSync
 a| 
Um instantâneo criado pelo SnapMirror é transferido na inicialização e atualização.



 a| 
all_source_snapshots
 a| 
espelho assíncrono
 a| 
Novos instantâneos na origem são transferidos na inicialização e atualização.



 a| 
diariamente
 a| 
cofre, espelho-cofre
 a| 
Novos instantâneos na fonte com o rótulo "diário" do SnapMirror são transferidos na inicialização e atualização.



 a| 
semanalmente
 a| 
cofre, espelho-cofre
 a| 
Novos instantâneos na origem com o rótulo "semanal" do SnapMirror são transferidos na inicialização e atualização.



 a| 
mensalmente
 a| 
espelho-cofre
 a| 
Novos instantâneos na fonte com o rótulo SnapMirror ""em quarto lugar" são transferidos na inicialização e atualização.



 a| 
app_consistente
 a| 
Sincronizar, StrictSync
 a| 
Os instantâneos com o rótulo SnapMirror "'app_consistent'" na origem são replicados sincronamente para o destino. Suportado a partir de ONTAP 9.7.

|===
Exceto para o tipo de política "async-mirror", você pode especificar regras adicionais conforme necessário, para políticas padrão ou personalizadas. Por exemplo:

* Para a política padrão `MirrorAndVault`, você pode criar uma regra chamada "bimestral" para combinar snapshots na origem com o rótulo SnapMirror "bimestral".
* Para uma política personalizada com o tipo de política "mirror-Vault", você pode criar uma regra chamada "bi-semporal" para combinar snapshots na origem com o rótulo SnapMirror "'bi-semporal'".


.Passo
. Defina uma regra para uma política:
+
`snapmirror policy add-rule -vserver _SVM_ -policy _policy_for_rule_ -snapmirror-label _snapmirror-label_ -keep _retention_count_`

+
Para obter a sintaxe completa do comando, consulte a página man.

+
O exemplo a seguir adiciona uma regra com o rótulo SnapMirror `bi-monthly` à política padrão `MirrorAndVault`:

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy MirrorAndVault -snapmirror-label bi-monthly -keep 6
----
+
O exemplo a seguir adiciona uma regra com o rótulo SnapMirror `bi-weekly` à política personalizada `my_snapvault`:

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy my_snapvault -snapmirror-label bi-weekly -keep 26
----
+
O exemplo a seguir adiciona uma regra com o rótulo SnapMirror `app_consistent` à política personalizada `Sync`:

+
[listing]
----
cluster_dst::> snapmirror policy add-rule -vserver svm1 -policy Sync -snapmirror-label app_consistent -keep 1
----
+
Em seguida, é possível replicar snapshots do cluster de origem que correspondem a esse rótulo do SnapMirror:

+
[listing]
----
cluster_src::> snapshot create -vserver vs1 -volume vol1 -snapshot snapshot1 -snapmirror-label app_consistent
----

