---
permalink: data-protection/delete-svm-replication-relationship-task.html 
sidebar: sidebar 
keywords: delete, svm, replication, relationship 
summary: Você pode usar os comandos SnapMirror DELETE e SnapMirror release para excluir uma relação de replicação SVM. Em seguida, pode eliminar manualmente volumes de destino desnecessários. 
---
= Exclua uma relação de replicação do ONTAP SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar os `snapmirror delete` comandos e `snapmirror release` para excluir uma relação de replicação SVM. Em seguida, pode eliminar manualmente volumes de destino desnecessários.

.Sobre esta tarefa
O `snapmirror release` comando exclui todos os snapshots criados pelo SnapMirror da origem. Você pode usar a `-relationship-info-only` opção para preservar os snapshots.

Saiba mais sobre `snapmirror release` o link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-release.html["Referência do comando ONTAP"^]na .

.Passos
. Execute o seguinte comando a partir do SVM de destino ou do cluster de destino para quebrar a relação de replicação:
+
`snapmirror break -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
Você deve inserir dois pontos (:) após o nome SVM `-source-path` nas opções e `-destination-path` . Veja o exemplo abaixo.

====
+
O exemplo a seguir rompe a relação entre o SVM de origem `svm1` e o SVM de destino `svm_backup` :

+
[listing]
----
cluster_dst::> snapmirror break -source-path svm1: -destination-path svm_backup:
----
. Execute o seguinte comando do SVM de destino ou do cluster de destino para excluir a relação de replicação:
+
`snapmirror delete -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
Você deve inserir dois pontos (:) após o nome SVM `-source-path` nas opções e `-destination-path` . Veja o exemplo abaixo.

====
+
O exemplo a seguir exclui a relação entre o SVM de origem `svm1` e o SVM de destino `svm_backup` :

+
[listing]
----
cluster_dst::> snapmirror delete -source-path svm1: -destination-path svm_backup:
----
. Execute o seguinte comando a partir do cluster de origem ou SVM de origem para liberar as informações de relação de replicação da SVM de origem:
+
`snapmirror release -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
Você deve inserir dois pontos (:) após o nome SVM `-source-path` nas opções e `-destination-path` . Veja o exemplo abaixo.

====
+
O exemplo a seguir libera informações para a relação de replicação especificada da SVM de origem `svm1` :

+
[listing]
----
cluster_src::> snapmirror release -source-path svm1: -destination-path svm_backup:
----

