---
permalink: data-protection/destination-volume-grows-automatically-concept.html 
sidebar: sidebar 
keywords: destination, volume, grow, automatic 
summary: Durante uma transferência espelhada de proteção de dados, o volume de destino aumenta automaticamente em tamanho se o volume de origem tiver crescido, desde que haja espaço disponível no agregado que contenha o volume. 
---
= Quando um volume de destino de proteção de dados da ONTAP aumenta automaticamente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durante uma transferência espelhada de proteção de dados, o volume de destino aumenta automaticamente em tamanho se o volume de origem tiver crescido, desde que haja espaço disponível no agregado que contenha o volume.

Este comportamento ocorre independentemente de qualquer definição de crescimento automático no destino. Você não pode limitar o crescimento do volume ou impedir que o ONTAP o aumente.

Por padrão, os volumes de proteção de dados são definidos para o `grow_shrink` modo automático, o que permite que o volume cresça ou diminua em resposta à quantidade de espaço usado. O dimensionamento automático máximo para volumes de proteção de dados é igual ao tamanho máximo de FlexVol e depende da plataforma. Por exemplo:

* FAS8200, volume DP padrão máximo-dimensionamento automático: 100TB


Para obter mais informações, https://hwu.netapp.com/["NetApp Hardware Universe"^]consulte .
