---
permalink: data-protection/dpo-systems-feature-enhancements-reference.html 
sidebar: sidebar 
keywords: dpo, systems, feature, enhancements, snapmirror, dp optimized, optimised, backoff, back off, deduplication, deduplicate, snapshot blocks, donors, compact, flexvol, license 
summary: 'A partir do ONTAP 9.6, o número máximo de volumes FlexVol suportados aumenta quando a licença DP_Optimized (DPO) é instalada. A partir do ONTAP 9.4, os sistemas com licença de DPO dão suporte a SnapMirror backoff, deduplicação em segundo plano entre volumes, uso de blocos Snapshot como doadores e compactação.' 
---
= Os sistemas DPO apresentam melhorias
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.6, o número máximo de volumes FlexVol suportados aumenta quando a licença DP_Optimized (DPO) é instalada. A partir do ONTAP 9.4, os sistemas com licença de DPO dão suporte a SnapMirror backoff, deduplicação em segundo plano entre volumes, uso de blocos Snapshot como doadores e compactação.

A partir do ONTAP 9.6, o número máximo de volumes FlexVol com suporte em sistemas secundários ou de proteção de dados aumentou, permitindo que você escale até 2.500 volumes FlexVol por nó ou até 5.000 TB no modo failover. O aumento dos volumes FlexVol é ativado com o link:https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-licensing-concept.html#data-protection-optimized-license["Licença DP_Optimized (DPO)"]. Ainda é necessário um link:https://docs.netapp.com/us-en/ontap/system-admin/manage-license-task.html#view-details-about-a-license["Licença SnapMirror"]nos nós de origem e de destino.

A partir do ONTAP 9.4, os seguintes aprimoramentos de recursos são feitos nos sistemas DPO:

* SnapMirror backoff: Nos sistemas DPO, o tráfego de replicação tem a mesma prioridade que as cargas de trabalho do cliente são dadas.
+
O backoff do SnapMirror é desativado por padrão nos sistemas DPO.

* Deduplicação em segundo plano do volume e deduplicação em segundo plano entre volumes: A deduplicação em segundo plano do volume e a deduplicação em segundo plano entre volumes são ativadas em sistemas DPO.
+
Você pode executar `storage aggregate efficiency cross-volume-dedupe start -aggregate _aggregate_name_ -scan-old-data true` o comando para deduplicar os dados existentes. A prática recomendada é executar o comando durante horas fora do pico para reduzir o impactos no desempenho.

* Maior economia ao usar blocos Snapshot como doadores: Os blocos de dados que não estão disponíveis no sistema de arquivos ativo, mas estão presos em cópias Snapshot são usados como doadores para deduplicação de volume.
+
Os novos dados podem ser deduplicados com os dados retidos nas cópias Snapshot. Eles também compartilham os blocos Snapshot com eficiência. O maior espaço de doadores oferece mais economia, especialmente quando o volume tem um grande número de cópias Snapshot.

* Compactação: A compactação de dados está ativada por padrão nos volumes DPO.

