---
permalink: data-protection/example-configure-vault-vault-cascade-task.html 
sidebar: sidebar 
keywords: example, configure, vault-vault, cascade 
summary: 'Um exemplo mostrará em termos concretos como você pode configurar relacionamentos de replicação uma etapa de cada vez. Você pode usar a implantação em cascata do Vault-Vault configurada no exemplo para reter mais de 251 snapshots rotulados "por semana".' 
---
= Exemplo: Configurar uma cascata de Vault-Vault do ONTAP SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um exemplo mostrará em termos concretos como você pode configurar relacionamentos de replicação uma etapa de cada vez. Você pode usar a implantação em cascata do Vault-Vault configurada no exemplo para reter mais de 251 snapshots rotulados `my-weekly`.

.Antes de começar
Os clusters de origem e destino e as SVMs devem ser colocados em Contato.

.Sobre esta tarefa
O exemplo assume o seguinte:

* Você configurou snapshots no cluster de origem com os rótulos SnapMirror `my-daily` , `my-weekly` e `my-monthly`.
* Você configurou volumes de destino com o nome `volA` nos clusters de destino secundário e terciário.
* Você configurou as programações de tarefas de replicação nomeadas `my_snapvault` nos clusters de destino secundário e terciário.


O exemplo mostra como criar relacionamentos de replicação com base em duas políticas personalizadas:

*  `snapvault_secondary`A política retém 7 snapshots diários, 52 semanais e 180 mensais no cluster de destino secundário.
* O `snapvault_tertiary policy` retém 250 instantâneos semanais no cluster de destino terciário.


.Passos
. No cluster de destino secundário, crie a `snapvault_secondary` política:
+
`cluster_secondary::> snapmirror policy create -policy snapvault_secondary -type vault -comment "Policy on secondary for vault to vault cascade" -vserver svm_secondary`

. No cluster de destino secundário, defina a `my-daily` regra para a política:
+
`cluster_secondary::> snapmirror policy add-rule -policy snapvault_secondary -snapmirror-label my-daily -keep 7 -vserver svm_secondary`

. No cluster de destino secundário, defina a `my-weekly` regra para a política:
+
`cluster_secondary::> snapmirror policy add-rule -policy snapvault_secondary -snapmirror-label my-weekly -keep 52 -vserver svm_secondary`

. No cluster de destino secundário, defina a `my-monthly` regra para a política:
+
`cluster_secondary::> snapmirror policy add-rule -policy snapvault_secondary -snapmirror-label my-monthly -keep 180 -vserver svm_secondary`

. No cluster de destino secundário, verifique a política:
+
`cluster_secondary::> snapmirror policy show snapvault_secondary -instance`

+
[listing]
----
                     Vserver: svm_secondary
      SnapMirror Policy Name: snapvault_secondary
      SnapMirror Policy Type: vault
                Policy Owner: cluster-admin
                 Tries Limit: 8
           Transfer Priority: normal
   Ignore accesstime Enabled: false
     Transfer Restartability: always
 Network Compression Enabled: false
             Create Snapshot: false
                     Comment: Policy on secondary for vault to vault cascade
       Total Number of Rules: 3
                  Total Keep: 239
                       Rules: SnapMirror Label     Keep  Preserve Warn Schedule Prefix
                              ----------------     ----  -------- ---- -------- ------
                              my-daily                7  false       0 -        -
                              my-weekly              52  false       0 -        -
                              my-monthly            180  false       0 -        -
----
. No cluster de destino secundário, crie a relação com o cluster de origem:
+
`cluster_secondary::> snapmirror create -source-path svm_primary:volA -destination-path svm_secondary:volA -type XDP -schedule my_snapvault -policy snapvault_secondary`

. No cluster de destino secundário, inicialize a relação com o cluster de origem:
+
`cluster_secondary::> snapmirror initialize -source-path svm_primary:volA -destination-path svm_secondary:volA`

. No cluster de destino terciário, crie a `snapvault_tertiary` política:
+
`cluster_tertiary::> snapmirror policy create -policy snapvault_tertiary -type vault -comment "Policy on tertiary for vault to vault cascade" -vserver svm_tertiary`

. No cluster de destino terciário, defina a `my-weekly` regra para a política:
+
`cluster_tertiary::> snapmirror policy add-rule -policy snapvault_tertiary -snapmirror-label my-weekly -keep 250 -vserver svm_tertiary`

. No cluster de destino terciário, verifique a política:
+
`cluster_tertiary::> snapmirror policy show snapvault_tertiary -instance`

+
[listing]
----
                     Vserver: svm_tertiary
      SnapMirror Policy Name: snapvault_tertiary
      SnapMirror Policy Type: vault
                Policy Owner: cluster-admin
                 Tries Limit: 8
           Transfer Priority: normal
   Ignore accesstime Enabled: false
     Transfer Restartability: always
 Network Compression Enabled: false
             Create Snapshot: false
                     Comment: Policy on tertiary for vault to vault cascade
       Total Number of Rules: 1
                  Total Keep: 250
                       Rules: SnapMirror Label     Keep  Preserve Warn Schedule Prefix
                              ----------------     ----  -------- ---- -------- ------
                              my-weekly             250  false       0 -        -
----
. No cluster de destino terciário, crie a relação com o cluster secundário:
+
`cluster_tertiary::> snapmirror create -source-path svm_secondary:volA -destination-path svm_tertiary:volA -type XDP -schedule my_snapvault -policy snapvault_tertiary`

. No cluster de destino terciário, inicialize a relação com o cluster secundário:
+
`cluster_tertiary::> snapmirror initialize -source-path svm_secondary:volA -destination-path svm_tertiary:volA`



.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["SnapMirror create"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html["inicialização do snapmirror"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-add-rule.html["política de adição de regra do snapmirror"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-create.html["criação de política do snapmirror"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-show.html["política do snapmirror mostrar"^]

