---
permalink: data-protection/example-snapshot-copies-exceed-reserve-concept.html 
sidebar: sidebar 
keywords: delete, protected, files, less file space 
summary: Um instantâneo aponta para um bloco mesmo depois que você exclui o arquivo que usou o bloco. Isso explica por que uma reserva de snapshot esgotada pode levar ao resultado contra-intuitivo no qual a exclusão de um sistema de arquivos inteiro resulta em menos espaço disponível do que o sistema de arquivos ocupado. 
---
= Como excluir arquivos protegidos pode levar a menos espaço do arquivo do que o esperado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um instantâneo aponta para um bloco mesmo depois que você exclui o arquivo que usou o bloco. Isso explica por que uma reserva de snapshot esgotada pode levar ao resultado contra-intuitivo no qual a exclusão de um sistema de arquivos inteiro resulta em menos espaço disponível do que o sistema de arquivos ocupado.

Considere o exemplo a seguir. Antes de excluir quaisquer arquivos, a `df` saída do comando é a seguinte:

[listing]
----

Filesystem          kbytes  used    avail  capacity
/vol/vol0/          3000000 3000000 0       100%
/vol/vol0/.snapshot 1000000 500000  500000   50%
----
Depois de excluir todo o sistema de arquivos e fazer um instantâneo do volume, o `df` comando gera a seguinte saída:

[listing]
----

Filesystem          kbytes  used    avail  capacity
/vol/vol0/          3000000 2500000 500000   83%
/vol/vol0/.snapshot 1000000 3500000 0       350%
----
Como mostra a saída, os 3 GB usados anteriormente pelo sistema de arquivos ativo agora estão sendo usados por snapshots, além dos 0,5 GB usados antes da exclusão.

Como o espaço em disco usado pelos snapshots agora excede a reserva de snapshot, o excesso de 2,5 GB "pílulas" para o espaço reservado para arquivos ativos, deixando você com 0,5 GB de espaço livre para arquivos onde você pode razoavelmente ter esperado 3 GB.

Saiba mais sobre os comandos descritos neste procedimento no link:https://docs.netapp.com/us-en/ontap-cli/["Referência do comando ONTAP"^].
