---
permalink: data-protection/extended-queries-many-snapmirror-relationships-task.html 
sidebar: sidebar 
keywords: extend, query, act, snapmirror, relationships 
summary: Você pode usar consultas estendidas para executar operações do SnapMirror em muitos relacionamentos do SnapMirror ao mesmo tempo. Por exemplo, você pode ter várias relações SnapMirror não inicializadas que deseja inicializar usando um comando. 
---
= Use consultas estendidas para agir em muitos relacionamentos do SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar _consultas estendidas_ para executar operações do SnapMirror em muitos relacionamentos do SnapMirror ao mesmo tempo. Por exemplo, você pode ter várias relações SnapMirror não inicializadas que deseja inicializar usando um comando.

.Sobre esta tarefa
Você pode aplicar consultas estendidas às seguintes operações do SnapMirror:

* Inicializando relacionamentos não inicializados
* Retomando relacionamentos quiesced
* Ressincronizar relacionamentos quebrados
* Atualizando relacionamentos ociosos
* A abortar transferências de dados de relacionamento


.Passo
. Execute uma operação SnapMirror em muitos relacionamentos:
+
`_snapmirror command_ {-state state } *`

+
O comando a seguir inicializa as relações SnapMirror que estão em um `Uninitialized` estado:

+
[listing]
----
vs1::> snapmirror initialize {-state Uninitialized} *
----

