---
permalink: data-protection/initialize-replication-relationship-task.html 
sidebar: sidebar 
keywords: initialize, replication, relationship, snapmirror, snap mirror, synchronous, transfer, snapshot copy, 
summary: 'Para todos os tipos de relacionamento, a inicialização executa uma transferência de linha de base: Ele faz um instantâneo do volume de origem e transfere essa cópia e todos os blocos de dados que ela faz referência ao volume de destino. Caso contrário, o conteúdo da transferência depende da política.' 
---
= Inicialize uma relação de replicação com o ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para todos os tipos de relacionamento, a inicialização executa uma _Baseline transfer_: Ele faz um snapshot do volume de origem, depois transfere essa cópia e todos os dados bloqueiam que ela faz referência ao volume de destino. Caso contrário, o conteúdo da transferência depende da política.

.O que você vai precisar
Os clusters de origem e destino e as SVMs devem ser colocados em Contato.

link:../peering/index.html["Peering de cluster e SVM"]

.Sobre esta tarefa
A inicialização pode ser demorada. Você pode querer executar a transferência de linha de base em horas fora do pico.

A partir do ONTAP 9.5, as relações síncronas do SnapMirror são suportadas.

.Passo
. Inicializar uma relação de replicação:
+
`snapmirror initialize -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ...`

+
Saiba mais sobre `snapmirror initialize` o link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html["Referência do comando ONTAP"^]na .

+
[NOTE]
====
Você deve executar esse comando a partir do SVM de destino ou do cluster de destino.

====
+
O exemplo a seguir inicializa a relação entre o volume de origem `volA` ligado `svm1` e o volume de destino `volA_dst` no `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror initialize -source-path svm1:volA -destination-path svm_backup:volA_dst
----

