---
permalink: data-protection/limitations-mirror-relationships-concept.html 
sidebar: sidebar 
keywords: snapmirror, limitations 
summary: Você deve estar ciente das limitações básicas do SnapMirror antes de criar um relacionamento de proteção de dados. 
---
= Limitações do SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve estar ciente das limitações básicas do SnapMirror antes de criar um relacionamento de proteção de dados.

* Um volume de destino pode ter apenas um volume de origem.
+

NOTE: Um volume de origem pode ter vários volumes de destino. O volume de destino pode ser o volume de origem para qualquer tipo de relação de replicação do SnapMirror.

* Dependendo do modelo do array, você pode distribuir um máximo de oito ou dezesseis volumes de destino a partir de um único volume de origem. Consulte link:https://hwu.netapp.com/["Hardware Universe"^]para obter detalhes sobre sua configuração específica.
* Não é possível restaurar arquivos para o destino de uma relação de DR do SnapMirror.
* Os volumes SnapVault de origem ou destino não podem ser de 32 bits.
* O volume de origem de uma relação SnapVault não deve ser um volume FlexClone.
+

NOTE: A relação funcionará, mas a eficiência oferecida pelos volumes FlexClone não será preservada.


