---
permalink: data-protection/long-term-retention-snapshots-concept.html 
sidebar: sidebar 
keywords: local, snapshot, retention, snapmirror, vault 
summary: Você pode criar snapshots de retenção de longo prazo diretamente no volume secundário de um relacionamento SnapMirror usando o tipo de política vault ou mirror-vault.  Esses instantâneos são mantidos no destino como backups. 
---
= Saiba mais sobre os snapshots de retenção de longo prazo do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os relacionamentos SnapMirror com um tipo de política "vault" ou "mirror-vault" permitem a criação de snapshots diretamente no volume secundário do relacionamento SnapMirror . Esses instantâneos são mantidos no destino como backups. Esses instantâneos geralmente são criados para retenção de longo prazo e são chamados de instantâneos de retenção de longo prazo (LTR).

Crie um snapshot de retenção de longo prazo especificando um cronograma de criação de snapshot na regra de política do SnapMirror , o prefixo do nome do snapshot, o rótulo do SnapMirror e a contagem de retenção.  Este instantâneo é retido no volume de destino do SnapMirror , independentemente das regras de retenção na origem.

Os snapshots de retenção de longo prazo estão disponíveis somente para configurações do FlexVol SnapMirror .  Não é possível criar snapshots LTR para configurações do FlexGroup SnapMirror .

Em um relacionamento em cascata do SnapMirror , snapshots de retenção de longo prazo só podem ser criados no último volume da cascata.



== Informações relacionadas

* link:supported-deployment-config-concept.html#how-cascade-deployments-work["Saiba como funcionam as implantações em cascata"]
* link:define-schedule-create-local-copy-destination-task.html["Defina uma agenda ONTAP SnapMirror para criar uma cópia local no destino"]

