---
permalink: data-protection/manage-local-snapshot-copies-concept.html 
sidebar: sidebar 
keywords: manage, local, snapshot, copy, storage, performance overhead, copies, image, restore, flexvol, flexgroup 
summary: Uma cópia Snapshot é uma imagem pontual e somente leitura de um volume. A imagem consome espaço de armazenamento mínimo e incorre em sobrecarga de desempenho insignificante, pois Registra apenas alterações nos arquivos desde a última cópia Snapshot. 
---
= Visão geral do gerenciamento de cópias Snapshot locais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Uma _cópia Snapshot_ é uma imagem pontual e somente leitura de um volume. A imagem consome espaço de armazenamento mínimo e incorre em sobrecarga de desempenho insignificante, pois Registra apenas alterações nos arquivos desde a última cópia Snapshot.

Você pode usar uma cópia Snapshot para restaurar todo o conteúdo de um volume ou para recuperar arquivos individuais ou LUNs. As cópias snapshot são armazenadas no diretório `.snapshot` do volume.

No ONTAP 9.3 e versões anteriores, um volume pode conter até 255 cópias Snapshot. No ONTAP 9.4 e posterior, um FlexVol volume pode conter até 1023 cópias snapshot.

[NOTE]
====
A partir do ONTAP 9.8, os volumes FlexGroup podem conter 1023 cópias Snapshot. Para obter mais informações, link:../flexgroup/protect-snapshot-copies-task.html["Proteja volumes FlexGroup com cópias Snapshot"]consulte .

====