---
permalink: data-protection/manage-storage-efficiency-task.html 
sidebar: sidebar 
keywords: snapmirror, efficiency, manage, storage, snap mirror, compression, compress, postprocess, post-process, update relationship, volume 
summary: Para preservar a eficiência de storage entre os volumes de origem e destino com o SnapMirror, é necessário desativar a compactação do pós-processo no volume de destino 
---
= Gerencie a eficiência de storage com o ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O SnapMirror preserva a eficiência de storage nos volumes de origem e destino, exceto quando a compactação de dados pós-processamento está ativada no volume de destino. Nesse caso, toda a eficiência de storage é perdida no volume de destino. Para corrigir esse problema, você precisa desativar a compactação pós-processo no volume de destino, atualizar a relação manualmente e reativar a eficiência de storage.

.Sobre esta tarefa
Você pode usar o `volume efficiency show` comando para determinar se a eficiência está ativada em um volume. Saiba mais sobre `volume efficiency show` o link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-show.html["Referência do comando ONTAP"^]na .

Você pode verificar se o SnapMirror está mantendo a eficiência de storage visualizando os logs de auditoria do SnapMirror e localizando a descrição da transferência. Se a descrição da transferência for exibida `transfer_desc=Logical Transfer with Storage Efficiency`, o SnapMirror manterá a eficiência do storage. Se a descrição da transferência for exibida `transfer_desc=Logical Transfer`, o SnapMirror não manterá a eficiência do storage. Por exemplo:

[listing]
----
Fri May 22 02:13:02 CDT 2020 ScheduledUpdate[May 22 02:12:00]:cc0fbc29-b665-11e5-a626-00a09860c273 Operation-Uuid=39fbcf48-550a-4282-a906-df35632c73a1 Group=none Operation-Cookie=0 action=End source=<sourcepath> destination=<destpath> status=Success bytes_transferred=117080571 network_compression_ratio=1.0:1 transfer_desc=Logical Transfer - Optimized Directory Mode
----
.Antes de começar
* Os clusters de origem e destino e as SVMs devem ser colocados em Contato.
+
https://docs.netapp.com/us-en/ontap-system-manager-classic/peering/index.html["Peering de cluster e SVM"^]

* Você deve desativar a compressão pós-processo no volume de destino.
* Transferência lógica com armazenamento: A partir do ONTAP 9.3, a atualização manual não é mais necessária para reativar a eficiência de storage. Se o SnapMirror detetar que a compactação pós-processo foi desativada, ele reativará automaticamente a eficiência de storage na próxima atualização agendada. Tanto a origem quanto o destino devem estar executando o ONTAP 9.3.
* A partir do ONTAP 9.3, os sistemas AFF gerenciam as configurações de eficiência de storage de maneira diferente dos sistemas FAS depois que um volume de destino é gravado:
+
** Depois de fazer um volume de destino gravável usando o `snapmirror break` comando, a política de cache no volume é automaticamente definida como "'auto'" (o padrão).
+
[NOTE]
====
Esse comportamento é aplicável apenas a volumes do FlexVol e não se aplica a volumes do FlexGroup.

====
** Na ressincronização, a política de armazenamento em cache é automaticamente definida como "nenhum", e a deduplicação e a compactação in-line são desativadas automaticamente, independentemente das configurações originais. Você deve modificar as configurações manualmente, conforme necessário.




[NOTE]
====
Atualizações manuais com eficiência de storage habilitada podem ser demoradas. Você pode querer executar a operação em horas fora do pico.

====
.Passos
. Atualizar uma relação de replicação e reativar a eficiência de storage:
+
[source, cli]
----
snapmirror update -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ... -enable-storage-efficiency true
----
+
Saiba mais sobre `snapmirror update` o link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-update.html["Referência do comando ONTAP"^]na .

+
[NOTE]
====
Você deve executar esse comando a partir do SVM de destino ou do cluster de destino. O comando falha se um snapshot comum não existir na origem e no destino.  `snapmirror initialize`Use para reinicializar o relacionamento.

====
+
O exemplo a seguir atualiza a relação entre o volume de origem `volA` ligado `svm1` e o volume de destino ligado `svm_backup` e `volA_dst` rehabilita a eficiência de storage:

+
[listing]
----
cluster_dst::> snapmirror update -source-path svm1:volA -destination-path svm_backup:volA_dst -enable-storage-efficiency true
----

