---
permalink: data-protection/reactivate-original-source-svm-flexgroup-task.html 
sidebar: sidebar 
keywords: reactivate, original, source, svm, flexgroup 
summary: É possível restabelecer a relação de proteção de dados original entre a fonte e o SVM de destino, quando não precisar mais fornecer dados do destino. Para reativar o SVM de origem original quando você estiver usando o FlexGroup volumes, você precisa executar algumas etapas adicionais, incluindo excluir a relação original do SVM DR e liberar a relação original antes de reverter a relação. Você também precisa liberar o relacionamento invertido e recriar o relacionamento original antes de parar as transferências agendadas. 
---
= Reative o SVM original de fonte do ONTAP SnapMirror para volumes do FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível restabelecer a relação de proteção de dados original entre a fonte e o SVM de destino, quando não precisar mais fornecer dados do destino. Para reativar o SVM de origem original quando você estiver usando o FlexGroup volumes, você precisa executar algumas etapas adicionais, incluindo excluir a relação original do SVM DR e liberar a relação original antes de reverter a relação. Você também precisa liberar o relacionamento invertido e recriar o relacionamento original antes de parar as transferências agendadas.

.Passos
. No SVM de destino original ou no cluster de destino original, exclua a relação de DR original do SVM:
+
`snapmirror delete -source-path SVM: -destination-path SVM:`

+
[NOTE]
====
Você deve inserir dois pontos (:) após o nome SVM `-source-path` nas opções e `-destination-path` . Veja o exemplo abaixo.

====
+
O exemplo a seguir exclui a relação original entre a fonte original SVM, svm1 e o SVM de destino original `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror delete -source-path svm1: -destination-path svm_backup:
----
. No SVM de origem original ou no cluster de origem original, solte a relação original e mantenha os snapshots intactos:
+
`snapmirror release -source-path SVM: -destination-path SVM: -relationship-info-only true`

+
[NOTE]
====
Você deve inserir dois pontos (:) após o nome SVM `-source-path` nas opções e `-destination-path` . Veja o exemplo abaixo.

====
+
O exemplo a seguir libera a relação original entre a fonte original SVM, svm1 e o SVM de destino original, `svm_backup`.

+
[listing]
----
cluster_src::> snapmirror release -source-path svm1: -destination-path svm_backup: -relationship-info-only true
----
. A partir do SVM de origem original ou do cluster de origem original, crie uma relação SVM DR reversa usando a mesma configuração, política e configuração de preservação de identidade que a relação SVM DR original:
+
`snapmirror create -source-path SVM: -destination-path SVM:`

+
[NOTE]
====
Você deve inserir dois pontos (:) após o nome SVM `-source-path` nas opções e `-destination-path` . Veja o exemplo abaixo.

====
+
O exemplo a seguir cria uma relação entre o SVM a partir do qual você está fornecendo dados e `svm_backup` o SVM de origem original `svm1`:

+
[listing]
----
cluster_src::> snapmirror create -source-path svm_backup: -destination-path svm1:
----
. No SVM de origem original ou no cluster de origem original, execute o seguinte comando para reverter a relação de proteção de dados:
+
`snapmirror resync -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
Você deve inserir dois pontos (:) após o nome SVM `-source-path` nas opções e `-destination-path` . Veja o exemplo abaixo.

====
+
Embora a ressincronização não exija uma transferência de linha de base, ela pode ser demorada. Você pode querer executar a ressincronização em horas fora do pico.

+
[NOTE]
====
O comando falha se um snapshot comum não existir na origem e no destino. Use `snapmirror initialize` para reinicializar o relacionamento.

====
+
O exemplo a seguir inverte a relação entre o SVM de origem original e `svm1` o SVM a partir do qual você está fornecendo dados, `svm_backup`:

+
[listing]
----
cluster_src::> snapmirror resync -source-path svm_backup: -destination-path svm1:
----
. Quando você quiser restabelecer o acesso aos dados à fonte original SVM, pare o SVM de destino original para desconetar todos os clientes conectados ao SVM de destino original.
+
`vserver stop -vserver _SVM_`

+
O exemplo a seguir interrompe o SVM de destino original que está fornecendo dados no momento:

+
[listing]
----
cluster_dst::> vserver stop svm_backup
----
. Verifique se o SVM de destino original está no estado parado usando o `vserver show` comando.
+
[listing]
----
cluster_dst::> vserver show
                                  Admin      Operational Root
Vserver        Type    Subtype    State      State       Volume     Aggregate
--------       ------- ---------- ---------- ----------- ---------- ----------
svm_backup     data    default    stopped    stopped     rv         aggr1
----
. No SVM de origem original ou no cluster de origem original, execute o seguinte comando para executar a atualização final da relação invertida para transferir todas as alterações do SVM de destino original para o SVM de origem original:
+
`snapmirror update -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
Você deve inserir dois pontos (:) após o nome SVM `-source-path` nas opções e `-destination-path` . Veja o exemplo abaixo.

====
+
O exemplo a seguir atualiza a relação entre o SVM de destino original a partir do qual você está fornecendo dados,`svm_backup`e o SVM de origem original `svm1`:

+
[listing]
----
cluster_src::> snapmirror update -source-path svm_backup: -destination-path svm1:
----
. No SVM de origem original ou no cluster de origem original, execute o seguinte comando para interromper as transferências agendadas para o relacionamento invertido:
+
`snapmirror quiesce -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
Você deve inserir dois pontos (:) após o nome SVM `-source-path` nas opções e `-destination-path` . Veja o exemplo abaixo.

====
+
O exemplo a seguir interrompe as transferências agendadas entre o SVM que você está fornecendo dados, `svm_backup` e o SVM original `svm1`:

+
[listing]
----
cluster_src::> snapmirror quiesce -source-path svm_backup: -destination-path svm1:
----
. Quando a atualização final estiver concluída e o relacionamento indicar "Quiesced" para o status do relacionamento, execute o seguinte comando da fonte original SVM ou do cluster de origem original para quebrar o relacionamento invertido:
+
`snapmirror break -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
Você deve inserir dois pontos (:) após o nome SVM `-source-path` nas opções e `-destination-path` . Veja o exemplo abaixo.

====
+
O exemplo a seguir rompe a relação entre o SVM de destino original do qual você estava fornecendo dados e `svm_backup` o SVM de origem original `svm1`:

+
[listing]
----
cluster_src::> snapmirror break -source-path svm_backup: -destination-path svm1:
----
+
Saiba mais sobre `snapmirror break` o link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-break.html["Referência do comando ONTAP"^]na .

. Se o SVM de origem original tiver sido interrompido anteriormente, a partir do cluster de origem original, inicie o SVM de origem original:
+
`vserver start -vserver _SVM_`

+
O exemplo a seguir inicia a fonte original SVM:

+
[listing]
----
cluster_src::> vserver start svm1
----
. No SVM de origem original ou no cluster de origem original, exclua a relação SVM DR invertida:
+
`snapmirror delete -source-path SVM: -destination-path SVM:`

+
[NOTE]
====
Você deve inserir dois pontos (:) após o nome SVM `-source-path` nas opções e `-destination-path` . Veja o exemplo abaixo.

====
+
O exemplo a seguir exclui a relação inversa entre o SVM de destino original, SVM_backup e a fonte original SVM `svm1`:

+
[listing]
----
cluster_src::> snapmirror delete -source-path svm_backup: -destination-path svm1:
----
. No SVM de destino original ou no cluster de destino original, libere a relação inversa enquanto mantém os snapshots intactos:
+
`snapmirror release -source-path SVM: -destination-path SVM: -relationship-info-only true`

+
[NOTE]
====
Você deve inserir dois pontos (:) após o nome SVM `-source-path` nas opções e `-destination-path` . Veja o exemplo abaixo.

====
+
O exemplo a seguir libera a relação inversa entre o SVM de destino original, SVM_backup e a fonte original SVM, svm1:

+
[listing]
----
cluster_dst::> snapmirror release -source-path svm_backup: -destination-path svm1: -relationship-info-only true
----
. A partir do SVM de destino original ou do cluster de destino original, recrie a relação original. Use a mesma configuração, política e configuração de preservação de identidade que a relação original do SVM DR:
+
`snapmirror create -source-path SVM: -destination-path SVM:`

+
[NOTE]
====
Você deve inserir dois pontos (:) após o nome SVM `-source-path` nas opções e `-destination-path` . Veja o exemplo abaixo.

====
+
O exemplo a seguir cria uma relação entre a fonte original SVM e `svm1` o SVM de destino original `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup:
----
. A partir do SVM de destino original ou do cluster de destino original, restabeleça a relação de proteção de dados original:
+
`snapmirror resync -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
Você deve inserir dois pontos (:) após o nome SVM `-source-path` nas opções e `-destination-path` . Veja o exemplo abaixo.

====
+
O exemplo a seguir restabelece a relação entre a fonte original SVM e `svm1` o SVM de destino original `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm1: -destination-path svm_backup:
----


.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["SnapMirror create"^]

