---
permalink: data-protection/replicate-entire-svm-config-task.html 
sidebar: sidebar 
keywords: replicate, entire, svm, storage vm, disaster, protection, configuration, snapmirror, snap mirror, replication, mirror vault policy, snapshot 
summary: 'Você pode criar uma relação de recuperação de desastre do SVM (SVM DR) para replicar uma configuração do SVM para outra. Em caso de desastre no local principal, você pode ativar rapidamente o SVM de destino.' 
---
= Replique toda uma configuração do ONTAP SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode criar uma relação de recuperação de desastre do SVM (SVM DR) para replicar uma configuração do SVM para outra. Em caso de desastre no local principal, você pode ativar rapidamente o SVM de destino.

.Antes de começar
Os clusters de origem e destino e as SVMs devem ser colocados em Contato. Para obter mais informações, link:../peering/create-cluster-relationship-93-later-task.html["Crie um relacionamento de pares de cluster"]consulte e link:../peering/create-intercluster-svm-peer-relationship-93-later-task.html["Criar um relacionamento entre clusters entre pares"].

Para obter a sintaxe completa do comando, consulte a página man.

.Sobre esta tarefa
Este fluxo de trabalho pressupõe que você já está usando uma política padrão ou uma política de replicação personalizada.

A partir do ONTAP 9.9,1, quando você usa a política de espelhamento de arquivos, pode criar diferentes políticas de Snapshot na SVM de origem e destino. Além disso, as cópias Snapshot no destino não serão sobrescritas por cópias Snapshot na origem. Para obter mais informações, link:snapmirror-svm-replication-concept.html["Compreensão da replicação do SnapMirror SVM"]consulte .

Conclua este procedimento a partir do destino. Se você precisar criar uma nova política de proteção, por exemplo, quando a VM de armazenamento de origem tiver o SMB configurado, crie a política e use a opção *Identity Preserve*. Para obter detalhes, link:create-custom-replication-policy-concept.html["Crie políticas de proteção de dados personalizadas"]consulte .

.Passos
Você pode executar esta tarefa a partir do Gerenciador do sistema ou da CLI do ONTAP.

[role="tabbed-block"]
====
.System Manager
--
. No cluster de destino, clique em *proteção > relacionamentos*.
. Em *relacionamentos*, clique em *proteger* e escolha *Storage VMs (DR)*.
. Selecione uma política de proteção. Se você criou uma política de proteção personalizada, selecione-a e escolha o cluster de origem e a VM de storage que deseja replicar. Você também pode criar uma nova VM de armazenamento de destino inserindo um novo nome de VM de armazenamento.
. Se desejado, altere as configurações de destino para substituir a preservação de identidade e incluir ou excluir interfaces e protocolos de rede.
. Clique em *Salvar*.


--
.CLI
--
. Criar um SVM de destino:
+
[source, cli]
----
vserver create -vserver <SVM_name> -subtype dp-destination
----
+
O nome do SVM deve ser exclusivo nos clusters de origem e destino.

+
O exemplo a seguir cria um SVM de destino chamado `svm_backup`:

+
[listing]
----
cluster_dst:> vserver create -vserver svm_backup -subtype dp-destination
----
. No cluster de destino, crie um relacionamento de pares SVM usando o `vserver peer create` comando.
+
Para obter mais informações, link:../peering/create-intercluster-svm-peer-relationship-93-later-task.html["Criar um relacionamento entre clusters entre pares"]consulte .

. Criar um agendamento de trabalho de replicação:
+
[source, cli]
----
job schedule cron create -name <job_name> -month <month> -dayofweek <day_of_week> -day <day_of_month> -hour <hour> -minute <minute>
----
+
Para `-month`, , `-dayofweek`, e `-hour`, é possível especificar `all` para executar o trabalho todos os meses, dia da semana e hora, respetivamente.

+

NOTE: O cronograma mínimo com suporte (RPO) para volumes do FlexVol em uma relação do SVM SnapMirror é de 15 minutos. O cronograma mínimo com suporte (RPO) para volumes do FlexGroup em uma relação do SVM SnapMirror é de 30 minutos.

+
O exemplo a seguir cria um horário de trabalho chamado `my_weekly` que é executado aos sábados às 3:00 da manhã:

+
[listing]
----
cluster_dst::> job schedule cron create -name my_weekly -dayofweek saturday -hour 3 -minute 0
----
. No SVM de destino ou no cluster de destino, crie uma relação de replicação:
+
[source, cli]
----
snapmirror create -source-path <SVM_name>: -destination-path <SVM_name>: -type <DP|XDP> -schedule <schedule> -policy <policy> -identity-preserve true
----
+

NOTE: Você deve inserir dois pontos (:) após o nome SVM `-source-path` nas opções e `-destination-path` .

+
O exemplo a seguir cria uma relação de DR do SnapMirror usando a política padrão `MirrorAllSnapshots`:

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy MirrorAllSnapshots -identity-preserve true
----
+
O exemplo a seguir cria uma relação de replicação unificada usando a política padrão `MirrorAndVault`:

+
[listing]
----
cluster_dst:> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy MirrorAndVault -identity-preserve true
----
+
Supondo que você tenha criado uma política personalizada com o tipo de diretiva `async-mirror` , o exemplo a seguir cria uma relação de DR do SnapMirror:

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy my_mirrored -identity-preserve true
----
+
Supondo que você tenha criado uma política personalizada com o tipo de diretiva `mirror-vault` , o exemplo a seguir cria uma relação de replicação unificada:

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy my_unified -identity-preserve true
----
. Pare o SVM de destino:
+
[source, cli]
----
vserver stop -vserver <SVM_name>
----
+
O exemplo a seguir interrompe um SVM de destino chamado SVM_backup:

+
[listing]
----
cluster_dst::> vserver stop -vserver svm_backup
----
. No SVM de destino ou no cluster de destino, inicialize a relação de replicação SVM:
+
[source, cli]
----
snapmirror initialize -source-path <SVM_name>: -destination-path <SVM_name>:
----
+

NOTE: Você deve inserir dois pontos (:) após o nome SVM `-source-path` nas opções e `-destination-path` .

+
O exemplo a seguir inicializa a relação entre a SVM de origem e `svm1` o SVM de destino `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror initialize -source-path svm1: -destination-path svm_backup:
----


--
====