---
permalink: data-protection/snapmirror-licensing-concept.html 
sidebar: sidebar 
keywords: snapmirror, licensing, snapvault, vault, mirror, relationship, replication, backup, back up, disaster recovery, dr 
summary: A partir do ONTAP 9.3, o licenciamento foi simplificado para replicação entre instâncias do ONTAP. Nas versões do ONTAP 9, a licença do SnapMirror suporta relações de cofre e espelho. Agora, os usuários podem adquirir uma licença do SnapMirror para dar suporte à replicação do ONTAP para casos de uso de backup e recuperação de desastres. 
---
= Saiba mais sobre o licenciamento do ONTAP SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.3, o licenciamento foi simplificado para replicação entre instâncias do ONTAP. Nas versões do ONTAP 9, a licença do SnapMirror suporta relações de cofre e espelho. Você pode usar uma licença do SnapMirror para dar suporte à replicação do ONTAP para casos de uso de backup e recuperação de desastres.

Antes da versão do ONTAP 9,3, uma licença SnapVault separada era necessária para configurar relações _Vault_ entre instâncias do ONTAP, onde a instância DP poderia reter um número maior de snapshots para suportar casos de uso de backup com tempos de retenção mais longos, e uma licença SnapMirror era necessária para configurar relações _mirror_ entre instâncias do ONTAP, onde cada instância do ONTAP manteria o mesmo número de snapshots (ou seja, uma imagem _mirror_) para suportar casos de recuperação de desastres. Ambas as licenças SnapMirror e SnapVault continuam a ser usadas e suportadas para versões do ONTAP 8.x e 9.x.

Embora as licenças do SnapVault continuem a funcionar e sejam suportadas para ambas as versões do ONTAP 8.x e 9.x, a licença do SnapMirror pode ser usada em vez de uma licença SnapVault e pode ser usada para configurações de espelhamento e cofre.

Para replicação assíncrona do ONTAP, a partir do ONTAP 9.3, um único mecanismo de replicação unificada é usado para configurar políticas de modo de proteção de dados estendida (XDP), em que a licença do SnapMirror pode ser configurada para uma política de espelhamento, uma política de cofre ou uma política de cofre-espelho. É necessária uma licença SnapMirror nos clusters de origem e destino. Uma licença SnapVault não é necessária se uma licença SnapMirror já estiver instalada. A licença perpétua assíncrona do SnapMirror está incluída no pacote de software ONTAP One que é instalado nos novos sistemas AFF e FAS.

Os limites de configuração de proteção de dados são determinados usando vários fatores, incluindo a versão do ONTAP, a plataforma de hardware e as licenças instaladas. Para obter mais informações, https://hwu.netapp.com/["Hardware Universe"^]consulte .



== Licença síncrona SnapMirror

A partir do ONTAP 9.5, as relações síncronas do SnapMirror são suportadas. Você precisa das seguintes licenças para criar um relacionamento síncrono do SnapMirror:

* A licença síncrona do SnapMirror é necessária no cluster de origem e no cluster de destino.
+
A licença síncrona do SnapMirror faz parte do link:../system-admin/manage-licenses-concept.html["Pacote de licenças ONTAP One"].

+
Se o seu sistema tiver sido adquirido antes de junho de 2019 com um pacote Premium ou Flash, você poderá baixar uma chave mestra NetApp para obter a licença síncrona SnapMirror necessária no site de suporte da NetApp: https://mysupport.netapp.com/NOW/knowledge/docs/olio/guides/master_lickey/["Chaves da licença principal"^].

* A licença SnapMirror é necessária no cluster de origem e no cluster de destino.




== Licença de nuvem da SnapMirror

A partir do ONTAP 9,8, a licença de nuvem do SnapMirror fornece replicação assíncrona de snapshots de instâncias do ONTAP para pontos de extremidade de storage de objetos. Os destinos de replicação podem ser configurados usando armazenamentos de objetos no local e serviços de storage de objetos em nuvem pública compatíveis com S3 e S3. Os relacionamentos de nuvem da SnapMirror são compatíveis com sistemas ONTAP para destinos de storage de objetos pré-qualificados.

A nuvem do SnapMirror não está disponível como uma licença autônoma. Apenas uma licença é necessária por cluster do ONTAP. Além de uma licença de nuvem do SnapMirror, a licença assíncrona do SnapMirror também é necessária.

Você precisa das seguintes licenças para criar um relacionamento de nuvem do SnapMirror:

* Uma licença SnapMirror e uma licença de nuvem SnapMirror para replicação diretamente no endpoint do armazenamento de objetos.
* Ao configurar um fluxo de trabalho de replicação de várias políticas (por exemplo, disco para disco para nuvem), é necessária uma licença SnapMirror em todas as instâncias do ONTAP, enquanto a licença de nuvem do SnapMirror é necessária apenas para o cluster de origem que está replicando diretamente para o endpoint de armazenamento de objetos.


Começando com ONTAP 9.9,1, você pode https://docs.netapp.com/us-en/ontap/task_dp_back_up_to_cloud.html["Use o System Manager para replicação na nuvem do SnapMirror"].

Uma lista de aplicativos de terceiros autorizados na nuvem da SnapMirror é publicada no site da NetApp.



== Licença otimizada de proteção de dados

As licenças de proteção de dados otimizada (DPO) não estão mais sendo vendidas e o DPO não é suportado nas plataformas atuais; no entanto, se você tiver uma licença de DPO instalada em uma plataforma compatível, o NetApp continuará fornecendo suporte até o final da disponibilidade dessa plataforma.

O DPO não está incluído com o pacote de licenças ONTAP One e não pode atualizar para o pacote de licenças ONTAP One se a licença DPO estiver instalada num sistema.

Para obter informações sobre plataformas compatíveis, https://hwu.netapp.com/["Hardware Universe"^] consulte .
