---
permalink: data-protection/vol-placement-criteria-svm-dest-reference.html 
sidebar: sidebar 
keywords: snapmirror, svm, replication, disaster recovery, aggregate, volume 
summary: Ao replicar volumes da SVM de origem para o SVM de destino, é importante saber os critérios de seleção de agregados. 
---
= Critérios de colocação de volumes em SVMs de destino do ONTAP SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao replicar volumes da SVM de origem para o SVM de destino, é importante saber os critérios de seleção de agregados.

Os agregados são selecionados com base nos seguintes critérios:

* Os volumes são sempre colocados em agregados não-raiz.
* Agregados não-raiz são selecionados com base no espaço livre disponível e no número de volumes já hospedados no agregado.
+
Agregados com mais espaço livre e menos volumes têm prioridade. O agregado com a prioridade mais alta é selecionado.

* Volumes de origem em agregados FabricPool são colocados em agregados FabricPool no destino com a mesma política de disposição em camadas.
* Se um volume na SVM de origem estiver localizado em um agregado de Flash Pool, o volume será colocado em um agregado de Flash Pool no SVM de destino, se esse agregado existir e tiver espaço livre suficiente.
* Se a `-space-guarantee` opção do volume replicado estiver definida como `volume`, somente agregados com espaço livre maior que o tamanho do volume serão considerados.
* O tamanho do volume aumenta automaticamente no SVM de destino durante a replicação, com base no tamanho do volume de origem.
+
Se você quiser pré-reservar o tamanho no SVM de destino, você deve redimensionar o volume. O tamanho do volume não diminui automaticamente no SVM de destino com base na SVM de origem.



Se você quiser mover um volume de um agregado para outro, use o `volume move` comando na SVM de destino.
