---
permalink: release-notes/index.html 
sidebar: sidebar 
keywords: release notes, new features, ontap 9, digital advisor 
summary: Saiba mais sobre os novos recursos disponíveis no ONTAP 9. 
---
= Destaques do lançamento do ONTAP 9
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada versão do software de gerenciamento de dados ONTAP 9 oferece recursos novos e aprimorados que melhoram os recursos, a capacidade de gerenciamento, o desempenho e as ofertas de segurança do ONTAP.

Além desses destaques, você pode encontrar uma cobertura abrangente por versão de todos os recursos novos e aprimorados introduzidos nas versões recentes do ONTAP.

* Saiba mais https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html["Novos e aprimorados recursos do ONTAP MetroCluster"^]sobre .
* Saiba mais https://docs.netapp.com/us-en/ontap-systems/whats-new.html["Suporte novo e aprimorado para plataformas FAS, ASA e AFF e switches compatíveis"^]sobre .
* Saiba mais sobre as atualizações do https://docs.netapp.com/us-en/ontap-automation/whats_new.html["API REST do ONTAP"^].


Para obter detalhes sobre problemas conhecidos, limitações e avisos de atualização em versões recentes do ONTAP 9, consulte o https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9 Notas de versão"^]. Você deve entrar com sua conta do NetApp ou criar uma conta para acessar as Notas de versão.

Para atualizar para a versão mais recente do ONTAP, xref:../upgrade/prepare.html[Atualize para a versão mais recente do ONTAP]consulte e. xref:../upgrade/when-to-upgrade.html[Quando devo atualizar o ONTAP?]



== Destaques do ONTAP 9.16,1

O ONTAP 9.16,1 oferece recursos novos e aprimorados nas áreas de gerenciamento de segurança, proteção de dados, rede, gerenciamento de SAN e gerenciamento de storage. Para obter uma lista completa de novos recursos e aprimoramentos, xref:whats-new-9161.adoc[O que há de novo no ONTAP 9.16,1]consulte .

* xref:../multi-admin-verify/index.html#rule-protected-commands[Melhorias na verificação multi-admin (MAV)]
+
O ONTAP 9.16,1 adiciona mais comandos à estrutura MAV para proteção adicional contra insiders maliciosos. Esses aprimoramentos incluem gerenciamento de muitos grupos de consistência (CG), Vscan e Autonomous ransomware Protection (ARP) e comandos de configuração NVMe.

* xref:../anti-ransomware/index.html[Proteção autônoma contra ransomware com aprimoramentos de AI (ARP/AI)]
+
O ARP foi atualizado com novos recursos de AI, permitindo que a TI detete e responda a ataques de ransomware com 99% de precisão e recall. Como a IA é treinada em um conjunto de dados abrangente, não há mais um período de aprendizado para o ARP sendo executado em volumes FlexVol e o ARP/AI começa no modo ativo imediatamente. O ARP/AI também apresenta um recurso de atualização automática independente de uma atualização do ONTAP para garantir proteção e resiliência constantes contra as ameaças mais recentes.

* NVMe/TCP em TLS 1,3
+
Proteja o NVMe/TCP "por cabo" na camada de protocolo com uma configuração simplificada e melhor desempenho em comparação com o IPSec.

* xref:../networking/ipsec-prepare.html[Suporte para descarga de hardware IPsec para novas placas de rede]
+
O ONTAP 9.16.1 oferece maior desempenho de criptografia "over-the-wire" ao utilizar a funcionalidade de descarga de hardware IPSec em placas de descarga introduzidas na mais recente geração de plataformas de sistemas AFF A-series e AFF-C.

* xref:../san-admin/enable-space-allocation.html[Suporte para alocação de espaço NVMe]
+
A realocação de espaço (também chamada de "perfuração" e "desmapear") agora é compatível com namespaces NVMe. O dellocation de espaço ajuda volumes com thin Provisioning e namespaces NVMe a recuperar espaço não usado quando os dados são excluídos pelo aplicativo host. Isso melhora muito a eficiência geral de armazenamento, especialmente com sistemas de arquivos que têm alta rotatividade de dados.

* xref:../flexgroup/enable-adv-capacity-flexgroup-task.html[Balanceamento de capacidade avançado para volumes FlexGroup]
+
O NetApp FlexGroup volumes pode, opcionalmente, distribuir dados em um único arquivo em vários volumes constituintes de back-end, reduzindo gargalos de desempenho e adicionando consistência no balanceamento de capacidade entre os volumes constituintes do back-end.

* xref:../svm-migrate/index.html[Suporte de mobilidade de dados SVM para migração de configurações do MetroCluster]
+
O ONTAP é compatível com as seguintes migrações do MetroCluster SVM:

+
** Migração de um SVM entre uma configuração que não seja MetroCluster e uma configuração IP MetroCluster
** Migração de um SVM entre duas configurações de MetroCluster IP
** Migração de um SVM entre uma configuração de MetroCluster FC e uma configuração de MetroCluster IP






== Destaques do ONTAP 9.15,1

O ONTAP 9.15,1 oferece recursos novos e aprimorados nas áreas de gerenciamento de segurança, proteção de dados e suporte a workloads nas. Para obter uma lista completa de novos recursos e aprimoramentos, xref:whats-new-9151.adoc[O que há de novo no ONTAP 9.15,1]consulte .

* https://www.netapp.com/data-storage/aff-a-series/["Suporte para novos sistemas AFF A-series, storage criado para AI"^]
+
O ONTAP 9.15,1 dá suporte aos novos sistemas AFF A1K, AFF A90 e AFF A70 de alta performance, desenvolvidos para a próxima geração de workloads de negócios, como treinamento e inferência de AI/ML. Essa nova classe de sistemas fornece até o dobro da performance das ofertas existentes do AFF A-series e fornece eficiência de storage aprimorada "sempre ativa", sem interrupções de performance.

* xref:../smb-admin/windows-backup-symlinks.html[Aplicativos de backup do Windows e links simbólicos em estilo Unix]
+
Começando com ONTAP 9.15,1, você também tem a opção de fazer backup do próprio link simbólico em vez dos dados para os quais ele aponta. Isso pode fornecer vários benefícios, incluindo melhor desempenho de seus aplicativos de backup. Você pode ativar o recurso usando a CLI do ONTAP ou a API REST.

* xref:../authentication/dynamic-authorization-overview.html[Autorização dinâmica]
+
O ONTAP 9.15,1 introduz uma estrutura inicial para autorização dinâmica, um recurso de segurança que pode determinar se um comando emitido por uma conta de administrador deve ser negado, solicitado para autenticação adicional ou autorizado a prosseguir. As determinações são baseadas na pontuação de confiança da conta do usuário, levando em conta fatores como hora do dia, localização, endereço IP, uso confiável do dispositivo e histórico de autenticação e autorização do usuário.

* xref:../multi-admin-verify/index.html#rule-protected-commands[Escopo expandido de impactos para verificação de vários administradores]
+
O ONTAP 9.15,1 RC1 adiciona mais de uma centena de novos comandos à estrutura MAV para proteção adicional contra insiders maliciosos.

* Suporte de criptografia TLS 1,3 para peering de cluster e muito mais
+
O ONTAP 9.15,1 apresenta suporte de criptografia TLS 1,3 para criptografia de peering de cluster, FlexCache, SnapMirror e armazenamento S3. Aplicativos como o FabricPool, o armazenamento de Blobs de páginas do Microsoft Azure e a nuvem do SnapMirror continuam a usar o TLS 1,2 para a versão 9.15.1.

* Suporte para tráfego SMTP através de TLS
+
Transfira dados do AutoSupport com segurança por e-mail com suporte a TLS.

* xref:../snapmirror-active-sync/index.html[Sincronização ativa do SnapMirror para configurações ativo-ativo simétricas]
+
Essa nova funcionalidade fornece replicação bidirecional síncrona para continuidade dos negócios e recuperação de desastres. Proteja o acesso a dados para workloads SAN críticos com acesso de leitura e gravação simultâneos aos dados em vários domínios de falha, permitindo operações ininterruptas e minimizando o tempo de inatividade durante desastres ou falhas do sistema.

* xref:../flexcache-writeback/flexcache-writeback-enable-task.html[FlexCache write-back]
+
O FlexCache write-back permite que os clientes gravem localmente em volumes FlexCache, reduzindo a latência e melhorando a performance em comparação à gravação diretamente no volume de origem. Os dados recém-gravados são replicados assincronamente de volta ao volume de origem.

* xref:../nfs-rdma/index.html[NFSv3 sobre RDMA]
+
O suporte NFSv3 sobre RDMA pode ajudá-lo a atender aos requisitos de alto desempenho, fornecendo acesso de baixa latência e alta largura de banda via TCP.





== Destaques do ONTAP 9.14,1

O ONTAP 9.14,1 oferece recursos novos e aprimorados nas áreas de FabricPool, proteção anti-ransomware, OAuth e muito mais. Para obter uma lista completa de novos recursos e aprimoramentos, xref:whats-new-9141.adoc[O que há de novo no ONTAP 9.14,1]consulte .

* xref:../volumes/determine-space-usage-volume-aggregate-concept.html[Redução de reservas no WAFL]
+
O ONTAP 9.14,1 introduz um aumento imediato de cinco por cento no espaço utilizável em sistemas FAS e Cloud Volumes ONTAP, reduzindo a reserva WAFL em agregados com 30 TB ou mais.

* xref:../fabricpool/enable-disable-volume-cloud-write-task.html[Melhorias no FabricPool]
+
O FabricPool aumenta xref:../fabricpool/enable-disable-aggressive-read-ahead-task.html[leia o desempenho]e permite a gravação direta na nuvem, reduzindo o risco de ficar sem espaço e reduzindo os custos de storage movendo dados inativos para uma camada de storage mais barata.

* link:../authentication/oauth2-deploy-ontap.html["Suporte para OAuth 2,0"]
+
O ONTAP suporta a estrutura OAuth 2,0, que pode ser configurada usando o Gerenciador de sistema. Com o OAuth 2,0, você pode fornecer acesso seguro ao ONTAP para estruturas de automação sem criar ou expor IDs de usuário e senhas a scripts de texto simples e runbooks.

* link:../anti-ransomware/manage-parameters-task.html["Aprimoramentos de proteção autônoma contra ransomware (ARP)"]
+
O ARP concede mais controle sobre a segurança de eventos, permitindo que você ajuste as condições que criam alertas e reduzindo a possibilidade de falsos positivos.

* xref:../data-protection/create-delete-snapmirror-failover-test-task.html[Ensaio de recuperação de desastres do SnapMirror no Gerente de sistemas]
+
O System Manager fornece um fluxo de trabalho simples para testar facilmente a recuperação de desastres em um local remoto e limpar após o teste. Esse recurso permite testes mais fáceis e frequentes e maior confiança nos objetivos de tempo de recuperação.

* xref:../s3-config/index.html[S3 suporte de bloqueio de objetos]
+
O ONTAP S3 oferece suporte ao comando API de bloqueio de objeto, permitindo que você proteja os dados gravados no ONTAP com S3 contra exclusão usando comandos padrão da API S3 e garanta que os dados importantes sejam protegidos pelo período de tempo apropriado.

* xref:../assign-tags-cluster-task.html[Cluster] e xref:../assign-tags-volumes-task.html[volume] marcação
+
Adicione tags de metadados a volumes e clusters, que seguem os dados conforme eles são migrados do local para a nuvem e revertidos.





== Destaques do ONTAP 9.13,1

O ONTAP 9.13,1 oferece recursos novos e aprimorados nas áreas de proteção contra ransomware, grupos de consistência, qualidade do serviço, gerenciamento de capacidade do locatário e muito mais. Para obter uma lista completa de novos recursos e aprimoramentos, xref:whats-new-9131.adoc[O que há de novo no ONTAP 9.13,1]consulte .

* Aprimoramentos de proteção autônoma contra ransomware (ARP):
+
** xref:../anti-ransomware/enable-default-task.adoc[Capacitação automática]
+
Com o ONTAP 9.13,1, o ARP passa automaticamente do treinamento para o modo de produção após ter dados de aprendizado suficientes, eliminando a necessidade de um administrador habilitá-lo após o período de 30 dias.

** xref:../anti-ransomware/use-cases-restrictions-concept.html#multi-admin-verification-with-volumes-protected-with-arp[Suporte à verificação de vários administradores]
+
Os comandos de desativação ARP são suportados pela verificação multi-admin, garantindo que nenhum administrador pode desativar o ARP para expor os dados a potenciais ataques de ransomware.

** xref:../anti-ransomware/use-cases-restrictions-concept.html[Suporte à FlexGroup]
+
O ARP suporta FlexGroups começando com ONTAP 9.13,1. O ARP pode monitorar e proteger FlexGroups que abrangem vários volumes e nós no cluster, permitindo que até mesmo os maiores conjuntos de dados sejam protegidos com ARP.



* xref:../consistency-groups/index.html[Monitoramento de desempenho e capacidade para grupos de consistência no System Manager]
+
O monitoramento de desempenho e capacidade fornece detalhes para cada grupo de consistência, permitindo que você identifique e relate rapidamente problemas potenciais no nível da aplicação, em vez de apenas no nível do objeto de dados.

* xref:../volumes/manage-svm-capacity.html[Gerenciamento de capacidade do locatário]
+
Os clientes e fornecedores de serviços que alocação a vários clientes podem definir um limite de capacidade em cada SVM, permitindo que os locatários realizem provisionamento de autoatendimento sem o risco de uma capacidade excessivamente demorada no cluster.

* xref:../performance-admin/adaptive-policy-template-task.html[Qualidade de Serviço tetos e pisos]
+
O ONTAP 9.13,1 permite agrupar objetos como volumes, LUNs ou arquivos em grupos e atribuir um limite de QoS (IOPs máximos) ou andar (IOPs mínimos), melhorando as expectativas de desempenho do aplicativo.





== Destaques do ONTAP 9.12,1

O ONTAP 9.12,1 oferece recursos novos e aprimorados nas áreas de fortalecimento da segurança, retenção, desempenho e muito mais. Para obter uma lista completa de novos recursos e aprimoramentos, xref:whats-new-9121.adoc[O que há de novo no ONTAP 9.12,1]consulte .

* xref:../snaplock/snapshot-lock-concept.html[Instantâneos invioláveis]
+
Com a tecnologia SnapLock, os instantâneos podem ser protegidos contra a eliminação na origem ou no destino.

+
Retenha mais pontos de recuperação protegendo snapshots no storage primário e secundário contra a exclusão por invasores de ransomware ou administradores desonestos.

* xref:../anti-ransomware/index.html[Aprimoramentos de proteção autônoma contra ransomware (ARP)]
+
Habilite imediatamente a proteção inteligente e autônoma contra ransomware em storage secundário, com base no modelo de triagem já concluído para o storage primário.

+
Após um failover, identifique instantaneamente potenciais ataques de ransomware no storage secundário. Um snapshot é imediatamente retirado dos dados que estão começando a ser afetados e os administradores são notificados, ajudando a parar um ataque e melhorar a recuperação.

* xref:../nas-audit/plan-fpolicy-event-config-concept.html[FPolicy]
+
Ativação com um clique do FPolicy do ONTAP para permitir o bloqueio automático de arquivos mal-intencionados conhecidos a ativação simplificada ajuda a proteger contra ataques típicos de ransomware que usam extensões de arquivo conhecidas e comuns.

* xref:../system-admin/ontap-implements-audit-logging-concept.html[Fortalecimento da segurança: Registro de retenção inviolável]
+
O login de retenção à prova de violações no ONTAP seguro que as contas de administrador comprometidas não podem ocultar ações maliciosas. O Admin e o histórico do usuário não podem ser alterados ou excluídos sem o conhecimento do sistema.

+
Registre e audite todas as ações de administração, independentemente da origem, garantindo que todas as ações que impactam os dados sejam capturadas. Um alerta é gerado sempre que os logs de auditoria do sistema foram adulterados de qualquer forma notificando os administradores da alteração.

* xref:../authentication/setup-ssh-multifactor-authentication-task.html[Fortalecimento da segurança: Autenticação multifator expandida]
+
A autenticação multifator (MFA) para CLI (SSH) suporta dispositivos token de hardware físico Yubikey, garantindo que um invasor não possa acessar o sistema ONTAP usando credenciais roubadas ou um sistema cliente comprometido. O Cisco DUO é compatível com MFA no Gerenciador de sistemas.

* Dualidade ficheiro-objeto (acesso multiprotocolo)
+
A dualidade ficheiro-objeto permite o acesso nativo de leitura e gravação do protocolo S3 à mesma fonte de dados que já tem acesso ao protocolo nas. Você pode acessar ao mesmo tempo o storage como arquivos ou como objetos da mesma fonte de dados, eliminando a necessidade de cópias duplicadas de dados para uso com diferentes protocolos (S3 ou nas), como análises que usam dados de objeto.

* xref:../flexgroup/manage-flexgroup-rebalance-task.html[Rebalanceamento do FlexGroup]
+
Se os componentes do FlexGroup ficarem desequilibrados, o FlexGroup poderá ser rebalanceado e gerenciado sem interrupções com a CLI, a API REST e o Gerenciador de sistemas. Para um desempenho ideal, os membros constituintes dentro de um FlexGroup devem ter sua capacidade usada distribuída uniformemente.

* Melhorias na capacidade de storage
+
A reserva de espaço do WAFL foi significativamente reduzida, fornecendo até 40 TIB mais capacidade utilizável por agregado.





== Destaques do ONTAP 9.11,1

O ONTAP 9.11,1 oferece recursos novos e aprimorados nas áreas de segurança, retenção, desempenho e muito mais. Para obter uma lista completa de novos recursos e aprimoramentos, xref:whats-new-9111.adoc[O que há de novo no ONTAP 9.11,1]consulte .

* xref:../multi-admin-verify/index.html[Verificação multi-admin]
+
A verificação multi-admin (MAV) é uma abordagem nativa da indústria para verificação, exigindo várias aprovações para tarefas administrativas sensíveis, como excluir um instantâneo ou volume. As aprovações necessárias em uma implementação MAV evitam ataques maliciosos e alterações acidentais nos dados.

* xref:../anti-ransomware/index.html[Melhorias na proteção Autonomous ransomware]
+
O Autonomous ransomware Protection (ARP) usa o aprendizado de máquina para detetar ameaças de ransomware com maior granularidade, permitindo que você identifique ameaças rapidamente e acelere a recuperação em caso de violação.

* xref:../flexgroup/supported-unsupported-config-concept.html#features-supported-beginning-with-ontap-9-11-1[SnapLock Compliance para FlexGroup volumes]
+
Proteja os dados com bloqueio de arquivos WORM para workloads, que não podem ser alterados ou excluídos.

* xref:../flexgroup/fast-directory-delete-asynchronous-task.html[Eliminação assíncrona do diretório]
+
Com o ONTAP 9.11,1, a exclusão de arquivos ocorre em segundo plano do sistema ONTAP, permitindo que você exclua facilmente grandes diretórios e, ao mesmo tempo, elimine impactos no desempenho e na latência na e/S do host

* xref:../s3-config/index.html[S3 melhorias]
+
Simplifique e expanda os recursos de gerenciamento de dados de objeto do S3 com o ONTAP com endpoints de API adicionais e controle de versão de objetos no nível do bucket, permitindo que várias versões de um objeto sejam armazenadas no mesmo bucket.

* Melhorias no System Manager
+
O System Manager oferece suporte a recursos avançados para otimizar recursos de storage e melhorar o gerenciamento de auditoria. Essas atualizações incluem habilidades aprimoradas de gerenciamento e configuração de agregados de storage, visibilidade aprimorada da análise do sistema e visualização de hardware para sistemas FAS.





== Destaques do ONTAP 9.10,1

O ONTAP 9.10,1 oferece recursos novos e aprimorados nas áreas de proteção de segurança, análise de performance, suporte ao protocolo NVMe e opções de backup de storage de objetos. Para obter uma lista completa de novos recursos e aprimoramentos, xref:whats-new-9101.adoc[O que há de novo no ONTAP 9.10,1]consulte .

* xref:../anti-ransomware/index.html[Proteção autônoma contra ransomware]
+
O Autonomous ransomware Protection cria automaticamente um snapshot do seu volume e alerta os administradores quando uma atividade anormal é detetada, permitindo que você detete rapidamente ataques de ransomware e se recupere com mais rapidez.

* Melhorias no System Manager
+
O System Manager faz o download automático de atualizações de firmware para discos, gavetas e processadores de serviço, além de fornecer novas integrações com o Active IQ Digital Advisor (também conhecido como consultor digital), o BlueXP  e o gerenciamento de certificados. Essas melhorias simplificam a administração e mantêm a continuidade dos negócios.

* xref:../concept_nas_file_system_analytics_overview.html[Melhorias na análise do sistema de arquivos]
+
O File System Analytics fornece telemetria adicional para identificar os principais arquivos, diretórios e usuários em seu compartilhamento de arquivos, permitindo identificar problemas de performance de workload para melhorar o Planejamento e a implementação de QoS.

* xref:../nvme/support-limitations.html[Compatibilidade com NVMe em TCP (NVMe/TCP) para sistemas AFF]
+
Obter alta performance e reduzir o TCO da SAN empresarial e workloads modernos no sistema AFF quando você usa NVMe/TCP em sua rede Ethernet existente.

* xref:../nvme/support-limitations.html[Compatibilidade com NVMe em Fibre Channel (NVMe/FC) para sistemas NetApp FAS]
+
Usar o protocolo NVMe/FC nos arrays híbridos para permitir a migração uniforme para o NVMe.

* xref:../s3-snapmirror/index.html[Backup de nuvem híbrida nativa para storage de objetos]
+
Proteja seus dados do ONTAP S3 com seus destinos de storage de objetos à sua escolha. Use a replicação do SnapMirror para fazer backup no storage local com o StorageGRID, na nuvem com Amazon S3 ou em outro bucket do ONTAP S3 nos sistemas NetApp AFF e FAS.

* xref:../flexcache/global-file-locking-task.html[Bloqueio global de arquivos com o FlexCache]
+
Garanta a consistência do arquivo nos locais de cache durante as atualizações para arquivos de origem na origem com bloqueio global de arquivos usando o FlexCache. Esse aprimoramento permite bloqueios exclusivos de leitura de arquivos em uma relação de origem para cache para cargas de trabalho que exigem bloqueio aprimorado.





== Destaques do ONTAP 9.9,1

O ONTAP 9.91,1 oferece recursos novos e aprimorados nas áreas de eficiência de storage, autenticação multifator, recuperação de desastres e muito mais. Para obter uma lista completa de novos recursos e aprimoramentos, xref:whats-new-991.adoc[O que há de novo no ONTAP 9.9,1]consulte .

* Segurança aprimorada para gerenciamento de acesso remoto CLI
+
O suporte para hash de senha SHA512 e SSH A512 protege as credenciais da conta de administrador de agentes maliciosos que estão tentando obter acesso ao sistema.

* https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_install_and_cable_the_mcc_components.html["Aprimoramentos de IP do MetroCluster: Suporte para clusters de 8 nós"^]
+
O novo limite é duas vezes maior do que o anterior, fornecendo suporte para configurações MetroCluster e permitindo disponibilidade contínua de dados.

* xref:../snapmirror-active-sync/index.html[Sincronização ativa do SnapMirror]
+
Oferece mais opções de replicação para backup e recuperação de desastres para grandes contêineres de dados para workloads nas.

* xref:../san-admin/storage-virtualization-vmware-copy-offload-concept.html[Maior performance da SAN]
+
Oferece performance de SAN até quatro vezes maior para aplicações LUN únicas, como datastores VMware, para que você possa obter alta performance em seu ambiente SAN.

* xref:../task_cloud_backup_data_using_cbs.html[Nova opção de storage de objetos para nuvem híbrida]
+
Permite o uso do StorageGRID como destino do NetApp Cloud Backup Service para simplificar e automatizar o backup de seus dados ONTAP no local.



.Próximas etapas
* xref:../upgrade/prepare.html[Atualize para a versão mais recente do ONTAP]
* xref:../upgrade/when-to-upgrade.html[Quando devo atualizar o ONTAP?]

