---
permalink: release-notes/release-support-reference.html 
sidebar: sidebar 
keywords: release notes, release support, support levels 
summary: Saiba mais sobre os novos recursos disponíveis no ONTAP 9. 
---
= Suporte ao lançamento do ONTAP 9
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Começando com o lançamento do ONTAP 9.8, o NetApp entrega lançamentos do ONTAP duas vezes por ano civil. Embora os planos estejam sujeitos a mudanças, a intenção é entregar novos lançamentos do ONTAP no segundo e quarto trimestre de cada ano civil. Use essas informações para Planejar o período de tempo da atualização para aproveitar a versão mais recente do ONTAP.

[cols="50,50"]
|===
| Versão | Data de lançamento 


 a| 
9.17.1
 a| 
Setembro de 2025



 a| 
9.16.1
 a| 
Janeiro de 2025



 a| 
9.15.1
 a| 
Julho de 2024



 a| 
9.14.1
 a| 
Janeiro de 2024



 a| 
9.13.1
 a| 
Junho de 2023



 a| 
9.12.1
 a| 
Fevereiro de 2023



 a| 
9.11.1
 a| 
Julho de 2022



 a| 
9.10.1
 a| 
Janeiro de 2022



 a| 
9.9.1
 a| 
Junho de 2021



 a| 

NOTE: Se você estiver executando uma versão do ONTAP anterior a 9,10.1, provavelmente estará no suporte limitado ou no suporte de autoatendimento. Considere atualizar para versões com suporte completo. Você pode verificar o nível de suporte para sua versão do ONTAP no https://mysupport.netapp.com/site/info/version-support#ontap_svst["Site de suporte da NetApp"^].

|===


== Níveis de suporte

O nível de suporte disponível para uma versão específica do ONTAP varia dependendo de quando o software foi lançado.

[cols="20,10,10,10,10,10,10,10,10"]
|===
| Nível de suporte 3+| Suporte completo 2+| Suporte limitado 3+| Suporte por autoatendimento 


 a| 
Ano
 a| 
1
 a| 
2
 a| 
3
 a| 
4
 a| 
5
 a| 
6
 a| 
7
 a| 
8



 a| 
Acesso à documentação online
 a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
Sim



 a| 
Suporte técnico
 a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
 a| 
 a| 



 a| 
Análise de causa raiz
 a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
 a| 
 a| 



 a| 
Downloads de software
 a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
 a| 
 a| 



 a| 
Atualizações de serviço (versões de patch [P-lançamentos])
 a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
 a| 
 a| 
 a| 
 a| 



 a| 
Alertas sobre vulnerabilidades
 a| 
Sim
 a| 
Sim
 a| 
Sim
 a| 
 a| 
 a| 
 a| 
 a| 

|===
Para atualizar para a versão mais recente do ONTAP, xref:../upgrade/prepare.html[Atualize para a versão mais recente do ONTAP]consulte e. xref:../upgrade/when-to-upgrade.html[Quando devo atualizar o ONTAP?]
