---
permalink: fabricpool/assign-new-tag-volume-creation-task.html 
sidebar: sidebar 
keywords: assigning, new tag, volume creation 
summary: Você pode criar uma nova tag de objeto quando quiser atribuir uma ou mais tags a novos objetos dispostos em camadas a partir de um novo volume criado. 
---
= Atribua uma nova tag durante a criação de volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode criar uma nova tag de objeto quando quiser atribuir uma ou mais tags a novos objetos dispostos em camadas a partir de um novo volume criado. Você pode usar tags para ajudar a classificar e classificar objetos em categorias para facilitar o gerenciamento de dados. A partir do ONTAP 9.8, você pode usar o Gerenciador do sistema para criar tags de objeto.

.Sobre esta tarefa
Você pode definir tags apenas em volumes FabricPool anexados ao StorageGRID. Essas tags são mantidas durante uma movimentação de volume.

* É permitido um máximo de 4 etiquetas por volume.
* Na CLI, cada tag de objeto deve ser um par de chave-valor separado por um sinal igual (`""`).
* Na CLI, várias tags devem ser separadas por uma (`""`vírgula ).
* Cada valor de tag pode conter um máximo de 127 carateres.
* Cada tecla de tag deve começar com um caractere alfabético ou um sublinhado.
+
As teclas devem conter apenas carateres alfanuméricos e sublinhados, e o número máximo de carateres permitido é 127.





== Procedimento

Você pode atribuir tags de objeto com o Gerenciador de sistema do ONTAP ou a CLI do ONTAP.

[role="tabbed-block"]
====
.System Manager
--
. Navegue até *Storage > Tiers*.
. Localize uma camada de storage com volumes que você deseja etiquetar.
. Clique na guia *volumes*.
. Localize o volume que você deseja marcar e na coluna *Tags de objeto* selecione *clique para inserir tags*.
. Introduza uma chave e um valor.
. Clique em *aplicar*.


--
.CLI
--
. Use o `volume create` comando com a `-tiering-object-tags` opção para criar um novo volume com as tags especificadas. Você pode especificar várias tags em pares separados por vírgulas:
+
[listing]
----
volume create [ -vserver <vserver name> ] -volume <volume_name> -tiering-object-tags <key1=value1> [
    ,<key2=value2>,<key3=value3>,<key4=value4> ]
----
+
O exemplo a seguir cria um volume chamado fp_volume1 com três tags de objeto.

+
[listing]
----
vol create -volume fp_volume1 -vserver vs0 -tiering-object-tags project=fabricpool,type=abc,content=data
----


--
====