---
permalink: fabricpool/install-ca-certificate-storagegrid-task.html 
sidebar: sidebar 
keywords: installing, ca certificate, storagegrid 
summary: A menos que você Planeje desabilitar a verificação de certificados para o StorageGRID, você deve instalar um certificado da CA StorageGRID no cluster para que o ONTAP possa se autenticar com o StorageGRID como o armazenamento de objetos para o FabricPool. 
---
= Instale um certificado de CA em um cluster do ONTAP para StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O uso de certificados CA cria uma relação confiável entre aplicativos clientes e StorageGRID.

A menos que você Planeje desabilitar a verificação de certificados para o StorageGRID, você deve instalar um certificado da CA StorageGRID no cluster para que o ONTAP possa se autenticar com o StorageGRID como o armazenamento de objetos para o FabricPool.

Embora o StorageGRID possa gerar certificados autoassinados, o uso de certificados assinados de uma autoridade de certificação de terceiros é a prática recomendada.

.Sobre esta tarefa
Embora a instalação e o uso de certificados de autoridade de certificação (CA) sejam práticas recomendadas, começando com o ONTAP 9,4, a instalação de certificados de CA não é necessária para o StorageGRID.

.Passos
. Contacte o administrador do StorageGRID para obter o https://docs.netapp.com/us-en/storagegrid-118/admin/configuring-storagegrid-certificates-for-fabricpool.html["Certificado CA do sistema StorageGRID"^].
. Use o `security certificate install` comando com o `-type` `server-ca` parâmetro para instalar o certificado da CA do StorageGRID no cluster.
+
O nome de domínio totalmente qualificado (FQDN) inserido deve corresponder ao nome comum personalizado no certificado da CA do StorageGRID.





== Atualizar um certificado expirado

Para atualizar um certificado expirado, a prática recomendada é usar uma CA confiável para gerar o novo certificado de servidor. Além disso, você deve garantir que o certificado seja atualizado no servidor StorageGRID e no cluster ONTAP ao mesmo tempo para manter qualquer tempo de inatividade ao mínimo.

.Informações relacionadas
https://docs.netapp.com/us-en/storagegrid-family/["Recursos do StorageGRID"^]
