---
permalink: fabricpool/move-volume-task.html 
sidebar: sidebar 
keywords: moving, volume, fabricpool, fabric pool, tiering, policy, policies, block, capacity, cold data, 
summary: Quando você move um volume para o FabricPool, você tem a opção de especificar ou alterar a política de disposição em camadas do volume com a movimentação. A partir do ONTAP 9.8, quando você move um volume não FabricPool com relatórios de dados inativos ativados, o FabricPool usa um mapa de calor para ler blocos direcionáveis e move dados inativos para a camada de capacidade no destino do FabricPool. 
---
= Mover um volume para FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando você move um volume para o FabricPool, você tem a opção de especificar ou alterar a política de disposição em camadas do volume com a movimentação. A partir do ONTAP 9.8, quando você move um volume não FabricPool com relatórios de dados inativos ativados, o FabricPool usa um mapa de calor para ler blocos direcionáveis e move dados inativos para a camada de capacidade no destino do FabricPool.

.O que você vai precisar
Você deve entender como mudar a política de disposição em camadas pode afetar o tempo necessário para que os dados fiquem inativos e sejam movidos para a categoria de nuvem.

link:tiering-policies-concept.html#what-happens-to-the-tiering-policy-when-you-move-a-volume["O que acontece com a política de disposição em camadas quando você move um volume"]

.Sobre esta tarefa
Se um volume que não é FabricPool tiver a geração de relatórios de dados inativos ativada, quando você move um volume com política de disposição em categorias `auto` ou `snapshot-only` para um FabricPool, o FabricPool lê os blocos direcionáveis de temperatura de um arquivo de mapa de calor e usa essa temperatura para mover os dados inativos diretamente para a camada de capacidade no destino do FabricPool.

Você não deve usar a `-tiering-policy` opção na movimentação de volume se estiver usando o ONTAP 9.8 e quiser que o FabricPools use informações de relatórios de dados inativos para mover dados diretamente para o nível de capacidade. O uso dessa opção faz com que o FabricPools ignore os dados de temperatura e, em vez disso, siga o comportamento de movimentação de Releases antes do ONTAP 9.8.

.Passo
. Use o `volume move start` comando para mover um volume para o FabricPool.
+
O `-tiering-policy` parâmetro opcional permite especificar a política de disposição em camadas para o volume.

+
Você pode especificar uma das seguintes políticas de disposição em categorias:

+
** `snapshot-only` (predefinição)
** `auto`
** `all`
** `none` E link:tiering-policies-concept.html#types-of-fabricpool-tiering-policies["Tipos de políticas de disposição em camadas do FabricPool"]




.Exemplo de mover um volume para o FabricPool
O exemplo a seguir move um volume chamado "yvol2" do SVM "VS1" para o agregado habilitado para FabricPool "dest_FabricPool". O volume está explicitamente definido para usar a `none` política de disposição em camadas:

[listing]
----
cluster1::> volume move start -vserver vs1 -volume myvol2
-destination-aggregate dest_FabricPool -tiering-policy none
----