---
permalink: fabricpool/promote-mirror-task.html 
sidebar: sidebar 
keywords: promoting, fabricpool, mirror 
summary: Você pode reatribuir o espelho de armazenamento de objetos como o armazenamento de objetos principal promovendo-o. Quando o espelho de armazenamento de objetos se torna o principal, o primário original se torna automaticamente o espelho. 
---
= Promova um espelho ONTAP FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode reatribuir o espelho de armazenamento de objetos como o armazenamento de objetos principal promovendo-o. Quando o espelho de armazenamento de objetos se torna o principal, o primário original se torna automaticamente o espelho.

.Antes de começar
* O espelho FabricPool deve estar sincronizado
* O armazenamento de objetos deve estar operacional


.Sobre esta tarefa
Você pode substituir o armazenamento de objetos original por um armazenamento de objetos de um provedor de nuvem diferente. Por exemplo, seu espelho original pode ser um armazenamento de objetos da AWS, mas você pode substituí-lo por um armazenamento de objetos do Azure.

.Passos
. Verifique se o espelho FabricPool está em sincronia usando o `storage aggregate object-store show-resync-status` comando. Se o espelho FabricPool estiver em sincronia, nenhuma entrada será exibida. Se o espelho não estiver em sincronia, aguarde até que a ressincronização seja concluída.
+
[listing]
----
aggregate1::> storage aggregate object-store show-resync-status -aggregate aggr1
----
+
[listing]
----
                                               Complete
      Aggregate    Primary       Mirror        Percentage
      ---------    -----------   ----------    ----------
      aggr1        my-store-1     my-store-2     40%
----
. Promova um espelho de armazenamento de objetos usando o `storage aggregate object-store modify -aggregate` comando.
+
[listing]
----
cluster1::> storage aggregate object-store modify -aggregate aggr1 -name my-store-2 -mirror-type primary
----

