---
permalink: fabricpool/setup-alibaba-object-storage-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting, up, alibaba cloud object, storage, cloud tier 
summary: Se você estiver executando o ONTAP 9.6 ou posterior, poderá configurar o Alibaba Cloud Object Storage como a camada de nuvem para FabricPool. 
---
= Configurar o Alibaba Cloud Object Storage como a camada de nuvem do ONTAP FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se você estiver executando o ONTAP 9.6 ou posterior, poderá configurar o Alibaba Cloud Object Storage como a camada de nuvem para FabricPool.

.Considerações para usar o storage de objetos na nuvem Alibaba com FabricPool
* A link:https://bluexp.netapp.com/cloud-tiering["Licença de disposição em camadas do BlueXP"] é necessário ao fazer categorias no Alibaba Cloud Object Storage. Para obter mais informações, link:install-license-aws-azure-ibm-task.html["Instale uma licença FabricPool em um cluster do ONTAP"]consulte .
* Nos sistemas AFF e FAS e ONTAP Select, o FabricPool oferece suporte às seguintes classes de serviço de storage de objetos Alibaba:
+
** Alibaba Object Storage Service Standard
** Alibaba Object Storage Service Acesso não frequente
+
https://www.alibabacloud.com/help/doc-detail/51374.htm["Alibaba Cloud: Introdução às classes de armazenamento"^]





Entre em Contato com o representante de vendas da NetApp para obter informações sobre classes de armazenamento não listadas.

.Passos
. Especifique as informações de configuração do Alibaba Cloud Object Storage usando o `storage aggregate object-store config create` comando com o `-provider-type` `AliCloud` parâmetro.
+
** O `storage aggregate object-store config create` comando falhará se o ONTAP não puder acessar o Alibaba Cloud Object Storage com as informações fornecidas.
** Use o `-access-key` parâmetro para especificar a chave de acesso para autorizar solicitações ao armazenamento de objetos Alibaba Cloud Object Storage.
** Se a senha do Alibaba Cloud Object Storage for alterada, você deverá atualizar a senha correspondente armazenada no ONTAP imediatamente.
+
Com isso, o ONTAP pode acessar os dados no Alibaba Cloud Object Storage sem interrupção.



+
[listing]
----
storage aggregate object-store config create my_ali_oss_store_1
-provider-type AliCloud -server oss-us-east-1.aliyuncs.com
-container-name my-ali-oss-bucket -access-key DXJRXHPXHYXA9X31X3JX
----
. Exiba e verifique as informações de configuração do Alibaba Cloud Object Storage usando o `storage aggregate object-store config show` comando.
+
O `storage aggregate object-store config modify` comando permite modificar as informações de configuração do Alibaba Cloud Object Storage para FabricPool.



.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-config-create.html["objeto de armazenamento agregado - configuração de armazenamento criada"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-object-store-config-modify.html["objeto de armazenamento agregado - modificar configuração de armazenamento"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-config-show.html["configuração de armazenamento de objetos agregados de armazenamento mostrar"^]

