---
permalink: nfs-config/add-storage-capacity-nfs-enabled-svm-concept.html 
sidebar: sidebar 
keywords: add, storage, capacity, nfs-enabled, svm 
summary: Para adicionar capacidade de storage a um SVM habilitado para NFS, você precisa criar um volume ou qtree para fornecer um contêiner de storage e criar ou modificar uma política de exportação para esse contêiner. Em seguida, você pode verificar o acesso do cliente NFS a partir do cluster e testar o acesso a partir de sistemas cliente. 
---
= Adicionar capacidade de storage a uma visão geral da SVM habilitada para NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para adicionar capacidade de storage a um SVM habilitado para NFS, você precisa criar um volume ou qtree para fornecer um contêiner de storage e criar ou modificar uma política de exportação para esse contêiner. Em seguida, você pode verificar o acesso do cliente NFS a partir do cluster e testar o acesso a partir de sistemas cliente.

.Antes de começar
* O NFS precisa estar completamente configurado no SVM.
* A política de exportação padrão do volume raiz da SVM deve conter uma regra que permita acesso a todos os clientes.
* Todas as atualizações da configuração dos serviços de nome devem estar concluídas.
* Quaisquer adições ou modificações a uma configuração Kerberos devem estar concluídas.

