---
permalink: nfs-config/assess-physical-storage-requirements-task.html 
sidebar: sidebar 
keywords: assess, physical, storage, requirements 
summary: Antes de provisionar o storage NFS para clientes, você deve garantir que haja espaço suficiente em um agregado existente para o novo volume. Se não houver, você poderá adicionar discos a um agregado existente ou criar um novo agregado do tipo desejado. 
---
= Avaliar os requisitos de armazenamento físico
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de provisionar o storage NFS para clientes, você deve garantir que haja espaço suficiente em um agregado existente para o novo volume. Se não houver, você poderá adicionar discos a um agregado existente ou criar um novo agregado do tipo desejado.

.Passos
. Exibir espaço disponível em agregados existentes:
+
`storage aggregate show`

+
Se houver um agregado com espaço suficiente, Registre seu nome na Planilha.

+
[listing]
----
cluster::> storage aggregate show
Aggregate     Size Available Used% State   #Vols  Nodes  RAID Status
--------- -------- --------- ----- ------- ------ ------ -----------
aggr_0     239.0GB   11.13GB   95% online       1 node1  raid_dp,
                                                         normal
aggr_1     239.0GB   11.13GB   95% online       1 node1  raid_dp,
                                                         normal
aggr_2     239.0GB   11.13GB   95% online       1 node2  raid_dp,
                                                         normal
aggr_3     239.0GB   11.13GB   95% online       1 node2  raid_dp,
                                                         normal
aggr_4     239.0GB   238.9GB   95% online       5 node3  raid_dp,
                                                         normal
aggr_5     239.0GB   239.0GB   95% online       4 node4  raid_dp,
                                                         normal
6 entries were displayed.
----
. Se não houver agregados com espaço suficiente, adicione discos a um agregado existente usando o `storage aggregate add-disks` comando ou crie um novo agregado usando o `storage aggregate create` comando.

