---
permalink: nfs-config/assign-export-policy-qtree-task.html 
sidebar: sidebar 
keywords: assign, export, policy, qtree 
summary: Em vez de exportar um volume inteiro, você também pode exportar uma qtree específica em um volume para torná-lo diretamente acessível aos clientes. Você pode exportar uma qtree atribuindo uma política de exportação a ela. Você pode atribuir a política de exportação ao criar uma nova qtree ou modificando uma qtree existente. 
---
= Atribua uma política de exportação a uma qtree
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Em vez de exportar um volume inteiro, você também pode exportar uma qtree específica em um volume para torná-lo diretamente acessível aos clientes. Você pode exportar uma qtree atribuindo uma política de exportação a ela. Você pode atribuir a política de exportação ao criar uma nova qtree ou modificando uma qtree existente.

.O que você vai precisar
A política de exportação tem de existir.

.Sobre esta tarefa
Por padrão, qtrees herdam a política de exportação pai do volume contendo se não for especificado de outra forma no momento da criação.

Você pode associar uma política de exportação a uma qtree quando você cria a qtree ou a qualquer momento depois de criar a qtree. Você pode associar uma política de exportação à qtree, embora uma política possa ser associada a muitos qtrees.

.Passos
. Se uma política de exportação não foi especificada quando a qtree foi criada, atribua uma política de exportação à qtree:
+
`volume qtree modify -vserver _vserver_name_ -qtree-path /vol/_volume_name/qtree_name_ -export-policy _export_policy_name_`

. Verifique se a política foi atribuída à qtree:
+
`volume qtree show -qtree _qtree_name_ -fields export-policy`



.Exemplo
Os comandos a seguir atribuem a política de exportação nfs_policy à qtree qt1 no SVM VS1 e verificam a atribuição:

[listing]
----
cluster::> volume modify -v1server vs1 -qtree-path /vol/vol1/qt1 -policy nfs_policy

cluster::>volume qtree show -volume vol1 -fields export-policy
vserver volume qtree export-policy
------- ------ ----- -------------
vs1     data1  qt01  nfs_policy
----