---
permalink: nfs-config/create-local-unix-user-task.html 
sidebar: sidebar 
keywords: create, local, unix, user 
summary: Você pode usar o comando name-service unix-user create dos serviços vserver para criar usuários UNIX locais. Um usuário UNIX local é um usuário UNIX criado no SVM como uma opção de serviços de nome UNIX para ser usado no processamento de mapeamentos de nomes. 
---
= Crie um usuário local do UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `vserver services name-service unix-user create` comando para criar usuários UNIX locais. Um usuário UNIX local é um usuário UNIX criado no SVM como uma opção de serviços de nome UNIX para ser usado no processamento de mapeamentos de nomes.

.Passo
. Criar um usuário local UNIX:
+
`vserver services name-service unix-user create -vserver _vserver_name_ -user _user_name_ -id _integer_ -primary-gid _integer_ -full-name _full_name_`

+
`-user _user_name_` especifica o nome de usuário. O comprimento do nome de utilizador tem de ter 64 carateres ou menos.

+
`-id _integer_` Especifica a ID de usuário que você atribui.

+
`-primary-gid _integer_` Especifica o ID do grupo principal. Isso adiciona o usuário ao grupo principal. Depois de criar o usuário, você pode adicionar manualmente o usuário a qualquer grupo adicional desejado.



.Exemplo
O comando a seguir cria um usuário UNIX local chamado johnm (nome completo "John Miller") no SVM chamado VS1. O usuário tem o ID 123 e o ID do grupo principal 100.

[listing]
----
node::> vserver services name-service unix-user create -vserver vs1 -user johnm -id 123
-primary-gid 100 -full-name "John Miller"
----