---
permalink: nfs-config/exports-differ-concept.html 
sidebar: sidebar 
keywords: ontap, exports, differ, 7-mode, exports 
summary: Se você não estiver familiarizado com a forma como o ONTAP implementa as exportações NFS, você pode comparar as ferramentas de configuração de exportação de 7 modos e ONTAP, bem como exemplos de arquivos /etc/exports de 7 modos com políticas e regras em cluster. 
---
= Como as exportações do ONTAP diferem das exportações do modo 7
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se não estiver familiarizado com a forma como o ONTAP implementa as exportações de NFS, pode comparar as ferramentas de configuração de exportação de modo 7D e ONTAP, bem como exemplos de arquivos de modo 7D `/etc/exports` com políticas e regras em cluster.

No ONTAP não há `/etc/exports` nenhum arquivo e nenhum `exportfs` comando. Em vez disso, você deve definir uma política de exportação. As políticas de exportação permitem que você controle o acesso do cliente da mesma forma que você fez no modo 7, mas oferecem funcionalidades adicionais, como a capacidade de reutilizar a mesma política de exportação para vários volumes.

.Informações relacionadas
link:../nfs-admin/index.html["Gerenciamento de NFS"]

https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["Relatório técnico da NetApp 4067: Guia de práticas recomendadas e implementação de NFS"^]
