---
permalink: nfs-config/export-policies-concept.html 
sidebar: sidebar 
keywords: secure, nfs, access, using, export, policies 
summary: Você pode usar políticas de exportação para restringir o acesso NFS a volumes ou qtrees a clientes que correspondem a parâmetros específicos. Ao provisionar um novo storage, você pode usar uma política e regras existentes, adicionar regras a uma política existente ou criar uma nova política e regras. Você também pode verificar a configuração das políticas de exportação 
---
= Aprenda a proteger o acesso ONTAP NFS usando políticas de exportação
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar políticas de exportação para restringir o acesso NFS a volumes ou qtrees a clientes que correspondem a parâmetros específicos. Ao provisionar um novo storage, você pode usar uma política e regras existentes, adicionar regras a uma política existente ou criar uma nova política e regras. Você também pode verificar a configuração das políticas de exportação

[NOTE]
====
A partir do ONTAP 9.3, você pode habilitar a verificação de configuração de política de exportação como uma tarefa em segundo plano que Registra quaisquer violações de regras em uma lista de regras de erro. Os `vserver export-policy config-checker` comandos invocam o verificador e exibem resultados, que podem ser usados para verificar sua configuração e excluir regras errôneas da política.os comandos validam somente a configuração de exportação para nomes de host, netgroups e usuários anônimos.

====