---
permalink: nfs-config/index.html 
sidebar: sidebar 
keywords: NFS, configuration, overview 
summary: Você pode usar os comandos CLI do ONTAP 9 para configurar o acesso do cliente NFS aos arquivos contidos em um novo volume ou qtree em uma máquina virtual de armazenamento nova ou existente. 
---
= Visão geral da configuração de NFS com a CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar os comandos de CLI do ONTAP 9 para configurar o acesso de cliente NFS a arquivos contidos em um novo volume ou qtree em uma máquina virtual de storage (SVM) nova ou existente.

Utilize estes procedimentos se pretender configurar o acesso a um volume ou qtree da seguinte forma:

* Você deseja usar qualquer versão do NFS atualmente compatível com ONTAP: NFSv3, NFSv4, NFSv4,1, NFSv4,2 ou NFSv4,1 com pNFS.
* Você deseja usar a interface de linha de comando (CLI), não o System Manager ou uma ferramenta de script automatizado.
+
Para usar o System Manager para configurar o acesso multiprotocolo nas, link:../task_nas_provision_nfs_and_smb.html["Provisionar storage nas para Windows e Linux usando NFS e SMB"]consulte .

* Você quer usar as práticas recomendadas, não explorar todas as opções disponíveis.
+
Saiba mais sobre a sintaxe de comando no link:https://docs.netapp.com/us-en/ontap-cli/["Referência do comando ONTAP"^].

* As permissões de arquivo UNIX serão usadas para proteger o novo volume.
* Você tem o administrador de clusters Privileges, e não o Privileges do administrador da SVM.


Se quiser obter detalhes sobre a gama de capacidades do protocolo NFS da ONTAP, consulte o link:../nfs-admin/index.html["Visão geral de referência de NFS"].



== Outras maneiras de fazer isso em ONTAP

|===


| Para executar estas tarefas com... | Consulte... 


| O Gerenciador de sistema redesenhado (disponível com o ONTAP 9.7 e posterior) | link:../task_nas_provision_linux_nfs.html["Provisione storage nas para servidores Linux usando NFS"] 


| System Manager Classic (disponível com o ONTAP 9.7 e versões anteriores | link:https://docs.netapp.com/us-en/ontap-system-manager-classic/nfs-config/index.html["Visão geral da configuração NFS"^] 
|===