---
permalink: nfs-config/verify-status-netgroup-definitions-task.html 
sidebar: sidebar 
keywords: verify, status, netgroup, definitions 
summary: Depois de carregar netgroups no SVM, você pode usar o comando vserver services name-service netgroup status para verificar o status das definições de netgroup. Isso permite determinar se as definições de netgroup são consistentes em todos os nós que fazem backup do SVM. 
---
= Verificar definições de netgroup ONTAP NFS SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depois de carregar netgroups no SVM, você pode usar o `vserver services name-service netgroup status` comando para verificar o status das definições do netgroup. Isso permite determinar se as definições de netgroup são consistentes em todos os nós que fazem backup do SVM.

.Passos
. Defina o nível de privilégio como avançado:
+
`set -privilege advanced`

. Verifique o status das definições do netgroup:
+
`vserver services name-service netgroup status`

+
Pode apresentar informações adicionais numa vista mais detalhada.

. Voltar ao nível de privilégio de administrador:
+
`set -privilege admin`



.Exemplo
Depois que o nível de privilégio é definido, o seguinte comando exibe o status do netgroup para todos os SVMs:

[listing]
----
vs1::> set -privilege advanced

Warning: These advanced commands are potentially dangerous; use them only when
         directed to do so by technical support.
Do you wish to continue? (y or n): y

vs1::*> vserver services name-service netgroup status
Virtual
Server    Node            Load Time           Hash Value
--------- --------------- ------------------- --------------------------------
vs1
          node1           9/20/2006 16:04:53  e6cb38ec1396a280c0d2b77e3a84eda2
          node2           9/20/2006 16:06:26  e6cb38ec1396a280c0d2b77e3a84eda2
          node3           9/20/2006 16:08:08  e6cb38ec1396a280c0d2b77e3a84eda2
          node4           9/20/2006 16:11:33  e6cb38ec1396a280c0d2b77e3a84eda2
----