---
permalink: nfs-config/where-provision-storage-capacity-task.html 
sidebar: sidebar 
keywords: decide, provision, new, nfs, storage, capacity 
summary: Antes de criar um novo volume ou qtree NFS, você precisa decidir se deseja colocá-lo em uma SVM nova ou existente e quanto de configuração o SVM precisa. Esta decisão determina o seu fluxo de trabalho. 
---
= Saiba mais sobre o provisionamento de capacidade de armazenamento ONTAP NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de criar um novo volume ou qtree NFS, você precisa decidir se deseja colocá-lo em uma SVM nova ou existente e quanto de configuração o SVM precisa. Esta decisão determina o seu fluxo de trabalho.

.Opções
* Se você quiser provisionar um volume ou qtree em um novo SVM ou em um SVM existente que tenha o NFS habilitado, mas não configurado, siga as etapas em "Configurar acesso NFS a um SVM" e "Adicionar storage NFS a um SVM habilitado para NFS".
+
xref:../nfs-config/create-svms-data-access-task.html[Configurar o acesso NFS a uma SVM]

+
xref:add-storage-capacity-nfs-enabled-svm-concept.adoc[Adicionar storage NFS a uma SVM habilitada para NFS]

+
Você pode optar por criar um novo SVM se uma das seguintes opções for verdadeira:

+
** Você está habilitando o NFS em um cluster pela primeira vez.
** Você tem SVMs existentes em um cluster no qual não deseja habilitar o suporte a NFS.
** Você tem um ou mais SVMs habilitados para NFS em um cluster e deseja outro servidor NFS em um namespace isolado (cenário de alocação a vários clientes). Você também deve escolher essa opção para provisionar storage em uma SVM existente que tenha o NFS habilitado, mas não configurado. Esse pode ser o caso se você criou o SVM para acesso à SAN ou se nenhum protocolo foi habilitado quando o SVM foi criado.


+
Depois de ativar o NFS no SVM, proceda ao provisionamento de um volume ou qtree.

* Se você quiser provisionar um volume ou qtree em uma SVM atual totalmente configurada para acesso NFS, siga as etapas em "adicionando storage NFS a uma SVM habilitado para NFS".
+
xref:add-storage-capacity-nfs-enabled-svm-concept.adoc[Adição de storage NFS a uma SVM habilitada para NFS]


