---
permalink: system-admin/accessg-node-log-core-dump-mib-files-task.html 
sidebar: sidebar 
keywords: service, processor, infrastructure, spi, web, service, node, log, core, dump, mib, file, browser 
summary: 'O serviço da Web spi (Service Processor Infrastructure) está ativado por predefinição para permitir que um browser da Web aceda aos ficheiros de registo, despejo de núcleo e MIB de um nó no cluster. Os arquivos permanecem acessíveis mesmo quando o nó está inativo, desde que o nó seja assumido pelo parceiro.' 
---
= Acesse logs de nó do ONTAP, despejos de núcleo e arquivos MIB usando um navegador da Web
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O (`spi`serviço da Web Service Processor Infrastructure ) está habilitado por padrão para permitir que um navegador da Web acesse os arquivos de log, despejo de núcleo e MIB de um nó no cluster. Os arquivos permanecem acessíveis mesmo quando o nó está inativo, desde que o nó seja assumido pelo parceiro.

.Antes de começar
* O LIF de gerenciamento de clusters deve estar ativo.
+
Você pode usar o LIF de gerenciamento do cluster ou de um nó para acessar o `spi` serviço da Web. No entanto, é recomendável usar o LIF de gerenciamento de cluster.

+
O `network interface show` comando exibe o status de todas as LIFs no cluster.

* Você deve usar uma conta de usuário local para acessar o `spi` serviço da Web, as contas de usuário de domínio não são suportadas.
* Se a sua conta de usuário não tiver a função "admin" (que tem acesso ao `spi` serviço da Web por padrão), sua função de controle de acesso deve ter acesso ao `spi` serviço da Web.
+
O `vserver services web access show` comando mostra quais funções têm acesso a quais serviços da Web.

* Se você não estiver usando a conta de usuário "'admin'" (que inclui o `http` método de acesso por padrão), sua conta de usuário deve ser configurada com o `http` método de acesso.
+
O `security login show` comando mostra os métodos de acesso e login das contas de usuário e suas funções de controle de acesso.

* Se você quiser usar HTTPS para acesso seguro à Web, o SSL deve estar habilitado e um certificado digital deve ser instalado.
+
O `system services web show` comando exibe a configuração do mecanismo de protocolo da Web no nível do cluster.



.Sobre esta tarefa
O `spi` serviço da Web está ativado por predefinição e o serviço pode ser desativado manualmente (`vserver services web modify -vserver * -name spi -enabled false`).

A função "'admin'" tem acesso ao `spi` serviço web por padrão e o acesso pode ser desativado manualmente (`services web access delete -vserver _cluster_name_ -name spi -role admin`).

.Passos
. Aponte o navegador da Web para o `spi` URL do serviço da Web em um dos seguintes formatos:
+
** `http://_cluster-mgmt-LIF_/spi/`
** `https://_cluster-mgmt-LIF_/spi/`
+
`cluster-mgmt-LIF` É o endereço IP do LIF de gerenciamento de cluster.



. Quando solicitado pelo navegador, insira sua conta de usuário e senha.
+
Depois que a conta for autenticada, o navegador exibirá links para os `/mroot/etc/log/` diretórios , `/mroot/etc/crash/` e `/mroot/etc/mib/` de cada nó no cluster.


