---
permalink: system-admin/access-sp-bmc-system-console-task.html 
sidebar: sidebar 
keywords: access, sp, bmc, system, console, serial, troubleshoot 
summary: 'Você pode acessar o SP a partir do console do sistema (também chamado de console serial) para executar tarefas de monitoramento ou solução de problemas.' 
---
= Aceda ao SP/BMC a partir da consola do sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode acessar o SP a partir do console do sistema (também chamado de _console serial_) para executar tarefas de monitoramento ou solução de problemas.

.Sobre esta tarefa
Esta tarefa aplica-se tanto ao SP como ao BMC.

.Passos
. Acesse a CLI do SP a partir do console do sistema pressionando Ctrl-G no prompt.
. Faça login na CLI do SP quando for solicitado.
+
O prompt SP é exibido, indicando que você tem acesso à CLI do SP.

. Saia da CLI do SP e retorne ao console do sistema pressionando Ctrl-D e pressione Enter.


.Exemplo de acesso à CLI do SP a partir do console do sistema
O exemplo a seguir mostra o resultado de pressionar Ctrl-G do console do sistema para acessar a CLI do SP. O `help system power` comando é inserido no prompt do SP, seguido de Ctrl-D e Enter para retornar ao console do sistema.

[listing]
----
cluster1::>
----
(Pressione Ctrl-G para acessar a CLI do SP.)

[listing]
----
Switching console to Service Processor
Service Processor Login:
Password:
SP>
SP> help system power
system power cycle - power the system off, then on
system power off - power the system off
system power on - power the system on
system power status - print system power status
SP>
----
(Pressione Ctrl-D e Enter para retornar ao console do sistema.)

[listing]
----
cluster1::>
----