---
permalink: system-admin/acces-ssp-bmc-administration-host-task.html 
sidebar: sidebar 
keywords: access, sp, bmc, administration, host, node, management 
summary: Você pode fazer login no SP de um nó de um host de administração para executar tarefas de gerenciamento de nós remotamente. 
---
= Acesse o ONTAP SP/BMC de um nó a partir de um host de administração
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode fazer login no SP de um nó de um host de administração para executar tarefas de gerenciamento de nós remotamente.

.O que você vai precisar
Devem ser cumpridas as seguintes condições:

* O host de administração que você usa para acessar o SP deve oferecer suporte a SSHv2.
* Sua conta de usuário já deve estar configurada para acessar o SP.
+
Para acessar o SP, sua conta de usuário deve ter sido criada com o `-application` parâmetro do `security login create` comando definido como `service-processor` e o `-authmethod` parâmetro definido como `password`.



[NOTE]
====
Esta tarefa aplica-se tanto ao SP como ao BMC.

====
Se o SP estiver configurado para usar um endereço IPv4 ou IPv6 e se cinco tentativas de login SSH de um host falharem consecutivamente em 10 minutos, o SP rejeita solicitações de login SSH e suspende a comunicação com o endereço IP do host por 15 minutos. A comunicação é retomada após 15 minutos e você pode tentar fazer login no SP novamente.

O ONTAP impede que você crie ou use nomes reservados ao sistema (como "root" e "naroot") para acessar o cluster ou o SP.

.Passos
. No host de administração, faça login no SP:
+
`*ssh username@SP_IP_address*`

. Quando lhe for solicitado, introduza a palavra-passe `username` do .
+
O prompt SP é exibido, indicando que você tem acesso à CLI do SP.



.Exemplos de acesso à SP de um host de administração
O exemplo a seguir mostra como fazer login no SP com uma conta de usuário `joe` , que foi configurada para acessar o SP.

[listing]
----
[admin_host]$ ssh joe@192.168.123.98
joe@192.168.123.98's password:
SP>
----
Os exemplos a seguir mostram como usar o endereço global IPv6 ou o endereço anunciado pelo roteador IPv6 para fazer login no SP em um nó que tenha SSH configurado para IPv6 e o SP configurado para IPv6.

[listing]
----
[admin_host]$ ssh joe@fd22:8b1e:b255:202::1234
joe@fd22:8b1e:b255:202::1234's password:
SP>
----
[listing]
----
[admin_host]$ ssh joe@fd22:8b1e:b255:202:2a0:98ff:fe01:7d5b
joe@fd22:8b1e:b255:202:2a0:98ff:fe01:7d5b's password:
SP>
----