---
permalink: system-admin/accounts-access-sp-concept.html 
sidebar: sidebar 
keywords: account, access, sp, cluster, user, cli, node 
summary: Ao tentar acessar o SP, você será solicitado a fornecer a credencial. Contas de usuário do cluster criadas com o tipo de aplicativo service-processor têm acesso à CLI do SP em qualquer nó do cluster. As contas de usuário do SP são gerenciadas pelo ONTAP e autenticadas por senha. A partir do ONTAP 9.15.1, as contas de usuário do SP podem, opcionalmente, usar autenticação de dois fatores com uma chave pública como segundo método de autenticação. A partir do ONTAP 9.9.1, as contas de usuário do SP devem ter a função admin. 
---
= Acesse o processador de serviços do ONTAP usando uma conta de usuário de cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ao tentar acessar o SP, você será solicitado a fornecer a credencial. Contas de usuário do cluster criadas com o tipo de aplicativo  `service-processor` têm acesso à CLI do SP em qualquer nó do cluster. As contas de usuário do SP são gerenciadas pelo ONTAP e autenticadas por senha. A partir do ONTAP 9.15.1, as contas de usuário do SP podem, opcionalmente, usar autenticação de dois fatores com uma chave pública como segundo método de autenticação. A partir do ONTAP 9.9.1, as contas de usuário do SP devem ter a função  `admin`.

As contas de usuário para acessar o SP são gerenciadas pelo ONTAP em vez da CLI do SP. Uma conta de usuário do cluster pode acessar o SP se for criada com o parâmetro  `-application` do comando  `security login create` definido como  `service-processor` e o parâmetro  `-authmethod` definido como  `password`. A partir do ONTAP 9.15.1, você pode opcionalmente configurar autenticação de dois fatores para uma conta do SP definindo o segundo método de autenticação como  `publickey` com o comando  `security login modify` e, em seguida, associando a chave pública com o comando  `security login publickey create`.

Você deve especificar o `-role` parâmetro ao criar uma conta de usuário do SP.

* No ONTAP 9.9,1 e versões posteriores, você deve especificar `admin` para o `-role` parâmetro, e quaisquer modificações em uma conta exigem a `admin` função. Outras funções não são mais permitidas por motivos de segurança.
+
** Se você estiver atualizando para o ONTAP 9.9,1 ou versões posteriores, link:../upgrade/sp-user-accounts-change-concept.html["Alteração nas contas de usuário que podem acessar o processador de serviço"]consulte .
** Se você estiver revertendo para o ONTAP 9.8 ou versões anteriores, link:../revert/verify-sp-user-accounts-task.html["Verifique as contas de usuário que podem acessar o processador de serviço"]consulte .


* No ONTAP 9.8 e versões anteriores, qualquer função pode acessar o SP, mas `admin` é recomendado.


Por padrão, a conta de usuário do cluster chamada "admin" inclui o `service-processor` tipo de aplicativo e tem acesso ao SP.

O ONTAP impede que você crie contas de usuário com nomes que são reservados para o sistema (como "root" e "naroot"). Não é possível usar um nome reservado ao sistema para acessar o cluster ou o SP.

Você pode exibir as contas de usuário atuais do SP usando o `-application service-processor` parâmetro `security login show` do comando.

Saiba mais sobre link:https://docs.netapp.com/us-en/ontap-cli/security-login-modify.html[`security login modify`^], link:https://docs.netapp.com/us-en/ontap-cli/security-login-publickey-create.html[`security login publickey create`^], e link:https://docs.netapp.com/us-en/ontap-cli/security-login-show.html[`security login show`^] na referência de comandos do ONTAP.
