---
permalink: system-admin/administrative-privilege-levels-concept.html 
sidebar: sidebar 
keywords: administrative, privilege, levels, parameters, commands, admin, advanced, diagnostic 
summary: 'Os comandos e parâmetros do ONTAP são definidos em três níveis de privilégio: admin, Advanced e Diagnostic. Os níveis de privilégio refletem os níveis de habilidade necessários na execução das tarefas.' 
---
= Entenda os níveis de privilégio dos comandos da CLI do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os comandos e parâmetros do ONTAP são definidos em três níveis de privilégio: _Admin_, _Advanced_ e _diagnostic_. Os níveis de privilégio refletem os níveis de habilidade necessários na execução das tarefas.

* *admin*
+
A maioria dos comandos e parâmetros estão disponíveis neste nível. Eles são usados para tarefas comuns ou rotineiras.

* *avançado*
+
Comandos e parâmetros neste nível são usados com pouca frequência, exigem conhecimentos avançados e podem causar problemas se usados de forma inadequada.

+
Você usa comandos ou parâmetros avançados apenas com o Conselho do pessoal de suporte.

* *diagnóstico*
+
Comandos e parâmetros de diagnóstico são potencialmente disruptivos. Eles são usados apenas pelo pessoal de suporte para diagnosticar e corrigir problemas.


