---
permalink: system-admin/autosupport-severity-types-concept.html 
sidebar: sidebar 
keywords: autosupport, severity, types, message 
summary: As mensagens do AutoSupport têm tipos de gravidade que ajudam a entender o propósito de cada mensagem, por exemplo, chamar a atenção imediata para um problema de emergência ou apenas para fornecer informações. 
---
= Saiba mais sobre os tipos de gravidade do ONTAP AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As mensagens do AutoSupport têm tipos de gravidade que ajudam a entender o propósito de cada mensagem - por exemplo, chamar a atenção imediata para um problema de emergência ou apenas para fornecer informações.

As mensagens têm uma das seguintes gravidades:

* *Alerta*: As mensagens de alerta indicam que um evento de nível superior próximo pode ocorrer se você não tomar alguma ação.
+
Você deve tomar uma ação contra mensagens de alerta dentro de 24 horas.

* *Emergência*: As mensagens de emergência são exibidas quando ocorre uma interrupção.
+
Você deve tomar uma ação contra mensagens de emergência imediatamente.

* *Erro*: As condições de erro indicam o que pode acontecer se você ignorar.
* *Aviso*: Condição normal, mas significativa.
* *Info*: A mensagem informativa fornece detalhes sobre o problema, que você pode ignorar.
* *Debug*: Mensagens no nível de depuração fornecem instruções que você deve executar.


Se a organização de suporte interno receber mensagens do AutoSupport por e-mail, a gravidade será exibida na linha de assunto da mensagem de e-mail.
