---
permalink: system-admin/autosupport-active-iq-digital-advisor-concept.html 
sidebar: sidebar 
keywords: autosupport, active iq, digital advisor, active, iq, digital, advisor, telemetry, artificial, intelligence 
summary: O componente AutoSupport do ONTAP coleta telemetria e envia-a para análise. O consultor digital analisa os dados do AutoSupport e fornece cuidado e otimização proativos. Usando inteligência artificial, o Digital Advisor pode identificar possíveis problemas e ajudá-lo a resolvê-los antes que eles afetem seu negócio. 
---
= Sobre o consultor digital e o AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O componente AutoSupport do ONTAP coleta telemetria e envia-a para análise. O consultor digital analisa os dados do AutoSupport e fornece cuidado e otimização proativos. Usando inteligência artificial, o Digital Advisor pode identificar possíveis problemas e ajudá-lo a resolvê-los antes que eles afetem seu negócio.

O Digital Advisor permite otimizar sua infraestrutura de dados em toda a nuvem híbrida global, fornecendo análises preditivas práticas e suporte proativo por meio de um portal baseado na nuvem e aplicativo móvel. Insights e recomendações orientados por dados do consultor digital estão disponíveis para todos os clientes da NetApp com um contrato de SupportEdge ativo (os recursos variam de acordo com o produto e a camada de suporte).

Aqui estão algumas coisas que você pode fazer com o Digital Advisor:

* Planejar atualizações. O consultor digital identifica problemas no seu ambiente que podem ser resolvidos ao atualizar para uma versão mais recente do ONTAP e o componente do consultor de atualização ajuda você a Planejar uma atualização bem-sucedida.
* Veja o bem-estar do sistema. Seu painel do Digital Advisor relata quaisquer problemas de bem-estar e ajuda você a corrigir esses problemas. Monitore a capacidade do sistema para garantir que você nunca fique sem espaço de armazenamento. Veja casos de suporte para o seu sistema.
* Gerenciar a performance. O Digital Advisor mostra o desempenho do sistema por um período mais longo do que você pode ver no System Manager. Identifique problemas de configuração e sistema que estejam afetando a performance.
* Maximizar a eficiência: Visualize as métricas de eficiência de storage e identifique maneiras de armazenar mais dados em menos espaço.
* Ver inventário e configuração. O Digital Advisor exibe o inventário completo e as informações de configuração de software e hardware. Veja quando os contratos de serviço estão expirando e renove-os para garantir que você permaneça suportado.


.Informações relacionadas
https://docs.netapp.com/us-en/active-iq/["Documentação do NetApp: Consultor digital"^]

https://aiq.netapp.com/custom-dashboard/search["Inicie o Digital Advisor"^]

https://www.netapp.com/us/services/support-edge.aspx["Serviços da SupportEdge"^]
