---
permalink: system-admin/bmc-cli-commands-reference.html 
sidebar: sidebar 
keywords: bmc, command, cli, log, ssh 
summary: Você pode fazer login no BMC usando SSH. Os seguintes comandos são suportados a partir da linha de comando BMC. 
---
= Comandos CLI suportados para o controlador de gerenciamento de placa base ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode fazer login no BMC usando SSH. Os seguintes comandos são suportados a partir da linha de comando BMC.

|===
| Comando | Função 


 a| 
sistema
 a| 
Exibir uma lista de todos os comandos.



 a| 
consola do sistema
 a| 
Ligue à consola do sistema.  `Ctrl+D`Utilize para sair da sessão.



 a| 
núcleo do sistema
 a| 
Descarregue o núcleo do sistema e reinicie.



 a| 
ciclo de alimentação do sistema
 a| 
Desligue o sistema e, em seguida, ligue-o.



 a| 
desligar o sistema
 a| 
Desligue o sistema.



 a| 
ligar o sistema
 a| 
Ligue o sistema.



 a| 
estado de alimentação do sistema
 a| 
Estado de alimentação do sistema de impressão.



 a| 
reposição do sistema
 a| 
Reinicie o sistema.



 a| 
registo do sistema
 a| 
Imprimir registos da consola do sistema



 a| 
apresentação da fru do sistema [id]
 a| 
Despejar todas/informações da unidade substituível em campo (FRU) selecionada.

|===