---
permalink: system-admin/cluster-management-server-concept.html 
sidebar: sidebar 
keywords: cluster, management, server, adminsvm, svm, single, entity 
summary: 'O servidor de gerenciamento de clusters, também chamado de adminSVM, é uma implementação especializada de máquina virtual de storage (SVM) que apresenta o cluster como uma única entidade gerenciável. Além de servir como o domínio administrativo de mais alto nível, o servidor de gerenciamento de clusters possui recursos que não pertencem logicamente a um SVM de dados.' 
---
= Saiba mais sobre o servidor de gerenciamento de cluster ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O servidor de gerenciamento de cluster, também chamado de __admin__SVM, é uma implementação especializada de máquina virtual de storage (SVM) que apresenta o cluster como uma única entidade gerenciável. Além de servir como o domínio administrativo de mais alto nível, o servidor de gerenciamento de clusters possui recursos que não pertencem logicamente a um SVM de dados.

O servidor de gerenciamento de cluster está sempre disponível no cluster. Você pode acessar o servidor de gerenciamento de cluster por meio do console ou do LIF de gerenciamento de cluster.

Após a falha de sua porta de rede doméstica, o LIF de gerenciamento de cluster automaticamente faz failover para outro nó no cluster. Dependendo das caraterísticas de conetividade do protocolo de gerenciamento que você está usando, você pode ou não notar o failover. Se você estiver usando um protocolo sem conexão (por exemplo, SNMP) ou tiver uma conexão limitada (por exemplo, HTTP), é provável que você não perceba o failover. No entanto, se você estiver usando uma conexão de longo prazo (por exemplo, SSH), então você terá que se reconetar ao servidor de gerenciamento de cluster após o failover.

Quando você cria um cluster, todas as caraterísticas do LIF de gerenciamento de cluster são configuradas, incluindo seu endereço IP, máscara de rede, gateway e porta.

Diferentemente de um SVM ou nó de dados, um servidor de gerenciamento de cluster não tem volume raiz ou volumes de usuário de host (embora possa hospedar volumes do sistema). Além disso, um servidor de gerenciamento de cluster só pode ter LIFs do tipo de gerenciamento de cluster.

Se você executar o `vserver show` comando, o servidor de gerenciamento de cluster aparecerá na lista de saída para esse comando.
