---
permalink: system-admin/cluster-svm-administrators-concept.html 
sidebar: sidebar 
keywords: cluster, svm, administrators,cluster, storage, virtual, machines, svm, vserver 
summary: 'Os administradores de cluster administram todo o cluster e as máquinas virtuais de armazenamento (SVMs, anteriormente conhecidas como VServers) que ele contém. Os administradores do SVM administram apenas seus próprios SVMs de dados.' 
---
= Saiba mais sobre as funções de administrador de cluster e SVM do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os administradores de cluster administram todo o cluster e as máquinas virtuais de armazenamento (SVMs, anteriormente conhecidas como VServers) que ele contém. Os administradores do SVM administram apenas seus próprios SVMs de dados.

Os administradores de cluster podem administrar todo o cluster e seus recursos. Eles também podem configurar SVMs de dados e delegar a administração da SVM aos administradores do SVM. Os recursos específicos que os administradores de cluster têm dependem de suas funções de controle de acesso. Por padrão, um administrador de cluster com o nome de conta "'admin'" ou nome de função tem todos os recursos para gerenciar o cluster e SVMs.

Os administradores do SVM podem administrar apenas seus próprios recursos de rede e storage SVM, como volumes, protocolos, LIFs e serviços. As funcionalidades específicas que os administradores do SVM têm dependem das funções de controle de acesso atribuídas pelos administradores de cluster.

[NOTE]
====
A interface de linha de comando (CLI) do ONTAP continua a usar o termo _SVM_ na saída, e `vserver` como um nome de comando ou parâmetro não foi alterado.

====