---
permalink: system-admin/commands-manage-config-backup-schedules-reference.html 
sidebar: sidebar 
keywords: command, manage, configuration, backup, schedule, settings 
summary: Você pode usar os comandos de configurações de backup de configuração do sistema para gerenciar programações de backup de configuração. 
---
= Comandos ONTAP para gerenciar programações de backup de configuração
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar os `system configuration backup settings` comandos para gerenciar programações de backup de configuração.

Esses comandos estão disponíveis no nível avançado de privilégio.

|===
| Se você quiser... | Use este comando... 


 a| 
Altere as configurações de um agendamento de backup de configuração:

* Especifique uma URL remota (HTTP, HTTPS, FTP ou FTPS) onde os arquivos de backup de configuração serão carregados, além dos locais padrão no cluster
* Especifique um nome de usuário a ser usado para fazer login no URL remoto
* Defina o número de backups a serem mantidos para cada agendamento de backup de configuração

 a| 
`system configuration backup settings modify`

Quando utilizar HTTPS na URL remota, utilize a `-validate-certification` opção para ativar ou desativar a validação de certificados digitais. A validação do certificado está desativada por predefinição.

[NOTE]
====
O servidor da Web para o qual você está fazendo o upload do arquivo de backup de configuração deve ter as operações de COLOCAÇÃO ativadas para HTTP e POST ativadas para HTTPS. Para obter mais informações, consulte a documentação do servidor Web.

====


 a| 
Defina a senha a ser usada para fazer login no URL remoto
 a| 
`system configuration backup settings set-password`



 a| 
Ver as definições do agendamento da cópia de segurança da configuração
 a| 
`system configuration backup settings show`

[NOTE]
====
Você define o `-instance` parâmetro para exibir o nome de usuário e o número de backups a serem mantidos para cada agendamento.

====
|===