---
permalink: system-admin/commands-monitor-health-system-reference.html 
sidebar: sidebar 
keywords: command, monitor, health, system, display, status, cli, software, version, switches, alert 
summary: Você pode usar os comandos de integridade do sistema para exibir informações sobre a integridade dos recursos do sistema, responder a alertas e configurar alertas futuros. O uso dos comandos CLI permite exibir informações detalhadas sobre como o monitoramento de integridade é configurado. As páginas man para os comandos contêm mais informações. 
---
= Comandos para monitorar a integridade do seu sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar os `system health` comandos para exibir informações sobre a integridade dos recursos do sistema, responder a alertas e configurar alertas futuros. O uso dos comandos CLI permite exibir informações detalhadas sobre como o monitoramento de integridade é configurado. Saiba mais sobre `system health` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+health["Referência do comando ONTAP"^]na .



== Apresentar o estado da integridade do sistema

|===
| Se você quiser... | Use este comando... 


 a| 
Apresentar o estado de funcionamento do sistema, que reflete o estado geral dos monitores de saúde individuais
 a| 
`system health status show`



 a| 
Apresentar o estado de funcionamento dos subsistemas para os quais a monitorização de integridade está disponível
 a| 
`system health subsystem show`

|===


== Exibir o status da conetividade do nó

|===
| Se você quiser... | Use este comando... 


 a| 
Exiba detalhes sobre a conectividade do nó para o compartimento de storage, incluindo informações de porta, velocidade da porta HBA, taxa de transferência de e/S e taxa de operações de e/S por segundo
 a| 
`storage shelf show -connectivity`

Use o `-instance` parâmetro para exibir informações detalhadas sobre cada prateleira.



 a| 
Exiba informações sobre unidades e LUNs de storage, incluindo o espaço utilizável, os números de compartimento e compartimento e o nome do nó proprietário
 a| 
`storage disk show`

Use o `-instance` parâmetro para exibir informações detalhadas sobre cada unidade.



 a| 
Exiba informações detalhadas sobre as portas do compartimento de armazenamento, incluindo o tipo, a velocidade e o status da porta
 a| 
`storage port show`

Use o `-instance` parâmetro para exibir informações detalhadas sobre cada adaptador.

|===


== Gerenciar a descoberta de switches de rede de cluster, armazenamento e gerenciamento

[cols="3*"]
|===
| Se você quiser... | Use este comando. (ONTAP 9.8 e posterior) | Use este comando. (ONTAP 9 .7 e anteriores) 


 a| 
Apresentar os interrutores que o grupo de instrumentos monitoriza
 a| 
`system switch ethernet show`
 a| 
`system cluster-switch show`



 a| 
Exiba os switches que o cluster monitora atualmente, incluindo os switches que você excluiu (mostrados na coluna motivo na saída do comando) e as informações de configuração necessárias para acesso à rede ao cluster e aos switches de rede de gerenciamento.

Este comando está disponível no nível de privilégio avançado.
 a| 
`system switch ethernet show-all`
 a| 
`system cluster-switch show-all`



 a| 
Configurar a descoberta de um switch não descoberto
 a| 
`system switch ethernet create`
 a| 
`system cluster-switch create`



 a| 
Modificar informações sobre um switch que o cluster monitora (por exemplo, nome do dispositivo, endereço IP, versão SNMP e cadeia de carateres da comunidade)
 a| 
`system switch ethernet modify`
 a| 
`system cluster-switch modify`



 a| 
Desativar a monitorização de um interrutor
 a| 
`system switch ethernet modify -disable-monitoring`
 a| 
`system cluster-switch modify -disable-monitoring`



 a| 
Desative a descoberta e o monitoramento de um switch e exclua as informações de configuração do switch
 a| 
`system switch ethernet delete`
 a| 
`system cluster-switch delete`



 a| 
Remover permanentemente as informações de configuração do switch que são armazenadas no banco de dados (isso rehabilita a descoberta automática do switch)
 a| 
`system switch ethernet delete -force`
 a| 
`system cluster-switch delete -force`



 a| 
Ative o registo automático para enviar com mensagens AutoSupport.
 a| 
`system switch ethernet log`
 a| 
`system cluster-switch log`

|===


== Responder a alertas gerados

|===
| Se você quiser... | Use este comando... 


 a| 
Exiba informações sobre alertas gerados, como o recurso e o nó em que o alerta foi acionado, e a gravidade e a causa provável do alerta
 a| 
`system health alert show`



 a| 
Exibir informações sobre cada alerta gerado
 a| 
`system health alert show -instance`



 a| 
Indique que alguém está trabalhando em um alerta
 a| 
`system health alert modify`



 a| 
Confirme um alerta
 a| 
`system health alert modify -acknowledge`



 a| 
Suprimir um alerta subsequente para que não afete o estado de funcionamento de um subsistema
 a| 
`system health alert modify -suppress`



 a| 
Exclua um alerta que não foi apagado automaticamente
 a| 
`system health alert delete`



 a| 
Exiba informações sobre as mensagens do AutoSupport que alertas dispararam na última semana, por exemplo, para determinar se um alerta acionou uma mensagem do AutoSupport
 a| 
`system health autosupport trigger history show`

|===


== Configurar alertas futuros

|===
| Se você quiser... | Use este comando... 


 a| 
Ative ou desative a política que controla se um estado de recurso específico gera um alerta específico
 a| 
`system health policy definition modify`

|===


== Exiba informações sobre como o monitoramento de integridade é configurado

|===
| Se você quiser... | Use este comando... 


 a| 
Exibir informações sobre monitores de integridade, como seus nós, nomes, subsistemas e status
 a| 
`system health config show`

[NOTE]
====
Use o `-instance` parâmetro para exibir informações detalhadas sobre cada monitor de integridade.

====


 a| 
Exiba informações sobre os alertas que um monitor de integridade pode gerar
 a| 
`system health alert definition show`

[NOTE]
====
Use o `-instance` parâmetro para exibir informações detalhadas sobre cada definição de alerta.

====


 a| 
Exiba informações sobre as políticas do monitor de integridade, que determinam quando os alertas são gerados
 a| 
`system health policy definition show`

[NOTE]
====
Use o `-instance` parâmetro para exibir informações detalhadas sobre cada política. Use outros parâmetros para filtrar a lista de alertas - por exemplo, por status da política (habilitado ou não), monitor de integridade, alerta e assim por diante.

====
|===
Saiba mais sobre os comandos descritos neste procedimento no link:https://docs.netapp.com/us-en/ontap-cli/["Referência do comando ONTAP"^].
