---
permalink: system-admin/commands-manage-autosupport-reference.html 
sidebar: sidebar 
keywords: command, manage, autosupport, node, message, send, resend, cancel, configure, display, information 
summary: Você usa os comandos AutoSupport do nó do sistema para alterar ou exibir a configuração do AutoSupport, exibir informações sobre mensagens AutoSupport anteriores e enviar, reenviar ou cancelar uma mensagem do AutoSupport. 
---
= Comandos para gerenciar AutoSupport no ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você usa os `system node autosupport` comandos para alterar ou exibir a configuração do AutoSupport, exibir informações sobre mensagens AutoSupport anteriores e enviar, reenviar ou cancelar uma mensagem do AutoSupport.



== Configurar o AutoSupport

|===
| Se você quiser... | Use este comando... 


 a| 
Controle se quaisquer mensagens AutoSupport são enviadas
 a| 
`system node autosupport modify` com o `-state` parâmetro



 a| 
Controlar se as mensagens AutoSupport são enviadas para o suporte técnico
 a| 
`system node autosupport modify` com o `-support` parâmetro



 a| 
Configure o AutoSupport ou modifique a configuração do AutoSupport
 a| 
`system node autosupport modify`



 a| 
Ative e desative as mensagens do AutoSupport para sua organização de suporte interno para eventos de acionamento individuais e especifique relatórios de subsistema adicionais a serem incluídos nas mensagens enviadas em resposta a eventos de acionamento individuais
 a| 
`system node autosupport trigger modify`

|===


== Exibir informações sobre a configuração do AutoSupport

|===
| Se você quiser... | Use este comando... 


 a| 
Apresentar a configuração do AutoSupport
 a| 
`system node autosupport show` com o `-node` parâmetro



 a| 
Veja um resumo de todos os endereços e URLs que recebem mensagens do AutoSupport
 a| 
`system node autosupport destinations show`



 a| 
Exiba quais mensagens do AutoSupport são enviadas para sua organização interna de suporte para eventos de acionamento individuais
 a| 
`system node autosupport trigger show`



 a| 
Apresentar o estado da configuração do AutoSupport, bem como a entrega para vários destinos
 a| 
`system node autosupport check show`



 a| 
Apresentar o estado detalhado da configuração do AutoSupport, bem como a entrega para vários destinos
 a| 
`system node autosupport check show-details`

|===


== Exibir informações sobre mensagens anteriores do AutoSupport

|===
| Se você quiser... | Use este comando... 


 a| 
Exiba informações sobre uma ou mais das 50 mensagens AutoSupport mais recentes
 a| 
`system node autosupport history show`



 a| 
Exiba informações sobre mensagens recentes do AutoSupport geradas para carregar arquivos de despejo de memória ou arquivamento de desempenho para o site de suporte técnico ou um URI especificado
 a| 
`system node autosupport history show-upload-details`



 a| 
Visualize as informações nas mensagens do AutoSupport, incluindo o nome e o tamanho de cada arquivo coletado para a mensagem, juntamente com quaisquer erros
 a| 
`system node autosupport manifest show`

|===


== Enviar, reenviar ou cancelar mensagens AutoSupport

|===
| Se você quiser... | Use este comando... 


 a| 
Retransmita uma mensagem AutoSupport armazenada localmente, identificada pelo seu número de sequência AutoSupport


NOTE: Se você retransmitir uma mensagem do AutoSupport e se o suporte já recebeu essa mensagem, o sistema de suporte não criará um caso duplicado. Se, por outro lado, o suporte não recebeu essa mensagem, o sistema AutoSupport analisará a mensagem e criará um caso, se necessário.
 a| 
`system node autosupport history retransmit`



 a| 
Gerar e enviar uma mensagem AutoSupport - por exemplo, para fins de teste
 a| 
`system node autosupport invoke`


NOTE: Use o `-force` parâmetro para enviar uma mensagem mesmo que o AutoSupport esteja desativado. Use o `-uri` parâmetro para enviar a mensagem para o destino especificado em vez do destino configurado.



 a| 
Cancelar uma mensagem AutoSupport
 a| 
`system node autosupport history cancel`

|===
Saiba mais sobre `system node autosupport` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+node+autosupport["Referência do comando ONTAP"^]na .

.Informações relacionadas
link:../concepts/manual-pages.html["Referência do comando ONTAP"]
