---
permalink: system-admin/commands-manage-node-remotely-reference.html 
sidebar: sidebar 
keywords: command, manage, node, remotely, sp, cli, cluster 
summary: Você pode gerenciar um nó remotamente acessando o SP e executando os comandos da CLI do SP para executar tarefas de gerenciamento de nós. Para várias tarefas de gerenciamento remoto de nós comumente executadas, você também pode usar comandos ONTAP de outro nó no cluster. Alguns comandos do SP são específicos da plataforma e podem não estar disponíveis na sua plataforma. 
---
= Comandos ONTAP para gerenciamento remoto de nós
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode gerenciar um nó remotamente acessando o SP e executando os comandos da CLI do SP para executar tarefas de gerenciamento de nós. Para várias tarefas de gerenciamento remoto de nós comumente executadas, você também pode usar comandos ONTAP de outro nó no cluster. Alguns comandos do SP são específicos da plataforma e podem não estar disponíveis na sua plataforma.

|===
| Se você quiser... | Use este comando SP... | Use este comando BMC... | Ou este comando ONTAP ... 


 a| 
Exiba os comandos SP disponíveis ou subcomandos de um comando SP especificado
 a| 
`help` [`command`]
 a| 
 a| 



 a| 
Exibir o nível de privilégio atual para a CLI do SP
 a| 
`priv show`
 a| 
 a| 



 a| 
Defina o nível de privilégio para acessar o modo especificado para a CLI do SP
 a| 
`priv set` {`admin` | `advanced` | `diag`
 a| 
 a| 



 a| 
Apresentar a data e a hora do sistema
 a| 
`date`
 a| 
 a| 
`date`



 a| 
Exibir eventos registrados pelo SP
 a| 
`events` {`all` | `info` `newest` `number` | `oldest number` | | `search keyword`
 a| 
 a| 



 a| 
Exibir informações de status do SP e configuração da rede
 a| 
`sp status`[`-v`  `-d` | ]

A `-v` opção exibe estatísticas do SP em forma verbose. A `-d` opção adiciona o log de depuração do SP à tela.
 a| 
`bmc status`[`-v`  `-d` | ]

A `-v` opção exibe estatísticas do SP em forma verbose. A `-d` opção adiciona o log de depuração do SP à tela.
 a| 
`system service-processor show`



 a| 
Apresentar o período de tempo em que o SP esteve ativo e o número médio de trabalhos na fila de execução nos últimos 1, 5 e 15 minutos
 a| 
`sp uptime`
 a| 
`bmc uptime`
 a| 



 a| 
Exiba os logs do console do sistema
 a| 
`system log`
 a| 
 a| 



 a| 
Exiba os arquivos de log do SP ou os arquivos em um arquivo
 a| 
`sp log history show`[`-archive` {`latest` {`all` Selecionar | | `archive-name`] [`-dump` {`all` | `file-name`
 a| 
`bmc log history show`[`-archive` {`latest` {`all` Selecionar | | `archive-name`] [`-dump` {`all` | `file-name`
 a| 



 a| 
Apresentar o estado de alimentação do controlador de um nó
 a| 
`system power status`
 a| 
 a| 
`system node power show`



 a| 
Apresentar informações sobre a bateria
 a| 
`system battery show`
 a| 
 a| 



 a| 
Apresentar informações ACP ou o estado dos sensores expansores
 a| 
`system acp`[`show`  `sensors show` | ]
 a| 
 a| 



 a| 
Listar todas as FRUs do sistema e suas IDs
 a| 
`system fru list`
 a| 
 a| 



 a| 
Exibir informações do produto para a FRU especificada
 a| 
`system fru show` `fru_id`
 a| 
 a| 



 a| 
Apresentar o registo do histórico de dados da FRU
 a| 
`system fru log show` (nível de privilégio avançado)
 a| 
 a| 



 a| 
Apresentar o estado dos sensores ambientais, incluindo os respetivos estados e valores atuais
 a| 
`system sensors` ou `system sensors show`
 a| 
 a| 
`system node environment sensors show`



 a| 
Apresentar o estado e os detalhes do sensor especificado
 a| 
`system sensors get` `sensor_name`

Pode obter `sensor_name` utilizando o `system sensors` comando ou `system sensors show` .
 a| 
 a| 



 a| 
Exiba as informações da versão do firmware do SP
 a| 
`version`
 a| 
 a| 
`system service-processor image show`



 a| 
Exiba o histórico de comandos do SP
 a| 
`sp log audit` (nível de privilégio avançado)
 a| 
`bmc log audit`
 a| 



 a| 
Exiba as informações de depuração do SP
 a| 
`sp log debug` (nível de privilégio avançado)
 a| 
`bmc log debug` (nível de privilégio avançado)
 a| 



 a| 
Exiba o arquivo de mensagens do SP
 a| 
`sp log messages` (nível de privilégio avançado)
 a| 
`bmc log messages` (nível de privilégio avançado)
 a| 



 a| 
Apresentar as definições de recolha forense do sistema num evento de reposição do watchdog, apresentar as informações forenses do sistema recolhidas durante um evento de reposição do watchdog ou limpar as informações forenses do sistema recolhidas
 a| 
`system forensics`[`show`  `log dump` | | `log clear`]
 a| 
 a| 



 a| 
Inicie sessão na consola do sistema
 a| 
`system console`
 a| 
 a| 
`system node run-console`



 a| 
Você deve pressionar Ctrl-D para sair da sessão do console do sistema.



 a| 
Ligue ou desligue o nó ou execute um ciclo de alimentação (desligando e voltando a ligar)
 a| 
`system power` `on`
 a| 
 a| 
`system node power on` (nível de privilégio avançado)



 a| 
`system power` `off`
 a| 
 a| 



 a| 
`system power` `cycle`
 a| 
 a| 



 a| 
A alimentação em espera permanece ligada para manter o SP em funcionamento sem interrupção. Durante o ciclo de alimentação, ocorre uma breve pausa antes de ligar novamente a alimentação.

[NOTE]
====
Usar esses comandos para desligar ou desligar o nó pode causar um desligamento inadequado do nó (também chamado de _desligamento anormal_) e não substitui um desligamento gracioso usando o comando ONTAP `system node halt`.

====


 a| 
Crie um despejo de núcleo e redefina o nó
 a| 
`system core` [`-f`]

A `-f` opção força a criação de um despejo de núcleo e a redefinição do nó.
 a| 
 a| 
`system node coredump trigger`

(nível de privilégio avançado)



 a| 
Esses comandos têm o mesmo efeito que pressionar o botão de interrupção não masável (NMI) em um nó, causando um desligamento sujo do nó e forçando um despejo dos arquivos centrais ao interromper o nó. Esses comandos são úteis quando o ONTAP no nó é suspenso ou não responde a comandos como `system node shutdown` . Os arquivos de despejo de núcleo gerados são exibidos na saída do `system node coredump show` comando. O SP permanece operacional desde que a energia de entrada para o nó não seja interrompida.



 a| 
Reinicie o nó com uma imagem de firmware do BIOS especificada opcionalmente (primária, backup ou atual) para se recuperar de problemas como uma imagem corrompida do dispositivo de inicialização do nó
 a| 
`system reset` {`primary` | `backup` | `current`
 a| 
 a| 
`system node reset` com o `-firmware` {`primary` `backup`parâmetro | | | `current` (nível de privilégio avançado)

`system node reset`



 a| 
[NOTE]
====
Esta operação causa um desligamento anormal do nó.

====
Se nenhuma imagem de firmware do BIOS for especificada, a imagem atual será usada para a reinicialização. O SP permanece operacional desde que a energia de entrada para o nó não seja interrompida.



 a| 
Apresentar o estado da atualização automática do firmware da bateria ou ativar ou desativar a atualização automática do firmware da bateria na próxima inicialização do SP
 a| 
`system battery auto_update`[`status`  `enable` | | `disable`]

(nível de privilégio avançado)
 a| 
 a| 



 a| 
Compare a imagem atual do firmware da bateria com uma imagem de firmware especificada
 a| 
`system battery verify` [`image_URL`]

(nível de privilégio avançado)

Se `image_URL` não for especificado, a imagem padrão do firmware da bateria será usada para comparação.
 a| 
 a| 



 a| 
Atualize o firmware da bateria a partir da imagem no local especificado
 a| 
`system battery flash` `image_URL`

(nível de privilégio avançado)

Use este comando se o processo de atualização automática do firmware da bateria tiver falhado por algum motivo.
 a| 
 a| 



 a| 
Atualize o firmware do SP utilizando a imagem no local especificado
 a| 
`sp update` `image_URL image_URL` não deve exceder 200 carateres.
 a| 
`bmc update` `image_URL image_URL` não deve exceder 200 carateres.
 a| 
`system service-processor image update`



 a| 
Reinicie o SP
 a| 
`sp reboot`
 a| 
 a| 
`system service-processor reboot-sp`



 a| 
Apague o conteúdo flash do NVRAM
 a| 
`system nvram flash clear` (nível de privilégio avançado)

Este comando não pode ser iniciado quando a alimentação do controlador está desligada (`system power off`).
 a| 
 a| 



 a| 
Saia da CLI do SP
 a| 
`exit`
 a| 
 a| 

|===
Saiba mais sobre os comandos descritos neste procedimento no link:https://docs.netapp.com/us-en/ontap-cli/["Referência do comando ONTAP"^].
