---
permalink: system-admin/commands-manage-feature-licenses-reference.html 
sidebar: sidebar 
keywords: command, manage, license, cli, command, cluster, system, feature, usage, usage 
summary: Você pode usar os comandos de licença do sistema da CLI do ONTAP para gerenciar licenças de recursos para o cluster. Você usa os comandos de uso de recursos do sistema para monitorar o uso de recursos. 
---
= Comandos para gerenciar licenças
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar os comandos da CLI do ONTAP `system license` para gerenciar licenças de recursos para o cluster. Você usa os `system feature-usage` comandos para monitorar o uso de recursos.

A tabela a seguir lista alguns dos comandos CLI comuns para gerenciar licenças e links para as páginas de manual do comando para obter informações adicionais.

[cols="2,4"]
|===
| Se você quiser... | Use este comando... 


 a| 
Exiba todos os pacotes que exigem licenças e seu status de licença atual, incluindo o seguinte:

* O nome do pacote
* O método licenciado
* A data de validade, se aplicável

 a| 
link:https://docs.netapp.com/us-en/ontap-cli/system-license-show-status.html["show-status da licença do sistema"]



 a| 
Exibir ou remover licenças expiradas ou não utilizadas
 a| 
link:https://docs.netapp.com/us-en/ontap-cli/system-license-clean-up.html["limpeza da licença do sistema"]



 a| 
Exiba o resumo do uso de recursos no cluster por nó
 a| 
https://docs.netapp.com/us-en/ontap-cli/system-feature-usage-show-summary.html["show-resumo do uso de recursos do sistema"]



 a| 
Exiba o status de uso do recurso no cluster por nó e por semana
 a| 
https://docs.netapp.com/us-en/ontap-cli/system-feature-usage-show-history.html["histórico de exibição de uso de recursos do sistema"]



 a| 
Exibir o status do risco de direito de licença para cada pacote de licença
 a| 
https://docs.netapp.com/us-en/ontap-cli/system-license-entitlement-risk-show.html["show de risco de direitos de licença do sistema"]

|===
.Informações relacionadas
* link:../concepts/manual-pages.html["Referência do comando ONTAP"]
* link:https://kb.netapp.com/onprem/ontap/os/ONTAP_9.10.1_and_later_licensing_overview["artigo da base de conhecimento: ONTAP 9.10,1 e visão geral do licenciamento posterior"^]
* link:install-license-task.html["Use o Gerenciador do sistema para instalar um arquivo de licença do NetApp"]

