---
permalink: system-admin/control-system-health-alerts-concept.html 
sidebar: sidebar 
keywords: system, health, alert, customization, monitor, enable, disable 
summary: Você pode controlar quais alertas um monitor de integridade gera ativando e desativando as políticas de integridade do sistema que definem quando os alertas são acionados. Isso permite que você personalize o sistema de monitoramento de integridade para seu ambiente específico. 
---
= Saiba mais sobre a personalização do alerta de integridade do sistema ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode controlar quais alertas um monitor de integridade gera ativando e desativando as políticas de integridade do sistema que definem quando os alertas são acionados. Isso permite que você personalize o sistema de monitoramento de integridade para seu ambiente específico.

Você pode aprender o nome de uma política exibindo informações detalhadas sobre um alerta gerado ou exibindo definições de política para um monitor de integridade específico, nó ou ID de alerta.

Desativar políticas de saúde é diferente de suprimir alertas. Quando você suprime um alerta, ele não afeta o status de integridade do subsistema, mas o alerta ainda pode ocorrer.

Se você desabilitar uma política, a condição ou estado definido em sua expressão de regra de política não acionará mais um alerta.

.Exemplo de um alerta que você deseja desativar
Por exemplo, suponha que ocorra um alerta que não seja útil para você. Você usa o `system health alert show –instance` comando para obter o ID da política para o alerta. Você usa o ID da política no `system health policy definition show` comando para exibir informações sobre a política. Depois de analisar a expressão da regra e outras informações sobre a política, você decide desativar a política. Você usa o `system health policy definition modify` comando para desativar a política.

.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/system-health-alert-show.html["mostrar alerta de saúde do sistema"^]

