---
permalink: system-admin/customize-show-command-output-concept.html 
sidebar: sidebar 
keywords: method, customizing, show, command, output, fields 
summary: Quando você usa o parâmetro –instance com um comando show para exibir detalhes, a saída pode ser longa e incluir mais informações do que você precisa. O parâmetro –fields de um comando show permite exibir apenas as informações especificadas. 
---
= Métodos de personalização da saída do comando show usando campos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando você usa o `–instance` parâmetro com um `show` comando para exibir detalhes, a saída pode ser longa e incluir mais informações do que você precisa. O `–fields` parâmetro de um `show` comando permite exibir apenas as informações especificadas.

Por exemplo, é provável que a execução `volume show -instance` resulte em várias telas de informações. Você pode usar `volume show –fields` `_fieldname[,fieldname...]_` para personalizar a saída de modo que ela inclua apenas o campo ou campos especificados (além dos campos padrão que são sempre exibidos). Você pode usar `–fields ?` para exibir campos válidos para um `show` comando.

O exemplo a seguir mostra a diferença de saída entre o `–instance` parâmetro e o `–fields` parâmetro:

[listing]
----
cluster1::> volume show -instance

                                   Vserver Name: cluster1-1
                                    Volume Name: vol0
                                 Aggregate Name: aggr0
                                    Volume Size: 348.3GB
                             Volume Data Set ID: -
                      Volume Master Data Set ID: -
                                   Volume State: online
                                    Volume Type: RW
                                   Volume Style: flex
                                         ...
                          Space Guarantee Style: volume
                      Space Guarantee in Effect: true
                                         ...
Press <space> to page down, <return> for next line, or 'q' to quit...
...
cluster1::>

cluster1::> volume show -fields space-guarantee,space-guarantee-enabled

vserver  volume space-guarantee space-guarantee-enabled
-------- ------ --------------- -----------------------
cluster1-1 vol0   volume          true
cluster1-2 vol0   volume          true
vs1      root_vol
                  volume          true
vs2      new_vol
                  volume          true
vs2      root_vol
                  volume          true
...
cluster1::>
----