---
permalink: system-admin/download-nlf-task.html 
sidebar: sidebar 
keywords: install, license, convert, download, add, record, software, entitlement, keys, codes, cluster, administrator, nlf, ontap one 
summary: Se o seu sistema estiver executando o ONTAP 9.10,1 ou posterior, você poderá atualizar os arquivos de licença ou as chaves de licença de 28 carateres em sistemas existentes baixando o NLF para ONTAP One ou núcleo ONTAP a partir do site de suporte da NetApp. 
---
= Faça download dos arquivos de licença do NetApp (NLF) no site de suporte da NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se o seu sistema estiver executando o ONTAP 9.10,1 ou posterior, você poderá atualizar os arquivos de licença do pacote em sistemas existentes baixando o NLF para ONTAP One ou núcleo ONTAP a partir do site de suporte da NetApp.


NOTE: As licenças SnapMirror Cloud e SnapMirror S3 não estão incluídas no ONTAP One. Eles fazem parte do pacote de compatibilidade do ONTAP One, que você pode obter gratuitamente se você tiver o ONTAP One e link:../data-protection/install-snapmirror-cloud-license-task.html["solicite separadamente"]o .

.Passos
Você pode baixar arquivos de licença do ONTAP One para sistemas com pacotes de arquivos de licença do NetApp existentes e para sistemas com chaves de licença de 28 carateres que foram convertidas em arquivos de licença do NetApp em sistemas executando o ONTAP 9.10,1 e posterior. Por uma taxa, você também pode atualizar os sistemas do ONTAP base para o ONTAP One.

[role="tabbed-block"]
====
.Atualizar NLF existente
--
. Entre em Contato com sua equipe de vendas da NetApp e solicite o pacote de arquivos de licença que você deseja atualizar ou converter (por exemplo, ONTAP base para ONTAP One ou pacote básico e pacote de proteção de dados para ONTAP One).
+
Quando a sua solicitação for processada, você receberá um e-mail de netappsw@netapp.com com o assunto "notificação de Licenciamento de Software da NetApp para O número [SO Number]" e o e-mail incluirá um anexo em PDF que inclui o número de série da sua licença.

. Inicie sessão no link:https://mysupport.netapp.com/site/["Site de suporte da NetApp"^].
. Selecione *sistemas > licenças de software*.
. No menu, escolha *número de série*, insira o número de série que recebeu e clique em *Nova Pesquisa*.
. Localize o pacote de licenças que você deseja converter.
. Clique em *Get NetApp License File* para cada pacote de licença e baixe os NLFs quando estiverem disponíveis.
. link:../system-admin/install-license-task.html["Instale"] O arquivo ONTAP One.


--
.Atualize o NLF convertido da chave de licença
--
. Inicie sessão no link:https://mysupport.netapp.com/site/["Site de suporte da NetApp"^].
. Selecione *sistemas > licenças de software*.
. No menu, escolha *número de série*, insira o número de série do sistema e clique em *Nova Pesquisa*.
. Localize a licença que você deseja converter e, na coluna *elegibilidade*, clique em *verificar*.
. No *formulário de elegibilidade*, clique em *Generate licenses for 9,10.x and later*.
. Feche o *Verifique o formulário de elegibilidade*.
+
Você precisará esperar pelo menos 2 horas para que as licenças sejam geradas.

. Repita os passos 1 a 3.
. Localize a licença ONTAP One, clique em *obter ficheiro de licença NetApp* e escolha o método de entrega.
. link:../system-admin/install-license-task.html["Instale"] O arquivo ONTAP One.


--
====