---
permalink: system-admin/files-sent-event-triggered-autosupport-messages-concept.html 
sidebar: sidebar 
keywords: files, event, triggered, autosupport, message, troubleshoot, subsystem, problem 
summary: As mensagens AutoSupport acionadas por evento contêm apenas informações básicas e de solução de problemas de subsistemas associados ao evento que fez com que o AutoSupport gerasse a mensagem. Os dados específicos ajudam os parceiros de suporte e suporte da NetApp a solucionar o problema. 
---
= Arquivos enviados em mensagens AutoSupport acionadas por evento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As mensagens AutoSupport acionadas por evento contêm apenas informações básicas e de solução de problemas de subsistemas associados ao evento que fez com que o AutoSupport gerasse a mensagem. Os dados específicos ajudam os parceiros de suporte e suporte da NetApp a solucionar o problema.

O AutoSupport usa os seguintes critérios para controlar o conteúdo em mensagens AutoSupport acionadas por evento:

* Quais subsistemas estão incluídos
+
Os dados são agrupados em subsistemas, incluindo subsistemas comuns, como arquivos de log e subsistemas específicos, como RAID. Cada evento aciona uma mensagem que contém apenas os dados de subsistemas específicos.

* O nível de detalhe de cada subsistema incluído
+
Os dados para cada subsistema incluído são fornecidos em um nível básico ou de solução de problemas.



Você pode visualizar todos os eventos possíveis e determinar quais subsistemas estão incluídos nas mensagens sobre cada evento usando o `system node autosupport trigger show` comando com o `-instance` parâmetro.

Além dos subsistemas que são incluídos por padrão para cada evento, você pode adicionar subsistemas adicionais em um nível básico ou de solução de problemas usando o `system node autosupport trigger modify` comando.
