---
permalink: system-admin/generate-certificate-signing-request-cluster-task.html 
sidebar: sidebar 
keywords: generate, certificate, sign, request, cluster, csr, ca 
summary: 'Você pode usar o comando security certificate Generate-csr para gerar uma solicitação de assinatura de certificado (CSR). Depois de processar sua solicitação, a autoridade de certificação (CA) envia o certificado digital assinado.' 
---
= Gerar uma solicitação de assinatura de certificado para o cluster no ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o comando certificado de segurança `generate-csr` para gerar uma solicitação de assinatura de certificado (CSR). Depois de processar sua solicitação, a autoridade de certificação (CA) envia o certificado digital assinado.

.Antes de começar
Você deve ser um administrador de cluster ou um administrador de SVM para executar essa tarefa.

.Passos
. Gerar um CSR:
+
[source, cli]
----
security certificate generate-csr -common-name <FQDN_or_common_name> -size 512|1024|1536|2048 -country <country> -state <state> -locality <locality> -organization <organization> -unit <unit> -email-addr <email_of_contact> -hash-function SHA1|SHA256|MD5
----
+
Saiba mais sobre `security certificate generate-csr` o link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-generate-csr.html["Referência do comando ONTAP"^]na .

+
O comando a seguir cria uma CSR com uma chave privada de 2.048 bits gerada pela função de hash SHA256 para uso pelo grupo Software no departamento DE TI de uma empresa cujo nome comum personalizado é server1.companyname.com, localizada em Sunnyvale, Califórnia, EUA. O endereço de e-mail do administrador de Contatos do SVM é web@example.com. O sistema apresenta a CSR e a chave privada na saída.

+
[listing]
----
cluster1::>security certificate generate-csr -common-name
server1.companyname.com -size 2048 -country US -state California -
locality Sunnyvale -organization IT -unit Software -email-addr
web@example.com -hash-function SHA256
Certificate Signing Request :
-----BEGIN CERTIFICATE REQUEST-----
<certificate_value>
-----END CERTIFICATE REQUEST-----
Private Key :
24 | Administrator Authentication and RBAC
-----BEGIN RSA PRIVATE KEY-----
<key_value>
-----END RSA PRIVATE KEY-----
Note: Please keep a copy of your certificate request and private key
for future reference.
----
. Copie a solicitação de certificado da saída CSR e, em seguida, envie-a em formato eletrônico (como e-mail) para uma CA de terceiros confiável para assinatura.
+
Após processar sua solicitação, a CA envia o certificado digital assinado. Você deve manter uma cópia da chave privada e do certificado digital assinado pela CA.


