---
permalink: system-admin/health-alerts-autosupport-messages-events-concept.html 
sidebar: sidebar 
keywords: system, health, alerts, trigger, autosupport, ems, event, management, message, event 
summary: 'Os alertas de integridade do sistema acionam mensagens e eventos AutoSupport no sistema de Gestão de Eventos (EMS), permitindo-lhe monitorizar a integridade do sistema utilizando mensagens AutoSupport e o EMS, além de utilizar diretamente o sistema de monitorização de integridade.' 
---
= Como os alertas de saúde acionam mensagens e eventos do AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os alertas de integridade do sistema acionam mensagens e eventos AutoSupport no sistema de Gestão de Eventos (EMS), permitindo-lhe monitorizar a integridade do sistema utilizando mensagens AutoSupport e o EMS, além de utilizar diretamente o sistema de monitorização de integridade.

O sistema envia uma mensagem AutoSupport dentro de cinco minutos após um alerta. A mensagem AutoSupport inclui todos os alertas gerados desde a mensagem AutoSupport anterior, exceto para alertas que duplicam um alerta para o mesmo recurso e causa provável na semana anterior.

Alguns alertas não acionam mensagens AutoSupport. Um alerta não aciona uma mensagem AutoSupport se a sua política de integridade desativar o envio de mensagens AutoSupport. Por exemplo, uma política de integridade pode desativar as mensagens do AutoSupport por padrão porque o AutoSupport já gera uma mensagem quando o problema ocorre. Você pode configurar políticas para não acionar mensagens AutoSupport usando o `system health policy definition modify` comando.

Você pode ver uma lista de todas as mensagens AutoSupport acionadas por alerta enviadas na semana anterior usando o `system health autosupport trigger history show` comando.

Os alertas também acionam a geração de eventos para o EMS. Um evento é gerado cada vez que um alerta é criado e cada vez que um alerta é apagado.
