---
permalink: system-admin/health-monitors-concept.html 
sidebar: sidebar 
keywords: available, cluster, health, monitors, errors, detect, events, alerts, delete 
summary: Existem vários monitores de integridade que monitorizam diferentes partes de um cluster. Os monitores de integridade ajudam você a se recuperar de erros nos sistemas ONTAP detetando eventos, enviando alertas para você e excluindo eventos conforme eles forem claros. 
---
= Saiba mais sobre os monitores de integridade do cluster ONTAP disponíveis
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Existem vários monitores de integridade que monitorizam diferentes partes de um cluster. Os monitores de integridade ajudam você a se recuperar de erros nos sistemas ONTAP detetando eventos, enviando alertas para você e excluindo eventos conforme eles forem claros.

|===
| Nome do monitor de integridade (identificador) | Nome do subsistema (identificador) | Finalidade 


 a| 
Switch Ethernet
 a| 
Interrutor (estado do interrutor)
 a| 
O Monitor de integridade do comutador Ethernet ONTAP (CSHM) monitora o status dos switches de rede de cluster e armazenamento enquanto coleta logs para análise. Por padrão, o CSHM polls cada switch via SNMPv2c a cada 5 minutos para atualizar tabelas de recursos com informações sobre capacidade de suporte, status de monitoramento, sensores de temperatura, utilização de CPU, configurações de interface e conexões, redundância de switch de cluster e operações de ventilador e fonte de alimentação. Além disso, se configurado, o CSHM coleta logs via SSH/SCP a cada hora, que são enviados através do AutoSupport para análise posterior. Mediante solicitação, o CSHM também pode executar uma coleção de log de suporte técnico mais detalhada usando SSH/SCP.

link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-cshm/config-overview.html["Monitoramento de integridade do switch"^]Consulte para obter mais detalhes.



 a| 
MetroCluster Fabric
 a| 
Interrutor
 a| 
Monitora a topologia da malha de back-end de configuração do MetroCluster e deteta configurações incorretas, como cabeamento e zoneamento incorretos e falhas de ISL.



 a| 
MetroCluster Saúde
 a| 
Interconexão, RAID e armazenamento
 a| 
Monitora os adaptadores FC-VI, os adaptadores iniciador FC, os discos e agregados esquerdos e as portas entre clusters



 a| 
Conetividade do nó (nó-conexão)
 a| 
Operações ininterruptas de CIFS (CIFS-NDO)
 a| 
Monitora conexões SMB para operações ininterruptas com aplicações Hyper-V.



 a| 
Storage (conexão SAS)
 a| 
Monitora compartimentos, discos e adaptadores no nível do nó para ver os caminhos e as conexões apropriados.



 a| 
Sistema
 a| 
não aplicável
 a| 
Agrega informações de outros monitores de saúde.



 a| 
Conetividade do sistema (conexão do sistema)
 a| 
Storage (conexão SAS)
 a| 
Monitora as gavetas no nível do cluster para ver os caminhos apropriados para dois nós em cluster de HA.

|===