---
permalink: system-admin/health-monitors-concept.html 
sidebar: sidebar 
keywords: available, cluster, health, monitors, errors, detect, events, alerts, delete 
summary: Existem vários monitores de integridade que monitorizam diferentes partes de um cluster. Os monitores de integridade ajudam você a se recuperar de erros nos sistemas ONTAP detetando eventos, enviando alertas para você e excluindo eventos conforme eles forem claros. 
---
= Saiba mais sobre os monitores de integridade do cluster ONTAP disponíveis
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Existem vários monitores de integridade que monitorizam diferentes partes de um cluster. Os monitores de integridade ajudam você a se recuperar de erros nos sistemas ONTAP detetando eventos, enviando alertas para você e excluindo eventos conforme eles forem claros.

|===
| Nome do monitor de integridade (identificador) | Nome do subsistema (identificador) | Finalidade 


 a| 
Interrutor do cluster (interrutor do cluster)
 a| 
Interrutor (estado do interrutor)
 a| 
Monitora os switches de rede de cluster e os switches de rede de gerenciamento para temperatura, utilização, configuração de interface, redundância (somente switches de rede de cluster) e operação de ventilador e fonte de alimentação. O monitor de integridade do comutador de cluster comunica com os comutadores através do SNMP. SNMPv2c é a configuração padrão.

[NOTE]
====
A partir do ONTAP 9.2, este monitor pode detetar e reportar quando uma central de cluster foi reinicializada desde o último período de polling.

====


 a| 
MetroCluster Fabric
 a| 
Interrutor
 a| 
Monitora a topologia da malha de back-end de configuração do MetroCluster e deteta configurações incorretas, como cabeamento e zoneamento incorretos e falhas de ISL.



 a| 
MetroCluster Saúde
 a| 
Interconexão, RAID e armazenamento
 a| 
Monitora os adaptadores FC-VI, os adaptadores iniciador FC, os discos e agregados esquerdos e as portas entre clusters



 a| 
Conetividade do nó (nó-conexão)
 a| 
Operações ininterruptas de CIFS (CIFS-NDO)
 a| 
Monitora conexões SMB para operações ininterruptas com aplicações Hyper-V.



 a| 
Storage (conexão SAS)
 a| 
Monitora compartimentos, discos e adaptadores no nível do nó para ver os caminhos e as conexões apropriados.



 a| 
Sistema
 a| 
não aplicável
 a| 
Agrega informações de outros monitores de saúde.



 a| 
Conetividade do sistema (conexão do sistema)
 a| 
Storage (conexão SAS)
 a| 
Monitora as gavetas no nível do cluster para ver os caminhos apropriados para dois nós em cluster de HA.

|===