---
permalink: system-admin/license-types-licensed-method-concept.html 
sidebar: sidebar 
keywords: license, types, method, cluster, manage, install, add, nlf 
summary: A compreensão dos tipos de licença e do método licenciado ajuda a gerenciar as licenças em um cluster. 
---
= Tipos de licença e método licenciado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A compreensão dos tipos de licença e do método licenciado ajuda a gerenciar as licenças em um cluster.



== Tipos de licença

Um pacote pode ter um ou mais dos seguintes tipos de licença instalados no cluster. O `system license show` comando exibe o tipo ou tipos de licença instalados para um pacote.

* Licença (`license`padrão )
+
Uma licença padrão é uma licença de nó bloqueado. Ele é emitido para um nó com um número de série específico do sistema (também conhecido como _número de série do controlador_). Uma licença padrão é válida apenas para o nó que tem o número de série correspondente.

+
A instalação de uma licença padrão de bloqueio de nó dá direito a um nó à funcionalidade licenciada. Para que o cluster use a funcionalidade licenciada, pelo menos um nó deve ser licenciado para a funcionalidade. Pode estar fora de conformidade usar a funcionalidade licenciada em um nó que não tenha direito à funcionalidade.

* Licença local (`site`)
+
Uma licença de local não está vinculada a um número de série específico do sistema. Quando você instala uma licença de site, todos os nós no cluster têm direito à funcionalidade licenciada. O `system license show` comando exibe as licenças do site sob o número de série do cluster.

+
Se o cluster tiver uma licença de site e você remover um nó do cluster, o nó não carregará a licença de site com ele e não terá mais direito à funcionalidade licenciada. Se você adicionar um nó a um cluster que tenha uma licença de site, o nó terá automaticamente direito à funcionalidade concedida pela licença de site.

* Licença de avaliação (`demo`)
+
Uma licença de avaliação é uma licença temporária que expira após um determinado período de tempo (indicado pelo `system license show` comando). Ele permite que você experimente determinadas funcionalidades de software sem comprar um direito. É uma licença em todo o cluster e não está vinculada a um número de série específico de um nó.

+
Se o cluster tiver uma licença de avaliação para um pacote e você remover um nó do cluster, o nó não carregará a licença de avaliação com ele.





== Método licenciado

É possível instalar uma licença em todo o cluster (o `site` tipo ou `demo`) e uma licença de nó bloqueado (o `license` tipo) para um pacote. Portanto, um pacote instalado pode ter vários tipos de licença no cluster. No entanto, para o cluster, há apenas um método _licenciado_ para um pacote. O `licensed method` campo `system license status show` do comando exibe o direito que está sendo usado para um pacote. O comando determina o método licenciado da seguinte forma:

* Se um pacote tiver apenas um tipo de licença instalado no cluster, o tipo de licença instalada é o método licenciado.
* Se um pacote não tiver nenhuma licença instalada no cluster, o método licenciado será `none`.
* Se um pacote tiver vários tipos de licença instalados no cluster, o método licenciado será determinado na seguinte ordem de prioridade do tipo de licença--`site`, `license` e `demo`.
+
Por exemplo:

+
** Se você tiver uma licença de site, uma licença padrão e uma licença de avaliação para um pacote, o método licenciado para o pacote no cluster é `site`.
** Se você tiver uma licença padrão e uma licença de avaliação para um pacote, o método licenciado para o pacote no cluster é `license`.
** Se você tiver apenas uma licença de avaliação para um pacote, o método licenciado para o pacote no cluster é `demo`.



