---
permalink: system-admin/log-files-sent-autosupport-messages-concept.html 
sidebar: sidebar 
keywords: log, files, autosupport, message, technical, support, staff 
summary: As mensagens do AutoSupport podem conter vários arquivos de log-chave que permitem que a equipe de suporte técnico analise a atividade recente do sistema. 
---
= Arquivos de log enviados em mensagens do AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As mensagens do AutoSupport podem conter vários arquivos de log-chave que permitem que a equipe de suporte técnico analise a atividade recente do sistema.

Todos os tipos de mensagens do AutoSupport podem incluir os seguintes arquivos de log quando o subsistema arquivos de log está habilitado:

|===
| Ficheiro de registo | Quantidade de dados incluídos no arquivo 


 a| 
* Arquivos de log do `/mroot/etc/log/mlog/` diretório
* O ficheiro de registo DE MENSAGENS

 a| 
Somente novas linhas adicionadas aos logs desde a última mensagem AutoSupport até um máximo especificado. Isso garante que as mensagens do AutoSupport tenham dados exclusivos e relevantes, não sobrepostos.

(Os arquivos de log de parceiros são a exceção; para parceiros, os dados máximos permitidos são incluídos.)



 a| 
* Arquivos de log do `/mroot/etc/log/shelflog/` diretório
* Arquivos de log do `/mroot/etc/log/acp/` diretório
* Dados de registo do sistema de gestão de eventos (EMS)

 a| 
As linhas de dados mais recentes até um máximo especificado.

|===
O conteúdo das mensagens do AutoSupport pode mudar entre as versões do ONTAP.
