---
permalink: system-admin/manage-core-dumps-concept.html 
sidebar: sidebar 
keywords: manage, core, dump, cluster, administrator, node, panic, configure, attributes, save, display, segment, upload, delete 
summary: Você pode configurar ou exibir atributos de despejo de núcleo do nó e gerenciar arquivos de despejo de núcleo do nó. 
---
= Gerenciar despejos de núcleo de nós para um cluster ONTAP (somente administradores de cluster)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando um nó entra em pânico, um despejo de núcleo ocorre e o sistema cria um arquivo de despejo de núcleo que o suporte técnico pode usar para solucionar o problema. Você pode configurar ou exibir atributos de despejo de memória. Você também pode salvar, exibir, segmentar, carregar ou excluir um arquivo de despejo de memória.

Você pode gerenciar despejos principais das seguintes maneiras:

* Configurar os despejos principais e exibir as configurações
* Exibindo informações básicas, o status e os atributos dos despejos principais
+
Os arquivos e relatórios de despejo de memória são armazenados `/mroot/etc/crash/` no diretório de um nó. Você pode exibir o conteúdo do diretório usando os `system node coredump` comandos ou um navegador da Web.

* Salvando o conteúdo do despejo do núcleo e carregando o arquivo salvo em um local especificado ou no suporte técnico
+
O ONTAP impede que você inicie o salvamento de um arquivo de despejo de memória durante uma aquisição, uma realocação agregada ou um giveback.

* Excluindo arquivos de despejo de memória que não são mais necessários




== Comandos para gerenciar despejos principais

Você usa os `system node coredump config` comandos para gerenciar a configuração de despejos de núcleo, os `system node coredump` comandos para gerenciar os arquivos de despejo de núcleo e os `system node coredump reports` comandos para gerenciar relatórios de núcleo de aplicativos.

Saiba mais sobre os comandos descritos neste tópico no link:https://docs.netapp.com/us-en/ontap-cli/["Referência do comando ONTAP"].

|===
| Se você quiser... | Use este comando... 


 a| 
Configurar despejos de núcleo
 a| 
`system node coredump config modify`



 a| 
Apresentar as definições de configuração para despejos de núcleo
 a| 
`system node coredump config show`



 a| 
Exibir informações básicas sobre despejos de núcleo
 a| 
`system node coredump show`



 a| 
Acione manualmente um despejo de memória quando você reiniciar um nó
 a| 
`system node reboot` com ambos `-dump` os parâmetros e `-skip-lif-migration-before-reboot`

[NOTE]
====
O parâmetro link:https://docs.NetApp.com/US-en/ONTAP-cli//system-node-reboot.html[`skip-lif-migration-before-reboot` especifica que a migração de LIF antes de uma reinicialização será ignorada.

====


 a| 
Acione manualmente um despejo de núcleo quando você desligar um nó
 a| 
`system node halt` com ambos `-dump` os parâmetros e `-skip-lif-migration-before-shutdown`

[NOTE]
====
O parâmetro link:https://docs.NetApp.com/US-en/ONTAP-cli/system-node-halt.html[`skip-lif-migration-before-shutdown` especifica que a migração de LIF antes de um desligamento será ignorada.

====


 a| 
Salve um despejo de memória especificado
 a| 
`system node coredump save`



 a| 
Salve todos os despejos de núcleo não salvos que estão em um nó especificado
 a| 
`system node coredump save-all`



 a| 
Gere e envie uma mensagem AutoSupport com um arquivo de despejo de memória que você especificar
 a| 
`system node autosupport invoke-core-upload`

[NOTE]
====
O `-uri` parâmetro opcional especifica um destino alternativo para a mensagem AutoSupport.

====


 a| 
Exibir informações de status sobre os despejos do núcleo
 a| 
`system node coredump status`



 a| 
Exclua um despejo de memória especificado
 a| 
`system node coredump delete`



 a| 
Exclua todos os despejos de núcleo não salvos ou todos os arquivos de núcleo salvos em um nó
 a| 
`system node coredump delete-all`



 a| 
Exibir relatórios de despejo do núcleo do aplicativo
 a| 
`system node coredump reports show`



 a| 
Excluir um relatório de despejo do núcleo do aplicativo
 a| 
`system node coredump reports delete`

|===
.Informações relacionadas
link:../concepts/manual-pages.html["Referência do comando ONTAP"]
