---
permalink: system-admin/manage-banner-reference.html 
sidebar: sidebar 
keywords: manage, banner, svm, cluster, configure 
summary: É possível gerenciar o banner no nível do cluster ou SVM. O banner configurado para o cluster também é usado para todos os SVMs que não têm uma mensagem de banner definida. Um banner criado posteriormente para um SVM substitui o banner do cluster para esse SVM. 
---
= Gerenciar o banner
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível gerenciar o banner no nível do cluster ou SVM. O banner configurado para o cluster também é usado para todos os SVMs que não têm uma mensagem de banner definida. Um banner criado posteriormente para um SVM substitui o banner do cluster para esse SVM.

.Opções
* Gerencie o banner no nível do cluster:
+
|===
| Se você quiser... | Então... 


 a| 
Crie um banner para exibir todas as sessões de login da CLI
 a| 
Definir um banner no nível do cluster:

`*security login banner modify -vserver _cluster_name_ { [-message "text"] | [_-uri ftp_or_http_addr_] }*`



 a| 
Remova o banner para todos os logins (cluster e SVM)
 a| 
Defina o banner para uma string vazia (`""`):

`*security login banner modify -vserver * -message ""*`



 a| 
Substituir um banner criado por um administrador SVM
 a| 
Modifique a mensagem de banner SVM:

`*security login banner modify -vserver _svm_name_ { [-message "_text_"] | [-uri _ftp_or_http_addr_] }*`

|===
* Gerencie o banner no nível da SVM:
+
Não é necessário especificar `-vserver _svm_name_` no contexto SVM.

+
|===
| Se você quiser... | Então... 


 a| 
Substitua o banner fornecido pelo administrador do cluster por um banner diferente para o SVM
 a| 
Crie um banner para o SVM:

`*security login banner modify -vserver _svm_name_ { [-message "text"] | [-uri ftp_or_http_addr] }*`



 a| 
Suprimir o banner fornecido pelo administrador do cluster para que nenhum banner seja exibido para o SVM
 a| 
Defina o banner SVM para uma cadeia vazia para o SVM:

`*security login banner modify -vserver _svm_name_ -message ""*`



 a| 
Use o banner no nível do cluster quando o SVM usar um banner no nível da SVM
 a| 
Defina o banner SVM como `"-"`:

`*security login banner modify -vserver _svm_name_ -message "-"*`

|===

