---
permalink: system-admin/manage-ssl-concept.html 
sidebar: sidebar 
keywords: manage, command, ssl, cluster, storage, svm, security, web, access, digital, certificate, encrypted, connection, server, browser 
summary: Use comandos ssl para gerenciar o protocolo SSL para melhorar a segurança do acesso à Web usando um certificado digital para estabelecer uma conexão criptografada. 
---
= Gerenciar SSL no ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Use os `security ssl` comandos para gerenciar o protocolo SSL para o cluster ou uma máquina virtual de armazenamento (SVM). O protocolo SSL melhora a segurança do acesso à Web usando um certificado digital para estabelecer uma conexão criptografada entre um servidor da Web e um navegador.

Você pode gerenciar SSL para o cluster ou uma máquina virtual de armazenamento (SVM) das seguintes maneiras:

* Ativar SSL
* Gerar e instalar um certificado digital e associá-lo ao cluster ou SVM
* Exibindo a configuração SSL para ver se o SSL foi ativado e, se disponível, o nome do certificado SSL
* Configuração de políticas de firewall para o cluster ou SVM, para que as solicitações de acesso à Web possam passar
* Definir quais versões SSL podem ser usadas
* Restringindo o acesso apenas a solicitações HTTPS para um serviço da Web




== Comandos para gerenciar SSL

Use os `security ssl` comandos para gerenciar o protocolo SSL para o cluster ou uma máquina virtual de armazenamento (SVM).

|===
| Se você quiser... | Use este comando... 


 a| 
Ative o SSL para o cluster ou um SVM e associe um certificado digital a ele
 a| 
`security ssl modify`



 a| 
Exiba a configuração SSL e o nome do certificado para o cluster ou um SVM
 a| 
`security ssl show`

|===
Saiba mais sobre `security ssl modify` e `security ssl show` no link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+ssl["Referência do comando ONTAP"^].
