---
permalink: system-admin/manage-licenses-concept.html 
sidebar: sidebar 
keywords: manage, license, ontap one, enable, add, record, software, entitlement, keys, codes, risk, usage, cluster, administrator, nlf, bundle 
summary: 'Uma licença é um Registro de um ou mais direitos de software. A partir do ONTAP 9.10,1, todas as licenças são entregues como um arquivo de licença NetApp (NLF), que é um único arquivo que permite vários recursos. A partir de maio de 2023, todos os sistemas AFF (Série A e série C) e FAS são vendidos com o pacote de software ONTAP One ou o pacote de software ONTAP base e, a partir de junho de 2023, todos os sistemas ASA são vendidos com o ONTAP One para SAN.' 
---
= Visão geral do licenciamento do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Uma licença é um Registro de um ou mais direitos de software. A partir do ONTAP 9.10,1, todas as licenças são entregues como um arquivo de licença NetApp (NLF), que é um único arquivo que permite vários recursos. A partir de maio de 2023, todos os sistemas AFF (Série A e série C) e FAS são vendidos com o pacote de software ONTAP One ou o pacote de software ONTAP base e, a partir de junho de 2023, todos os sistemas ASA são vendidos com o ONTAP One para SAN. Cada pacote de software é fornecido como um único NLF, substituindo os pacotes NLF separados introduzidos pela primeira vez no ONTAP 9.10,1.



== Licenças incluídas no ONTAP One

O ONTAP One contém todas as funcionalidades licenciadas disponíveis. Ele contém uma combinação do conteúdo do antigo pacote Core, do pacote Data Protection, do pacote Security and Compliance, do pacote Hybrid Cloud e do pacote Encryption, conforme mostrado na tabela. A criptografia não está disponível em países restritos.

|===


| Nome antigo do pacote | Chaves ONTAP incluídas 


.5+| Pacote básico | FlexClone 


| SnapRestore 


| NFS, SMB, S3 


| FC, iSCSI 


| NVMe-of 


.3+| Pacote de segurança e conformidade | Proteção autônoma contra ransomware 


| MTKM 


| SnapLock 


.3+| Pacote de proteção de dados | SnapMirror (sincronização assíncrona, síncrona, ativa) 


| SnapCenter 


| SnapMirror S3 para alvos NetApp 


.2+| Pacote de nuvem híbrida | Nuvem da SnapMirror 


| SnapMirror S3 para alvos não-NetApp 


.2+| Pacote de criptografia | Criptografia de volume do NetApp 


| Módulo Plataforma confiável 
|===


== Licenças não incluídas no ONTAP One

O ONTAP One não inclui nenhum dos serviços fornecidos em nuvem da NetApp, incluindo o seguinte:

* Disposição em camadas do BlueXP  (anteriormente conhecida como disposição em camadas na nuvem)
* Cloud Insights
* Backup BlueXP 
* Governança de dados




== ONTAP One para sistemas existentes

Se você tiver sistemas existentes que estão atualmente sob suporte do NetApp, mas não foram atualizados para o ONTAP One, as licenças existentes nesses sistemas ainda serão válidas e continuarão funcionando conforme esperado. Por exemplo, se a licença SnapMirror já estiver instalada em sistemas existentes, não será necessário atualizar para o ONTAP One para obter uma nova licença SnapMirror. No entanto, se você não tiver uma licença SnapMirror instalada em um sistema existente, a única maneira de obter essa licença é atualizar para o ONTAP One por uma taxa adicional.

A partir de junho de 2023, os sistemas ONTAP que usam chaves de licença de 28 carateres também podem link:https://kb.netapp.com/onprem/ontap/os/How_to_get_an_ONTAP_One_license_when_the_system_has_28_character_keys["Atualize para o pacote de compatibilidade ONTAP One ou ONTAP base"].



== Licenças incluídas no ONTAP base

O ONTAP base é um pacote de software opcional que é uma alternativa ao ONTAP One para sistemas ONTAP. Ele é para casos de uso específicos em que não são necessárias tecnologias de proteção de dados, como o SnapMirror e o SnapCenter, bem como recursos de segurança, como o Autonomous ransomware, como sistemas não produtivos para ambientes dedicados de teste ou desenvolvimento. Licenças adicionais não podem ser adicionadas ao ONTAP base. Se você quiser licenças adicionais, como o SnapMirror, você deve atualizar para o ONTAP One.

|===


| Nome antigo do pacote | Chaves ONTAP incluídas 


.5+| Pacote básico | FlexClone 


| SnapRestore 


| NFS, SMB, S3 


| FC, iSCSI 


| NVMe-of 


.2+| Pacote de criptografia | Criptografia de volume do NetApp 


| Módulo Plataforma confiável 
|===


== Licenças incluídas no ONTAP One para SAN

O ONTAP One para SAN está disponível para sistemas ASA da série A e série C. Este é o único pacote de software disponível para SAN. O ONTAP One para SAN contém as seguintes licenças:

|===


| Chaves ONTAP incluídas 


| FlexClone 


| SnapRestore 


| FC, iSCSI 


| NVMe-of 


| MTKM 


| SnapLock 


| SnapMirror (sincronização assíncrona, síncrona, ativa) 


| SnapCenter 


| Nuvem da SnapMirror 


| Criptografia de volume do NetApp 


| Módulo Plataforma confiável 
|===


== Outros métodos de entrega de licenças

No ONTAP 8,2 até ONTAP 9.9,1, as chaves de licença são entregues como strings de 28 carateres, e há uma chave por recurso ONTAP. Você usa a CLI do ONTAP para instalar chaves de licença se estiver usando o ONTAP 8,2 através do ONTAP 9.9,1.

[NOTE]
====
O ONTAP 9.10,1 suporta a instalação de chaves de licença de 28 carateres usando o Gerenciador do sistema ou a CLI. No entanto, se uma licença NLF for instalada para um recurso, você não poderá instalar uma chave de licença de 28 carateres sobre o arquivo de licença NetApp para o mesmo recurso. Para obter informações sobre como instalar NLFs ou chaves de licença usando o System Manager, link:../system-admin/install-license-task.html["Instalar licenças ONTAP"]consulte .

====
.Informações relacionadas
https://kb.netapp.com/onprem/ontap/os/How_to_get_an_ONTAP_One_license_when_the_system_has_NLFs_already["Como obter uma licença ONTAP One quando o sistema já tiver NLFs"]

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_verify_Data_ONTAP_Software_Entitlements_and_related_License_Keys_using_the_Support_Site["Como verificar os direitos do software ONTAP e as chaves de licença relacionadas usando o site de suporte"^]

http://mysupport.netapp.com/licensing/ontapentitlementriskstatus["NetApp: Status de risco de direito do ONTAP"^]
