---
permalink: system-admin/manage-autosupport-concept.html 
sidebar: sidebar 
keywords: manage, autosupport, support, technical, message 
summary: O AutoSupport é um mecanismo que monitora proativamente a integridade do sistema e envia mensagens automaticamente para o suporte técnico da NetApp, sua organização de suporte interno e um parceiro de suporte. Embora as mensagens do AutoSupport para suporte técnico estejam habilitadas por padrão, você deve definir as opções corretas e ter um host de e-mail válido para que as mensagens sejam enviadas para sua organização interna de suporte. 
---
= Saiba mais sobre o ONTAP AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O AutoSupport é um mecanismo que monitora proativamente a integridade do sistema e envia mensagens automaticamente para o suporte técnico da NetApp, sua organização de suporte interno e um parceiro de suporte. Embora as mensagens do AutoSupport para suporte técnico estejam habilitadas por padrão, você deve definir as opções corretas e ter um host de e-mail válido para que as mensagens sejam enviadas para sua organização interna de suporte.

Somente o administrador do cluster pode executar o gerenciamento do AutoSupport. O administrador da máquina virtual de storage (SVM) não tem acesso ao AutoSupport.

O AutoSupport é ativado por padrão quando você configura o sistema de storage pela primeira vez. O AutoSupport começa a enviar mensagens para o suporte técnico 24 horas após a ativação do AutoSupport. Você pode encurtar o período de 24 horas atualizando ou revertendo o sistema, modificando a configuração do AutoSupport ou alterando o tempo do sistema para ser algo diferente de um período de 24 horas.

[NOTE]
====
Você pode desativar o AutoSupport a qualquer momento, mas deve deixá-lo habilitado. A ativação do AutoSupport pode ajudar a acelerar significativamente a determinação e a resolução de problemas em caso de problema no sistema de storage. Por padrão, o sistema coleta informações do AutoSupport e as armazena localmente, mesmo que você desative o AutoSupport.

====
Para obter mais informações sobre o AutoSupport, consulte o site de suporte da NetApp.

.Informações relacionadas
* https://support.netapp.com/["Suporte à NetApp"^]
* link:../concepts/manual-pages.html["Referência do comando ONTAP"]

