---
permalink: system-admin/manage-web-services-concept.html 
sidebar: sidebar 
keywords: manage, web, services, svm, storage, virtual, machine, cluster, controller, user 
summary: 'Você pode ativar ou desativar um serviço da Web para o cluster ou uma máquina virtual de armazenamento (SVM), exibir as configurações de serviços da Web e controlar se os usuários de uma função podem acessar um serviço da Web.' 
---
= Gerencie a visão geral dos serviços da Web
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode ativar ou desativar um serviço da Web para o cluster ou uma máquina virtual de armazenamento (SVM), exibir as configurações de serviços da Web e controlar se os usuários de uma função podem acessar um serviço da Web.

Você pode gerenciar os serviços da Web para o cluster ou uma SVM das seguintes maneiras:

* Ativar ou desativar um serviço Web específico
* Especificar se o acesso a um serviço da Web é restrito apenas a HTTP encriptado (SSL)
* Exibindo a disponibilidade de serviços da Web
* Permitir ou não permitir que usuários de uma função acessem um serviço da Web
* Exibindo as funções que têm permissão para acessar um serviço da Web


Para que um usuário acesse um serviço da Web, todas as seguintes condições devem ser atendidas:

* O usuário deve ser autenticado.
+
Por exemplo, um serviço da Web pode solicitar um nome de usuário e uma senha. A resposta do usuário deve corresponder a uma conta válida.

* O utilizador tem de ser configurado com o método de acesso correto.
+
A autenticação só é bem-sucedida para os usuários com o método de acesso correto para o serviço web fornecido. Para o serviço Web da API ONTAP  `ontapi`), os usuários devem ter o `ontapi` método de acesso. Para todos os outros serviços da Web, os usuários devem ter o `http` método de acesso.

+
[NOTE]
====
Você usa os `security login` comandos para gerenciar os métodos de acesso e os métodos de autenticação dos usuários.

====
* O serviço Web deve ser configurado para permitir a função de controle de acesso do usuário.
+
[NOTE]
====
Você usa os `vserver services web access` comandos para controlar o acesso de uma função a um serviço da Web.

====


Se um firewall estiver ativado, a política de firewall para o LIF a ser usado para serviços da Web deve ser configurada para permitir HTTP ou HTTPS.

Se você usar HTTPS para acesso ao serviço da Web, o SSL para o cluster ou SVM que ofereça o serviço da Web também deverá estar habilitado e fornecer um certificado digital para o cluster ou SVM.
