---
permalink: system-admin/methods-view-command-history-concept.html 
sidebar: sidebar 
keywords: method, view, command, history, reissue, command 
summary: Cada sessão CLI mantém um histórico de todos os comandos emitidos nela. Você pode ver o histórico de comandos da sessão em que está atualmente. Você também pode reemitir comandos. 
---
= Visualize o histórico de comandos do ONTAP e execute novamente qualquer comando do histórico
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada sessão CLI mantém um histórico de todos os comandos emitidos nela. Você pode ver o histórico de comandos da sessão em que está atualmente. Você também pode reemitir comandos.

Para visualizar o histórico de comandos, pode utilizar o `history` comando.

Para reemitir um comando, você pode usar o `redo` comando com um dos seguintes argumentos:

* Uma cadeia de carateres que corresponde a parte de um comando anterior
+
Por exemplo, se o único `volume` comando executado for `volume show`, você poderá usar o `redo volume` comando para reexecutar o comando.

* O ID numérico de um comando anterior, conforme listado pelo `history` comando
+
Por exemplo, você pode usar o `redo 4` comando para reemitir o quarto comando na lista de histórico.

* Um desvio negativo a partir do final da lista de histórico
+
Por exemplo, você pode usar o `redo -2` comando para reemitir o comando que você executou dois comandos atrás.



Por exemplo, para refazer o comando que está em terceiro lugar do final do histórico de comandos, digite o seguinte comando:

[listing]
----
cluster1::> redo -3
----
.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/history.html["história"^]
* link:https://docs.netapp.com/us-en/ontap-cli/redo.html["refazer"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume["volume"^]

