---
permalink: system-admin/online-help-at-sp-bmc-cli-task.html 
sidebar: sidebar 
keywords: online, help, sp, bmc, cli, command 
summary: A ajuda on-line exibe os comandos e opções da CLI do SP/BMC. 
---
= Veja as informações de ajuda na CLI do ONTAP SP/BMC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A ajuda on-line exibe os comandos e opções da CLI do SP/BMC.

.Sobre esta tarefa
Esta tarefa aplica-se tanto ao SP como ao BMC.

.Passos
. Para exibir informações de ajuda para os comandos SP/BMC, digite o seguinte:
+
|===
| Para acessar a ajuda do SP... | Para acessar a ajuda do BMC... 


 a| 
Digite `help` no prompt SP.
 a| 
Digite `system` no prompt BMC.

|===
+
O exemplo a seguir mostra a ajuda online da CLI do SP.

+
[listing]
----
SP> help
date - print date and time
exit - exit from the SP command line interface
events - print system events and event information
help - print command help
priv - show and set user mode
sp - commands to control the SP
system - commands to control the system
version - print SP version
----
+
O exemplo a seguir mostra a ajuda online da CLI do BMC.

+
[listing]
----
BMC> system
system acp - acp related commands
system battery - battery related commands
system console - connect to the system console
system core - dump the system core and reset
system cpld - cpld commands
system log - print system console logs
system power - commands controlling system power
system reset - reset the system using the selected firmware
system sensors - print environmental sensors status
system service-event - print service-event status
system fru - fru related commands
system watchdog - system watchdog commands

BMC>
----
. Para exibir informações de ajuda para a opção de um comando SP/BMC, digite `help` antes ou depois do comando SP/BMC.
+
O exemplo a seguir mostra a ajuda online da CLI do SP para o comando SP `events`.

+
[listing]
----
SP> help events
events all - print all system events
events info - print system event log information
events newest - print newest system events
events oldest - print oldest system events
events search - search for and print system events
----
+
O exemplo a seguir mostra a ajuda online da CLI do BMC para o comando BMC `system power`.

+
[listing]
----
BMC> system power help
system power cycle - power the system off, then on
system power off - power the system off
system power on - power the system on
system power status - print system power status

BMC>
----


Saiba mais sobre os comandos descritos neste procedimento no link:https://docs.netapp.com/us-en/ontap-cli/["Referência do comando ONTAP"^].

.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=events["eventos"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+power["alimentação do sistema"^]

