---
permalink: system-admin/receive-system-health-alerts-automatic-task.html 
sidebar: sidebar 
keywords: receive, system, health, alert, automatically, system, show, command, ems, event, management, monito 
summary: 'Você pode visualizar manualmente os alertas de integridade do sistema usando o comando show de alerta de integridade do sistema. No entanto, você deve assinar mensagens específicas do sistema de Gerenciamento de Eventos (EMS) para receber notificações automaticamente quando um monitor de integridade gera um alerta.' 
---
= Receber alertas de integridade do sistema ONTAP automaticamente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode visualizar manualmente os alertas de integridade do sistema usando o `system health alert show` comando. No entanto, você deve assinar mensagens específicas do sistema de Gerenciamento de Eventos (EMS) para receber notificações automaticamente quando um monitor de integridade gera um alerta.

.Sobre esta tarefa
O procedimento a seguir mostra como configurar notificações para todas as mensagens hm.alert.raised e todas as mensagens hm.alert.cleared.

Todas as mensagens hm.alert.raised e todas as mensagens hm.alert.cleared incluem um trap SNMP. Os nomes dos traps SNMP são `HealthMonitorAlertRaised` e `HealthMonitorAlertCleared`.

Saiba mais sobre `system health alert show` o link:https://docs.netapp.com/us-en/ontap-cli/system-health-alert-show.html["Referência do comando ONTAP"^]na .

.Passos
. Utilize o `event destination create` comando para definir o destino para o qual pretende enviar as mensagens EMS.
+
[listing]
----
cluster1::> event destination create -name health_alerts -mail admin@example.com
----
+
Saiba mais sobre `event destination create` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=event+destination+create["Referência do comando ONTAP"^]na .

. Utilize o `event route add-destinations` comando para encaminhar a `hm.alert.raised` mensagem e a `hm.alert.cleared` mensagem para um destino.
+
[listing]
----
cluster1::> event route add-destinations -messagename hm.alert* -destinations health_alerts
----
+
Saiba mais sobre `event route add-destinations` o link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=event+route+add-destinations["Referência do comando ONTAP"^]na .



.Informações relacionadas
* link:../networking/networking_reference.html["Visualize a rede ONTAP usando o Gerenciador do sistema"^]
* link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_SNMP_monitoring_on_DATA_ONTAP["Como configurar o monitoramento SNMP no DATA ONTAP"^]

