---
permalink: system-admin/remove-nodes-cluster-concept.html 
sidebar: sidebar 
keywords: remove, node, cluster, failover, partner, erase, inaccessible 
summary: Você pode remover nós indesejados de um cluster, um nó de cada vez. Depois de remover um nó, você também deve remover o parceiro de failover. Se você estiver removendo um nó, seus dados ficarão inacessíveis ou apagados. 
---
= Remover nós de um cluster do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode remover nós indesejados de um cluster, um nó de cada vez. Depois de remover um nó, você também deve remover o parceiro de failover. Se você estiver removendo um nó, seus dados ficarão inacessíveis ou apagados.

.Antes de começar
Você deve atender às seguintes condições antes de remover nós do cluster:

* Mais da metade dos nós no cluster precisa estar saudável.
* Todos os dados, volumes e agregados não raiz devem ser realocados ou removidos do nó.
+
** Todos os dados no nó que você deseja remover devem ter sido evacuados. Isso pode incluir link:../encryption-at-rest/secure-purge-data-encrypted-volume-concept.html["limpando dados de um volume criptografado"].
** Todos os volumes que não são raiz link:../volumes/move-volume-task.html["movido"]foram de agregados pertencentes ao nó.
** Todos os agregados que não são root foram link:../disks-aggregates/commands-manage-aggregates-reference.html["eliminado"]do nó.


* Todas as LIFs e VLANs foram relocadas ou removidas do nó.
+
** Os LIFs de dados foram link:../networking/delete_a_lif.html["eliminado"] ou link:../networking/migrate_a_lif.html["relocado"] do nó.
** As LIFs de gerenciamento de cluster foram link:../networking/migrate_a_lif.html["relocado"]do nó e as portas iniciais foram alteradas.
** Todos os LIFs entre clusters foram link:../networking/delete_a_lif.html["removido"]. Ao remover LIFs entre clusters, é exibido um aviso que pode ser ignorado.
** Todas as VLANs no nó foram link:../networking/configure_vlans_over_physical_ports.html#delete-a-vlan["eliminado"].


* O nó não está participando de nenhum relacionamento de failover.
+
** O failover de storage link:../high-availability/ha_commands_for_enabling_and_disabling_storage_failover.html["desativado"]foi para o nó.
** Todas as regras de failover de LIF foram link:../networking/commands_for_managing_failover_groups_and_policies.html["modificado"] para remover portas no nó.


* Se o nó possuir discos FIPS (Federal Information Processing Standards) ou SEDs (Self-Encrypting Disks)link:../encryption-at-rest/return-seds-unprotected-mode-task.html["a criptografia de disco foi removida"], retornando os discos para o modo desprotegido.
+
** Você também pode querer link:../encryption-at-rest/sanitize-fips-drive-sed-task.html["Higienizar unidades FIPS ou SEDs"].


* Se você tiver LUNs no nó a ser removido, você deve link:../san-admin/modify-slm-reporting-nodes-task.html["Modifique a lista de nós de relatório do mapa LUN seletivo (SLM)"] antes de remover o nó.
+
Se você não remover o nó e seu parceiro de HA da lista de nós de relatórios do SLM, o acesso às LUNs anteriormente no nó poderá ser perdido mesmo que os volumes que contêm as LUNs tenham sido movidos para outro nó.



Recomenda-se que você emita uma mensagem do AutoSupport para notificar o suporte técnico da NetApp de que a remoção do nó está em andamento.


IMPORTANT: Não execute operações como `cluster remove-node` , `cluster unjoin` e `node rename` quando uma atualização automática do ONTAP estiver em andamento.

.Sobre esta tarefa
* Se você estiver executando um cluster de versão mista, poderá remover o último nó de versão baixa usando um dos comandos de privilégio avançados que começam com ONTAP 9.3:
+
** ONTAP 9.3: `cluster unjoin -skip-last-low-version-node-check`
** ONTAP 9 .4 e posterior: `cluster remove-node -skip-last-low-version-node-check`


* Se você remover dois nós de um cluster de quatro nós, o HA do cluster será ativado automaticamente nos dois nós restantes.


[NOTE]
====
Todos os dados do sistema e dados de usuário, de todos os discos conectados ao nó, devem ser tornados inacessíveis aos usuários antes de remover um nó do cluster.

Caso um nó tenha sido removido incorretamente de um cluster, entre em contato com o Suporte da NetApp para obter assistência com as opções de recuperação.

====
[[disable-ha]]
.Passos
. Altere o nível de privilégio para avançado:
+
[source, cli]
----
set -privilege advanced
----
. Identifique o nó no cluster que possui epsilon:
+
[source, cli]
----
cluster show
----
+
No exemplo a seguir, "node0" atualmente contém epsilon:

+
[listing]
----
cluster::*>
Node                 Health  Eligibility  Epsilon
-------------------- ------- ------------ ------------
node0                true    true         true
node1                true    true         false
node2                true    true         false
node3                true    true         false
----
. [[epsilon-true]]Se o nó que você está removendo contém epsilon:
+
.. Mova o epsilon do nó que você está removendo:
+
[source, cli]
----
cluster modify -node <name_of_node_to_be_removed> -epsilon false
----
.. Mova epsilon para um nó que você não está removendo:
+
[source, cli]
----
cluster modify -node <node_name> -epsilon true
----


. Identificar o nó principal atual:
+
[source, cli]
----
cluster ring show
----
+
O nó principal é o nó que contém processos como `mgmt` , `vldb`, , `vifmgr`, `bcomd` `crs` e .

. Se o nó que você está removendo for o nó mestre atual, habilite outro nó no cluster para ser eleito como o nó mestre:
+
.. Torne o nó principal atual inelegível para participar do cluster:
+
[source, cli]
----
cluster modify -node <node_name> -eligibility false
----
+
O nó é marcado como não íntegro até que a elegibilidade seja restaurada. Quando o nó mestre se torna inelegível, um dos nós restantes é eleito pelo quórum do cluster como o novo mestre.

+
[NOTE]
====
Se você estiver executando esta etapa no primeiro nó de um par de HA, você deve marcar apenas esse nó como inelegível. Não modifique o status do parceiro de HA.

Se o nó parceiro for selecionado como o novo mestre, você precisa verificar se ele detém epsilon antes de torná-lo inelegível. Se o nó parceiro detiver epsilon, você precisa mover epsilon para outro nó que permaneça no cluster antes de torná-lo inelegível. Você faz isso ao repetir estas etapas para remover o nó parceiro.

====
.. Torne o nó principal anterior elegível para participar novamente no cluster:
+
[source, cli]
----
cluster modify -node <node_name> -eligibility true
----


. Faça login na LIF de gerenciamento de nó remoto ou na LIF de gerenciamento de cluster em um nó que você não está removendo do cluster.
. Remova os nós do cluster:
+
|===
| Para esta versão ONTAP... | Use este comando... 


 a| 
ONTAP 9,3
 a| 
[source, cli]
----
cluster unjoin
----


 a| 
ONTAP 9 .4 e mais tarde
 a| 
Com nome do nó:

[source, cli]
----
cluster remove-node -node <node_name>
----
Com IP do nó:

[source, cli]
----
cluster remove-node -cluster_ip <node_ip>
----
|===
+
Se você tiver um cluster de versão mista e estiver removendo o último nó de versão inferior, use o `-skip-last-low-version-node-check` parâmetro com esses comandos.

+
O sistema informa-o do seguinte:

+
** Você também deve remover o parceiro de failover do nó do cluster.
** Após o nó ser removido e antes que ele possa se juntar novamente a um cluster, você deve usar a opção do menu de inicialização *(4) Limpar configuração e inicializar todos os discos* ou a opção *(9) Configurar particionamento avançado de unidade* para apagar a configuração do nó e inicializar todos os discos.
+
Uma mensagem de falha é gerada se você tiver condições que devem ser endereçadas antes de remover o nó. Por exemplo, a mensagem pode indicar que o nó tem recursos compartilhados que você deve remover ou que o nó está em uma configuração de HA de cluster ou configuração de failover de storage que você deve desativar.

+
Se o nó for o mestre do quórum, o cluster perderá brevemente e retornará ao quórum. Essa perda de quorum é temporária e não afeta nenhuma operação de dados.



. Se uma mensagem de falha indicar condições de erro, aborde essas condições e execute novamente o `cluster remove-node` comando ou `cluster unjoin`.
+
O nó reinicia automaticamente após ser removido com sucesso do cluster.

. Se você estiver reutilizando o nó, apague a configuração do nó e inicialize todos os discos:
+
.. Durante o processo de inicialização, pressione Ctrl-C para exibir o menu de inicialização quando solicitado a fazê-lo.
.. Selecione a opção do menu de inicialização *(4) Limpar configuração e inicializar todos os discos*.


. [[return-admin]]Retornar ao nível de privilégio de admin:
+
[source, cli]
----
set -privilege admin
----
. Repita os passos <<disable-ha,1>> a <<return-admin,9>> para remover o parceiro de failover do cluster.


.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/cluster-remove-node.html["nó de remoção do cluster"^]

