---
permalink: system-admin/set-display-preferences-task.html 
sidebar: sidebar 
keywords: set, display, preferences, cli, session, set, rows 
summary: Você pode definir preferências de exibição para uma sessão CLI usando o comando SET e linhas . As preferências definidas aplicam-se apenas à sessão em que se encontra. Elas não são persistentes em todas as sessões. 
---
= Defina as preferências de exibição para a CLI do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode definir preferências de exibição para uma sessão CLI usando o `set` comando e `rows` o comando. As preferências definidas aplicam-se apenas à sessão em que se encontra. Elas não são persistentes em todas as sessões.

.Sobre esta tarefa
Você pode definir as seguintes preferências de exibição da CLI:

* O nível de privilégio da sessão de comando
* Se as confirmações são emitidas para comandos potencialmente disruptivos
* Se `show` os comandos exibem todos os campos
* O caractere ou carateres a serem usados como separador de campo
* A unidade padrão ao relatar tamanhos de dados
* O número de linhas que a tela exibe na sessão atual da CLI antes que a interface interrompa a saída
+
Se o número preferido de linhas não for especificado, ele será ajustado automaticamente com base na altura real do terminal. Se a altura real for indefinida, o número padrão de linhas é 24.

* O nó ou a máquina virtual de storage padrão (SVM)
* Se um comando contínuo deve parar se encontrar um erro


.Passos
. Para definir preferências de exibição da CLI, use o `set` comando.
+
Para definir o número de linhas que a tela exibe na sessão atual da CLI, você também pode usar o `rows` comando.

+
Saiba mais sobre `set` e `rows` no link:https://docs.netapp.com/us-en/ontap-cli/["Referência do comando ONTAP"^].



.Exemplo de configuração de preferências de exibição na CLI
O exemplo a seguir define uma vírgula para ser o separador de campos, define `GB` como a unidade padrão de tamanho de dados e define o número de linhas como 50:

[listing]
----
cluster1::> set -showseparator "," -units GB
cluster1::> rows 50
----
.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=show["mostrar"^]
* link:https://docs.netapp.com/us-en/ontap-cli/set.html["definir"^]
* link:https://docs.netapp.com/us-en/ontap-cli/rows.html["linhas"^]

