---
permalink: system-admin/sp-bmc-network-interface--firmware-updates-concept.html 
sidebar: sidebar 
keywords: sp, bmc, network, interface, firmware, update 
summary: Uma atualização de firmware do SP que é acionada a partir do ONTAP com o SP executando a versão 1,5, 2,5, 3,1 ou posterior suporta o uso de um mecanismo de transferência de arquivos baseado em IP através da interface de rede SP. 
---
= Utilização de ONTAP SP/BMC e interface de rede para atualizações de firmware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Uma atualização de firmware do SP que é acionada a partir do ONTAP com o SP executando a versão 1,5, 2,5, 3,1 ou posterior suporta o uso de um mecanismo de transferência de arquivos baseado em IP através da interface de rede SP.

[NOTE]
====
Este tópico aplica-se tanto ao SP como ao BMC.

====
Uma atualização de firmware do SP através da interface de rede é mais rápida do que uma atualização através da interface serial. Ele reduz a janela de manutenção durante a qual o firmware do SP está sendo atualizado e também não causa interrupções na operação do ONTAP. As versões do SP que suportam esse recurso estão incluídas no ONTAP. Eles também estão disponíveis no site de suporte da NetApp e podem ser instalados em controladores que executam uma versão compatível do ONTAP.

Quando você estiver executando o SP versão 1,5, 2,5, 3,1 ou posterior, os seguintes comportamentos de atualização de firmware se aplicam:

* Uma atualização de firmware do SP que é _automaticamente_ acionada pelo ONTAP usa a interface de rede para a atualização; no entanto, a atualização automática do SP muda para usar a interface serial para a atualização de firmware se ocorrer uma das seguintes condições:
+
** A interface de rede SP não está configurada ou não está disponível.
** A transferência de arquivos baseada em IP falha.
** O serviço de API do SP está desativado.




Independentemente da versão do SP que você está executando, uma atualização de firmware do SP acionada a partir da CLI do SP sempre usa a interface de rede do SP para a atualização.

.Informações relacionadas
https://mysupport.netapp.com/site/downloads/firmware/system-firmware-diagnostics["Downloads do NetApp: Firmware e Diagnóstico do sistema"^]
