---
permalink: system-admin/structure-autosupport-messages-sent-email-concept.html 
sidebar: sidebar 
keywords: structure, autosupport, messages, sent, email, subject, standard, brief, body, large, attachment, 7z, file, data 
summary: Quando uma mensagem AutoSupport é enviada por e-mail, a mensagem tem um assunto padrão, um corpo breve e um anexo grande em formato de arquivo 7z que contém os dados. 
---
= Saiba mais sobre a estrutura das mensagens do ONTAP AutoSupport enviadas por e-mail
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando uma mensagem AutoSupport é enviada por e-mail, a mensagem tem um assunto padrão, um corpo breve e um anexo grande em formato de arquivo 7z que contém os dados.

[NOTE]
====
Se o AutoSupport estiver configurado para ocultar dados privados, certas informações, como o nome do host, serão omitidas ou mascaradas no cabeçalho, assunto, corpo e anexos.

====


== Assunto

A linha de assunto das mensagens enviadas pelo mecanismo AutoSupport contém uma cadeia de texto que identifica o motivo da notificação. O formato da linha de assunto é o seguinte:

Notificação de Grupo HA de _Nome_do_sistema_ (_mensagem_) _gravidade_

* _Nome_do_sistema_ é o nome do host ou o ID do sistema, dependendo da configuração do AutoSupport




== Corpo

O corpo da mensagem AutoSupport contém as seguintes informações:

* Data e carimbo de data/hora da mensagem
* Versão do ONTAP no nó que gerou a mensagem
* ID do sistema, número de série e nome do host do nó que gerou a mensagem
* Número de sequência AutoSupport
* Nome e localização do contacto SNMP, se especificado
* ID do sistema e nome do host do partnernode HA




== Ficheiros anexados

As informações-chave de uma mensagem AutoSupport estão contidas em arquivos compatados em um arquivo 7z chamado `body.7z` e anexado à mensagem.

Os arquivos contidos no anexo são específicos para o tipo de mensagem AutoSupport.
