---
permalink: system-admin/system-volumes-concept.html 
sidebar: sidebar 
keywords: system, volume, flexvol, metadata, file, services, audit, logs, account, storage, cluster 
summary: Os volumes do sistema são volumes do FlexVol que contêm metadados especiais, como metadados para logs de auditoria de serviços de arquivo. Esses volumes ficam visíveis no cluster para que você possa considerar totalmente o uso do storage no cluster. 
---
= Quais são os volumes do sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os volumes do sistema são volumes do FlexVol que contêm metadados especiais, como metadados para logs de auditoria de serviços de arquivo. Esses volumes ficam visíveis no cluster para que você possa considerar totalmente o uso do storage no cluster.

Os volumes de sistema pertencem ao servidor de gerenciamento de cluster (também chamado de administrador SVM) e são criados automaticamente quando a auditoria de serviços de arquivos é ativada.

Você pode visualizar volumes do sistema usando o `volume show` comando, mas a maioria das outras operações de volume não são permitidas. Por exemplo, você não pode modificar um volume de sistema usando o `volume modify` comando.

Este exemplo mostra quatro volumes de sistema no SVM admin, que foram criados automaticamente quando a auditoria de serviços de arquivo foi ativada para um SVM de dados no cluster:

[listing]
----
cluster1::> volume show -vserver cluster1
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
cluster1  MDV_aud_1d0131843d4811e296fc123478563412
                       aggr0        online     RW          2GB     1.90GB    5%
cluster1  MDV_aud_8be27f813d7311e296fc123478563412
                       root_vs0     online     RW          2GB     1.90GB    5%
cluster1  MDV_aud_9dc4ad503d7311e296fc123478563412
                       aggr1        online     RW          2GB     1.90GB    5%
cluster1  MDV_aud_a4b887ac3d7311e296fc123478563412
                       aggr2        online     RW          2GB     1.90GB    5%
4 entries were displayed.
----