---
permalink: system-admin/system-health-monitoring-concept.html 
sidebar: sidebar 
keywords: monitor, health, system, cluster, conditions, alert, fault, risk, degraded, status, active 
summary: Os monitores de integridade monitoram proativamente certas condições críticas no cluster e emitem alertas se detetarem uma falha ou risco. Se existirem alertas ativos, o estado de funcionamento do sistema comunica um estado degradado para o cluster. Os alertas incluem as informações de que você precisa para responder à integridade degradada do sistema. 
---
= Saiba mais sobre o monitoramento de integridade do sistema ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Os monitores de integridade monitoram proativamente certas condições críticas no cluster e emitem alertas se detetarem uma falha ou risco. Se existirem alertas ativos, o estado de funcionamento do sistema comunica um estado degradado para o cluster. Os alertas incluem as informações de que você precisa para responder à integridade degradada do sistema.

Se o estado estiver degradado, pode visualizar detalhes sobre o problema, incluindo a causa provável e as ações de recuperação recomendadas. Depois de resolver o problema, o estado de funcionamento do sistema regressa automaticamente a OK.

O status de integridade do sistema reflete vários monitores de integridade separados. Um status degradado em um monitor de integridade individual causa um status degradado para a integridade geral do sistema.

Para obter detalhes sobre como o ONTAP suporta switches de cluster para monitoramento de integridade do sistema em seu cluster, consulte _Hardware Universe_.

https://hwu.netapp.com/SWITCH/INDEX["Switches suportados no Hardware Universe"^]

Para obter detalhes sobre as causas das mensagens do AutoSupport do Monitor de integridade do comutador de cluster (CSHM) e as ações necessárias para resolver esses alertas, consulte o artigo da base de conhecimento.

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/AutoSupport_Message%3A_Health_Monitor_Process_CSHM["Mensagem do AutoSupport: Processo do monitor de saúde CSHM"]
