---
permalink: system-admin/types-svms-concept.html 
sidebar: sidebar 
keywords: types, svm, data, acces, resources, admin, node, system 
summary: Um cluster consiste em quatro tipos de SVMs, que ajudam a gerenciar o cluster e seus recursos e acesso a dados aos clientes e aplicações. 
---
= Tipos de SVMs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um cluster consiste em quatro tipos de SVMs, que ajudam a gerenciar o cluster e seus recursos e acesso a dados aos clientes e aplicações.

Um cluster contém os seguintes tipos de SVMs:

* SVM admin
+
O processo de configuração do cluster cria automaticamente o administrador SVM para o cluster. O SVM admin representa o cluster.

* SVM de nó
+
Um nó SVM é criado quando o nó se junta ao cluster e o nó SVM representa os nós individuais do cluster.

* SVM do sistema (avançado)
+
Um SVM do sistema é criado automaticamente para comunicações no nível do cluster em um espaço IPspace.

* Data SVM
+
Um data SVM representa os dados que atendem SVMs. Após a configuração do cluster, um administrador de cluster deve criar SVMs de dados e adicionar volumes a essas SVMs para facilitar o acesso aos dados a partir do cluster.

+
Um cluster precisa ter pelo menos um SVM de dados para servir dados a seus clientes.



[NOTE]
====
Salvo especificação em contrário, o termo SVM se refere a um SVM de dados (fornecimento de dados).

Na CLI, os SVMs são exibidos como VServers.

====