---
permalink: system-admin/upload-performance-archive-files-task.html 
sidebar: sidebar 
keywords: upload, performance, archive, files, autosupport, message, technical 
summary: Você pode gerar e enviar uma mensagem do AutoSupport que contenha um arquivo de desempenho. Por padrão, o suporte técnico da NetApp recebe a mensagem AutoSupport e o arquivo de desempenho é carregado no site de suporte da NetApp. Você pode especificar um destino alternativo para a mensagem e upload. 
---
= Carregar ficheiros de arquivo de desempenho do ONTAP AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode gerar e enviar uma mensagem do AutoSupport que contenha um arquivo de desempenho. Por padrão, o suporte técnico da NetApp recebe a mensagem AutoSupport e o arquivo de desempenho é carregado no site de suporte da NetApp. Você pode especificar um destino alternativo para a mensagem e upload.

.Antes de começar
* Você deve ter configurado o AutoSupport com as seguintes configurações:
+
** O AutoSupport está ativado no nó.
** O AutoSupport está configurado para enviar mensagens ao suporte técnico.
** O AutoSupport está configurado para utilizar o protocolo de transporte HTTPS.
+
O protocolo de transporte SMTP não é suportado ao enviar mensagens que incluam arquivos grandes, como arquivos de arquivo de desempenho.





.Sobre esta tarefa
Tem de especificar uma data de início para os dados de arquivo de desempenho que pretende carregar. A maioria dos sistemas de storage mantém arquivos de performance por duas semanas, permitindo que você especifique uma data de início há até duas semanas. Por exemplo, se hoje é 15 de janeiro, você pode especificar uma data de início de 2 de janeiro.

.Passo
. Gere uma mensagem AutoSupport e carregue o arquivo de arquivo de desempenho usando o `system node autosupport invoke-performance-archive` comando.
+
No exemplo a seguir, 4 horas de arquivos de arquivamento de desempenho de 12 de janeiro de 2015 são adicionados a uma mensagem do AutoSupport e carregados para o local padrão, que é o site de suporte do NetApp:

+
[listing]
----
cluster1::> system node autosupport invoke-performance-archive -node local -start-date 1/12/2015 13:42:09 -duration 4h
----
+
No exemplo a seguir, 4 horas de arquivos de arquivo de desempenho a partir de 12 de janeiro de 2015 são adicionados a uma mensagem AutoSupport e carregados para o local especificado pelo URI:

+
[listing]
----
cluster1::> system node autosupport invoke-performance-archive -node local -start-date 1/12/2015 13:42:09 -duration 4h -uri https://files.company.com
----

