---
permalink: system-admin/verify-identity-remote-servers-certificates-concept.html 
sidebar: sidebar 
keywords: verify, identity, remote, servers, certificate 
summary: O ONTAP suporta recursos de certificado de segurança para verificar a identidade de servidores remotos. 
---
= Verifique a identidade de servidores remotos usando a visão geral de certificados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O ONTAP suporta recursos de certificado de segurança para verificar a identidade de servidores remotos.

O software ONTAP permite conexões seguras usando esses recursos e protocolos de certificado digital:

* O OCSP (Online Certificate Status Protocol) valida o status de solicitações de certificados digitais de serviços ONTAP usando conexões SSL e TLS (Transport Layer Security). Esta funcionalidade está desativada por predefinição.
* Um conjunto padrão de certificados raiz confiáveis é incluído no software ONTAP.
* Os certificados KMIP (Key Management Interoperability Protocol) permitem a autenticação mútua de um cluster e de um servidor KMIP.

