---
permalink: system-admin/view-default-certificates-tls-based-applications-task.html 
sidebar: sidebar 
keywords: view, default, certificates, tls, applications, transport 
summary: 'A partir do ONTAP 9.2, o ONTAP fornece um conjunto padrão de certificados raiz confiáveis para aplicativos ONTAP usando a Segurança da camada de Transporte (TLS).' 
---
= Exibir certificados padrão para aplicativos baseados em TLS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.2, o ONTAP fornece um conjunto padrão de certificados raiz confiáveis para aplicativos ONTAP usando a Segurança da camada de Transporte (TLS).

.Antes de começar
Os certificados padrão são instalados somente no SVM do administrador durante sua criação ou durante uma atualização para o ONTAP 9.2.

.Sobre esta tarefa
Os aplicativos atuais que atuam como cliente e exigem validação de certificado são AutoSupport, EMS, LDAP, Registro de auditoria, FabricPool e KMIP.

Quando os certificados expiram, é invocada uma mensagem EMS que solicita ao utilizador que elimine os certificados. Os certificados padrão só podem ser excluídos no nível avançado de privilégio.

[NOTE]
====
A exclusão dos certificados padrão pode resultar em alguns aplicativos do ONTAP não funcionarem como esperado (por exemplo, AutoSupport e Registro de auditoria).

====
.Passo
. Você pode exibir os certificados padrão instalados no SVM do administrador usando o comando show do certificado de segurança:
+
`*security certificate show -vserver –type server-ca*`

+
[listing]
----
cluster1::> security certificate show

Vserver    Serial Number   Certificate Name                          Type
---------- --------------- ----------------------------------------- ---------
vs0        4F4E4D7B         www.example.com                            server
    Certificate Authority:  www.example.com
          Expiration Date: Thu Feb 28 16:08:28 2013
----

