---
permalink: authentication/change-login-password-task.html 
sidebar: sidebar 
keywords: reset password, administrator, security login password 
summary: Você deve alterar sua senha inicial imediatamente após fazer login no sistema pela primeira vez. 
---
= Altere uma senha de administrador do ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você deve alterar sua senha inicial imediatamente após fazer login no sistema pela primeira vez. Se você for um administrador SVM, poderá usar o `security login password` comando para alterar sua própria senha. Se for um administrador de cluster, pode utilizar o `security login password` comando para alterar a palavra-passe de qualquer administrador.

.Sobre esta tarefa
A nova palavra-passe deve respeitar as seguintes regras:

* Não pode conter o nome de utilizador
* Deve ter pelo menos oito carateres
* Deve conter pelo menos uma letra e um número
* Não pode ser o mesmo que as últimas seis senhas



NOTE: Você pode usar o `security login role config modify` comando para modificar as regras de senha para contas associadas a uma determinada função.

.Antes de começar
* Você deve ser um administrador de cluster ou SVM para alterar sua própria senha.
* Você deve ser um administrador de cluster para alterar a senha de outro administrador.


.Passo
. Alterar uma palavra-passe de administrador: `security login password -vserver _svm_name_ -username _user_name_`
+
O comando a seguir altera a senha do administrador `admin1` do SVM``vs1.example.com``. É-lhe pedido que introduza a palavra-passe atual e, em seguida, introduza e volte a introduzir a nova palavra-passe.

+
[listing]
----
vs1.example.com::>security login password -vserver engData -username admin1
Please enter your current password:
Please enter a new password:
Please enter it again:
----


.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap-cli/security-login-role-config-modify.html["modificar configuração de função de login de segurança"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-login-password.html["senha de login de segurança"^]

