---
permalink: authentication/configure-cisco-duo-mfa-task.html 
sidebar: sidebar 
keywords: enable, ssh, multifactor authentication, mfa, 2fa, hardware authentication device, Cisco, Duo 
summary: 'Para aproveitar o aumento da segurança da conta por meio da autenticação de dois fatores (2FA) com o Cisco Duo para SSH, você deve configurar o SSH para uso do Cisco Duo.' 
---
= Configure o Cisco Duo 2FA para logins SSH com o ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir do ONTAP 9.14,1, você pode configurar o ONTAP para usar o Cisco Duo para autenticação de dois fatores (2FA) durante logins SSH. Você configura o Duo no nível do cluster e se aplica a todas as contas de usuário por padrão. Como alternativa, você pode configurar o Duo no nível da VM de armazenamento (anteriormente chamado de vserver), caso em que ele se aplica apenas aos usuários dessa VM de armazenamento. Se você ativar e configurar o Duo, ele serve como um método de autenticação adicional, complementando os métodos existentes para todos os usuários.

Se você ativar a autenticação Duo para logins SSH, os usuários precisarão Registrar um dispositivo na próxima vez que fizerem login usando SSH. Para obter informações sobre a inscrição, consulte o Cisco https://guide.duo.com/add-device["documentação de inscrição"^] Duo .

Você pode usar a interface de linha de comando ONTAP para executar as seguintes tarefas com o Cisco Duo:

* <<Configure o Cisco Duo>>
* <<Altere a configuração do Cisco Duo>>
* <<Remova a configuração do Cisco Duo>>
* <<Veja a configuração do Cisco Duo>>
* <<Remova um grupo Duo>>
* <<Ver grupos Duo>>
* <<Ignorar a autenticação Duo para usuários>>




== Configure o Cisco Duo

Você pode criar uma configuração do Cisco Duo para todo o cluster ou para uma VM de armazenamento específica (chamada de vserver na CLI do ONTAP) usando o[`security login duo create` comando. Quando você faz isso, o Cisco Duo é habilitado para logins SSH para esse cluster ou VM de armazenamento. Saiba mais sobre o[`security login duo create` comando ONTAP na referência de comando.

.Passos
. Inicie sessão no Painel de Administração do Cisco Duo.
. Aceda a *aplicações > aplicação UNIX*.
. Registre sua chave de integração, chave secreta e nome de host da API.
. Faça login na sua conta ONTAP usando SSH.
. Ative a autenticação do Cisco Duo para esta VM de armazenamento, substituindo as informações do seu ambiente pelos valores entre parênteses:
+
[source, cli]
----
security login duo create \
-vserver <STORAGE_VM_NAME> \
-integration-key <INTEGRATION_KEY> \
-secret-key <SECRET_KEY> \
-apihost <API_HOSTNAME>
----




== Altere a configuração do Cisco Duo

Você pode alterar a maneira como o Cisco Duo autentica os usuários (por exemplo, quantos prompts de autenticação são fornecidos ou qual proxy HTTP é usado). Se você precisar alterar a configuração do Cisco Duo para uma VM de armazenamento (chamada de vserver na CLI do ONTAP), use o[`security login duo modify` comando. Saiba mais sobre o[`security login duo modify` comando ONTAP na referência de comando.

.Passos
. Inicie sessão no Painel de Administração do Cisco Duo.
. Aceda a *aplicações > aplicação UNIX*.
. Registre sua chave de integração, chave secreta e nome de host da API.
. Faça login na sua conta ONTAP usando SSH.
. Altere a configuração do Cisco Duo para esta VM de armazenamento, substituindo as informações atualizadas do seu ambiente pelos valores entre parênteses:
+
[source, cli]
----
security login duo modify \
-vserver <STORAGE_VM_NAME> \
-integration-key <INTEGRATION_KEY> \
-secret-key <SECRET_KEY> \
-apihost <API_HOSTNAME> \
-pushinfo true|false \
-http-proxy <HTTP_PROXY_URL> \
-autopush true|false \
-max-prompts 1|2|3 \
-is-enabled true|false \
-fail-mode safe|secure
----




== Remova a configuração do Cisco Duo

Você pode remover a configuração do Cisco Duo, que removerá a necessidade de os usuários SSH se autenticarem usando o Duo no início de sessão. Para remover a configuração do Cisco Duo para uma VM de armazenamento (conhecida como vserver na CLI do ONTAP), você pode usar o[`security login duo delete` comando. Saiba mais sobre o[`security login duo delete` comando ONTAP na referência de comando.

.Passos
. Faça login na sua conta ONTAP usando SSH.
. Remova a configuração do Cisco Duo para esta VM de armazenamento, substituindo o nome da VM de armazenamento por `<STORAGE_VM_NAME>`:
+
[source, cli]
----
security login duo delete  -vserver <STORAGE_VM_NAME>
----
+
Isso exclui permanentemente a configuração do Cisco Duo para essa VM de armazenamento.





== Veja a configuração do Cisco Duo

Você pode exibir a configuração existente do Cisco Duo para uma VM de armazenamento (chamada de vserver na CLI do ONTAP) usando o[`security login duo show` comando. Saiba mais sobre o[`security login duo show` comando ONTAP na referência de comando.

.Passos
. Faça login na sua conta ONTAP usando SSH.
. Mostrar a configuração do Cisco Duo para esta VM de armazenamento. Opcionalmente, você pode usar o `vserver` parâmetro para especificar uma VM de armazenamento, substituindo o nome da VM de armazenamento por `<STORAGE_VM_NAME>`:
+
[source, cli]
----
security login duo show -vserver <STORAGE_VM_NAME>
----
+
Você deve ver saída semelhante ao seguinte:

+
[source, cli]
----
Vserver: testcluster
Enabled: true

Status: ok
INTEGRATION-KEY: DI89811J9JWMJCCO7IOH
SKEY SHA Fingerprint:
b79ffa4b1c50b1c747fbacdb34g671d4814
API Host: api-host.duosecurity.com
Autopush: true
Push info: true
Failmode: safe
Http-proxy: 192.168.0.1:3128
Prompts: 1
Comments: -
----




== Crie um grupo Duo

Você pode instruir o Cisco Duo a incluir somente os usuários em um determinado ative Directory, LDAP ou grupo de usuários local no processo de autenticação Duo. Se você criar um grupo Duo, somente os usuários desse grupo serão solicitados a autenticação Duo. Você pode criar um grupo Duo usando o[`security login duo group create` comando. Quando você cria um grupo, você pode excluir usuários específicos desse grupo do processo de autenticação Duo. Saiba mais sobre o[`security login duo group create` comando ONTAP na referência de comando.

.Passos
. Faça login na sua conta ONTAP usando SSH.
. Crie o grupo Duo, substituindo as informações do seu ambiente pelos valores entre parênteses. Se você omitir o `-vserver` parâmetro, o grupo será criado no nível do cluster:
+
[source, cli]
----
security login duo group create -vserver <STORAGE_VM_NAME> -group-name <GROUP_NAME> -excluded-users <USER1, USER2>
----
+
O nome do grupo Duo tem de corresponder a um grupo ative Directory, LDAP ou local. Os usuários que você especificar com o parâmetro opcional `-excluded-users` não serão incluídos no processo de autenticação Duo.





== Ver grupos Duo

Você pode exibir entradas de grupo existentes do Cisco Duo usando o[`security login duo group show` comando. Saiba mais sobre o[`security login duo group show` comando ONTAP na referência de comando.

.Passos
. Faça login na sua conta ONTAP usando SSH.
. Mostre as entradas do grupo Duo, substituindo as informações do seu ambiente pelos valores entre parênteses. Se você omitir o `-vserver` parâmetro, o grupo será mostrado no nível do cluster:
+
[source, cli]
----
security login duo group show -vserver <STORAGE_VM_NAME> -group-name <GROUP_NAME> -excluded-users <USER1, USER2>
----
+
O nome do grupo Duo tem de corresponder a um grupo ative Directory, LDAP ou local. Os usuários que você especificar com o parâmetro opcional `-excluded-users` não serão exibidos.





== Remova um grupo Duo

Você pode remover uma entrada de grupo Duo usando o[`security login duo group delete` comando. Se você remover um grupo, os usuários desse grupo não serão mais incluídos no processo de autenticação Duo. Saiba mais sobre o[`security login duo group delete` comando ONTAP na referência de comando.

.Passos
. Faça login na sua conta ONTAP usando SSH.
. Remova a entrada do grupo Duo, substituindo as informações do ambiente pelos valores entre parênteses. Se você omitir o `-vserver` parâmetro, o grupo será removido no nível do cluster:
+
[source, cli]
----
security login duo group delete -vserver <STORAGE_VM_NAME> -group-name <GROUP_NAME>
----
+
O nome do grupo Duo tem de corresponder a um grupo ative Directory, LDAP ou local.





== Ignorar a autenticação Duo para usuários

Você pode excluir todos os usuários ou usuários específicos do processo de autenticação Duo SSH.



=== Excluir todos os usuários Duo

Você pode desativar a autenticação SSH do Cisco Duo para todos os usuários.

.Passos
. Faça login na sua conta ONTAP usando SSH.
. Desative a autenticação Cisco Duo para usuários SSH, substituindo o nome do SVM para `<STORAGE_VM_NAME>`:
+
[source, cli]
----
security login duo modify -vserver <STORAGE_VM_NAME> -is-enabled false
----




=== Excluir usuários do grupo Duo

Você pode excluir certos usuários que fazem parte de um grupo Duo do processo de autenticação Duo SSH.

.Passos
. Faça login na sua conta ONTAP usando SSH.
. Desative a autenticação Cisco Duo para usuários específicos em um grupo. Substitua o nome do grupo e a lista de usuários para excluir pelos valores entre parênteses:
+
[source, cli]
----
security login duo group modify -group-name <GROUP_NAME> -excluded-users <USER1, USER2>
----
+
O nome do grupo Duo tem de corresponder a um grupo ative Directory, LDAP ou local. Os usuários que você especificar com o `-excluded-users` parâmetro não serão incluídos no processo de autenticação Duo.





=== Excluir usuários locais Duo

Você pode excluir usuários locais específicos do uso da autenticação Duo usando o Painel de Administração do Cisco Duo. Para obter instruções, consulte https://duo.com/docs/administration-users#changing-user-status["Documentação do Cisco Duo"^] a .
