---
permalink: authentication/enable-password-account-access-task.html 
sidebar: sidebar 
keywords: enable, password, account, access 
summary: Você pode usar o comando security login create para permitir que as contas de administrador acessem um administrador ou data SVM com uma senha. Você será solicitado a digitar a senha depois de digitar o comando. 
---
= Ativar acesso à conta de palavra-passe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode usar o `security login create` comando para habilitar contas de administrador para acessar um administrador ou data SVM com uma senha. Você será solicitado a digitar a senha depois de digitar o comando. Saiba mais sobre `security login create` o link:https://docs.netapp.com/us-en/ontap-cli/security-login-create.html["Referência do comando ONTAP"^]na .

.Sobre esta tarefa
Se você não tiver certeza da função de controle de acesso que deseja atribuir à conta de login, use o `security login modify` comando para adicionar a função mais tarde.

.Antes de começar
Você deve ser um administrador de cluster para executar esta tarefa.

.Passo
. Ative as contas de administrador locais para acessar um SVM usando uma senha:
+
`security login create -vserver _SVM_name_ -user-or-group-name _user_or_group_name_ -application _application_ -authmethod _authentication_method_ -role _role_ -comment _comment_`

+
O comando a seguir habilita a conta de administrador de cluster `admin1` com a função predefinida `backup` para acessar o SVM de administrador``engCluster`` usando uma senha. Você será solicitado a digitar a senha depois de digitar o comando.

+
[listing]
----
cluster1::>security login create -vserver engCluster -user-or-group-name admin1 -application ssh -authmethod password -role backup
----

