---
permalink: authentication/index.html 
sidebar: sidebar 
keywords: decide, overview, administrator, authentication, rbac, role-based, access, control 
summary: 'Você pode habilitar contas de login para administradores de cluster do ONTAP e administradores de máquina virtual de storage (SVM). Você também pode usar o controle de acesso baseado em função (RBAC) para definir as funcionalidades dos administradores.' 
---
= Saiba mais sobre a autenticação de administrador e o RBAC no ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode habilitar contas de login para administradores de cluster do ONTAP e administradores de máquina virtual de storage (SVM). Você também pode usar o controle de acesso baseado em função (RBAC) para definir as funcionalidades dos administradores.

Você pode habilitar contas de administrador locais para acessar uma máquina virtual de storage de administrador (SVM) ou um data SVM com os seguintes tipos de autenticação:

* link:enable-password-account-access-task.html["Palavra-passe"]
* link:enable-ssh-public-key-accounts-task.html["Chave pública SSH"]
* link:enable-ssl-certificate-accounts-task.html["Certificado SSL"]
* link:mfa-overview.html["Autenticação multifator SSH (MFA)"]
+
A partir do ONTAP 9.3, a autenticação com senha e chave pública é suportada.



Você pode habilitar contas de administrador remoto para acessar um SVM admin ou um SVM de dados com os seguintes tipos de autenticação:

* link:grant-access-active-directory-users-groups-task.html["Ative Directory"]
+
A partir do ONTAP 9.13.1, você pode usar uma chave pública SSH como seu método de autenticação principal ou secundário para um usuário do ative Directory.

* link:../system-admin/configure-saml-authentication-task.html["Autenticação SAML (somente para SVM de administrador)"]
+
A partir do ONTAP 9.3, a autenticação SAML (Security Assertion Markup Language) pode ser usada para acessar o SVM admin usando qualquer um dos seguintes serviços da Web: Infraestrutura do processador de serviços, APIs ONTAP ou Gerenciador de sistemas.

* link:grant-access-nis-ldap-user-accounts-task.html["LDAP ou NIS"]
+
A partir do ONTAP 9.4, o SSH MFA pode ser usado para usuários remotos em servidores LDAP ou NIS. A autenticação com nsswitch e chave pública é suportada.


