---
permalink: authentication/manage-failed-login-attempts-reference.html 
sidebar: sidebar 
keywords: manage, failed, login, attempts 
summary: Tentativas repetidas de login falhadas às vezes indicam que um intruso está tentando acessar o sistema de armazenamento. Você pode executar várias etapas para garantir que não ocorra uma intrusão. 
---
= Gerir tentativas de início de sessão falhadas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tentativas repetidas de login falhadas às vezes indicam que um intruso está tentando acessar o sistema de armazenamento. Você pode executar várias etapas para garantir que não ocorra uma intrusão.



== Como você saberá que as tentativas de login falharam

O sistema de Gestão de Eventos (EMS) notifica-o sobre tentativas falhadas de início de sessão a cada hora. Pode encontrar um registo de tentativas de início de sessão falhadas `audit.log` no ficheiro.



== O que fazer se tentativas repetidas de login falharem

A curto prazo, você pode executar várias etapas para evitar uma intrusão:

* Exigir que as senhas sejam compostas por um número mínimo de carateres maiúsculos, minúsculos, carateres especiais e/ou dígitos
* Impor um atraso após uma tentativa de início de sessão com falha
* Limite o número de tentativas de início de sessão falhadas permitidas e bloqueie os utilizadores após o número especificado de tentativas falhadas
* Expire e bloqueie contas que estejam inativas por um determinado número de dias


Você pode usar o `security login role config modify` comando para executar essas tarefas.

A longo prazo, você pode seguir estes passos adicionais:

* Use o `security ssh modify` comando para limitar o número de tentativas de login falhadas para todos os SVMs recém-criados.
* Migre contas de algoritmo MD5 existentes para o algoritmo SHA-512 mais seguro, exigindo que os usuários alterem suas senhas.

