---
permalink: authentication/manage-public-key-authentication-concept.html 
sidebar: sidebar 
keywords: associate, public key, administrator account 
summary: Para autenticação de chave pública SSH, você deve associar a chave pública a uma conta de administrador antes que a conta possa acessar o SVM. Você pode usar o comando security login publickey create para associar uma chave a uma conta de administrador. 
---
= Associar uma chave pública a uma conta de administrador
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para autenticação de chave pública SSH, você deve associar a chave pública a uma conta de administrador antes que a conta possa acessar o SVM. Você pode usar o `security login publickey create` comando para associar uma chave a uma conta de administrador.

.Sobre esta tarefa
Se você autenticar uma conta via SSH com uma senha e uma chave pública SSH, a conta será autenticada primeiro com a chave pública.

.Antes de começar
* Você deve ter gerado a chave SSH.
* Você deve ser um administrador de cluster ou SVM para executar essa tarefa.


.Passos
. Associar uma chave pública a uma conta de administrador:
+
`security login publickey create -vserver _SVM_name_ -username _user_name_ -index _index_ -publickey _certificate_ -comment _comment_`

+
Para obter a sintaxe de comando completa, consulte a referência de Planilha para link:config-worksheets-reference.html["Associar uma chave pública a uma conta de utilizador"^].

. Verifique a alteração visualizando a chave pública:
+
`security login publickey show -vserver _SVM_name_ -username _user_name_ -index _index_`



.Exemplo
O comando a seguir associa uma chave pública à conta de administrador do SVM `svmadmin1` para o `engData1` SVM . A chave pública recebe o número de índice 5.

[listing]
----
cluster1::> security login publickey create -vserver engData1 -username svmadmin1 -index 5 -publickey
"<key text>"
----