---
sidebar: sidebar 
permalink: authentication/oauth2-external-roles.html 
keywords: oauth 2.0, oauth2, external roles, external role mapping 
summary: Uma função externa é definida em um provedor de identificação configurado para uso pelo ONTAP. Você pode criar e administrar os relacionamentos de mapeamento entre essas funções externas e as funções do ONTAP usando a CLI do ONTAP. 
---
= Mapeamento de funções externas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Uma função externa é definida em um provedor de identificação configurado para uso pelo ONTAP. Você pode criar e administrar relacionamentos de mapeamento entre essas funções externas e as funções do ONTAP usando a CLI do ONTAP.


NOTE: Você também pode configurar o recurso de mapeamento de função externa usando a API REST do ONTAP. Saiba mais no https://docs.netapp.com/us-en/ontap-automation/["Documentação de automação do ONTAP"^].

.Informações relacionadas
* https://docs.netapp.com/us-en/ontap-cli/["Comandos CLI do ONTAP"^].




== Funções externas em um token de acesso

Aqui está um fragmento de um token de acesso JSON contendo dois papéis externos.

[listing]
----
  ...
  "appidacr": "1",
  "family_name": "User",
  "name": "Test User 1",
  "oid": "4c2215c7-6d52-40a7-ce71-096fa41379ba",
  "roles": [
    "Global Administrator",
    "Application Administrator"
  ],
  "ver": "1.0",
  ...
----


== Configuração

Você pode usar a interface de linha de comando ONTAP para administrar o recurso de mapeamento de função externa.



=== Criar

Você pode definir uma configuração de mapeamento de função com o `security login external-role-mapping create` comando. Você precisa estar no nível de privilégio ONTAP *admin* para emitir este comando, bem como as opções relacionadas.

.Parâmetros
Os parâmetros usados para criar um mapeamento de grupo são descritos abaixo.

[cols="30,70"]
|===
| Parâmetro | Descrição 


| `external-role` | O nome da função definida no provedor de identidade externo. 


| `provider` | O nome do provedor de identidade. Este deve ser o identificador do sistema. 


| `ontap-role` | Indica a função ONTAP existente para a qual a função externa está mapeada. 
|===
.Exemplo
[listing]
----
security login external-role-mapping create -external-role "Global Administrator" -provider entra -ontap-role admin
----


=== Operações CLI adicionais

O comando suporta várias operações adicionais, incluindo:

* Mostrar
* Modificar
* Eliminar


Consulte a documentação de referência dos comandos do ONTAP ou as páginas man da CLI do ONTAP para obter mais informações.
