---
permalink: authentication/predefined-roles-cluster-administrators-concept.html 
sidebar: sidebar 
keywords: predefined roles, cluster administrators 
summary: As funções predefinidas para administradores de cluster devem atender à maioria das suas necessidades. Você pode criar funções personalizadas conforme necessário. Por padrão, um administrador de cluster recebe a função de administrador predefinida. 
---
= Funções predefinidas para administradores de cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As funções predefinidas para administradores de cluster devem atender à maioria das suas necessidades. Você pode criar funções personalizadas conforme necessário. Por padrão, um administrador de cluster recebe a função predefinida `admin`.

A tabela a seguir lista as funções predefinidas para administradores de cluster:

|===


| Esta função... | Tem este nível de acesso... | Para os seguintes comandos ou diretórios de comandos 


 a| 
administrador
 a| 
tudo
 a| 
Todos os diretórios de comando (`DEFAULT`)



 a| 
admin-no-fsa (disponível a partir de ONTAP 9.12,1)
 a| 
Leitura/escrita
 a| 
* Todos os diretórios de comando (`DEFAULT`)
* `security login rest-role`
* `security login role`




 a| 
Somente leitura
 a| 
* `security login rest-role create`
* `security login rest-role delete`
* `security login rest-role modify`
* `security login rest-role show`
* `security login role create`
* `security login role create`
* `security login role delete`
* `security login role modify`
* `security login role show`
* `volume activity-tracking`
* `volume analytics`




 a| 
Nenhum
 a| 
`volume file show-disk-usage`



 a| 
AutoSupport
 a| 
tudo
 a| 
* `set`
* `system node autosupport`




 a| 
nenhum
 a| 
Todos os outros diretórios de comando (`DEFAULT`)



 a| 
backup
 a| 
tudo
 a| 
`vserver services ndmp`



 a| 
readonly
 a| 
`volume`



 a| 
nenhum
 a| 
Todos os outros diretórios de comando (`DEFAULT`)



 a| 
readonly
 a| 
tudo
 a| 
* `security login password`
+
Apenas para gerir a palavra-passe local da conta de utilizador e as informações das chaves

* `set`




 a| 
nenhum
 a| 
`security`



 a| 
readonly
 a| 
Todos os outros diretórios de comando (`DEFAULT`)



 a| 
SnapLock
 a| 
tudo
 a| 
* `set`
* `volume create`
* `volume modify`
* `volume move`
* `volume show`




 a| 
nenhum
 a| 
* `volume move governor`
* `volume move recommend`




 a| 
nenhum
 a| 
Todos os outros diretórios de comando (`DEFAULT`)



 a| 
nenhum
 a| 
nenhum
 a| 
Todos os diretórios de comando (`DEFAULT`)

|===

NOTE: A `autosupport` função é atribuída à conta predefinida `autosupport`, que é usada pelo AutoSupport OnDemand. O ONTAP impede que você modifique ou exclua a `autosupport` conta. O ONTAP também impede que você atribua `autosupport` a função a outras contas de usuário.
