---
permalink: authentication/reset-totp-configuration-task.html 
sidebar: sidebar 
keywords: enable, ssh, multifactor authentication, mfa, hardware authentication device 
summary: Para proteger a segurança da sua conta, se a sua chave secreta TOTP estiver comprometida ou perdida, você deve desativá-la e criar uma nova. 
---
= Repor chave secreta TOTP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para proteger a segurança da sua conta, se a sua chave secreta TOTP estiver comprometida ou perdida, você deve desativá-la e criar uma nova.



== Reponha o TOTP se a sua chave estiver comprometida

Se sua chave secreta TOTP estiver comprometida, mas você ainda tiver acesso a ela, poderá remover a chave comprometida e criar uma nova.

. Faça login na sua conta de usuário com sua senha de usuário ou chave pública SSH e sua chave secreta TOTP comprometida.
. Remova a chave secreta TOTP comprometida:
+
[source, cli]
----
security login totp delete -vserver <svm_name> -username <account_username>
----
. Crie uma nova chave secreta TOTP:
+
[source, cli]
----
security login totp create -vserver <svm_name> -username <account_username>
----
. Verifique se a configuração TOTP está ativada na sua conta:
+
[source, cli]
----
security login totp show -vserver <svm_name> -username <account_username>
----




== Reinicie o TOTP se a sua chave for perdida

Se a chave secreta TOTP for perdida, entre em Contato com o administrador de armazenamento para link:disable-totp-secret-key-task.html["tenha a chave desativada"]. Depois que sua chave for desativada, você poderá usar seu primeiro método de autenticação para fazer login e configurar um novo TOTP.

.Antes de começar
A chave secreta TOTP deve ser desativada por um administrador de armazenamento. Se não tiver uma conta de administrador de armazenamento, contacte o administrador de armazenamento para desativar a chave.

.Passos
. Depois que o segredo TOTP for desativado por um administrador de armazenamento, use seu método de autenticação principal para fazer login na sua conta local.
. Crie uma nova chave secreta TOTP:
+
[source, cli]
----
security login totp create -vserver <svm_name> -username <account_username >
----
. Verifique se a configuração TOTP está ativada na sua conta:
+
[source, cli]
----
security login totp show -vserver <svm_name> -username <account_username>
----

